import type { CheckboxProps } from "@zentauri-ui/zentauri-components/ui/checkbox";

export const CHECKBOX_APPEARANCES = [
  "default",
  "success",
  "warning",
  "error",
  "info",
  "blue",
  "cyan",
  "green",
  "lime",
  "mint",
  "ocean",
  "sapphire",
  "lavender",
  "ruby",
  "red",
  "slate",
  "zinc",
  "stone",
  "royal",
  "electric",
  "forest",
  "sunset",
  "magenta",
  "crimson",
  "aqua",
  "plum",
  "violet",
  "amber",
  "pink",
  "indigo",
] as const satisfies readonly NonNullable<CheckboxProps["appearance"]>[];

export const CHECKBOX_SIZES = [
  "sm",
  "md",
  "lg",
] as const satisfies readonly NonNullable<CheckboxProps["size"]>[];
