import type { CardProps } from "@zentauri-ui/zentauri-components/ui/card";

export { PREVIEW_SECTION_CLASS as CARD_CODE_EXAMPLES_SECTION_CLASS } from "@/components/common/Section";

export const CARD_APPEARANCES = [
  "default",
  "glass",
  "outline",
  "ghost",
  "elevated",
  "blue",
  "cyan",
  "green",
  "lime",
  "mint",
  "ocean",
  "sapphire",
  "lavender",
  "ruby",
  "red",
  "slate",
  "zinc",
  "stone",
  "royal",
  "electric",
  "forest",
  "sunset",
  "magenta",
  "crimson",
  "aqua",
  "plum",
  "sky",
  "rose",
  "purple",
  "pink",
  "orange",
  "yellow",
  "teal",
  "indigo",
  "emerald",
  "gray",
  "amber",
  "violet",
  "gradient-blue",
  "gradient-green",
  "gradient-red",
  "gradient-yellow",
  "gradient-purple",
  "gradient-teal",
  "gradient-indigo",
  "gradient-pink",
  "gradient-orange",
] as const satisfies readonly NonNullable<CardProps["appearance"]>[];

export const CARD_SIZES = [
  "sm",
  "md",
  "lg",
] as const satisfies readonly NonNullable<CardProps["size"]>[];

export const CARD_ROUNDED = [
  "sm",
  "md",
  "lg",
  "full",
] as const satisfies readonly NonNullable<CardProps["rounded"]>[];
