// Generated by packages/components/scripts/update-test-health.mjs. Do not edit by hand.
export const PACKAGE_TEST_HEALTH = {
  files: {
    total: 79,
    passed: 79,
  },
  tests: {
    total: 624,
    passed: 624,
  },
  areas: [
    {
      area: "Components and UI utilities",
      files: 47,
      tests: 452,
    },
    {
      area: "Standalone animations",
      files: 1,
      tests: 45,
    },
    {
      area: "React hooks",
      files: 28,
      tests: 101,
    },
    {
      area: "Design system facade",
      files: 1,
      tests: 11,
    },
    {
      area: "CLI and import rewriting",
      files: 2,
      tests: 15,
    },
  ],
} as const;
