// Generated by packages/components/scripts/update-test-health.mjs. Do not edit by hand.
export const PACKAGE_TEST_HEALTH = {
  files: {
    total: 159,
    passed: 159,
  },
  tests: {
    total: 1954,
    passed: 1954,
  },
  areas: [
    {
      area: "Components and UI utilities",
      files: 102,
      tests: 1503,
    },
    {
      area: "Standalone animations",
      files: 1,
      tests: 45,
    },
    {
      area: "React hooks",
      files: 48,
      tests: 242,
    },
    {
      area: "Design system facade",
      files: 1,
      tests: 22,
    },
    {
      area: "CLI and import rewriting",
      files: 4,
      tests: 43,
    },
    {
      area: "Accessibility (axe + keyboard)",
      files: 2,
      tests: 52,
    },
    {
      area: "Permission system",
      files: 1,
      tests: 47,
    },
  ],
} as const;
