// Generated by packages/components/scripts/update-test-health.mjs. Do not edit by hand.
export const PACKAGE_TEST_HEALTH = {
  files: {
    total: 91,
    passed: 91,
  },
  tests: {
    total: 671,
    passed: 671,
  },
  areas: [
    {
      area: "Components and UI utilities",
      files: 47,
      tests: 452,
    },
    {
      area: "Standalone animations",
      files: 1,
      tests: 45,
    },
    {
      area: "React hooks",
      files: 41,
      tests: 169,
    },
    {
      area: "Design system facade",
      files: 1,
      tests: 11,
    },
    {
      area: "CLI and import rewriting",
      files: 2,
      tests: 15,
    },
  ],
} as const;
