/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    section: SectionBlock;
    text: TextBlock;
    spacer: SpacerBlock;
    code: CodeBlock;
    row: RowBlock;
    accordion: AccordionBlock;
    button: ButtonBlock;
    alert: AlertBlock;
    badge: BadgeBlock;
    card: CardBlock;
    divider: DividerBlock;
    table: TableBlock;
    breadcrumb: BreadcrumbBlock;
    drawer: DrawerBlock;
    "json-viewer": JsonViewerBlock;
    kbd: KbdBlock;
    modal: ModalBlock;
    "package-install-command": PackageInstallCommandBlock;
    "qr-code": QrCodeBlock;
    "secret-reveal": SecretRevealBlock;
    tabs: TabsBlock;
    timeline: TimelineBlock;
    "tree-view": TreeViewBlock;
  };
  collections: {
    users: User;
    media: Media;
    pages: Page;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlock".
 */
export interface SectionBlock {
  /**
   * Optional anchor id for in-page links (lowercase letters, numbers, and hyphens only)
   */
  sectionId?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "section";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  appearance?:
    | (
        | "default"
        | "muted"
        | "primary"
        | "secondary"
        | "accent"
        | "destructive"
        | "info"
        | "success"
        | "warning"
        | "error"
        | "gradient-pink-violet"
        | "gradient-cyan-violet"
        | "gradient-cyan-blue"
        | "gradient-cyan-green"
        | "gradient-cyan-orange"
        | "gradient-cyan-red"
        | "gradient-cyan-purple"
        | "gradient-cyan-pink"
      )
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "text";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  height:
    | "0"
    | "4"
    | "8"
    | "12"
    | "16"
    | "20"
    | "24"
    | "32"
    | "40"
    | "48"
    | "60"
    | "64"
    | "80"
    | "90"
    | "100"
    | "120"
    | "140"
    | "160"
    | "180"
    | "200";
  id?: string | null;
  blockName?: string | null;
  blockType: "spacer";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language:
    | "typescript"
    | "tsx"
    | "javascript"
    | "jsx"
    | "css"
    | "html"
    | "json"
    | "bash"
    | "markdown"
    | "plaintext";
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: "code";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock".
 */
export interface RowBlock {
  /**
   * Each item is a flex child of the row
   */
  items: (
    | SpacerBlock
    | CodeBlock
    | AccordionBlock
    | ButtonBlock
    | AlertBlock
    | BadgeBlock
    | CardBlock
    | DividerBlock
    | TextBlock
    | TableBlock
    | BreadcrumbBlock
    | DrawerBlock
    | JsonViewerBlock
    | KbdBlock
    | ModalBlock
    | PackageInstallCommandBlock
    | QrCodeBlock
    | SecretRevealBlock
    | TabsBlock
    | TimelineBlock
    | TreeViewBlock
  )[];
  gap:
    | "0"
    | "4"
    | "8"
    | "12"
    | "16"
    | "20"
    | "24"
    | "32"
    | "40"
    | "48"
    | "60"
    | "64"
    | "80"
    | "90"
    | "100";
  /**
   * justify-content
   */
  horizontalAlign?:
    | (
        | "flex-start"
        | "center"
        | "flex-end"
        | "space-between"
        | "space-around"
        | "space-evenly"
      )
    | null;
  /**
   * align-items
   */
  verticalAlign?:
    | ("stretch" | "flex-start" | "center" | "flex-end" | "baseline")
    | null;
  /**
   * Render as a column on mobile viewports
   */
  stackOnMobile?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "row";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  accordions?:
    | {
        appearance?:
          | (
              | "default"
              | "outline"
              | "ghost"
              | "card"
              | "separated"
              | "blue"
              | "cyan"
              | "green"
              | "lime"
              | "mint"
              | "ocean"
              | "sapphire"
              | "lavender"
              | "ruby"
              | "red"
              | "slate"
              | "zinc"
              | "stone"
              | "royal"
              | "electric"
              | "forest"
              | "sunset"
              | "magenta"
              | "crimson"
              | "aqua"
              | "plum"
              | "sky"
              | "rose"
              | "purple"
              | "pink"
              | "orange"
              | "yellow"
              | "teal"
              | "indigo"
              | "emerald"
              | "gradient-blue"
              | "gradient-green"
              | "gradient-red"
              | "gradient-yellow"
              | "gradient-purple"
              | "gradient-teal"
              | "gradient-indigo"
              | "gradient-pink"
              | "gradient-orange"
            )
          | null;
        size?: ("sm" | "md" | "lg") | null;
        items: {
          /**
           * Trigger text
           */
          label: string;
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ("ltr" | "rtl") | null;
              format:
                | "left"
                | "start"
                | "center"
                | "right"
                | "end"
                | "justify"
                | "";
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "accordion";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  label: string;
  appearance?:
    | (
        | "default"
        | "secondary"
        | "destructive"
        | "outline"
        | "ghost"
        | "link"
        | "glass"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
        | "emerald"
        | "indigo"
        | "purple"
        | "pink"
        | "rose"
        | "sky"
        | "teal"
        | "yellow"
        | "orange"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
      )
    | null;
  size?:
    | (
        | "sm"
        | "md"
        | "lg"
        | "xl"
        | "2xl"
        | "3xl"
        | "4xl"
        | "5xl"
        | "6xl"
        | "7xl"
        | "8xl"
        | "9xl"
        | "10xl"
        | "icon"
      )
    | null;
  as: "button" | "link";
  href?: string | null;
  target?: ("_self" | "_blank") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "button";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AlertBlock".
 */
export interface AlertBlock {
  appearance?:
    | (
        | "default"
        | "success"
        | "warning"
        | "error"
        | "info"
        | "ghost"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "gray"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  closable?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "alert";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BadgeBlock".
 */
export interface BadgeBlock {
  label: string;
  appearance?:
    | (
        | "default"
        | "secondary"
        | "destructive"
        | "outline"
        | "ghost"
        | "glass"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
        | "emerald"
        | "indigo"
        | "purple"
        | "pink"
        | "rose"
        | "sky"
        | "teal"
        | "yellow"
        | "orange"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  shape?: ("pill" | "square" | "dot") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "badge";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock".
 */
export interface CardBlock {
  appearance?:
    | (
        | "default"
        | "glass"
        | "outline"
        | "ghost"
        | "elevated"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  rounded?: ("sm" | "md" | "lg" | "full") | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "card";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  appearance?:
    | (
        | "default"
        | "muted"
        | "primary"
        | "destructive"
        | "ghost"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  orientation?: ("horizontal" | "vertical") | null;
  /**
   * Optional label between divider lines
   */
  label?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "divider";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  appearance?:
    | (
        | "default"
        | "striped"
        | "bordered"
        | "ghost"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  textAlign?: ("left" | "center" | "right") | null;
  stickyHeader?: boolean | null;
  columns: {
    label: string;
    id?: string | null;
  }[];
  rows: {
    cells: {
      value: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "table";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BreadcrumbBlock".
 */
export interface BreadcrumbBlock {
  appearance?:
    | (
        | "default"
        | "muted"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
      )
    | null;
  items: {
    label: string;
    /**
     * Leave empty to render as the current (non-linked) page
     */
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "breadcrumb";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DrawerBlock".
 */
export interface DrawerBlock {
  triggerLabel: string;
  triggerAppearance?:
    | (
        | "default"
        | "glass"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  side?: ("left" | "right" | "top" | "bottom") | null;
  size?: ("sm" | "md" | "lg" | "xl" | "full") | null;
  contentAppearance?:
    | (
        | "default"
        | "glass"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  /**
   * Optional drawer header title
   */
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "drawer";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JsonViewerBlock".
 */
export interface JsonViewerBlock {
  appearance?: ("default" | "subtle" | "contrast" | "glass") | null;
  size?: ("sm" | "md" | "lg") | null;
  /**
   * Leave empty to expand everything
   */
  defaultExpandedDepth?: number | null;
  showToolbar?: boolean | null;
  enableClipboard?: boolean | null;
  showItemCount?: boolean | null;
  quoteStrings?: boolean | null;
  data: string;
  id?: string | null;
  blockName?: string | null;
  blockType: "json-viewer";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KbdBlock".
 */
export interface KbdBlock {
  appearance?:
    | (
        | "default"
        | "secondary"
        | "destructive"
        | "outline"
        | "ghost"
        | "glass"
        | "emerald"
        | "indigo"
        | "purple"
        | "pink"
        | "rose"
        | "sky"
        | "teal"
        | "yellow"
        | "orange"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  /**
   * Rendered between keycaps, e.g. "+"
   */
  separator?: string | null;
  keys: {
    /**
     * e.g. "⌘" or "K"
     */
    key: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "kbd";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ModalBlock".
 */
export interface ModalBlock {
  triggerLabel: string;
  triggerAppearance?:
    | (
        | "default"
        | "glass"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  size?: ("sm" | "md" | "lg" | "xl" | "full") | null;
  position?: ("center" | "top" | "bottom") | null;
  contentAppearance?:
    | (
        | "default"
        | "glass"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "amber"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  /**
   * Optional modal header title
   */
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "modal";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PackageInstallCommandBlock".
 */
export interface PackageInstallCommandBlock {
  /**
   * e.g. "react" or "react react-dom"
   */
  packageName: string;
  defaultManager?: ("npm" | "pnpm" | "yarn" | "bun") | null;
  appearance?: ("default" | "subtle" | "contrast" | "glass") | null;
  size?: ("sm" | "md" | "lg") | null;
  enableClipboard?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "package-install-command";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QrCodeBlock".
 */
export interface QrCodeBlock {
  /**
   * The URL or text to encode
   */
  value: string;
  canvasSize?: number | null;
  level?: ("L" | "M" | "Q" | "H") | null;
  margin?: number | null;
  /**
   * Background color (hex)
   */
  bgColor?: string | null;
  /**
   * Foreground color (hex)
   */
  fgColor?: string | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "qr-code";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecretRevealBlock".
 */
export interface SecretRevealBlock {
  value: string;
  appearance?:
    | (
        | "default"
        | "subtle"
        | "muted"
        | "primary"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "emerald"
        | "indigo"
        | "purple"
        | "pink"
        | "rose"
        | "sky"
        | "teal"
        | "yellow"
        | "orange"
        | "red"
        | "slate"
        | "gray"
        | "zinc"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  label?: string | null;
  labelPosition?: ("top" | "side") | null;
  /**
   * Mask character, e.g. "•"
   */
  muteChar?: string | null;
  initiallyRevealed?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "secret-reveal";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock".
 */
export interface TabsBlock {
  appearance?:
    | (
        | "default"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  variant?: ("default" | "underline" | "pills") | null;
  size?: ("sm" | "md" | "lg") | null;
  orientation?: ("horizontal" | "vertical") | null;
  tabs: {
    label: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ("ltr" | "rtl") | null;
        format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "tabs";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  appearance?:
    | (
        | "default"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gray"
        | "violet"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  items: {
    title: string;
    /**
     * Overrides the timeline's default indicator color
     */
    appearance?:
      | (
          | "default"
          | "sky"
          | "rose"
          | "purple"
          | "pink"
          | "orange"
          | "yellow"
          | "teal"
          | "indigo"
          | "emerald"
          | "gray"
          | "violet"
          | "gradient-blue"
          | "gradient-green"
          | "gradient-red"
          | "gradient-yellow"
          | "gradient-purple"
          | "gradient-teal"
          | "gradient-indigo"
          | "gradient-pink"
          | "gradient-orange"
          | "blue"
          | "cyan"
          | "green"
          | "lime"
          | "mint"
          | "ocean"
          | "sapphire"
          | "lavender"
          | "ruby"
          | "red"
          | "slate"
          | "zinc"
          | "stone"
          | "royal"
          | "electric"
          | "forest"
          | "sunset"
          | "magenta"
          | "crimson"
          | "aqua"
          | "plum"
        )
      | null;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "timeline";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TreeViewBlock".
 */
export interface TreeViewBlock {
  appearance?:
    | (
        | "default"
        | "outline"
        | "ghost"
        | "card"
        | "separated"
        | "sky"
        | "rose"
        | "purple"
        | "pink"
        | "orange"
        | "yellow"
        | "teal"
        | "indigo"
        | "emerald"
        | "gradient-blue"
        | "gradient-green"
        | "gradient-red"
        | "gradient-yellow"
        | "gradient-purple"
        | "gradient-teal"
        | "gradient-indigo"
        | "gradient-pink"
        | "gradient-orange"
        | "blue"
        | "cyan"
        | "green"
        | "lime"
        | "mint"
        | "ocean"
        | "sapphire"
        | "lavender"
        | "ruby"
        | "red"
        | "slate"
        | "zinc"
        | "stone"
        | "royal"
        | "electric"
        | "forest"
        | "sunset"
        | "magenta"
        | "crimson"
        | "aqua"
        | "plum"
      )
    | null;
  size?: ("sm" | "md" | "lg") | null;
  showGuides?: boolean | null;
  nodes: {
    label: string;
    children?:
      | {
          label: string;
          children?:
            | {
                label: string;
                children?:
                  | {
                      label: string;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "tree-view";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  _key?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * The URL slug for this page
   */
  slug: string;
  /**
   * Page content is composed of Section blocks
   */
  layout?: SectionBlock[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "pages";
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T | {};
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
