import type { OTPInputProps } from "@zentauri-ui/zentauri-components/ui/otp-input";

export const OTP_INPUT_APPEARANCES = [
  "default",
  "outline",
  "glass",
  "success",
  "error",
  "warning",
  "info",
  "violet",
  "amber",
  "pink",
  "indigo",
  "orange",
  "blue",
  "cyan",
  "green",
  "lime",
  "mint",
  "ocean",
  "sapphire",
  "lavender",
  "ruby",
  "red",
  "slate",
  "zinc",
  "stone",
  "royal",
  "electric",
  "forest",
  "sunset",
  "magenta",
  "crimson",
  "aqua",
  "plum",
] as const satisfies readonly NonNullable<OTPInputProps["appearance"]>[];

export const OTP_INPUT_SIZES = [
  "sm",
  "md",
  "lg",
] as const satisfies readonly NonNullable<OTPInputProps["size"]>[];
