export const zuiAlertBase =
  "relative flex w-full gap-3 border text-sm ring-offset-[var(--zui-alert-ring-offset,var(--zui-ring-offset,oklch(98.4%_0.003_247.858)))] dark:ring-offset-[var(--zui-alert-ring-offset-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))] transition-colors";

export const zuiAlertAppearances = {
  default:
    "border-[color:var(--zui-alert-default-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-alert-default-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-alert-default-bg,var(--zui-brand,#0000000d))] dark:bg-[var(--zui-alert-default-bg-dark,var(--zui-brand-dark,#ffffff0d))] text-[color:var(--zui-alert-default-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-default-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  success:
    "border-[color:var(--zui-alert-success-border,color-mix(in oklch, var(--zui-status-success,oklch(69.6%_0.17_162.48_/_0.4)) 40%, transparent))] dark:border-[color:var(--zui-alert-success-border-dark,color-mix(in oklch, var(--zui-status-success-dark,oklch(69.6%_0.17_162.48_/_0.4)) 40%, transparent))] bg-[var(--zui-alert-success-bg,color-mix(in oklch, var(--zui-status-success,oklch(69.6%_0.17_162.48_/_0.1)) 10%, transparent))] dark:bg-[var(--zui-alert-success-bg-dark,color-mix(in oklch, var(--zui-status-success-dark,oklch(69.6%_0.17_162.48_/_0.1)) 10%, transparent))] text-[color:var(--zui-alert-success-fg,var(--zui-status-success,oklch(26.2%_0.051_172.552)))] dark:text-[color:var(--zui-alert-success-fg-dark,var(--zui-status-success-dark,oklch(97.9%_0.021_166.113)))]",
  warning:
    "border-[color:var(--zui-alert-warning-border,color-mix(in oklch, var(--zui-status-warning,oklch(76.9%_0.188_70.08_/_0.4)) 40%, transparent))] dark:border-[color:var(--zui-alert-warning-border-dark,color-mix(in oklch, var(--zui-status-warning-dark,oklch(76.9%_0.188_70.08_/_0.4)) 40%, transparent))] bg-[var(--zui-alert-warning-bg,color-mix(in oklch, var(--zui-status-warning,oklch(76.9%_0.188_70.08_/_0.1)) 10%, transparent))] dark:bg-[var(--zui-alert-warning-bg-dark,color-mix(in oklch, var(--zui-status-warning-dark,oklch(76.9%_0.188_70.08_/_0.1)) 10%, transparent))] text-[color:var(--zui-alert-warning-fg,var(--zui-status-warning,oklch(27.9%_0.077_45.635)))] dark:text-[color:var(--zui-alert-warning-fg-dark,var(--zui-status-warning-dark,oklch(98.7%_0.022_95.277)))]",
  error:
    "border-[color:var(--zui-alert-error-border,color-mix(in oklch, var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.5)) 40%, transparent))] dark:border-[color:var(--zui-alert-error-border-dark,color-mix(in oklch, var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.5)) 40%, transparent))] bg-[var(--zui-alert-error-bg,color-mix(in oklch, var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.1)) 10%, transparent))] dark:bg-[var(--zui-alert-error-bg-dark,color-mix(in oklch, var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.1)) 10%, transparent))] text-[color:var(--zui-alert-error-fg,var(--zui-status-error,oklch(27.1%_0.105_12.094)))] dark:text-[color:var(--zui-alert-error-fg-dark,var(--zui-status-error-dark,oklch(96.9%_0.015_12.422)))]",
  info: "border-[color:var(--zui-alert-info-border,color-mix(in oklch, var(--zui-status-info,oklch(68.5%_0.169_237.323_/_0.4)) 40%, transparent))] dark:border-[color:var(--zui-alert-info-border-dark,color-mix(in oklch, var(--zui-status-info-dark,oklch(68.5%_0.169_237.323_/_0.4)) 40%, transparent))] bg-[var(--zui-alert-info-bg,color-mix(in oklch, var(--zui-status-info,oklch(68.5%_0.169_237.323_/_0.1)) 10%, transparent))] dark:bg-[var(--zui-alert-info-bg-dark,color-mix(in oklch, var(--zui-status-info-dark,oklch(68.5%_0.169_237.323_/_0.1)) 10%, transparent))] text-[color:var(--zui-alert-info-fg,var(--zui-status-info,oklch(29.3%_0.066_243.157)))] dark:text-[color:var(--zui-alert-info-fg-dark,var(--zui-status-info-dark,oklch(97.7%_0.013_236.62)))]",
  ghost:
    "border-[color:var(--zui-alert-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-alert-ghost-border-dark,var(--zui-border-dark,transparent))] bg-[var(--zui-alert-ghost-bg,var(--zui-surface-soft,transparent))] dark:bg-[var(--zui-alert-ghost-bg-dark,var(--zui-surface-soft-dark,transparent))] text-[color:var(--zui-alert-ghost-fg,var(--zui-fg-muted,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-alert-ghost-fg-dark,var(--zui-fg-muted-dark,oklch(92.9%_0.013_255.508)))]",
  blue: "border-[color:var(--zui-alert-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-alert-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-alert-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb1a) 10%, transparent))] dark:bg-[var(--zui-alert-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f626) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-blue-fg,var(--zui-color-blue,#0f172a))] dark:text-[color:var(--zui-alert-blue-fg-dark,var(--zui-color-blue-dark,#f8fafc))]",
  cyan: "border-[color:var(--zui-alert-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-alert-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-alert-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b21a) 10%, transparent))] dark:bg-[var(--zui-alert-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-cyan-fg,var(--zui-color-cyan,#0f172a))] dark:text-[color:var(--zui-alert-cyan-fg-dark,var(--zui-color-cyan-dark,#f8fafc))]",
  green:
    "border-[color:var(--zui-alert-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-alert-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-alert-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a1a) 10%, transparent))] dark:bg-[var(--zui-alert-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-green-fg,var(--zui-color-green,#0f172a))] dark:text-[color:var(--zui-alert-green-fg-dark,var(--zui-color-green-dark,#f8fafc))]",
  lime: "border-[color:var(--zui-alert-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-alert-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-alert-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d1a) 10%, transparent))] dark:bg-[var(--zui-alert-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63526) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-lime-fg,var(--zui-color-lime,#0f172a))] dark:text-[color:var(--zui-alert-lime-fg-dark,var(--zui-color-lime-dark,#f8fafc))]",
  mint: "border-[color:var(--zui-alert-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-alert-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-alert-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b9811a) 10%, transparent))] dark:bg-[var(--zui-alert-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b726) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-mint-fg,var(--zui-color-mint,#0f172a))] dark:text-[color:var(--zui-alert-mint-fg-dark,var(--zui-color-mint-dark,#f8fafc))]",
  ocean:
    "border-[color:var(--zui-alert-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-alert-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-alert-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c71a) 10%, transparent))] dark:bg-[var(--zui-alert-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf826) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-ocean-fg,var(--zui-color-ocean,#0f172a))] dark:text-[color:var(--zui-alert-ocean-fg-dark,var(--zui-color-ocean-dark,#f8fafc))]",
  sapphire:
    "border-[color:var(--zui-alert-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-alert-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-alert-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed81a) 10%, transparent))] dark:bg-[var(--zui-alert-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-sapphire-fg,var(--zui-color-sapphire,#0f172a))] dark:text-[color:var(--zui-alert-sapphire-fg-dark,var(--zui-color-sapphire-dark,#f8fafc))]",
  lavender:
    "border-[color:var(--zui-alert-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-alert-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-alert-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf61a) 10%, transparent))] dark:bg-[var(--zui-alert-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-lavender-fg,var(--zui-color-lavender,#0f172a))] dark:text-[color:var(--zui-alert-lavender-fg-dark,var(--zui-color-lavender-dark,#f8fafc))]",
  ruby: "border-[color:var(--zui-alert-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-alert-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-alert-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c1a) 10%, transparent))] dark:bg-[var(--zui-alert-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718526) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-ruby-fg,var(--zui-color-ruby,#0f172a))] dark:text-[color:var(--zui-alert-ruby-fg-dark,var(--zui-color-ruby-dark,#f8fafc))]",
  red: "border-[color:var(--zui-alert-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-alert-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-alert-red-bg,color-mix(in oklch, var(--zui-color-red,#dc26261a) 10%, transparent))] dark:bg-[var(--zui-alert-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444426) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-red-fg,var(--zui-color-red,#0f172a))] dark:text-[color:var(--zui-alert-red-fg-dark,var(--zui-color-red-dark,#f8fafc))]",
  slate:
    "border-[color:var(--zui-alert-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-alert-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-alert-slate-bg,color-mix(in oklch, var(--zui-color-slate,#4755691a) 10%, transparent))] dark:bg-[var(--zui-alert-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-slate-fg,var(--zui-color-slate,#0f172a))] dark:text-[color:var(--zui-alert-slate-fg-dark,var(--zui-color-slate-dark,#f8fafc))]",
  zinc: "border-[color:var(--zui-alert-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-alert-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-alert-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b1a) 10%, transparent))] dark:bg-[var(--zui-alert-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-zinc-fg,var(--zui-color-zinc,#0f172a))] dark:text-[color:var(--zui-alert-zinc-fg-dark,var(--zui-color-zinc-dark,#f8fafc))]",
  stone:
    "border-[color:var(--zui-alert-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-alert-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-alert-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e1a) 10%, transparent))] dark:bg-[var(--zui-alert-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-stone-fg,var(--zui-color-stone,#0f172a))] dark:text-[color:var(--zui-alert-stone-fg-dark,var(--zui-color-stone-dark,#f8fafc))]",
  royal:
    "border-[color:var(--zui-alert-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-alert-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-alert-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca1a) 10%, transparent))] dark:bg-[var(--zui-alert-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf826) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-royal-fg,var(--zui-color-royal,#0f172a))] dark:text-[color:var(--zui-alert-royal-fg-dark,var(--zui-color-royal-dark,#f8fafc))]",
  electric:
    "border-[color:var(--zui-alert-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-alert-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-alert-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e91a) 10%, transparent))] dark:bg-[var(--zui-alert-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf826) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-electric-fg,var(--zui-color-electric,#0f172a))] dark:text-[color:var(--zui-alert-electric-fg-dark,var(--zui-color-electric-dark,#f8fafc))]",
  forest:
    "border-[color:var(--zui-alert-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-alert-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-alert-forest-bg,color-mix(in oklch, var(--zui-color-forest,#1665341a) 10%, transparent))] dark:bg-[var(--zui-alert-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8026) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-forest-fg,var(--zui-color-forest,#0f172a))] dark:text-[color:var(--zui-alert-forest-fg-dark,var(--zui-color-forest-dark,#f8fafc))]",
  sunset:
    "border-[color:var(--zui-alert-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-alert-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-alert-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c1a) 10%, transparent))] dark:bg-[var(--zui-alert-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-sunset-fg,var(--zui-color-sunset,#0f172a))] dark:text-[color:var(--zui-alert-sunset-fg-dark,var(--zui-color-sunset-dark,#f8fafc))]",
  magenta:
    "border-[color:var(--zui-alert-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-alert-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-alert-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d31a) 10%, transparent))] dark:bg-[var(--zui-alert-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f926) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-magenta-fg,var(--zui-color-magenta,#0f172a))] dark:text-[color:var(--zui-alert-magenta-fg-dark,var(--zui-color-magenta-dark,#f8fafc))]",
  crimson:
    "border-[color:var(--zui-alert-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-alert-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-alert-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c1a) 10%, transparent))] dark:bg-[var(--zui-alert-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717126) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-crimson-fg,var(--zui-color-crimson,#0f172a))] dark:text-[color:var(--zui-alert-crimson-fg-dark,var(--zui-color-crimson-dark,#f8fafc))]",
  aqua: "border-[color:var(--zui-alert-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-alert-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-alert-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e1a) 10%, transparent))] dark:bg-[var(--zui-alert-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-aqua-fg,var(--zui-color-aqua,#0f172a))] dark:text-[color:var(--zui-alert-aqua-fg-dark,var(--zui-color-aqua-dark,#f8fafc))]",
  plum: "border-[color:var(--zui-alert-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-alert-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-alert-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce1a) 10%, transparent))] dark:bg-[var(--zui-alert-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc26) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-plum-fg,var(--zui-color-plum,#0f172a))] dark:text-[color:var(--zui-alert-plum-fg-dark,var(--zui-color-plum-dark,#f8fafc))]",
  purple:
    "border-[color:var(--zui-alert-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-alert-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-alert-purple-bg,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:bg-[var(--zui-alert-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-purple-fg,var(--zui-color-purple,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-purple-fg-dark,var(--zui-color-purple-dark,oklch(98.4%_0.003_247.858)))]",
  pink: "border-[color:var(--zui-alert-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-alert-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-alert-pink-bg,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:bg-[var(--zui-alert-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-pink-fg,var(--zui-color-pink,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-pink-fg-dark,var(--zui-color-pink-dark,oklch(98.4%_0.003_247.858)))]",
  orange:
    "border-[color:var(--zui-alert-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-alert-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-alert-orange-bg,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:bg-[var(--zui-alert-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-orange-fg,var(--zui-color-orange,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-orange-fg-dark,var(--zui-color-orange-dark,oklch(98.4%_0.003_247.858)))]",
  yellow:
    "border-[color:var(--zui-alert-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-alert-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-alert-yellow-bg,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:bg-[var(--zui-alert-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-yellow-fg,var(--zui-color-yellow,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(98.4%_0.003_247.858)))]",
  teal: "border-[color:var(--zui-alert-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-alert-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-alert-teal-bg,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:bg-[var(--zui-alert-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-teal-fg,var(--zui-color-teal,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-teal-fg-dark,var(--zui-color-teal-dark,oklch(98.4%_0.003_247.858)))]",
  indigo:
    "border-[color:var(--zui-alert-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-alert-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-alert-indigo-bg,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:bg-[var(--zui-alert-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-indigo-fg,var(--zui-color-indigo,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(98.4%_0.003_247.858)))]",
  gray: "border-[color:var(--zui-alert-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-alert-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] bg-[var(--zui-alert-gray-bg,var(--zui-color-gray,oklch(98.5%_0.002_247.839)))] dark:bg-[var(--zui-alert-gray-bg-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(13%_0.028_261.692_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-gray-fg,var(--zui-color-gray,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gray-fg-dark,var(--zui-color-gray-dark,oklch(98.4%_0.003_247.858)))]",
  violet:
    "border-[color:var(--zui-alert-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-alert-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-alert-violet-bg,var(--zui-color-violet,oklch(96.9%_0.016_293.756)))] dark:bg-[var(--zui-alert-violet-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(28.3%_0.141_291.089_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-alert-violet-fg,var(--zui-color-violet,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-violet-fg-dark,var(--zui-color-violet-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-blue":
    "border-[color:var(--zui-alert-gradient-blue-border,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:border-[color:var(--zui-alert-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] bg-linear-to-r from-[var(--zui-alert-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:from-[var(--zui-alert-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(28.2%_0.091_267.935_/_0.7)))] to-[var(--zui-alert-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-alert-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-blue-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-green":
    "border-[color:var(--zui-alert-gradient-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:border-[color:var(--zui-alert-gradient-green-border-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] bg-linear-to-r from-[var(--zui-alert-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:from-[var(--zui-alert-gradient-green-from-dark,var(--zui-color-green-dark,oklch(26.6%_0.065_152.934_/_0.7)))] to-[var(--zui-alert-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:to-[var(--zui-alert-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(27.4%_0.072_132.109_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-green-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-red":
    "border-[color:var(--zui-alert-gradient-red-border,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:border-[color:var(--zui-alert-gradient-red-border-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] bg-linear-to-r from-[var(--zui-alert-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:from-[var(--zui-alert-gradient-red-from-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] to-[var(--zui-alert-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-alert-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-red-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-yellow":
    "border-[color:var(--zui-alert-gradient-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-alert-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-linear-to-r from-[var(--zui-alert-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:from-[var(--zui-alert-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)))] to-[var(--zui-alert-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:to-[var(--zui-alert-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-yellow-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-purple":
    "border-[color:var(--zui-alert-gradient-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-alert-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-linear-to-r from-[var(--zui-alert-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:from-[var(--zui-alert-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] to-[var(--zui-alert-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-alert-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-purple-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-teal":
    "border-[color:var(--zui-alert-gradient-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-alert-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-linear-to-r from-[var(--zui-alert-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:from-[var(--zui-alert-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)))] to-[var(--zui-alert-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:to-[var(--zui-alert-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(30.2%_0.056_229.695_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-teal-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-indigo":
    "border-[color:var(--zui-alert-gradient-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-alert-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-linear-to-r from-[var(--zui-alert-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:from-[var(--zui-alert-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)))] to-[var(--zui-alert-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-alert-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-indigo-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-pink":
    "border-[color:var(--zui-alert-gradient-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-alert-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-linear-to-r from-[var(--zui-alert-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:from-[var(--zui-alert-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] to-[var(--zui-alert-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:to-[var(--zui-alert-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-pink-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
  "gradient-orange":
    "border-[color:var(--zui-alert-gradient-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-alert-gradient-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-linear-to-r from-[var(--zui-alert-gradient-orange-from,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:from-[var(--zui-alert-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] to-[var(--zui-alert-gradient-orange-to,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:to-[var(--zui-alert-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-alert-gradient-orange-fg,var(--zui-brand-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-alert-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.003_247.858)))]",
} as const;

export const zuiAlertSizes = {
  sm: "rounded-lg p-3",
  md: "rounded-xl p-4",
  lg: "rounded-2xl p-5 text-base",
} as const;

export const zuiAlertTitleBase = "font-semibold leading-tight";

export const zuiAlertTextSizes = {
  sm: "text-xs md:text-sm",
  md: "text-xs md:text-sm",
  lg: "text-xs md:text-sm",
} as const;

export const zuiAlertDescriptionBase =
  "text-[color:var(--zui-alert-description-fg,var(--zui-fg-muted,oklch(44.6%_0.043_257.281)))] dark:text-[color:var(--zui-alert-description-fg-dark,var(--zui-fg-muted-dark,oklch(86.9%_0.022_252.894)))]";
