export const zuiAvatarBase =
  "relative flex shrink-0 overflow-hidden rounded-full border border-[color:var(--zui-avatar-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-avatar-border-dark,var(--zui-border-dark,#ffffff1a))] text-[color:var(--zui-avatar-fg,var(--zui-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-fg-dark,var(--zui-fg-dark,oklch(92.9%_0.013_255.508)))]";

export const zuiAvatarAppearances = {
  default:
    "border-[color:var(--zui-avatar-default-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-avatar-default-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-avatar-default-bg,var(--zui-brand,#0000001a))] dark:bg-[var(--zui-avatar-default-bg-dark,var(--zui-brand-dark,#ffffff1a))] text-[color:var(--zui-avatar-default-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-default-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  muted:
    "border-[color:var(--zui-avatar-muted-border,var(--zui-border,#00000066))] bg-[var(--zui-avatar-muted-bg,var(--zui-surface-soft,oklch(98.4%_0.003_247.858)))] dark:border-[color:var(--zui-avatar-muted-border-dark,var(--zui-border-dark,#ffffff1a))] dark:bg-[var(--zui-avatar-muted-bg-dark,var(--zui-surface-soft-dark,oklch(12.9%_0.042_264.695_/_0.4)))] text-[color:var(--zui-avatar-muted-fg,var(--zui-fg-muted,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-muted-fg-dark,var(--zui-fg-muted-dark,oklch(92.9%_0.013_255.508)))]",
  blue: "border-[color:var(--zui-avatar-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-avatar-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-avatar-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb1a) 10%, transparent))] dark:bg-[var(--zui-avatar-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f626) 18%, transparent))] text-[color:var(--zui-avatar-blue-fg,var(--zui-color-blue,#0f172a))] dark:text-[color:var(--zui-avatar-blue-fg-dark,var(--zui-color-blue-dark,#f8fafc))]",
  cyan: "border-[color:var(--zui-avatar-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-avatar-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-avatar-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b21a) 10%, transparent))] dark:bg-[var(--zui-avatar-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee26) 18%, transparent))] text-[color:var(--zui-avatar-cyan-fg,var(--zui-color-cyan,#0f172a))] dark:text-[color:var(--zui-avatar-cyan-fg-dark,var(--zui-color-cyan-dark,#f8fafc))]",
  green:
    "border-[color:var(--zui-avatar-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-avatar-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-avatar-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a1a) 10%, transparent))] dark:bg-[var(--zui-avatar-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e26) 18%, transparent))] text-[color:var(--zui-avatar-green-fg,var(--zui-color-green,#0f172a))] dark:text-[color:var(--zui-avatar-green-fg-dark,var(--zui-color-green-dark,#f8fafc))]",
  lime: "border-[color:var(--zui-avatar-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-avatar-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-avatar-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d1a) 10%, transparent))] dark:bg-[var(--zui-avatar-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63526) 18%, transparent))] text-[color:var(--zui-avatar-lime-fg,var(--zui-color-lime,#0f172a))] dark:text-[color:var(--zui-avatar-lime-fg-dark,var(--zui-color-lime-dark,#f8fafc))]",
  mint: "border-[color:var(--zui-avatar-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-avatar-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-avatar-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b9811a) 10%, transparent))] dark:bg-[var(--zui-avatar-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b726) 18%, transparent))] text-[color:var(--zui-avatar-mint-fg,var(--zui-color-mint,#0f172a))] dark:text-[color:var(--zui-avatar-mint-fg-dark,var(--zui-color-mint-dark,#f8fafc))]",
  ocean:
    "border-[color:var(--zui-avatar-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-avatar-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-avatar-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c71a) 10%, transparent))] dark:bg-[var(--zui-avatar-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf826) 18%, transparent))] text-[color:var(--zui-avatar-ocean-fg,var(--zui-color-ocean,#0f172a))] dark:text-[color:var(--zui-avatar-ocean-fg-dark,var(--zui-color-ocean-dark,#f8fafc))]",
  sapphire:
    "border-[color:var(--zui-avatar-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-avatar-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-avatar-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed81a) 10%, transparent))] dark:bg-[var(--zui-avatar-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa26) 18%, transparent))] text-[color:var(--zui-avatar-sapphire-fg,var(--zui-color-sapphire,#0f172a))] dark:text-[color:var(--zui-avatar-sapphire-fg-dark,var(--zui-color-sapphire-dark,#f8fafc))]",
  lavender:
    "border-[color:var(--zui-avatar-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-avatar-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-avatar-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf61a) 10%, transparent))] dark:bg-[var(--zui-avatar-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa26) 18%, transparent))] text-[color:var(--zui-avatar-lavender-fg,var(--zui-color-lavender,#0f172a))] dark:text-[color:var(--zui-avatar-lavender-fg-dark,var(--zui-color-lavender-dark,#f8fafc))]",
  ruby: "border-[color:var(--zui-avatar-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-avatar-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-avatar-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c1a) 10%, transparent))] dark:bg-[var(--zui-avatar-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718526) 18%, transparent))] text-[color:var(--zui-avatar-ruby-fg,var(--zui-color-ruby,#0f172a))] dark:text-[color:var(--zui-avatar-ruby-fg-dark,var(--zui-color-ruby-dark,#f8fafc))]",
  red: "border-[color:var(--zui-avatar-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-avatar-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-avatar-red-bg,color-mix(in oklch, var(--zui-color-red,#dc26261a) 10%, transparent))] dark:bg-[var(--zui-avatar-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444426) 18%, transparent))] text-[color:var(--zui-avatar-red-fg,var(--zui-color-red,#0f172a))] dark:text-[color:var(--zui-avatar-red-fg-dark,var(--zui-color-red-dark,#f8fafc))]",
  slate:
    "border-[color:var(--zui-avatar-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-avatar-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-avatar-slate-bg,color-mix(in oklch, var(--zui-color-slate,#4755691a) 10%, transparent))] dark:bg-[var(--zui-avatar-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b26) 18%, transparent))] text-[color:var(--zui-avatar-slate-fg,var(--zui-color-slate,#0f172a))] dark:text-[color:var(--zui-avatar-slate-fg-dark,var(--zui-color-slate-dark,#f8fafc))]",
  zinc: "border-[color:var(--zui-avatar-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-avatar-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-avatar-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b1a) 10%, transparent))] dark:bg-[var(--zui-avatar-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a26) 18%, transparent))] text-[color:var(--zui-avatar-zinc-fg,var(--zui-color-zinc,#0f172a))] dark:text-[color:var(--zui-avatar-zinc-fg-dark,var(--zui-color-zinc-dark,#f8fafc))]",
  stone:
    "border-[color:var(--zui-avatar-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-avatar-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-avatar-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e1a) 10%, transparent))] dark:bg-[var(--zui-avatar-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c26) 18%, transparent))] text-[color:var(--zui-avatar-stone-fg,var(--zui-color-stone,#0f172a))] dark:text-[color:var(--zui-avatar-stone-fg-dark,var(--zui-color-stone-dark,#f8fafc))]",
  royal:
    "border-[color:var(--zui-avatar-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-avatar-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-avatar-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca1a) 10%, transparent))] dark:bg-[var(--zui-avatar-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf826) 18%, transparent))] text-[color:var(--zui-avatar-royal-fg,var(--zui-color-royal,#0f172a))] dark:text-[color:var(--zui-avatar-royal-fg-dark,var(--zui-color-royal-dark,#f8fafc))]",
  electric:
    "border-[color:var(--zui-avatar-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-avatar-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-avatar-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e91a) 10%, transparent))] dark:bg-[var(--zui-avatar-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf826) 18%, transparent))] text-[color:var(--zui-avatar-electric-fg,var(--zui-color-electric,#0f172a))] dark:text-[color:var(--zui-avatar-electric-fg-dark,var(--zui-color-electric-dark,#f8fafc))]",
  forest:
    "border-[color:var(--zui-avatar-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-avatar-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-avatar-forest-bg,color-mix(in oklch, var(--zui-color-forest,#1665341a) 10%, transparent))] dark:bg-[var(--zui-avatar-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8026) 18%, transparent))] text-[color:var(--zui-avatar-forest-fg,var(--zui-color-forest,#0f172a))] dark:text-[color:var(--zui-avatar-forest-fg-dark,var(--zui-color-forest-dark,#f8fafc))]",
  sunset:
    "border-[color:var(--zui-avatar-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-avatar-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-avatar-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c1a) 10%, transparent))] dark:bg-[var(--zui-avatar-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c26) 18%, transparent))] text-[color:var(--zui-avatar-sunset-fg,var(--zui-color-sunset,#0f172a))] dark:text-[color:var(--zui-avatar-sunset-fg-dark,var(--zui-color-sunset-dark,#f8fafc))]",
  magenta:
    "border-[color:var(--zui-avatar-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-avatar-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-avatar-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d31a) 10%, transparent))] dark:bg-[var(--zui-avatar-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f926) 18%, transparent))] text-[color:var(--zui-avatar-magenta-fg,var(--zui-color-magenta,#0f172a))] dark:text-[color:var(--zui-avatar-magenta-fg-dark,var(--zui-color-magenta-dark,#f8fafc))]",
  crimson:
    "border-[color:var(--zui-avatar-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-avatar-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-avatar-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c1a) 10%, transparent))] dark:bg-[var(--zui-avatar-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717126) 18%, transparent))] text-[color:var(--zui-avatar-crimson-fg,var(--zui-color-crimson,#0f172a))] dark:text-[color:var(--zui-avatar-crimson-fg-dark,var(--zui-color-crimson-dark,#f8fafc))]",
  aqua: "border-[color:var(--zui-avatar-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-avatar-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-avatar-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e1a) 10%, transparent))] dark:bg-[var(--zui-avatar-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf26) 18%, transparent))] text-[color:var(--zui-avatar-aqua-fg,var(--zui-color-aqua,#0f172a))] dark:text-[color:var(--zui-avatar-aqua-fg-dark,var(--zui-color-aqua-dark,#f8fafc))]",
  plum: "border-[color:var(--zui-avatar-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-avatar-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-avatar-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce1a) 10%, transparent))] dark:bg-[var(--zui-avatar-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc26) 18%, transparent))] text-[color:var(--zui-avatar-plum-fg,var(--zui-color-plum,#0f172a))] dark:text-[color:var(--zui-avatar-plum-fg-dark,var(--zui-color-plum-dark,#f8fafc))]",
  sky: "border-[color:var(--zui-avatar-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-avatar-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] bg-[var(--zui-avatar-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(95.1%_0.026_236.824_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-sky-fg,var(--zui-color-sky,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-sky-fg-dark,var(--zui-color-sky-dark,oklch(92.9%_0.013_255.508)))]",
  rose: "border-[color:var(--zui-avatar-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-avatar-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] bg-[var(--zui-avatar-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(94.1%_0.03_12.58_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-rose-fg,var(--zui-color-rose,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-rose-fg-dark,var(--zui-color-rose-dark,oklch(92.9%_0.013_255.508)))]",
  purple:
    "border-[color:var(--zui-avatar-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-avatar-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-avatar-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(94.6%_0.033_307.174_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-purple-fg,var(--zui-color-purple,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-purple-fg-dark,var(--zui-color-purple-dark,oklch(92.9%_0.013_255.508)))]",
  pink: "border-[color:var(--zui-avatar-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-avatar-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-avatar-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(94.8%_0.028_342.258_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-pink-fg,var(--zui-color-pink,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-pink-fg-dark,var(--zui-color-pink-dark,oklch(92.9%_0.013_255.508)))]",
  orange:
    "border-[color:var(--zui-avatar-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-avatar-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-avatar-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(95.4%_0.038_75.164_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-orange-fg,var(--zui-color-orange,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-orange-fg-dark,var(--zui-color-orange-dark,oklch(92.9%_0.013_255.508)))]",
  yellow:
    "border-[color:var(--zui-avatar-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-avatar-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-avatar-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(97.3%_0.071_103.193_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-yellow-fg,var(--zui-color-yellow,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(92.9%_0.013_255.508)))]",
  teal: "border-[color:var(--zui-avatar-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-avatar-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-avatar-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(95.3%_0.051_180.801_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(60%_0.118_184.704_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-teal-fg,var(--zui-color-teal,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-teal-fg-dark,var(--zui-color-teal-dark,oklch(92.9%_0.013_255.508)))]",
  indigo:
    "border-[color:var(--zui-avatar-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-avatar-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-avatar-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(93%_0.034_272.788_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-indigo-fg,var(--zui-color-indigo,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(92.9%_0.013_255.508)))]",
  emerald:
    "border-[color:var(--zui-avatar-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-avatar-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] bg-[var(--zui-avatar-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(95%_0.052_163.051_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-emerald-fg,var(--zui-color-emerald,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(92.9%_0.013_255.508)))]",
  gray: "border-[color:var(--zui-avatar-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-avatar-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] bg-[var(--zui-avatar-gray-bg,color-mix(in oklch, var(--zui-color-gray,oklch(96.7%_0.003_264.542_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-gray-bg-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-gray-fg,var(--zui-color-gray,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gray-fg-dark,var(--zui-color-gray-dark,oklch(92.9%_0.013_255.508)))]",
  amber:
    "border-[color:var(--zui-avatar-amber-border,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:border-[color:var(--zui-avatar-amber-border-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] bg-[var(--zui-avatar-amber-bg,color-mix(in oklch, var(--zui-color-amber,oklch(96.2%_0.059_95.617_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-amber-bg-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-amber-fg,var(--zui-color-amber,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-amber-fg-dark,var(--zui-color-amber-dark,oklch(92.9%_0.013_255.508)))]",
  violet:
    "border-[color:var(--zui-avatar-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-avatar-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-avatar-violet-bg,color-mix(in oklch, var(--zui-color-violet,oklch(94.3%_0.029_294.588_/_0.5)) 10%, transparent))] dark:bg-[var(--zui-avatar-violet-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009_/_0.03)) 18%, transparent))] text-[color:var(--zui-avatar-violet-fg,var(--zui-color-violet,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-violet-fg-dark,var(--zui-color-violet-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-blue-from,var(--zui-color-blue,oklch(62.3%_0.214_259.815)))] dark:from-[var(--zui-avatar-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-avatar-gradient-blue-to,var(--zui-color-purple,oklch(62.7%_0.265_303.9)))] dark:to-[var(--zui-avatar-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-blue-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-green-from,var(--zui-color-green,oklch(72.3%_0.219_149.579)))] dark:from-[var(--zui-avatar-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-avatar-gradient-green-to,var(--zui-color-lime,oklch(76.8%_0.233_130.85)))] dark:to-[var(--zui-avatar-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-green-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-red-from,var(--zui-color-red,oklch(63.7%_0.237_25.331)))] dark:from-[var(--zui-avatar-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-avatar-gradient-red-to,var(--zui-color-pink,oklch(65.6%_0.241_354.308)))] dark:to-[var(--zui-avatar-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-red-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-yellow-from,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:from-[var(--zui-avatar-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-avatar-gradient-yellow-to,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:to-[var(--zui-avatar-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-yellow-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-purple-from,var(--zui-color-purple,oklch(62.7%_0.265_303.9)))] dark:from-[var(--zui-avatar-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-avatar-gradient-purple-to,var(--zui-color-pink,oklch(65.6%_0.241_354.308)))] dark:to-[var(--zui-avatar-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-purple-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-teal-from,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:from-[var(--zui-avatar-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-avatar-gradient-teal-to,var(--zui-color-cyan,oklch(71.5%_0.143_215.221)))] dark:to-[var(--zui-avatar-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-teal-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-indigo-from,var(--zui-color-indigo,oklch(58.5%_0.233_277.117)))] dark:from-[var(--zui-avatar-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-avatar-gradient-indigo-to,var(--zui-color-purple,oklch(62.7%_0.265_303.9)))] dark:to-[var(--zui-avatar-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-indigo-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-pink-from,var(--zui-color-pink,oklch(65.6%_0.241_354.308)))] dark:from-[var(--zui-avatar-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-avatar-gradient-pink-to,var(--zui-color-rose,oklch(64.5%_0.246_16.439)))] dark:to-[var(--zui-avatar-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-pink-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-avatar-gradient-orange-from,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:from-[var(--zui-avatar-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-avatar-gradient-orange-to,var(--zui-color-red,oklch(63.7%_0.237_25.331)))] dark:to-[var(--zui-avatar-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] backdrop-blur-xl text-[color:var(--zui-avatar-gradient-orange-fg,var(--zui-brand-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-avatar-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(92.9%_0.013_255.508)))]",
} as const;

export const zuiAvatarSizes = {
  sm: "size-8 text-xs",
  md: "size-10 text-sm",
  lg: "size-12 text-base",
  xl: "size-16 text-lg",
} as const;

export const zuiAvatarImageBase = "aspect-square size-full object-cover";

export const zuiAvatarFallbackBase =
  "flex size-full items-center justify-center bg-[var(--zui-avatar-fallback-bg,var(--zui-surface-soft,oklch(92.9%_0.013_255.508)))] dark:bg-[var(--zui-avatar-fallback-bg-dark,var(--zui-surface-soft-dark,oklch(27.9%_0.041_260.031)))] font-medium text-[color:var(--zui-avatar-fallback-fg,var(--zui-fg,oklch(27.9%_0.041_260.031)))] dark:text-[color:var(--zui-avatar-fallback-fg-dark,var(--zui-fg-dark,oklch(96.8%_0.007_247.896)))]";

export const zuiAvatarGroupBase =
  "flex items-center [&_[data-slot=avatar]]:-ml-2 [&_[data-slot=avatar]]:ring-2 [&_[data-slot=avatar]]:ring-[var(--zui-avatar-group-ring,var(--zui-focus-ring,#ffffff))] dark:[&_[data-slot=avatar]]:ring-[var(--zui-avatar-group-ring-dark,var(--zui-focus-ring-dark,oklch(12.9%_0.042_264.695)))] [&_[data-slot=avatar]]:first:ml-0";
