export const zuiCalendarBase = [
  "inline-flex flex-col gap-3",
  "rounded-[var(--zui-calendar-radius,0.75rem)] p-[var(--zui-calendar-p,0.75rem)]",
  "border border-[color:var(--zui-calendar-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-calendar-border-dark,var(--zui-border-dark,#ffffff1a))]",
  "bg-[var(--zui-calendar-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-calendar-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))]",
  "text-[color:var(--zui-calendar-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-calendar-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))]",
] as const;

export const zuiCalendarSizes = {
  sm: "text-xs",
  md: "text-sm",
  lg: "text-base",
} as const;

export const zuiCalendarMonths = "flex flex-col gap-6 sm:flex-row sm:gap-8";

export const zuiCalendarMonth = "flex flex-col gap-2";

export const zuiCalendarHeader = "flex items-center justify-between gap-2";

export const zuiCalendarNavButton =
  "inline-flex size-[var(--zui-calendar-nav-size,2rem)] shrink-0 cursor-pointer items-center justify-center rounded-md border border-[color:var(--zui-calendar-nav-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-calendar-nav-border-dark,var(--zui-border-dark,#ffffff1a))] bg-transparent text-current transition-colors hover:bg-[var(--zui-calendar-cell-hover-bg,var(--zui-surface-soft,#0000000d))] dark:hover:bg-[var(--zui-calendar-cell-hover-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-calendar-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281)))] dark:focus-visible:ring-[var(--zui-calendar-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894)))]";

export const zuiCalendarCaption =
  "flex flex-1 items-center justify-center gap-1.5 font-medium text-[length:var(--zui-calendar-caption-font-size,0.875rem)]";

export const zuiCalendarDropdown =
  "h-8 cursor-pointer rounded-md border border-[color:var(--zui-calendar-dropdown-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-calendar-dropdown-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-calendar-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-calendar-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] px-1.5 text-current focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-calendar-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281)))] dark:focus-visible:ring-[var(--zui-calendar-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894)))]";

export const zuiCalendarGrid = "w-full border-collapse";

export const zuiCalendarWeekday =
  "pb-1.5 text-center align-middle text-xs font-medium text-[color:var(--zui-calendar-muted-fg,var(--zui-fg-muted,oklch(44.6%_0.043_257.281)))] dark:text-[color:var(--zui-calendar-muted-fg-dark,var(--zui-fg-muted-dark,oklch(86.9%_0.022_252.894)))]";

export const zuiCalendarWeekNumber =
  "pr-1.5 text-center align-middle text-xs tabular-nums text-[color:var(--zui-calendar-muted-fg,var(--zui-fg-muted,oklch(44.6%_0.043_257.281)))] dark:text-[color:var(--zui-calendar-muted-fg-dark,var(--zui-fg-muted-dark,oklch(86.9%_0.022_252.894)))]";

export const zuiCalendarDayCell = "p-0 text-center align-middle";

export const zuiCalendarDayBase = [
  "inline-flex cursor-pointer items-center justify-center select-none rounded-[var(--zui-calendar-cell-radius,0.5rem)] font-normal tabular-nums transition-colors",
  "hover:bg-[var(--zui-calendar-cell-hover-bg,var(--zui-surface-soft,#0000000d))] dark:hover:bg-[var(--zui-calendar-cell-hover-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))]",
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-calendar-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281)))] dark:focus-visible:ring-[var(--zui-calendar-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894)))] focus-visible:z-10",
  "data-[today=true]:ring-1 data-[today=true]:ring-inset data-[today=true]:ring-[color:var(--zui-calendar-today-ring,var(--zui-focus-ring,oklch(44.6%_0.043_257.281)))] dark:data-[today=true]:ring-[color:var(--zui-calendar-today-ring-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894)))]",
  "data-[outside=true]:opacity-60 data-[outside=true]:text-[color:var(--zui-calendar-muted-fg,var(--zui-fg-muted,oklch(44.6%_0.043_257.281)))] dark:data-[outside=true]:text-[color:var(--zui-calendar-muted-fg-dark,var(--zui-fg-muted-dark,oklch(86.9%_0.022_252.894)))]",
  "data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-35 data-[disabled=true]:hover:bg-transparent dark:data-[disabled=true]:hover:bg-transparent",
  "data-[range-start=true]:rounded-r-none data-[range-end=true]:rounded-l-none data-[range-middle=true]:rounded-none data-[range-start=true]:data-[range-end=true]:rounded-[var(--zui-calendar-cell-radius,0.5rem)]",
] as const;

export const zuiCalendarDaySizes = {
  sm: "size-[var(--zui-calendar-cell-size-sm,2rem)] text-xs",
  md: "size-[var(--zui-calendar-cell-size-md,2.25rem)] text-sm",
  lg: "size-[var(--zui-calendar-cell-size-lg,2.75rem)] text-base",
} as const;

export const zuiCalendarDayAppearances = {
  default:
    "data-[selected=true]:bg-[var(--zui-calendar-default-selected-bg,var(--zui-brand,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:bg-[var(--zui-calendar-default-selected-bg-dark,var(--zui-brand-dark,oklch(98.4%_0.003_247.858)))] data-[selected=true]:text-[color:var(--zui-calendar-default-selected-fg,var(--zui-brand-fg,oklch(98.4%_0.003_247.858)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-default-selected-fg-dark,var(--zui-brand-fg-dark,oklch(12.9%_0.042_264.695)))] data-[range-middle=true]:bg-[var(--zui-calendar-default-range-bg,color-mix(in_oklch,var(--zui-brand,oklch(20.8%_0.042_265.755))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-default-range-bg-dark,color-mix(in_oklch,var(--zui-brand-dark,oklch(98.4%_0.003_247.858))_28%,transparent))] data-[range-middle=true]:text-current",
  secondary:
    "data-[selected=true]:bg-[var(--zui-calendar-secondary-selected-bg,var(--zui-surface-muted,oklch(92.9%_0.013_255.508)))] dark:data-[selected=true]:bg-[var(--zui-calendar-secondary-selected-bg-dark,var(--zui-surface-muted-dark,oklch(27.9%_0.041_260.031)))] data-[selected=true]:text-[color:var(--zui-calendar-secondary-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-secondary-selected-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] data-[range-middle=true]:bg-[var(--zui-calendar-secondary-range-bg,color-mix(in_oklch,var(--zui-surface-muted,oklch(92.9%_0.013_255.508))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-secondary-range-bg-dark,color-mix(in_oklch,var(--zui-surface-muted-dark,oklch(27.9%_0.041_260.031))_28%,transparent))] data-[range-middle=true]:text-current",
  destructive:
    "data-[selected=true]:bg-[var(--zui-calendar-destructive-selected-bg,var(--zui-status-error,oklch(64.5%_0.246_16.439)))] dark:data-[selected=true]:bg-[var(--zui-calendar-destructive-selected-bg-dark,var(--zui-status-error-dark,oklch(51.4%_0.222_16.935)))] data-[selected=true]:text-[color:var(--zui-calendar-destructive-selected-fg,var(--zui-brand-fg,oklch(98.4%_0.003_247.858)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-destructive-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-destructive-range-bg,color-mix(in_oklch,var(--zui-status-error,oklch(64.5%_0.246_16.439))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-destructive-range-bg-dark,color-mix(in_oklch,var(--zui-status-error-dark,oklch(51.4%_0.222_16.935))_28%,transparent))] data-[range-middle=true]:text-current",
  outline:
    "data-[selected=true]:border data-[selected=true]:border-[color:var(--zui-calendar-outline-selected-border,var(--zui-border,#00000026))] dark:data-[selected=true]:border-[color:var(--zui-calendar-outline-selected-border-dark,var(--zui-border-dark,#ffffff26))] data-[selected=true]:bg-[var(--zui-calendar-outline-selected-bg,var(--zui-surface-soft,#0000000d))] dark:data-[selected=true]:bg-[var(--zui-calendar-outline-selected-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] data-[selected=true]:text-[color:var(--zui-calendar-outline-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-outline-selected-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] data-[range-middle=true]:bg-[var(--zui-calendar-outline-range-bg,var(--zui-surface-soft,#0000000d))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-outline-range-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] data-[range-middle=true]:text-current",
  ghost:
    "data-[selected=true]:bg-[var(--zui-calendar-ghost-selected-bg,var(--zui-surface-soft,#0000001a))] dark:data-[selected=true]:bg-[var(--zui-calendar-ghost-selected-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] data-[selected=true]:text-[color:var(--zui-calendar-ghost-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-ghost-selected-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] data-[range-middle=true]:bg-[var(--zui-calendar-ghost-range-bg,var(--zui-surface-soft,#0000000d))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-ghost-range-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] data-[range-middle=true]:text-current",
  glass:
    "data-[selected=true]:border data-[selected=true]:border-[color:var(--zui-calendar-glass-selected-border,var(--zui-border,#00000026))] dark:data-[selected=true]:border-[color:var(--zui-calendar-glass-selected-border-dark,var(--zui-border-dark,#ffffff26))] data-[selected=true]:bg-[var(--zui-calendar-glass-selected-bg,var(--zui-surface-soft,#0000001a))] dark:data-[selected=true]:bg-[var(--zui-calendar-glass-selected-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] data-[selected=true]:text-[color:var(--zui-calendar-glass-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-glass-selected-fg-dark,var(--zui-fg-dark,#ffffff))] data-[selected=true]:backdrop-blur-md data-[range-middle=true]:bg-[var(--zui-calendar-glass-range-bg,var(--zui-surface-soft,#0000000d))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-glass-range-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] data-[range-middle=true]:text-current",
  blue: "data-[selected=true]:bg-[var(--zui-calendar-blue-selected-bg,var(--zui-color-blue,#2563eb))] dark:data-[selected=true]:bg-[var(--zui-calendar-blue-selected-bg-dark,var(--zui-color-blue-dark,#3b82f6))] data-[selected=true]:text-[color:var(--zui-calendar-blue-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-blue-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-blue-range-bg,color-mix(in_oklch,var(--zui-color-blue,#2563eb)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-blue-range-bg-dark,color-mix(in_oklch,var(--zui-color-blue-dark,#3b82f6)_28%,transparent))] data-[range-middle=true]:text-current",
  cyan: "data-[selected=true]:bg-[var(--zui-calendar-cyan-selected-bg,var(--zui-color-cyan,#0891b2))] dark:data-[selected=true]:bg-[var(--zui-calendar-cyan-selected-bg-dark,var(--zui-color-cyan-dark,#22d3ee))] data-[selected=true]:text-[color:var(--zui-calendar-cyan-selected-fg,var(--zui-brand-fg,#083344))] dark:data-[selected=true]:text-[color:var(--zui-calendar-cyan-selected-fg-dark,var(--zui-brand-fg-dark,#083344))] data-[range-middle=true]:bg-[var(--zui-calendar-cyan-range-bg,color-mix(in_oklch,var(--zui-color-cyan,#0891b2)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-cyan-range-bg-dark,color-mix(in_oklch,var(--zui-color-cyan-dark,#22d3ee)_28%,transparent))] data-[range-middle=true]:text-current",
  green:
    "data-[selected=true]:bg-[var(--zui-calendar-green-selected-bg,var(--zui-color-green,#16a34a))] dark:data-[selected=true]:bg-[var(--zui-calendar-green-selected-bg-dark,var(--zui-color-green-dark,#22c55e))] data-[selected=true]:text-[color:var(--zui-calendar-green-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-green-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-green-range-bg,color-mix(in_oklch,var(--zui-color-green,#16a34a)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-green-range-bg-dark,color-mix(in_oklch,var(--zui-color-green-dark,#22c55e)_28%,transparent))] data-[range-middle=true]:text-current",
  lime: "data-[selected=true]:bg-[var(--zui-calendar-lime-selected-bg,var(--zui-color-lime,#65a30d))] dark:data-[selected=true]:bg-[var(--zui-calendar-lime-selected-bg-dark,var(--zui-color-lime-dark,#a3e635))] data-[selected=true]:text-[color:var(--zui-calendar-lime-selected-fg,var(--zui-brand-fg,#1a2e05))] dark:data-[selected=true]:text-[color:var(--zui-calendar-lime-selected-fg-dark,var(--zui-brand-fg-dark,#1a2e05))] data-[range-middle=true]:bg-[var(--zui-calendar-lime-range-bg,color-mix(in_oklch,var(--zui-color-lime,#65a30d)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-lime-range-bg-dark,color-mix(in_oklch,var(--zui-color-lime-dark,#a3e635)_28%,transparent))] data-[range-middle=true]:text-current",
  mint: "data-[selected=true]:bg-[var(--zui-calendar-mint-selected-bg,var(--zui-color-mint,#10b981))] dark:data-[selected=true]:bg-[var(--zui-calendar-mint-selected-bg-dark,var(--zui-color-mint-dark,#6ee7b7))] data-[selected=true]:text-[color:var(--zui-calendar-mint-selected-fg,var(--zui-brand-fg,#064e3b))] dark:data-[selected=true]:text-[color:var(--zui-calendar-mint-selected-fg-dark,var(--zui-brand-fg-dark,#064e3b))] data-[range-middle=true]:bg-[var(--zui-calendar-mint-range-bg,color-mix(in_oklch,var(--zui-color-mint,#10b981)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-mint-range-bg-dark,color-mix(in_oklch,var(--zui-color-mint-dark,#6ee7b7)_28%,transparent))] data-[range-middle=true]:text-current",
  ocean:
    "data-[selected=true]:bg-[var(--zui-calendar-ocean-selected-bg,var(--zui-color-ocean,#0284c7))] dark:data-[selected=true]:bg-[var(--zui-calendar-ocean-selected-bg-dark,var(--zui-color-ocean-dark,#38bdf8))] data-[selected=true]:text-[color:var(--zui-calendar-ocean-selected-fg,var(--zui-brand-fg,#082f49))] dark:data-[selected=true]:text-[color:var(--zui-calendar-ocean-selected-fg-dark,var(--zui-brand-fg-dark,#082f49))] data-[range-middle=true]:bg-[var(--zui-calendar-ocean-range-bg,color-mix(in_oklch,var(--zui-color-ocean,#0284c7)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-ocean-range-bg-dark,color-mix(in_oklch,var(--zui-color-ocean-dark,#38bdf8)_28%,transparent))] data-[range-middle=true]:text-current",
  sapphire:
    "data-[selected=true]:bg-[var(--zui-calendar-sapphire-selected-bg,var(--zui-color-sapphire,#1d4ed8))] dark:data-[selected=true]:bg-[var(--zui-calendar-sapphire-selected-bg-dark,var(--zui-color-sapphire-dark,#60a5fa))] data-[selected=true]:text-[color:var(--zui-calendar-sapphire-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-sapphire-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-sapphire-range-bg,color-mix(in_oklch,var(--zui-color-sapphire,#1d4ed8)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-sapphire-range-bg-dark,color-mix(in_oklch,var(--zui-color-sapphire-dark,#60a5fa)_28%,transparent))] data-[range-middle=true]:text-current",
  lavender:
    "data-[selected=true]:bg-[var(--zui-calendar-lavender-selected-bg,var(--zui-color-lavender,#8b5cf6))] dark:data-[selected=true]:bg-[var(--zui-calendar-lavender-selected-bg-dark,var(--zui-color-lavender-dark,#a78bfa))] data-[selected=true]:text-[color:var(--zui-calendar-lavender-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-lavender-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-lavender-range-bg,color-mix(in_oklch,var(--zui-color-lavender,#8b5cf6)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-lavender-range-bg-dark,color-mix(in_oklch,var(--zui-color-lavender-dark,#a78bfa)_28%,transparent))] data-[range-middle=true]:text-current",
  ruby: "data-[selected=true]:bg-[var(--zui-calendar-ruby-selected-bg,var(--zui-color-ruby,#be123c))] dark:data-[selected=true]:bg-[var(--zui-calendar-ruby-selected-bg-dark,var(--zui-color-ruby-dark,#fb7185))] data-[selected=true]:text-[color:var(--zui-calendar-ruby-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-ruby-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-ruby-range-bg,color-mix(in_oklch,var(--zui-color-ruby,#be123c)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-ruby-range-bg-dark,color-mix(in_oklch,var(--zui-color-ruby-dark,#fb7185)_28%,transparent))] data-[range-middle=true]:text-current",
  red: "data-[selected=true]:bg-[var(--zui-calendar-red-selected-bg,var(--zui-color-red,#dc2626))] dark:data-[selected=true]:bg-[var(--zui-calendar-red-selected-bg-dark,var(--zui-color-red-dark,#ef4444))] data-[selected=true]:text-[color:var(--zui-calendar-red-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-red-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-red-range-bg,color-mix(in_oklch,var(--zui-color-red,#dc2626)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-red-range-bg-dark,color-mix(in_oklch,var(--zui-color-red-dark,#ef4444)_28%,transparent))] data-[range-middle=true]:text-current",
  slate:
    "data-[selected=true]:bg-[var(--zui-calendar-slate-selected-bg,var(--zui-color-slate,#475569))] dark:data-[selected=true]:bg-[var(--zui-calendar-slate-selected-bg-dark,var(--zui-color-slate-dark,#64748b))] data-[selected=true]:text-[color:var(--zui-calendar-slate-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-slate-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-slate-range-bg,color-mix(in_oklch,var(--zui-color-slate,#475569)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-slate-range-bg-dark,color-mix(in_oklch,var(--zui-color-slate-dark,#64748b)_28%,transparent))] data-[range-middle=true]:text-current",
  zinc: "data-[selected=true]:bg-[var(--zui-calendar-zinc-selected-bg,var(--zui-color-zinc,#52525b))] dark:data-[selected=true]:bg-[var(--zui-calendar-zinc-selected-bg-dark,var(--zui-color-zinc-dark,#71717a))] data-[selected=true]:text-[color:var(--zui-calendar-zinc-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-zinc-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-zinc-range-bg,color-mix(in_oklch,var(--zui-color-zinc,#52525b)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-zinc-range-bg-dark,color-mix(in_oklch,var(--zui-color-zinc-dark,#71717a)_28%,transparent))] data-[range-middle=true]:text-current",
  stone:
    "data-[selected=true]:bg-[var(--zui-calendar-stone-selected-bg,var(--zui-color-stone,#57534e))] dark:data-[selected=true]:bg-[var(--zui-calendar-stone-selected-bg-dark,var(--zui-color-stone-dark,#78716c))] data-[selected=true]:text-[color:var(--zui-calendar-stone-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-stone-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-stone-range-bg,color-mix(in_oklch,var(--zui-color-stone,#57534e)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-stone-range-bg-dark,color-mix(in_oklch,var(--zui-color-stone-dark,#78716c)_28%,transparent))] data-[range-middle=true]:text-current",
  royal:
    "data-[selected=true]:bg-[var(--zui-calendar-royal-selected-bg,var(--zui-color-royal,#4338ca))] dark:data-[selected=true]:bg-[var(--zui-calendar-royal-selected-bg-dark,var(--zui-color-royal-dark,#818cf8))] data-[selected=true]:text-[color:var(--zui-calendar-royal-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-royal-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-royal-range-bg,color-mix(in_oklch,var(--zui-color-royal,#4338ca)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-royal-range-bg-dark,color-mix(in_oklch,var(--zui-color-royal-dark,#818cf8)_28%,transparent))] data-[range-middle=true]:text-current",
  electric:
    "data-[selected=true]:bg-[var(--zui-calendar-electric-selected-bg,var(--zui-color-electric,#0ea5e9))] dark:data-[selected=true]:bg-[var(--zui-calendar-electric-selected-bg-dark,var(--zui-color-electric-dark,#38bdf8))] data-[selected=true]:text-[color:var(--zui-calendar-electric-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-electric-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-electric-range-bg,color-mix(in_oklch,var(--zui-color-electric,#0ea5e9)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-electric-range-bg-dark,color-mix(in_oklch,var(--zui-color-electric-dark,#38bdf8)_28%,transparent))] data-[range-middle=true]:text-current",
  forest:
    "data-[selected=true]:bg-[var(--zui-calendar-forest-selected-bg,var(--zui-color-forest,#166534))] dark:data-[selected=true]:bg-[var(--zui-calendar-forest-selected-bg-dark,var(--zui-color-forest-dark,#4ade80))] data-[selected=true]:text-[color:var(--zui-calendar-forest-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-forest-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-forest-range-bg,color-mix(in_oklch,var(--zui-color-forest,#166534)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-forest-range-bg-dark,color-mix(in_oklch,var(--zui-color-forest-dark,#4ade80)_28%,transparent))] data-[range-middle=true]:text-current",
  sunset:
    "data-[selected=true]:bg-[var(--zui-calendar-sunset-selected-bg,var(--zui-color-sunset,#ea580c))] dark:data-[selected=true]:bg-[var(--zui-calendar-sunset-selected-bg-dark,var(--zui-color-sunset-dark,#fb923c))] data-[selected=true]:text-[color:var(--zui-calendar-sunset-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-sunset-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-sunset-range-bg,color-mix(in_oklch,var(--zui-color-sunset,#ea580c)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-sunset-range-bg-dark,color-mix(in_oklch,var(--zui-color-sunset-dark,#fb923c)_28%,transparent))] data-[range-middle=true]:text-current",
  magenta:
    "data-[selected=true]:bg-[var(--zui-calendar-magenta-selected-bg,var(--zui-color-magenta,#c026d3))] dark:data-[selected=true]:bg-[var(--zui-calendar-magenta-selected-bg-dark,var(--zui-color-magenta-dark,#e879f9))] data-[selected=true]:text-[color:var(--zui-calendar-magenta-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-magenta-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-magenta-range-bg,color-mix(in_oklch,var(--zui-color-magenta,#c026d3)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-magenta-range-bg-dark,color-mix(in_oklch,var(--zui-color-magenta-dark,#e879f9)_28%,transparent))] data-[range-middle=true]:text-current",
  crimson:
    "data-[selected=true]:bg-[var(--zui-calendar-crimson-selected-bg,var(--zui-color-crimson,#b91c1c))] dark:data-[selected=true]:bg-[var(--zui-calendar-crimson-selected-bg-dark,var(--zui-color-crimson-dark,#f87171))] data-[selected=true]:text-[color:var(--zui-calendar-crimson-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-crimson-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-crimson-range-bg,color-mix(in_oklch,var(--zui-color-crimson,#b91c1c)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-crimson-range-bg-dark,color-mix(in_oklch,var(--zui-color-crimson-dark,#f87171)_28%,transparent))] data-[range-middle=true]:text-current",
  aqua: "data-[selected=true]:bg-[var(--zui-calendar-aqua-selected-bg,var(--zui-color-aqua,#0f766e))] dark:data-[selected=true]:bg-[var(--zui-calendar-aqua-selected-bg-dark,var(--zui-color-aqua-dark,#2dd4bf))] data-[selected=true]:text-[color:var(--zui-calendar-aqua-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-aqua-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-aqua-range-bg,color-mix(in_oklch,var(--zui-color-aqua,#0f766e)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-aqua-range-bg-dark,color-mix(in_oklch,var(--zui-color-aqua-dark,#2dd4bf)_28%,transparent))] data-[range-middle=true]:text-current",
  plum: "data-[selected=true]:bg-[var(--zui-calendar-plum-selected-bg,var(--zui-color-plum,#7e22ce))] dark:data-[selected=true]:bg-[var(--zui-calendar-plum-selected-bg-dark,var(--zui-color-plum-dark,#c084fc))] data-[selected=true]:text-[color:var(--zui-calendar-plum-selected-fg,var(--zui-brand-fg,#ffffff))] dark:data-[selected=true]:text-[color:var(--zui-calendar-plum-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-plum-range-bg,color-mix(in_oklch,var(--zui-color-plum,#7e22ce)_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-plum-range-bg-dark,color-mix(in_oklch,var(--zui-color-plum-dark,#c084fc)_28%,transparent))] data-[range-middle=true]:text-current",
  emerald:
    "data-[selected=true]:bg-[var(--zui-calendar-emerald-selected-bg,var(--zui-color-emerald,oklch(69.6%_0.17_162.48)))] dark:data-[selected=true]:bg-[var(--zui-calendar-emerald-selected-bg-dark,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913)))] data-[selected=true]:text-[color:var(--zui-calendar-emerald-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-emerald-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-emerald-range-bg,color-mix(in_oklch,var(--zui-color-emerald,oklch(69.6%_0.17_162.48))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-emerald-range-bg-dark,color-mix(in_oklch,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913))_28%,transparent))] data-[range-middle=true]:text-current",
  indigo:
    "data-[selected=true]:bg-[var(--zui-calendar-indigo-selected-bg,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:data-[selected=true]:bg-[var(--zui-calendar-indigo-selected-bg-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] data-[selected=true]:text-[color:var(--zui-calendar-indigo-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-indigo-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-indigo-range-bg,color-mix(in_oklch,var(--zui-color-indigo,oklch(39.8%_0.195_277.366))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-indigo-range-bg-dark,color-mix(in_oklch,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966))_28%,transparent))] data-[range-middle=true]:text-current",
  purple:
    "data-[selected=true]:bg-[var(--zui-calendar-purple-selected-bg,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:data-[selected=true]:bg-[var(--zui-calendar-purple-selected-bg-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:text-[color:var(--zui-calendar-purple-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-purple-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-purple-range-bg,color-mix(in_oklch,var(--zui-color-purple,oklch(43.8%_0.218_303.724))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-purple-range-bg-dark,color-mix(in_oklch,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321))_28%,transparent))] data-[range-middle=true]:text-current",
  pink: "data-[selected=true]:bg-[var(--zui-calendar-pink-selected-bg,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:data-[selected=true]:bg-[var(--zui-calendar-pink-selected-bg-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:text-[color:var(--zui-calendar-pink-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-pink-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-pink-range-bg,color-mix(in_oklch,var(--zui-color-pink,oklch(45.9%_0.187_3.815))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-pink-range-bg-dark,color-mix(in_oklch,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584))_28%,transparent))] data-[range-middle=true]:text-current",
  rose: "data-[selected=true]:bg-[var(--zui-calendar-rose-selected-bg,var(--zui-color-rose,oklch(64.5%_0.246_16.439)))] dark:data-[selected=true]:bg-[var(--zui-calendar-rose-selected-bg-dark,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935)))] data-[selected=true]:text-[color:var(--zui-calendar-rose-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-rose-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-rose-range-bg,color-mix(in_oklch,var(--zui-color-rose,oklch(64.5%_0.246_16.439))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-rose-range-bg-dark,color-mix(in_oklch,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935))_28%,transparent))] data-[range-middle=true]:text-current",
  sky: "data-[selected=true]:bg-[var(--zui-calendar-sky-selected-bg,var(--zui-color-sky,oklch(68.5%_0.169_237.323)))] dark:data-[selected=true]:bg-[var(--zui-calendar-sky-selected-bg-dark,var(--zui-color-sky-dark,oklch(50%_0.134_242.749)))] data-[selected=true]:text-[color:var(--zui-calendar-sky-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-sky-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-sky-range-bg,color-mix(in_oklch,var(--zui-color-sky,oklch(68.5%_0.169_237.323))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-sky-range-bg-dark,color-mix(in_oklch,var(--zui-color-sky-dark,oklch(50%_0.134_242.749))_28%,transparent))] data-[range-middle=true]:text-current",
  teal: "data-[selected=true]:bg-[var(--zui-calendar-teal-selected-bg,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:data-[selected=true]:bg-[var(--zui-calendar-teal-selected-bg-dark,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391)))] data-[selected=true]:text-[color:var(--zui-calendar-teal-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-teal-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-teal-range-bg,color-mix(in_oklch,var(--zui-color-teal,oklch(70.4%_0.14_182.503))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-teal-range-bg-dark,color-mix(in_oklch,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391))_28%,transparent))] data-[range-middle=true]:text-current",
  yellow:
    "data-[selected=true]:bg-[var(--zui-calendar-yellow-selected-bg,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:data-[selected=true]:bg-[var(--zui-calendar-yellow-selected-bg-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] data-[selected=true]:text-[color:var(--zui-calendar-yellow-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-yellow-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-yellow-range-bg,color-mix(in_oklch,var(--zui-color-yellow,oklch(79.5%_0.184_86.047))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-yellow-range-bg-dark,color-mix(in_oklch,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907))_28%,transparent))] data-[range-middle=true]:text-current",
  orange:
    "data-[selected=true]:bg-[var(--zui-calendar-orange-selected-bg,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:data-[selected=true]:bg-[var(--zui-calendar-orange-selected-bg-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] data-[selected=true]:text-[color:var(--zui-calendar-orange-selected-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-orange-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-orange-range-bg,color-mix(in_oklch,var(--zui-color-orange,oklch(70.5%_0.213_47.604))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-orange-range-bg-dark,color-mix(in_oklch,var(--zui-color-orange-dark,oklch(47%_0.157_37.304))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-blue":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] data-[selected=true]:to-[var(--zui-calendar-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-blue-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-blue-range-bg,color-mix(in_oklch,var(--zui-color-blue,oklch(42.4%_0.199_265.638))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-blue-range-bg-dark,color-mix(in_oklch,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-green":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] data-[selected=true]:to-[var(--zui-calendar-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-green-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-green-range-bg,color-mix(in_oklch,var(--zui-color-green,oklch(44.8%_0.119_151.328))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-green-range-bg-dark,color-mix(in_oklch,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-red":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] data-[selected=true]:to-[var(--zui-calendar-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-red-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-red-range-bg,color-mix(in_oklch,var(--zui-color-red,oklch(44.4%_0.177_26.899))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-red-range-bg-dark,color-mix(in_oklch,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-yellow":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] data-[selected=true]:to-[var(--zui-calendar-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-yellow-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-yellow-range-bg,color-mix(in_oklch,var(--zui-color-yellow,oklch(47.6%_0.114_61.907))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-yellow-range-bg-dark,color-mix(in_oklch,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-purple":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:to-[var(--zui-calendar-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-purple-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-purple-range-bg,color-mix(in_oklch,var(--zui-color-purple,oklch(43.8%_0.218_303.724))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-purple-range-bg-dark,color-mix(in_oklch,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-teal":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] data-[selected=true]:to-[var(--zui-calendar-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-teal-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-teal-range-bg,color-mix(in_oklch,var(--zui-color-teal,oklch(43.7%_0.078_188.216))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-teal-range-bg-dark,color-mix(in_oklch,var(--zui-color-teal-dark,oklch(60%_0.118_184.704))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-indigo":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] data-[selected=true]:to-[var(--zui-calendar-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-indigo-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-indigo-range-bg,color-mix(in_oklch,var(--zui-color-indigo,oklch(39.8%_0.195_277.366))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-indigo-range-bg-dark,color-mix(in_oklch,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-pink":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:to-[var(--zui-calendar-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-pink-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-pink-range-bg,color-mix(in_oklch,var(--zui-color-pink,oklch(45.9%_0.187_3.815))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-pink-range-bg-dark,color-mix(in_oklch,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584))_28%,transparent))] data-[range-middle=true]:text-current",
  "gradient-orange":
    "data-[selected=true]:bg-linear-to-br data-[selected=true]:from-[var(--zui-calendar-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:data-[selected=true]:from-[var(--zui-calendar-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] data-[selected=true]:to-[var(--zui-calendar-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:data-[selected=true]:to-[var(--zui-calendar-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] data-[selected=true]:text-[color:var(--zui-calendar-gradient-orange-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:data-[selected=true]:text-[color:var(--zui-calendar-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))] data-[range-middle=true]:bg-[var(--zui-calendar-gradient-orange-range-bg,color-mix(in_oklch,var(--zui-color-orange,oklch(47%_0.157_37.304))_18%,transparent))] dark:data-[range-middle=true]:bg-[var(--zui-calendar-gradient-orange-range-bg-dark,color-mix(in_oklch,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116))_28%,transparent))] data-[range-middle=true]:text-current",
} as const;

export type ZuiCalendarDayAppearance = keyof typeof zuiCalendarDayAppearances;
