// Literal strings preserve all theme tokens in consumer Tailwind scan scope.
export const zuiChangeImpactExplorerBase =
  "@container/zui-impact min-w-0 max-w-full overflow-hidden border-solid rounded-[var(--zui-change-impact-explorer-radius,1rem)] dark:rounded-[var(--zui-change-impact-explorer-radius-dark,1rem)] border-[length:var(--zui-change-impact-explorer-border-width,1px)] dark:border-[length:var(--zui-change-impact-explorer-border-width-dark,1px)]";
export const zuiChangeImpactExplorerHeader =
  "flex flex-wrap items-end justify-between gap-4 border-b border-current/15 p-[var(--zui-change-impact-explorer-padding,1rem)] dark:p-[var(--zui-change-impact-explorer-padding-dark,1rem)]";
export const zuiChangeImpactExplorerControls =
  "grid w-full min-w-0 gap-3 @min-[36rem]/zui-impact:flex @min-[36rem]/zui-impact:w-auto @min-[36rem]/zui-impact:flex-wrap @min-[36rem]/zui-impact:items-end";
export const zuiChangeImpactExplorerControl =
  "w-full min-w-0 max-w-full rounded-md border border-current/25 bg-transparent px-3 py-2 text-inherit outline-none focus-visible:outline-solid focus-visible:outline-[length:var(--zui-change-impact-explorer-focus-width,2px)] dark:focus-visible:outline-[length:var(--zui-change-impact-explorer-focus-width-dark,2px)] focus-visible:outline-offset-[var(--zui-change-impact-explorer-focus-offset,2px)] dark:focus-visible:outline-offset-[var(--zui-change-impact-explorer-focus-offset-dark,2px)] focus-visible:outline-[color:var(--zui-change-impact-explorer-focus-ring,currentColor)] dark:focus-visible:outline-[color:var(--zui-change-impact-explorer-focus-ring-dark,currentColor)]";
export const zuiChangeImpactExplorerSummary =
  "grid grid-cols-2 gap-3 @min-[36rem]/zui-impact:grid-cols-4 p-[var(--zui-change-impact-explorer-padding,1rem)] dark:p-[var(--zui-change-impact-explorer-padding-dark,1rem)]";
export const zuiChangeImpactExplorerStat =
  "min-w-0 rounded-lg border border-current/15 bg-current/5 p-3";
export const zuiChangeImpactExplorerMap =
  "overflow-auto max-h-[var(--zui-change-impact-explorer-map-height,24rem)] dark:max-h-[var(--zui-change-impact-explorer-map-height-dark,24rem)] border-y border-current/15 p-[var(--zui-change-impact-explorer-padding,1rem)] dark:p-[var(--zui-change-impact-explorer-padding-dark,1rem)]";
export const zuiChangeImpactExplorerLane = "min-w-0 flex-1 space-y-3";
export const zuiChangeImpactExplorerNode =
  "flex w-full min-w-0 flex-col gap-1 rounded-lg border border-current/20 bg-transparent p-3 text-start text-inherit transition-colors motion-reduce:transition-none hover:bg-current/10 outline-none focus-visible:outline-solid aria-pressed:border-current aria-pressed:bg-current/10 focus-visible:outline-[length:var(--zui-change-impact-explorer-focus-width,2px)] dark:focus-visible:outline-[length:var(--zui-change-impact-explorer-focus-width-dark,2px)] focus-visible:outline-offset-[var(--zui-change-impact-explorer-focus-offset,2px)] dark:focus-visible:outline-offset-[var(--zui-change-impact-explorer-focus-offset-dark,2px)] focus-visible:outline-[color:var(--zui-change-impact-explorer-focus-ring,currentColor)] dark:focus-visible:outline-[color:var(--zui-change-impact-explorer-focus-ring-dark,currentColor)]";
export const zuiChangeImpactExplorerBody =
  "grid min-w-0 gap-0 @min-[44rem]/zui-impact:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]";
export const zuiChangeImpactExplorerResults =
  "min-w-0 p-[var(--zui-change-impact-explorer-padding,1rem)] dark:p-[var(--zui-change-impact-explorer-padding-dark,1rem)]";
export const zuiChangeImpactExplorerList =
  "relative overflow-y-auto rounded-lg border border-current/20 outline-none focus-visible:outline-solid focus-visible:outline-[length:var(--zui-change-impact-explorer-focus-width,2px)] dark:focus-visible:outline-[length:var(--zui-change-impact-explorer-focus-width-dark,2px)] focus-visible:outline-offset-[var(--zui-change-impact-explorer-focus-offset,2px)] dark:focus-visible:outline-offset-[var(--zui-change-impact-explorer-focus-offset-dark,2px)] focus-visible:outline-[color:var(--zui-change-impact-explorer-focus-ring,currentColor)] dark:focus-visible:outline-[color:var(--zui-change-impact-explorer-focus-ring-dark,currentColor)]";
export const zuiChangeImpactExplorerItem =
  "flex w-full min-w-0 cursor-pointer items-center justify-between gap-3 border-b border-current/10 px-3 py-2 text-start hover:bg-current/5 aria-selected:shadow-[inset_3px_0_0_currentColor] aria-selected:bg-[var(--zui-change-impact-explorer-selected-bg,#64748b1a)] dark:aria-selected:bg-[var(--zui-change-impact-explorer-selected-bg-dark,#64748b1a)]";
export const zuiChangeImpactExplorerDetails =
  "min-w-0 border-t border-current/15 @min-[44rem]/zui-impact:border-t-0 @min-[44rem]/zui-impact:border-s p-[var(--zui-change-impact-explorer-padding,1rem)] dark:p-[var(--zui-change-impact-explorer-padding-dark,1rem)]";
export const zuiChangeImpactExplorerPath =
  "space-y-3 border-s-2 border-current/20 ps-4";
export const zuiChangeImpactExplorerComparison =
  "grid min-w-0 gap-3 @min-[28rem]/zui-impact:grid-cols-2";
export const zuiChangeImpactExplorerValue =
  "min-w-0 overflow-auto rounded-lg border border-current/15 bg-current/5 p-3 whitespace-pre-wrap break-words";
export const zuiChangeImpactExplorerBadge =
  "inline-flex shrink-0 items-center rounded-full border border-current/20 px-2 py-0.5 text-xs";
export const zuiChangeImpactExplorerEmpty =
  "p-6 text-center text-sm opacity-80";
export const zuiChangeImpactExplorerSizes = {
  sm: "text-[length:var(--zui-change-impact-explorer-font-size-sm,0.75rem)] dark:text-[length:var(--zui-change-impact-explorer-font-size-sm-dark,0.75rem)]",
  md: "text-[length:var(--zui-change-impact-explorer-font-size-md,0.875rem)] dark:text-[length:var(--zui-change-impact-explorer-font-size-md-dark,0.875rem)]",
  lg: "text-[length:var(--zui-change-impact-explorer-font-size-lg,1rem)] dark:text-[length:var(--zui-change-impact-explorer-font-size-lg-dark,1rem)]",
} as const;
export const zuiChangeImpactExplorerAppearances = {
  default:
    "bg-[var(--zui-change-impact-explorer-default-bg,#ffffff)] dark:bg-[var(--zui-change-impact-explorer-default-bg-dark,#0f172a)] text-[color:var(--zui-change-impact-explorer-default-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-default-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-default-border,#e2e8f0)] dark:border-[color:var(--zui-change-impact-explorer-default-border-dark,#334155)]",
  subtle:
    "bg-[var(--zui-change-impact-explorer-subtle-bg,#f8fafc)] dark:bg-[var(--zui-change-impact-explorer-subtle-bg-dark,#1e293b)] text-[color:var(--zui-change-impact-explorer-subtle-fg,#334155)] dark:text-[color:var(--zui-change-impact-explorer-subtle-fg-dark,#e2e8f0)] border-[color:var(--zui-change-impact-explorer-subtle-border,#e2e8f0)] dark:border-[color:var(--zui-change-impact-explorer-subtle-border-dark,#334155)]",
  contrast:
    "bg-[var(--zui-change-impact-explorer-contrast-bg,#0f172a)] dark:bg-[var(--zui-change-impact-explorer-contrast-bg-dark,#f8fafc)] text-[color:var(--zui-change-impact-explorer-contrast-fg,#f8fafc)] dark:text-[color:var(--zui-change-impact-explorer-contrast-fg-dark,#0f172a)] border-[color:var(--zui-change-impact-explorer-contrast-border,#334155)] dark:border-[color:var(--zui-change-impact-explorer-contrast-border-dark,#cbd5e1)]",
  glass:
    "bg-[var(--zui-change-impact-explorer-glass-bg,#ffffffb3)] dark:bg-[var(--zui-change-impact-explorer-glass-bg-dark,#0f172ab3)] text-[color:var(--zui-change-impact-explorer-glass-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-glass-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-glass-border,#cbd5e1)] dark:border-[color:var(--zui-change-impact-explorer-glass-border-dark,#475569)] backdrop-blur-[var(--zui-change-impact-explorer-glass-blur,12px)] dark:backdrop-blur-[var(--zui-change-impact-explorer-glass-blur-dark,12px)]",
  blue: "bg-[var(--zui-change-impact-explorer-blue-bg,#eff6ff)] dark:bg-[var(--zui-change-impact-explorer-blue-bg-dark,#172554)] text-[color:var(--zui-change-impact-explorer-blue-fg,#1e40af)] dark:text-[color:var(--zui-change-impact-explorer-blue-fg-dark,#dbeafe)] border-[color:var(--zui-change-impact-explorer-blue-border,#bfdbfe)] dark:border-[color:var(--zui-change-impact-explorer-blue-border-dark,#1e40af)]",
  cyan: "bg-[var(--zui-change-impact-explorer-cyan-bg,#ecfeff)] dark:bg-[var(--zui-change-impact-explorer-cyan-bg-dark,#083344)] text-[color:var(--zui-change-impact-explorer-cyan-fg,#155e75)] dark:text-[color:var(--zui-change-impact-explorer-cyan-fg-dark,#cffafe)] border-[color:var(--zui-change-impact-explorer-cyan-border,#a5f3fc)] dark:border-[color:var(--zui-change-impact-explorer-cyan-border-dark,#155e75)]",
  green:
    "bg-[var(--zui-change-impact-explorer-green-bg,#f0fdf4)] dark:bg-[var(--zui-change-impact-explorer-green-bg-dark,#052e16)] text-[color:var(--zui-change-impact-explorer-green-fg,#166534)] dark:text-[color:var(--zui-change-impact-explorer-green-fg-dark,#dcfce7)] border-[color:var(--zui-change-impact-explorer-green-border,#bbf7d0)] dark:border-[color:var(--zui-change-impact-explorer-green-border-dark,#166534)]",
  lime: "bg-[var(--zui-change-impact-explorer-lime-bg,#f7fee7)] dark:bg-[var(--zui-change-impact-explorer-lime-bg-dark,#1a2e05)] text-[color:var(--zui-change-impact-explorer-lime-fg,#3f6212)] dark:text-[color:var(--zui-change-impact-explorer-lime-fg-dark,#ecfccb)] border-[color:var(--zui-change-impact-explorer-lime-border,#d9f99d)] dark:border-[color:var(--zui-change-impact-explorer-lime-border-dark,#3f6212)]",
  emerald:
    "bg-[var(--zui-change-impact-explorer-emerald-bg,#ecfdf5)] dark:bg-[var(--zui-change-impact-explorer-emerald-bg-dark,#022c22)] text-[color:var(--zui-change-impact-explorer-emerald-fg,#065f46)] dark:text-[color:var(--zui-change-impact-explorer-emerald-fg-dark,#d1fae5)] border-[color:var(--zui-change-impact-explorer-emerald-border,#a7f3d0)] dark:border-[color:var(--zui-change-impact-explorer-emerald-border-dark,#065f46)]",
  indigo:
    "bg-[var(--zui-change-impact-explorer-indigo-bg,#eef2ff)] dark:bg-[var(--zui-change-impact-explorer-indigo-bg-dark,#1e1b4b)] text-[color:var(--zui-change-impact-explorer-indigo-fg,#3730a3)] dark:text-[color:var(--zui-change-impact-explorer-indigo-fg-dark,#e0e7ff)] border-[color:var(--zui-change-impact-explorer-indigo-border,#c7d2fe)] dark:border-[color:var(--zui-change-impact-explorer-indigo-border-dark,#3730a3)]",
  purple:
    "bg-[var(--zui-change-impact-explorer-purple-bg,#faf5ff)] dark:bg-[var(--zui-change-impact-explorer-purple-bg-dark,#3b0764)] text-[color:var(--zui-change-impact-explorer-purple-fg,#6b21a8)] dark:text-[color:var(--zui-change-impact-explorer-purple-fg-dark,#f3e8ff)] border-[color:var(--zui-change-impact-explorer-purple-border,#e9d5ff)] dark:border-[color:var(--zui-change-impact-explorer-purple-border-dark,#6b21a8)]",
  pink: "bg-[var(--zui-change-impact-explorer-pink-bg,#fdf2f8)] dark:bg-[var(--zui-change-impact-explorer-pink-bg-dark,#500724)] text-[color:var(--zui-change-impact-explorer-pink-fg,#9d174d)] dark:text-[color:var(--zui-change-impact-explorer-pink-fg-dark,#fce7f3)] border-[color:var(--zui-change-impact-explorer-pink-border,#fbcfe8)] dark:border-[color:var(--zui-change-impact-explorer-pink-border-dark,#9d174d)]",
  rose: "bg-[var(--zui-change-impact-explorer-rose-bg,#fff1f2)] dark:bg-[var(--zui-change-impact-explorer-rose-bg-dark,#4c0519)] text-[color:var(--zui-change-impact-explorer-rose-fg,#9f1239)] dark:text-[color:var(--zui-change-impact-explorer-rose-fg-dark,#ffe4e6)] border-[color:var(--zui-change-impact-explorer-rose-border,#fecdd3)] dark:border-[color:var(--zui-change-impact-explorer-rose-border-dark,#9f1239)]",
  sky: "bg-[var(--zui-change-impact-explorer-sky-bg,#f0f9ff)] dark:bg-[var(--zui-change-impact-explorer-sky-bg-dark,#082f49)] text-[color:var(--zui-change-impact-explorer-sky-fg,#075985)] dark:text-[color:var(--zui-change-impact-explorer-sky-fg-dark,#e0f2fe)] border-[color:var(--zui-change-impact-explorer-sky-border,#bae6fd)] dark:border-[color:var(--zui-change-impact-explorer-sky-border-dark,#075985)]",
  teal: "bg-[var(--zui-change-impact-explorer-teal-bg,#f0fdfa)] dark:bg-[var(--zui-change-impact-explorer-teal-bg-dark,#042f2e)] text-[color:var(--zui-change-impact-explorer-teal-fg,#115e59)] dark:text-[color:var(--zui-change-impact-explorer-teal-fg-dark,#ccfbf1)] border-[color:var(--zui-change-impact-explorer-teal-border,#99f6e4)] dark:border-[color:var(--zui-change-impact-explorer-teal-border-dark,#115e59)]",
  yellow:
    "bg-[var(--zui-change-impact-explorer-yellow-bg,#fefce8)] dark:bg-[var(--zui-change-impact-explorer-yellow-bg-dark,#422006)] text-[color:var(--zui-change-impact-explorer-yellow-fg,#854d0e)] dark:text-[color:var(--zui-change-impact-explorer-yellow-fg-dark,#fef9c3)] border-[color:var(--zui-change-impact-explorer-yellow-border,#fef08a)] dark:border-[color:var(--zui-change-impact-explorer-yellow-border-dark,#854d0e)]",
  orange:
    "bg-[var(--zui-change-impact-explorer-orange-bg,#fff7ed)] dark:bg-[var(--zui-change-impact-explorer-orange-bg-dark,#431407)] text-[color:var(--zui-change-impact-explorer-orange-fg,#9a3412)] dark:text-[color:var(--zui-change-impact-explorer-orange-fg-dark,#ffedd5)] border-[color:var(--zui-change-impact-explorer-orange-border,#fed7aa)] dark:border-[color:var(--zui-change-impact-explorer-orange-border-dark,#9a3412)]",
  red: "bg-[var(--zui-change-impact-explorer-red-bg,#fef2f2)] dark:bg-[var(--zui-change-impact-explorer-red-bg-dark,#450a0a)] text-[color:var(--zui-change-impact-explorer-red-fg,#991b1b)] dark:text-[color:var(--zui-change-impact-explorer-red-fg-dark,#fee2e2)] border-[color:var(--zui-change-impact-explorer-red-border,#fecaca)] dark:border-[color:var(--zui-change-impact-explorer-red-border-dark,#991b1b)]",
  slate:
    "bg-[var(--zui-change-impact-explorer-slate-bg,#f8fafc)] dark:bg-[var(--zui-change-impact-explorer-slate-bg-dark,#0f172a)] text-[color:var(--zui-change-impact-explorer-slate-fg,#334155)] dark:text-[color:var(--zui-change-impact-explorer-slate-fg-dark,#f1f5f9)] border-[color:var(--zui-change-impact-explorer-slate-border,#cbd5e1)] dark:border-[color:var(--zui-change-impact-explorer-slate-border-dark,#334155)]",
  gray: "bg-[var(--zui-change-impact-explorer-gray-bg,#f9fafb)] dark:bg-[var(--zui-change-impact-explorer-gray-bg-dark,#111827)] text-[color:var(--zui-change-impact-explorer-gray-fg,#374151)] dark:text-[color:var(--zui-change-impact-explorer-gray-fg-dark,#f3f4f6)] border-[color:var(--zui-change-impact-explorer-gray-border,#d1d5db)] dark:border-[color:var(--zui-change-impact-explorer-gray-border-dark,#374151)]",
  zinc: "bg-[var(--zui-change-impact-explorer-zinc-bg,#fafafa)] dark:bg-[var(--zui-change-impact-explorer-zinc-bg-dark,#18181b)] text-[color:var(--zui-change-impact-explorer-zinc-fg,#3f3f46)] dark:text-[color:var(--zui-change-impact-explorer-zinc-fg-dark,#f4f4f5)] border-[color:var(--zui-change-impact-explorer-zinc-border,#d4d4d8)] dark:border-[color:var(--zui-change-impact-explorer-zinc-border-dark,#3f3f46)]",
  "gradient-blue":
    "bg-linear-to-br from-[var(--zui-change-impact-explorer-gradient-blue-from,#eff6ff)] dark:from-[var(--zui-change-impact-explorer-gradient-blue-from-dark,#172554)] to-[var(--zui-change-impact-explorer-gradient-blue-to,#faf5ff)] dark:to-[var(--zui-change-impact-explorer-gradient-blue-to-dark,#3b0764)] text-[color:var(--zui-change-impact-explorer-gradient-blue-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-gradient-blue-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-gradient-blue-border,#bfdbfe)] dark:border-[color:var(--zui-change-impact-explorer-gradient-blue-border-dark,#1e40af)]",
  "gradient-green":
    "bg-linear-to-br from-[var(--zui-change-impact-explorer-gradient-green-from,#f0fdf4)] dark:from-[var(--zui-change-impact-explorer-gradient-green-from-dark,#052e16)] to-[var(--zui-change-impact-explorer-gradient-green-to,#f7fee7)] dark:to-[var(--zui-change-impact-explorer-gradient-green-to-dark,#1a2e05)] text-[color:var(--zui-change-impact-explorer-gradient-green-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-gradient-green-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-gradient-green-border,#bbf7d0)] dark:border-[color:var(--zui-change-impact-explorer-gradient-green-border-dark,#166534)]",
  "gradient-purple":
    "bg-linear-to-br from-[var(--zui-change-impact-explorer-gradient-purple-from,#faf5ff)] dark:from-[var(--zui-change-impact-explorer-gradient-purple-from-dark,#3b0764)] to-[var(--zui-change-impact-explorer-gradient-purple-to,#fdf2f8)] dark:to-[var(--zui-change-impact-explorer-gradient-purple-to-dark,#500724)] text-[color:var(--zui-change-impact-explorer-gradient-purple-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-gradient-purple-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-gradient-purple-border,#e9d5ff)] dark:border-[color:var(--zui-change-impact-explorer-gradient-purple-border-dark,#6b21a8)]",
  "gradient-orange":
    "bg-linear-to-br from-[var(--zui-change-impact-explorer-gradient-orange-from,#fff7ed)] dark:from-[var(--zui-change-impact-explorer-gradient-orange-from-dark,#431407)] to-[var(--zui-change-impact-explorer-gradient-orange-to,#fefce8)] dark:to-[var(--zui-change-impact-explorer-gradient-orange-to-dark,#422006)] text-[color:var(--zui-change-impact-explorer-gradient-orange-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-gradient-orange-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-gradient-orange-border,#fed7aa)] dark:border-[color:var(--zui-change-impact-explorer-gradient-orange-border-dark,#9a3412)]",
  "gradient-pink":
    "bg-linear-to-br from-[var(--zui-change-impact-explorer-gradient-pink-from,#fdf2f8)] dark:from-[var(--zui-change-impact-explorer-gradient-pink-from-dark,#500724)] to-[var(--zui-change-impact-explorer-gradient-pink-to,#fff1f2)] dark:to-[var(--zui-change-impact-explorer-gradient-pink-to-dark,#4c0519)] text-[color:var(--zui-change-impact-explorer-gradient-pink-fg,#0f172a)] dark:text-[color:var(--zui-change-impact-explorer-gradient-pink-fg-dark,#f8fafc)] border-[color:var(--zui-change-impact-explorer-gradient-pink-border,#fbcfe8)] dark:border-[color:var(--zui-change-impact-explorer-gradient-pink-border-dark,#9d174d)]",
} as const;
