export const zuiCheckboxRootBase =
  "group inline-flex w-fit items-start gap-2.5 text-sm font-medium text-[color:var(--zui-checkbox-label-fg,oklch(20.8%_0.042_265.755))] dark:text-[color:var(--zui-checkbox-label-fg-dark,oklch(98.4%_0.003_247.858))] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiCheckboxControlBase =
  "grid shrink-0 place-items-center rounded-md border-2 border-[color:var(--zui-checkbox-border,#0000004d)] bg-[var(--zui-checkbox-bg,transparent)] dark:bg-[var(--zui-checkbox-bg-dark,transparent)] text-[color:var(--zui-checkbox-fg,oklch(44.6%_0.043_257.281))] transition-[background-color,border-color,color,box-shadow] peer-focus-visible:outline-none peer-focus-visible:ring-2 peer-focus-visible:ring-[var(--zui-checkbox-ring-focus,oklch(44.6%_0.043_257.281_/_0.7))] peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-[var(--zui-checkbox-ring-offset-focus,oklch(98.4%_0.003_247.858))] dark:border-[color:var(--zui-checkbox-border-dark,#ffffff4d)] dark:text-[color:var(--zui-checkbox-fg-dark,oklch(92.9%_0.013_255.508))] dark:peer-focus-visible:ring-[var(--zui-checkbox-ring-focus-dark,oklch(86.9%_0.022_252.894_/_0.7))] dark:peer-focus-visible:ring-offset-[var(--zui-checkbox-ring-offset-focus-dark,oklch(12.9%_0.042_264.695))] group-data-[disabled=true]:cursor-not-allowed";

export const zuiCheckboxIndicatorBase =
  "pointer-events-none opacity-0 transition-opacity duration-150 stroke-current group-data-[state=checked]:opacity-100 group-data-[state=indeterminate]:opacity-100";

export const zuiCheckboxSizes = {
  sm: {
    root: "text-xs",
    control: "mt-0.5 size-4 rounded-[0.35rem]",
    indicator: "size-3",
  },
  md: {
    root: "text-sm",
    control: "mt-0.5 size-5",
    indicator: "size-3.5",
  },
  lg: {
    root: "text-base",
    control: "mt-0.5 size-6",
    indicator: "size-4",
  },
} as const;

export const zuiCheckboxAppearances = {
  default:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-default-border-checked,oklch(44.6%_0.043_257.281))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-default-border-checked-dark,oklch(44.6%_0.043_257.281))] group-data-[state=checked]:bg-[var(--zui-checkbox-default-bg-checked,oklch(44.6%_0.043_257.281))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-default-bg-checked-dark,oklch(44.6%_0.043_257.281))] group-data-[state=checked]:text-[color:var(--zui-checkbox-default-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-default-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-default-border-checked,oklch(44.6%_0.043_257.281))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-default-border-checked-dark,oklch(44.6%_0.043_257.281))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-default-bg-checked,oklch(44.6%_0.043_257.281))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-default-bg-checked-dark,oklch(44.6%_0.043_257.281))] group-data-[state=indeterminate]:text-[color:var(--zui-checkbox-default-fg-checked,#ffffff)] dark:group-data-[state=indeterminate]:text-[color:var(--zui-checkbox-default-fg-checked-dark,#ffffff)]",
  success:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-success-border-checked,oklch(59.6%_0.145_163.225))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-success-border-checked-dark,oklch(59.6%_0.145_163.225))] group-data-[state=checked]:bg-[var(--zui-checkbox-success-bg-checked,oklch(59.6%_0.145_163.225))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-success-bg-checked-dark,oklch(59.6%_0.145_163.225))] group-data-[state=checked]:text-[color:var(--zui-checkbox-success-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-success-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-success-border-checked,oklch(59.6%_0.145_163.225))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-success-border-checked-dark,oklch(59.6%_0.145_163.225))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-success-bg-checked,oklch(59.6%_0.145_163.225))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-success-bg-checked-dark,oklch(59.6%_0.145_163.225))]",
  warning:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-warning-border-checked,oklch(68.1%_0.162_75.834))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-warning-border-checked-dark,oklch(68.1%_0.162_75.834))] group-data-[state=checked]:bg-[var(--zui-checkbox-warning-bg-checked,oklch(68.1%_0.162_75.834))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-warning-bg-checked-dark,oklch(68.1%_0.162_75.834))] group-data-[state=checked]:text-[color:var(--zui-checkbox-warning-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-warning-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-warning-border-checked,oklch(68.1%_0.162_75.834))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-warning-border-checked-dark,oklch(68.1%_0.162_75.834))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-warning-bg-checked,oklch(68.1%_0.162_75.834))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-warning-bg-checked-dark,oklch(68.1%_0.162_75.834))]",
  error:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-error-border-checked,oklch(58.6%_0.253_17.585))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-error-border-checked-dark,oklch(58.6%_0.253_17.585))] group-data-[state=checked]:bg-[var(--zui-checkbox-error-bg-checked,oklch(58.6%_0.253_17.585))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-error-bg-checked-dark,oklch(58.6%_0.253_17.585))] group-data-[state=checked]:text-[color:var(--zui-checkbox-error-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-error-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-error-border-checked,oklch(58.6%_0.253_17.585))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-error-border-checked-dark,oklch(58.6%_0.253_17.585))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-error-bg-checked,oklch(58.6%_0.253_17.585))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-error-bg-checked-dark,oklch(58.6%_0.253_17.585))]",
  info: "group-data-[state=checked]:border-[color:var(--zui-checkbox-info-border-checked,oklch(54.6%_0.245_262.881))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-info-border-checked-dark,oklch(54.6%_0.245_262.881))] group-data-[state=checked]:bg-[var(--zui-checkbox-info-bg-checked,oklch(54.6%_0.245_262.881))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-info-bg-checked-dark,oklch(54.6%_0.245_262.881))] group-data-[state=checked]:text-[color:var(--zui-checkbox-info-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-info-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-info-border-checked,oklch(54.6%_0.245_262.881))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-info-border-checked-dark,oklch(54.6%_0.245_262.881))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-info-bg-checked,oklch(54.6%_0.245_262.881))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-info-bg-checked-dark,oklch(54.6%_0.245_262.881))]",
  blue: "group-data-[state=checked]:border-[color:var(--zui-checkbox-blue-border-checked,#2563eb)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-blue-border-checked-dark,#3b82f6)] group-data-[state=checked]:bg-[var(--zui-checkbox-blue-bg-checked,#2563eb)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-blue-bg-checked-dark,#3b82f6)] group-data-[state=checked]:text-[color:var(--zui-checkbox-blue-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-blue-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-blue-border-checked,#2563eb)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-blue-border-checked-dark,#3b82f6)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-blue-bg-checked,#2563eb)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-blue-bg-checked-dark,#3b82f6)]",
  cyan: "group-data-[state=checked]:border-[color:var(--zui-checkbox-cyan-border-checked,#0891b2)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-cyan-border-checked-dark,#22d3ee)] group-data-[state=checked]:bg-[var(--zui-checkbox-cyan-bg-checked,#0891b2)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-cyan-bg-checked-dark,#22d3ee)] group-data-[state=checked]:text-[color:var(--zui-checkbox-cyan-fg-checked,#083344)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-cyan-fg-checked-dark,#083344)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-cyan-border-checked,#0891b2)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-cyan-border-checked-dark,#22d3ee)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-cyan-bg-checked,#0891b2)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-cyan-bg-checked-dark,#22d3ee)]",
  green:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-green-border-checked,#16a34a)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-green-border-checked-dark,#22c55e)] group-data-[state=checked]:bg-[var(--zui-checkbox-green-bg-checked,#16a34a)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-green-bg-checked-dark,#22c55e)] group-data-[state=checked]:text-[color:var(--zui-checkbox-green-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-green-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-green-border-checked,#16a34a)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-green-border-checked-dark,#22c55e)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-green-bg-checked,#16a34a)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-green-bg-checked-dark,#22c55e)]",
  lime: "group-data-[state=checked]:border-[color:var(--zui-checkbox-lime-border-checked,#65a30d)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-lime-border-checked-dark,#a3e635)] group-data-[state=checked]:bg-[var(--zui-checkbox-lime-bg-checked,#65a30d)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-lime-bg-checked-dark,#a3e635)] group-data-[state=checked]:text-[color:var(--zui-checkbox-lime-fg-checked,#1a2e05)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-lime-fg-checked-dark,#1a2e05)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lime-border-checked,#65a30d)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lime-border-checked-dark,#a3e635)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lime-bg-checked,#65a30d)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lime-bg-checked-dark,#a3e635)]",
  mint: "group-data-[state=checked]:border-[color:var(--zui-checkbox-mint-border-checked,#10b981)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-mint-border-checked-dark,#6ee7b7)] group-data-[state=checked]:bg-[var(--zui-checkbox-mint-bg-checked,#10b981)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-mint-bg-checked-dark,#6ee7b7)] group-data-[state=checked]:text-[color:var(--zui-checkbox-mint-fg-checked,#064e3b)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-mint-fg-checked-dark,#064e3b)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-mint-border-checked,#10b981)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-mint-border-checked-dark,#6ee7b7)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-mint-bg-checked,#10b981)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-mint-bg-checked-dark,#6ee7b7)]",
  ocean:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-ocean-border-checked,#0284c7)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-ocean-border-checked-dark,#38bdf8)] group-data-[state=checked]:bg-[var(--zui-checkbox-ocean-bg-checked,#0284c7)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-ocean-bg-checked-dark,#38bdf8)] group-data-[state=checked]:text-[color:var(--zui-checkbox-ocean-fg-checked,#082f49)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-ocean-fg-checked-dark,#082f49)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ocean-border-checked,#0284c7)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ocean-border-checked-dark,#38bdf8)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ocean-bg-checked,#0284c7)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ocean-bg-checked-dark,#38bdf8)]",
  sapphire:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-sapphire-border-checked,#1d4ed8)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-sapphire-border-checked-dark,#60a5fa)] group-data-[state=checked]:bg-[var(--zui-checkbox-sapphire-bg-checked,#1d4ed8)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-sapphire-bg-checked-dark,#60a5fa)] group-data-[state=checked]:text-[color:var(--zui-checkbox-sapphire-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-sapphire-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sapphire-border-checked,#1d4ed8)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sapphire-border-checked-dark,#60a5fa)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sapphire-bg-checked,#1d4ed8)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sapphire-bg-checked-dark,#60a5fa)]",
  lavender:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-lavender-border-checked,#8b5cf6)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-lavender-border-checked-dark,#a78bfa)] group-data-[state=checked]:bg-[var(--zui-checkbox-lavender-bg-checked,#8b5cf6)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-lavender-bg-checked-dark,#a78bfa)] group-data-[state=checked]:text-[color:var(--zui-checkbox-lavender-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-lavender-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lavender-border-checked,#8b5cf6)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lavender-border-checked-dark,#a78bfa)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lavender-bg-checked,#8b5cf6)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lavender-bg-checked-dark,#a78bfa)]",
  ruby: "group-data-[state=checked]:border-[color:var(--zui-checkbox-ruby-border-checked,#be123c)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-ruby-border-checked-dark,#fb7185)] group-data-[state=checked]:bg-[var(--zui-checkbox-ruby-bg-checked,#be123c)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-ruby-bg-checked-dark,#fb7185)] group-data-[state=checked]:text-[color:var(--zui-checkbox-ruby-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-ruby-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ruby-border-checked,#be123c)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ruby-border-checked-dark,#fb7185)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ruby-bg-checked,#be123c)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ruby-bg-checked-dark,#fb7185)]",
  red: "group-data-[state=checked]:border-[color:var(--zui-checkbox-red-border-checked,#dc2626)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-red-border-checked-dark,#ef4444)] group-data-[state=checked]:bg-[var(--zui-checkbox-red-bg-checked,#dc2626)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-red-bg-checked-dark,#ef4444)] group-data-[state=checked]:text-[color:var(--zui-checkbox-red-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-red-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-red-border-checked,#dc2626)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-red-border-checked-dark,#ef4444)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-red-bg-checked,#dc2626)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-red-bg-checked-dark,#ef4444)]",
  slate:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-slate-border-checked,#475569)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-slate-border-checked-dark,#64748b)] group-data-[state=checked]:bg-[var(--zui-checkbox-slate-bg-checked,#475569)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-slate-bg-checked-dark,#64748b)] group-data-[state=checked]:text-[color:var(--zui-checkbox-slate-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-slate-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-slate-border-checked,#475569)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-slate-border-checked-dark,#64748b)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-slate-bg-checked,#475569)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-slate-bg-checked-dark,#64748b)]",
  zinc: "group-data-[state=checked]:border-[color:var(--zui-checkbox-zinc-border-checked,#52525b)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-zinc-border-checked-dark,#71717a)] group-data-[state=checked]:bg-[var(--zui-checkbox-zinc-bg-checked,#52525b)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-zinc-bg-checked-dark,#71717a)] group-data-[state=checked]:text-[color:var(--zui-checkbox-zinc-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-zinc-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-zinc-border-checked,#52525b)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-zinc-border-checked-dark,#71717a)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-zinc-bg-checked,#52525b)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-zinc-bg-checked-dark,#71717a)]",
  stone:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-stone-border-checked,#57534e)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-stone-border-checked-dark,#78716c)] group-data-[state=checked]:bg-[var(--zui-checkbox-stone-bg-checked,#57534e)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-stone-bg-checked-dark,#78716c)] group-data-[state=checked]:text-[color:var(--zui-checkbox-stone-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-stone-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-stone-border-checked,#57534e)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-stone-border-checked-dark,#78716c)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-stone-bg-checked,#57534e)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-stone-bg-checked-dark,#78716c)]",
  royal:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-royal-border-checked,#4338ca)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-royal-border-checked-dark,#818cf8)] group-data-[state=checked]:bg-[var(--zui-checkbox-royal-bg-checked,#4338ca)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-royal-bg-checked-dark,#818cf8)] group-data-[state=checked]:text-[color:var(--zui-checkbox-royal-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-royal-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-royal-border-checked,#4338ca)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-royal-border-checked-dark,#818cf8)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-royal-bg-checked,#4338ca)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-royal-bg-checked-dark,#818cf8)]",
  electric:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-electric-border-checked,#0ea5e9)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-electric-border-checked-dark,#38bdf8)] group-data-[state=checked]:bg-[var(--zui-checkbox-electric-bg-checked,#0ea5e9)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-electric-bg-checked-dark,#38bdf8)] group-data-[state=checked]:text-[color:var(--zui-checkbox-electric-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-electric-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-electric-border-checked,#0ea5e9)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-electric-border-checked-dark,#38bdf8)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-electric-bg-checked,#0ea5e9)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-electric-bg-checked-dark,#38bdf8)]",
  forest:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-forest-border-checked,#166534)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-forest-border-checked-dark,#4ade80)] group-data-[state=checked]:bg-[var(--zui-checkbox-forest-bg-checked,#166534)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-forest-bg-checked-dark,#4ade80)] group-data-[state=checked]:text-[color:var(--zui-checkbox-forest-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-forest-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-forest-border-checked,#166534)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-forest-border-checked-dark,#4ade80)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-forest-bg-checked,#166534)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-forest-bg-checked-dark,#4ade80)]",
  sunset:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-sunset-border-checked,#ea580c)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-sunset-border-checked-dark,#fb923c)] group-data-[state=checked]:bg-[var(--zui-checkbox-sunset-bg-checked,#ea580c)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-sunset-bg-checked-dark,#fb923c)] group-data-[state=checked]:text-[color:var(--zui-checkbox-sunset-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-sunset-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sunset-border-checked,#ea580c)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sunset-border-checked-dark,#fb923c)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sunset-bg-checked,#ea580c)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sunset-bg-checked-dark,#fb923c)]",
  magenta:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-magenta-border-checked,#c026d3)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-magenta-border-checked-dark,#e879f9)] group-data-[state=checked]:bg-[var(--zui-checkbox-magenta-bg-checked,#c026d3)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-magenta-bg-checked-dark,#e879f9)] group-data-[state=checked]:text-[color:var(--zui-checkbox-magenta-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-magenta-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-magenta-border-checked,#c026d3)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-magenta-border-checked-dark,#e879f9)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-magenta-bg-checked,#c026d3)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-magenta-bg-checked-dark,#e879f9)]",
  crimson:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-crimson-border-checked,#b91c1c)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-crimson-border-checked-dark,#f87171)] group-data-[state=checked]:bg-[var(--zui-checkbox-crimson-bg-checked,#b91c1c)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-crimson-bg-checked-dark,#f87171)] group-data-[state=checked]:text-[color:var(--zui-checkbox-crimson-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-crimson-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-crimson-border-checked,#b91c1c)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-crimson-border-checked-dark,#f87171)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-crimson-bg-checked,#b91c1c)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-crimson-bg-checked-dark,#f87171)]",
  aqua: "group-data-[state=checked]:border-[color:var(--zui-checkbox-aqua-border-checked,#0f766e)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-aqua-border-checked-dark,#2dd4bf)] group-data-[state=checked]:bg-[var(--zui-checkbox-aqua-bg-checked,#0f766e)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-aqua-bg-checked-dark,#2dd4bf)] group-data-[state=checked]:text-[color:var(--zui-checkbox-aqua-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-aqua-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-aqua-border-checked,#0f766e)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-aqua-border-checked-dark,#2dd4bf)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-aqua-bg-checked,#0f766e)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-aqua-bg-checked-dark,#2dd4bf)]",
  plum: "group-data-[state=checked]:border-[color:var(--zui-checkbox-plum-border-checked,#7e22ce)] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-plum-border-checked-dark,#c084fc)] group-data-[state=checked]:bg-[var(--zui-checkbox-plum-bg-checked,#7e22ce)] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-plum-bg-checked-dark,#c084fc)] group-data-[state=checked]:text-[color:var(--zui-checkbox-plum-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-plum-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-plum-border-checked,#7e22ce)] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-plum-border-checked-dark,#c084fc)] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-plum-bg-checked,#7e22ce)] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-plum-bg-checked-dark,#c084fc)]",
  violet:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-violet-border-checked,oklch(54.1%_0.281_293.009))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-violet-border-checked-dark,oklch(54.1%_0.281_293.009))] group-data-[state=checked]:bg-[var(--zui-checkbox-violet-bg-checked,oklch(54.1%_0.281_293.009))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-violet-bg-checked-dark,oklch(54.1%_0.281_293.009))] group-data-[state=checked]:text-[color:var(--zui-checkbox-violet-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-violet-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-violet-border-checked,oklch(54.1%_0.281_293.009))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-violet-border-checked-dark,oklch(54.1%_0.281_293.009))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-violet-bg-checked,oklch(54.1%_0.281_293.009))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-violet-bg-checked-dark,oklch(54.1%_0.281_293.009))]",
  amber:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-amber-border-checked,oklch(66.6%_0.179_58.318))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-amber-border-checked-dark,oklch(66.6%_0.179_58.318))] group-data-[state=checked]:bg-[var(--zui-checkbox-amber-bg-checked,oklch(66.6%_0.179_58.318))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-amber-bg-checked-dark,oklch(66.6%_0.179_58.318))] group-data-[state=checked]:text-[color:var(--zui-checkbox-amber-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-amber-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-amber-border-checked,oklch(66.6%_0.179_58.318))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-amber-border-checked-dark,oklch(66.6%_0.179_58.318))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-amber-bg-checked,oklch(66.6%_0.179_58.318))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-amber-bg-checked-dark,oklch(66.6%_0.179_58.318))]",
  pink: "group-data-[state=checked]:border-[color:var(--zui-checkbox-pink-border-checked,oklch(59.2%_0.249_0.584))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-pink-border-checked-dark,oklch(59.2%_0.249_0.584))] group-data-[state=checked]:bg-[var(--zui-checkbox-pink-bg-checked,oklch(59.2%_0.249_0.584))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-pink-bg-checked-dark,oklch(59.2%_0.249_0.584))] group-data-[state=checked]:text-[color:var(--zui-checkbox-pink-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-pink-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-pink-border-checked,oklch(59.2%_0.249_0.584))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-pink-border-checked-dark,oklch(59.2%_0.249_0.584))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-pink-bg-checked,oklch(59.2%_0.249_0.584))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-pink-bg-checked-dark,oklch(59.2%_0.249_0.584))]",
  indigo:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-indigo-border-checked,oklch(51.1%_0.262_276.966))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-indigo-border-checked-dark,oklch(51.1%_0.262_276.966))] group-data-[state=checked]:bg-[var(--zui-checkbox-indigo-bg-checked,oklch(51.1%_0.262_276.966))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-indigo-bg-checked-dark,oklch(51.1%_0.262_276.966))] group-data-[state=checked]:text-[color:var(--zui-checkbox-indigo-fg-checked,#ffffff)] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-indigo-fg-checked-dark,#ffffff)] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-indigo-border-checked,oklch(51.1%_0.262_276.966))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-indigo-border-checked-dark,oklch(51.1%_0.262_276.966))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-indigo-bg-checked,oklch(51.1%_0.262_276.966))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-indigo-bg-checked-dark,oklch(51.1%_0.262_276.966))]",
} as const;
