export const zuiCheckboxRootBase =
  "group inline-flex w-fit items-start gap-2.5 text-sm font-medium text-[color:var(--zui-checkbox-label-fg,var(--zui-fg-muted,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-checkbox-label-fg-dark,var(--zui-fg-muted-dark,oklch(98.4%_0.003_247.858)))] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiCheckboxControlBase =
  "grid shrink-0 place-items-center rounded-md border-2 border-[color:var(--zui-checkbox-border,var(--zui-border,#0000004d))] bg-[var(--zui-checkbox-bg,var(--zui-surface-soft,transparent))] dark:bg-[var(--zui-checkbox-bg-dark,var(--zui-surface-soft-dark,transparent))] text-[color:var(--zui-checkbox-fg,var(--zui-fg,oklch(44.6%_0.043_257.281)))] transition-[background-color,border-color,color,box-shadow] peer-focus-visible:outline-none peer-focus-visible:ring-2 peer-focus-visible:ring-[var(--zui-checkbox-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281_/_0.7)))] peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-[var(--zui-checkbox-ring-offset-focus,var(--zui-ring-offset,oklch(98.4%_0.003_247.858)))] dark:border-[color:var(--zui-checkbox-border-dark,var(--zui-border-dark,#ffffff4d))] dark:text-[color:var(--zui-checkbox-fg-dark,var(--zui-fg-dark,oklch(92.9%_0.013_255.508)))] dark:peer-focus-visible:ring-[var(--zui-checkbox-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894_/_0.7)))] dark:peer-focus-visible:ring-offset-[var(--zui-checkbox-ring-offset-focus-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))] group-data-[disabled=true]:cursor-not-allowed";

export const zuiCheckboxIndicatorBase =
  "pointer-events-none opacity-0 transition-opacity duration-150 stroke-current group-data-[state=checked]:opacity-100 group-data-[state=indeterminate]:opacity-100";

export const zuiCheckboxSizes = {
  sm: {
    root: "text-xs",
    control: "mt-0.5 size-4 rounded-[0.35rem]",
    indicator: "size-3",
  },
  md: {
    root: "text-sm",
    control: "mt-0.5 size-5",
    indicator: "size-3.5",
  },
  lg: {
    root: "text-base",
    control: "mt-0.5 size-6",
    indicator: "size-4",
  },
} as const;

export const zuiCheckboxAppearances = {
  default:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-default-border-checked,var(--zui-brand,oklch(44.6%_0.043_257.281)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-default-border-checked-dark,var(--zui-brand-dark,oklch(44.6%_0.043_257.281)))] group-data-[state=checked]:bg-[var(--zui-checkbox-default-bg-checked,var(--zui-brand,oklch(44.6%_0.043_257.281)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-default-bg-checked-dark,var(--zui-brand-dark,oklch(44.6%_0.043_257.281)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-default-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-default-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-default-border-checked,var(--zui-brand,oklch(44.6%_0.043_257.281)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-default-border-checked-dark,var(--zui-brand-dark,oklch(44.6%_0.043_257.281)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-default-bg-checked,var(--zui-brand,oklch(44.6%_0.043_257.281)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-default-bg-checked-dark,var(--zui-brand-dark,oklch(44.6%_0.043_257.281)))] group-data-[state=indeterminate]:text-[color:var(--zui-checkbox-default-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=indeterminate]:text-[color:var(--zui-checkbox-default-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))]",
  success:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-success-border-checked,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-success-border-checked-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225)))] group-data-[state=checked]:bg-[var(--zui-checkbox-success-bg-checked,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-success-bg-checked-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-success-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-success-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-success-border-checked,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-success-border-checked-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-success-bg-checked,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-success-bg-checked-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225)))]",
  warning:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-warning-border-checked,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-warning-border-checked-dark,var(--zui-status-warning-dark,oklch(68.1%_0.162_75.834)))] group-data-[state=checked]:bg-[var(--zui-checkbox-warning-bg-checked,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-warning-bg-checked-dark,var(--zui-status-warning-dark,oklch(68.1%_0.162_75.834)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-warning-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-warning-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-warning-border-checked,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-warning-border-checked-dark,var(--zui-status-warning-dark,oklch(68.1%_0.162_75.834)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-warning-bg-checked,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-warning-bg-checked-dark,var(--zui-status-warning-dark,oklch(68.1%_0.162_75.834)))]",
  error:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-error-border-checked,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-error-border-checked-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585)))] group-data-[state=checked]:bg-[var(--zui-checkbox-error-bg-checked,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-error-bg-checked-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-error-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-error-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-error-border-checked,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-error-border-checked-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-error-bg-checked,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-error-bg-checked-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585)))]",
  info: "group-data-[state=checked]:border-[color:var(--zui-checkbox-info-border-checked,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-info-border-checked-dark,var(--zui-status-info-dark,oklch(54.6%_0.245_262.881)))] group-data-[state=checked]:bg-[var(--zui-checkbox-info-bg-checked,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-info-bg-checked-dark,var(--zui-status-info-dark,oklch(54.6%_0.245_262.881)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-info-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-info-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-info-border-checked,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-info-border-checked-dark,var(--zui-status-info-dark,oklch(54.6%_0.245_262.881)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-info-bg-checked,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-info-bg-checked-dark,var(--zui-status-info-dark,oklch(54.6%_0.245_262.881)))]",
  blue: "group-data-[state=checked]:border-[color:var(--zui-checkbox-blue-border-checked,var(--zui-color-blue,#2563eb))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-blue-border-checked-dark,var(--zui-color-blue-dark,#3b82f6))] group-data-[state=checked]:bg-[var(--zui-checkbox-blue-bg-checked,var(--zui-color-blue,#2563eb))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-blue-bg-checked-dark,var(--zui-color-blue-dark,#3b82f6))] group-data-[state=checked]:text-[color:var(--zui-checkbox-blue-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-blue-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-blue-border-checked,var(--zui-color-blue,#2563eb))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-blue-border-checked-dark,var(--zui-color-blue-dark,#3b82f6))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-blue-bg-checked,var(--zui-color-blue,#2563eb))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-blue-bg-checked-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "group-data-[state=checked]:border-[color:var(--zui-checkbox-cyan-border-checked,var(--zui-color-cyan,#0891b2))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-cyan-border-checked-dark,var(--zui-color-cyan-dark,#22d3ee))] group-data-[state=checked]:bg-[var(--zui-checkbox-cyan-bg-checked,var(--zui-color-cyan,#0891b2))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-cyan-bg-checked-dark,var(--zui-color-cyan-dark,#22d3ee))] group-data-[state=checked]:text-[color:var(--zui-checkbox-cyan-fg-checked,var(--zui-brand-fg,#083344))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-cyan-fg-checked-dark,var(--zui-brand-fg-dark,#083344))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-cyan-border-checked,var(--zui-color-cyan,#0891b2))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-cyan-border-checked-dark,var(--zui-color-cyan-dark,#22d3ee))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-cyan-bg-checked,var(--zui-color-cyan,#0891b2))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-cyan-bg-checked-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-green-border-checked,var(--zui-color-green,#16a34a))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-green-border-checked-dark,var(--zui-color-green-dark,#22c55e))] group-data-[state=checked]:bg-[var(--zui-checkbox-green-bg-checked,var(--zui-color-green,#16a34a))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-green-bg-checked-dark,var(--zui-color-green-dark,#22c55e))] group-data-[state=checked]:text-[color:var(--zui-checkbox-green-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-green-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-green-border-checked,var(--zui-color-green,#16a34a))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-green-border-checked-dark,var(--zui-color-green-dark,#22c55e))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-green-bg-checked,var(--zui-color-green,#16a34a))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-green-bg-checked-dark,var(--zui-color-green-dark,#22c55e))]",
  lime: "group-data-[state=checked]:border-[color:var(--zui-checkbox-lime-border-checked,var(--zui-color-lime,#65a30d))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-lime-border-checked-dark,var(--zui-color-lime-dark,#a3e635))] group-data-[state=checked]:bg-[var(--zui-checkbox-lime-bg-checked,var(--zui-color-lime,#65a30d))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-lime-bg-checked-dark,var(--zui-color-lime-dark,#a3e635))] group-data-[state=checked]:text-[color:var(--zui-checkbox-lime-fg-checked,var(--zui-brand-fg,#1a2e05))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-lime-fg-checked-dark,var(--zui-brand-fg-dark,#1a2e05))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lime-border-checked,var(--zui-color-lime,#65a30d))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lime-border-checked-dark,var(--zui-color-lime-dark,#a3e635))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lime-bg-checked,var(--zui-color-lime,#65a30d))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lime-bg-checked-dark,var(--zui-color-lime-dark,#a3e635))]",
  mint: "group-data-[state=checked]:border-[color:var(--zui-checkbox-mint-border-checked,var(--zui-color-mint,#10b981))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-mint-border-checked-dark,var(--zui-color-mint-dark,#6ee7b7))] group-data-[state=checked]:bg-[var(--zui-checkbox-mint-bg-checked,var(--zui-color-mint,#10b981))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-mint-bg-checked-dark,var(--zui-color-mint-dark,#6ee7b7))] group-data-[state=checked]:text-[color:var(--zui-checkbox-mint-fg-checked,var(--zui-brand-fg,#064e3b))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-mint-fg-checked-dark,var(--zui-brand-fg-dark,#064e3b))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-mint-border-checked,var(--zui-color-mint,#10b981))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-mint-border-checked-dark,var(--zui-color-mint-dark,#6ee7b7))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-mint-bg-checked,var(--zui-color-mint,#10b981))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-mint-bg-checked-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-ocean-border-checked,var(--zui-color-ocean,#0284c7))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-ocean-border-checked-dark,var(--zui-color-ocean-dark,#38bdf8))] group-data-[state=checked]:bg-[var(--zui-checkbox-ocean-bg-checked,var(--zui-color-ocean,#0284c7))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-ocean-bg-checked-dark,var(--zui-color-ocean-dark,#38bdf8))] group-data-[state=checked]:text-[color:var(--zui-checkbox-ocean-fg-checked,var(--zui-brand-fg,#082f49))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-ocean-fg-checked-dark,var(--zui-brand-fg-dark,#082f49))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ocean-border-checked,var(--zui-color-ocean,#0284c7))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ocean-border-checked-dark,var(--zui-color-ocean-dark,#38bdf8))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ocean-bg-checked,var(--zui-color-ocean,#0284c7))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ocean-bg-checked-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-sapphire-border-checked,var(--zui-color-sapphire,#1d4ed8))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-sapphire-border-checked-dark,var(--zui-color-sapphire-dark,#60a5fa))] group-data-[state=checked]:bg-[var(--zui-checkbox-sapphire-bg-checked,var(--zui-color-sapphire,#1d4ed8))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-sapphire-bg-checked-dark,var(--zui-color-sapphire-dark,#60a5fa))] group-data-[state=checked]:text-[color:var(--zui-checkbox-sapphire-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-sapphire-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sapphire-border-checked,var(--zui-color-sapphire,#1d4ed8))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sapphire-border-checked-dark,var(--zui-color-sapphire-dark,#60a5fa))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sapphire-bg-checked,var(--zui-color-sapphire,#1d4ed8))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sapphire-bg-checked-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-lavender-border-checked,var(--zui-color-lavender,#8b5cf6))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-lavender-border-checked-dark,var(--zui-color-lavender-dark,#a78bfa))] group-data-[state=checked]:bg-[var(--zui-checkbox-lavender-bg-checked,var(--zui-color-lavender,#8b5cf6))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-lavender-bg-checked-dark,var(--zui-color-lavender-dark,#a78bfa))] group-data-[state=checked]:text-[color:var(--zui-checkbox-lavender-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-lavender-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lavender-border-checked,var(--zui-color-lavender,#8b5cf6))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-lavender-border-checked-dark,var(--zui-color-lavender-dark,#a78bfa))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lavender-bg-checked,var(--zui-color-lavender,#8b5cf6))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-lavender-bg-checked-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "group-data-[state=checked]:border-[color:var(--zui-checkbox-ruby-border-checked,var(--zui-color-ruby,#be123c))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-ruby-border-checked-dark,var(--zui-color-ruby-dark,#fb7185))] group-data-[state=checked]:bg-[var(--zui-checkbox-ruby-bg-checked,var(--zui-color-ruby,#be123c))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-ruby-bg-checked-dark,var(--zui-color-ruby-dark,#fb7185))] group-data-[state=checked]:text-[color:var(--zui-checkbox-ruby-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-ruby-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ruby-border-checked,var(--zui-color-ruby,#be123c))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-ruby-border-checked-dark,var(--zui-color-ruby-dark,#fb7185))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ruby-bg-checked,var(--zui-color-ruby,#be123c))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-ruby-bg-checked-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "group-data-[state=checked]:border-[color:var(--zui-checkbox-red-border-checked,var(--zui-color-red,#dc2626))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-red-border-checked-dark,var(--zui-color-red-dark,#ef4444))] group-data-[state=checked]:bg-[var(--zui-checkbox-red-bg-checked,var(--zui-color-red,#dc2626))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-red-bg-checked-dark,var(--zui-color-red-dark,#ef4444))] group-data-[state=checked]:text-[color:var(--zui-checkbox-red-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-red-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-red-border-checked,var(--zui-color-red,#dc2626))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-red-border-checked-dark,var(--zui-color-red-dark,#ef4444))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-red-bg-checked,var(--zui-color-red,#dc2626))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-red-bg-checked-dark,var(--zui-color-red-dark,#ef4444))]",
  slate:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-slate-border-checked,var(--zui-color-slate,#475569))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-slate-border-checked-dark,var(--zui-color-slate-dark,#64748b))] group-data-[state=checked]:bg-[var(--zui-checkbox-slate-bg-checked,var(--zui-color-slate,#475569))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-slate-bg-checked-dark,var(--zui-color-slate-dark,#64748b))] group-data-[state=checked]:text-[color:var(--zui-checkbox-slate-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-slate-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-slate-border-checked,var(--zui-color-slate,#475569))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-slate-border-checked-dark,var(--zui-color-slate-dark,#64748b))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-slate-bg-checked,var(--zui-color-slate,#475569))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-slate-bg-checked-dark,var(--zui-color-slate-dark,#64748b))]",
  zinc: "group-data-[state=checked]:border-[color:var(--zui-checkbox-zinc-border-checked,var(--zui-color-zinc,#52525b))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-zinc-border-checked-dark,var(--zui-color-zinc-dark,#71717a))] group-data-[state=checked]:bg-[var(--zui-checkbox-zinc-bg-checked,var(--zui-color-zinc,#52525b))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-zinc-bg-checked-dark,var(--zui-color-zinc-dark,#71717a))] group-data-[state=checked]:text-[color:var(--zui-checkbox-zinc-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-zinc-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-zinc-border-checked,var(--zui-color-zinc,#52525b))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-zinc-border-checked-dark,var(--zui-color-zinc-dark,#71717a))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-zinc-bg-checked,var(--zui-color-zinc,#52525b))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-zinc-bg-checked-dark,var(--zui-color-zinc-dark,#71717a))]",
  stone:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-stone-border-checked,var(--zui-color-stone,#57534e))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-stone-border-checked-dark,var(--zui-color-stone-dark,#78716c))] group-data-[state=checked]:bg-[var(--zui-checkbox-stone-bg-checked,var(--zui-color-stone,#57534e))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-stone-bg-checked-dark,var(--zui-color-stone-dark,#78716c))] group-data-[state=checked]:text-[color:var(--zui-checkbox-stone-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-stone-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-stone-border-checked,var(--zui-color-stone,#57534e))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-stone-border-checked-dark,var(--zui-color-stone-dark,#78716c))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-stone-bg-checked,var(--zui-color-stone,#57534e))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-stone-bg-checked-dark,var(--zui-color-stone-dark,#78716c))]",
  royal:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-royal-border-checked,var(--zui-color-royal,#4338ca))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-royal-border-checked-dark,var(--zui-color-royal-dark,#818cf8))] group-data-[state=checked]:bg-[var(--zui-checkbox-royal-bg-checked,var(--zui-color-royal,#4338ca))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-royal-bg-checked-dark,var(--zui-color-royal-dark,#818cf8))] group-data-[state=checked]:text-[color:var(--zui-checkbox-royal-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-royal-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-royal-border-checked,var(--zui-color-royal,#4338ca))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-royal-border-checked-dark,var(--zui-color-royal-dark,#818cf8))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-royal-bg-checked,var(--zui-color-royal,#4338ca))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-royal-bg-checked-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-electric-border-checked,var(--zui-color-electric,#0ea5e9))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-electric-border-checked-dark,var(--zui-color-electric-dark,#38bdf8))] group-data-[state=checked]:bg-[var(--zui-checkbox-electric-bg-checked,var(--zui-color-electric,#0ea5e9))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-electric-bg-checked-dark,var(--zui-color-electric-dark,#38bdf8))] group-data-[state=checked]:text-[color:var(--zui-checkbox-electric-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-electric-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-electric-border-checked,var(--zui-color-electric,#0ea5e9))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-electric-border-checked-dark,var(--zui-color-electric-dark,#38bdf8))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-electric-bg-checked,var(--zui-color-electric,#0ea5e9))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-electric-bg-checked-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-forest-border-checked,var(--zui-color-forest,#166534))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-forest-border-checked-dark,var(--zui-color-forest-dark,#4ade80))] group-data-[state=checked]:bg-[var(--zui-checkbox-forest-bg-checked,var(--zui-color-forest,#166534))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-forest-bg-checked-dark,var(--zui-color-forest-dark,#4ade80))] group-data-[state=checked]:text-[color:var(--zui-checkbox-forest-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-forest-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-forest-border-checked,var(--zui-color-forest,#166534))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-forest-border-checked-dark,var(--zui-color-forest-dark,#4ade80))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-forest-bg-checked,var(--zui-color-forest,#166534))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-forest-bg-checked-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-sunset-border-checked,var(--zui-color-sunset,#ea580c))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-sunset-border-checked-dark,var(--zui-color-sunset-dark,#fb923c))] group-data-[state=checked]:bg-[var(--zui-checkbox-sunset-bg-checked,var(--zui-color-sunset,#ea580c))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-sunset-bg-checked-dark,var(--zui-color-sunset-dark,#fb923c))] group-data-[state=checked]:text-[color:var(--zui-checkbox-sunset-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-sunset-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sunset-border-checked,var(--zui-color-sunset,#ea580c))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-sunset-border-checked-dark,var(--zui-color-sunset-dark,#fb923c))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sunset-bg-checked,var(--zui-color-sunset,#ea580c))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-sunset-bg-checked-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-magenta-border-checked,var(--zui-color-magenta,#c026d3))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-magenta-border-checked-dark,var(--zui-color-magenta-dark,#e879f9))] group-data-[state=checked]:bg-[var(--zui-checkbox-magenta-bg-checked,var(--zui-color-magenta,#c026d3))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-magenta-bg-checked-dark,var(--zui-color-magenta-dark,#e879f9))] group-data-[state=checked]:text-[color:var(--zui-checkbox-magenta-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-magenta-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-magenta-border-checked,var(--zui-color-magenta,#c026d3))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-magenta-border-checked-dark,var(--zui-color-magenta-dark,#e879f9))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-magenta-bg-checked,var(--zui-color-magenta,#c026d3))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-magenta-bg-checked-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-crimson-border-checked,var(--zui-color-crimson,#b91c1c))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-crimson-border-checked-dark,var(--zui-color-crimson-dark,#f87171))] group-data-[state=checked]:bg-[var(--zui-checkbox-crimson-bg-checked,var(--zui-color-crimson,#b91c1c))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-crimson-bg-checked-dark,var(--zui-color-crimson-dark,#f87171))] group-data-[state=checked]:text-[color:var(--zui-checkbox-crimson-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-crimson-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-crimson-border-checked,var(--zui-color-crimson,#b91c1c))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-crimson-border-checked-dark,var(--zui-color-crimson-dark,#f87171))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-crimson-bg-checked,var(--zui-color-crimson,#b91c1c))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-crimson-bg-checked-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "group-data-[state=checked]:border-[color:var(--zui-checkbox-aqua-border-checked,var(--zui-color-aqua,#0f766e))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-aqua-border-checked-dark,var(--zui-color-aqua-dark,#2dd4bf))] group-data-[state=checked]:bg-[var(--zui-checkbox-aqua-bg-checked,var(--zui-color-aqua,#0f766e))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-aqua-bg-checked-dark,var(--zui-color-aqua-dark,#2dd4bf))] group-data-[state=checked]:text-[color:var(--zui-checkbox-aqua-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-aqua-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-aqua-border-checked,var(--zui-color-aqua,#0f766e))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-aqua-border-checked-dark,var(--zui-color-aqua-dark,#2dd4bf))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-aqua-bg-checked,var(--zui-color-aqua,#0f766e))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-aqua-bg-checked-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "group-data-[state=checked]:border-[color:var(--zui-checkbox-plum-border-checked,var(--zui-color-plum,#7e22ce))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-plum-border-checked-dark,var(--zui-color-plum-dark,#c084fc))] group-data-[state=checked]:bg-[var(--zui-checkbox-plum-bg-checked,var(--zui-color-plum,#7e22ce))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-plum-bg-checked-dark,var(--zui-color-plum-dark,#c084fc))] group-data-[state=checked]:text-[color:var(--zui-checkbox-plum-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-plum-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-plum-border-checked,var(--zui-color-plum,#7e22ce))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-plum-border-checked-dark,var(--zui-color-plum-dark,#c084fc))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-plum-bg-checked,var(--zui-color-plum,#7e22ce))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-plum-bg-checked-dark,var(--zui-color-plum-dark,#c084fc))]",
  violet:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-violet-border-checked,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-violet-border-checked-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] group-data-[state=checked]:bg-[var(--zui-checkbox-violet-bg-checked,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-violet-bg-checked-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-violet-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-violet-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-violet-border-checked,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-violet-border-checked-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-violet-bg-checked,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-violet-bg-checked-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))]",
  amber:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-amber-border-checked,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-amber-border-checked-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] group-data-[state=checked]:bg-[var(--zui-checkbox-amber-bg-checked,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-amber-bg-checked-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-amber-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-amber-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-amber-border-checked,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-amber-border-checked-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-amber-bg-checked,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-amber-bg-checked-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))]",
  pink: "group-data-[state=checked]:border-[color:var(--zui-checkbox-pink-border-checked,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-pink-border-checked-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] group-data-[state=checked]:bg-[var(--zui-checkbox-pink-bg-checked,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-pink-bg-checked-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-pink-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-pink-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-pink-border-checked,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-pink-border-checked-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-pink-bg-checked,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-pink-bg-checked-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  indigo:
    "group-data-[state=checked]:border-[color:var(--zui-checkbox-indigo-border-checked,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:group-data-[state=checked]:border-[color:var(--zui-checkbox-indigo-border-checked-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] group-data-[state=checked]:bg-[var(--zui-checkbox-indigo-bg-checked,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:group-data-[state=checked]:bg-[var(--zui-checkbox-indigo-bg-checked-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] group-data-[state=checked]:text-[color:var(--zui-checkbox-indigo-fg-checked,var(--zui-brand-fg,#ffffff))] dark:group-data-[state=checked]:text-[color:var(--zui-checkbox-indigo-fg-checked-dark,var(--zui-brand-fg-dark,#ffffff))] group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-indigo-border-checked,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:group-data-[state=indeterminate]:border-[color:var(--zui-checkbox-indigo-border-checked-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] group-data-[state=indeterminate]:bg-[var(--zui-checkbox-indigo-bg-checked,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:group-data-[state=indeterminate]:bg-[var(--zui-checkbox-indigo-bg-checked-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))]",
} as const;
