/**
 * Circular menu design tokens.
 *
 * Pure token data only: every themeable value is a `--zui-circular-menu-*` CSS
 * custom property with a hardcoded fallback, and every color-bearing appearance
 * entry pairs its light and `dark:` classes in the same string so consumer
 * Tailwind scans pick up both.
 *
 * Layout tokens (`--zui-circular-menu-size`, `-radius`, `-item-size`,
 * `-item-x`, `-item-y`, `-item-angle`, `-item-index`, `-open`) are written
 * inline by `circular-menu-base.tsx`, because the ring geometry is solved in JS
 * (see `../ui/circular-menu/geometry.ts`) and must stay in sync with the DOM.
 */

/** Square, `position: relative` box that owns the ring's coordinate space. */
export const zuiCircularMenuRootBase =
  "group/circular-menu relative isolate inline-flex items-center justify-center [block-size:var(--zui-circular-menu-size,300px)] [inline-size:var(--zui-circular-menu-size,300px)] data-[disabled=true]:cursor-not-allowed";

/** Center button that opens the ring. Sized by its own token so it can grow past the discs. */
export const zuiCircularMenuTriggerBase =
  "absolute left-1/2 top-1/2 z-20 inline-flex -translate-x-1/2 -translate-y-1/2 select-none items-center justify-center gap-1 rounded-full border text-center font-semibold leading-none shadow-sm outline-none transition-[background-color,border-color,color,box-shadow,transform,filter] duration-200 ease-out [block-size:var(--zui-circular-menu-trigger-size,64px)] [inline-size:var(--zui-circular-menu-trigger-size,64px)] hover:scale-[1.04] active:scale-95 focus-visible:ring-2 focus-visible:ring-[color:var(--zui-circular-menu-focus-ring,var(--zui-color-blue,#2563eb))] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--zui-circular-menu-ring-offset,var(--zui-bg,#ffffff))] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:scale-100 dark:focus-visible:ring-[color:var(--zui-circular-menu-focus-ring-dark,var(--zui-color-blue-dark,#3b82f6))] dark:focus-visible:ring-offset-[var(--zui-circular-menu-ring-offset-dark,var(--zui-bg-dark,#09090b))] motion-reduce:transition-none motion-reduce:hover:scale-100";

/** Zero-size ring origin pinned to the root center; spins as one rigid body. */
export const zuiCircularMenuListBase =
  "absolute left-1/2 top-1/2 z-10 [block-size:0px] [inline-size:0px] transition-opacity [transition-duration:var(--zui-circular-menu-transition-duration,220ms)] ease-out data-[state=closed]:pointer-events-none data-[state=closed]:opacity-0 data-[state=closed]:[--zui-circular-menu-open:0] data-[state=open]:opacity-100 data-[state=open]:[--zui-circular-menu-open:1] data-[spin=true]:animate-spin data-[spin=true]:[animation-duration:var(--zui-circular-menu-spin-duration,12s)] data-[spin=true]:[animation-timing-function:linear] data-[pause-on-hover=true]:group-hover/circular-menu:[animation-play-state:paused] motion-reduce:animate-none motion-reduce:transition-none";

/** Per-item wrapper that carries the solved polar offset. Keeps the disc's own transform free. */
export const zuiCircularMenuItemPositionerBase =
  "absolute left-0 top-0 flex flex-col items-center justify-center [block-size:var(--zui-circular-menu-item-size,40px)] [inline-size:var(--zui-circular-menu-item-size,40px)] translate-x-[calc(var(--zui-circular-menu-item-x,0px)_*_var(--zui-circular-menu-open,1)_-_50%)] translate-y-[calc(var(--zui-circular-menu-item-y,0px)_*_var(--zui-circular-menu-open,1)_-_50%)] transition-transform [transition-duration:var(--zui-circular-menu-transition-duration,220ms)] [transition-delay:calc(var(--zui-circular-menu-item-index,0)_*_var(--zui-circular-menu-stagger,40ms))] ease-out motion-reduce:transition-none";

/** The item disc itself. */
export const zuiCircularMenuItemBase =
  "group/circular-menu-item relative inline-flex select-none items-center justify-center rounded-full border shadow-sm outline-none [block-size:var(--zui-circular-menu-item-size,40px)] [inline-size:var(--zui-circular-menu-item-size,40px)] transition-[background-color,border-color,color,box-shadow,transform,opacity,filter] [transition-duration:var(--zui-circular-menu-transition-duration,220ms)] [transition-delay:calc(var(--zui-circular-menu-item-index,0)_*_var(--zui-circular-menu-stagger,40ms))] ease-out hover:z-30 hover:scale-110 focus-visible:z-30 focus-visible:ring-2 focus-visible:ring-[color:var(--zui-circular-menu-focus-ring,var(--zui-color-blue,#2563eb))] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--zui-circular-menu-ring-offset,var(--zui-bg,#ffffff))] dark:focus-visible:ring-[color:var(--zui-circular-menu-focus-ring-dark,var(--zui-color-blue-dark,#3b82f6))] dark:focus-visible:ring-offset-[var(--zui-circular-menu-ring-offset-dark,var(--zui-bg-dark,#09090b))] group-data-[state=closed]/circular-menu:scale-50 group-data-[state=closed]/circular-menu:opacity-0 data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50 data-[disabled=true]:hover:scale-100 motion-reduce:transition-none motion-reduce:hover:scale-100";

/** Icon slot. Counter-rotates so glyphs stay upright while the ring spins. */
export const zuiCircularMenuItemIconBase =
  "pointer-events-none inline-flex items-center justify-center leading-none [font-size:calc(var(--zui-circular-menu-item-size,40px)_*_0.45)] [&_svg]:size-[1em] data-[counter-spin=true]:animate-spin data-[counter-spin=true]:[animation-direction:reverse] data-[counter-spin=true]:[animation-duration:var(--zui-circular-menu-spin-duration,12s)] data-[counter-spin=true]:[animation-timing-function:linear] data-[pause-on-hover=true]:group-hover/circular-menu:[animation-play-state:paused] motion-reduce:animate-none";

/** Label slot. Positioned by `zuiCircularMenuLabelPlacements`. */
export const zuiCircularMenuItemLabelBase =
  "pointer-events-none select-none whitespace-nowrap text-center font-medium leading-none text-[color:var(--zui-circular-menu-label-fg,var(--zui-fg-muted,#52525b))] transition-opacity [transition-duration:var(--zui-circular-menu-transition-duration,220ms)] ease-out group-data-[state=closed]/circular-menu:opacity-0 dark:text-[color:var(--zui-circular-menu-label-fg-dark,var(--zui-fg-muted-dark,#d4d4d8))] data-[counter-spin=true]:animate-spin data-[counter-spin=true]:[animation-direction:reverse] data-[counter-spin=true]:[animation-duration:var(--zui-circular-menu-spin-duration,12s)] data-[counter-spin=true]:[animation-timing-function:linear] data-[pause-on-hover=true]:group-hover/circular-menu:[animation-play-state:paused] motion-reduce:animate-none motion-reduce:transition-none";

/** Optional line from the center to each item. Length is derived from the radius token. */
export const zuiCircularMenuSpokeBase =
  "pointer-events-none absolute left-1/2 top-1/2 z-0 origin-top rounded-full [inline-size:var(--zui-circular-menu-spoke-width,2px)] [block-size:calc((var(--zui-circular-menu-radius,132px)_-_(var(--zui-circular-menu-item-size,40px)_/_2))_*_var(--zui-circular-menu-open,1))] -translate-x-1/2 rotate-[calc(var(--zui-circular-menu-item-angle,0deg)_+_180deg)] transition-[block-size,opacity] [transition-duration:var(--zui-circular-menu-transition-duration,220ms)] ease-out group-data-[state=closed]/circular-menu:opacity-0 motion-reduce:transition-none";

/**
 * Typography and trigger sizing per size variant.
 *
 * Ring radius and item size are NOT set here: they feed the JS geometry solver,
 * so `circular-menu-base.tsx` writes them inline from
 * `CIRCULAR_MENU_SIZE_METRICS`. The trigger only affects CSS, so it stays a
 * pure token.
 */
export const zuiCircularMenuSizes = {
  sm: "text-xs [--zui-circular-menu-trigger-size:48px]",
  md: "text-sm [--zui-circular-menu-trigger-size:64px]",
  lg: "text-base [--zui-circular-menu-trigger-size:80px]",
} as const;

/** Where an item's label sits relative to its disc. */
export const zuiCircularMenuLabelPlacements = {
  inside: "relative z-10 text-[0.7em]",
  outside:
    "absolute left-1/2 top-full z-10 mt-1.5 -translate-x-1/2 text-[0.75em]",
  tooltip:
    "absolute left-1/2 top-full z-40 mt-2 -translate-x-1/2 rounded-md border px-2 py-1 text-[0.75em] opacity-0 shadow-sm border-[color:var(--zui-circular-menu-tooltip-border,var(--zui-border,#e4e4e7))] bg-[var(--zui-circular-menu-tooltip-bg,var(--zui-bg,#ffffff))] dark:border-[color:var(--zui-circular-menu-tooltip-border-dark,var(--zui-border-dark,#3f3f46))] dark:bg-[var(--zui-circular-menu-tooltip-bg-dark,var(--zui-color-zinc-900,#18181b))] group-hover/circular-menu-item:opacity-100 group-focus-visible/circular-menu-item:opacity-100",
  none: "sr-only",
} as const;

/** Center trigger palettes: solid accents, gradients, and glass. */
export const zuiCircularMenuTriggerAppearances = {
  default:
    "border-[color:var(--zui-circular-menu-default-trigger-border,var(--zui-color-zinc-900,#18181b))] bg-[var(--zui-circular-menu-default-trigger-bg,var(--zui-color-zinc-900,#18181b))] text-[color:var(--zui-circular-menu-default-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-default-trigger-hover-bg,var(--zui-color-zinc-800,#27272a))] dark:border-[color:var(--zui-circular-menu-default-trigger-border-dark,var(--zui-color-zinc-100,#f4f4f5))] dark:bg-[var(--zui-circular-menu-default-trigger-bg-dark,var(--zui-color-zinc-100,#f4f4f5))] dark:text-[color:var(--zui-circular-menu-default-trigger-fg-dark,var(--zui-color-zinc-900,#18181b))] dark:hover:bg-[var(--zui-circular-menu-default-trigger-hover-bg-dark,#ffffff)]",
  primary:
    "border-[color:var(--zui-circular-menu-primary-trigger-border,var(--zui-color-blue-600,#2563eb))] bg-[var(--zui-circular-menu-primary-trigger-bg,var(--zui-color-blue-600,#2563eb))] text-[color:var(--zui-circular-menu-primary-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-primary-trigger-hover-bg,var(--zui-color-blue-700,#1d4ed8))] dark:border-[color:var(--zui-circular-menu-primary-trigger-border-dark,var(--zui-color-blue-400,#60a5fa))] dark:bg-[var(--zui-circular-menu-primary-trigger-bg-dark,var(--zui-color-blue-500,#3b82f6))] dark:text-[color:var(--zui-circular-menu-primary-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-primary-trigger-hover-bg-dark,var(--zui-color-blue-400,#60a5fa))]",
  secondary:
    "border-[color:var(--zui-circular-menu-secondary-trigger-border,var(--zui-color-slate-600,#475569))] bg-[var(--zui-circular-menu-secondary-trigger-bg,var(--zui-color-slate-600,#475569))] text-[color:var(--zui-circular-menu-secondary-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-secondary-trigger-hover-bg,var(--zui-color-slate-700,#334155))] dark:border-[color:var(--zui-circular-menu-secondary-trigger-border-dark,var(--zui-color-slate-400,#94a3b8))] dark:bg-[var(--zui-circular-menu-secondary-trigger-bg-dark,var(--zui-color-slate-500,#64748b))] dark:text-[color:var(--zui-circular-menu-secondary-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-secondary-trigger-hover-bg-dark,var(--zui-color-slate-400,#94a3b8))]",
  success:
    "border-[color:var(--zui-circular-menu-success-trigger-border,var(--zui-color-emerald-600,#059669))] bg-[var(--zui-circular-menu-success-trigger-bg,var(--zui-color-emerald-600,#059669))] text-[color:var(--zui-circular-menu-success-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-success-trigger-hover-bg,var(--zui-color-emerald-700,#047857))] dark:border-[color:var(--zui-circular-menu-success-trigger-border-dark,var(--zui-color-emerald-400,#34d399))] dark:bg-[var(--zui-circular-menu-success-trigger-bg-dark,var(--zui-color-emerald-500,#10b981))] dark:text-[color:var(--zui-circular-menu-success-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-success-trigger-hover-bg-dark,var(--zui-color-emerald-400,#34d399))]",
  destructive:
    "border-[color:var(--zui-circular-menu-destructive-trigger-border,var(--zui-color-red-600,#dc2626))] bg-[var(--zui-circular-menu-destructive-trigger-bg,var(--zui-color-red-600,#dc2626))] text-[color:var(--zui-circular-menu-destructive-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-destructive-trigger-hover-bg,var(--zui-color-red-700,#b91c1c))] dark:border-[color:var(--zui-circular-menu-destructive-trigger-border-dark,var(--zui-color-red-400,#f87171))] dark:bg-[var(--zui-circular-menu-destructive-trigger-bg-dark,var(--zui-color-red-500,#ef4444))] dark:text-[color:var(--zui-circular-menu-destructive-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-destructive-trigger-hover-bg-dark,var(--zui-color-red-400,#f87171))]",
  warning:
    "border-[color:var(--zui-circular-menu-warning-trigger-border,var(--zui-color-amber-600,#d97706))] bg-[var(--zui-circular-menu-warning-trigger-bg,var(--zui-color-amber-600,#d97706))] text-[color:var(--zui-circular-menu-warning-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-warning-trigger-hover-bg,var(--zui-color-amber-700,#b45309))] dark:border-[color:var(--zui-circular-menu-warning-trigger-border-dark,var(--zui-color-amber-400,#fbbf24))] dark:bg-[var(--zui-circular-menu-warning-trigger-bg-dark,var(--zui-color-amber-500,#f59e0b))] dark:text-[color:var(--zui-circular-menu-warning-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-warning-trigger-hover-bg-dark,var(--zui-color-amber-400,#fbbf24))]",
  info: "border-[color:var(--zui-circular-menu-info-trigger-border,var(--zui-color-cyan-600,#0891b2))] bg-[var(--zui-circular-menu-info-trigger-bg,var(--zui-color-cyan-600,#0891b2))] text-[color:var(--zui-circular-menu-info-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-info-trigger-hover-bg,var(--zui-color-cyan-700,#0e7490))] dark:border-[color:var(--zui-circular-menu-info-trigger-border-dark,var(--zui-color-cyan-400,#22d3ee))] dark:bg-[var(--zui-circular-menu-info-trigger-bg-dark,var(--zui-color-cyan-500,#06b6d4))] dark:text-[color:var(--zui-circular-menu-info-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-info-trigger-hover-bg-dark,var(--zui-color-cyan-400,#22d3ee))]",
  blue: "border-[color:var(--zui-circular-menu-blue-trigger-border,var(--zui-color-blue-600,#2563eb))] bg-[var(--zui-circular-menu-blue-trigger-bg,var(--zui-color-blue-600,#2563eb))] text-[color:var(--zui-circular-menu-blue-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-blue-trigger-hover-bg,var(--zui-color-blue-700,#1d4ed8))] dark:border-[color:var(--zui-circular-menu-blue-trigger-border-dark,var(--zui-color-blue-400,#60a5fa))] dark:bg-[var(--zui-circular-menu-blue-trigger-bg-dark,var(--zui-color-blue-500,#3b82f6))] dark:text-[color:var(--zui-circular-menu-blue-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-blue-trigger-hover-bg-dark,var(--zui-color-blue-400,#60a5fa))]",
  violet:
    "border-[color:var(--zui-circular-menu-violet-trigger-border,var(--zui-color-violet-600,#7c3aed))] bg-[var(--zui-circular-menu-violet-trigger-bg,var(--zui-color-violet-600,#7c3aed))] text-[color:var(--zui-circular-menu-violet-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-violet-trigger-hover-bg,var(--zui-color-violet-700,#6d28d9))] dark:border-[color:var(--zui-circular-menu-violet-trigger-border-dark,var(--zui-color-violet-400,#a78bfa))] dark:bg-[var(--zui-circular-menu-violet-trigger-bg-dark,var(--zui-color-violet-500,#8b5cf6))] dark:text-[color:var(--zui-circular-menu-violet-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-violet-trigger-hover-bg-dark,var(--zui-color-violet-400,#a78bfa))]",
  emerald:
    "border-[color:var(--zui-circular-menu-emerald-trigger-border,var(--zui-color-emerald-600,#059669))] bg-[var(--zui-circular-menu-emerald-trigger-bg,var(--zui-color-emerald-600,#059669))] text-[color:var(--zui-circular-menu-emerald-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-emerald-trigger-hover-bg,var(--zui-color-emerald-700,#047857))] dark:border-[color:var(--zui-circular-menu-emerald-trigger-border-dark,var(--zui-color-emerald-400,#34d399))] dark:bg-[var(--zui-circular-menu-emerald-trigger-bg-dark,var(--zui-color-emerald-500,#10b981))] dark:text-[color:var(--zui-circular-menu-emerald-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-emerald-trigger-hover-bg-dark,var(--zui-color-emerald-400,#34d399))]",
  amber:
    "border-[color:var(--zui-circular-menu-amber-trigger-border,var(--zui-color-amber-600,#d97706))] bg-[var(--zui-circular-menu-amber-trigger-bg,var(--zui-color-amber-600,#d97706))] text-[color:var(--zui-circular-menu-amber-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-amber-trigger-hover-bg,var(--zui-color-amber-700,#b45309))] dark:border-[color:var(--zui-circular-menu-amber-trigger-border-dark,var(--zui-color-amber-400,#fbbf24))] dark:bg-[var(--zui-circular-menu-amber-trigger-bg-dark,var(--zui-color-amber-500,#f59e0b))] dark:text-[color:var(--zui-circular-menu-amber-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-amber-trigger-hover-bg-dark,var(--zui-color-amber-400,#fbbf24))]",
  rose: "border-[color:var(--zui-circular-menu-rose-trigger-border,var(--zui-color-rose-600,#e11d48))] bg-[var(--zui-circular-menu-rose-trigger-bg,var(--zui-color-rose-600,#e11d48))] text-[color:var(--zui-circular-menu-rose-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-rose-trigger-hover-bg,var(--zui-color-rose-700,#be123c))] dark:border-[color:var(--zui-circular-menu-rose-trigger-border-dark,var(--zui-color-rose-400,#fb7185))] dark:bg-[var(--zui-circular-menu-rose-trigger-bg-dark,var(--zui-color-rose-500,#f43f5e))] dark:text-[color:var(--zui-circular-menu-rose-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-rose-trigger-hover-bg-dark,var(--zui-color-rose-400,#fb7185))]",
  slate:
    "border-[color:var(--zui-circular-menu-slate-trigger-border,var(--zui-color-slate-600,#475569))] bg-[var(--zui-circular-menu-slate-trigger-bg,var(--zui-color-slate-600,#475569))] text-[color:var(--zui-circular-menu-slate-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-slate-trigger-hover-bg,var(--zui-color-slate-700,#334155))] dark:border-[color:var(--zui-circular-menu-slate-trigger-border-dark,var(--zui-color-slate-400,#94a3b8))] dark:bg-[var(--zui-circular-menu-slate-trigger-bg-dark,var(--zui-color-slate-500,#64748b))] dark:text-[color:var(--zui-circular-menu-slate-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-slate-trigger-hover-bg-dark,var(--zui-color-slate-400,#94a3b8))]",
  zinc: "border-[color:var(--zui-circular-menu-zinc-trigger-border,var(--zui-color-zinc-600,#52525b))] bg-[var(--zui-circular-menu-zinc-trigger-bg,var(--zui-color-zinc-600,#52525b))] text-[color:var(--zui-circular-menu-zinc-trigger-fg,#ffffff)] hover:bg-[var(--zui-circular-menu-zinc-trigger-hover-bg,var(--zui-color-zinc-700,#3f3f46))] dark:border-[color:var(--zui-circular-menu-zinc-trigger-border-dark,var(--zui-color-zinc-400,#a1a1aa))] dark:bg-[var(--zui-circular-menu-zinc-trigger-bg-dark,var(--zui-color-zinc-500,#71717a))] dark:text-[color:var(--zui-circular-menu-zinc-trigger-fg-dark,#ffffff)] dark:hover:bg-[var(--zui-circular-menu-zinc-trigger-hover-bg-dark,var(--zui-color-zinc-400,#a1a1aa))]",
  "gradient-blue":
    "border-[color:var(--zui-circular-menu-gradient-blue-trigger-border,var(--zui-color-blue-500,#3b82f6))] bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-blue-trigger-from,#2563eb),var(--zui-circular-menu-gradient-blue-trigger-to,#06b6d4))] text-[color:var(--zui-circular-menu-gradient-blue-trigger-fg,#ffffff)] hover:brightness-110 active:brightness-95 dark:border-[color:var(--zui-circular-menu-gradient-blue-trigger-border-dark,var(--zui-color-blue-300,#93c5fd))] dark:bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-blue-trigger-from-dark,#3b82f6),var(--zui-circular-menu-gradient-blue-trigger-to-dark,#22d3ee))] dark:text-[color:var(--zui-circular-menu-gradient-blue-trigger-fg-dark,#ffffff)]",
  "gradient-violet":
    "border-[color:var(--zui-circular-menu-gradient-violet-trigger-border,var(--zui-color-violet-500,#8b5cf6))] bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-violet-trigger-from,#7c3aed),var(--zui-circular-menu-gradient-violet-trigger-to,#d946ef))] text-[color:var(--zui-circular-menu-gradient-violet-trigger-fg,#ffffff)] hover:brightness-110 active:brightness-95 dark:border-[color:var(--zui-circular-menu-gradient-violet-trigger-border-dark,var(--zui-color-violet-300,#c4b5fd))] dark:bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-violet-trigger-from-dark,#8b5cf6),var(--zui-circular-menu-gradient-violet-trigger-to-dark,#e879f9))] dark:text-[color:var(--zui-circular-menu-gradient-violet-trigger-fg-dark,#ffffff)]",
  "gradient-rose":
    "border-[color:var(--zui-circular-menu-gradient-rose-trigger-border,var(--zui-color-rose-500,#f43f5e))] bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-rose-trigger-from,#e11d48),var(--zui-circular-menu-gradient-rose-trigger-to,#f97316))] text-[color:var(--zui-circular-menu-gradient-rose-trigger-fg,#ffffff)] hover:brightness-110 active:brightness-95 dark:border-[color:var(--zui-circular-menu-gradient-rose-trigger-border-dark,var(--zui-color-rose-300,#fda4af))] dark:bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-rose-trigger-from-dark,#f43f5e),var(--zui-circular-menu-gradient-rose-trigger-to-dark,#fb923c))] dark:text-[color:var(--zui-circular-menu-gradient-rose-trigger-fg-dark,#ffffff)]",
  glass:
    "border-[color:var(--zui-circular-menu-glass-trigger-border,rgba(255,255,255,0.7))] bg-[var(--zui-circular-menu-glass-trigger-bg,rgba(255,255,255,0.72))] text-[color:var(--zui-circular-menu-glass-trigger-fg,var(--zui-color-slate-800,#1e293b))] hover:bg-[var(--zui-circular-menu-glass-trigger-hover-bg,rgba(255,255,255,0.9))] backdrop-blur-xl dark:border-[color:var(--zui-circular-menu-glass-trigger-border-dark,rgba(255,255,255,0.18))] dark:bg-[var(--zui-circular-menu-glass-trigger-bg-dark,rgba(15,23,42,0.68))] dark:text-[color:var(--zui-circular-menu-glass-trigger-fg-dark,var(--zui-color-slate-100,#f1f5f9))] dark:hover:bg-[var(--zui-circular-menu-glass-trigger-hover-bg-dark,rgba(15,23,42,0.85))]",
} as const;

/** Item disc palettes: soft surfaces that read against the page. */
export const zuiCircularMenuItemAppearances = {
  default:
    "border-[color:var(--zui-circular-menu-default-item-border,var(--zui-color-zinc-200,#e4e4e7))] bg-[var(--zui-circular-menu-default-item-bg,var(--zui-bg,#ffffff))] text-[color:var(--zui-circular-menu-default-item-fg,var(--zui-color-zinc-700,#3f3f46))] hover:bg-[var(--zui-circular-menu-default-item-hover-bg,var(--zui-color-zinc-100,#f4f4f5))] active:bg-[var(--zui-circular-menu-default-item-active-bg,var(--zui-color-zinc-200,#e4e4e7))] dark:border-[color:var(--zui-circular-menu-default-item-border-dark,var(--zui-color-zinc-700,#3f3f46))] dark:bg-[var(--zui-circular-menu-default-item-bg-dark,var(--zui-color-zinc-900,#18181b))] dark:text-[color:var(--zui-circular-menu-default-item-fg-dark,var(--zui-color-zinc-100,#f4f4f5))] dark:hover:bg-[var(--zui-circular-menu-default-item-hover-bg-dark,var(--zui-color-zinc-800,#27272a))] dark:active:bg-[var(--zui-circular-menu-default-item-active-bg-dark,var(--zui-color-zinc-700,#3f3f46))]",
  primary:
    "border-[color:var(--zui-circular-menu-primary-item-border,var(--zui-color-blue-200,#bfdbfe))] bg-[var(--zui-circular-menu-primary-item-bg,var(--zui-color-blue-50,#eff6ff))] text-[color:var(--zui-circular-menu-primary-item-fg,var(--zui-color-blue-700,#1d4ed8))] hover:bg-[var(--zui-circular-menu-primary-item-hover-bg,var(--zui-color-blue-100,#dbeafe))] active:bg-[var(--zui-circular-menu-primary-item-active-bg,var(--zui-color-blue-200,#bfdbfe))] dark:border-[color:var(--zui-circular-menu-primary-item-border-dark,var(--zui-color-blue-800,#1e40af))] dark:bg-[var(--zui-circular-menu-primary-item-bg-dark,var(--zui-color-blue-950,#172554))] dark:text-[color:var(--zui-circular-menu-primary-item-fg-dark,var(--zui-color-blue-100,#dbeafe))] dark:hover:bg-[var(--zui-circular-menu-primary-item-hover-bg-dark,var(--zui-color-blue-900,#1e3a8a))] dark:active:bg-[var(--zui-circular-menu-primary-item-active-bg-dark,var(--zui-color-blue-800,#1e40af))]",
  secondary:
    "border-[color:var(--zui-circular-menu-secondary-item-border,var(--zui-color-slate-200,#e2e8f0))] bg-[var(--zui-circular-menu-secondary-item-bg,var(--zui-color-slate-50,#f8fafc))] text-[color:var(--zui-circular-menu-secondary-item-fg,var(--zui-color-slate-700,#334155))] hover:bg-[var(--zui-circular-menu-secondary-item-hover-bg,var(--zui-color-slate-100,#f1f5f9))] active:bg-[var(--zui-circular-menu-secondary-item-active-bg,var(--zui-color-slate-200,#e2e8f0))] dark:border-[color:var(--zui-circular-menu-secondary-item-border-dark,var(--zui-color-slate-800,#1e293b))] dark:bg-[var(--zui-circular-menu-secondary-item-bg-dark,var(--zui-color-slate-950,#020617))] dark:text-[color:var(--zui-circular-menu-secondary-item-fg-dark,var(--zui-color-slate-100,#f1f5f9))] dark:hover:bg-[var(--zui-circular-menu-secondary-item-hover-bg-dark,var(--zui-color-slate-900,#0f172a))] dark:active:bg-[var(--zui-circular-menu-secondary-item-active-bg-dark,var(--zui-color-slate-800,#1e293b))]",
  success:
    "border-[color:var(--zui-circular-menu-success-item-border,var(--zui-color-emerald-200,#a7f3d0))] bg-[var(--zui-circular-menu-success-item-bg,var(--zui-color-emerald-50,#ecfdf5))] text-[color:var(--zui-circular-menu-success-item-fg,var(--zui-color-emerald-700,#047857))] hover:bg-[var(--zui-circular-menu-success-item-hover-bg,var(--zui-color-emerald-100,#d1fae5))] active:bg-[var(--zui-circular-menu-success-item-active-bg,var(--zui-color-emerald-200,#a7f3d0))] dark:border-[color:var(--zui-circular-menu-success-item-border-dark,var(--zui-color-emerald-800,#065f46))] dark:bg-[var(--zui-circular-menu-success-item-bg-dark,var(--zui-color-emerald-950,#022c22))] dark:text-[color:var(--zui-circular-menu-success-item-fg-dark,var(--zui-color-emerald-100,#d1fae5))] dark:hover:bg-[var(--zui-circular-menu-success-item-hover-bg-dark,var(--zui-color-emerald-900,#064e3b))] dark:active:bg-[var(--zui-circular-menu-success-item-active-bg-dark,var(--zui-color-emerald-800,#065f46))]",
  destructive:
    "border-[color:var(--zui-circular-menu-destructive-item-border,var(--zui-color-red-200,#fecaca))] bg-[var(--zui-circular-menu-destructive-item-bg,var(--zui-color-red-50,#fef2f2))] text-[color:var(--zui-circular-menu-destructive-item-fg,var(--zui-color-red-700,#b91c1c))] hover:bg-[var(--zui-circular-menu-destructive-item-hover-bg,var(--zui-color-red-100,#fee2e2))] active:bg-[var(--zui-circular-menu-destructive-item-active-bg,var(--zui-color-red-200,#fecaca))] dark:border-[color:var(--zui-circular-menu-destructive-item-border-dark,var(--zui-color-red-800,#991b1b))] dark:bg-[var(--zui-circular-menu-destructive-item-bg-dark,var(--zui-color-red-950,#450a0a))] dark:text-[color:var(--zui-circular-menu-destructive-item-fg-dark,var(--zui-color-red-100,#fee2e2))] dark:hover:bg-[var(--zui-circular-menu-destructive-item-hover-bg-dark,var(--zui-color-red-900,#7f1d1d))] dark:active:bg-[var(--zui-circular-menu-destructive-item-active-bg-dark,var(--zui-color-red-800,#991b1b))]",
  warning:
    "border-[color:var(--zui-circular-menu-warning-item-border,var(--zui-color-amber-200,#fde68a))] bg-[var(--zui-circular-menu-warning-item-bg,var(--zui-color-amber-50,#fffbeb))] text-[color:var(--zui-circular-menu-warning-item-fg,var(--zui-color-amber-700,#b45309))] hover:bg-[var(--zui-circular-menu-warning-item-hover-bg,var(--zui-color-amber-100,#fef3c7))] active:bg-[var(--zui-circular-menu-warning-item-active-bg,var(--zui-color-amber-200,#fde68a))] dark:border-[color:var(--zui-circular-menu-warning-item-border-dark,var(--zui-color-amber-800,#92400e))] dark:bg-[var(--zui-circular-menu-warning-item-bg-dark,var(--zui-color-amber-950,#451a03))] dark:text-[color:var(--zui-circular-menu-warning-item-fg-dark,var(--zui-color-amber-100,#fef3c7))] dark:hover:bg-[var(--zui-circular-menu-warning-item-hover-bg-dark,var(--zui-color-amber-900,#78350f))] dark:active:bg-[var(--zui-circular-menu-warning-item-active-bg-dark,var(--zui-color-amber-800,#92400e))]",
  info: "border-[color:var(--zui-circular-menu-info-item-border,var(--zui-color-cyan-200,#a5f3fc))] bg-[var(--zui-circular-menu-info-item-bg,var(--zui-color-cyan-50,#ecfeff))] text-[color:var(--zui-circular-menu-info-item-fg,var(--zui-color-cyan-700,#0e7490))] hover:bg-[var(--zui-circular-menu-info-item-hover-bg,var(--zui-color-cyan-100,#cffafe))] active:bg-[var(--zui-circular-menu-info-item-active-bg,var(--zui-color-cyan-200,#a5f3fc))] dark:border-[color:var(--zui-circular-menu-info-item-border-dark,var(--zui-color-cyan-800,#155e75))] dark:bg-[var(--zui-circular-menu-info-item-bg-dark,var(--zui-color-cyan-950,#083344))] dark:text-[color:var(--zui-circular-menu-info-item-fg-dark,var(--zui-color-cyan-100,#cffafe))] dark:hover:bg-[var(--zui-circular-menu-info-item-hover-bg-dark,var(--zui-color-cyan-900,#164e63))] dark:active:bg-[var(--zui-circular-menu-info-item-active-bg-dark,var(--zui-color-cyan-800,#155e75))]",
  blue: "border-[color:var(--zui-circular-menu-blue-item-border,var(--zui-color-blue-200,#bfdbfe))] bg-[var(--zui-circular-menu-blue-item-bg,var(--zui-color-blue-50,#eff6ff))] text-[color:var(--zui-circular-menu-blue-item-fg,var(--zui-color-blue-700,#1d4ed8))] hover:bg-[var(--zui-circular-menu-blue-item-hover-bg,var(--zui-color-blue-100,#dbeafe))] active:bg-[var(--zui-circular-menu-blue-item-active-bg,var(--zui-color-blue-200,#bfdbfe))] dark:border-[color:var(--zui-circular-menu-blue-item-border-dark,var(--zui-color-blue-800,#1e40af))] dark:bg-[var(--zui-circular-menu-blue-item-bg-dark,var(--zui-color-blue-950,#172554))] dark:text-[color:var(--zui-circular-menu-blue-item-fg-dark,var(--zui-color-blue-100,#dbeafe))] dark:hover:bg-[var(--zui-circular-menu-blue-item-hover-bg-dark,var(--zui-color-blue-900,#1e3a8a))] dark:active:bg-[var(--zui-circular-menu-blue-item-active-bg-dark,var(--zui-color-blue-800,#1e40af))]",
  violet:
    "border-[color:var(--zui-circular-menu-violet-item-border,var(--zui-color-violet-200,#ddd6fe))] bg-[var(--zui-circular-menu-violet-item-bg,var(--zui-color-violet-50,#f5f3ff))] text-[color:var(--zui-circular-menu-violet-item-fg,var(--zui-color-violet-700,#6d28d9))] hover:bg-[var(--zui-circular-menu-violet-item-hover-bg,var(--zui-color-violet-100,#ede9fe))] active:bg-[var(--zui-circular-menu-violet-item-active-bg,var(--zui-color-violet-200,#ddd6fe))] dark:border-[color:var(--zui-circular-menu-violet-item-border-dark,var(--zui-color-violet-800,#5b21b6))] dark:bg-[var(--zui-circular-menu-violet-item-bg-dark,var(--zui-color-violet-950,#2e1065))] dark:text-[color:var(--zui-circular-menu-violet-item-fg-dark,var(--zui-color-violet-100,#ede9fe))] dark:hover:bg-[var(--zui-circular-menu-violet-item-hover-bg-dark,var(--zui-color-violet-900,#4c1d95))] dark:active:bg-[var(--zui-circular-menu-violet-item-active-bg-dark,var(--zui-color-violet-800,#5b21b6))]",
  emerald:
    "border-[color:var(--zui-circular-menu-emerald-item-border,var(--zui-color-emerald-200,#a7f3d0))] bg-[var(--zui-circular-menu-emerald-item-bg,var(--zui-color-emerald-50,#ecfdf5))] text-[color:var(--zui-circular-menu-emerald-item-fg,var(--zui-color-emerald-700,#047857))] hover:bg-[var(--zui-circular-menu-emerald-item-hover-bg,var(--zui-color-emerald-100,#d1fae5))] active:bg-[var(--zui-circular-menu-emerald-item-active-bg,var(--zui-color-emerald-200,#a7f3d0))] dark:border-[color:var(--zui-circular-menu-emerald-item-border-dark,var(--zui-color-emerald-800,#065f46))] dark:bg-[var(--zui-circular-menu-emerald-item-bg-dark,var(--zui-color-emerald-950,#022c22))] dark:text-[color:var(--zui-circular-menu-emerald-item-fg-dark,var(--zui-color-emerald-100,#d1fae5))] dark:hover:bg-[var(--zui-circular-menu-emerald-item-hover-bg-dark,var(--zui-color-emerald-900,#064e3b))] dark:active:bg-[var(--zui-circular-menu-emerald-item-active-bg-dark,var(--zui-color-emerald-800,#065f46))]",
  amber:
    "border-[color:var(--zui-circular-menu-amber-item-border,var(--zui-color-amber-200,#fde68a))] bg-[var(--zui-circular-menu-amber-item-bg,var(--zui-color-amber-50,#fffbeb))] text-[color:var(--zui-circular-menu-amber-item-fg,var(--zui-color-amber-700,#b45309))] hover:bg-[var(--zui-circular-menu-amber-item-hover-bg,var(--zui-color-amber-100,#fef3c7))] active:bg-[var(--zui-circular-menu-amber-item-active-bg,var(--zui-color-amber-200,#fde68a))] dark:border-[color:var(--zui-circular-menu-amber-item-border-dark,var(--zui-color-amber-800,#92400e))] dark:bg-[var(--zui-circular-menu-amber-item-bg-dark,var(--zui-color-amber-950,#451a03))] dark:text-[color:var(--zui-circular-menu-amber-item-fg-dark,var(--zui-color-amber-100,#fef3c7))] dark:hover:bg-[var(--zui-circular-menu-amber-item-hover-bg-dark,var(--zui-color-amber-900,#78350f))] dark:active:bg-[var(--zui-circular-menu-amber-item-active-bg-dark,var(--zui-color-amber-800,#92400e))]",
  rose: "border-[color:var(--zui-circular-menu-rose-item-border,var(--zui-color-rose-200,#fecdd3))] bg-[var(--zui-circular-menu-rose-item-bg,var(--zui-color-rose-50,#fff1f2))] text-[color:var(--zui-circular-menu-rose-item-fg,var(--zui-color-rose-700,#be123c))] hover:bg-[var(--zui-circular-menu-rose-item-hover-bg,var(--zui-color-rose-100,#ffe4e6))] active:bg-[var(--zui-circular-menu-rose-item-active-bg,var(--zui-color-rose-200,#fecdd3))] dark:border-[color:var(--zui-circular-menu-rose-item-border-dark,var(--zui-color-rose-800,#9f1239))] dark:bg-[var(--zui-circular-menu-rose-item-bg-dark,var(--zui-color-rose-950,#4c0519))] dark:text-[color:var(--zui-circular-menu-rose-item-fg-dark,var(--zui-color-rose-100,#ffe4e6))] dark:hover:bg-[var(--zui-circular-menu-rose-item-hover-bg-dark,var(--zui-color-rose-900,#881337))] dark:active:bg-[var(--zui-circular-menu-rose-item-active-bg-dark,var(--zui-color-rose-800,#9f1239))]",
  slate:
    "border-[color:var(--zui-circular-menu-slate-item-border,var(--zui-color-slate-200,#e2e8f0))] bg-[var(--zui-circular-menu-slate-item-bg,var(--zui-color-slate-50,#f8fafc))] text-[color:var(--zui-circular-menu-slate-item-fg,var(--zui-color-slate-700,#334155))] hover:bg-[var(--zui-circular-menu-slate-item-hover-bg,var(--zui-color-slate-100,#f1f5f9))] active:bg-[var(--zui-circular-menu-slate-item-active-bg,var(--zui-color-slate-200,#e2e8f0))] dark:border-[color:var(--zui-circular-menu-slate-item-border-dark,var(--zui-color-slate-800,#1e293b))] dark:bg-[var(--zui-circular-menu-slate-item-bg-dark,var(--zui-color-slate-950,#020617))] dark:text-[color:var(--zui-circular-menu-slate-item-fg-dark,var(--zui-color-slate-100,#f1f5f9))] dark:hover:bg-[var(--zui-circular-menu-slate-item-hover-bg-dark,var(--zui-color-slate-900,#0f172a))] dark:active:bg-[var(--zui-circular-menu-slate-item-active-bg-dark,var(--zui-color-slate-800,#1e293b))]",
  zinc: "border-[color:var(--zui-circular-menu-zinc-item-border,var(--zui-color-zinc-200,#e4e4e7))] bg-[var(--zui-circular-menu-zinc-item-bg,var(--zui-color-zinc-50,#fafafa))] text-[color:var(--zui-circular-menu-zinc-item-fg,var(--zui-color-zinc-700,#3f3f46))] hover:bg-[var(--zui-circular-menu-zinc-item-hover-bg,var(--zui-color-zinc-100,#f4f4f5))] active:bg-[var(--zui-circular-menu-zinc-item-active-bg,var(--zui-color-zinc-200,#e4e4e7))] dark:border-[color:var(--zui-circular-menu-zinc-item-border-dark,var(--zui-color-zinc-800,#27272a))] dark:bg-[var(--zui-circular-menu-zinc-item-bg-dark,var(--zui-color-zinc-950,#09090b))] dark:text-[color:var(--zui-circular-menu-zinc-item-fg-dark,var(--zui-color-zinc-100,#f4f4f5))] dark:hover:bg-[var(--zui-circular-menu-zinc-item-hover-bg-dark,var(--zui-color-zinc-900,#18181b))] dark:active:bg-[var(--zui-circular-menu-zinc-item-active-bg-dark,var(--zui-color-zinc-800,#27272a))]",
  "gradient-blue":
    "border-[color:var(--zui-circular-menu-gradient-blue-item-border,#bfdbfe)] bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-blue-item-from,#eff6ff),var(--zui-circular-menu-gradient-blue-item-to,#ecfeff))] text-[color:var(--zui-circular-menu-gradient-blue-item-fg,#1d4ed8)] hover:brightness-105 active:brightness-95 dark:border-[color:var(--zui-circular-menu-gradient-blue-item-border-dark,#1e40af)] dark:bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-blue-item-from-dark,#172554),var(--zui-circular-menu-gradient-blue-item-to-dark,#083344))] dark:text-[color:var(--zui-circular-menu-gradient-blue-item-fg-dark,#dbeafe)]",
  "gradient-violet":
    "border-[color:var(--zui-circular-menu-gradient-violet-item-border,#ddd6fe)] bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-violet-item-from,#f5f3ff),var(--zui-circular-menu-gradient-violet-item-to,#fdf4ff))] text-[color:var(--zui-circular-menu-gradient-violet-item-fg,#6d28d9)] hover:brightness-105 active:brightness-95 dark:border-[color:var(--zui-circular-menu-gradient-violet-item-border-dark,#5b21b6)] dark:bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-violet-item-from-dark,#2e1065),var(--zui-circular-menu-gradient-violet-item-to-dark,#4a044e))] dark:text-[color:var(--zui-circular-menu-gradient-violet-item-fg-dark,#ede9fe)]",
  "gradient-rose":
    "border-[color:var(--zui-circular-menu-gradient-rose-item-border,#fecdd3)] bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-rose-item-from,#fff1f2),var(--zui-circular-menu-gradient-rose-item-to,#fff7ed))] text-[color:var(--zui-circular-menu-gradient-rose-item-fg,#be123c)] hover:brightness-105 active:brightness-95 dark:border-[color:var(--zui-circular-menu-gradient-rose-item-border-dark,#9f1239)] dark:bg-[linear-gradient(135deg,var(--zui-circular-menu-gradient-rose-item-from-dark,#4c0519),var(--zui-circular-menu-gradient-rose-item-to-dark,#431407))] dark:text-[color:var(--zui-circular-menu-gradient-rose-item-fg-dark,#ffe4e6)]",
  glass:
    "border-[color:var(--zui-circular-menu-glass-item-border,rgba(148,163,184,0.35))] bg-[var(--zui-circular-menu-glass-item-bg,rgba(255,255,255,0.62))] text-[color:var(--zui-circular-menu-glass-item-fg,var(--zui-color-slate-800,#1e293b))] hover:bg-[var(--zui-circular-menu-glass-item-hover-bg,rgba(255,255,255,0.82))] active:bg-[var(--zui-circular-menu-glass-item-active-bg,rgba(255,255,255,0.92))] backdrop-blur-xl dark:border-[color:var(--zui-circular-menu-glass-item-border-dark,rgba(255,255,255,0.14))] dark:bg-[var(--zui-circular-menu-glass-item-bg-dark,rgba(15,23,42,0.55))] dark:text-[color:var(--zui-circular-menu-glass-item-fg-dark,var(--zui-color-slate-100,#f1f5f9))] dark:hover:bg-[var(--zui-circular-menu-glass-item-hover-bg-dark,rgba(15,23,42,0.72))] dark:active:bg-[var(--zui-circular-menu-glass-item-active-bg-dark,rgba(15,23,42,0.85))]",
} as const;

/** Spoke palettes, matched to the item surfaces. */
export const zuiCircularMenuSpokeAppearances = {
  default:
    "bg-[var(--zui-circular-menu-default-spoke-bg,var(--zui-color-zinc-200,#e4e4e7))] dark:bg-[var(--zui-circular-menu-default-spoke-bg-dark,var(--zui-color-zinc-700,#3f3f46))]",
  primary:
    "bg-[var(--zui-circular-menu-primary-spoke-bg,var(--zui-color-blue-200,#bfdbfe))] dark:bg-[var(--zui-circular-menu-primary-spoke-bg-dark,var(--zui-color-blue-800,#1e40af))]",
  secondary:
    "bg-[var(--zui-circular-menu-secondary-spoke-bg,var(--zui-color-slate-200,#e2e8f0))] dark:bg-[var(--zui-circular-menu-secondary-spoke-bg-dark,var(--zui-color-slate-800,#1e293b))]",
  success:
    "bg-[var(--zui-circular-menu-success-spoke-bg,var(--zui-color-emerald-200,#a7f3d0))] dark:bg-[var(--zui-circular-menu-success-spoke-bg-dark,var(--zui-color-emerald-800,#065f46))]",
  destructive:
    "bg-[var(--zui-circular-menu-destructive-spoke-bg,var(--zui-color-red-200,#fecaca))] dark:bg-[var(--zui-circular-menu-destructive-spoke-bg-dark,var(--zui-color-red-800,#991b1b))]",
  warning:
    "bg-[var(--zui-circular-menu-warning-spoke-bg,var(--zui-color-amber-200,#fde68a))] dark:bg-[var(--zui-circular-menu-warning-spoke-bg-dark,var(--zui-color-amber-800,#92400e))]",
  info: "bg-[var(--zui-circular-menu-info-spoke-bg,var(--zui-color-cyan-200,#a5f3fc))] dark:bg-[var(--zui-circular-menu-info-spoke-bg-dark,var(--zui-color-cyan-800,#155e75))]",
  blue: "bg-[var(--zui-circular-menu-blue-spoke-bg,var(--zui-color-blue-200,#bfdbfe))] dark:bg-[var(--zui-circular-menu-blue-spoke-bg-dark,var(--zui-color-blue-800,#1e40af))]",
  violet:
    "bg-[var(--zui-circular-menu-violet-spoke-bg,var(--zui-color-violet-200,#ddd6fe))] dark:bg-[var(--zui-circular-menu-violet-spoke-bg-dark,var(--zui-color-violet-800,#5b21b6))]",
  emerald:
    "bg-[var(--zui-circular-menu-emerald-spoke-bg,var(--zui-color-emerald-200,#a7f3d0))] dark:bg-[var(--zui-circular-menu-emerald-spoke-bg-dark,var(--zui-color-emerald-800,#065f46))]",
  amber:
    "bg-[var(--zui-circular-menu-amber-spoke-bg,var(--zui-color-amber-200,#fde68a))] dark:bg-[var(--zui-circular-menu-amber-spoke-bg-dark,var(--zui-color-amber-800,#92400e))]",
  rose: "bg-[var(--zui-circular-menu-rose-spoke-bg,var(--zui-color-rose-200,#fecdd3))] dark:bg-[var(--zui-circular-menu-rose-spoke-bg-dark,var(--zui-color-rose-800,#9f1239))]",
  slate:
    "bg-[var(--zui-circular-menu-slate-spoke-bg,var(--zui-color-slate-200,#e2e8f0))] dark:bg-[var(--zui-circular-menu-slate-spoke-bg-dark,var(--zui-color-slate-800,#1e293b))]",
  zinc: "bg-[var(--zui-circular-menu-zinc-spoke-bg,var(--zui-color-zinc-200,#e4e4e7))] dark:bg-[var(--zui-circular-menu-zinc-spoke-bg-dark,var(--zui-color-zinc-800,#27272a))]",
  "gradient-blue":
    "bg-[var(--zui-circular-menu-gradient-blue-spoke-bg,var(--zui-color-blue-200,#bfdbfe))] dark:bg-[var(--zui-circular-menu-gradient-blue-spoke-bg-dark,var(--zui-color-blue-800,#1e40af))]",
  "gradient-violet":
    "bg-[var(--zui-circular-menu-gradient-violet-spoke-bg,var(--zui-color-violet-200,#ddd6fe))] dark:bg-[var(--zui-circular-menu-gradient-violet-spoke-bg-dark,var(--zui-color-violet-800,#5b21b6))]",
  "gradient-rose":
    "bg-[var(--zui-circular-menu-gradient-rose-spoke-bg,var(--zui-color-rose-200,#fecdd3))] dark:bg-[var(--zui-circular-menu-gradient-rose-spoke-bg-dark,var(--zui-color-rose-800,#9f1239))]",
  glass:
    "bg-[var(--zui-circular-menu-glass-spoke-bg,rgba(148,163,184,0.45))] dark:bg-[var(--zui-circular-menu-glass-spoke-bg-dark,rgba(255,255,255,0.18))]",
} as const;

/** Canonical appearance key set for the public `CircularMenuAppearance` type. */
export const zuiCircularMenuAppearances = zuiCircularMenuItemAppearances;
