export const zuiComboboxTriggerBase =
  "flex items-center cursor-pointer justify-between rounded-md border transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-combobox-trigger-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[var(--zui-combobox-trigger-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))] focus-visible:ring-offset-2";

export const zuiComboboxTriggerVariants = {
  default:
    "border-[color:var(--zui-combobox-trigger-default-border,var(--zui-border,oklch(87.2%_0.01_258.338)))] dark:border-[color:var(--zui-combobox-trigger-default-border-dark,var(--zui-border-dark,oklch(87.2%_0.01_258.338)))] bg-[var(--zui-combobox-trigger-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-combobox-trigger-default-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-combobox-trigger-default-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-combobox-trigger-default-fg-dark,var(--zui-fg-dark,#ffffff))]",
  outline:
    "border-2 border-[color:var(--zui-combobox-trigger-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-combobox-trigger-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] text-[color:var(--zui-combobox-trigger-outline-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-combobox-trigger-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  ghost:
    "border-[color:var(--zui-combobox-trigger-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-combobox-trigger-ghost-border-dark,var(--zui-border-dark,transparent))] text-[color:var(--zui-combobox-trigger-ghost-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-combobox-trigger-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  sky: "border-[color:var(--zui-combobox-trigger-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-combobox-trigger-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] text-[color:var(--zui-combobox-trigger-sky-fg,var(--zui-color-sky,oklch(29.3%_0.066_243.157)))] dark:text-[color:var(--zui-combobox-trigger-sky-fg-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))]",
  rose: "border-[color:var(--zui-combobox-trigger-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-combobox-trigger-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] text-[color:var(--zui-combobox-trigger-rose-fg,var(--zui-color-rose,oklch(27.1%_0.105_12.094)))] dark:text-[color:var(--zui-combobox-trigger-rose-fg-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))]",
  purple:
    "border-[color:var(--zui-combobox-trigger-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-combobox-trigger-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-combobox-trigger-purple-fg,var(--zui-color-purple,oklch(29.1%_0.149_302.717)))] dark:text-[color:var(--zui-combobox-trigger-purple-fg-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  pink: "border-[color:var(--zui-combobox-trigger-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-combobox-trigger-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-combobox-trigger-pink-fg,var(--zui-color-pink,oklch(28.4%_0.109_3.907)))] dark:text-[color:var(--zui-combobox-trigger-pink-fg-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  orange:
    "border-[color:var(--zui-combobox-trigger-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-combobox-trigger-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] text-[color:var(--zui-combobox-trigger-orange-fg,var(--zui-color-orange,oklch(26.6%_0.079_36.259)))] dark:text-[color:var(--zui-combobox-trigger-orange-fg-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))]",
  yellow:
    "border-[color:var(--zui-combobox-trigger-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-combobox-trigger-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] text-[color:var(--zui-combobox-trigger-yellow-fg,var(--zui-color-yellow,oklch(28.6%_0.066_53.813)))] dark:text-[color:var(--zui-combobox-trigger-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))]",
  teal: "border-[color:var(--zui-combobox-trigger-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-combobox-trigger-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] text-[color:var(--zui-combobox-trigger-teal-fg,var(--zui-color-teal,oklch(27.7%_0.046_192.524)))] dark:text-[color:var(--zui-combobox-trigger-teal-fg-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))]",
  indigo:
    "border-[color:var(--zui-combobox-trigger-indigo-border,var(--zui-color-indigo,oklch(58.5%_0.233_277.117)))] dark:border-[color:var(--zui-combobox-trigger-indigo-border-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)))] text-[color:var(--zui-combobox-trigger-indigo-fg,var(--zui-color-indigo,oklch(25.7%_0.09_281.288)))] dark:text-[color:var(--zui-combobox-trigger-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)))]",
  emerald:
    "border-[color:var(--zui-combobox-trigger-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-combobox-trigger-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] text-[color:var(--zui-combobox-trigger-emerald-fg,var(--zui-color-emerald,oklch(26.2%_0.051_172.552)))] dark:text-[color:var(--zui-combobox-trigger-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))]",
  glass:
    "border-[color:var(--zui-combobox-trigger-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-combobox-trigger-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-combobox-trigger-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-combobox-trigger-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-combobox-trigger-glass-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-combobox-trigger-glass-fg-dark,var(--zui-fg-dark,#ffffff))] backdrop-blur-md",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-blue-from,var(--zui-color-blue,oklch(37.9%_0.146_265.522)))] dark:from-[var(--zui-combobox-trigger-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-combobox-trigger-gradient-blue-to,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:to-[var(--zui-combobox-trigger-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-green-from,var(--zui-color-green,oklch(39.3%_0.095_152.535)))] dark:from-[var(--zui-combobox-trigger-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-combobox-trigger-gradient-green-to,var(--zui-color-lime,oklch(40.5%_0.101_131.063)))] dark:to-[var(--zui-combobox-trigger-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-red-from,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:from-[var(--zui-combobox-trigger-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-combobox-trigger-gradient-red-to,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:to-[var(--zui-combobox-trigger-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-yellow-from,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:from-[var(--zui-combobox-trigger-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-combobox-trigger-gradient-yellow-to,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:to-[var(--zui-combobox-trigger-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-purple-from,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:from-[var(--zui-combobox-trigger-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-combobox-trigger-gradient-purple-to,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:to-[var(--zui-combobox-trigger-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-teal-from,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:from-[var(--zui-combobox-trigger-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-combobox-trigger-gradient-teal-to,var(--zui-color-cyan,oklch(39.8%_0.07_227.392)))] dark:to-[var(--zui-combobox-trigger-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-indigo-from,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:from-[var(--zui-combobox-trigger-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-combobox-trigger-gradient-indigo-to,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:to-[var(--zui-combobox-trigger-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-pink-from,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:from-[var(--zui-combobox-trigger-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-combobox-trigger-gradient-pink-to,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:to-[var(--zui-combobox-trigger-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-combobox-trigger-gradient-orange-from,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:from-[var(--zui-combobox-trigger-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-combobox-trigger-gradient-orange-to,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:to-[var(--zui-combobox-trigger-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] backdrop-blur-xl text-[color:var(--zui-combobox-trigger-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-combobox-trigger-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  blue: "border border-[color:var(--zui-combobox-trigger-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-combobox-trigger-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-combobox-trigger-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-combobox-trigger-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] hover:bg-[var(--zui-combobox-trigger-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))]",
  cyan: "border border-[color:var(--zui-combobox-trigger-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-combobox-trigger-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-combobox-trigger-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-combobox-trigger-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] hover:bg-[var(--zui-combobox-trigger-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))]",
  green:
    "border border-[color:var(--zui-combobox-trigger-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-combobox-trigger-green-border-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-combobox-trigger-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-combobox-trigger-green-fg-dark,var(--zui-color-green-dark,#22c55e))] hover:bg-[var(--zui-combobox-trigger-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))]",
  lime: "border border-[color:var(--zui-combobox-trigger-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-combobox-trigger-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-combobox-trigger-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-combobox-trigger-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] hover:bg-[var(--zui-combobox-trigger-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))]",
  mint: "border border-[color:var(--zui-combobox-trigger-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-combobox-trigger-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-combobox-trigger-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-combobox-trigger-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] hover:bg-[var(--zui-combobox-trigger-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))]",
  ocean:
    "border border-[color:var(--zui-combobox-trigger-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-combobox-trigger-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-combobox-trigger-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-combobox-trigger-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] hover:bg-[var(--zui-combobox-trigger-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))]",
  sapphire:
    "border border-[color:var(--zui-combobox-trigger-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-combobox-trigger-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-combobox-trigger-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-combobox-trigger-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] hover:bg-[var(--zui-combobox-trigger-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))]",
  lavender:
    "border border-[color:var(--zui-combobox-trigger-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-combobox-trigger-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-combobox-trigger-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-combobox-trigger-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] hover:bg-[var(--zui-combobox-trigger-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))]",
  ruby: "border border-[color:var(--zui-combobox-trigger-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-combobox-trigger-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-combobox-trigger-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-combobox-trigger-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] hover:bg-[var(--zui-combobox-trigger-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))]",
  red: "border border-[color:var(--zui-combobox-trigger-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-combobox-trigger-red-border-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-combobox-trigger-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-combobox-trigger-red-fg-dark,var(--zui-color-red-dark,#ef4444))] hover:bg-[var(--zui-combobox-trigger-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))]",
  slate:
    "border border-[color:var(--zui-combobox-trigger-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-combobox-trigger-slate-border-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-combobox-trigger-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-combobox-trigger-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] hover:bg-[var(--zui-combobox-trigger-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))]",
  zinc: "border border-[color:var(--zui-combobox-trigger-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-combobox-trigger-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-combobox-trigger-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-combobox-trigger-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] hover:bg-[var(--zui-combobox-trigger-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))]",
  stone:
    "border border-[color:var(--zui-combobox-trigger-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-combobox-trigger-stone-border-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-combobox-trigger-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-combobox-trigger-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] hover:bg-[var(--zui-combobox-trigger-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))]",
  royal:
    "border border-[color:var(--zui-combobox-trigger-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-combobox-trigger-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-combobox-trigger-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-combobox-trigger-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] hover:bg-[var(--zui-combobox-trigger-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))]",
  electric:
    "border border-[color:var(--zui-combobox-trigger-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-combobox-trigger-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-combobox-trigger-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-combobox-trigger-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] hover:bg-[var(--zui-combobox-trigger-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))]",
  forest:
    "border border-[color:var(--zui-combobox-trigger-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-combobox-trigger-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-combobox-trigger-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-combobox-trigger-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] hover:bg-[var(--zui-combobox-trigger-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))]",
  sunset:
    "border border-[color:var(--zui-combobox-trigger-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-combobox-trigger-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-combobox-trigger-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-combobox-trigger-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] hover:bg-[var(--zui-combobox-trigger-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))]",
  magenta:
    "border border-[color:var(--zui-combobox-trigger-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-combobox-trigger-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-combobox-trigger-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-combobox-trigger-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] hover:bg-[var(--zui-combobox-trigger-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))]",
  crimson:
    "border border-[color:var(--zui-combobox-trigger-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-combobox-trigger-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-combobox-trigger-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-combobox-trigger-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] hover:bg-[var(--zui-combobox-trigger-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))]",
  aqua: "border border-[color:var(--zui-combobox-trigger-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-combobox-trigger-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-combobox-trigger-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-combobox-trigger-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] hover:bg-[var(--zui-combobox-trigger-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))]",
  plum: "border border-[color:var(--zui-combobox-trigger-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-combobox-trigger-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-combobox-trigger-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-combobox-trigger-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] hover:bg-[var(--zui-combobox-trigger-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-trigger-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))]",
} as const;

export const zuiComboboxSizes = {
  sm: "px-2 py-1 text-sm",
  md: "px-3 py-2",
  lg: "px-4 py-3 text-lg",
} as const;

export const zuiComboboxItemBase =
  "cursor-pointer px-3 py-2 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-combobox-item-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[var(--zui-combobox-item-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))] focus-visible:ring-inset";

export const zuiComboboxItemAppearances = {
  default:
    "bg-[var(--zui-combobox-item-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-combobox-item-default-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-combobox-item-default-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-combobox-item-default-fg-dark,var(--zui-fg-dark,oklch(92.8%_0.006_264.531)))] data-[selected=true]:bg-[var(--zui-combobox-item-default-selected-bg,var(--zui-surface-hover,oklch(92.8%_0.006_264.531)))] dark:data-[selected=true]:bg-[var(--zui-combobox-item-default-selected-bg-dark,var(--zui-surface-hover-dark,oklch(27%_0.006_264.531)))] data-[selected=true]:text-[color:var(--zui-combobox-item-default-selected-fg,var(--zui-fg,oklch(37.3%_0.034_259.733)))] dark:data-[selected=true]:text-[color:var(--zui-combobox-item-default-selected-fg-dark,var(--zui-fg-dark,oklch(92.8%_0.006_264.531)))]",
  glass:
    "bg-[var(--zui-combobox-item-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-combobox-item-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-combobox-item-glass-fg,var(--zui-fg,oklch(37.3%_0.034_259.733)))] dark:text-[color:var(--zui-combobox-item-glass-fg-dark,var(--zui-fg-dark,oklch(92.8%_0.006_264.531)))]",
  outline:
    "border-2 border-[color:var(--zui-combobox-item-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-combobox-item-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] text-[color:var(--zui-combobox-item-outline-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-combobox-item-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  ghost:
    "border-[color:var(--zui-combobox-item-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-combobox-item-ghost-border-dark,var(--zui-border-dark,transparent))] text-[color:var(--zui-combobox-item-ghost-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-combobox-item-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  sky: "text-[color:var(--zui-combobox-item-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:text-[color:var(--zui-combobox-item-sky-fg-dark,var(--zui-color-sky-dark,oklch(90.1%_0.058_230.902)))] hover:bg-[var(--zui-combobox-item-sky-bg-hover,color-mix(in oklch, var(--zui-color-sky,oklch(90.1%_0.058_230.902)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-sky-bg-hover-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(28%_0.04_232)) 18%, transparent))]",
  rose: "text-[color:var(--zui-combobox-item-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-combobox-item-rose-fg-dark,var(--zui-color-rose-dark,oklch(89.2%_0.058_10.001)))] hover:bg-[var(--zui-combobox-item-rose-bg-hover,color-mix(in oklch, var(--zui-color-rose,oklch(89.2%_0.058_10.001)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-rose-bg-hover-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(27%_0.05_10)) 18%, transparent))]",
  purple:
    "text-[color:var(--zui-combobox-item-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-combobox-item-purple-fg-dark,var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)))] hover:bg-[var(--zui-combobox-item-purple-bg-hover,color-mix(in oklch, var(--zui-color-purple,oklch(90.2%_0.063_306.703)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-purple-bg-hover-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(26%_0.06_304)) 18%, transparent))]",
  pink: "text-[color:var(--zui-combobox-item-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-combobox-item-pink-fg-dark,var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)))] hover:bg-[var(--zui-combobox-item-pink-bg-hover,color-mix(in oklch, var(--zui-color-pink,oklch(89.9%_0.061_343.231)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-pink-bg-hover-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(27%_0.05_343)) 18%, transparent))]",
  orange:
    "text-[color:var(--zui-combobox-item-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-combobox-item-orange-fg-dark,var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)))] hover:bg-[var(--zui-combobox-item-orange-bg-hover,color-mix(in oklch, var(--zui-color-orange,oklch(90.1%_0.076_70.697)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-orange-bg-hover-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(27%_0.04_38)) 18%, transparent))]",
  yellow:
    "text-[color:var(--zui-combobox-item-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-combobox-item-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)))] hover:bg-[var(--zui-combobox-item-yellow-bg-hover,color-mix(in oklch, var(--zui-color-yellow,oklch(94.5%_0.129_101.54)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-yellow-bg-hover-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28%_0.05_58)) 18%, transparent))]",
  teal: "text-[color:var(--zui-combobox-item-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-combobox-item-teal-fg-dark,var(--zui-color-teal-dark,oklch(91%_0.096_180.426)))] hover:bg-[var(--zui-combobox-item-teal-bg-hover,color-mix(in oklch, var(--zui-color-teal,oklch(91%_0.096_180.426)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-teal-bg-hover-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(26%_0.04_188)) 18%, transparent))]",
  indigo:
    "text-[color:var(--zui-combobox-item-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-combobox-item-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)))] hover:bg-[var(--zui-combobox-item-indigo-bg-hover,color-mix(in oklch, var(--zui-color-indigo,oklch(87%_0.065_274.039)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-indigo-bg-hover-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25%_0.06_278)) 18%, transparent))]",
  emerald:
    "text-[color:var(--zui-combobox-item-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-combobox-item-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(90.5%_0.093_164.15)))] hover:bg-[var(--zui-combobox-item-emerald-bg-hover,color-mix(in oklch, var(--zui-color-emerald,oklch(90.5%_0.093_164.15)) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-emerald-bg-hover-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(26%_0.04_167)) 18%, transparent))]",
  blue: "hover:bg-[var(--zui-combobox-item-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb18) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f62e) 18%, transparent))] hover:text-[color:var(--zui-combobox-item-blue-fg-hover,var(--zui-color-blue,#2563eb))] dark:hover:text-[color:var(--zui-combobox-item-blue-fg-hover-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-combobox-item-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb10) 10%, transparent))] dark:bg-[var(--zui-combobox-item-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f61f) 18%, transparent))] text-[color:var(--zui-combobox-item-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-combobox-item-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "hover:bg-[var(--zui-combobox-item-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b218) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee2e) 18%, transparent))] hover:text-[color:var(--zui-combobox-item-cyan-fg-hover,var(--zui-color-cyan,#0891b2))] dark:hover:text-[color:var(--zui-combobox-item-cyan-fg-hover-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-combobox-item-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b210) 10%, transparent))] dark:bg-[var(--zui-combobox-item-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee1f) 18%, transparent))] text-[color:var(--zui-combobox-item-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-combobox-item-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "hover:bg-[var(--zui-combobox-item-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a18) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e2e) 18%, transparent))] hover:text-[color:var(--zui-combobox-item-green-fg-hover,var(--zui-color-green,#16a34a))] dark:hover:text-[color:var(--zui-combobox-item-green-fg-hover-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-combobox-item-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a10) 10%, transparent))] dark:bg-[var(--zui-combobox-item-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e1f) 18%, transparent))] text-[color:var(--zui-combobox-item-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-combobox-item-green-fg-dark,var(--zui-color-green-dark,#22c55e))]",
  lavender:
    "hover:bg-[var(--zui-combobox-item-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf618) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa2e) 18%, transparent))] hover:text-[color:var(--zui-combobox-item-lavender-fg-hover,var(--zui-color-lavender,#8b5cf6))] dark:hover:text-[color:var(--zui-combobox-item-lavender-fg-hover-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-combobox-item-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf610) 10%, transparent))] dark:bg-[var(--zui-combobox-item-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa1f) 18%, transparent))] text-[color:var(--zui-combobox-item-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-combobox-item-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  red: "hover:bg-[var(--zui-combobox-item-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262618) 10%, transparent))] dark:hover:bg-[var(--zui-combobox-item-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44442e) 18%, transparent))] hover:text-[color:var(--zui-combobox-item-red-fg-hover,var(--zui-color-red,#dc2626))] dark:hover:text-[color:var(--zui-combobox-item-red-fg-hover-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-combobox-item-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262610) 10%, transparent))] dark:bg-[var(--zui-combobox-item-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44441f) 18%, transparent))] text-[color:var(--zui-combobox-item-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-combobox-item-red-fg-dark,var(--zui-color-red-dark,#ef4444))]",
} as const;

export const zuiComboboxDisabled = {
  true: "opacity-50 cursor-not-allowed",
} as const;

export const zuiComboboxContentBase =
  "absolute z-10 mt-2 w-full rounded-md border border-[color:var(--zui-combobox-content-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-combobox-content-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-combobox-content-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-combobox-content-bg-dark,var(--zui-surface-muted-dark,#000000))] shadow-[var(--zui-combobox-content-shadow,var(--zui-shadow,0_4px_12px_rgba(15,23,42,0.12)))] dark:shadow-[var(--zui-combobox-content-shadow-dark,var(--zui-shadow-dark,0_12px_32px_rgba(15,23,42,0.45)))] overflow-hidden";

export const zuiComboboxContentAppearances = {
  default:
    "bg-[var(--zui-combobox-content-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-combobox-content-default-bg-dark,var(--zui-surface-muted-dark,#000000))] shadow-[var(--zui-combobox-content-default-shadow,var(--zui-shadow,0_4px_12px_rgba(15,23,42,0.12)))] dark:shadow-[var(--zui-combobox-content-default-shadow-dark,var(--zui-shadow-dark,0_12px_32px_rgba(15,23,42,0.45)))]",
  glass:
    "bg-[var(--zui-combobox-content-glass-bg,var(--zui-surface-muted,#0000001a))] dark:bg-[var(--zui-combobox-content-glass-bg-dark,var(--zui-surface-muted-dark,#ffffff1a))] backdrop-blur-md",
  outline:
    "border-2 border-[color:var(--zui-combobox-content-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-combobox-content-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))]",
  ghost:
    "border-[color:var(--zui-combobox-content-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-combobox-content-ghost-border-dark,var(--zui-border-dark,transparent))]",
  sky: "border-[color:var(--zui-combobox-content-sky-border,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:border-[color:var(--zui-combobox-content-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))]",
  rose: "border-[color:var(--zui-combobox-content-rose-border,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:border-[color:var(--zui-combobox-content-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))]",
  purple:
    "border-[color:var(--zui-combobox-content-purple-border,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:border-[color:var(--zui-combobox-content-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  pink: "border-[color:var(--zui-combobox-content-pink-border,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:border-[color:var(--zui-combobox-content-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  orange:
    "border-[color:var(--zui-combobox-content-orange-border,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:border-[color:var(--zui-combobox-content-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))]",
  yellow:
    "border-[color:var(--zui-combobox-content-yellow-border,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:border-[color:var(--zui-combobox-content-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))]",
  teal: "border-[color:var(--zui-combobox-content-teal-border,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:border-[color:var(--zui-combobox-content-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))]",
  indigo:
    "border-[color:var(--zui-combobox-content-indigo-border,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:border-[color:var(--zui-combobox-content-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))]",
  emerald:
    "border-[color:var(--zui-combobox-content-emerald-border,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:border-[color:var(--zui-combobox-content-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))]",
  blue: "border border-[color:var(--zui-combobox-content-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-combobox-content-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-combobox-content-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:bg-[var(--zui-combobox-content-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))]",
  red: "border border-[color:var(--zui-combobox-content-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-combobox-content-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-combobox-content-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:bg-[var(--zui-combobox-content-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))]",
} as const;

export const zuiComboboxSpacing = {
  none: "space-y-0",
  default: "space-y-1",
  sm: "space-y-2",
  md: "space-y-3",
  lg: "space-y-4",
  xl: "space-y-5",
} as const;

export const zuiComboboxSearchRowBase =
  "flex items-center gap-2 border-b px-3 py-2 border-[color:var(--zui-combobox-search-border,var(--zui-border,oklch(87.2%_0.01_258.338)))] dark:border-[color:var(--zui-combobox-search-border-dark,var(--zui-border-dark,oklch(27%_0.006_264.531)))]";

export const zuiComboboxSearchInputBase =
  "w-full bg-transparent text-sm outline-none placeholder:text-[color:var(--zui-combobox-search-placeholder,var(--zui-fg-muted,oklch(55.1%_0.027_264.364)))] dark:placeholder:text-[color:var(--zui-combobox-search-placeholder-dark,var(--zui-fg-muted-dark,oklch(55.1%_0.027_264.364)))] text-[color:var(--zui-combobox-search-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-combobox-search-fg-dark,var(--zui-fg-dark,#ffffff))]";

export const zuiComboboxSearchIconBase =
  "size-4 shrink-0 opacity-50 text-[color:var(--zui-combobox-search-icon,var(--zui-fg,currentColor))]";

export const zuiComboboxListBase =
  "max-h-60 overflow-y-auto py-1 rounded-md border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-1";

export const zuiComboboxListAppearances = {
  default:
    "border-[color:var(--zui-combobox-list-default-border,var(--zui-border,oklch(87.2%_0.01_258.338)))] dark:border-[color:var(--zui-combobox-list-default-border-dark,var(--zui-border-dark,oklch(27%_0.006_264.531)))] focus-visible:ring-[color:var(--zui-combobox-list-default-ring,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-default-ring-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))]",
  glass:
    "border-[color:var(--zui-combobox-list-glass-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-combobox-list-glass-border-dark,var(--zui-border-dark,#ffffff1a))] focus-visible:ring-[color:var(--zui-combobox-list-glass-ring,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-glass-ring-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))]",
  outline:
    "border-[color:var(--zui-combobox-list-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-combobox-list-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] focus-visible:ring-[color:var(--zui-combobox-list-outline-ring,var(--zui-focus-ring,oklch(55.1%_0.027_264.364)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-outline-ring-dark,var(--zui-focus-ring-dark,oklch(55.1%_0.027_264.364)))]",
  ghost:
    "border-transparent focus-visible:ring-[color:var(--zui-combobox-list-ghost-ring,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-ghost-ring-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))]",
  sky: "border-[color:var(--zui-combobox-list-sky-border,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:border-[color:var(--zui-combobox-list-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] focus-visible:ring-[color:var(--zui-combobox-list-sky-ring,var(--zui-focus-ring,oklch(39.1%_0.09_240.876)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-sky-ring-dark,var(--zui-focus-ring-dark,oklch(58.8%_0.158_241.966)))]",
  rose: "border-[color:var(--zui-combobox-list-rose-border,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:border-[color:var(--zui-combobox-list-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] focus-visible:ring-[color:var(--zui-combobox-list-rose-ring,var(--zui-focus-ring,oklch(41%_0.159_10.272)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-rose-ring-dark,var(--zui-focus-ring-dark,oklch(58.6%_0.253_17.585)))]",
  purple:
    "border-[color:var(--zui-combobox-list-purple-border,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:border-[color:var(--zui-combobox-list-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] focus-visible:ring-[color:var(--zui-combobox-list-purple-ring,var(--zui-focus-ring,oklch(38.1%_0.176_304.987)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-purple-ring-dark,var(--zui-focus-ring-dark,oklch(55.8%_0.288_302.321)))]",
  pink: "border-[color:var(--zui-combobox-list-pink-border,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:border-[color:var(--zui-combobox-list-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] focus-visible:ring-[color:var(--zui-combobox-list-pink-ring,var(--zui-focus-ring,oklch(40.8%_0.153_2.432)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-pink-ring-dark,var(--zui-focus-ring-dark,oklch(59.2%_0.249_0.584)))]",
  orange:
    "border-[color:var(--zui-combobox-list-orange-border,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:border-[color:var(--zui-combobox-list-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] focus-visible:ring-[color:var(--zui-combobox-list-orange-ring,var(--zui-focus-ring,oklch(40.8%_0.123_38.172)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-orange-ring-dark,var(--zui-focus-ring-dark,oklch(64.6%_0.222_41.116)))]",
  yellow:
    "border-[color:var(--zui-combobox-list-yellow-border,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:border-[color:var(--zui-combobox-list-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] focus-visible:ring-[color:var(--zui-combobox-list-yellow-ring,var(--zui-focus-ring,oklch(42.1%_0.095_57.708)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-yellow-ring-dark,var(--zui-focus-ring-dark,oklch(68.1%_0.162_75.834)))]",
  teal: "border-[color:var(--zui-combobox-list-teal-border,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:border-[color:var(--zui-combobox-list-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] focus-visible:ring-[color:var(--zui-combobox-list-teal-ring,var(--zui-focus-ring,oklch(38.6%_0.063_188.416)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-teal-ring-dark,var(--zui-focus-ring-dark,oklch(60%_0.118_184.704)))]",
  indigo:
    "border-[color:var(--zui-combobox-list-indigo-border,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:border-[color:var(--zui-combobox-list-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] focus-visible:ring-[color:var(--zui-combobox-list-indigo-ring,var(--zui-focus-ring,oklch(35.9%_0.144_278.697)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-indigo-ring-dark,var(--zui-focus-ring-dark,oklch(51.1%_0.262_276.966)))]",
  emerald:
    "border-[color:var(--zui-combobox-list-emerald-border,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:border-[color:var(--zui-combobox-list-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] focus-visible:ring-[color:var(--zui-combobox-list-emerald-ring,var(--zui-focus-ring,oklch(37.8%_0.077_168.94)))] dark:focus-visible:ring-[color:var(--zui-combobox-list-emerald-ring-dark,var(--zui-focus-ring-dark,oklch(59.6%_0.145_163.225)))]",
  blue: "border-[color:var(--zui-combobox-list-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-combobox-list-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] focus-visible:ring-[color:var(--zui-combobox-list-blue-ring,var(--zui-focus-ring,#2563eb))] dark:focus-visible:ring-[color:var(--zui-combobox-list-blue-ring-dark,var(--zui-focus-ring-dark,#3b82f6))]",
  red: "border-[color:var(--zui-combobox-list-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-combobox-list-red-border-dark,var(--zui-color-red-dark,#ef4444))] focus-visible:ring-[color:var(--zui-combobox-list-red-ring,var(--zui-focus-ring,#dc2626))] dark:focus-visible:ring-[color:var(--zui-combobox-list-red-ring-dark,var(--zui-focus-ring-dark,#ef4444))]",
} as const;

export const zuiComboboxEmptyBase =
  "px-3 py-6 text-center text-sm text-[color:var(--zui-combobox-empty-fg,var(--zui-fg-muted,oklch(55.1%_0.027_264.364)))] dark:text-[color:var(--zui-combobox-empty-fg-dark,var(--zui-fg-muted-dark,oklch(55.1%_0.027_264.364)))]";
