export const zuiCommandOverlayBase =
  "fixed inset-0 z-9999 bg-[var(--zui-command-overlay-bg,var(--zui-fg,oklch(12.9%_0.042_264.695_/_0.6)))] dark:bg-[var(--zui-command-overlay-bg-dark,var(--zui-fg-dark,oklch(12.9%_0.042_264.695_/_0.6)))] backdrop-blur-sm";

export const zuiCommandTriggerBase =
  "relative inline-flex shrink-0 cursor-pointer items-center gap-2 rounded-md border border-[color:var(--zui-command-trigger-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-command-trigger-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-command-trigger-bg,var(--zui-surface-soft,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-command-trigger-bg-dark,var(--zui-surface-soft-dark,oklch(12.9%_0.042_264.695)))] px-3 py-2 text-sm text-[color:var(--zui-command-trigger-fg,var(--zui-fg,oklch(44.6%_0.03_256.802)))] dark:text-[color:var(--zui-command-trigger-fg-dark,var(--zui-fg-dark,oklch(86.9%_0.022_252.894)))] transition hover:bg-[var(--zui-command-trigger-bg-hover,var(--zui-surface-hover,#0000000d))] dark:hover:bg-[var(--zui-command-trigger-bg-hover-dark,var(--zui-surface-hover-dark,#ffffff0d))] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-command-trigger-ring-focus,var(--zui-focus-ring,#06b6d466))] dark:focus-visible:ring-[var(--zui-command-trigger-ring-focus-dark,var(--zui-focus-ring-dark,#22d3ee66))]";

export const zuiCommandContentBase =
  "fixed left-1/2 top-[15%] z-9999 w-[calc(100%-2rem)] -translate-x-1/2 overflow-hidden rounded-xl border border-[color:var(--zui-command-content-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-command-content-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-command-content-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-command-content-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] text-[color:var(--zui-command-content-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-command-content-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] shadow-[var(--zui-command-content-shadow,var(--zui-shadow,0_12px_40px_rgba(15,23,42,0.18)))] dark:shadow-[var(--zui-command-content-shadow-dark,var(--zui-shadow-dark,0_24px_80px_rgba(15,23,42,0.6)))] focus:outline-none";

export const zuiCommandContentSizes = {
  sm: "max-w-md",
  md: "max-w-lg",
  lg: "max-w-2xl",
} as const;

export const zuiCommandInputRowBase =
  "flex items-center gap-2 border-b border-[color:var(--zui-command-input-border,var(--zui-border,#0000000f))] dark:border-[color:var(--zui-command-input-border-dark,var(--zui-border-dark,#ffffff14))] px-4";

export const zuiCommandInputBase =
  "h-12 w-full bg-transparent text-sm text-[color:var(--zui-command-input-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-command-input-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] placeholder:text-[color:var(--zui-command-input-placeholder,var(--zui-fg-muted,oklch(55.1%_0.027_264.364)))] dark:placeholder:text-[color:var(--zui-command-input-placeholder-dark,var(--zui-fg-muted-dark,oklch(55.1%_0.027_264.364)))] focus:outline-none";

export const zuiCommandListBase =
  "max-h-[min(60vh,420px)] overflow-y-auto overscroll-contain p-2";

export const zuiCommandGroupHeadingBase =
  "px-2 pb-1 pt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[color:var(--zui-command-group-heading-fg,var(--zui-fg-muted,oklch(55.1%_0.027_264.364)))] dark:text-[color:var(--zui-command-group-heading-fg-dark,var(--zui-fg-muted-dark,oklch(70.7%_0.022_261.325)))]";

export const zuiCommandItemBase =
  "flex cursor-pointer items-center gap-3 rounded-lg px-3 py-2 text-sm text-[color:var(--zui-command-item-fg,var(--zui-fg,oklch(27.8%_0.033_256.848)))] dark:text-[color:var(--zui-command-item-fg-dark,var(--zui-fg-dark,oklch(86.9%_0.022_252.894)))] transition-colors data-[active=true]:bg-[var(--zui-command-item-active-bg,var(--zui-surface-hover,oklch(95.1%_0.026_236.824)))] dark:data-[active=true]:bg-[var(--zui-command-item-active-bg-dark,var(--zui-surface-hover-dark,oklch(28.2%_0.091_267.935_/_0.55)))] data-[active=true]:text-[color:var(--zui-command-item-active-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[active=true]:text-[color:var(--zui-command-item-active-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] aria-disabled:cursor-not-allowed aria-disabled:opacity-50";

export const zuiCommandSeparatorBase =
  "my-1 h-px bg-[var(--zui-command-separator-bg,var(--zui-border,#0000000f))] dark:bg-[var(--zui-command-separator-bg-dark,var(--zui-border-dark,#ffffff14))]";

export const zuiCommandEmptyBase =
  "px-3 py-8 text-center text-sm text-[color:var(--zui-command-empty-fg,var(--zui-fg-muted,oklch(55.1%_0.027_264.364)))] dark:text-[color:var(--zui-command-empty-fg-dark,var(--zui-fg-muted-dark,oklch(70.7%_0.022_261.325)))]";

export const zuiCommandFooterBase =
  "flex items-center gap-3 border-t border-[color:var(--zui-command-footer-border,var(--zui-border,#0000000f))] dark:border-[color:var(--zui-command-footer-border-dark,var(--zui-border-dark,#ffffff14))] px-4 py-2 text-xs text-[color:var(--zui-command-footer-fg,var(--zui-fg-muted,oklch(55.1%_0.027_264.364)))] dark:text-[color:var(--zui-command-footer-fg-dark,var(--zui-fg-muted-dark,oklch(70.7%_0.022_261.325)))]";

export const zuiCommandContentAppearances = {
  default:
    "bg-[var(--zui-command-content-default-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-command-content-default-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))]",
  glass:
    "border-[color:var(--zui-command-content-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-command-content-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-command-content-glass-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858_/_0.7)))] dark:bg-[var(--zui-command-content-glass-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695_/_0.7)))] backdrop-blur-xl",
  sky: "border-[color:var(--zui-command-content-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-command-content-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] bg-[var(--zui-command-content-sky-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-sky-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  rose: "border-[color:var(--zui-command-content-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-command-content-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] bg-[var(--zui-command-content-rose-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-rose-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  purple:
    "border-[color:var(--zui-command-content-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-command-content-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-command-content-purple-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-purple-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  pink: "border-[color:var(--zui-command-content-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-command-content-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-command-content-pink-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-pink-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  orange:
    "border-[color:var(--zui-command-content-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-command-content-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-command-content-orange-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-orange-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  yellow:
    "border-[color:var(--zui-command-content-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-command-content-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-command-content-yellow-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-yellow-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  teal: "border-[color:var(--zui-command-content-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-command-content-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-command-content-teal-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-teal-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  indigo:
    "border-[color:var(--zui-command-content-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-command-content-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-command-content-indigo-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-indigo-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  emerald:
    "border-[color:var(--zui-command-content-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-command-content-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] bg-[var(--zui-command-content-emerald-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-emerald-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  gray: "border-[color:var(--zui-command-content-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-command-content-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] bg-[var(--zui-command-content-gray-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-gray-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  amber:
    "border-[color:var(--zui-command-content-amber-border,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:border-[color:var(--zui-command-content-amber-border-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] bg-[var(--zui-command-content-amber-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-amber-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  violet:
    "border-[color:var(--zui-command-content-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-command-content-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-command-content-violet-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-violet-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  "gradient-blue":
    "border-[color:var(--zui-command-content-gradient-blue-border,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:border-[color:var(--zui-command-content-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] bg-linear-to-br from-[var(--zui-command-content-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:from-[var(--zui-command-content-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(28.2%_0.091_267.935_/_0.85)))] to-[var(--zui-command-content-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-command-content-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.85)))] backdrop-blur-xl",
  "gradient-green":
    "border-[color:var(--zui-command-content-gradient-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:border-[color:var(--zui-command-content-gradient-green-border-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] bg-linear-to-br from-[var(--zui-command-content-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:from-[var(--zui-command-content-gradient-green-from-dark,var(--zui-color-green-dark,oklch(26.6%_0.065_152.934_/_0.85)))] to-[var(--zui-command-content-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:to-[var(--zui-command-content-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(27.4%_0.072_132.109_/_0.85)))] backdrop-blur-xl",
  "gradient-red":
    "border-[color:var(--zui-command-content-gradient-red-border,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:border-[color:var(--zui-command-content-gradient-red-border-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] bg-linear-to-br from-[var(--zui-command-content-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:from-[var(--zui-command-content-gradient-red-from-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.85)))] to-[var(--zui-command-content-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-command-content-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.85)))] backdrop-blur-xl",
  "gradient-yellow":
    "border-[color:var(--zui-command-content-gradient-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-command-content-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-linear-to-br from-[var(--zui-command-content-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:from-[var(--zui-command-content-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.85)))] to-[var(--zui-command-content-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:to-[var(--zui-command-content-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.85)))] backdrop-blur-xl",
  "gradient-purple":
    "border-[color:var(--zui-command-content-gradient-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-command-content-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-linear-to-br from-[var(--zui-command-content-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:from-[var(--zui-command-content-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.85)))] to-[var(--zui-command-content-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-command-content-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.85)))] backdrop-blur-xl",
  "gradient-teal":
    "border-[color:var(--zui-command-content-gradient-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-command-content-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-linear-to-br from-[var(--zui-command-content-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:from-[var(--zui-command-content-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.85)))] to-[var(--zui-command-content-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:to-[var(--zui-command-content-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(30.2%_0.056_229.695_/_0.85)))] backdrop-blur-xl",
  "gradient-indigo":
    "border-[color:var(--zui-command-content-gradient-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-command-content-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-linear-to-br from-[var(--zui-command-content-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:from-[var(--zui-command-content-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.85)))] to-[var(--zui-command-content-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-command-content-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.85)))] backdrop-blur-xl",
  "gradient-pink":
    "border-[color:var(--zui-command-content-gradient-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-command-content-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-linear-to-br from-[var(--zui-command-content-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:from-[var(--zui-command-content-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.85)))] to-[var(--zui-command-content-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:to-[var(--zui-command-content-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.85)))] backdrop-blur-xl",
  blue: "border border-[color:var(--zui-command-content-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-command-content-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-command-content-blue-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-blue-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  cyan: "border border-[color:var(--zui-command-content-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-command-content-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-command-content-cyan-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-cyan-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  green:
    "border border-[color:var(--zui-command-content-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-command-content-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-command-content-green-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-green-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  lime: "border border-[color:var(--zui-command-content-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-command-content-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-command-content-lime-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-lime-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  mint: "border border-[color:var(--zui-command-content-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-command-content-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-command-content-mint-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-mint-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  ocean:
    "border border-[color:var(--zui-command-content-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-command-content-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-command-content-ocean-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-ocean-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  sapphire:
    "border border-[color:var(--zui-command-content-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-command-content-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-command-content-sapphire-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-sapphire-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  lavender:
    "border border-[color:var(--zui-command-content-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-command-content-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-command-content-lavender-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-lavender-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  ruby: "border border-[color:var(--zui-command-content-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-command-content-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-command-content-ruby-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-ruby-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  red: "border border-[color:var(--zui-command-content-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-command-content-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-command-content-red-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-red-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  slate:
    "border border-[color:var(--zui-command-content-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-command-content-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-command-content-slate-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-slate-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  zinc: "border border-[color:var(--zui-command-content-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-command-content-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-command-content-zinc-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-zinc-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  stone:
    "border border-[color:var(--zui-command-content-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-command-content-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-command-content-stone-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-stone-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  royal:
    "border border-[color:var(--zui-command-content-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-command-content-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-command-content-royal-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-royal-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  electric:
    "border border-[color:var(--zui-command-content-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-command-content-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-command-content-electric-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-electric-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  forest:
    "border border-[color:var(--zui-command-content-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-command-content-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-command-content-forest-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-forest-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  sunset:
    "border border-[color:var(--zui-command-content-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-command-content-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-command-content-sunset-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-sunset-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  magenta:
    "border border-[color:var(--zui-command-content-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-command-content-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-command-content-magenta-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-magenta-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  crimson:
    "border border-[color:var(--zui-command-content-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-command-content-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-command-content-crimson-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-crimson-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  aqua: "border border-[color:var(--zui-command-content-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-command-content-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-command-content-aqua-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-aqua-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
  plum: "border border-[color:var(--zui-command-content-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-command-content-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-command-content-plum-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-command-content-plum-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] backdrop-blur-xl",
} as const;
