export const zuiCopyButtonBase = [
  "relative inline-flex items-center justify-center gap-2 whitespace-nowrap",
  "rounded-[var(--zui-copy-button-radius,var(--zui-radius,0.75rem))] font-medium",
  "ring-offset-[var(--zui-copy-button-ring-offset,var(--zui-ring-offset,#f8fafc))] dark:ring-offset-[var(--zui-copy-button-ring-offset-dark,var(--zui-ring-offset-dark,#020617))]",
  "transition-colors select-none",
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-copy-button-focus-ring,var(--zui-focus-ring,#475569))] dark:focus-visible:ring-[var(--zui-copy-button-focus-ring-dark,var(--zui-focus-ring-dark,#cbd5e1))] focus-visible:ring-offset-2",
  "disabled:pointer-events-none disabled:opacity-50",
] as const;

export const zuiCopyButtonAppearances = {
  default:
    "bg-[var(--zui-copy-button-default-bg,var(--zui-brand,#0f172a))] dark:bg-[var(--zui-copy-button-default-bg-dark,var(--zui-brand-dark,#f8fafc))] text-[color:var(--zui-copy-button-default-fg,var(--zui-brand-fg,#f8fafc))] dark:text-[color:var(--zui-copy-button-default-fg-dark,var(--zui-brand-fg-dark,#020617))] shadow-[var(--zui-copy-button-default-shadow,var(--zui-shadow,0_1px_2px_#0f172a14))] dark:shadow-[var(--zui-copy-button-default-shadow-dark,var(--zui-shadow-dark,0_1px_2px_#0f172a1f))] hover:bg-[var(--zui-copy-button-default-bg-hover,var(--zui-brand-hover,#000000))] dark:hover:bg-[var(--zui-copy-button-default-bg-hover-dark,var(--zui-brand-hover-dark,#ffffff))]",
  secondary:
    "bg-[var(--zui-copy-button-secondary-bg,var(--zui-surface-soft,#e2e8f0))] dark:bg-[var(--zui-copy-button-secondary-bg-dark,var(--zui-surface-soft-dark,#1e293b))] text-[color:var(--zui-copy-button-secondary-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-copy-button-secondary-fg-dark,var(--zui-fg-dark,#f8fafc))] hover:bg-[var(--zui-copy-button-secondary-bg-hover,var(--zui-surface-hover,#cbd5e1))] dark:hover:bg-[var(--zui-copy-button-secondary-bg-hover-dark,var(--zui-surface-hover-dark,#334155))]",
  destructive:
    "bg-[var(--zui-copy-button-destructive-bg,var(--zui-status-error,#f43f5e))] dark:bg-[var(--zui-copy-button-destructive-bg-dark,var(--zui-status-error-dark,#be123c))] text-[color:var(--zui-copy-button-destructive-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-destructive-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-destructive-bg-hover,var(--zui-status-error,#f43f5e))] dark:hover:bg-[var(--zui-copy-button-destructive-bg-hover-dark,var(--zui-status-error-dark,#9f1239))]",
  outline:
    "border border-[color:var(--zui-copy-button-outline-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-copy-button-outline-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-copy-button-outline-bg,var(--zui-surface-soft,#0000000d))] dark:bg-[var(--zui-copy-button-outline-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] text-[color:var(--zui-copy-button-outline-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-copy-button-outline-fg-dark,var(--zui-fg-dark,#f8fafc))] hover:bg-[var(--zui-copy-button-outline-bg-hover,var(--zui-surface-hover,#0000001a))] dark:hover:bg-[var(--zui-copy-button-outline-bg-hover-dark,var(--zui-surface-hover-dark,#ffffff1a))]",
  ghost:
    "bg-transparent text-[color:var(--zui-copy-button-ghost-fg,var(--zui-fg,#334155))] dark:text-[color:var(--zui-copy-button-ghost-fg-dark,var(--zui-fg-dark,#e2e8f0))] hover:bg-[var(--zui-copy-button-ghost-bg-hover,var(--zui-surface-hover,#0000000d))] dark:hover:bg-[var(--zui-copy-button-ghost-bg-hover-dark,var(--zui-surface-hover-dark,#ffffff0d))]",
  glass:
    "border border-[color:var(--zui-copy-button-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-copy-button-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-copy-button-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-copy-button-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-copy-button-glass-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-copy-button-glass-fg-dark,var(--zui-fg-dark,#ffffff))] backdrop-blur-md hover:bg-[var(--zui-copy-button-glass-bg-hover,var(--zui-surface-hover,#00000026))] dark:hover:bg-[var(--zui-copy-button-glass-bg-hover-dark,var(--zui-surface-hover-dark,#ffffff26))]",
  emerald:
    "bg-[var(--zui-copy-button-emerald-bg,var(--zui-color-emerald,#10b981))] dark:bg-[var(--zui-copy-button-emerald-bg-dark,var(--zui-color-emerald-dark,#065f46))] text-[color:var(--zui-copy-button-emerald-fg,var(--zui-brand-fg,#064e3b))] dark:text-[color:var(--zui-copy-button-emerald-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-emerald-bg-hover,var(--zui-color-emerald,#10b981))] dark:hover:bg-[var(--zui-copy-button-emerald-bg-hover-dark,var(--zui-color-emerald-dark,#064e3b))]",
  indigo:
    "bg-[var(--zui-copy-button-indigo-bg,var(--zui-color-indigo,#3730a3))] dark:bg-[var(--zui-copy-button-indigo-bg-dark,var(--zui-color-indigo-dark,#4f46e5))] text-[color:var(--zui-copy-button-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-indigo-bg-hover,var(--zui-color-indigo,#3730a3))] dark:hover:bg-[var(--zui-copy-button-indigo-bg-hover-dark,var(--zui-color-indigo-dark,#4f46e5))]",
  purple:
    "bg-[var(--zui-copy-button-purple-bg,var(--zui-color-purple,#6b21a8))] dark:bg-[var(--zui-copy-button-purple-bg-dark,var(--zui-color-purple-dark,#9333ea))] text-[color:var(--zui-copy-button-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-purple-bg-hover,var(--zui-color-purple,#6b21a8))] dark:hover:bg-[var(--zui-copy-button-purple-bg-hover-dark,var(--zui-color-purple-dark,#9333ea))]",
  pink: "bg-[var(--zui-copy-button-pink-bg,var(--zui-color-pink,#9d174d))] dark:bg-[var(--zui-copy-button-pink-bg-dark,var(--zui-color-pink-dark,#db2777))] text-[color:var(--zui-copy-button-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-pink-bg-hover,var(--zui-color-pink,#9d174d))] dark:hover:bg-[var(--zui-copy-button-pink-bg-hover-dark,var(--zui-color-pink-dark,#db2777))]",
  rose: "bg-[var(--zui-copy-button-rose-bg,var(--zui-color-rose,#9f1239))] dark:bg-[var(--zui-copy-button-rose-bg-dark,var(--zui-color-rose-dark,#e11d48))] text-[color:var(--zui-copy-button-rose-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-rose-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-rose-bg-hover,var(--zui-color-rose,#9f1239))] dark:hover:bg-[var(--zui-copy-button-rose-bg-hover-dark,var(--zui-color-rose-dark,#e11d48))]",
  sky: "bg-[var(--zui-copy-button-sky-bg,var(--zui-color-sky,#0ea5e9))] dark:bg-[var(--zui-copy-button-sky-bg-dark,var(--zui-color-sky-dark,#0369a1))] text-[color:var(--zui-copy-button-sky-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-sky-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-sky-bg-hover,var(--zui-color-sky,#0ea5e9))] dark:hover:bg-[var(--zui-copy-button-sky-bg-hover-dark,var(--zui-color-sky-dark,#075985))]",
  teal: "bg-[var(--zui-copy-button-teal-bg,var(--zui-color-teal,#14b8a6))] dark:bg-[var(--zui-copy-button-teal-bg-dark,var(--zui-color-teal-dark,#0f766e))] text-[color:var(--zui-copy-button-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-teal-bg-hover,var(--zui-color-teal,#14b8a6))] dark:hover:bg-[var(--zui-copy-button-teal-bg-hover-dark,var(--zui-color-teal-dark,#115e59))]",
  yellow:
    "bg-[var(--zui-copy-button-yellow-bg,var(--zui-color-yellow,#eab308))] dark:bg-[var(--zui-copy-button-yellow-bg-dark,var(--zui-color-yellow-dark,#854d0e))] text-[color:var(--zui-copy-button-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-yellow-bg-hover,var(--zui-color-yellow,#eab308))] dark:hover:bg-[var(--zui-copy-button-yellow-bg-hover-dark,var(--zui-color-yellow-dark,#713f12))]",
  orange:
    "bg-[var(--zui-copy-button-orange-bg,var(--zui-color-orange,#f97316))] dark:bg-[var(--zui-copy-button-orange-bg-dark,var(--zui-color-orange-dark,#9a3412))] text-[color:var(--zui-copy-button-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-orange-bg-hover,var(--zui-color-orange,#f97316))] dark:hover:bg-[var(--zui-copy-button-orange-bg-hover-dark,var(--zui-color-orange-dark,#7c2d12))]",
  gray: "bg-[var(--zui-copy-button-gray-bg,var(--zui-color-gray,#6b7280))] dark:bg-[var(--zui-copy-button-gray-bg-dark,var(--zui-color-gray-dark,#374151))] text-[color:var(--zui-copy-button-gray-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gray-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-gray-bg-hover,var(--zui-color-gray,#6b7280))] dark:hover:bg-[var(--zui-copy-button-gray-bg-hover-dark,var(--zui-color-gray-dark,#1f2937))]",
  amber:
    "bg-[var(--zui-copy-button-amber-bg,var(--zui-color-amber,#f59e0b))] dark:bg-[var(--zui-copy-button-amber-bg-dark,var(--zui-color-amber-dark,#92400e))] text-[color:var(--zui-copy-button-amber-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-amber-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-amber-bg-hover,var(--zui-color-amber,#f59e0b))] dark:hover:bg-[var(--zui-copy-button-amber-bg-hover-dark,var(--zui-color-amber-dark,#78350f))]",
  violet:
    "bg-[var(--zui-copy-button-violet-bg,var(--zui-color-violet,#5b21b6))] dark:bg-[var(--zui-copy-button-violet-bg-dark,var(--zui-color-violet-dark,#7c3aed))] text-[color:var(--zui-copy-button-violet-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-violet-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-violet-bg-hover,var(--zui-color-violet,#5b21b6))] dark:hover:bg-[var(--zui-copy-button-violet-bg-hover-dark,var(--zui-color-violet-dark,#7c3aed))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-blue-from,var(--zui-color-blue,#1e40af))] dark:from-[var(--zui-copy-button-gradient-blue-from-dark,var(--zui-color-blue-dark,#2563eb))] to-[var(--zui-copy-button-gradient-blue-to,var(--zui-color-purple,#6b21a8))] dark:to-[var(--zui-copy-button-gradient-blue-to-dark,var(--zui-color-purple-dark,#9333ea))] text-[color:var(--zui-copy-button-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-blue-from-hover,var(--zui-color-blue,#1e40af))] dark:hover:from-[var(--zui-copy-button-gradient-blue-from-hover-dark,var(--zui-color-blue-dark,#2563eb))] hover:to-[var(--zui-copy-button-gradient-blue-to-hover,var(--zui-color-purple,#6b21a8))] dark:hover:to-[var(--zui-copy-button-gradient-blue-to-hover-dark,var(--zui-color-purple-dark,#9333ea))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-green-from,var(--zui-color-green,#166534))] dark:from-[var(--zui-copy-button-gradient-green-from-dark,var(--zui-color-green-dark,#16a34a))] to-[var(--zui-copy-button-gradient-green-to,var(--zui-color-lime,#3f6212))] dark:to-[var(--zui-copy-button-gradient-green-to-dark,var(--zui-color-lime-dark,#65a30d))] text-[color:var(--zui-copy-button-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-green-from-hover,var(--zui-color-green,#166534))] dark:hover:from-[var(--zui-copy-button-gradient-green-from-hover-dark,var(--zui-color-green-dark,#16a34a))] hover:to-[var(--zui-copy-button-gradient-green-to-hover,var(--zui-color-lime,#3f6212))] dark:hover:to-[var(--zui-copy-button-gradient-green-to-hover-dark,var(--zui-color-lime-dark,#65a30d))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-red-from,var(--zui-color-red,#991b1b))] dark:from-[var(--zui-copy-button-gradient-red-from-dark,var(--zui-color-red-dark,#dc2626))] to-[var(--zui-copy-button-gradient-red-to,var(--zui-color-pink,#9d174d))] dark:to-[var(--zui-copy-button-gradient-red-to-dark,var(--zui-color-pink-dark,#db2777))] text-[color:var(--zui-copy-button-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-red-from-hover,var(--zui-color-red,#991b1b))] dark:hover:from-[var(--zui-copy-button-gradient-red-from-hover-dark,var(--zui-color-red-dark,#dc2626))] hover:to-[var(--zui-copy-button-gradient-red-to-hover,var(--zui-color-pink,#9d174d))] dark:hover:to-[var(--zui-copy-button-gradient-red-to-hover-dark,var(--zui-color-pink-dark,#db2777))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-yellow-from,var(--zui-color-yellow,#854d0e))] dark:from-[var(--zui-copy-button-gradient-yellow-from-dark,var(--zui-color-yellow-dark,#ca8a04))] to-[var(--zui-copy-button-gradient-yellow-to,var(--zui-color-orange,#9a3412))] dark:to-[var(--zui-copy-button-gradient-yellow-to-dark,var(--zui-color-orange-dark,#ea580c))] text-[color:var(--zui-copy-button-gradient-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-yellow-from-hover,var(--zui-color-yellow,#854d0e))] dark:hover:from-[var(--zui-copy-button-gradient-yellow-from-hover-dark,var(--zui-color-yellow-dark,#ca8a04))] hover:to-[var(--zui-copy-button-gradient-yellow-to-hover,var(--zui-color-orange,#9a3412))] dark:hover:to-[var(--zui-copy-button-gradient-yellow-to-hover-dark,var(--zui-color-orange-dark,#ea580c))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-purple-from,var(--zui-color-purple,#6b21a8))] dark:from-[var(--zui-copy-button-gradient-purple-from-dark,var(--zui-color-purple-dark,#9333ea))] to-[var(--zui-copy-button-gradient-purple-to,var(--zui-color-pink,#9d174d))] dark:to-[var(--zui-copy-button-gradient-purple-to-dark,var(--zui-color-pink-dark,#db2777))] text-[color:var(--zui-copy-button-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-purple-from-hover,var(--zui-color-purple,#6b21a8))] dark:hover:from-[var(--zui-copy-button-gradient-purple-from-hover-dark,var(--zui-color-purple-dark,#9333ea))] hover:to-[var(--zui-copy-button-gradient-purple-to-hover,var(--zui-color-pink,#9d174d))] dark:hover:to-[var(--zui-copy-button-gradient-purple-to-hover-dark,var(--zui-color-pink-dark,#db2777))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-teal-from,var(--zui-color-teal,#115e59))] dark:from-[var(--zui-copy-button-gradient-teal-from-dark,var(--zui-color-teal-dark,#0d9488))] to-[var(--zui-copy-button-gradient-teal-to,var(--zui-color-cyan,#155e75))] dark:to-[var(--zui-copy-button-gradient-teal-to-dark,var(--zui-color-cyan-dark,#0891b2))] text-[color:var(--zui-copy-button-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-teal-from-hover,var(--zui-color-teal,#115e59))] dark:hover:from-[var(--zui-copy-button-gradient-teal-from-hover-dark,var(--zui-color-teal-dark,#0d9488))] hover:to-[var(--zui-copy-button-gradient-teal-to-hover,var(--zui-color-cyan,#155e75))] dark:hover:to-[var(--zui-copy-button-gradient-teal-to-hover-dark,var(--zui-color-cyan-dark,#0891b2))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-indigo-from,var(--zui-color-indigo,#3730a3))] dark:from-[var(--zui-copy-button-gradient-indigo-from-dark,var(--zui-color-indigo-dark,#4f46e5))] to-[var(--zui-copy-button-gradient-indigo-to,var(--zui-color-purple,#6b21a8))] dark:to-[var(--zui-copy-button-gradient-indigo-to-dark,var(--zui-color-purple-dark,#9333ea))] text-[color:var(--zui-copy-button-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-indigo-from-hover,var(--zui-color-indigo,#3730a3))] dark:hover:from-[var(--zui-copy-button-gradient-indigo-from-hover-dark,var(--zui-color-indigo-dark,#4f46e5))] hover:to-[var(--zui-copy-button-gradient-indigo-to-hover,var(--zui-color-purple,#6b21a8))] dark:hover:to-[var(--zui-copy-button-gradient-indigo-to-hover-dark,var(--zui-color-purple-dark,#9333ea))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-pink-from,var(--zui-color-pink,#9d174d))] dark:from-[var(--zui-copy-button-gradient-pink-from-dark,var(--zui-color-pink-dark,#db2777))] to-[var(--zui-copy-button-gradient-pink-to,var(--zui-color-rose,#9f1239))] dark:to-[var(--zui-copy-button-gradient-pink-to-dark,var(--zui-color-rose-dark,#e11d48))] text-[color:var(--zui-copy-button-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-pink-from-hover,var(--zui-color-pink,#9d174d))] dark:hover:from-[var(--zui-copy-button-gradient-pink-from-hover-dark,var(--zui-color-pink-dark,#db2777))] hover:to-[var(--zui-copy-button-gradient-pink-to-hover,var(--zui-color-rose,#9f1239))] dark:hover:to-[var(--zui-copy-button-gradient-pink-to-hover-dark,var(--zui-color-rose-dark,#e11d48))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-copy-button-gradient-orange-from,var(--zui-color-orange,#9a3412))] dark:from-[var(--zui-copy-button-gradient-orange-from-dark,var(--zui-color-orange-dark,#ea580c))] to-[var(--zui-copy-button-gradient-orange-to,var(--zui-color-red,#991b1b))] dark:to-[var(--zui-copy-button-gradient-orange-to-dark,var(--zui-color-red-dark,#dc2626))] text-[color:var(--zui-copy-button-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:from-[var(--zui-copy-button-gradient-orange-from-hover,var(--zui-color-orange,#9a3412))] dark:hover:from-[var(--zui-copy-button-gradient-orange-from-hover-dark,var(--zui-color-orange-dark,#ea580c))] hover:to-[var(--zui-copy-button-gradient-orange-to-hover,var(--zui-color-red,#991b1b))] dark:hover:to-[var(--zui-copy-button-gradient-orange-to-hover-dark,var(--zui-color-red-dark,#dc2626))]",
  blue: "border border-[color:var(--zui-copy-button-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-copy-button-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-copy-button-blue-bg,var(--zui-color-blue,#2563eb))] dark:bg-[var(--zui-copy-button-blue-bg-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-copy-button-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-blue-bg-hover,var(--zui-color-blue,#2563eb))] dark:hover:bg-[var(--zui-copy-button-blue-bg-hover-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "border border-[color:var(--zui-copy-button-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-copy-button-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-copy-button-cyan-bg,var(--zui-color-cyan,#0891b2))] dark:bg-[var(--zui-copy-button-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-copy-button-cyan-fg,var(--zui-brand-fg,#083344))] dark:text-[color:var(--zui-copy-button-cyan-fg-dark,var(--zui-brand-fg-dark,#083344))] hover:bg-[var(--zui-copy-button-cyan-bg-hover,var(--zui-color-cyan,#0891b2))] dark:hover:bg-[var(--zui-copy-button-cyan-bg-hover-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "border border-[color:var(--zui-copy-button-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-copy-button-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-copy-button-green-bg,var(--zui-color-green,#16a34a))] dark:bg-[var(--zui-copy-button-green-bg-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-copy-button-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-green-bg-hover,var(--zui-color-green,#16a34a))] dark:hover:bg-[var(--zui-copy-button-green-bg-hover-dark,var(--zui-color-green-dark,#22c55e))]",
  lime: "border border-[color:var(--zui-copy-button-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-copy-button-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-copy-button-lime-bg,var(--zui-color-lime,#65a30d))] dark:bg-[var(--zui-copy-button-lime-bg-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-copy-button-lime-fg,var(--zui-brand-fg,#1a2e05))] dark:text-[color:var(--zui-copy-button-lime-fg-dark,var(--zui-brand-fg-dark,#1a2e05))] hover:bg-[var(--zui-copy-button-lime-bg-hover,var(--zui-color-lime,#65a30d))] dark:hover:bg-[var(--zui-copy-button-lime-bg-hover-dark,var(--zui-color-lime-dark,#a3e635))]",
  mint: "border border-[color:var(--zui-copy-button-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-copy-button-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-copy-button-mint-bg,var(--zui-color-mint,#10b981))] dark:bg-[var(--zui-copy-button-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-copy-button-mint-fg,var(--zui-brand-fg,#064e3b))] dark:text-[color:var(--zui-copy-button-mint-fg-dark,var(--zui-brand-fg-dark,#064e3b))] hover:bg-[var(--zui-copy-button-mint-bg-hover,var(--zui-color-mint,#10b981))] dark:hover:bg-[var(--zui-copy-button-mint-bg-hover-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "border border-[color:var(--zui-copy-button-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-copy-button-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-copy-button-ocean-bg,var(--zui-color-ocean,#0284c7))] dark:bg-[var(--zui-copy-button-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-copy-button-ocean-fg,var(--zui-brand-fg,#082f49))] dark:text-[color:var(--zui-copy-button-ocean-fg-dark,var(--zui-brand-fg-dark,#082f49))] hover:bg-[var(--zui-copy-button-ocean-bg-hover,var(--zui-color-ocean,#0284c7))] dark:hover:bg-[var(--zui-copy-button-ocean-bg-hover-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "border border-[color:var(--zui-copy-button-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-copy-button-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-copy-button-sapphire-bg,var(--zui-color-sapphire,#1d4ed8))] dark:bg-[var(--zui-copy-button-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-copy-button-sapphire-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-sapphire-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-sapphire-bg-hover,var(--zui-color-sapphire,#1d4ed8))] dark:hover:bg-[var(--zui-copy-button-sapphire-bg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "border border-[color:var(--zui-copy-button-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-copy-button-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-copy-button-lavender-bg,var(--zui-color-lavender,#8b5cf6))] dark:bg-[var(--zui-copy-button-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-copy-button-lavender-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-lavender-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-lavender-bg-hover,var(--zui-color-lavender,#8b5cf6))] dark:hover:bg-[var(--zui-copy-button-lavender-bg-hover-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "border border-[color:var(--zui-copy-button-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-copy-button-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-copy-button-ruby-bg,var(--zui-color-ruby,#be123c))] dark:bg-[var(--zui-copy-button-ruby-bg-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-copy-button-ruby-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-ruby-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-ruby-bg-hover,var(--zui-color-ruby,#be123c))] dark:hover:bg-[var(--zui-copy-button-ruby-bg-hover-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "border border-[color:var(--zui-copy-button-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-copy-button-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-copy-button-red-bg,var(--zui-color-red,#dc2626))] dark:bg-[var(--zui-copy-button-red-bg-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-copy-button-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-red-bg-hover,var(--zui-color-red,#dc2626))] dark:hover:bg-[var(--zui-copy-button-red-bg-hover-dark,var(--zui-color-red-dark,#ef4444))]",
  slate:
    "border border-[color:var(--zui-copy-button-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-copy-button-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-copy-button-slate-bg,var(--zui-color-slate,#475569))] dark:bg-[var(--zui-copy-button-slate-bg-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-copy-button-slate-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-slate-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-slate-bg-hover,var(--zui-color-slate,#475569))] dark:hover:bg-[var(--zui-copy-button-slate-bg-hover-dark,var(--zui-color-slate-dark,#64748b))]",
  zinc: "border border-[color:var(--zui-copy-button-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-copy-button-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-copy-button-zinc-bg,var(--zui-color-zinc,#52525b))] dark:bg-[var(--zui-copy-button-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-copy-button-zinc-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-zinc-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-zinc-bg-hover,var(--zui-color-zinc,#52525b))] dark:hover:bg-[var(--zui-copy-button-zinc-bg-hover-dark,var(--zui-color-zinc-dark,#71717a))]",
  stone:
    "border border-[color:var(--zui-copy-button-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-copy-button-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-copy-button-stone-bg,var(--zui-color-stone,#57534e))] dark:bg-[var(--zui-copy-button-stone-bg-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-copy-button-stone-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-stone-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-stone-bg-hover,var(--zui-color-stone,#57534e))] dark:hover:bg-[var(--zui-copy-button-stone-bg-hover-dark,var(--zui-color-stone-dark,#78716c))]",
  royal:
    "border border-[color:var(--zui-copy-button-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-copy-button-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-copy-button-royal-bg,var(--zui-color-royal,#4338ca))] dark:bg-[var(--zui-copy-button-royal-bg-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-copy-button-royal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-royal-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-royal-bg-hover,var(--zui-color-royal,#4338ca))] dark:hover:bg-[var(--zui-copy-button-royal-bg-hover-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "border border-[color:var(--zui-copy-button-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-copy-button-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-copy-button-electric-bg,var(--zui-color-electric,#0ea5e9))] dark:bg-[var(--zui-copy-button-electric-bg-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-copy-button-electric-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-electric-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-electric-bg-hover,var(--zui-color-electric,#0ea5e9))] dark:hover:bg-[var(--zui-copy-button-electric-bg-hover-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "border border-[color:var(--zui-copy-button-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-copy-button-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-copy-button-forest-bg,var(--zui-color-forest,#166534))] dark:bg-[var(--zui-copy-button-forest-bg-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-copy-button-forest-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-forest-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-forest-bg-hover,var(--zui-color-forest,#166534))] dark:hover:bg-[var(--zui-copy-button-forest-bg-hover-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "border border-[color:var(--zui-copy-button-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-copy-button-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-copy-button-sunset-bg,var(--zui-color-sunset,#ea580c))] dark:bg-[var(--zui-copy-button-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-copy-button-sunset-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-sunset-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-sunset-bg-hover,var(--zui-color-sunset,#ea580c))] dark:hover:bg-[var(--zui-copy-button-sunset-bg-hover-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "border border-[color:var(--zui-copy-button-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-copy-button-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-copy-button-magenta-bg,var(--zui-color-magenta,#c026d3))] dark:bg-[var(--zui-copy-button-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-copy-button-magenta-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-magenta-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-magenta-bg-hover,var(--zui-color-magenta,#c026d3))] dark:hover:bg-[var(--zui-copy-button-magenta-bg-hover-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "border border-[color:var(--zui-copy-button-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-copy-button-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-copy-button-crimson-bg,var(--zui-color-crimson,#b91c1c))] dark:bg-[var(--zui-copy-button-crimson-bg-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-copy-button-crimson-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-crimson-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-crimson-bg-hover,var(--zui-color-crimson,#b91c1c))] dark:hover:bg-[var(--zui-copy-button-crimson-bg-hover-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "border border-[color:var(--zui-copy-button-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-copy-button-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-copy-button-aqua-bg,var(--zui-color-aqua,#0f766e))] dark:bg-[var(--zui-copy-button-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-copy-button-aqua-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-aqua-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-aqua-bg-hover,var(--zui-color-aqua,#0f766e))] dark:hover:bg-[var(--zui-copy-button-aqua-bg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "border border-[color:var(--zui-copy-button-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-copy-button-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-copy-button-plum-bg,var(--zui-color-plum,#7e22ce))] dark:bg-[var(--zui-copy-button-plum-bg-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-copy-button-plum-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-copy-button-plum-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-copy-button-plum-bg-hover,var(--zui-color-plum,#7e22ce))] dark:hover:bg-[var(--zui-copy-button-plum-bg-hover-dark,var(--zui-color-plum-dark,#c084fc))]",
} as const;

export type ZuiCopyButtonAppearance = keyof typeof zuiCopyButtonAppearances;

export const zuiCopyButtonSizes = {
  sm: "h-8 px-2.5 text-xs [&_svg]:size-3.5",
  md: "h-9 px-3 text-sm [&_svg]:size-4",
  lg: "h-11 px-4 text-base [&_svg]:size-5",
} as const;

export type ZuiCopyButtonSize = keyof typeof zuiCopyButtonSizes;

export const zuiCopyButtonIconOnlySizes = {
  sm: "w-8 px-0",
  md: "w-9 px-0",
  lg: "w-11 px-0",
} as const;
