export const zuiDatePickerTriggerBase = [
  "inline-flex w-full cursor-pointer items-center justify-between gap-2 whitespace-nowrap",
  "rounded-[var(--zui-date-picker-trigger-radius,0.5rem)] border transition-all",
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-date-picker-ring,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[var(--zui-date-picker-ring-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))] focus-visible:ring-offset-2",
  "disabled:cursor-not-allowed disabled:opacity-50",
  "data-[empty=true]:text-[color:var(--zui-date-picker-placeholder-fg,var(--zui-fg-muted,oklch(44.6%_0.043_257.281)))] dark:data-[empty=true]:text-[color:var(--zui-date-picker-placeholder-fg-dark,var(--zui-fg-muted-dark,oklch(86.9%_0.022_252.894)))]",
] as const;

export const zuiDatePickerTriggerSizes = {
  sm: "h-[var(--zui-date-picker-trigger-h-sm,2rem)] px-[var(--zui-date-picker-trigger-px,0.75rem)] text-sm",
  md: "h-[var(--zui-date-picker-trigger-h-md,2.5rem)] px-[var(--zui-date-picker-trigger-px,0.75rem)] text-sm",
  lg: "h-[var(--zui-date-picker-trigger-h-lg,3rem)] px-[var(--zui-date-picker-trigger-px,0.75rem)] text-base",
} as const;

export const zuiDatePickerTriggerAppearances = {
  default:
    "border-[color:var(--zui-date-picker-trigger-default-border,var(--zui-border,oklch(87.2%_0.01_258.338)))] dark:border-[color:var(--zui-date-picker-trigger-default-border-dark,var(--zui-border-dark,oklch(87.2%_0.01_258.338)))] bg-[var(--zui-date-picker-trigger-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-date-picker-trigger-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] text-[color:var(--zui-date-picker-trigger-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-date-picker-trigger-fg-dark,var(--zui-fg-dark,#ffffff))]",
  outline:
    "border-2 border-[color:var(--zui-date-picker-trigger-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-date-picker-trigger-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] text-[color:var(--zui-date-picker-trigger-outline-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-date-picker-trigger-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  ghost:
    "border-[color:var(--zui-date-picker-trigger-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-date-picker-trigger-ghost-border-dark,var(--zui-border-dark,transparent))] text-[color:var(--zui-date-picker-trigger-ghost-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-date-picker-trigger-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))] hover:bg-[var(--zui-date-picker-trigger-ghost-bg-hover,var(--zui-surface-soft,#0000000d))] dark:hover:bg-[var(--zui-date-picker-trigger-ghost-bg-hover-dark,var(--zui-surface-soft-dark,#ffffff0d))]",
  glass:
    "border-[color:var(--zui-date-picker-trigger-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-date-picker-trigger-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-date-picker-trigger-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-date-picker-trigger-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-date-picker-trigger-glass-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-date-picker-trigger-glass-fg-dark,var(--zui-fg-dark,#ffffff))] backdrop-blur-md",
  blue: "border border-[color:var(--zui-date-picker-trigger-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-date-picker-trigger-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-date-picker-trigger-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-date-picker-trigger-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] hover:bg-[var(--zui-date-picker-trigger-blue-bg-hover,color-mix(in_oklch,var(--zui-color-blue,#2563eb)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-blue-bg-hover-dark,color-mix(in_oklch,var(--zui-color-blue-dark,#3b82f6)_14%,transparent))]",
  cyan: "border border-[color:var(--zui-date-picker-trigger-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-date-picker-trigger-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-date-picker-trigger-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-date-picker-trigger-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] hover:bg-[var(--zui-date-picker-trigger-cyan-bg-hover,color-mix(in_oklch,var(--zui-color-cyan,#0891b2)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-cyan-bg-hover-dark,color-mix(in_oklch,var(--zui-color-cyan-dark,#22d3ee)_14%,transparent))]",
  green:
    "border border-[color:var(--zui-date-picker-trigger-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-date-picker-trigger-green-border-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-date-picker-trigger-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-date-picker-trigger-green-fg-dark,var(--zui-color-green-dark,#22c55e))] hover:bg-[var(--zui-date-picker-trigger-green-bg-hover,color-mix(in_oklch,var(--zui-color-green,#16a34a)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-green-bg-hover-dark,color-mix(in_oklch,var(--zui-color-green-dark,#22c55e)_14%,transparent))]",
  lime: "border border-[color:var(--zui-date-picker-trigger-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-date-picker-trigger-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-date-picker-trigger-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-date-picker-trigger-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] hover:bg-[var(--zui-date-picker-trigger-lime-bg-hover,color-mix(in_oklch,var(--zui-color-lime,#65a30d)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-lime-bg-hover-dark,color-mix(in_oklch,var(--zui-color-lime-dark,#a3e635)_14%,transparent))]",
  mint: "border border-[color:var(--zui-date-picker-trigger-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-date-picker-trigger-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-date-picker-trigger-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-date-picker-trigger-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] hover:bg-[var(--zui-date-picker-trigger-mint-bg-hover,color-mix(in_oklch,var(--zui-color-mint,#10b981)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-mint-bg-hover-dark,color-mix(in_oklch,var(--zui-color-mint-dark,#6ee7b7)_14%,transparent))]",
  ocean:
    "border border-[color:var(--zui-date-picker-trigger-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-date-picker-trigger-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-date-picker-trigger-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-date-picker-trigger-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] hover:bg-[var(--zui-date-picker-trigger-ocean-bg-hover,color-mix(in_oklch,var(--zui-color-ocean,#0284c7)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-ocean-bg-hover-dark,color-mix(in_oklch,var(--zui-color-ocean-dark,#38bdf8)_14%,transparent))]",
  sapphire:
    "border border-[color:var(--zui-date-picker-trigger-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-date-picker-trigger-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-date-picker-trigger-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-date-picker-trigger-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] hover:bg-[var(--zui-date-picker-trigger-sapphire-bg-hover,color-mix(in_oklch,var(--zui-color-sapphire,#1d4ed8)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-sapphire-bg-hover-dark,color-mix(in_oklch,var(--zui-color-sapphire-dark,#60a5fa)_14%,transparent))]",
  lavender:
    "border border-[color:var(--zui-date-picker-trigger-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-date-picker-trigger-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-date-picker-trigger-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-date-picker-trigger-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] hover:bg-[var(--zui-date-picker-trigger-lavender-bg-hover,color-mix(in_oklch,var(--zui-color-lavender,#8b5cf6)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-lavender-bg-hover-dark,color-mix(in_oklch,var(--zui-color-lavender-dark,#a78bfa)_14%,transparent))]",
  ruby: "border border-[color:var(--zui-date-picker-trigger-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-date-picker-trigger-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-date-picker-trigger-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-date-picker-trigger-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] hover:bg-[var(--zui-date-picker-trigger-ruby-bg-hover,color-mix(in_oklch,var(--zui-color-ruby,#be123c)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-ruby-bg-hover-dark,color-mix(in_oklch,var(--zui-color-ruby-dark,#fb7185)_14%,transparent))]",
  red: "border border-[color:var(--zui-date-picker-trigger-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-date-picker-trigger-red-border-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-date-picker-trigger-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-date-picker-trigger-red-fg-dark,var(--zui-color-red-dark,#ef4444))] hover:bg-[var(--zui-date-picker-trigger-red-bg-hover,color-mix(in_oklch,var(--zui-color-red,#dc2626)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-red-bg-hover-dark,color-mix(in_oklch,var(--zui-color-red-dark,#ef4444)_14%,transparent))]",
  slate:
    "border border-[color:var(--zui-date-picker-trigger-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-date-picker-trigger-slate-border-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-date-picker-trigger-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-date-picker-trigger-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] hover:bg-[var(--zui-date-picker-trigger-slate-bg-hover,color-mix(in_oklch,var(--zui-color-slate,#475569)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-slate-bg-hover-dark,color-mix(in_oklch,var(--zui-color-slate-dark,#64748b)_14%,transparent))]",
  zinc: "border border-[color:var(--zui-date-picker-trigger-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-date-picker-trigger-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-date-picker-trigger-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-date-picker-trigger-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] hover:bg-[var(--zui-date-picker-trigger-zinc-bg-hover,color-mix(in_oklch,var(--zui-color-zinc,#52525b)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-zinc-bg-hover-dark,color-mix(in_oklch,var(--zui-color-zinc-dark,#71717a)_14%,transparent))]",
  stone:
    "border border-[color:var(--zui-date-picker-trigger-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-date-picker-trigger-stone-border-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-date-picker-trigger-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-date-picker-trigger-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] hover:bg-[var(--zui-date-picker-trigger-stone-bg-hover,color-mix(in_oklch,var(--zui-color-stone,#57534e)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-stone-bg-hover-dark,color-mix(in_oklch,var(--zui-color-stone-dark,#78716c)_14%,transparent))]",
  royal:
    "border border-[color:var(--zui-date-picker-trigger-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-date-picker-trigger-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-date-picker-trigger-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-date-picker-trigger-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] hover:bg-[var(--zui-date-picker-trigger-royal-bg-hover,color-mix(in_oklch,var(--zui-color-royal,#4338ca)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-royal-bg-hover-dark,color-mix(in_oklch,var(--zui-color-royal-dark,#818cf8)_14%,transparent))]",
  electric:
    "border border-[color:var(--zui-date-picker-trigger-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-date-picker-trigger-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-date-picker-trigger-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-date-picker-trigger-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] hover:bg-[var(--zui-date-picker-trigger-electric-bg-hover,color-mix(in_oklch,var(--zui-color-electric,#0ea5e9)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-electric-bg-hover-dark,color-mix(in_oklch,var(--zui-color-electric-dark,#38bdf8)_14%,transparent))]",
  forest:
    "border border-[color:var(--zui-date-picker-trigger-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-date-picker-trigger-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-date-picker-trigger-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-date-picker-trigger-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] hover:bg-[var(--zui-date-picker-trigger-forest-bg-hover,color-mix(in_oklch,var(--zui-color-forest,#166534)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-forest-bg-hover-dark,color-mix(in_oklch,var(--zui-color-forest-dark,#4ade80)_14%,transparent))]",
  sunset:
    "border border-[color:var(--zui-date-picker-trigger-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-date-picker-trigger-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-date-picker-trigger-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-date-picker-trigger-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] hover:bg-[var(--zui-date-picker-trigger-sunset-bg-hover,color-mix(in_oklch,var(--zui-color-sunset,#ea580c)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-sunset-bg-hover-dark,color-mix(in_oklch,var(--zui-color-sunset-dark,#fb923c)_14%,transparent))]",
  magenta:
    "border border-[color:var(--zui-date-picker-trigger-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-date-picker-trigger-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-date-picker-trigger-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-date-picker-trigger-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] hover:bg-[var(--zui-date-picker-trigger-magenta-bg-hover,color-mix(in_oklch,var(--zui-color-magenta,#c026d3)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-magenta-bg-hover-dark,color-mix(in_oklch,var(--zui-color-magenta-dark,#e879f9)_14%,transparent))]",
  crimson:
    "border border-[color:var(--zui-date-picker-trigger-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-date-picker-trigger-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-date-picker-trigger-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-date-picker-trigger-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] hover:bg-[var(--zui-date-picker-trigger-crimson-bg-hover,color-mix(in_oklch,var(--zui-color-crimson,#b91c1c)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-crimson-bg-hover-dark,color-mix(in_oklch,var(--zui-color-crimson-dark,#f87171)_14%,transparent))]",
  aqua: "border border-[color:var(--zui-date-picker-trigger-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-date-picker-trigger-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-date-picker-trigger-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-date-picker-trigger-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] hover:bg-[var(--zui-date-picker-trigger-aqua-bg-hover,color-mix(in_oklch,var(--zui-color-aqua,#0f766e)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-aqua-bg-hover-dark,color-mix(in_oklch,var(--zui-color-aqua-dark,#2dd4bf)_14%,transparent))]",
  plum: "border border-[color:var(--zui-date-picker-trigger-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-date-picker-trigger-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-date-picker-trigger-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-date-picker-trigger-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] hover:bg-[var(--zui-date-picker-trigger-plum-bg-hover,color-mix(in_oklch,var(--zui-color-plum,#7e22ce)_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-plum-bg-hover-dark,color-mix(in_oklch,var(--zui-color-plum-dark,#c084fc)_14%,transparent))]",
  emerald:
    "border border-[color:var(--zui-date-picker-trigger-emerald-border,var(--zui-color-emerald,oklch(69.6%_0.17_162.48)))] dark:border-[color:var(--zui-date-picker-trigger-emerald-border-dark,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913)))] text-[color:var(--zui-date-picker-trigger-emerald-fg,var(--zui-color-emerald,oklch(69.6%_0.17_162.48)))] dark:text-[color:var(--zui-date-picker-trigger-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913)))] hover:bg-[var(--zui-date-picker-trigger-emerald-bg-hover,color-mix(in_oklch,var(--zui-color-emerald,oklch(69.6%_0.17_162.48))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-emerald-bg-hover-dark,color-mix(in_oklch,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913))_14%,transparent))]",
  indigo:
    "border border-[color:var(--zui-date-picker-trigger-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-date-picker-trigger-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] text-[color:var(--zui-date-picker-trigger-indigo-fg,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:text-[color:var(--zui-date-picker-trigger-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] hover:bg-[var(--zui-date-picker-trigger-indigo-bg-hover,color-mix(in_oklch,var(--zui-color-indigo,oklch(39.8%_0.195_277.366))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-indigo-bg-hover-dark,color-mix(in_oklch,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966))_14%,transparent))]",
  purple:
    "border border-[color:var(--zui-date-picker-trigger-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-date-picker-trigger-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-date-picker-trigger-purple-fg,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:text-[color:var(--zui-date-picker-trigger-purple-fg-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] hover:bg-[var(--zui-date-picker-trigger-purple-bg-hover,color-mix(in_oklch,var(--zui-color-purple,oklch(43.8%_0.218_303.724))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-purple-bg-hover-dark,color-mix(in_oklch,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321))_14%,transparent))]",
  pink: "border border-[color:var(--zui-date-picker-trigger-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-date-picker-trigger-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-date-picker-trigger-pink-fg,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:text-[color:var(--zui-date-picker-trigger-pink-fg-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] hover:bg-[var(--zui-date-picker-trigger-pink-bg-hover,color-mix(in_oklch,var(--zui-color-pink,oklch(45.9%_0.187_3.815))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-pink-bg-hover-dark,color-mix(in_oklch,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584))_14%,transparent))]",
  rose: "border border-[color:var(--zui-date-picker-trigger-rose-border,var(--zui-color-rose,oklch(64.5%_0.246_16.439)))] dark:border-[color:var(--zui-date-picker-trigger-rose-border-dark,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935)))] text-[color:var(--zui-date-picker-trigger-rose-fg,var(--zui-color-rose,oklch(64.5%_0.246_16.439)))] dark:text-[color:var(--zui-date-picker-trigger-rose-fg-dark,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935)))] hover:bg-[var(--zui-date-picker-trigger-rose-bg-hover,color-mix(in_oklch,var(--zui-color-rose,oklch(64.5%_0.246_16.439))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-rose-bg-hover-dark,color-mix(in_oklch,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935))_14%,transparent))]",
  sky: "border border-[color:var(--zui-date-picker-trigger-sky-border,var(--zui-color-sky,oklch(68.5%_0.169_237.323)))] dark:border-[color:var(--zui-date-picker-trigger-sky-border-dark,var(--zui-color-sky-dark,oklch(50%_0.134_242.749)))] text-[color:var(--zui-date-picker-trigger-sky-fg,var(--zui-color-sky,oklch(68.5%_0.169_237.323)))] dark:text-[color:var(--zui-date-picker-trigger-sky-fg-dark,var(--zui-color-sky-dark,oklch(50%_0.134_242.749)))] hover:bg-[var(--zui-date-picker-trigger-sky-bg-hover,color-mix(in_oklch,var(--zui-color-sky,oklch(68.5%_0.169_237.323))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-sky-bg-hover-dark,color-mix(in_oklch,var(--zui-color-sky-dark,oklch(50%_0.134_242.749))_14%,transparent))]",
  teal: "border border-[color:var(--zui-date-picker-trigger-teal-border,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:border-[color:var(--zui-date-picker-trigger-teal-border-dark,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391)))] text-[color:var(--zui-date-picker-trigger-teal-fg,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:text-[color:var(--zui-date-picker-trigger-teal-fg-dark,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391)))] hover:bg-[var(--zui-date-picker-trigger-teal-bg-hover,color-mix(in_oklch,var(--zui-color-teal,oklch(70.4%_0.14_182.503))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-teal-bg-hover-dark,color-mix(in_oklch,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391))_14%,transparent))]",
  yellow:
    "border border-[color:var(--zui-date-picker-trigger-yellow-border,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:border-[color:var(--zui-date-picker-trigger-yellow-border-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] text-[color:var(--zui-date-picker-trigger-yellow-fg,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:text-[color:var(--zui-date-picker-trigger-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] hover:bg-[var(--zui-date-picker-trigger-yellow-bg-hover,color-mix(in_oklch,var(--zui-color-yellow,oklch(79.5%_0.184_86.047))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-yellow-bg-hover-dark,color-mix(in_oklch,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907))_14%,transparent))]",
  orange:
    "border border-[color:var(--zui-date-picker-trigger-orange-border,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:border-[color:var(--zui-date-picker-trigger-orange-border-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] text-[color:var(--zui-date-picker-trigger-orange-fg,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:text-[color:var(--zui-date-picker-trigger-orange-fg-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] hover:bg-[var(--zui-date-picker-trigger-orange-bg-hover,color-mix(in_oklch,var(--zui-color-orange,oklch(70.5%_0.213_47.604))_8%,transparent))] dark:hover:bg-[var(--zui-date-picker-trigger-orange-bg-hover-dark,color-mix(in_oklch,var(--zui-color-orange-dark,oklch(47%_0.157_37.304))_14%,transparent))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-date-picker-trigger-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-date-picker-trigger-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-date-picker-trigger-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-date-picker-trigger-gradient-blue-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-date-picker-trigger-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-date-picker-trigger-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-date-picker-trigger-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] text-[color:var(--zui-date-picker-trigger-gradient-green-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-date-picker-trigger-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-date-picker-trigger-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-date-picker-trigger-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-date-picker-trigger-gradient-red-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-date-picker-trigger-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-date-picker-trigger-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-date-picker-trigger-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] text-[color:var(--zui-date-picker-trigger-gradient-yellow-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-date-picker-trigger-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-date-picker-trigger-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-date-picker-trigger-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-date-picker-trigger-gradient-purple-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-date-picker-trigger-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-date-picker-trigger-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-date-picker-trigger-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] text-[color:var(--zui-date-picker-trigger-gradient-teal-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-date-picker-trigger-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-date-picker-trigger-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-date-picker-trigger-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-date-picker-trigger-gradient-indigo-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-date-picker-trigger-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-date-picker-trigger-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-date-picker-trigger-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] text-[color:var(--zui-date-picker-trigger-gradient-pink-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-date-picker-trigger-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-date-picker-trigger-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-date-picker-trigger-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-date-picker-trigger-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] text-[color:var(--zui-date-picker-trigger-gradient-orange-fg,var(--zui-brand-fg,oklch(96.8%_0.007_247.896)))] dark:text-[color:var(--zui-date-picker-trigger-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
} as const;

export type ZuiDatePickerTriggerAppearance =
  keyof typeof zuiDatePickerTriggerAppearances;

export const zuiDatePickerIcon = "size-4 shrink-0 opacity-70";

export const zuiDatePickerClearButton =
  "inline-flex size-5 shrink-0 cursor-pointer items-center justify-center rounded-full text-[color:var(--zui-date-picker-clear-fg,var(--zui-fg-muted,oklch(44.6%_0.043_257.281)))] dark:text-[color:var(--zui-date-picker-clear-fg-dark,var(--zui-fg-muted-dark,oklch(86.9%_0.022_252.894)))] transition-colors hover:bg-[var(--zui-date-picker-clear-bg-hover,var(--zui-surface-soft,#0000000d))] dark:hover:bg-[var(--zui-date-picker-clear-bg-hover-dark,var(--zui-surface-soft-dark,#ffffff0d))] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-date-picker-ring,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[var(--zui-date-picker-ring-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))]";

export const zuiDatePickerContent = "p-2";
