export const zuiDropdownTriggerBase =
  "inline-flex items-center justify-between rounded-md font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-dropdown-trigger-ring-focus,var(--zui-focus-ring,oklch(55.1%_0.027_264.364_/_0.6)))] dark:focus-visible:ring-[var(--zui-dropdown-trigger-ring-focus-dark,var(--zui-focus-ring-dark,oklch(55.1%_0.027_264.364_/_0.6)))] cursor-pointer";

export const zuiDropdownTriggerVariants = {
  default:
    "bg-[var(--zui-dropdown-trigger-default-bg,var(--zui-surface-muted,oklch(92.8%_0.006_264.531)))] dark:bg-[var(--zui-dropdown-trigger-default-bg-dark,var(--zui-surface-muted-dark,oklch(21%_0.034_264.665)))] text-[color:var(--zui-dropdown-trigger-default-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dropdown-trigger-default-fg-dark,var(--zui-fg-dark,#ffffff))]",
  outline:
    "border border-[color:var(--zui-dropdown-trigger-outline-border,var(--zui-border,oklch(37.3%_0.034_259.733)))] dark:border-[color:var(--zui-dropdown-trigger-outline-border-dark,var(--zui-border-dark,oklch(87.2%_0.01_258.338)))] text-[color:var(--zui-dropdown-trigger-outline-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-trigger-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  ghost:
    "bg-[var(--zui-dropdown-trigger-ghost-bg,transparent)] dark:bg-[var(--zui-dropdown-trigger-ghost-bg-dark,transparent)] text-[color:var(--zui-dropdown-trigger-ghost-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-trigger-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  white:
    "bg-[var(--zui-dropdown-trigger-white-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-dropdown-trigger-white-bg-dark,var(--zui-surface-muted-dark,#ffffff))] text-[color:var(--zui-dropdown-trigger-white-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-trigger-white-fg-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))]",
  black:
    "bg-[var(--zui-dropdown-trigger-black-bg,var(--zui-brand,#000000))] dark:bg-[var(--zui-dropdown-trigger-black-bg-dark,var(--zui-brand-dark,#000000))] text-[color:var(--zui-dropdown-trigger-black-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-dropdown-trigger-black-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  sky: "border border-[color:var(--zui-dropdown-trigger-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-dropdown-trigger-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] text-[color:var(--zui-dropdown-trigger-sky-fg,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:text-[color:var(--zui-dropdown-trigger-sky-fg-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))]",
  rose: "border border-[color:var(--zui-dropdown-trigger-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-dropdown-trigger-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] text-[color:var(--zui-dropdown-trigger-rose-fg,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:text-[color:var(--zui-dropdown-trigger-rose-fg-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))]",
  purple:
    "border border-[color:var(--zui-dropdown-trigger-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-dropdown-trigger-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-dropdown-trigger-purple-fg,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:text-[color:var(--zui-dropdown-trigger-purple-fg-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  pink: "border border-[color:var(--zui-dropdown-trigger-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-dropdown-trigger-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-dropdown-trigger-pink-fg,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:text-[color:var(--zui-dropdown-trigger-pink-fg-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  orange:
    "border border-[color:var(--zui-dropdown-trigger-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-dropdown-trigger-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] text-[color:var(--zui-dropdown-trigger-orange-fg,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:text-[color:var(--zui-dropdown-trigger-orange-fg-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))]",
  yellow:
    "border border-[color:var(--zui-dropdown-trigger-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-dropdown-trigger-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] text-[color:var(--zui-dropdown-trigger-yellow-fg,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:text-[color:var(--zui-dropdown-trigger-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))]",
  teal: "border border-[color:var(--zui-dropdown-trigger-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-dropdown-trigger-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] text-[color:var(--zui-dropdown-trigger-teal-fg,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:text-[color:var(--zui-dropdown-trigger-teal-fg-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))]",
  indigo:
    "border border-[color:var(--zui-dropdown-trigger-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-dropdown-trigger-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] text-[color:var(--zui-dropdown-trigger-indigo-fg,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:text-[color:var(--zui-dropdown-trigger-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))]",
  emerald:
    "border border-[color:var(--zui-dropdown-trigger-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-dropdown-trigger-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] text-[color:var(--zui-dropdown-trigger-emerald-fg,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:text-[color:var(--zui-dropdown-trigger-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))]",
  gray: "border border-[color:var(--zui-dropdown-trigger-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-dropdown-trigger-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] text-[color:var(--zui-dropdown-trigger-gray-fg,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:text-[color:var(--zui-dropdown-trigger-gray-fg-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))]",
  amber:
    "border border-[color:var(--zui-dropdown-trigger-amber-border,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:border-[color:var(--zui-dropdown-trigger-amber-border-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] text-[color:var(--zui-dropdown-trigger-amber-fg,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:text-[color:var(--zui-dropdown-trigger-amber-fg-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))]",
  violet:
    "border border-[color:var(--zui-dropdown-trigger-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-dropdown-trigger-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] text-[color:var(--zui-dropdown-trigger-violet-fg,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:text-[color:var(--zui-dropdown-trigger-violet-fg-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-dropdown-trigger-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-dropdown-trigger-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-dropdown-trigger-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-dropdown-trigger-gradient-blue-fg,var(--zui-brand-fg,oklch(88.2%_0.059_254.128)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(88.2%_0.059_254.128)))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-dropdown-trigger-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-dropdown-trigger-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-dropdown-trigger-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] text-[color:var(--zui-dropdown-trigger-gradient-green-fg,var(--zui-brand-fg,oklch(92.5%_0.084_155.995)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(92.5%_0.084_155.995)))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-dropdown-trigger-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-dropdown-trigger-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-dropdown-trigger-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-dropdown-trigger-gradient-red-fg,var(--zui-brand-fg,oklch(88.5%_0.062_18.334)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(88.5%_0.062_18.334)))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-dropdown-trigger-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-dropdown-trigger-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-dropdown-trigger-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] text-[color:var(--zui-dropdown-trigger-gradient-yellow-fg,var(--zui-brand-fg,oklch(94.5%_0.129_101.54)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(94.5%_0.129_101.54)))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-dropdown-trigger-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-dropdown-trigger-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-dropdown-trigger-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-dropdown-trigger-gradient-purple-fg,var(--zui-brand-fg,oklch(90.2%_0.063_306.703)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(90.2%_0.063_306.703)))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-dropdown-trigger-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-dropdown-trigger-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-dropdown-trigger-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] text-[color:var(--zui-dropdown-trigger-gradient-teal-fg,var(--zui-brand-fg,oklch(91%_0.096_180.426)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(91%_0.096_180.426)))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-dropdown-trigger-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-dropdown-trigger-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-dropdown-trigger-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-dropdown-trigger-gradient-indigo-fg,var(--zui-brand-fg,oklch(87%_0.065_274.039)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(87%_0.065_274.039)))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-dropdown-trigger-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-dropdown-trigger-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-dropdown-trigger-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] text-[color:var(--zui-dropdown-trigger-gradient-pink-fg,var(--zui-brand-fg,oklch(89.9%_0.061_343.231)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(89.9%_0.061_343.231)))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-dropdown-trigger-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-dropdown-trigger-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-dropdown-trigger-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-dropdown-trigger-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] text-[color:var(--zui-dropdown-trigger-gradient-orange-fg,var(--zui-brand-fg,oklch(90.1%_0.076_70.697)))] dark:text-[color:var(--zui-dropdown-trigger-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(90.1%_0.076_70.697)))]",
  blue: "border border-[color:var(--zui-dropdown-trigger-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-dropdown-trigger-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-dropdown-trigger-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-dropdown-trigger-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] hover:bg-[var(--zui-dropdown-trigger-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))]",
  cyan: "border border-[color:var(--zui-dropdown-trigger-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-dropdown-trigger-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-dropdown-trigger-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-dropdown-trigger-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] hover:bg-[var(--zui-dropdown-trigger-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))]",
  green:
    "border border-[color:var(--zui-dropdown-trigger-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-dropdown-trigger-green-border-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-dropdown-trigger-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-dropdown-trigger-green-fg-dark,var(--zui-color-green-dark,#22c55e))] hover:bg-[var(--zui-dropdown-trigger-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))]",
  lime: "border border-[color:var(--zui-dropdown-trigger-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-dropdown-trigger-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-dropdown-trigger-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-dropdown-trigger-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] hover:bg-[var(--zui-dropdown-trigger-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))]",
  mint: "border border-[color:var(--zui-dropdown-trigger-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-dropdown-trigger-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-dropdown-trigger-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-dropdown-trigger-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] hover:bg-[var(--zui-dropdown-trigger-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))]",
  ocean:
    "border border-[color:var(--zui-dropdown-trigger-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-dropdown-trigger-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-dropdown-trigger-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-dropdown-trigger-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] hover:bg-[var(--zui-dropdown-trigger-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))]",
  sapphire:
    "border border-[color:var(--zui-dropdown-trigger-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-dropdown-trigger-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-dropdown-trigger-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-dropdown-trigger-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] hover:bg-[var(--zui-dropdown-trigger-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))]",
  lavender:
    "border border-[color:var(--zui-dropdown-trigger-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-dropdown-trigger-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-dropdown-trigger-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-dropdown-trigger-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] hover:bg-[var(--zui-dropdown-trigger-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))]",
  ruby: "border border-[color:var(--zui-dropdown-trigger-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-dropdown-trigger-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-dropdown-trigger-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-dropdown-trigger-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] hover:bg-[var(--zui-dropdown-trigger-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))]",
  red: "border border-[color:var(--zui-dropdown-trigger-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-dropdown-trigger-red-border-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-dropdown-trigger-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-dropdown-trigger-red-fg-dark,var(--zui-color-red-dark,#ef4444))] hover:bg-[var(--zui-dropdown-trigger-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))]",
  slate:
    "border border-[color:var(--zui-dropdown-trigger-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-dropdown-trigger-slate-border-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-dropdown-trigger-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-dropdown-trigger-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] hover:bg-[var(--zui-dropdown-trigger-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))]",
  zinc: "border border-[color:var(--zui-dropdown-trigger-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-dropdown-trigger-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-dropdown-trigger-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-dropdown-trigger-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] hover:bg-[var(--zui-dropdown-trigger-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))]",
  stone:
    "border border-[color:var(--zui-dropdown-trigger-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-dropdown-trigger-stone-border-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-dropdown-trigger-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-dropdown-trigger-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] hover:bg-[var(--zui-dropdown-trigger-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))]",
  royal:
    "border border-[color:var(--zui-dropdown-trigger-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-dropdown-trigger-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-dropdown-trigger-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-dropdown-trigger-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] hover:bg-[var(--zui-dropdown-trigger-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))]",
  electric:
    "border border-[color:var(--zui-dropdown-trigger-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-dropdown-trigger-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-dropdown-trigger-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-dropdown-trigger-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] hover:bg-[var(--zui-dropdown-trigger-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))]",
  forest:
    "border border-[color:var(--zui-dropdown-trigger-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-dropdown-trigger-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-dropdown-trigger-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-dropdown-trigger-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] hover:bg-[var(--zui-dropdown-trigger-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))]",
  sunset:
    "border border-[color:var(--zui-dropdown-trigger-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-dropdown-trigger-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-dropdown-trigger-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-dropdown-trigger-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] hover:bg-[var(--zui-dropdown-trigger-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))]",
  magenta:
    "border border-[color:var(--zui-dropdown-trigger-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-dropdown-trigger-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-dropdown-trigger-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-dropdown-trigger-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] hover:bg-[var(--zui-dropdown-trigger-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))]",
  crimson:
    "border border-[color:var(--zui-dropdown-trigger-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-dropdown-trigger-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-dropdown-trigger-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-dropdown-trigger-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] hover:bg-[var(--zui-dropdown-trigger-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))]",
  aqua: "border border-[color:var(--zui-dropdown-trigger-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-dropdown-trigger-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-dropdown-trigger-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-dropdown-trigger-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] hover:bg-[var(--zui-dropdown-trigger-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))]",
  plum: "border border-[color:var(--zui-dropdown-trigger-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-dropdown-trigger-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-dropdown-trigger-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-dropdown-trigger-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] hover:bg-[var(--zui-dropdown-trigger-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-trigger-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))]",
} as const;

export const zuiDropdownTriggerSizes = {
  sm: "px-2 py-1 text-sm",
  md: "px-3 py-2 text-base",
  lg: "px-4 py-3 text-lg",
} as const;

export const zuiDropdownContentBase =
  "absolute min-w-[200px] rounded-[var(--zui-dropdown-content-radius,var(--zui-radius,0.5rem))] p-2 z-50 border border-[color:var(--zui-dropdown-content-border,var(--zui-border,oklch(20.8%_0.042_265.755_/_0.1)))] dark:border-[color:var(--zui-dropdown-content-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-dropdown-content-bg,var(--zui-surface-muted,oklch(96.8%_0.007_247.896)))] dark:bg-[var(--zui-dropdown-content-bg-dark,var(--zui-surface-muted-dark,oklch(20.8%_0.042_265.755)))] text-[color:var(--zui-dropdown-content-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dropdown-content-fg-dark,var(--zui-fg-dark,oklch(96.8%_0.007_247.896)))] shadow-[var(--zui-dropdown-content-shadow,var(--zui-shadow,0_10px_30px_rgba(15,23,42,0.16)))] dark:shadow-[var(--zui-dropdown-content-shadow-dark,var(--zui-shadow-dark,0_18px_48px_rgba(15,23,42,0.35)))]";

export const zuiDropdownPlacements = {
  top: "bottom-full mb-2",
  bottom: "top-full mt-2",
  left: "right-full mr-2",
  right: "left-full ml-2",
} as const;

export const zuiDropdownSpacing = {
  none: "space-y-0",
  default: "space-y-1",
  sm: "space-y-2",
  md: "space-y-3",
  lg: "space-y-4",
  xl: "space-y-5",
} as const;

export const zuiDropdownItemBase =
  "flex items-center justify-between px-3 py-2 text-sm cursor-pointer rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-dropdown-item-ring-focus,var(--zui-focus-ring,oklch(55.1%_0.027_264.364_/_0.6)))] dark:focus-visible:ring-[var(--zui-dropdown-item-ring-focus-dark,var(--zui-focus-ring-dark,oklch(55.1%_0.027_264.364_/_0.6)))] font-semibold";

export const zuiDropdownItemVariants = {
  default:
    "hover:bg-[var(--zui-dropdown-item-default-bg-hover,var(--zui-surface-hover,oklch(96.7%_0.003_264.542)))] dark:hover:bg-[var(--zui-dropdown-item-default-bg-hover-dark,var(--zui-surface-hover-dark,oklch(96.7%_0.003_264.542)))] hover:text-[color:var(--zui-dropdown-item-default-fg-hover,var(--zui-fg,oklch(55.1%_0.027_264.364)))] dark:hover:text-[color:var(--zui-dropdown-item-default-fg-hover-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))] text-[color:var(--zui-dropdown-item-default-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-item-default-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  outline:
    "hover:bg-[var(--zui-dropdown-item-outline-bg-hover,var(--zui-surface-hover,oklch(96.7%_0.003_264.542)))] dark:hover:bg-[var(--zui-dropdown-item-outline-bg-hover-dark,var(--zui-surface-hover-dark,oklch(96.7%_0.003_264.542)))] hover:text-[color:var(--zui-dropdown-item-outline-fg-hover,var(--zui-fg,oklch(55.1%_0.027_264.364)))] dark:hover:text-[color:var(--zui-dropdown-item-outline-fg-hover-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))] border border-[color:var(--zui-dropdown-item-outline-border,var(--zui-border,#000000))] dark:border-[color:var(--zui-dropdown-item-outline-border-dark,var(--zui-border-dark,#ffffff))] text-[color:var(--zui-dropdown-item-outline-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-item-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  ghost:
    "hover:bg-[var(--zui-dropdown-item-ghost-bg-hover,var(--zui-surface-hover,oklch(96.7%_0.003_264.542)))] dark:hover:bg-[var(--zui-dropdown-item-ghost-bg-hover-dark,var(--zui-surface-hover-dark,oklch(96.7%_0.003_264.542)))] hover:text-[color:var(--zui-dropdown-item-ghost-fg-hover,var(--zui-fg,oklch(55.1%_0.027_264.364)))] dark:hover:text-[color:var(--zui-dropdown-item-ghost-fg-hover-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))] bg-[var(--zui-dropdown-item-ghost-bg,transparent)] dark:bg-[var(--zui-dropdown-item-ghost-bg-dark,transparent)] text-[color:var(--zui-dropdown-item-ghost-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-item-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  white:
    "hover:bg-[var(--zui-dropdown-item-white-bg-hover,var(--zui-surface-hover,oklch(96.7%_0.003_264.542)))] dark:hover:bg-[var(--zui-dropdown-item-white-bg-hover-dark,var(--zui-surface-hover-dark,oklch(96.7%_0.003_264.542)))] hover:text-[color:var(--zui-dropdown-item-white-fg-hover,var(--zui-fg,oklch(55.1%_0.027_264.364)))] dark:hover:text-[color:var(--zui-dropdown-item-white-fg-hover-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))] bg-[var(--zui-dropdown-item-white-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-dropdown-item-white-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-dropdown-item-white-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dropdown-item-white-fg-dark,var(--zui-fg-dark,#ffffff))]",
  black:
    "hover:bg-[var(--zui-dropdown-item-black-bg-hover,var(--zui-surface-hover,oklch(96.7%_0.003_264.542)))] dark:hover:bg-[var(--zui-dropdown-item-black-bg-hover-dark,var(--zui-surface-hover-dark,oklch(96.7%_0.003_264.542)))] hover:text-[color:var(--zui-dropdown-item-black-fg-hover,var(--zui-brand-fg,oklch(55.1%_0.027_264.364)))] dark:hover:text-[color:var(--zui-dropdown-item-black-fg-hover-dark,var(--zui-brand-fg-dark,oklch(21%_0.034_264.665)))] bg-[var(--zui-dropdown-item-black-bg,var(--zui-brand,#000000))] dark:bg-[var(--zui-dropdown-item-black-bg-dark,var(--zui-brand-dark,#ffffff))] text-[color:var(--zui-dropdown-item-black-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-dropdown-item-black-fg-dark,var(--zui-brand-fg-dark,oklch(21%_0.034_264.665)))]",
  sky: "hover:bg-[var(--zui-dropdown-item-sky-bg-hover,color-mix(in oklch, var(--zui-color-sky,oklch(95.1%_0.026_236.824)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-sky-bg-hover-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(95.1%_0.026_236.824)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-sky-fg-hover,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:hover:text-[color:var(--zui-dropdown-item-sky-fg-hover-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] bg-[var(--zui-dropdown-item-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(90.1%_0.058_230.902)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(90.1%_0.058_230.902)) 18%, transparent))] text-[color:var(--zui-dropdown-item-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:text-[color:var(--zui-dropdown-item-sky-fg-dark,var(--zui-color-sky-dark,oklch(44.3%_0.11_240.79)))]",
  rose: "hover:bg-[var(--zui-dropdown-item-rose-bg-hover,color-mix(in oklch, var(--zui-color-rose,oklch(94.1%_0.03_12.58)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-rose-bg-hover-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(94.1%_0.03_12.58)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-rose-fg-hover,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:hover:text-[color:var(--zui-dropdown-item-rose-fg-hover-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] bg-[var(--zui-dropdown-item-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(89.2%_0.058_10.001)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(89.2%_0.058_10.001)) 18%, transparent))] text-[color:var(--zui-dropdown-item-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-dropdown-item-rose-fg-dark,var(--zui-color-rose-dark,oklch(45.5%_0.188_13.697)))]",
  purple:
    "hover:bg-[var(--zui-dropdown-item-purple-bg-hover,color-mix(in oklch, var(--zui-color-purple,oklch(94.6%_0.033_307.174)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-purple-bg-hover-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(94.6%_0.033_307.174)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-purple-fg-hover,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:hover:text-[color:var(--zui-dropdown-item-purple-fg-hover-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-dropdown-item-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(90.2%_0.063_306.703)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)) 18%, transparent))] text-[color:var(--zui-dropdown-item-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-dropdown-item-purple-fg-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))]",
  pink: "hover:bg-[var(--zui-dropdown-item-pink-bg-hover,color-mix(in oklch, var(--zui-color-pink,oklch(94.8%_0.028_342.258)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-pink-bg-hover-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(94.8%_0.028_342.258)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-pink-fg-hover,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:hover:text-[color:var(--zui-dropdown-item-pink-fg-hover-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-dropdown-item-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(89.9%_0.061_343.231)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)) 18%, transparent))] text-[color:var(--zui-dropdown-item-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-dropdown-item-pink-fg-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))]",
  orange:
    "hover:bg-[var(--zui-dropdown-item-orange-bg-hover,color-mix(in oklch, var(--zui-color-orange,oklch(95.4%_0.038_75.164)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-orange-bg-hover-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(95.4%_0.038_75.164)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-orange-fg-hover,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:hover:text-[color:var(--zui-dropdown-item-orange-fg-hover-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-dropdown-item-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(90.1%_0.076_70.697)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)) 18%, transparent))] text-[color:var(--zui-dropdown-item-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-dropdown-item-orange-fg-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))]",
  yellow:
    "hover:bg-[var(--zui-dropdown-item-yellow-bg-hover,color-mix(in oklch, var(--zui-color-yellow,oklch(97.3%_0.071_103.193)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-yellow-bg-hover-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(97.3%_0.071_103.193)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-yellow-fg-hover,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:hover:text-[color:var(--zui-dropdown-item-yellow-fg-hover-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-dropdown-item-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(94.5%_0.129_101.54)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)) 18%, transparent))] text-[color:var(--zui-dropdown-item-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-dropdown-item-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))]",
  teal: "hover:bg-[var(--zui-dropdown-item-teal-bg-hover,color-mix(in oklch, var(--zui-color-teal,oklch(95.3%_0.051_180.801)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-teal-bg-hover-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(95.3%_0.051_180.801)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-teal-fg-hover,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:hover:text-[color:var(--zui-dropdown-item-teal-fg-hover-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-dropdown-item-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(91%_0.096_180.426)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(91%_0.096_180.426)) 18%, transparent))] text-[color:var(--zui-dropdown-item-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-dropdown-item-teal-fg-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))]",
  indigo:
    "hover:bg-[var(--zui-dropdown-item-indigo-bg-hover,color-mix(in oklch, var(--zui-color-indigo,oklch(93%_0.034_272.788)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-indigo-bg-hover-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(93%_0.034_272.788)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-indigo-fg-hover,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:hover:text-[color:var(--zui-dropdown-item-indigo-fg-hover-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-dropdown-item-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(87%_0.065_274.039)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)) 18%, transparent))] text-[color:var(--zui-dropdown-item-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-dropdown-item-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))]",
  emerald:
    "hover:bg-[var(--zui-dropdown-item-emerald-bg-hover,color-mix(in oklch, var(--zui-color-emerald,oklch(95%_0.052_163.051)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-emerald-bg-hover-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(95%_0.052_163.051)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-emerald-fg-hover,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:hover:text-[color:var(--zui-dropdown-item-emerald-fg-hover-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] bg-[var(--zui-dropdown-item-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(90.5%_0.093_164.15)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(90.5%_0.093_164.15)) 18%, transparent))] text-[color:var(--zui-dropdown-item-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-dropdown-item-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913)))]",
  gray: "hover:bg-[var(--zui-dropdown-item-gray-bg-hover,color-mix(in oklch, var(--zui-color-gray,oklch(96.7%_0.003_264.542)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-gray-bg-hover-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(96.7%_0.003_264.542)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-gray-fg-hover,var(--zui-color-gray,oklch(55.1%_0.027_264.364)))] dark:hover:text-[color:var(--zui-dropdown-item-gray-fg-hover-dark,var(--zui-color-gray-dark,oklch(21%_0.034_264.665)))] bg-[var(--zui-dropdown-item-gray-bg,color-mix(in oklch, var(--zui-color-gray,oklch(92.8%_0.006_264.531)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-gray-bg-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(92.8%_0.006_264.531)) 18%, transparent))] text-[color:var(--zui-dropdown-item-gray-fg,var(--zui-color-gray,oklch(55.1%_0.027_264.364)))] dark:text-[color:var(--zui-dropdown-item-gray-fg-dark,var(--zui-color-gray-dark,oklch(27.8%_0.033_256.848)))]",
  amber:
    "hover:bg-[var(--zui-dropdown-item-amber-bg-hover,color-mix(in oklch, var(--zui-color-amber,oklch(96.2%_0.059_95.617)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-amber-bg-hover-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(96.2%_0.059_95.617)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-amber-fg-hover,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:hover:text-[color:var(--zui-dropdown-item-amber-fg-hover-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] bg-[var(--zui-dropdown-item-amber-bg,color-mix(in oklch, var(--zui-color-amber,oklch(92.4%_0.12_95.746)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-amber-bg-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(92.4%_0.12_95.746)) 18%, transparent))] text-[color:var(--zui-dropdown-item-amber-fg,var(--zui-color-amber,oklch(41.4%_0.112_45.904)))] dark:text-[color:var(--zui-dropdown-item-amber-fg-dark,var(--zui-color-amber-dark,oklch(47.3%_0.137_46.201)))]",
  violet:
    "hover:bg-[var(--zui-dropdown-item-violet-bg-hover,color-mix(in oklch, var(--zui-color-violet,oklch(94.3%_0.029_294.588)) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-violet-bg-hover-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(94.3%_0.029_294.588)) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-violet-fg-hover,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:hover:text-[color:var(--zui-dropdown-item-violet-fg-hover-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-dropdown-item-violet-bg,color-mix(in oklch, var(--zui-color-violet,oklch(89.4%_0.057_293.283)) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-violet-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(89.4%_0.057_293.283)) 18%, transparent))] text-[color:var(--zui-dropdown-item-violet-fg,var(--zui-color-violet,oklch(38%_0.189_293.745)))] dark:text-[color:var(--zui-dropdown-item-violet-fg-dark,var(--zui-color-violet-dark,oklch(43.2%_0.232_292.759)))]",
  "gradient-blue":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-dropdown-item-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-dropdown-item-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-dropdown-item-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] hover:text-[color:var(--zui-dropdown-item-gradient-blue-fg-hover,var(--zui-color-blue,oklch(62.3%_0.214_259.815)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-blue-fg-hover-dark,var(--zui-color-blue-dark,oklch(37.9%_0.146_265.522)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-blue-from,var(--zui-color-blue,oklch(88.2%_0.059_254.128)))] to-[var(--zui-dropdown-item-gradient-blue-to,var(--zui-color-purple,oklch(90.2%_0.063_306.703)))] text-[color:var(--zui-dropdown-item-gradient-blue-fg,var(--zui-color-blue,oklch(37.9%_0.146_265.522)))] dark:text-[color:var(--zui-dropdown-item-gradient-blue-fg-dark,var(--zui-color-blue-dark,oklch(88.2%_0.059_254.128)))]",
  "gradient-green":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-dropdown-item-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-dropdown-item-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-dropdown-item-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] hover:text-[color:var(--zui-dropdown-item-gradient-green-fg-hover,var(--zui-color-green,oklch(72.3%_0.219_149.579)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-green-fg-hover-dark,var(--zui-color-green-dark,oklch(39.3%_0.095_152.535)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-green-from,var(--zui-color-green,oklch(92.5%_0.084_155.995)))] to-[var(--zui-dropdown-item-gradient-green-to,var(--zui-color-lime,oklch(93.8%_0.127_124.321)))] text-[color:var(--zui-dropdown-item-gradient-green-fg,var(--zui-color-green,oklch(39.3%_0.095_152.535)))] dark:text-[color:var(--zui-dropdown-item-gradient-green-fg-dark,var(--zui-color-green-dark,oklch(92.5%_0.084_155.995)))]",
  "gradient-red":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-dropdown-item-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-dropdown-item-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-dropdown-item-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] hover:text-[color:var(--zui-dropdown-item-gradient-red-fg-hover,var(--zui-color-red,oklch(63.7%_0.237_25.331)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-red-fg-hover-dark,var(--zui-color-red-dark,oklch(39.6%_0.141_25.723)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-red-from,var(--zui-color-red,oklch(88.5%_0.062_18.334)))] to-[var(--zui-dropdown-item-gradient-red-to,var(--zui-color-pink,oklch(89.9%_0.061_343.231)))] text-[color:var(--zui-dropdown-item-gradient-red-fg,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:text-[color:var(--zui-dropdown-item-gradient-red-fg-dark,var(--zui-color-red-dark,oklch(88.5%_0.062_18.334)))]",
  "gradient-yellow":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-dropdown-item-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-dropdown-item-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-dropdown-item-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] hover:text-[color:var(--zui-dropdown-item-gradient-yellow-fg-hover,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-yellow-fg-hover-dark,var(--zui-color-yellow-dark,oklch(42.1%_0.095_57.708)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-yellow-from,var(--zui-color-yellow,oklch(94.5%_0.129_101.54)))] to-[var(--zui-dropdown-item-gradient-yellow-to,var(--zui-color-orange,oklch(90.1%_0.076_70.697)))] text-[color:var(--zui-dropdown-item-gradient-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-dropdown-item-gradient-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)))]",
  "gradient-purple":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-dropdown-item-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-dropdown-item-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-dropdown-item-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] hover:text-[color:var(--zui-dropdown-item-gradient-purple-fg-hover,var(--zui-color-purple,oklch(62.7%_0.265_303.9)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-purple-fg-hover-dark,var(--zui-color-purple-dark,oklch(38.1%_0.176_304.987)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-purple-from,var(--zui-color-purple,oklch(90.2%_0.063_306.703)))] to-[var(--zui-dropdown-item-gradient-purple-to,var(--zui-color-pink,oklch(89.9%_0.061_343.231)))] text-[color:var(--zui-dropdown-item-gradient-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-dropdown-item-gradient-purple-fg-dark,var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)))]",
  "gradient-teal":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-dropdown-item-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-dropdown-item-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-dropdown-item-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] hover:text-[color:var(--zui-dropdown-item-gradient-teal-fg-hover,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-teal-fg-hover-dark,var(--zui-color-teal-dark,oklch(38.6%_0.063_188.416)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-teal-from,var(--zui-color-teal,oklch(91%_0.096_180.426)))] to-[var(--zui-dropdown-item-gradient-teal-to,var(--zui-color-cyan,oklch(91.7%_0.08_205.041)))] text-[color:var(--zui-dropdown-item-gradient-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-dropdown-item-gradient-teal-fg-dark,var(--zui-color-teal-dark,oklch(91%_0.096_180.426)))]",
  "gradient-indigo":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-dropdown-item-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-dropdown-item-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-dropdown-item-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] hover:text-[color:var(--zui-dropdown-item-gradient-indigo-fg-hover,var(--zui-color-indigo,oklch(58.5%_0.233_277.117)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-indigo-fg-hover-dark,var(--zui-color-indigo-dark,oklch(35.9%_0.144_278.697)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-indigo-from,var(--zui-color-indigo,oklch(87%_0.065_274.039)))] to-[var(--zui-dropdown-item-gradient-indigo-to,var(--zui-color-purple,oklch(90.2%_0.063_306.703)))] text-[color:var(--zui-dropdown-item-gradient-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-dropdown-item-gradient-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)))]",
  "gradient-pink":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-dropdown-item-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-dropdown-item-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-dropdown-item-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] hover:text-[color:var(--zui-dropdown-item-gradient-pink-fg-hover,var(--zui-color-pink,oklch(65.6%_0.241_354.308)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-pink-fg-hover-dark,var(--zui-color-pink-dark,oklch(40.8%_0.153_2.432)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-pink-from,var(--zui-color-pink,oklch(89.9%_0.061_343.231)))] to-[var(--zui-dropdown-item-gradient-pink-to,var(--zui-color-rose,oklch(89.2%_0.058_10.001)))] text-[color:var(--zui-dropdown-item-gradient-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-dropdown-item-gradient-pink-fg-dark,var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)))]",
  "gradient-orange":
    "hover:bg-linear-to-r from-[var(--zui-dropdown-item-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-dropdown-item-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-dropdown-item-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-dropdown-item-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] hover:text-[color:var(--zui-dropdown-item-gradient-orange-fg-hover,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:hover:text-[color:var(--zui-dropdown-item-gradient-orange-fg-hover-dark,var(--zui-color-orange-dark,oklch(40.8%_0.123_38.172)))] bg-linear-to-r from-[var(--zui-dropdown-item-gradient-orange-from,var(--zui-color-orange,oklch(90.1%_0.076_70.697)))] to-[var(--zui-dropdown-item-gradient-orange-to,var(--zui-color-red,oklch(88.5%_0.062_18.334)))] text-[color:var(--zui-dropdown-item-gradient-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-dropdown-item-gradient-orange-fg-dark,var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)))]",
  blue: "hover:bg-[var(--zui-dropdown-item-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f62e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-blue-fg-hover,var(--zui-color-blue,#2563eb))] dark:hover:text-[color:var(--zui-dropdown-item-blue-fg-hover-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-dropdown-item-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f61f) 18%, transparent))] text-[color:var(--zui-dropdown-item-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-dropdown-item-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "hover:bg-[var(--zui-dropdown-item-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b218) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-cyan-fg-hover,var(--zui-color-cyan,#0891b2))] dark:hover:text-[color:var(--zui-dropdown-item-cyan-fg-hover-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-dropdown-item-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b210) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-dropdown-item-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "hover:bg-[var(--zui-dropdown-item-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-green-fg-hover,var(--zui-color-green,#16a34a))] dark:hover:text-[color:var(--zui-dropdown-item-green-fg-hover-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-dropdown-item-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-dropdown-item-green-fg-dark,var(--zui-color-green-dark,#22c55e))]",
  lime: "hover:bg-[var(--zui-dropdown-item-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e6352e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-lime-fg-hover,var(--zui-color-lime,#65a30d))] dark:hover:text-[color:var(--zui-dropdown-item-lime-fg-hover-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-dropdown-item-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e6351f) 18%, transparent))] text-[color:var(--zui-dropdown-item-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-dropdown-item-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))]",
  mint: "hover:bg-[var(--zui-dropdown-item-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98118) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b72e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-mint-fg-hover,var(--zui-color-mint,#10b981))] dark:hover:text-[color:var(--zui-dropdown-item-mint-fg-hover-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-dropdown-item-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98110) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b71f) 18%, transparent))] text-[color:var(--zui-dropdown-item-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-dropdown-item-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "hover:bg-[var(--zui-dropdown-item-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c718) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf82e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-ocean-fg-hover,var(--zui-color-ocean,#0284c7))] dark:hover:text-[color:var(--zui-dropdown-item-ocean-fg-hover-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-dropdown-item-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c710) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf81f) 18%, transparent))] text-[color:var(--zui-dropdown-item-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-dropdown-item-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "hover:bg-[var(--zui-dropdown-item-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed818) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-sapphire-fg-hover,var(--zui-color-sapphire,#1d4ed8))] dark:hover:text-[color:var(--zui-dropdown-item-sapphire-fg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-dropdown-item-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed810) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-dropdown-item-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "hover:bg-[var(--zui-dropdown-item-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf618) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-lavender-fg-hover,var(--zui-color-lavender,#8b5cf6))] dark:hover:text-[color:var(--zui-dropdown-item-lavender-fg-hover-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-dropdown-item-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf610) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-dropdown-item-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "hover:bg-[var(--zui-dropdown-item-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb71852e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-ruby-fg-hover,var(--zui-color-ruby,#be123c))] dark:hover:text-[color:var(--zui-dropdown-item-ruby-fg-hover-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-dropdown-item-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb71851f) 18%, transparent))] text-[color:var(--zui-dropdown-item-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-dropdown-item-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "hover:bg-[var(--zui-dropdown-item-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262618) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44442e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-red-fg-hover,var(--zui-color-red,#dc2626))] dark:hover:text-[color:var(--zui-dropdown-item-red-fg-hover-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-dropdown-item-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262610) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44441f) 18%, transparent))] text-[color:var(--zui-dropdown-item-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-dropdown-item-red-fg-dark,var(--zui-color-red-dark,#ef4444))]",
  slate:
    "hover:bg-[var(--zui-dropdown-item-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556918) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-slate-fg-hover,var(--zui-color-slate,#475569))] dark:hover:text-[color:var(--zui-dropdown-item-slate-fg-hover-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-dropdown-item-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556910) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-dropdown-item-slate-fg-dark,var(--zui-color-slate-dark,#64748b))]",
  zinc: "hover:bg-[var(--zui-dropdown-item-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-zinc-fg-hover,var(--zui-color-zinc,#52525b))] dark:hover:text-[color:var(--zui-dropdown-item-zinc-fg-hover-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-dropdown-item-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-dropdown-item-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))]",
  stone:
    "hover:bg-[var(--zui-dropdown-item-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-stone-fg-hover,var(--zui-color-stone,#57534e))] dark:hover:text-[color:var(--zui-dropdown-item-stone-fg-hover-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-dropdown-item-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-dropdown-item-stone-fg-dark,var(--zui-color-stone-dark,#78716c))]",
  royal:
    "hover:bg-[var(--zui-dropdown-item-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf82e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-royal-fg-hover,var(--zui-color-royal,#4338ca))] dark:hover:text-[color:var(--zui-dropdown-item-royal-fg-hover-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-dropdown-item-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf81f) 18%, transparent))] text-[color:var(--zui-dropdown-item-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-dropdown-item-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "hover:bg-[var(--zui-dropdown-item-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e918) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf82e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-electric-fg-hover,var(--zui-color-electric,#0ea5e9))] dark:hover:text-[color:var(--zui-dropdown-item-electric-fg-hover-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-dropdown-item-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e910) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf81f) 18%, transparent))] text-[color:var(--zui-dropdown-item-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-dropdown-item-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "hover:bg-[var(--zui-dropdown-item-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653418) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade802e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-forest-fg-hover,var(--zui-color-forest,#166534))] dark:hover:text-[color:var(--zui-dropdown-item-forest-fg-hover-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-dropdown-item-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653410) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade801f) 18%, transparent))] text-[color:var(--zui-dropdown-item-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-dropdown-item-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "hover:bg-[var(--zui-dropdown-item-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-sunset-fg-hover,var(--zui-color-sunset,#ea580c))] dark:hover:text-[color:var(--zui-dropdown-item-sunset-fg-hover-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-dropdown-item-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-dropdown-item-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "hover:bg-[var(--zui-dropdown-item-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d318) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f92e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-magenta-fg-hover,var(--zui-color-magenta,#c026d3))] dark:hover:text-[color:var(--zui-dropdown-item-magenta-fg-hover-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-dropdown-item-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d310) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f91f) 18%, transparent))] text-[color:var(--zui-dropdown-item-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-dropdown-item-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "hover:bg-[var(--zui-dropdown-item-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f871712e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-crimson-fg-hover,var(--zui-color-crimson,#b91c1c))] dark:hover:text-[color:var(--zui-dropdown-item-crimson-fg-hover-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-dropdown-item-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f871711f) 18%, transparent))] text-[color:var(--zui-dropdown-item-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-dropdown-item-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "hover:bg-[var(--zui-dropdown-item-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-aqua-fg-hover,var(--zui-color-aqua,#0f766e))] dark:hover:text-[color:var(--zui-dropdown-item-aqua-fg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-dropdown-item-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-dropdown-item-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "hover:bg-[var(--zui-dropdown-item-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce18) 10%, transparent))] dark:hover:bg-[var(--zui-dropdown-item-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc2e) 18%, transparent))] hover:text-[color:var(--zui-dropdown-item-plum-fg-hover,var(--zui-color-plum,#7e22ce))] dark:hover:text-[color:var(--zui-dropdown-item-plum-fg-hover-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-dropdown-item-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce10) 10%, transparent))] dark:bg-[var(--zui-dropdown-item-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc1f) 18%, transparent))] text-[color:var(--zui-dropdown-item-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-dropdown-item-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))]",
} as const;
