export type ZuiDynamicStepperIndicatorSemanticState =
  | "complete"
  | "current"
  | "upcoming";

export const zuiDynamicStepperIndicatorToneClasses = {
  default: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-default-border-complete,var(--zui-border,oklch(55.4%_0.046_257.417_/_0.55)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-default-border-complete-dark,var(--zui-border-dark,oklch(37.2%_0.044_257.287_/_0.55)))] bg-[var(--zui-dynamic-stepper-indicator-default-bg-complete,var(--zui-surface-muted,oklch(55.4%_0.046_257.417_/_0.25)))] dark:bg-[var(--zui-dynamic-stepper-indicator-default-bg-complete-dark,var(--zui-surface-muted-dark,oklch(55.4%_0.046_257.417_/_0.25)))] text-[color:var(--zui-dynamic-stepper-indicator-default-fg-complete,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-default-fg-complete-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-default-ring-complete,var(--zui-focus-ring,oklch(55.4%_0.046_257.417_/_0.25)))] dark:ring-[var(--zui-dynamic-stepper-indicator-default-ring-complete-dark,var(--zui-focus-ring-dark,oklch(70.4%_0.04_256.788_/_0.25)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-default-border-current,var(--zui-border,oklch(44.6%_0.043_257.281)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-default-border-current-dark,var(--zui-border-dark,oklch(86.9%_0.022_252.894)))] bg-[var(--zui-dynamic-stepper-indicator-default-bg-current,var(--zui-surface-hover,oklch(55.4%_0.046_257.417_/_0.35)))] dark:bg-[var(--zui-dynamic-stepper-indicator-default-bg-current-dark,var(--zui-surface-hover-dark,oklch(55.4%_0.046_257.417_/_0.35)))] text-[color:var(--zui-dynamic-stepper-indicator-default-fg-current,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-default-fg-current-dark,var(--zui-fg-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-default-ring-current,var(--zui-focus-ring,oklch(44.6%_0.043_257.281_/_0.45)))] dark:ring-[var(--zui-dynamic-stepper-indicator-default-ring-current-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894_/_0.45)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-default-border-upcoming,var(--zui-border,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-default-border-upcoming-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-default-bg-upcoming,var(--zui-surface-muted,#0000000d))] dark:bg-[var(--zui-dynamic-stepper-indicator-default-bg-upcoming-dark,var(--zui-surface-muted-dark,#ffffff0d))] text-[color:var(--zui-dynamic-stepper-indicator-default-fg-upcoming,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-default-fg-upcoming-dark,var(--zui-fg-dark,oklch(70.4%_0.04_256.788)))]",
  },
  secondary: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-secondary-border-complete,var(--zui-border,oklch(70.4%_0.04_256.788)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-secondary-border-complete-dark,var(--zui-border-dark,oklch(44.6%_0.043_257.281)))] bg-[var(--zui-dynamic-stepper-indicator-secondary-bg-complete,var(--zui-surface-soft,oklch(92.9%_0.013_255.508_/_0.7)))] dark:bg-[var(--zui-dynamic-stepper-indicator-secondary-bg-complete-dark,var(--zui-surface-soft-dark,oklch(27.9%_0.041_260.031_/_0.7)))] text-[color:var(--zui-dynamic-stepper-indicator-secondary-fg-complete,var(--zui-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-secondary-fg-complete-dark,var(--zui-fg-dark,oklch(92.9%_0.013_255.508)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-secondary-ring-complete,var(--zui-focus-ring,oklch(70.4%_0.04_256.788_/_0.35)))] dark:ring-[var(--zui-dynamic-stepper-indicator-secondary-ring-complete-dark,var(--zui-focus-ring-dark,oklch(44.6%_0.043_257.281_/_0.35)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-secondary-border-current,var(--zui-border,oklch(55.4%_0.046_257.417)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-secondary-border-current-dark,var(--zui-border-dark,oklch(55.4%_0.046_257.417)))] bg-[var(--zui-dynamic-stepper-indicator-secondary-bg-current,var(--zui-surface-hover,oklch(86.9%_0.022_252.894_/_0.55)))] dark:bg-[var(--zui-dynamic-stepper-indicator-secondary-bg-current-dark,var(--zui-surface-hover-dark,oklch(37.2%_0.044_257.287_/_0.55)))] text-[color:var(--zui-dynamic-stepper-indicator-secondary-fg-current,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-secondary-fg-current-dark,var(--zui-fg-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-secondary-ring-current,var(--zui-focus-ring,oklch(55.4%_0.046_257.417_/_0.45)))] dark:ring-[var(--zui-dynamic-stepper-indicator-secondary-ring-current-dark,var(--zui-focus-ring-dark,oklch(55.4%_0.046_257.417_/_0.45)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-secondary-border-upcoming,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-dynamic-stepper-indicator-secondary-border-upcoming-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-dynamic-stepper-indicator-secondary-bg-upcoming,var(--zui-surface-soft,oklch(96.8%_0.007_247.896_/_0.5)))] dark:bg-[var(--zui-dynamic-stepper-indicator-secondary-bg-upcoming-dark,var(--zui-surface-soft-dark,oklch(20.8%_0.042_265.755_/_0.5)))] text-[color:var(--zui-dynamic-stepper-indicator-secondary-fg-upcoming,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-secondary-fg-upcoming-dark,var(--zui-fg-dark,oklch(55.4%_0.046_257.417)))]",
  },
  destructive: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-destructive-border-complete,var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-destructive-border-complete-dark,var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-destructive-bg-complete,var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.2)))] dark:bg-[var(--zui-dynamic-stepper-indicator-destructive-bg-complete-dark,var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.2)))] text-[color:var(--zui-dynamic-stepper-indicator-destructive-fg-complete,var(--zui-status-error,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-destructive-fg-complete-dark,var(--zui-status-error-dark,oklch(94.1%_0.03_12.58)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-destructive-ring-complete,var(--zui-focus-ring,oklch(71.2%_0.194_13.428_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-destructive-ring-complete-dark,var(--zui-focus-ring-dark,oklch(71.2%_0.194_13.428_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-destructive-border-current,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-destructive-border-current-dark,var(--zui-status-error-dark,oklch(71.2%_0.194_13.428)))] bg-[var(--zui-dynamic-stepper-indicator-destructive-bg-current,var(--zui-status-error,oklch(94.1%_0.03_12.58_/_0.5)))] dark:bg-[var(--zui-dynamic-stepper-indicator-destructive-bg-current-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585_/_0.35)))] text-[color:var(--zui-dynamic-stepper-indicator-destructive-fg-current,var(--zui-status-error,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-destructive-fg-current-dark,var(--zui-status-error-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-destructive-ring-current,var(--zui-focus-ring,oklch(71.2%_0.194_13.428_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-destructive-ring-current-dark,var(--zui-focus-ring-dark,oklch(71.2%_0.194_13.428_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-destructive-border-upcoming,var(--zui-status-error,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-destructive-border-upcoming-dark,var(--zui-status-error-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-destructive-bg-upcoming,var(--zui-status-error,oklch(96.9%_0.015_12.422)))] dark:bg-[var(--zui-dynamic-stepper-indicator-destructive-bg-upcoming-dark,var(--zui-status-error-dark,oklch(27.1%_0.105_12.094_/_0.25)))] text-[color:var(--zui-dynamic-stepper-indicator-destructive-fg-upcoming,var(--zui-status-error,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-destructive-fg-upcoming-dark,var(--zui-status-error-dark,oklch(70.4%_0.04_256.788)))]",
  },
  outline: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-outline-border-complete,var(--zui-border,oklch(69.6%_0.17_162.48_/_0.55)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-outline-border-complete-dark,var(--zui-border-dark,oklch(69.6%_0.17_162.48_/_0.55)))] bg-[var(--zui-dynamic-stepper-indicator-outline-bg-complete,var(--zui-surface-soft,transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-outline-bg-complete-dark,var(--zui-surface-soft-dark,transparent))] text-[color:var(--zui-dynamic-stepper-indicator-outline-fg-complete,var(--zui-fg,oklch(90.5%_0.093_164.15)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-outline-fg-complete-dark,var(--zui-fg-dark,oklch(90.5%_0.093_164.15)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-outline-ring-complete,var(--zui-focus-ring,oklch(69.6%_0.17_162.48_/_0.25)))] dark:ring-[var(--zui-dynamic-stepper-indicator-outline-ring-complete-dark,var(--zui-focus-ring-dark,oklch(69.6%_0.17_162.48_/_0.25)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-outline-border-current,var(--zui-border,#0000004d))] dark:border-[color:var(--zui-dynamic-stepper-indicator-outline-border-current-dark,var(--zui-border-dark,#ffffff4d))] bg-[var(--zui-dynamic-stepper-indicator-outline-bg-current,var(--zui-surface-hover,#0000001a))] dark:bg-[var(--zui-dynamic-stepper-indicator-outline-bg-current-dark,var(--zui-surface-hover-dark,#ffffff1a))] text-[color:var(--zui-dynamic-stepper-indicator-outline-fg-current,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-outline-fg-current-dark,var(--zui-fg-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-outline-ring-current,var(--zui-focus-ring,#00000040))] dark:ring-[var(--zui-dynamic-stepper-indicator-outline-ring-current-dark,var(--zui-focus-ring-dark,#ffffff40))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-outline-border-upcoming,var(--zui-border,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-outline-border-upcoming-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-outline-bg-upcoming,var(--zui-surface-soft,#0000000d))] dark:bg-[var(--zui-dynamic-stepper-indicator-outline-bg-upcoming-dark,var(--zui-surface-soft-dark,#ffffff0d))] text-[color:var(--zui-dynamic-stepper-indicator-outline-fg-upcoming,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-outline-fg-upcoming-dark,var(--zui-fg-dark,oklch(70.4%_0.04_256.788)))]",
  },
  ghost: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-ghost-border-complete,var(--zui-border,transparent))] dark:border-[color:var(--zui-dynamic-stepper-indicator-ghost-border-complete-dark,var(--zui-border-dark,transparent))] bg-[var(--zui-dynamic-stepper-indicator-ghost-bg-complete,var(--zui-surface-soft,oklch(69.6%_0.17_162.48_/_0.15)))] dark:bg-[var(--zui-dynamic-stepper-indicator-ghost-bg-complete-dark,var(--zui-surface-soft-dark,oklch(69.6%_0.17_162.48_/_0.15)))] text-[color:var(--zui-dynamic-stepper-indicator-ghost-fg-complete,var(--zui-fg,oklch(90.5%_0.093_164.15)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-ghost-fg-complete-dark,var(--zui-fg-dark,oklch(90.5%_0.093_164.15)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-ghost-ring-complete,var(--zui-focus-ring,oklch(76.5%_0.177_163.223_/_0.2)))] dark:ring-[var(--zui-dynamic-stepper-indicator-ghost-ring-complete-dark,var(--zui-focus-ring-dark,oklch(76.5%_0.177_163.223_/_0.2)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-ghost-border-current,var(--zui-border,transparent))] dark:border-[color:var(--zui-dynamic-stepper-indicator-ghost-border-current-dark,var(--zui-border-dark,transparent))] bg-[var(--zui-dynamic-stepper-indicator-ghost-bg-current,var(--zui-surface-hover,#0000001a))] dark:bg-[var(--zui-dynamic-stepper-indicator-ghost-bg-current-dark,var(--zui-surface-hover-dark,#ffffff1a))] text-[color:var(--zui-dynamic-stepper-indicator-ghost-fg-current,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-ghost-fg-current-dark,var(--zui-fg-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-ghost-ring-current,var(--zui-focus-ring,#00000026))] dark:ring-[var(--zui-dynamic-stepper-indicator-ghost-ring-current-dark,var(--zui-focus-ring-dark,#ffffff26))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-ghost-border-upcoming,var(--zui-border,transparent))] dark:border-[color:var(--zui-dynamic-stepper-indicator-ghost-border-upcoming-dark,var(--zui-border-dark,transparent))] bg-[var(--zui-dynamic-stepper-indicator-ghost-bg-upcoming,transparent)] dark:bg-[var(--zui-dynamic-stepper-indicator-ghost-bg-upcoming-dark,transparent)] text-[color:var(--zui-dynamic-stepper-indicator-ghost-fg-upcoming,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-ghost-fg-upcoming-dark,var(--zui-fg-dark,oklch(55.4%_0.046_257.417)))]",
  },
  link: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-link-border-complete,var(--zui-border,oklch(71.5%_0.143_215.221_/_0.45)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-link-border-complete-dark,var(--zui-border-dark,oklch(71.5%_0.143_215.221_/_0.45)))] bg-[var(--zui-dynamic-stepper-indicator-link-bg-complete,var(--zui-surface-soft,oklch(98.4%_0.019_200.873)))] dark:bg-[var(--zui-dynamic-stepper-indicator-link-bg-complete-dark,var(--zui-surface-soft-dark,oklch(30.2%_0.056_229.695_/_0.35)))] text-[color:var(--zui-dynamic-stepper-indicator-link-fg-complete,var(--zui-fg,oklch(91.7%_0.08_205.041)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-link-fg-complete-dark,var(--zui-fg-dark,oklch(91.7%_0.08_205.041)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-link-ring-complete,var(--zui-focus-ring,oklch(78.9%_0.154_211.53_/_0.25)))] dark:ring-[var(--zui-dynamic-stepper-indicator-link-ring-complete-dark,var(--zui-focus-ring-dark,oklch(78.9%_0.154_211.53_/_0.25)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-link-border-current,var(--zui-border,oklch(60.9%_0.126_221.723)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-link-border-current-dark,var(--zui-border-dark,oklch(78.9%_0.154_211.53)))] bg-[var(--zui-dynamic-stepper-indicator-link-bg-current,var(--zui-surface-hover,oklch(39.8%_0.07_227.392_/_0.45)))] dark:bg-[var(--zui-dynamic-stepper-indicator-link-bg-current-dark,var(--zui-surface-hover-dark,oklch(39.8%_0.07_227.392_/_0.45)))] text-[color:var(--zui-dynamic-stepper-indicator-link-fg-current,var(--zui-fg,oklch(30.2%_0.056_229.695)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-link-fg-current-dark,var(--zui-fg-dark,oklch(98.4%_0.019_200.873)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-link-ring-current,var(--zui-focus-ring,oklch(78.9%_0.154_211.53_/_0.45)))] dark:ring-[var(--zui-dynamic-stepper-indicator-link-ring-current-dark,var(--zui-focus-ring-dark,oklch(78.9%_0.154_211.53_/_0.45)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-link-border-upcoming,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-dynamic-stepper-indicator-link-border-upcoming-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-dynamic-stepper-indicator-link-bg-upcoming,var(--zui-surface-soft,transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-link-bg-upcoming-dark,var(--zui-surface-soft-dark,transparent))] text-[color:var(--zui-dynamic-stepper-indicator-link-fg-upcoming,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-link-fg-upcoming-dark,var(--zui-fg-dark,oklch(55.4%_0.046_257.417)))]",
  },
  glass: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-glass-border-complete,var(--zui-border,#00000040))] dark:border-[color:var(--zui-dynamic-stepper-indicator-glass-border-complete-dark,var(--zui-border-dark,#ffffff40))] bg-[var(--zui-dynamic-stepper-indicator-glass-bg-complete,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-dynamic-stepper-indicator-glass-bg-complete-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-dynamic-stepper-indicator-glass-fg-complete,var(--zui-fg,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-glass-fg-complete-dark,var(--zui-fg-dark,oklch(95%_0.052_163.051)))] shadow-[var(--zui-dynamic-stepper-indicator-glass-shadow-complete,var(--zui-shadow,inset_0_1px_0_rgba(255,255,255,0.06)))] dark:shadow-[var(--zui-dynamic-stepper-indicator-glass-shadow-complete-dark,var(--zui-shadow-dark,inset_0_1px_0_rgba(255,255,255,0.06)))] backdrop-blur-md ring-2 ring-[var(--zui-dynamic-stepper-indicator-glass-ring-complete,var(--zui-focus-ring,oklch(76.5%_0.177_163.223_/_0.25)))] dark:ring-[var(--zui-dynamic-stepper-indicator-glass-ring-complete-dark,var(--zui-focus-ring-dark,oklch(76.5%_0.177_163.223_/_0.25)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-glass-border-current,var(--zui-border,#00000059))] dark:border-[color:var(--zui-dynamic-stepper-indicator-glass-border-current-dark,var(--zui-border-dark,#ffffff59))] bg-[var(--zui-dynamic-stepper-indicator-glass-bg-current,var(--zui-surface-hover,#00000026))] dark:bg-[var(--zui-dynamic-stepper-indicator-glass-bg-current-dark,var(--zui-surface-hover-dark,#ffffff26))] text-[color:var(--zui-dynamic-stepper-indicator-glass-fg-current,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-glass-fg-current-dark,var(--zui-fg-dark,#ffffff))] shadow-[var(--zui-dynamic-stepper-indicator-glass-shadow-current,var(--zui-shadow,inset_0_1px_0_rgba(255,255,255,0.08)))] dark:shadow-[var(--zui-dynamic-stepper-indicator-glass-shadow-current-dark,var(--zui-shadow-dark,inset_0_1px_0_rgba(255,255,255,0.08)))] backdrop-blur-md ring-2 ring-[var(--zui-dynamic-stepper-indicator-glass-ring-current,var(--zui-focus-ring,#0000004d))] dark:ring-[var(--zui-dynamic-stepper-indicator-glass-ring-current-dark,var(--zui-focus-ring-dark,#ffffff4d))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-glass-border-upcoming,var(--zui-border,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-glass-border-upcoming-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-glass-bg-upcoming,var(--zui-surface-soft,#0000000d))] dark:bg-[var(--zui-dynamic-stepper-indicator-glass-bg-upcoming-dark,var(--zui-surface-soft-dark,#ffffff0d))] text-[color:var(--zui-dynamic-stepper-indicator-glass-fg-upcoming,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-glass-fg-upcoming-dark,var(--zui-fg-dark,oklch(70.4%_0.04_256.788)))] backdrop-blur-sm",
  },
  emerald: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-emerald-border-complete,var(--zui-color-emerald,oklch(69.6%_0.17_162.48_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-emerald-border-complete-dark,var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-emerald-bg-complete,color-mix(in oklch, var(--zui-color-emerald,oklch(69.6%_0.17_162.48)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-emerald-bg-complete-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-emerald-fg-complete,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-emerald-fg-complete-dark,var(--zui-color-emerald-dark,oklch(95%_0.052_163.051)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-emerald-ring-complete,var(--zui-focus-ring,oklch(76.5%_0.177_163.223_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-emerald-ring-complete-dark,var(--zui-focus-ring-dark,oklch(76.5%_0.177_163.223_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-emerald-border-current,var(--zui-color-emerald,oklch(59.6%_0.145_163.225)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-emerald-border-current-dark,var(--zui-color-emerald-dark,oklch(76.5%_0.177_163.223)))] bg-[var(--zui-dynamic-stepper-indicator-emerald-bg-current,color-mix(in oklch, var(--zui-color-emerald,oklch(69.6%_0.17_162.48)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-emerald-bg-current-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-emerald-fg-current,var(--zui-color-emerald,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-emerald-fg-current-dark,var(--zui-color-emerald-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-emerald-ring-current,var(--zui-focus-ring,oklch(76.5%_0.177_163.223_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-emerald-ring-current-dark,var(--zui-focus-ring-dark,oklch(76.5%_0.177_163.223_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-emerald-border-upcoming,var(--zui-color-emerald,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-emerald-border-upcoming-dark,var(--zui-color-emerald-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-emerald-bg-upcoming,color-mix(in oklch, var(--zui-color-emerald,oklch(97.9%_0.021_166.113)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-emerald-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(26.2%_0.051_172.552)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-emerald-fg-upcoming,var(--zui-color-emerald,oklch(50.8%_0.118_165.612_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-emerald-fg-upcoming-dark,var(--zui-color-emerald-dark,oklch(50.8%_0.118_165.612_/_0.55)))]",
  },
  indigo: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-indigo-border-complete,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-indigo-border-complete-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-indigo-bg-complete,color-mix(in oklch, var(--zui-color-indigo,oklch(58.5%_0.233_277.117)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-indigo-bg-complete-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-indigo-fg-complete,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-indigo-fg-complete-dark,var(--zui-color-indigo-dark,oklch(93%_0.034_272.788)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-indigo-ring-complete,var(--zui-focus-ring,oklch(67.3%_0.182_276.935_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-indigo-ring-complete-dark,var(--zui-focus-ring-dark,oklch(67.3%_0.182_276.935_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-indigo-border-current,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-indigo-border-current-dark,var(--zui-color-indigo-dark,oklch(67.3%_0.182_276.935)))] bg-[var(--zui-dynamic-stepper-indicator-indigo-bg-current,color-mix(in oklch, var(--zui-color-indigo,oklch(58.5%_0.233_277.117)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-indigo-bg-current-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-indigo-fg-current,var(--zui-color-indigo,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-indigo-fg-current-dark,var(--zui-color-indigo-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-indigo-ring-current,var(--zui-focus-ring,oklch(67.3%_0.182_276.935_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-indigo-ring-current-dark,var(--zui-focus-ring-dark,oklch(67.3%_0.182_276.935_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-indigo-border-upcoming,var(--zui-color-indigo,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-indigo-border-upcoming-dark,var(--zui-color-indigo-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-indigo-bg-upcoming,color-mix(in oklch, var(--zui-color-indigo,oklch(96.2%_0.018_272.314)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-indigo-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-indigo-fg-upcoming,var(--zui-color-indigo,oklch(45.7%_0.24_277.023_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-indigo-fg-upcoming-dark,var(--zui-color-indigo-dark,oklch(45.7%_0.24_277.023_/_0.55)))]",
  },
  purple: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-purple-border-complete,var(--zui-color-purple,oklch(62.7%_0.265_303.9_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-purple-border-complete-dark,var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-purple-bg-complete,color-mix(in oklch, var(--zui-color-purple,oklch(62.7%_0.265_303.9)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-purple-bg-complete-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-purple-fg-complete,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-purple-fg-complete-dark,var(--zui-color-purple-dark,oklch(94.6%_0.033_307.174)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-purple-ring-complete,var(--zui-focus-ring,oklch(71.4%_0.203_305.504_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-purple-ring-complete-dark,var(--zui-focus-ring-dark,oklch(71.4%_0.203_305.504_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-purple-border-current,var(--zui-color-purple,oklch(55.8%_0.288_302.321)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-purple-border-current-dark,var(--zui-color-purple-dark,oklch(71.4%_0.203_305.504)))] bg-[var(--zui-dynamic-stepper-indicator-purple-bg-current,color-mix(in oklch, var(--zui-color-purple,oklch(62.7%_0.265_303.9)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-purple-bg-current-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-purple-fg-current,var(--zui-color-purple,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-purple-fg-current-dark,var(--zui-color-purple-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-purple-ring-current,var(--zui-focus-ring,oklch(71.4%_0.203_305.504_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-purple-ring-current-dark,var(--zui-focus-ring-dark,oklch(71.4%_0.203_305.504_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-purple-border-upcoming,var(--zui-color-purple,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-purple-border-upcoming-dark,var(--zui-color-purple-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-purple-bg-upcoming,color-mix(in oklch, var(--zui-color-purple,oklch(97.7%_0.014_308.299)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-purple-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-purple-fg-upcoming,var(--zui-color-purple,oklch(49.6%_0.265_301.924_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-purple-fg-upcoming-dark,var(--zui-color-purple-dark,oklch(49.6%_0.265_301.924_/_0.55)))]",
  },
  pink: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-pink-border-complete,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-pink-border-complete-dark,var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-pink-bg-complete,color-mix(in oklch, var(--zui-color-pink,oklch(65.6%_0.241_354.308)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-pink-bg-complete-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-pink-fg-complete,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-pink-fg-complete-dark,var(--zui-color-pink-dark,oklch(94.8%_0.028_342.258)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-pink-ring-complete,var(--zui-focus-ring,oklch(71.8%_0.202_349.761_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-pink-ring-complete-dark,var(--zui-focus-ring-dark,oklch(71.8%_0.202_349.761_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-pink-border-current,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-pink-border-current-dark,var(--zui-color-pink-dark,oklch(71.8%_0.202_349.761)))] bg-[var(--zui-dynamic-stepper-indicator-pink-bg-current,color-mix(in oklch, var(--zui-color-pink,oklch(65.6%_0.241_354.308)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-pink-bg-current-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-pink-fg-current,var(--zui-color-pink,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-pink-fg-current-dark,var(--zui-color-pink-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-pink-ring-current,var(--zui-focus-ring,oklch(71.8%_0.202_349.761_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-pink-ring-current-dark,var(--zui-focus-ring-dark,oklch(71.8%_0.202_349.761_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-pink-border-upcoming,var(--zui-color-pink,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-pink-border-upcoming-dark,var(--zui-color-pink-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-pink-bg-upcoming,color-mix(in oklch, var(--zui-color-pink,oklch(97.1%_0.014_343.198)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-pink-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-pink-fg-upcoming,var(--zui-color-pink,oklch(52.5%_0.223_3.958_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-pink-fg-upcoming-dark,var(--zui-color-pink-dark,oklch(52.5%_0.223_3.958_/_0.55)))]",
  },
  rose: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-rose-border-complete,var(--zui-color-rose,oklch(64.5%_0.246_16.439_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-rose-border-complete-dark,var(--zui-color-rose-dark,oklch(64.5%_0.246_16.439_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-rose-bg-complete,color-mix(in oklch, var(--zui-color-rose,oklch(64.5%_0.246_16.439)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-rose-bg-complete-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(64.5%_0.246_16.439)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-rose-fg-complete,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-rose-fg-complete-dark,var(--zui-color-rose-dark,oklch(94.1%_0.03_12.58)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-rose-ring-complete,var(--zui-focus-ring,oklch(71.2%_0.194_13.428_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-rose-ring-complete-dark,var(--zui-focus-ring-dark,oklch(71.2%_0.194_13.428_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-rose-border-current,var(--zui-color-rose,oklch(58.6%_0.253_17.585)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-rose-border-current-dark,var(--zui-color-rose-dark,oklch(71.2%_0.194_13.428)))] bg-[var(--zui-dynamic-stepper-indicator-rose-bg-current,color-mix(in oklch, var(--zui-color-rose,oklch(64.5%_0.246_16.439)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-rose-bg-current-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(64.5%_0.246_16.439)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-rose-fg-current,var(--zui-color-rose,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-rose-fg-current-dark,var(--zui-color-rose-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-rose-ring-current,var(--zui-focus-ring,oklch(71.2%_0.194_13.428_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-rose-ring-current-dark,var(--zui-focus-ring-dark,oklch(71.2%_0.194_13.428_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-rose-border-upcoming,var(--zui-color-rose,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-rose-border-upcoming-dark,var(--zui-color-rose-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-rose-bg-upcoming,color-mix(in oklch, var(--zui-color-rose,oklch(96.9%_0.015_12.422)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-rose-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-rose-fg-upcoming,var(--zui-color-rose,oklch(51.4%_0.222_16.935_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-rose-fg-upcoming-dark,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935_/_0.55)))]",
  },
  sky: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-sky-border-complete,var(--zui-color-sky,oklch(68.5%_0.169_237.323_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-sky-border-complete-dark,var(--zui-color-sky-dark,oklch(68.5%_0.169_237.323_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-sky-bg-complete,color-mix(in oklch, var(--zui-color-sky,oklch(68.5%_0.169_237.323)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-sky-bg-complete-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(68.5%_0.169_237.323)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-sky-fg-complete,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-sky-fg-complete-dark,var(--zui-color-sky-dark,oklch(95.1%_0.026_236.824)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-sky-ring-complete,var(--zui-focus-ring,oklch(74.6%_0.16_232.661_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-sky-ring-complete-dark,var(--zui-focus-ring-dark,oklch(74.6%_0.16_232.661_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-sky-border-current,var(--zui-color-sky,oklch(58.8%_0.158_241.966)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-sky-border-current-dark,var(--zui-color-sky-dark,oklch(74.6%_0.16_232.661)))] bg-[var(--zui-dynamic-stepper-indicator-sky-bg-current,color-mix(in oklch, var(--zui-color-sky,oklch(68.5%_0.169_237.323)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-sky-bg-current-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(68.5%_0.169_237.323)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-sky-fg-current,var(--zui-color-sky,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-sky-fg-current-dark,var(--zui-color-sky-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-sky-ring-current,var(--zui-focus-ring,oklch(74.6%_0.16_232.661_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-sky-ring-current-dark,var(--zui-focus-ring-dark,oklch(74.6%_0.16_232.661_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-sky-border-upcoming,var(--zui-color-sky,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-sky-border-upcoming-dark,var(--zui-color-sky-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-sky-bg-upcoming,color-mix(in oklch, var(--zui-color-sky,oklch(97.7%_0.013_236.62)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-sky-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(29.3%_0.066_243.157)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-sky-fg-upcoming,var(--zui-color-sky,oklch(50%_0.134_242.749_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-sky-fg-upcoming-dark,var(--zui-color-sky-dark,oklch(50%_0.134_242.749_/_0.55)))]",
  },
  teal: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-teal-border-complete,var(--zui-color-teal,oklch(70.4%_0.14_182.503_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-teal-border-complete-dark,var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-teal-bg-complete,color-mix(in oklch, var(--zui-color-teal,oklch(70.4%_0.14_182.503)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-teal-bg-complete-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-teal-fg-complete,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-teal-fg-complete-dark,var(--zui-color-teal-dark,oklch(95.3%_0.051_180.801)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-teal-ring-complete,var(--zui-focus-ring,oklch(77.7%_0.152_181.912_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-teal-ring-complete-dark,var(--zui-focus-ring-dark,oklch(77.7%_0.152_181.912_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-teal-border-current,var(--zui-color-teal,oklch(60%_0.118_184.704)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-teal-border-current-dark,var(--zui-color-teal-dark,oklch(77.7%_0.152_181.912)))] bg-[var(--zui-dynamic-stepper-indicator-teal-bg-current,color-mix(in oklch, var(--zui-color-teal,oklch(70.4%_0.14_182.503)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-teal-bg-current-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-teal-fg-current,var(--zui-color-teal,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-teal-fg-current-dark,var(--zui-color-teal-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-teal-ring-current,var(--zui-focus-ring,oklch(77.7%_0.152_181.912_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-teal-ring-current-dark,var(--zui-focus-ring-dark,oklch(77.7%_0.152_181.912_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-teal-border-upcoming,var(--zui-color-teal,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-teal-border-upcoming-dark,var(--zui-color-teal-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-teal-bg-upcoming,color-mix(in oklch, var(--zui-color-teal,oklch(98.4%_0.014_180.72)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-teal-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-teal-fg-upcoming,var(--zui-color-teal,oklch(51.1%_0.096_186.391_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-teal-fg-upcoming-dark,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391_/_0.55)))]",
  },
  yellow: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-yellow-border-complete,var(--zui-color-yellow,oklch(79.5%_0.184_86.047_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-yellow-border-complete-dark,var(--zui-color-yellow-dark,oklch(79.5%_0.184_86.047_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-yellow-bg-complete,color-mix(in oklch, var(--zui-color-yellow,oklch(79.5%_0.184_86.047)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-yellow-bg-complete-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(79.5%_0.184_86.047)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-yellow-fg-complete,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-yellow-fg-complete-dark,var(--zui-color-yellow-dark,oklch(97.3%_0.071_103.193)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-yellow-ring-complete,var(--zui-focus-ring,oklch(85.2%_0.199_91.936_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-yellow-ring-complete-dark,var(--zui-focus-ring-dark,oklch(85.2%_0.199_91.936_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-yellow-border-current,var(--zui-color-yellow,oklch(68.1%_0.162_75.834)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-yellow-border-current-dark,var(--zui-color-yellow-dark,oklch(85.2%_0.199_91.936)))] bg-[var(--zui-dynamic-stepper-indicator-yellow-bg-current,color-mix(in oklch, var(--zui-color-yellow,oklch(97.3%_0.071_103.193)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-yellow-bg-current-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-yellow-fg-current,var(--zui-color-yellow,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-yellow-fg-current-dark,var(--zui-color-yellow-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-yellow-ring-current,var(--zui-focus-ring,oklch(85.2%_0.199_91.936_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-yellow-ring-current-dark,var(--zui-focus-ring-dark,oklch(85.2%_0.199_91.936_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-yellow-border-upcoming,var(--zui-color-yellow,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-yellow-border-upcoming-dark,var(--zui-color-yellow-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-yellow-bg-upcoming,color-mix(in oklch, var(--zui-color-yellow,oklch(98.7%_0.026_102.212)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-yellow-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-yellow-fg-upcoming,var(--zui-color-yellow,oklch(55.4%_0.135_66.442_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-yellow-fg-upcoming-dark,var(--zui-color-yellow-dark,oklch(55.4%_0.135_66.442_/_0.55)))]",
  },
  orange: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-orange-border-complete,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-orange-border-complete-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-orange-bg-complete,color-mix(in oklch, var(--zui-color-orange,oklch(70.5%_0.213_47.604)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-orange-bg-complete-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-orange-fg-complete,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-orange-fg-complete-dark,var(--zui-color-orange-dark,oklch(95.4%_0.038_75.164)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-orange-ring-complete,var(--zui-focus-ring,oklch(75%_0.183_55.934_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-orange-ring-complete-dark,var(--zui-focus-ring-dark,oklch(75%_0.183_55.934_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-orange-border-current,var(--zui-color-orange,oklch(64.6%_0.222_41.116)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-orange-border-current-dark,var(--zui-color-orange-dark,oklch(75%_0.183_55.934)))] bg-[var(--zui-dynamic-stepper-indicator-orange-bg-current,color-mix(in oklch, var(--zui-color-orange,oklch(95.4%_0.038_75.164)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-orange-bg-current-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-orange-fg-current,var(--zui-color-orange,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-orange-fg-current-dark,var(--zui-color-orange-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-orange-ring-current,var(--zui-focus-ring,oklch(75%_0.183_55.934_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-orange-ring-current-dark,var(--zui-focus-ring-dark,oklch(75%_0.183_55.934_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-orange-border-upcoming,var(--zui-color-orange,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-orange-border-upcoming-dark,var(--zui-color-orange-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-orange-bg-upcoming,color-mix(in oklch, var(--zui-color-orange,oklch(98%_0.016_73.684)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-orange-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-orange-fg-upcoming,var(--zui-color-orange,oklch(55.3%_0.195_38.402_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-orange-fg-upcoming-dark,var(--zui-color-orange-dark,oklch(55.3%_0.195_38.402_/_0.55)))]",
  },
  gray: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-gray-border-complete,var(--zui-color-gray,oklch(55.1%_0.027_264.364_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-gray-border-complete-dark,var(--zui-color-gray-dark,oklch(55.1%_0.027_264.364_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-gray-bg-complete,color-mix(in oklch, var(--zui-color-gray,oklch(55.1%_0.027_264.364)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-gray-bg-complete-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(55.1%_0.027_264.364)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-gray-fg-complete,var(--zui-color-gray,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-gray-fg-complete-dark,var(--zui-color-gray-dark,oklch(96.7%_0.003_264.542)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-gray-ring-complete,var(--zui-focus-ring,oklch(70.7%_0.022_261.325_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-gray-ring-complete-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-gray-border-current,var(--zui-color-gray,oklch(44.6%_0.03_256.802)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-gray-border-current-dark,var(--zui-color-gray-dark,oklch(70.7%_0.022_261.325)))] bg-[var(--zui-dynamic-stepper-indicator-gray-bg-current,color-mix(in oklch, var(--zui-color-gray,oklch(96.7%_0.003_264.542)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-gray-bg-current-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-gray-fg-current,var(--zui-color-gray,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-gray-fg-current-dark,var(--zui-color-gray-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-gray-ring-current,var(--zui-focus-ring,oklch(70.7%_0.022_261.325_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-gray-ring-current-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-gray-border-upcoming,var(--zui-color-gray,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-gray-border-upcoming-dark,var(--zui-color-gray-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-gray-bg-upcoming,color-mix(in oklch, var(--zui-color-gray,oklch(98.5%_0.002_247.839)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-gray-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(13%_0.028_261.692)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-gray-fg-upcoming,var(--zui-color-gray,oklch(87.2%_0.01_258.338_/_0.7)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-gray-fg-upcoming-dark,var(--zui-color-gray-dark,oklch(87.2%_0.01_258.338_/_0.7)))]",
  },
  amber: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-amber-border-complete,var(--zui-color-amber,oklch(76.9%_0.188_70.08_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-amber-border-complete-dark,var(--zui-color-amber-dark,oklch(76.9%_0.188_70.08_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-amber-bg-complete,color-mix(in oklch, var(--zui-color-amber,oklch(76.9%_0.188_70.08)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-amber-bg-complete-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(76.9%_0.188_70.08)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-amber-fg-complete,var(--zui-color-amber,oklch(41.4%_0.112_45.904)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-amber-fg-complete-dark,var(--zui-color-amber-dark,oklch(96.2%_0.059_95.617)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-amber-ring-complete,var(--zui-focus-ring,oklch(82.8%_0.189_84.429_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-amber-ring-complete-dark,var(--zui-focus-ring-dark,oklch(82.8%_0.189_84.429_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-amber-border-current,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-amber-border-current-dark,var(--zui-color-amber-dark,oklch(82.8%_0.189_84.429)))] bg-[var(--zui-dynamic-stepper-indicator-amber-bg-current,color-mix(in oklch, var(--zui-color-amber,oklch(96.2%_0.059_95.617)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-amber-bg-current-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-amber-fg-current,var(--zui-color-amber,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-amber-fg-current-dark,var(--zui-color-amber-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-amber-ring-current,var(--zui-focus-ring,oklch(82.8%_0.189_84.429_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-amber-ring-current-dark,var(--zui-focus-ring-dark,oklch(82.8%_0.189_84.429_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-amber-border-upcoming,var(--zui-color-amber,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-amber-border-upcoming-dark,var(--zui-color-amber-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-amber-bg-upcoming,color-mix(in oklch, var(--zui-color-amber,oklch(98.7%_0.022_95.277)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-amber-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(27.9%_0.077_45.635)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-amber-fg-upcoming,var(--zui-color-amber,oklch(55.5%_0.163_48.998_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-amber-fg-upcoming-dark,var(--zui-color-amber-dark,oklch(55.5%_0.163_48.998_/_0.55)))]",
  },
  violet: {
    complete:
      "border-[color:var(--zui-dynamic-stepper-indicator-violet-border-complete,var(--zui-color-violet,oklch(60.6%_0.25_292.717_/_0.6)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-violet-border-complete-dark,var(--zui-color-violet-dark,oklch(60.6%_0.25_292.717_/_0.6)))] bg-[var(--zui-dynamic-stepper-indicator-violet-bg-complete,color-mix(in oklch, var(--zui-color-violet,oklch(60.6%_0.25_292.717)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-violet-bg-complete-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(60.6%_0.25_292.717)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-violet-fg-complete,var(--zui-color-violet,oklch(38%_0.189_293.745)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-violet-fg-complete-dark,var(--zui-color-violet-dark,oklch(94.3%_0.029_294.588)))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-violet-ring-complete,var(--zui-focus-ring,oklch(70.2%_0.183_293.541_/_0.3)))] dark:ring-[var(--zui-dynamic-stepper-indicator-violet-ring-complete-dark,var(--zui-focus-ring-dark,oklch(70.2%_0.183_293.541_/_0.3)))]",
    current:
      "border-[color:var(--zui-dynamic-stepper-indicator-violet-border-current,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] dark:border-[color:var(--zui-dynamic-stepper-indicator-violet-border-current-dark,var(--zui-color-violet-dark,oklch(70.2%_0.183_293.541)))] bg-[var(--zui-dynamic-stepper-indicator-violet-bg-current,color-mix(in oklch, var(--zui-color-violet,oklch(60.6%_0.25_292.717)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-violet-bg-current-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(60.6%_0.25_292.717)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-violet-fg-current,var(--zui-color-violet,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-violet-fg-current-dark,var(--zui-color-violet-dark,#ffffff))] ring-2 ring-[var(--zui-dynamic-stepper-indicator-violet-ring-current,var(--zui-focus-ring,oklch(70.2%_0.183_293.541_/_0.5)))] dark:ring-[var(--zui-dynamic-stepper-indicator-violet-ring-current-dark,var(--zui-focus-ring-dark,oklch(70.2%_0.183_293.541_/_0.5)))]",
    upcoming:
      "border-[color:var(--zui-dynamic-stepper-indicator-violet-border-upcoming,var(--zui-color-violet,#00000026))] dark:border-[color:var(--zui-dynamic-stepper-indicator-violet-border-upcoming-dark,var(--zui-color-violet-dark,#ffffff26))] bg-[var(--zui-dynamic-stepper-indicator-violet-bg-upcoming,color-mix(in oklch, var(--zui-color-violet,oklch(96.9%_0.016_293.756)) 10%, transparent))] dark:bg-[var(--zui-dynamic-stepper-indicator-violet-bg-upcoming-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(28.3%_0.141_291.089)) 18%, transparent))] text-[color:var(--zui-dynamic-stepper-indicator-violet-fg-upcoming,var(--zui-color-violet,oklch(49.1%_0.27_292.581_/_0.55)))] dark:text-[color:var(--zui-dynamic-stepper-indicator-violet-fg-upcoming-dark,var(--zui-color-violet-dark,oklch(49.1%_0.27_292.581_/_0.55)))]",
  },
} as const satisfies Record<
  string,
  Record<ZuiDynamicStepperIndicatorSemanticState, string>
>;

export type ZuiDynamicStepperIndicatorToneAppearance =
  keyof typeof zuiDynamicStepperIndicatorToneClasses;

export const zuiDynamicStepperRootBase = "flex w-full";

export const zuiDynamicStepperRootOrientations = {
  horizontal:
    "flex-row flex-wrap items-start justify-between gap-4 md:flex-nowrap md:items-center",
  vertical: "flex-col gap-6",
} as const;

export const zuiDynamicStepperMapperBase = "m-0 min-w-0 flex-1 list-none p-0";

export const zuiDynamicStepperMapperOrientations = {
  horizontal: "flex flex-row flex-wrap items-start justify-center gap-4",
  vertical: "flex flex-col gap-6",
} as const;

export const zuiDynamicStepperItemBase = "relative flex gap-3";

export const zuiDynamicStepperItemOrientations = {
  horizontal: "min-w-0 flex-col items-center text-center",
  vertical: "flex-row items-start text-left",
} as const;

export const zuiDynamicStepperIndicatorBase =
  "grid size-9 shrink-0 place-items-center rounded-full border text-sm font-semibold transition-colors";

export const zuiDynamicStepperIndicatorSizes = {
  sm: "size-8 text-xs",
  md: "size-9 text-sm",
  lg: "size-10 text-base",
} as const;
