export const zuiEmptyStateBase =
  "flex w-full flex-col items-center text-center";

export const zuiEmptyStateSizes = {
  sm: "gap-2 p-4 text-sm",
  md: "gap-3 p-6 text-sm",
  lg: "gap-4 p-8 text-base",
} as const;

export const zuiEmptyStateAppearances = {
  default:
    "text-[color:var(--zui-empty-state-default-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-empty-state-default-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))]",
  ghost:
    "text-[color:var(--zui-empty-state-ghost-fg,var(--zui-fg,oklch(37.2%_0.044_257.287)))] dark:text-[color:var(--zui-empty-state-ghost-fg-dark,var(--zui-fg-dark,oklch(92.9%_0.013_255.508)))]",
  card: "rounded-2xl border border-[color:var(--zui-empty-state-card-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-empty-state-card-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-empty-state-card-bg,var(--zui-surface-soft,#ffffffe6))] dark:bg-[var(--zui-empty-state-card-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] p-8 text-[color:var(--zui-empty-state-card-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-empty-state-card-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] shadow-[var(--zui-empty-state-card-shadow,var(--zui-shadow,0_8px_24px_rgba(15,23,42,0.12)))] dark:shadow-[var(--zui-empty-state-card-shadow-dark,var(--zui-shadow-dark,0_18px_48px_rgba(15,23,42,0.35)))]",
  blue: "border border-[color:var(--zui-empty-state-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-empty-state-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-empty-state-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:bg-[var(--zui-empty-state-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))] text-[color:var(--zui-empty-state-blue-fg,var(--zui-color-blue,#0f172a))] dark:text-[color:var(--zui-empty-state-blue-fg-dark,var(--zui-color-blue-dark,#f8fafc))]",
  cyan: "border border-[color:var(--zui-empty-state-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-empty-state-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-empty-state-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:bg-[var(--zui-empty-state-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))] text-[color:var(--zui-empty-state-cyan-fg,var(--zui-color-cyan,#0f172a))] dark:text-[color:var(--zui-empty-state-cyan-fg-dark,var(--zui-color-cyan-dark,#f8fafc))]",
  green:
    "border border-[color:var(--zui-empty-state-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-empty-state-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-empty-state-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:bg-[var(--zui-empty-state-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))] text-[color:var(--zui-empty-state-green-fg,var(--zui-color-green,#0f172a))] dark:text-[color:var(--zui-empty-state-green-fg-dark,var(--zui-color-green-dark,#f8fafc))]",
  lime: "border border-[color:var(--zui-empty-state-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-empty-state-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-empty-state-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:bg-[var(--zui-empty-state-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))] text-[color:var(--zui-empty-state-lime-fg,var(--zui-color-lime,#0f172a))] dark:text-[color:var(--zui-empty-state-lime-fg-dark,var(--zui-color-lime-dark,#f8fafc))]",
  mint: "border border-[color:var(--zui-empty-state-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-empty-state-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-empty-state-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:bg-[var(--zui-empty-state-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))] text-[color:var(--zui-empty-state-mint-fg,var(--zui-color-mint,#0f172a))] dark:text-[color:var(--zui-empty-state-mint-fg-dark,var(--zui-color-mint-dark,#f8fafc))]",
  ocean:
    "border border-[color:var(--zui-empty-state-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-empty-state-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-empty-state-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:bg-[var(--zui-empty-state-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-empty-state-ocean-fg,var(--zui-color-ocean,#0f172a))] dark:text-[color:var(--zui-empty-state-ocean-fg-dark,var(--zui-color-ocean-dark,#f8fafc))]",
  sapphire:
    "border border-[color:var(--zui-empty-state-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-empty-state-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-empty-state-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:bg-[var(--zui-empty-state-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))] text-[color:var(--zui-empty-state-sapphire-fg,var(--zui-color-sapphire,#0f172a))] dark:text-[color:var(--zui-empty-state-sapphire-fg-dark,var(--zui-color-sapphire-dark,#f8fafc))]",
  lavender:
    "border border-[color:var(--zui-empty-state-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-empty-state-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-empty-state-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:bg-[var(--zui-empty-state-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))] text-[color:var(--zui-empty-state-lavender-fg,var(--zui-color-lavender,#0f172a))] dark:text-[color:var(--zui-empty-state-lavender-fg-dark,var(--zui-color-lavender-dark,#f8fafc))]",
  ruby: "border border-[color:var(--zui-empty-state-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-empty-state-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-empty-state-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:bg-[var(--zui-empty-state-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))] text-[color:var(--zui-empty-state-ruby-fg,var(--zui-color-ruby,#0f172a))] dark:text-[color:var(--zui-empty-state-ruby-fg-dark,var(--zui-color-ruby-dark,#f8fafc))]",
  red: "border border-[color:var(--zui-empty-state-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-empty-state-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-empty-state-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:bg-[var(--zui-empty-state-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))] text-[color:var(--zui-empty-state-red-fg,var(--zui-color-red,#0f172a))] dark:text-[color:var(--zui-empty-state-red-fg-dark,var(--zui-color-red-dark,#f8fafc))]",
  slate:
    "border border-[color:var(--zui-empty-state-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-empty-state-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-empty-state-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:bg-[var(--zui-empty-state-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))] text-[color:var(--zui-empty-state-slate-fg,var(--zui-color-slate,#0f172a))] dark:text-[color:var(--zui-empty-state-slate-fg-dark,var(--zui-color-slate-dark,#f8fafc))]",
  zinc: "border border-[color:var(--zui-empty-state-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-empty-state-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-empty-state-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:bg-[var(--zui-empty-state-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))] text-[color:var(--zui-empty-state-zinc-fg,var(--zui-color-zinc,#0f172a))] dark:text-[color:var(--zui-empty-state-zinc-fg-dark,var(--zui-color-zinc-dark,#f8fafc))]",
  stone:
    "border border-[color:var(--zui-empty-state-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-empty-state-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-empty-state-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:bg-[var(--zui-empty-state-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))] text-[color:var(--zui-empty-state-stone-fg,var(--zui-color-stone,#0f172a))] dark:text-[color:var(--zui-empty-state-stone-fg-dark,var(--zui-color-stone-dark,#f8fafc))]",
  royal:
    "border border-[color:var(--zui-empty-state-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-empty-state-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-empty-state-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:bg-[var(--zui-empty-state-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))] text-[color:var(--zui-empty-state-royal-fg,var(--zui-color-royal,#0f172a))] dark:text-[color:var(--zui-empty-state-royal-fg-dark,var(--zui-color-royal-dark,#f8fafc))]",
  electric:
    "border border-[color:var(--zui-empty-state-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-empty-state-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-empty-state-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:bg-[var(--zui-empty-state-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-empty-state-electric-fg,var(--zui-color-electric,#0f172a))] dark:text-[color:var(--zui-empty-state-electric-fg-dark,var(--zui-color-electric-dark,#f8fafc))]",
  forest:
    "border border-[color:var(--zui-empty-state-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-empty-state-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-empty-state-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:bg-[var(--zui-empty-state-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))] text-[color:var(--zui-empty-state-forest-fg,var(--zui-color-forest,#0f172a))] dark:text-[color:var(--zui-empty-state-forest-fg-dark,var(--zui-color-forest-dark,#f8fafc))]",
  sunset:
    "border border-[color:var(--zui-empty-state-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-empty-state-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-empty-state-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:bg-[var(--zui-empty-state-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))] text-[color:var(--zui-empty-state-sunset-fg,var(--zui-color-sunset,#0f172a))] dark:text-[color:var(--zui-empty-state-sunset-fg-dark,var(--zui-color-sunset-dark,#f8fafc))]",
  magenta:
    "border border-[color:var(--zui-empty-state-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-empty-state-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-empty-state-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:bg-[var(--zui-empty-state-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))] text-[color:var(--zui-empty-state-magenta-fg,var(--zui-color-magenta,#0f172a))] dark:text-[color:var(--zui-empty-state-magenta-fg-dark,var(--zui-color-magenta-dark,#f8fafc))]",
  crimson:
    "border border-[color:var(--zui-empty-state-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-empty-state-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-empty-state-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:bg-[var(--zui-empty-state-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))] text-[color:var(--zui-empty-state-crimson-fg,var(--zui-color-crimson,#0f172a))] dark:text-[color:var(--zui-empty-state-crimson-fg-dark,var(--zui-color-crimson-dark,#f8fafc))]",
  aqua: "border border-[color:var(--zui-empty-state-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-empty-state-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-empty-state-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:bg-[var(--zui-empty-state-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))] text-[color:var(--zui-empty-state-aqua-fg,var(--zui-color-aqua,#0f172a))] dark:text-[color:var(--zui-empty-state-aqua-fg-dark,var(--zui-color-aqua-dark,#f8fafc))]",
  plum: "border border-[color:var(--zui-empty-state-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-empty-state-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-empty-state-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:bg-[var(--zui-empty-state-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))] text-[color:var(--zui-empty-state-plum-fg,var(--zui-color-plum,#0f172a))] dark:text-[color:var(--zui-empty-state-plum-fg-dark,var(--zui-color-plum-dark,#f8fafc))]",
} as const;

export const zuiEmptyStateAlignments = {
  start: "items-start text-left",
  center: "items-center text-center",
  end: "items-end text-right",
} as const;

export const zuiEmptyStateTitleBase = "font-semibold tracking-tight";

export const zuiEmptyStateTitleSizes = {
  sm: "text-base",
  md: "text-lg",
  lg: "text-xl",
} as const;

export const zuiEmptyStateDescriptionBase =
  "max-w-md text-[color:var(--zui-empty-state-description-fg,var(--zui-fg-muted,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-empty-state-description-fg-dark,var(--zui-fg-muted-dark,oklch(70.4%_0.04_256.788)))]";

export const zuiEmptyStateDescriptionSizes = {
  sm: "text-xs",
  md: "text-sm",
  lg: "text-base",
} as const;
