export const zuiInputBase = [
  "w-full min-w-0 rounded-xl border bg-[var(--zui-input-bg,#0000000d)] dark:bg-[var(--zui-input-bg-dark,#ffffff0d)] text-[color:var(--zui-input-fg,oklch(20.8%_0.042_265.755))] dark:text-[color:var(--zui-input-fg-dark,oklch(98.4%_0.003_247.858))] shadow-[var(--zui-input-shadow,0_1px_2px_rgba(15,23,42,0.08))] dark:shadow-[var(--zui-input-shadow-dark,0_1px_2px_rgba(15,23,42,0.12))]",
  "ring-offset-[var(--zui-input-ring-offset,oklch(98.4%_0.003_247.858))] dark:ring-offset-[var(--zui-input-ring-offset-dark,oklch(12.9%_0.042_264.695))] transition-colors",
  "placeholder:text-[color:var(--zui-input-placeholder-fg,oklch(55.4%_0.046_257.417))] dark:placeholder:text-[color:var(--zui-input-placeholder-fg-dark,oklch(55.4%_0.046_257.417))]",
  "focus-visible:outline-none",
  "disabled:cursor-not-allowed disabled:opacity-50",
  "read-only:cursor-default read-only:bg-[var(--zui-input-bg-read-only,#00000008)] dark:read-only:bg-[var(--zui-input-bg-read-only-dark,#ffffff08)] dark:bg-[var(--zui-input-bg-dark,#ffffff08)]",
  "file:h-8",
] as const;

export const zuiInputAs = {
  input: "",
  textarea: "h-auto! resize-y py-2 align-top",
  file: [
    "p-0! cursor-pointer",
    "file:cursor-pointer file:border-0 file:border-r file:border-[color:var(--zui-input-file-border,#0000001a)] dark:file:border-[color:var(--zui-input-file-border-dark,#ffffff1a)]",
    "file:bg-[var(--zui-input-file-bg,#0000001a)] dark:file:bg-[var(--zui-input-file-bg-dark,#ffffff1a)] file:text-[color:var(--zui-input-file-fg,oklch(37.2%_0.044_257.287))] dark:file:text-[color:var(--zui-input-file-fg-dark,oklch(92.9%_0.013_255.508))] file:font-medium",
    "file:transition-colors file:duration-200",
    "hover:file:bg-[var(--zui-input-file-bg-hover,#00000026)] dark:hover:file:bg-[var(--zui-input-file-bg-hover-dark,#ffffff26)]",
    "[&:not(:disabled)]:file:hover:text-[color:var(--zui-input-file-fg-hover,#ffffff)] dark:[&:not(:disabled)]:file:hover:text-[color:var(--zui-input-file-fg-hover-dark,#ffffff)]",
    "disabled:file:cursor-not-allowed",
  ],
  checkbox: [
    "shrink-0 cursor-pointer appearance-none relative",
    "min-h-0! shadow-none outline-none",
    "border-2 border-[color:var(--zui-input-checkbox-border,#0000004d)] dark:border-[color:var(--zui-input-checkbox-border-dark,#ffffff4d)] [&:not(:checked)]:bg-[var(--zui-input-checkbox-bg,transparent)] dark:[&:not(:checked)]:bg-[var(--zui-input-checkbox-bg-dark,transparent)]",
    "transition-[color,box-shadow,border-color,background-color]",
    "disabled:cursor-not-allowed disabled:opacity-50",
    "read-only:cursor-default",
    "checked:after:absolute checked:after:content-[''] checked:after:size-3 checked:after:top-1/2 checked:after:left-1/2 checked:after:-translate-x-1/2 checked:after:-translate-y-1/2 checked:after:rounded-full checked:after:bg-current",
  ],
  radio: [
    "shrink-0 cursor-pointer appearance-none rounded-full",
    "min-h-0! shadow-none outline-none",
    "border-2 border-[color:var(--zui-input-radio-border,#0000004d)] dark:border-[color:var(--zui-input-radio-border-dark,#ffffff4d)] bg-[var(--zui-input-radio-bg,transparent)]! dark:bg-[var(--zui-input-radio-bg-dark,transparent)]! read-only:bg-[var(--zui-input-radio-bg-read-only,transparent)]! dark:read-only:bg-[var(--zui-input-radio-bg-read-only-dark,transparent)]!",
    "ring-2 ring-[var(--zui-input-radio-ring,#00000033)] dark:ring-[var(--zui-input-radio-ring-dark,#ffffff33)] ring-offset-2 ring-offset-[var(--zui-input-radio-ring-offset,oklch(98.4%_0.003_247.858))] dark:ring-offset-[var(--zui-input-radio-ring-offset-dark,oklch(12.9%_0.042_264.695))]",
    "transition-[color,box-shadow,background-color,border-color,box-shadow]",
    "disabled:cursor-not-allowed disabled:opacity-50",
    "read-only:cursor-default",
  ],
  date: "w-auto shrink-0",
} as const;

export const zuiInputAppearances = {
  default:
    "border-[color:var(--zui-input-default-border,#0000001a)] dark:border-[color:var(--zui-input-default-border-dark,#ffffff1a)] focus-visible:border-[color:var(--zui-input-default-border-focus,#00000033)] dark:focus-visible:border-[color:var(--zui-input-default-border-focus-dark,#ffffff33)]",
  warning:
    "border-[color:var(--zui-input-warning-border,oklch(79.5%_0.184_86.047_/_0.8))] dark:border-[color:var(--zui-input-warning-border-dark,oklch(79.5%_0.184_86.047_/_0.8))] text-[color:var(--zui-input-warning-fg,oklch(28.6%_0.066_53.813))] dark:text-[color:var(--zui-input-warning-fg-dark,oklch(98.7%_0.026_102.212))] placeholder:text-[color:var(--zui-input-warning-placeholder-fg,oklch(47.6%_0.114_61.907))] dark:placeholder:text-[color:var(--zui-input-warning-placeholder-fg-dark,oklch(90.5%_0.182_98.111_/_0.7))] focus-visible:border-[color:var(--zui-input-warning-border-focus,oklch(68.1%_0.162_75.834))] dark:focus-visible:border-[color:var(--zui-input-warning-border-focus-dark,oklch(85.2%_0.199_91.936))] focus-visible:ring-[var(--zui-input-warning-ring-focus,oklch(85.2%_0.199_91.936_/_0.8))] dark:focus-visible:ring-[var(--zui-input-warning-ring-focus-dark,oklch(85.2%_0.199_91.936_/_0.8))]",
  error:
    "border-[color:var(--zui-input-error-border,oklch(64.5%_0.246_16.439_/_0.8))] dark:border-[color:var(--zui-input-error-border-dark,oklch(64.5%_0.246_16.439_/_0.8))] text-[color:var(--zui-input-error-fg,oklch(27.1%_0.105_12.094))] dark:text-[color:var(--zui-input-error-fg-dark,oklch(96.9%_0.015_12.422))] placeholder:text-[color:var(--zui-input-error-placeholder-fg,oklch(45.5%_0.188_13.697))] dark:placeholder:text-[color:var(--zui-input-error-placeholder-fg-dark,oklch(81%_0.117_11.638_/_0.7))] focus-visible:border-[color:var(--zui-input-error-border-focus,oklch(58.6%_0.253_17.585))] dark:focus-visible:border-[color:var(--zui-input-error-border-focus-dark,oklch(71.2%_0.194_13.428))] focus-visible:ring-[var(--zui-input-error-ring-focus,oklch(71.2%_0.194_13.428_/_0.8))] dark:focus-visible:ring-[var(--zui-input-error-ring-focus-dark,oklch(71.2%_0.194_13.428_/_0.8))]",
  success:
    "border-[color:var(--zui-input-success-border,oklch(69.6%_0.17_162.48_/_0.7))] dark:border-[color:var(--zui-input-success-border-dark,oklch(69.6%_0.17_162.48_/_0.7))] text-[color:var(--zui-input-success-fg,oklch(26.2%_0.051_172.552))] dark:text-[color:var(--zui-input-success-fg-dark,oklch(97.9%_0.021_166.113))] placeholder:text-[color:var(--zui-input-success-placeholder-fg,oklch(43.2%_0.095_166.913))] dark:placeholder:text-[color:var(--zui-input-success-placeholder-fg-dark,oklch(84.5%_0.143_164.978_/_0.7))] focus-visible:border-[color:var(--zui-input-success-border-focus,oklch(59.6%_0.145_163.225))] dark:focus-visible:border-[color:var(--zui-input-success-border-focus-dark,oklch(76.5%_0.177_163.223))] focus-visible:ring-[var(--zui-input-success-ring-focus,oklch(76.5%_0.177_163.223_/_0.8))] dark:focus-visible:ring-[var(--zui-input-success-ring-focus-dark,oklch(76.5%_0.177_163.223_/_0.8))]",
  info: "border-[color:var(--zui-input-info-border,oklch(62.3%_0.214_259.815_/_0.8))] dark:border-[color:var(--zui-input-info-border-dark,oklch(62.3%_0.214_259.815_/_0.8))] text-[color:var(--zui-input-info-fg,oklch(28.2%_0.091_267.935))] dark:text-[color:var(--zui-input-info-fg-dark,oklch(97%_0.014_254.604))] placeholder:text-[color:var(--zui-input-info-placeholder-fg,oklch(42.4%_0.199_265.638))] dark:placeholder:text-[color:var(--zui-input-info-placeholder-fg-dark,oklch(80.9%_0.105_251.813_/_0.7))] focus-visible:border-[color:var(--zui-input-info-border-focus,oklch(54.6%_0.245_262.881))] dark:focus-visible:border-[color:var(--zui-input-info-border-focus-dark,oklch(70.7%_0.165_254.624))] focus-visible:ring-[var(--zui-input-info-ring-focus,oklch(70.7%_0.165_254.624_/_0.8))] dark:focus-visible:ring-[var(--zui-input-info-ring-focus-dark,oklch(70.7%_0.165_254.624_/_0.8))]",
  violet:
    "border-[color:var(--zui-input-violet-border,oklch(60.6%_0.25_292.717_/_0.8))] dark:border-[color:var(--zui-input-violet-border-dark,oklch(60.6%_0.25_292.717_/_0.8))] text-[color:var(--zui-input-violet-fg,oklch(28.3%_0.141_291.089))] dark:text-[color:var(--zui-input-violet-fg-dark,oklch(96.9%_0.016_293.756))] placeholder:text-[color:var(--zui-input-violet-placeholder-fg,oklch(43.2%_0.232_292.759))] dark:placeholder:text-[color:var(--zui-input-violet-placeholder-fg-dark,oklch(81.1%_0.111_293.571_/_0.7))] focus-visible:border-[color:var(--zui-input-violet-border-focus,oklch(54.1%_0.281_293.009))] dark:focus-visible:border-[color:var(--zui-input-violet-border-focus-dark,oklch(70.2%_0.183_293.541))] focus-visible:ring-[var(--zui-input-violet-ring-focus,oklch(70.2%_0.183_293.541_/_0.8))] dark:focus-visible:ring-[var(--zui-input-violet-ring-focus-dark,oklch(70.2%_0.183_293.541_/_0.8))]",
  amber:
    "border-[color:var(--zui-input-amber-border,oklch(76.9%_0.188_70.08_/_0.8))] dark:border-[color:var(--zui-input-amber-border-dark,oklch(76.9%_0.188_70.08_/_0.8))] text-[color:var(--zui-input-amber-fg,oklch(27.9%_0.077_45.635))] dark:text-[color:var(--zui-input-amber-fg-dark,oklch(98.7%_0.022_95.277))] placeholder:text-[color:var(--zui-input-amber-placeholder-fg,oklch(47.3%_0.137_46.201))] dark:placeholder:text-[color:var(--zui-input-amber-placeholder-fg-dark,oklch(87.9%_0.169_91.605_/_0.7))] focus-visible:border-[color:var(--zui-input-amber-border-focus,oklch(66.6%_0.179_58.318))] dark:focus-visible:border-[color:var(--zui-input-amber-border-focus-dark,oklch(82.8%_0.189_84.429))] focus-visible:ring-[var(--zui-input-amber-ring-focus,oklch(82.8%_0.189_84.429_/_0.8))] dark:focus-visible:ring-[var(--zui-input-amber-ring-focus-dark,oklch(82.8%_0.189_84.429_/_0.8))]",
  pink: "border-[color:var(--zui-input-pink-border,oklch(65.6%_0.241_354.308_/_0.8))] dark:border-[color:var(--zui-input-pink-border-dark,oklch(65.6%_0.241_354.308_/_0.8))] text-[color:var(--zui-input-pink-fg,oklch(28.4%_0.109_3.907))] dark:text-[color:var(--zui-input-pink-fg-dark,oklch(97.1%_0.014_343.198))] placeholder:text-[color:var(--zui-input-pink-placeholder-fg,oklch(45.9%_0.187_3.815))] dark:placeholder:text-[color:var(--zui-input-pink-placeholder-fg-dark,oklch(82.3%_0.12_346.018_/_0.7))] focus-visible:border-[color:var(--zui-input-pink-border-focus,oklch(59.2%_0.249_0.584))] dark:focus-visible:border-[color:var(--zui-input-pink-border-focus-dark,oklch(71.8%_0.202_349.761))] focus-visible:ring-[var(--zui-input-pink-ring-focus,oklch(71.8%_0.202_349.761_/_0.8))] dark:focus-visible:ring-[var(--zui-input-pink-ring-focus-dark,oklch(71.8%_0.202_349.761_/_0.8))]",
  indigo:
    "border-[color:var(--zui-input-indigo-border,oklch(58.5%_0.233_277.117_/_0.8))] dark:border-[color:var(--zui-input-indigo-border-dark,oklch(58.5%_0.233_277.117_/_0.8))] text-[color:var(--zui-input-indigo-fg,oklch(25.7%_0.09_281.288))] dark:text-[color:var(--zui-input-indigo-fg-dark,oklch(96.2%_0.018_272.314))] placeholder:text-[color:var(--zui-input-indigo-placeholder-fg,oklch(39.8%_0.195_277.366))] dark:placeholder:text-[color:var(--zui-input-indigo-placeholder-fg-dark,oklch(78.5%_0.115_274.713_/_0.7))] focus-visible:border-[color:var(--zui-input-indigo-border-focus,oklch(51.1%_0.262_276.966))] dark:focus-visible:border-[color:var(--zui-input-indigo-border-focus-dark,oklch(67.3%_0.182_276.935))] focus-visible:ring-[var(--zui-input-indigo-ring-focus,oklch(67.3%_0.182_276.935_/_0.8))] dark:focus-visible:ring-[var(--zui-input-indigo-ring-focus-dark,oklch(67.3%_0.182_276.935_/_0.8))]",
  orange:
    "border-[color:var(--zui-input-orange-border,oklch(70.5%_0.213_47.604_/_0.8))] dark:border-[color:var(--zui-input-orange-border-dark,oklch(70.5%_0.213_47.604_/_0.8))] text-[color:var(--zui-input-orange-fg,oklch(26.6%_0.079_36.259))] dark:text-[color:var(--zui-input-orange-fg-dark,oklch(98%_0.016_73.684))] placeholder:text-[color:var(--zui-input-orange-placeholder-fg,oklch(47%_0.157_37.304))] dark:placeholder:text-[color:var(--zui-input-orange-placeholder-fg-dark,oklch(83.7%_0.128_66.29_/_0.7))] focus-visible:border-[color:var(--zui-input-orange-border-focus,oklch(64.6%_0.222_41.116))] dark:focus-visible:border-[color:var(--zui-input-orange-border-focus-dark,oklch(75%_0.183_55.934))] focus-visible:ring-[var(--zui-input-orange-ring-focus,oklch(75%_0.183_55.934_/_0.8))] dark:focus-visible:ring-[var(--zui-input-orange-ring-focus-dark,oklch(75%_0.183_55.934_/_0.8))]",
} as const;

export const zuiInputSizes = {
  sm: "h-8 px-3 text-xs",
  md: "h-9 md:h-11 px-4 text-sm",
  lg: "h-10 md:h-12 px-5 text-base",
} as const;

export const zuiInputTextareaSizes = {
  sm: "min-h-[5rem]",
  md: "min-h-[6rem]",
  lg: "min-h-[7.5rem]",
} as const;

export const zuiInputFileSizes = {
  sm: "h-8 text-xs pl-1 file:h-8 file:px-3 file:text-xs",
  md: "h-9 md:h-11 text-sm pl-1 file:h-9 md:file:h-11 file:px-4 file:text-sm",
  lg: "h-10 md:h-12 text-base pl-1 file:h-10 md:file:h-12 file:px-5 file:text-base",
} as const;

export const zuiInputFileAppearances = {
  default:
    "file:text-[color:var(--zui-input-file-default-fg,#334155)] dark:file:text-[color:var(--zui-input-file-default-fg-dark,#e2e8f0)]",
  warning:
    "file:bg-[var(--zui-input-file-warning-bg,#eab30833)] dark:file:bg-[var(--zui-input-file-warning-bg-dark,#eab30833)] file:text-[color:var(--zui-input-file-warning-fg,#854d0e)] dark:file:text-[color:var(--zui-input-file-warning-fg-dark,#fef08a)] file:border-[color:var(--zui-input-file-warning-border,#eab30866)] dark:file:border-[color:var(--zui-input-file-warning-border-dark,#eab30866)] hover:file:bg-[var(--zui-input-file-warning-bg-hover,#eab3084d)] dark:hover:file:bg-[var(--zui-input-file-warning-bg-hover-dark,#eab3084d)]",
  error:
    "file:bg-[var(--zui-input-file-error-bg,#f43f5e33)] dark:file:bg-[var(--zui-input-file-error-bg-dark,#f43f5e33)] file:text-[color:var(--zui-input-file-error-fg,#9f1239)] dark:file:text-[color:var(--zui-input-file-error-fg-dark,#fecdd3)] file:border-[color:var(--zui-input-file-error-border,#f43f5e66)] dark:file:border-[color:var(--zui-input-file-error-border-dark,#f43f5e66)] hover:file:bg-[var(--zui-input-file-error-bg-hover,#f43f5e4d)] dark:hover:file:bg-[var(--zui-input-file-error-bg-hover-dark,#f43f5e4d)]",
  success:
    "file:bg-[var(--zui-input-file-success-bg,#10b98133)] dark:file:bg-[var(--zui-input-file-success-bg-dark,#10b98133)] file:text-[color:var(--zui-input-file-success-fg,#065f46)] dark:file:text-[color:var(--zui-input-file-success-fg-dark,#a7f3d0)] file:border-[color:var(--zui-input-file-success-border,#10b98166)] dark:file:border-[color:var(--zui-input-file-success-border-dark,#10b98166)] hover:file:bg-[var(--zui-input-file-success-bg-hover,#10b9814d)] dark:hover:file:bg-[var(--zui-input-file-success-bg-hover-dark,#10b9814d)]",
  info: "file:bg-[var(--zui-input-file-info-bg,#3b82f633)] dark:file:bg-[var(--zui-input-file-info-bg-dark,#3b82f633)] file:text-[color:var(--zui-input-file-info-fg,#1e40af)] dark:file:text-[color:var(--zui-input-file-info-fg-dark,#bfdbfe)] file:border-[color:var(--zui-input-file-info-border,#3b82f666)] dark:file:border-[color:var(--zui-input-file-info-border-dark,#3b82f666)] hover:file:bg-[var(--zui-input-file-info-bg-hover,#3b82f64d)] dark:hover:file:bg-[var(--zui-input-file-info-bg-hover-dark,#3b82f64d)]",
  violet:
    "file:bg-[var(--zui-input-file-violet-bg,#8b5cf633)] dark:file:bg-[var(--zui-input-file-violet-bg-dark,#8b5cf633)] file:text-[color:var(--zui-input-file-violet-fg,#5b21b6)] dark:file:text-[color:var(--zui-input-file-violet-fg-dark,#ddd6fe)] file:border-[color:var(--zui-input-file-violet-border,#8b5cf666)] dark:file:border-[color:var(--zui-input-file-violet-border-dark,#8b5cf666)] hover:file:bg-[var(--zui-input-file-violet-bg-hover,#8b5cf64d)] dark:hover:file:bg-[var(--zui-input-file-violet-bg-hover-dark,#8b5cf64d)]",
  amber:
    "file:bg-[var(--zui-input-file-amber-bg,#f59e0b33)] dark:file:bg-[var(--zui-input-file-amber-bg-dark,#f59e0b33)] file:text-[color:var(--zui-input-file-amber-fg,#92400e)] dark:file:text-[color:var(--zui-input-file-amber-fg-dark,#fde68a)] file:border-[color:var(--zui-input-file-amber-border,#f59e0b66)] dark:file:border-[color:var(--zui-input-file-amber-border-dark,#f59e0b66)] hover:file:bg-[var(--zui-input-file-amber-bg-hover,#f59e0b4d)] dark:hover:file:bg-[var(--zui-input-file-amber-bg-hover-dark,#f59e0b4d)]",
  pink: "file:bg-[var(--zui-input-file-pink-bg,#ec489933)] dark:file:bg-[var(--zui-input-file-pink-bg-dark,#ec489933)] file:text-[color:var(--zui-input-file-pink-fg,#9d174d)] dark:file:text-[color:var(--zui-input-file-pink-fg-dark,#fbcfe8)] file:border-[color:var(--zui-input-file-pink-border,#ec489966)] dark:file:border-[color:var(--zui-input-file-pink-border-dark,#ec489966)] hover:file:bg-[var(--zui-input-file-pink-bg-hover,#ec48994d)] dark:hover:file:bg-[var(--zui-input-file-pink-bg-hover-dark,#ec48994d)]",
  indigo:
    "file:bg-[var(--zui-input-file-indigo-bg,#6366f133)] dark:file:bg-[var(--zui-input-file-indigo-bg-dark,#6366f133)] file:text-[color:var(--zui-input-file-indigo-fg,#3730a3)] dark:file:text-[color:var(--zui-input-file-indigo-fg-dark,#c7d2fe)] file:border-[color:var(--zui-input-file-indigo-border,#6366f166)] dark:file:border-[color:var(--zui-input-file-indigo-border-dark,#6366f166)] hover:file:bg-[var(--zui-input-file-indigo-bg-hover,#6366f14d)] dark:hover:file:bg-[var(--zui-input-file-indigo-bg-hover-dark,#6366f14d)]",
} as const;

export const zuiInputCheckboxSizes = {
  sm: "h-4! w-4! min-h-0! rounded-[0.35rem]! px-0! py-0!",
  md: "h-5! w-5! min-h-0! rounded-md! px-0! py-0!",
  lg: "h-6! w-6! min-h-0! rounded-md! px-0! py-0!",
} as const;

export const zuiInputRadioSizes = {
  sm: "h-4! w-4! min-h-0! px-0! py-0!",
  md: "h-5! w-5! min-h-0! px-0! py-0!",
  lg: "h-6! w-6! min-h-0! px-0! py-0!",
} as const;

export const zuiInputCheckboxAppearances = {
  default:
    "border-[color:var(--zui-input-checkbox-default-border,#94a3b8b3)]! dark:border-[color:var(--zui-input-checkbox-default-border-dark,#94a3b8b3)]! checked:border-[color:var(--zui-input-checkbox-default-border-checked,#334155)] dark:checked:border-[color:var(--zui-input-checkbox-default-border-checked-dark,#e2e8f0)] checked:text-[color:var(--zui-input-checkbox-default-fg-checked,#334155)] dark:checked:text-[color:var(--zui-input-checkbox-default-fg-checked-dark,#e2e8f0)] hover:border-[color:var(--zui-input-checkbox-default-border-hover,#475569)] dark:hover:border-[color:var(--zui-input-checkbox-default-border-hover-dark,#cbd5e1)] focus-visible:border-[color:var(--zui-input-checkbox-default-border-focus,#475569)] dark:focus-visible:border-[color:var(--zui-input-checkbox-default-border-focus-dark,#cbd5e1)] focus-visible:ring-[var(--zui-input-checkbox-default-ring-focus,#64748bb3)] dark:focus-visible:ring-[var(--zui-input-checkbox-default-ring-focus-dark,#94a3b8b3)]",
  warning:
    "border-[color:var(--zui-input-checkbox-warning-border,#eab308b3)]! dark:border-[color:var(--zui-input-checkbox-warning-border-dark,#eab308b3)]! checked:border-[color:var(--zui-input-checkbox-warning-border-checked,#ca8a04)] dark:checked:border-[color:var(--zui-input-checkbox-warning-border-checked-dark,#facc15)] checked:text-[color:var(--zui-input-checkbox-warning-fg-checked,#a16207)] dark:checked:text-[color:var(--zui-input-checkbox-warning-fg-checked-dark,#fde047)] hover:border-[color:var(--zui-input-checkbox-warning-border-hover,#ca8a04)] dark:hover:border-[color:var(--zui-input-checkbox-warning-border-hover-dark,#facc15)] focus-visible:border-[color:var(--zui-input-checkbox-warning-border-focus,#ca8a04)] dark:focus-visible:border-[color:var(--zui-input-checkbox-warning-border-focus-dark,#facc15)] focus-visible:ring-[var(--zui-input-checkbox-warning-ring-focus,#facc15cc)] dark:focus-visible:ring-[var(--zui-input-checkbox-warning-ring-focus-dark,#facc15cc)]",
  error:
    "border-[color:var(--zui-input-checkbox-error-border,#f43f5eb3)]! dark:border-[color:var(--zui-input-checkbox-error-border-dark,#f43f5eb3)]! checked:border-[color:var(--zui-input-checkbox-error-border-checked,#e11d48)] dark:checked:border-[color:var(--zui-input-checkbox-error-border-checked-dark,#fb7185)] checked:text-[color:var(--zui-input-checkbox-error-fg-checked,#be123c)] dark:checked:text-[color:var(--zui-input-checkbox-error-fg-checked-dark,#fda4af)] hover:border-[color:var(--zui-input-checkbox-error-border-hover,#e11d48)] dark:hover:border-[color:var(--zui-input-checkbox-error-border-hover-dark,#fb7185)] focus-visible:border-[color:var(--zui-input-checkbox-error-border-focus,#e11d48)] dark:focus-visible:border-[color:var(--zui-input-checkbox-error-border-focus-dark,#fb7185)] focus-visible:ring-[var(--zui-input-checkbox-error-ring-focus,#fb7185cc)] dark:focus-visible:ring-[var(--zui-input-checkbox-error-ring-focus-dark,#fb7185cc)]",
  success:
    "border-[color:var(--zui-input-checkbox-success-border,#10b981b3)]! dark:border-[color:var(--zui-input-checkbox-success-border-dark,#10b981b3)]! checked:border-[color:var(--zui-input-checkbox-success-border-checked,#059669)] dark:checked:border-[color:var(--zui-input-checkbox-success-border-checked-dark,#34d399)] checked:text-[color:var(--zui-input-checkbox-success-fg-checked,#047857)] dark:checked:text-[color:var(--zui-input-checkbox-success-fg-checked-dark,#6ee7b7)] hover:border-[color:var(--zui-input-checkbox-success-border-hover,#059669)] dark:hover:border-[color:var(--zui-input-checkbox-success-border-hover-dark,#34d399)] focus-visible:border-[color:var(--zui-input-checkbox-success-border-focus,#059669)] dark:focus-visible:border-[color:var(--zui-input-checkbox-success-border-focus-dark,#34d399)] focus-visible:ring-[var(--zui-input-checkbox-success-ring-focus,#34d399cc)] dark:focus-visible:ring-[var(--zui-input-checkbox-success-ring-focus-dark,#34d399cc)]",
  info: "border-[color:var(--zui-input-checkbox-info-border,#3b82f6b3)]! dark:border-[color:var(--zui-input-checkbox-info-border-dark,#3b82f6b3)]! checked:border-[color:var(--zui-input-checkbox-info-border-checked,#2563eb)] dark:checked:border-[color:var(--zui-input-checkbox-info-border-checked-dark,#60a5fa)] checked:text-[color:var(--zui-input-checkbox-info-fg-checked,#1d4ed8)] dark:checked:text-[color:var(--zui-input-checkbox-info-fg-checked-dark,#93c5fd)] hover:border-[color:var(--zui-input-checkbox-info-border-hover,#2563eb)] dark:hover:border-[color:var(--zui-input-checkbox-info-border-hover-dark,#60a5fa)] focus-visible:border-[color:var(--zui-input-checkbox-info-border-focus,#2563eb)] dark:focus-visible:border-[color:var(--zui-input-checkbox-info-border-focus-dark,#60a5fa)] focus-visible:ring-[var(--zui-input-checkbox-info-ring-focus,#60a5facc)] dark:focus-visible:ring-[var(--zui-input-checkbox-info-ring-focus-dark,#60a5facc)]",
  violet:
    "border-[color:var(--zui-input-checkbox-violet-border,#8b5cf6b3)]! dark:border-[color:var(--zui-input-checkbox-violet-border-dark,#8b5cf6b3)]! checked:after:bg-[var(--zui-input-checkbox-violet-indicator-bg-checked,#7c3aed)] dark:checked:after:bg-[var(--zui-input-checkbox-violet-indicator-bg-checked-dark,#a78bfa)] checked:border-[color:var(--zui-input-checkbox-violet-border-checked,#7c3aed)] dark:checked:border-[color:var(--zui-input-checkbox-violet-border-checked-dark,#a78bfa)] checked:text-[color:var(--zui-input-checkbox-violet-fg-checked,#6d28d9)] dark:checked:text-[color:var(--zui-input-checkbox-violet-fg-checked-dark,#c4b5fd)] hover:border-[color:var(--zui-input-checkbox-violet-border-hover,#7c3aed)] dark:hover:border-[color:var(--zui-input-checkbox-violet-border-hover-dark,#a78bfa)] focus-visible:border-[color:var(--zui-input-checkbox-violet-border-focus,#7c3aed)] dark:focus-visible:border-[color:var(--zui-input-checkbox-violet-border-focus-dark,#a78bfa)] focus-visible:ring-[var(--zui-input-checkbox-violet-ring-focus,#a78bfacc)] dark:focus-visible:ring-[var(--zui-input-checkbox-violet-ring-focus-dark,#a78bfacc)]",
  amber:
    "border-[color:var(--zui-input-checkbox-amber-border,#f59e0bb3)]! dark:border-[color:var(--zui-input-checkbox-amber-border-dark,#f59e0bb3)]! checked:border-[color:var(--zui-input-checkbox-amber-border-checked,#fbbf24)]! dark:checked:border-[color:var(--zui-input-checkbox-amber-border-checked-dark,#fbbf24)]! checked:text-[color:var(--zui-input-checkbox-amber-fg-checked,#b45309)] dark:checked:text-[color:var(--zui-input-checkbox-amber-fg-checked-dark,#fcd34d)] hover:border-[color:var(--zui-input-checkbox-amber-border-hover,#fbbf24)]! dark:hover:border-[color:var(--zui-input-checkbox-amber-border-hover-dark,#fbbf24)]! focus-visible:border-[color:var(--zui-input-checkbox-amber-border-focus,#fbbf24)]! dark:focus-visible:border-[color:var(--zui-input-checkbox-amber-border-focus-dark,#fbbf24)]! focus-visible:ring-[var(--zui-input-checkbox-amber-ring-focus,#fbbf24cc)]! dark:focus-visible:ring-[var(--zui-input-checkbox-amber-ring-focus-dark,#fbbf24cc)]!",
  pink: "border-[color:var(--zui-input-checkbox-pink-border,#ec4899b3)]! dark:border-[color:var(--zui-input-checkbox-pink-border-dark,#ec4899b3)]! checked:border-[color:var(--zui-input-checkbox-pink-border-checked,#db2777)] dark:checked:border-[color:var(--zui-input-checkbox-pink-border-checked-dark,#f472b6)] checked:text-[color:var(--zui-input-checkbox-pink-fg-checked,#be185d)] dark:checked:text-[color:var(--zui-input-checkbox-pink-fg-checked-dark,#f9a8d4)] hover:border-[color:var(--zui-input-checkbox-pink-border-hover,#db2777)] dark:hover:border-[color:var(--zui-input-checkbox-pink-border-hover-dark,#f472b6)] focus-visible:border-[color:var(--zui-input-checkbox-pink-border-focus,#db2777)] dark:focus-visible:border-[color:var(--zui-input-checkbox-pink-border-focus-dark,#f472b6)] focus-visible:ring-[var(--zui-input-checkbox-pink-ring-focus,#f472b6cc)] dark:focus-visible:ring-[var(--zui-input-checkbox-pink-ring-focus-dark,#f472b6cc)]",
  indigo:
    "border-[color:var(--zui-input-checkbox-indigo-border,#6366f1b3)]! dark:border-[color:var(--zui-input-checkbox-indigo-border-dark,#6366f1b3)]! checked:border-[color:var(--zui-input-checkbox-indigo-border-checked,#818cf8)]! dark:checked:border-[color:var(--zui-input-checkbox-indigo-border-checked-dark,#818cf8)]! checked:text-[color:var(--zui-input-checkbox-indigo-fg-checked,#4338ca)] dark:checked:text-[color:var(--zui-input-checkbox-indigo-fg-checked-dark,#a5b4fc)] hover:border-[color:var(--zui-input-checkbox-indigo-border-hover,#818cf8)]! dark:hover:border-[color:var(--zui-input-checkbox-indigo-border-hover-dark,#818cf8)]! focus-visible:border-[color:var(--zui-input-checkbox-indigo-border-focus,#818cf8)]! dark:focus-visible:border-[color:var(--zui-input-checkbox-indigo-border-focus-dark,#818cf8)]! focus-visible:ring-[var(--zui-input-checkbox-indigo-ring-focus,#818cf8cc)]! dark:focus-visible:ring-[var(--zui-input-checkbox-indigo-ring-focus-dark,#818cf8cc)]!",
} as const;

export const zuiInputRadioAppearances = {
  default:
    "border-[color:var(--zui-input-radio-default-border,#94a3b8b3)]! dark:border-[color:var(--zui-input-radio-default-border-dark,#94a3b8b3)]! checked:border-[color:var(--zui-input-radio-default-border-checked,#334155)] dark:checked:border-[color:var(--zui-input-radio-default-border-checked-dark,#e2e8f0)] checked:bg-[var(--zui-input-radio-default-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-default-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-default-dot,#e2e8f0)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-default-dot-dark,#e2e8f0)]! hover:border-[color:var(--zui-input-radio-default-border-hover,#475569)] dark:hover:border-[color:var(--zui-input-radio-default-border-hover-dark,#cbd5e1)] focus-visible:border-[color:var(--zui-input-radio-default-border-focus,#475569)] dark:focus-visible:border-[color:var(--zui-input-radio-default-border-focus-dark,#cbd5e1)] focus-visible:ring-[var(--zui-input-radio-default-ring-focus,#64748bb3)] dark:focus-visible:ring-[var(--zui-input-radio-default-ring-focus-dark,#94a3b8b3)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-default-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-default-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-default-ring-checked,#cbd5e1e6)]!",
  warning:
    "border-[color:var(--zui-input-radio-warning-border,#eab308b3)]! dark:border-[color:var(--zui-input-radio-warning-border-dark,#eab308b3)]! checked:border-[color:var(--zui-input-radio-warning-border-checked,#ca8a04)] dark:checked:border-[color:var(--zui-input-radio-warning-border-checked-dark,#facc15)] checked:bg-[var(--zui-input-radio-warning-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-warning-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-warning-dot,#facc15)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-warning-dot-dark,#facc15)]! hover:border-[color:var(--zui-input-radio-warning-border-hover,#ca8a04)] dark:hover:border-[color:var(--zui-input-radio-warning-border-hover-dark,#facc15)] focus-visible:border-[color:var(--zui-input-radio-warning-border-focus,#ca8a04)] dark:focus-visible:border-[color:var(--zui-input-radio-warning-border-focus-dark,#facc15)] focus-visible:ring-[var(--zui-input-radio-warning-ring-focus,#facc15cc)] dark:focus-visible:ring-[var(--zui-input-radio-warning-ring-focus-dark,#facc15cc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-warning-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-warning-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-warning-ring-checked,#facc15e6)]!",
  error:
    "border-[color:var(--zui-input-radio-error-border,#f43f5eb3)]! dark:border-[color:var(--zui-input-radio-error-border-dark,#f43f5eb3)]! checked:border-[color:var(--zui-input-radio-error-border-checked,#e11d48)] dark:checked:border-[color:var(--zui-input-radio-error-border-checked-dark,#fb7185)] checked:bg-[var(--zui-input-radio-error-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-error-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-error-dot,#fb7185)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-error-dot-dark,#fb7185)]! hover:border-[color:var(--zui-input-radio-error-border-hover,#e11d48)] dark:hover:border-[color:var(--zui-input-radio-error-border-hover-dark,#fb7185)] focus-visible:border-[color:var(--zui-input-radio-error-border-focus,#e11d48)] dark:focus-visible:border-[color:var(--zui-input-radio-error-border-focus-dark,#fb7185)] focus-visible:ring-[var(--zui-input-radio-error-ring-focus,#fb7185cc)] dark:focus-visible:ring-[var(--zui-input-radio-error-ring-focus-dark,#fb7185cc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-error-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-error-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-error-ring-checked,#fb7185e6)]!",
  success:
    "border-[color:var(--zui-input-radio-success-border,#10b981b3)]! dark:border-[color:var(--zui-input-radio-success-border-dark,#10b981b3)]! checked:border-[color:var(--zui-input-radio-success-border-checked,#059669)] dark:checked:border-[color:var(--zui-input-radio-success-border-checked-dark,#34d399)] checked:bg-[var(--zui-input-radio-success-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-success-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-success-dot,#34d399)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-success-dot-dark,#34d399)]! hover:border-[color:var(--zui-input-radio-success-border-hover,#059669)] dark:hover:border-[color:var(--zui-input-radio-success-border-hover-dark,#34d399)] focus-visible:border-[color:var(--zui-input-radio-success-border-focus,#059669)] dark:focus-visible:border-[color:var(--zui-input-radio-success-border-focus-dark,#34d399)] focus-visible:ring-[var(--zui-input-radio-success-ring-focus,#34d399cc)] dark:focus-visible:ring-[var(--zui-input-radio-success-ring-focus-dark,#34d399cc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-success-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-success-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-success-ring-checked,#34d399e6)]!",
  info: "border-[color:var(--zui-input-radio-info-border,#3b82f6b3)]! dark:border-[color:var(--zui-input-radio-info-border-dark,#3b82f6b3)]! checked:border-[color:var(--zui-input-radio-info-border-checked,#2563eb)] dark:checked:border-[color:var(--zui-input-radio-info-border-checked-dark,#60a5fa)] checked:bg-[var(--zui-input-radio-info-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-info-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-info-dot,#60a5fa)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-info-dot-dark,#60a5fa)]! hover:border-[color:var(--zui-input-radio-info-border-hover,#2563eb)] dark:hover:border-[color:var(--zui-input-radio-info-border-hover-dark,#60a5fa)] focus-visible:border-[color:var(--zui-input-radio-info-border-focus,#2563eb)] dark:focus-visible:border-[color:var(--zui-input-radio-info-border-focus-dark,#60a5fa)] focus-visible:ring-[var(--zui-input-radio-info-ring-focus,#60a5facc)] dark:focus-visible:ring-[var(--zui-input-radio-info-ring-focus-dark,#60a5facc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-info-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-info-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-info-ring-checked,#60a5fae6)]!",
  violet:
    "border-[color:var(--zui-input-radio-violet-border,#8b5cf6b3)]! dark:border-[color:var(--zui-input-radio-violet-border-dark,#8b5cf6b3)]! checked:border-[color:var(--zui-input-radio-violet-border-checked,#7c3aed)] dark:checked:border-[color:var(--zui-input-radio-violet-border-checked-dark,#a78bfa)] checked:bg-[var(--zui-input-radio-violet-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-violet-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-violet-dot,#a78bfa)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-violet-dot-dark,#a78bfa)]! hover:border-[color:var(--zui-input-radio-violet-border-hover,#7c3aed)] dark:hover:border-[color:var(--zui-input-radio-violet-border-hover-dark,#a78bfa)] focus-visible:border-[color:var(--zui-input-radio-violet-border-focus,#7c3aed)] dark:focus-visible:border-[color:var(--zui-input-radio-violet-border-focus-dark,#a78bfa)] focus-visible:ring-[var(--zui-input-radio-violet-ring-focus,#a78bfacc)] dark:focus-visible:ring-[var(--zui-input-radio-violet-ring-focus-dark,#a78bfacc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-violet-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-violet-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-violet-ring-checked,#a78bfae6)]!",
  amber:
    "border-[color:var(--zui-input-radio-amber-border,#f59e0bb3)]! dark:border-[color:var(--zui-input-radio-amber-border-dark,#f59e0bb3)]! checked:border-[color:var(--zui-input-radio-amber-border-checked,#d97706)] dark:checked:border-[color:var(--zui-input-radio-amber-border-checked-dark,#fbbf24)] checked:bg-[var(--zui-input-radio-amber-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-amber-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-amber-dot,#fbbf24)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-amber-dot-dark,#fbbf24)]! hover:border-[color:var(--zui-input-radio-amber-border-hover,#d97706)] dark:hover:border-[color:var(--zui-input-radio-amber-border-hover-dark,#fbbf24)] focus-visible:border-[color:var(--zui-input-radio-amber-border-focus,#d97706)] dark:focus-visible:border-[color:var(--zui-input-radio-amber-border-focus-dark,#fbbf24)] focus-visible:ring-[var(--zui-input-radio-amber-ring-focus,#fbbf24cc)] dark:focus-visible:ring-[var(--zui-input-radio-amber-ring-focus-dark,#fbbf24cc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-amber-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-amber-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-amber-ring-checked,#fbbf24e6)]!",
  pink: "border-[color:var(--zui-input-radio-pink-border,#ec4899b3)]! dark:border-[color:var(--zui-input-radio-pink-border-dark,#ec4899b3)]! checked:border-[color:var(--zui-input-radio-pink-border-checked,#db2777)] dark:checked:border-[color:var(--zui-input-radio-pink-border-checked-dark,#f472b6)] checked:bg-[var(--zui-input-radio-pink-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-pink-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-pink-dot,#f472b6)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-pink-dot-dark,#f472b6)]! hover:border-[color:var(--zui-input-radio-pink-border-hover,#db2777)] dark:hover:border-[color:var(--zui-input-radio-pink-border-hover-dark,#f472b6)] focus-visible:border-[color:var(--zui-input-radio-pink-border-focus,#db2777)] dark:focus-visible:border-[color:var(--zui-input-radio-pink-border-focus-dark,#f472b6)] focus-visible:ring-[var(--zui-input-radio-pink-ring-focus,#f472b6cc)] dark:focus-visible:ring-[var(--zui-input-radio-pink-ring-focus-dark,#f472b6cc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-pink-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-pink-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-pink-ring-checked,#f472b6e6)]!",
  indigo:
    "border-[color:var(--zui-input-radio-indigo-border,#6366f1b3)]! dark:border-[color:var(--zui-input-radio-indigo-border-dark,#6366f1b3)]! checked:border-[color:var(--zui-input-radio-indigo-border-checked,#4f46e5)] dark:checked:border-[color:var(--zui-input-radio-indigo-border-checked-dark,#818cf8)] checked:bg-[var(--zui-input-radio-indigo-bg-checked,transparent)]! dark:checked:bg-[var(--zui-input-radio-indigo-bg-checked-dark,transparent)]! checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-indigo-dot,#818cf8)]! dark:checked:shadow-[inset_0_0_0_0.28rem_var(--zui-input-radio-indigo-dot-dark,#818cf8)]! hover:border-[color:var(--zui-input-radio-indigo-border-hover,#4f46e5)] dark:hover:border-[color:var(--zui-input-radio-indigo-border-hover-dark,#818cf8)] focus-visible:border-[color:var(--zui-input-radio-indigo-border-focus,#4f46e5)] dark:focus-visible:border-[color:var(--zui-input-radio-indigo-border-focus-dark,#818cf8)] focus-visible:ring-[var(--zui-input-radio-indigo-ring-focus,#818cf8cc)] dark:focus-visible:ring-[var(--zui-input-radio-indigo-ring-focus-dark,#818cf8cc)] checked:ring-2! checked:ring-offset-2! checked:ring-offset-[var(--zui-input-radio-indigo-ring-offset-checked,#ffffff)]! dark:checked:ring-offset-[var(--zui-input-radio-indigo-ring-offset-checked-dark,#020617)]! checked:ring-[var(--zui-input-radio-indigo-ring-checked,#818cf8e6)]!",
} as const;

export const zuiInputDateAppearances = {
  default:
    "bg-[var(--zui-input-date-default-bg,#ffffff)] dark:bg-[var(--zui-input-date-default-bg-dark,#000000)] border border-[color:var(--zui-input-date-default-border,#0000001a)] dark:border-[color:var(--zui-input-date-default-border-dark,#ffffffcc)] text-[color:var(--zui-input-date-default-fg,#000000)] dark:text-[color:var(--zui-input-date-default-fg-dark,#ffffff)]",
  warning:
    "bg-[var(--zui-input-date-warning-bg,#713f12)] dark:bg-[var(--zui-input-date-warning-bg-dark,transparent)] text-[color:var(--zui-input-date-warning-fg,#fefce8)] dark:text-[color:var(--zui-input-date-warning-fg-dark,#fefce8)]",
  error:
    "bg-[var(--zui-input-date-error-bg,#881337)] dark:bg-[var(--zui-input-date-error-bg-dark,transparent)] text-[color:var(--zui-input-date-error-fg,#fff1f2)] dark:text-[color:var(--zui-input-date-error-fg-dark,#fff1f2)]",
  success:
    "bg-[var(--zui-input-date-success-bg,#064e3b)] dark:bg-[var(--zui-input-date-success-bg-dark,transparent)] text-[color:var(--zui-input-date-success-fg,#ecfdf5)] dark:text-[color:var(--zui-input-date-success-fg-dark,#ecfdf5)]",
  info: "bg-[var(--zui-input-date-info-bg,#1e3a8a)] dark:bg-[var(--zui-input-date-info-bg-dark,transparent)] text-[color:var(--zui-input-date-info-fg,#eff6ff)] dark:text-[color:var(--zui-input-date-info-fg-dark,#eff6ff)]",
  violet:
    "bg-[var(--zui-input-date-violet-bg,#4c1d95)] dark:bg-[var(--zui-input-date-violet-bg-dark,transparent)] text-[color:var(--zui-input-date-violet-fg,#f5f3ff)] dark:text-[color:var(--zui-input-date-violet-fg-dark,#f5f3ff)]",
  amber:
    "bg-[var(--zui-input-date-amber-bg,#78350f)] dark:bg-[var(--zui-input-date-amber-bg-dark,transparent)] text-[color:var(--zui-input-date-amber-fg,#fffbeb)] dark:text-[color:var(--zui-input-date-amber-fg-dark,#fffbeb)]",
  pink: "bg-[var(--zui-input-date-pink-bg,#831843)] dark:bg-[var(--zui-input-date-pink-bg-dark,transparent)] text-[color:var(--zui-input-date-pink-fg,#fdf2f8)] dark:text-[color:var(--zui-input-date-pink-fg-dark,#fdf2f8)]",
  indigo:
    "bg-[var(--zui-input-date-indigo-bg,#312e81)] dark:bg-[var(--zui-input-date-indigo-bg-dark,transparent)] text-[color:var(--zui-input-date-indigo-fg,#eef2ff)] dark:text-[color:var(--zui-input-date-indigo-fg-dark,#eef2ff)]",
  orange:
    "bg-[var(--zui-input-date-orange-bg,#7c2d12)] dark:bg-[var(--zui-input-date-orange-bg-dark,transparent)] text-[color:var(--zui-input-date-orange-fg,#fff7ed)] dark:text-[color:var(--zui-input-date-orange-fg-dark,#fff7ed)]",
} as const;

export const zuiInputRing = {
  true: "focus-visible:ring-2 focus-visible:ring-offset-2",
  false: "",
} as const;
