export const zuiKbdBase = [
  "inline-flex items-center justify-center gap-1 align-middle",
  "rounded-[var(--zui-kbd-radius,var(--zui-radius,0.375rem))] font-mono font-medium leading-none select-none",
] as const;

export const zuiKbdKeyAppearances = {
  default:
    "bg-[var(--zui-kbd-default-bg,var(--zui-brand,#0f172a))] dark:bg-[var(--zui-kbd-default-bg-dark,var(--zui-brand-dark,#f8fafc))] text-[color:var(--zui-kbd-default-fg,var(--zui-brand-fg,#f8fafc))] dark:text-[color:var(--zui-kbd-default-fg-dark,var(--zui-brand-fg-dark,#020617))] shadow-[var(--zui-kbd-default-shadow,var(--zui-shadow,0_1px_2px_#0f172a14))] dark:shadow-[var(--zui-kbd-default-shadow-dark,var(--zui-shadow-dark,0_1px_2px_#0f172a1f))]",
  secondary:
    "bg-[var(--zui-kbd-secondary-bg,var(--zui-surface-soft,#e2e8f0))] dark:bg-[var(--zui-kbd-secondary-bg-dark,var(--zui-surface-soft-dark,#1e293b))] text-[color:var(--zui-kbd-secondary-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-kbd-secondary-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  destructive:
    "bg-[var(--zui-kbd-destructive-bg,var(--zui-status-error,#f43f5e))] dark:bg-[var(--zui-kbd-destructive-bg-dark,var(--zui-status-error-dark,#be123c))] text-[color:var(--zui-kbd-destructive-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-destructive-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  outline:
    "border border-[color:var(--zui-kbd-outline-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-kbd-outline-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-kbd-outline-bg,var(--zui-surface-soft,#0000000d))] dark:bg-[var(--zui-kbd-outline-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] text-[color:var(--zui-kbd-outline-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-kbd-outline-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  ghost:
    "bg-transparent text-[color:var(--zui-kbd-ghost-fg,var(--zui-fg,#334155))] dark:text-[color:var(--zui-kbd-ghost-fg-dark,var(--zui-fg-dark,#e2e8f0))]",
  glass:
    "border border-[color:var(--zui-kbd-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-kbd-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-kbd-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-kbd-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-kbd-glass-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-kbd-glass-fg-dark,var(--zui-fg-dark,#ffffff))] backdrop-blur-md",
  emerald:
    "bg-[var(--zui-kbd-emerald-bg,var(--zui-color-emerald,#10b981))] dark:bg-[var(--zui-kbd-emerald-bg-dark,var(--zui-color-emerald-dark,#065f46))] text-[color:var(--zui-kbd-emerald-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-emerald-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  indigo:
    "bg-[var(--zui-kbd-indigo-bg,var(--zui-color-indigo,#3730a3))] dark:bg-[var(--zui-kbd-indigo-bg-dark,var(--zui-color-indigo-dark,#4f46e5))] text-[color:var(--zui-kbd-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  purple:
    "bg-[var(--zui-kbd-purple-bg,var(--zui-color-purple,#6b21a8))] dark:bg-[var(--zui-kbd-purple-bg-dark,var(--zui-color-purple-dark,#9333ea))] text-[color:var(--zui-kbd-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  pink: "bg-[var(--zui-kbd-pink-bg,var(--zui-color-pink,#9d174d))] dark:bg-[var(--zui-kbd-pink-bg-dark,var(--zui-color-pink-dark,#db2777))] text-[color:var(--zui-kbd-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  rose: "bg-[var(--zui-kbd-rose-bg,var(--zui-color-rose,#9f1239))] dark:bg-[var(--zui-kbd-rose-bg-dark,var(--zui-color-rose-dark,#e11d48))] text-[color:var(--zui-kbd-rose-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-rose-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  sky: "bg-[var(--zui-kbd-sky-bg,var(--zui-color-sky,#0ea5e9))] dark:bg-[var(--zui-kbd-sky-bg-dark,var(--zui-color-sky-dark,#0369a1))] text-[color:var(--zui-kbd-sky-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-sky-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  teal: "bg-[var(--zui-kbd-teal-bg,var(--zui-color-teal,#14b8a6))] dark:bg-[var(--zui-kbd-teal-bg-dark,var(--zui-color-teal-dark,#0f766e))] text-[color:var(--zui-kbd-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  yellow:
    "bg-[var(--zui-kbd-yellow-bg,var(--zui-color-yellow,#eab308))] dark:bg-[var(--zui-kbd-yellow-bg-dark,var(--zui-color-yellow-dark,#854d0e))] text-[color:var(--zui-kbd-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  orange:
    "bg-[var(--zui-kbd-orange-bg,var(--zui-color-orange,#f97316))] dark:bg-[var(--zui-kbd-orange-bg-dark,var(--zui-color-orange-dark,#9a3412))] text-[color:var(--zui-kbd-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  gray: "bg-[var(--zui-kbd-gray-bg,var(--zui-color-gray,#6b7280))] dark:bg-[var(--zui-kbd-gray-bg-dark,var(--zui-color-gray-dark,#374151))] text-[color:var(--zui-kbd-gray-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gray-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  amber:
    "bg-[var(--zui-kbd-amber-bg,var(--zui-color-amber,#f59e0b))] dark:bg-[var(--zui-kbd-amber-bg-dark,var(--zui-color-amber-dark,#92400e))] text-[color:var(--zui-kbd-amber-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-amber-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  violet:
    "bg-[var(--zui-kbd-violet-bg,var(--zui-color-violet,#5b21b6))] dark:bg-[var(--zui-kbd-violet-bg-dark,var(--zui-color-violet-dark,#7c3aed))] text-[color:var(--zui-kbd-violet-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-violet-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-blue-from,var(--zui-color-blue,#1e40af))] dark:from-[var(--zui-kbd-gradient-blue-from-dark,var(--zui-color-blue-dark,#2563eb))] to-[var(--zui-kbd-gradient-blue-to,var(--zui-color-purple,#6b21a8))] dark:to-[var(--zui-kbd-gradient-blue-to-dark,var(--zui-color-purple-dark,#9333ea))] text-[color:var(--zui-kbd-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-green-from,var(--zui-color-green,#166534))] dark:from-[var(--zui-kbd-gradient-green-from-dark,var(--zui-color-green-dark,#16a34a))] to-[var(--zui-kbd-gradient-green-to,var(--zui-color-lime,#3f6212))] dark:to-[var(--zui-kbd-gradient-green-to-dark,var(--zui-color-lime-dark,#65a30d))] text-[color:var(--zui-kbd-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-red-from,var(--zui-color-red,#991b1b))] dark:from-[var(--zui-kbd-gradient-red-from-dark,var(--zui-color-red-dark,#dc2626))] to-[var(--zui-kbd-gradient-red-to,var(--zui-color-pink,#9d174d))] dark:to-[var(--zui-kbd-gradient-red-to-dark,var(--zui-color-pink-dark,#db2777))] text-[color:var(--zui-kbd-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-yellow-from,var(--zui-color-yellow,#854d0e))] dark:from-[var(--zui-kbd-gradient-yellow-from-dark,var(--zui-color-yellow-dark,#ca8a04))] to-[var(--zui-kbd-gradient-yellow-to,var(--zui-color-orange,#9a3412))] dark:to-[var(--zui-kbd-gradient-yellow-to-dark,var(--zui-color-orange-dark,#ea580c))] text-[color:var(--zui-kbd-gradient-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-purple-from,var(--zui-color-purple,#6b21a8))] dark:from-[var(--zui-kbd-gradient-purple-from-dark,var(--zui-color-purple-dark,#9333ea))] to-[var(--zui-kbd-gradient-purple-to,var(--zui-color-pink,#9d174d))] dark:to-[var(--zui-kbd-gradient-purple-to-dark,var(--zui-color-pink-dark,#db2777))] text-[color:var(--zui-kbd-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-teal-from,var(--zui-color-teal,#115e59))] dark:from-[var(--zui-kbd-gradient-teal-from-dark,var(--zui-color-teal-dark,#0d9488))] to-[var(--zui-kbd-gradient-teal-to,var(--zui-color-cyan,#155e75))] dark:to-[var(--zui-kbd-gradient-teal-to-dark,var(--zui-color-cyan-dark,#0891b2))] text-[color:var(--zui-kbd-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-indigo-from,var(--zui-color-indigo,#3730a3))] dark:from-[var(--zui-kbd-gradient-indigo-from-dark,var(--zui-color-indigo-dark,#4f46e5))] to-[var(--zui-kbd-gradient-indigo-to,var(--zui-color-purple,#6b21a8))] dark:to-[var(--zui-kbd-gradient-indigo-to-dark,var(--zui-color-purple-dark,#9333ea))] text-[color:var(--zui-kbd-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-pink-from,var(--zui-color-pink,#9d174d))] dark:from-[var(--zui-kbd-gradient-pink-from-dark,var(--zui-color-pink-dark,#db2777))] to-[var(--zui-kbd-gradient-pink-to,var(--zui-color-rose,#9f1239))] dark:to-[var(--zui-kbd-gradient-pink-to-dark,var(--zui-color-rose-dark,#e11d48))] text-[color:var(--zui-kbd-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-kbd-gradient-orange-from,var(--zui-color-orange,#9a3412))] dark:from-[var(--zui-kbd-gradient-orange-from-dark,var(--zui-color-orange-dark,#ea580c))] to-[var(--zui-kbd-gradient-orange-to,var(--zui-color-red,#991b1b))] dark:to-[var(--zui-kbd-gradient-orange-to-dark,var(--zui-color-red-dark,#dc2626))] text-[color:var(--zui-kbd-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  blue: "border border-[color:var(--zui-kbd-key-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-kbd-key-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-kbd-key-blue-bg,var(--zui-color-blue,#2563eb))] dark:bg-[var(--zui-kbd-key-blue-bg-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-kbd-key-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f6) 18%, transparent))]",
  cyan: "border border-[color:var(--zui-kbd-key-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-kbd-key-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-kbd-key-cyan-bg,var(--zui-color-cyan,#0891b2))] dark:bg-[var(--zui-kbd-key-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-kbd-key-cyan-fg,var(--zui-brand-fg,#083344))] dark:text-[color:var(--zui-kbd-key-cyan-fg-dark,var(--zui-brand-fg-dark,#083344))] hover:bg-[var(--zui-kbd-key-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b2) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee) 18%, transparent))]",
  green:
    "border border-[color:var(--zui-kbd-key-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-kbd-key-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-kbd-key-green-bg,var(--zui-color-green,#16a34a))] dark:bg-[var(--zui-kbd-key-green-bg-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-kbd-key-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e) 18%, transparent))]",
  lime: "border border-[color:var(--zui-kbd-key-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-kbd-key-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-kbd-key-lime-bg,var(--zui-color-lime,#65a30d))] dark:bg-[var(--zui-kbd-key-lime-bg-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-kbd-key-lime-fg,var(--zui-brand-fg,#1a2e05))] dark:text-[color:var(--zui-kbd-key-lime-fg-dark,var(--zui-brand-fg-dark,#1a2e05))] hover:bg-[var(--zui-kbd-key-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e635) 18%, transparent))]",
  mint: "border border-[color:var(--zui-kbd-key-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-kbd-key-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-kbd-key-mint-bg,var(--zui-color-mint,#10b981))] dark:bg-[var(--zui-kbd-key-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-kbd-key-mint-fg,var(--zui-brand-fg,#064e3b))] dark:text-[color:var(--zui-kbd-key-mint-fg-dark,var(--zui-brand-fg-dark,#064e3b))] hover:bg-[var(--zui-kbd-key-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b981) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b7) 18%, transparent))]",
  ocean:
    "border border-[color:var(--zui-kbd-key-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-kbd-key-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-kbd-key-ocean-bg,var(--zui-color-ocean,#0284c7))] dark:bg-[var(--zui-kbd-key-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-kbd-key-ocean-fg,var(--zui-brand-fg,#082f49))] dark:text-[color:var(--zui-kbd-key-ocean-fg-dark,var(--zui-brand-fg-dark,#082f49))] hover:bg-[var(--zui-kbd-key-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c7) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf8) 18%, transparent))]",
  sapphire:
    "border border-[color:var(--zui-kbd-key-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-kbd-key-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-kbd-key-sapphire-bg,var(--zui-color-sapphire,#1d4ed8))] dark:bg-[var(--zui-kbd-key-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-kbd-key-sapphire-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-sapphire-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed8) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa) 18%, transparent))]",
  lavender:
    "border border-[color:var(--zui-kbd-key-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-kbd-key-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-kbd-key-lavender-bg,var(--zui-color-lavender,#8b5cf6))] dark:bg-[var(--zui-kbd-key-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-kbd-key-lavender-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-lavender-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf6) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa) 18%, transparent))]",
  ruby: "border border-[color:var(--zui-kbd-key-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-kbd-key-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-kbd-key-ruby-bg,var(--zui-color-ruby,#be123c))] dark:bg-[var(--zui-kbd-key-ruby-bg-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-kbd-key-ruby-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-ruby-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb7185) 18%, transparent))]",
  red: "border border-[color:var(--zui-kbd-key-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-kbd-key-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-kbd-key-red-bg,var(--zui-color-red,#dc2626))] dark:bg-[var(--zui-kbd-key-red-bg-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-kbd-key-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc2626) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef4444) 18%, transparent))]",
  slate:
    "border border-[color:var(--zui-kbd-key-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-kbd-key-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-kbd-key-slate-bg,var(--zui-color-slate,#475569))] dark:bg-[var(--zui-kbd-key-slate-bg-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-kbd-key-slate-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-slate-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#475569) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b) 18%, transparent))]",
  zinc: "border border-[color:var(--zui-kbd-key-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-kbd-key-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-kbd-key-zinc-bg,var(--zui-color-zinc,#52525b))] dark:bg-[var(--zui-kbd-key-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-kbd-key-zinc-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-zinc-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a) 18%, transparent))]",
  stone:
    "border border-[color:var(--zui-kbd-key-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-kbd-key-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-kbd-key-stone-bg,var(--zui-color-stone,#57534e))] dark:bg-[var(--zui-kbd-key-stone-bg-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-kbd-key-stone-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-stone-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c) 18%, transparent))]",
  royal:
    "border border-[color:var(--zui-kbd-key-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-kbd-key-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-kbd-key-royal-bg,var(--zui-color-royal,#4338ca))] dark:bg-[var(--zui-kbd-key-royal-bg-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-kbd-key-royal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-royal-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf8) 18%, transparent))]",
  electric:
    "border border-[color:var(--zui-kbd-key-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-kbd-key-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-kbd-key-electric-bg,var(--zui-color-electric,#0ea5e9))] dark:bg-[var(--zui-kbd-key-electric-bg-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-kbd-key-electric-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-electric-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e9) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf8) 18%, transparent))]",
  forest:
    "border border-[color:var(--zui-kbd-key-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-kbd-key-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-kbd-key-forest-bg,var(--zui-color-forest,#166534))] dark:bg-[var(--zui-kbd-key-forest-bg-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-kbd-key-forest-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-forest-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#166534) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade80) 18%, transparent))]",
  sunset:
    "border border-[color:var(--zui-kbd-key-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-kbd-key-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-kbd-key-sunset-bg,var(--zui-color-sunset,#ea580c))] dark:bg-[var(--zui-kbd-key-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-kbd-key-sunset-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-sunset-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c) 18%, transparent))]",
  magenta:
    "border border-[color:var(--zui-kbd-key-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-kbd-key-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-kbd-key-magenta-bg,var(--zui-color-magenta,#c026d3))] dark:bg-[var(--zui-kbd-key-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-kbd-key-magenta-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-magenta-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d3) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f9) 18%, transparent))]",
  crimson:
    "border border-[color:var(--zui-kbd-key-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-kbd-key-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-kbd-key-crimson-bg,var(--zui-color-crimson,#b91c1c))] dark:bg-[var(--zui-kbd-key-crimson-bg-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-kbd-key-crimson-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-crimson-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f87171) 18%, transparent))]",
  aqua: "border border-[color:var(--zui-kbd-key-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-kbd-key-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-kbd-key-aqua-bg,var(--zui-color-aqua,#0f766e))] dark:bg-[var(--zui-kbd-key-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-kbd-key-aqua-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-aqua-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf) 18%, transparent))]",
  plum: "border border-[color:var(--zui-kbd-key-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-kbd-key-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-kbd-key-plum-bg,var(--zui-color-plum,#7e22ce))] dark:bg-[var(--zui-kbd-key-plum-bg-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-kbd-key-plum-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-kbd-key-plum-fg-dark,var(--zui-brand-fg-dark,#ffffff))] hover:bg-[var(--zui-kbd-key-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce) 10%, transparent))] dark:hover:bg-[var(--zui-kbd-key-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc) 18%, transparent))]",
} as const;

export type ZuiKbdAppearance = keyof typeof zuiKbdKeyAppearances;

export const zuiKbdKeyBase = [
  "inline-flex items-center justify-center font-mono font-medium leading-none",
  "rounded-[var(--zui-kbd-radius,var(--zui-radius,0.375rem))]",
  "shadow-[var(--zui-kbd-shadow,var(--zui-shadow,inset_0_-1px_0_#0000001f))] dark:shadow-[var(--zui-kbd-shadow-dark,var(--zui-shadow-dark,inset_0_-1px_0_#0000004d))]",
] as const;

export const zuiKbdKeySizes = {
  sm: "h-5 min-w-5 px-1 text-[0.7rem]",
  md: "h-6 min-w-6 px-1.5 text-xs",
  lg: "h-7 min-w-7 px-2 text-sm",
} as const;

export type ZuiKbdSize = keyof typeof zuiKbdKeySizes;

export const zuiKbdSeparatorBase =
  "text-[color:var(--zui-kbd-separator-fg,var(--zui-fg,#94a3b8))] dark:text-[color:var(--zui-kbd-separator-fg-dark,var(--zui-fg-dark,#64748b))]";

export const zuiKbdSeparatorSizes = {
  sm: "text-[0.7rem]",
  md: "text-xs",
  lg: "text-sm",
} as const;
