export const zuiMarqueeBase =
  "group/marquee relative isolate flex min-w-0 overflow-hidden rounded-xl border border-transparent bg-[var(--zui-marquee-bg,var(--zui-surface-soft,transparent))] text-[color:var(--zui-marquee-fg,var(--zui-fg,inherit))] [--zui-marquee-gap:1rem]";

export const zuiMarqueeAppearances = {
  default:
    "[--zui-marquee-bg:transparent] [--zui-marquee-fg:oklch(20.8%_0.042_265.755)] dark:[--zui-marquee-fg:#ffffff]",
  outline:
    "border-[color:var(--zui-marquee-outline-border,var(--zui-border,oklch(86.9%_0.022_252.894)))] [--zui-marquee-bg:#ffffff] [--zui-marquee-fg:oklch(20.8%_0.042_265.755)] dark:border-[color:var(--zui-marquee-outline-border-dark,var(--zui-border-dark,oklch(37.2%_0.044_257.287)))] dark:[--zui-marquee-bg:oklch(20.8%_0.042_265.755)] dark:[--zui-marquee-fg:#ffffff]",
  ghost:
    "[--zui-marquee-bg:transparent] [--zui-marquee-fg:oklch(27.9%_0.041_260.031)] dark:[--zui-marquee-fg:oklch(96.8%_0.007_247.896)]",
  card: "border-[color:var(--zui-marquee-card-border,var(--zui-border,oklch(92.9%_0.013_255.508)))] bg-[var(--zui-marquee-card-bg,var(--zui-surface-soft,#ffffff))] shadow-sm shadow-slate-950/5 [--zui-marquee-fg:oklch(20.8%_0.042_265.755)] dark:border-[color:var(--zui-marquee-card-border-dark,var(--zui-border-dark,oklch(37.2%_0.044_257.287)))] dark:bg-[var(--zui-marquee-card-bg-dark,var(--zui-surface-soft-dark,oklch(20.8%_0.042_265.755_/_0.9)))] dark:shadow-black/20 dark:[--zui-marquee-fg:#ffffff]",
  separated:
    "border-y border-x-0 rounded-none border-[color:var(--zui-marquee-separated-border,var(--zui-border,oklch(86.9%_0.022_252.894)))] [--zui-marquee-bg:transparent] [--zui-marquee-fg:oklch(20.8%_0.042_265.755)] dark:border-[color:var(--zui-marquee-separated-border-dark,var(--zui-border-dark,oklch(37.2%_0.044_257.287)))] dark:[--zui-marquee-fg:#ffffff]",
  sky: "border-[color:var(--zui-marquee-sky-border,var(--zui-color-sky,oklch(62.3%_0.214_259.815_/_0.28)))] [--zui-marquee-bg:oklch(97.7%_0.013_236.62)] [--zui-marquee-fg:oklch(39.1%_0.09_240.876)] dark:border-[color:var(--zui-marquee-sky-border-dark,var(--zui-color-sky-dark,oklch(70.7%_0.165_254.624_/_0.3)))] dark:[--zui-marquee-bg:oklch(39.1%_0.09_240.876_/_0.28)] dark:[--zui-marquee-fg:oklch(95.1%_0.026_236.824)]",
  rose: "border-[color:var(--zui-marquee-rose-border,var(--zui-color-rose,oklch(58.6%_0.253_17.585_/_0.24)))] [--zui-marquee-bg:oklch(96.9%_0.015_12.422)] [--zui-marquee-fg:oklch(41%_0.159_10.272)] dark:border-[color:var(--zui-marquee-rose-border-dark,var(--zui-color-rose-dark,oklch(71.2%_0.194_13.428_/_0.3)))] dark:[--zui-marquee-bg:oklch(41%_0.159_10.272_/_0.28)] dark:[--zui-marquee-fg:oklch(94.1%_0.03_12.58)]",
  purple:
    "border-[color:var(--zui-marquee-purple-border,var(--zui-color-purple,oklch(62.7%_0.265_303.9_/_0.24)))] [--zui-marquee-bg:oklch(97.7%_0.014_308.299)] [--zui-marquee-fg:oklch(38.1%_0.176_304.987)] dark:border-[color:var(--zui-marquee-purple-border-dark,var(--zui-color-purple-dark,oklch(71.4%_0.203_305.504_/_0.3)))] dark:[--zui-marquee-bg:oklch(38.1%_0.176_304.987_/_0.28)] dark:[--zui-marquee-fg:oklch(94.6%_0.033_307.174)]",
  pink: "border-[color:var(--zui-marquee-pink-border,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.24)))] [--zui-marquee-bg:oklch(97.1%_0.014_343.198)] [--zui-marquee-fg:oklch(40.8%_0.153_2.432)] dark:border-[color:var(--zui-marquee-pink-border-dark,var(--zui-color-pink-dark,oklch(71.8%_0.202_349.761_/_0.3)))] dark:[--zui-marquee-bg:oklch(40.8%_0.153_2.432_/_0.28)] dark:[--zui-marquee-fg:oklch(94.8%_0.028_342.258)]",
  orange:
    "border-[color:var(--zui-marquee-orange-border,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.26)))] [--zui-marquee-bg:oklch(98%_0.016_73.684)] [--zui-marquee-fg:oklch(40.8%_0.123_38.172)] dark:border-[color:var(--zui-marquee-orange-border-dark,var(--zui-color-orange-dark,oklch(75%_0.183_55.934_/_0.32)))] dark:[--zui-marquee-bg:oklch(40.8%_0.123_38.172_/_0.28)] dark:[--zui-marquee-fg:oklch(95.4%_0.038_75.164)]",
  yellow:
    "border-[color:var(--zui-marquee-yellow-border,var(--zui-color-yellow,oklch(79.5%_0.184_86.047_/_0.3)))] [--zui-marquee-bg:oklch(98.7%_0.026_102.212)] [--zui-marquee-fg:oklch(42.1%_0.095_57.708)] dark:border-[color:var(--zui-marquee-yellow-border-dark,var(--zui-color-yellow-dark,oklch(85.2%_0.199_91.936_/_0.32)))] dark:[--zui-marquee-bg:oklch(42.1%_0.095_57.708_/_0.28)] dark:[--zui-marquee-fg:oklch(97.3%_0.071_103.193)]",
  teal: "border-[color:var(--zui-marquee-teal-border,var(--zui-color-teal,oklch(70.4%_0.14_182.503_/_0.28)))] [--zui-marquee-bg:oklch(98.4%_0.014_180.72)] [--zui-marquee-fg:oklch(38.6%_0.063_188.416)] dark:border-[color:var(--zui-marquee-teal-border-dark,var(--zui-color-teal-dark,oklch(77.7%_0.152_181.912_/_0.32)))] dark:[--zui-marquee-bg:oklch(38.6%_0.063_188.416_/_0.28)] dark:[--zui-marquee-fg:oklch(95.3%_0.051_180.801)]",
  indigo:
    "border-[color:var(--zui-marquee-indigo-border,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.24)))] [--zui-marquee-bg:oklch(96.2%_0.018_272.314)] [--zui-marquee-fg:oklch(35.9%_0.144_278.697)] dark:border-[color:var(--zui-marquee-indigo-border-dark,var(--zui-color-indigo-dark,oklch(67.3%_0.182_276.935_/_0.32)))] dark:[--zui-marquee-bg:oklch(35.9%_0.144_278.697_/_0.28)] dark:[--zui-marquee-fg:oklch(93%_0.034_272.788)]",
  emerald:
    "border-[color:var(--zui-marquee-emerald-border,var(--zui-color-emerald,oklch(69.6%_0.17_162.48_/_0.28)))] [--zui-marquee-bg:oklch(97.9%_0.021_166.113)] [--zui-marquee-fg:oklch(37.8%_0.077_168.94)] dark:border-[color:var(--zui-marquee-emerald-border-dark,var(--zui-color-emerald-dark,oklch(76.5%_0.177_163.223_/_0.32)))] dark:[--zui-marquee-bg:oklch(37.8%_0.077_168.94_/_0.28)] dark:[--zui-marquee-fg:oklch(95%_0.052_163.051)]",
  "gradient-blue":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-blue-from,var(--zui-color-blue,oklch(62.3%_0.214_259.815)))] dark:from-[var(--zui-marquee-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(42.4%_0.199_265.638)))] to-[var(--zui-marquee-gradient-blue-to,var(--zui-color-purple,oklch(54.6%_0.245_262.881)))] dark:to-[var(--zui-marquee-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(37.9%_0.146_265.522)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-green":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-green-from,var(--zui-color-green,oklch(72.3%_0.219_149.579)))] dark:from-[var(--zui-marquee-gradient-green-from-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328)))] to-[var(--zui-marquee-gradient-green-to,var(--zui-color-lime,oklch(62.7%_0.194_149.214)))] dark:to-[var(--zui-marquee-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(39.3%_0.095_152.535)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-red":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-red-from,var(--zui-color-red,oklch(63.7%_0.237_25.331)))] dark:from-[var(--zui-marquee-gradient-red-from-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] to-[var(--zui-marquee-gradient-red-to,var(--zui-color-pink,oklch(57.7%_0.245_27.325)))] dark:to-[var(--zui-marquee-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(39.6%_0.141_25.723)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-yellow":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-yellow-from,var(--zui-color-yellow,oklch(85.2%_0.199_91.936)))] dark:from-[var(--zui-marquee-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] to-[var(--zui-marquee-gradient-yellow-to,var(--zui-color-orange,oklch(79.5%_0.184_86.047)))] dark:to-[var(--zui-marquee-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(42.1%_0.095_57.708)))] [--zui-marquee-fg:oklch(27.9%_0.077_45.635)] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-purple":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-purple-from,var(--zui-color-purple,oklch(71.4%_0.203_305.504)))] dark:from-[var(--zui-marquee-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] to-[var(--zui-marquee-gradient-purple-to,var(--zui-color-pink,oklch(62.7%_0.265_303.9)))] dark:to-[var(--zui-marquee-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(38.1%_0.176_304.987)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-teal":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-teal-from,var(--zui-color-teal,oklch(77.7%_0.152_181.912)))] dark:from-[var(--zui-marquee-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))] to-[var(--zui-marquee-gradient-teal-to,var(--zui-color-cyan,oklch(70.4%_0.14_182.503)))] dark:to-[var(--zui-marquee-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(38.6%_0.063_188.416)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-indigo":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-indigo-from,var(--zui-color-indigo,oklch(67.3%_0.182_276.935)))] dark:from-[var(--zui-marquee-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))] to-[var(--zui-marquee-gradient-indigo-to,var(--zui-color-purple,oklch(58.5%_0.233_277.117)))] dark:to-[var(--zui-marquee-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(35.9%_0.144_278.697)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-pink":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-pink-from,var(--zui-color-pink,oklch(71.8%_0.202_349.761)))] dark:from-[var(--zui-marquee-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] to-[var(--zui-marquee-gradient-pink-to,var(--zui-color-rose,oklch(65.6%_0.241_354.308)))] dark:to-[var(--zui-marquee-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(40.8%_0.153_2.432)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  "gradient-orange":
    "border-transparent bg-linear-to-r from-[var(--zui-marquee-gradient-orange-from,var(--zui-color-orange,oklch(75%_0.183_55.934)))] dark:from-[var(--zui-marquee-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] to-[var(--zui-marquee-gradient-orange-to,var(--zui-color-red,oklch(70.5%_0.213_47.604)))] dark:to-[var(--zui-marquee-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(40.8%_0.123_38.172)))] [--zui-marquee-fg:#ffffff] dark:[--zui-marquee-fg:#ffffff]",
  blue: "border border-[color:var(--zui-marquee-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-marquee-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-marquee-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:bg-[var(--zui-marquee-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))] text-[color:var(--zui-marquee-blue-fg,var(--zui-color-blue,#0f172a))] dark:text-[color:var(--zui-marquee-blue-fg-dark,var(--zui-color-blue-dark,#f8fafc))]",
  cyan: "border border-[color:var(--zui-marquee-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-marquee-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-marquee-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:bg-[var(--zui-marquee-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))] text-[color:var(--zui-marquee-cyan-fg,var(--zui-color-cyan,#0f172a))] dark:text-[color:var(--zui-marquee-cyan-fg-dark,var(--zui-color-cyan-dark,#f8fafc))]",
  green:
    "border border-[color:var(--zui-marquee-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-marquee-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-marquee-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:bg-[var(--zui-marquee-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))] text-[color:var(--zui-marquee-green-fg,var(--zui-color-green,#0f172a))] dark:text-[color:var(--zui-marquee-green-fg-dark,var(--zui-color-green-dark,#f8fafc))]",
  lime: "border border-[color:var(--zui-marquee-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-marquee-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-marquee-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:bg-[var(--zui-marquee-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))] text-[color:var(--zui-marquee-lime-fg,var(--zui-color-lime,#0f172a))] dark:text-[color:var(--zui-marquee-lime-fg-dark,var(--zui-color-lime-dark,#f8fafc))]",
  mint: "border border-[color:var(--zui-marquee-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-marquee-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-marquee-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:bg-[var(--zui-marquee-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))] text-[color:var(--zui-marquee-mint-fg,var(--zui-color-mint,#0f172a))] dark:text-[color:var(--zui-marquee-mint-fg-dark,var(--zui-color-mint-dark,#f8fafc))]",
  ocean:
    "border border-[color:var(--zui-marquee-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-marquee-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-marquee-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:bg-[var(--zui-marquee-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-marquee-ocean-fg,var(--zui-color-ocean,#0f172a))] dark:text-[color:var(--zui-marquee-ocean-fg-dark,var(--zui-color-ocean-dark,#f8fafc))]",
  sapphire:
    "border border-[color:var(--zui-marquee-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-marquee-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-marquee-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:bg-[var(--zui-marquee-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))] text-[color:var(--zui-marquee-sapphire-fg,var(--zui-color-sapphire,#0f172a))] dark:text-[color:var(--zui-marquee-sapphire-fg-dark,var(--zui-color-sapphire-dark,#f8fafc))]",
  lavender:
    "border border-[color:var(--zui-marquee-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-marquee-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-marquee-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:bg-[var(--zui-marquee-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))] text-[color:var(--zui-marquee-lavender-fg,var(--zui-color-lavender,#0f172a))] dark:text-[color:var(--zui-marquee-lavender-fg-dark,var(--zui-color-lavender-dark,#f8fafc))]",
  ruby: "border border-[color:var(--zui-marquee-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-marquee-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-marquee-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:bg-[var(--zui-marquee-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))] text-[color:var(--zui-marquee-ruby-fg,var(--zui-color-ruby,#0f172a))] dark:text-[color:var(--zui-marquee-ruby-fg-dark,var(--zui-color-ruby-dark,#f8fafc))]",
  red: "border border-[color:var(--zui-marquee-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-marquee-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-marquee-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:bg-[var(--zui-marquee-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))] text-[color:var(--zui-marquee-red-fg,var(--zui-color-red,#0f172a))] dark:text-[color:var(--zui-marquee-red-fg-dark,var(--zui-color-red-dark,#f8fafc))]",
  slate:
    "border border-[color:var(--zui-marquee-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-marquee-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-marquee-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:bg-[var(--zui-marquee-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))] text-[color:var(--zui-marquee-slate-fg,var(--zui-color-slate,#0f172a))] dark:text-[color:var(--zui-marquee-slate-fg-dark,var(--zui-color-slate-dark,#f8fafc))]",
  zinc: "border border-[color:var(--zui-marquee-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-marquee-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-marquee-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:bg-[var(--zui-marquee-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))] text-[color:var(--zui-marquee-zinc-fg,var(--zui-color-zinc,#0f172a))] dark:text-[color:var(--zui-marquee-zinc-fg-dark,var(--zui-color-zinc-dark,#f8fafc))]",
  stone:
    "border border-[color:var(--zui-marquee-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-marquee-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-marquee-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:bg-[var(--zui-marquee-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))] text-[color:var(--zui-marquee-stone-fg,var(--zui-color-stone,#0f172a))] dark:text-[color:var(--zui-marquee-stone-fg-dark,var(--zui-color-stone-dark,#f8fafc))]",
  royal:
    "border border-[color:var(--zui-marquee-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-marquee-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-marquee-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:bg-[var(--zui-marquee-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))] text-[color:var(--zui-marquee-royal-fg,var(--zui-color-royal,#0f172a))] dark:text-[color:var(--zui-marquee-royal-fg-dark,var(--zui-color-royal-dark,#f8fafc))]",
  electric:
    "border border-[color:var(--zui-marquee-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-marquee-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-marquee-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:bg-[var(--zui-marquee-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-marquee-electric-fg,var(--zui-color-electric,#0f172a))] dark:text-[color:var(--zui-marquee-electric-fg-dark,var(--zui-color-electric-dark,#f8fafc))]",
  forest:
    "border border-[color:var(--zui-marquee-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-marquee-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-marquee-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:bg-[var(--zui-marquee-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))] text-[color:var(--zui-marquee-forest-fg,var(--zui-color-forest,#0f172a))] dark:text-[color:var(--zui-marquee-forest-fg-dark,var(--zui-color-forest-dark,#f8fafc))]",
  sunset:
    "border border-[color:var(--zui-marquee-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-marquee-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-marquee-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:bg-[var(--zui-marquee-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))] text-[color:var(--zui-marquee-sunset-fg,var(--zui-color-sunset,#0f172a))] dark:text-[color:var(--zui-marquee-sunset-fg-dark,var(--zui-color-sunset-dark,#f8fafc))]",
  magenta:
    "border border-[color:var(--zui-marquee-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-marquee-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-marquee-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:bg-[var(--zui-marquee-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))] text-[color:var(--zui-marquee-magenta-fg,var(--zui-color-magenta,#0f172a))] dark:text-[color:var(--zui-marquee-magenta-fg-dark,var(--zui-color-magenta-dark,#f8fafc))]",
  crimson:
    "border border-[color:var(--zui-marquee-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-marquee-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-marquee-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:bg-[var(--zui-marquee-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))] text-[color:var(--zui-marquee-crimson-fg,var(--zui-color-crimson,#0f172a))] dark:text-[color:var(--zui-marquee-crimson-fg-dark,var(--zui-color-crimson-dark,#f8fafc))]",
  aqua: "border border-[color:var(--zui-marquee-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-marquee-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-marquee-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:bg-[var(--zui-marquee-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))] text-[color:var(--zui-marquee-aqua-fg,var(--zui-color-aqua,#0f172a))] dark:text-[color:var(--zui-marquee-aqua-fg-dark,var(--zui-color-aqua-dark,#f8fafc))]",
  plum: "border border-[color:var(--zui-marquee-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-marquee-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-marquee-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:bg-[var(--zui-marquee-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))] text-[color:var(--zui-marquee-plum-fg,var(--zui-color-plum,#0f172a))] dark:text-[color:var(--zui-marquee-plum-fg-dark,var(--zui-color-plum-dark,#f8fafc))]",
} as const;

export const zuiMarqueeOrientations = {
  horizontal: "w-full flex-row",
  vertical: "h-64 flex-col",
} as const;

export const zuiMarqueeSizes = {
  sm: "p-2 text-xs",
  md: "p-3 text-sm",
  lg: "p-4 text-base",
} as const;

export const zuiMarqueeFade = {
  false: "",
  true: "[mask-image:linear-gradient(to_right,transparent,black_12%,black_88%,transparent)] data-[orientation=vertical]:[mask-image:linear-gradient(to_bottom,transparent,black_12%,black_88%,transparent)]",
} as const;
