export const zuiModalOverlayBase =
  "fixed inset-0 z-50 bg-[var(--zui-modal-overlay-bg,color-mix(in oklch, var(--zui-fg,oklch(12.9%_0.042_264.695_/_0.7)) 60%, transparent))] dark:bg-[var(--zui-modal-overlay-bg-dark,color-mix(in oklch, var(--zui-fg-dark,oklch(12.9%_0.042_264.695_/_0.7)) 60%, transparent))] backdrop-blur-sm data-[state=open]:animate-in";

export const zuiModalTriggerBase =
  "relative inline-flex shrink-0 cursor-pointer rounded-md border";

export const zuiModalTriggerAppearances = {
  default:
    "bg-[var(--zui-modal-trigger-default-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-modal-trigger-default-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] text-[color:var(--zui-modal-trigger-default-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-modal-trigger-default-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))]",
  glass:
    "border-[color:var(--zui-modal-trigger-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-modal-trigger-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-modal-trigger-glass-bg,var(--zui-surface-soft,oklch(98.4%_0.003_247.858_/_0.7)))] dark:bg-[var(--zui-modal-trigger-glass-bg-dark,var(--zui-surface-soft-dark,oklch(12.9%_0.042_264.695_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-glass-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-modal-trigger-glass-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))]",
  sky: "border-[color:var(--zui-modal-trigger-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-modal-trigger-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] bg-[var(--zui-modal-trigger-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(97.7%_0.013_236.62)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(29.3%_0.066_243.157_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-sky-fg,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:text-[color:var(--zui-modal-trigger-sky-fg-dark,var(--zui-color-sky-dark,oklch(97.7%_0.013_236.62)))]",
  rose: "border-[color:var(--zui-modal-trigger-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-modal-trigger-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] bg-[var(--zui-modal-trigger-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(96.9%_0.015_12.422)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-rose-fg,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:text-[color:var(--zui-modal-trigger-rose-fg-dark,var(--zui-color-rose-dark,oklch(96.9%_0.015_12.422)))]",
  purple:
    "border-[color:var(--zui-modal-trigger-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-modal-trigger-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-modal-trigger-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(97.7%_0.014_308.299)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-purple-fg,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:text-[color:var(--zui-modal-trigger-purple-fg-dark,var(--zui-color-purple-dark,oklch(97.7%_0.014_308.299)))]",
  pink: "border-[color:var(--zui-modal-trigger-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-modal-trigger-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-modal-trigger-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(97.1%_0.014_343.198)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-pink-fg,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:text-[color:var(--zui-modal-trigger-pink-fg-dark,var(--zui-color-pink-dark,oklch(97.1%_0.014_343.198)))]",
  orange:
    "border-[color:var(--zui-modal-trigger-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-modal-trigger-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-modal-trigger-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(98%_0.016_73.684)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-orange-fg,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:text-[color:var(--zui-modal-trigger-orange-fg-dark,var(--zui-color-orange-dark,oklch(98%_0.016_73.684)))]",
  yellow:
    "border-[color:var(--zui-modal-trigger-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-modal-trigger-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-modal-trigger-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(98.7%_0.026_102.212)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-yellow-fg,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:text-[color:var(--zui-modal-trigger-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(98.7%_0.026_102.212)))]",
  teal: "border-[color:var(--zui-modal-trigger-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-modal-trigger-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-modal-trigger-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(98.4%_0.014_180.72)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-teal-fg,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:text-[color:var(--zui-modal-trigger-teal-fg-dark,var(--zui-color-teal-dark,oklch(98.4%_0.014_180.72)))]",
  indigo:
    "border-[color:var(--zui-modal-trigger-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-modal-trigger-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-modal-trigger-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(96.2%_0.018_272.314)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-indigo-fg,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:text-[color:var(--zui-modal-trigger-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(96.2%_0.018_272.314)))]",
  emerald:
    "border-[color:var(--zui-modal-trigger-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-modal-trigger-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] bg-[var(--zui-modal-trigger-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(97.9%_0.021_166.113)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(26.2%_0.051_172.552_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-emerald-fg,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:text-[color:var(--zui-modal-trigger-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(97.9%_0.021_166.113)))]",
  gray: "border-[color:var(--zui-modal-trigger-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-modal-trigger-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] bg-[var(--zui-modal-trigger-gray-bg,color-mix(in oklch, var(--zui-color-gray,oklch(98.5%_0.002_247.839)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-gray-bg-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(13%_0.028_261.692_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gray-fg,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:text-[color:var(--zui-modal-trigger-gray-fg-dark,var(--zui-color-gray-dark,oklch(98.5%_0.002_247.839)))]",
  amber:
    "border-[color:var(--zui-modal-trigger-amber-border,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:border-[color:var(--zui-modal-trigger-amber-border-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] bg-[var(--zui-modal-trigger-amber-bg,color-mix(in oklch, var(--zui-color-amber,oklch(98.7%_0.022_95.277)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-amber-bg-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(27.9%_0.077_45.635_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-amber-fg,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:text-[color:var(--zui-modal-trigger-amber-fg-dark,var(--zui-color-amber-dark,oklch(98.7%_0.022_95.277)))]",
  violet:
    "border-[color:var(--zui-modal-trigger-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-modal-trigger-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-modal-trigger-violet-bg,color-mix(in oklch, var(--zui-color-violet,oklch(96.9%_0.016_293.756)) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-violet-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(28.3%_0.141_291.089_/_0.7)) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-violet-fg,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:text-[color:var(--zui-modal-trigger-violet-fg-dark,var(--zui-color-violet-dark,oklch(96.9%_0.016_293.756)))]",
  "gradient-blue":
    "border-[color:var(--zui-modal-trigger-gradient-blue-border,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:border-[color:var(--zui-modal-trigger-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:from-[var(--zui-modal-trigger-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(28.2%_0.091_267.935_/_0.7)))] to-[var(--zui-modal-trigger-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-modal-trigger-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-blue-fg,var(--zui-brand-fg,oklch(42.4%_0.199_265.638)))] dark:text-[color:var(--zui-modal-trigger-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(97%_0.014_254.604)))]",
  "gradient-green":
    "border-[color:var(--zui-modal-trigger-gradient-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:border-[color:var(--zui-modal-trigger-gradient-green-border-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:from-[var(--zui-modal-trigger-gradient-green-from-dark,var(--zui-color-green-dark,oklch(26.6%_0.065_152.934_/_0.7)))] to-[var(--zui-modal-trigger-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:to-[var(--zui-modal-trigger-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(27.4%_0.072_132.109_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-green-fg,var(--zui-brand-fg,oklch(44.8%_0.119_151.328)))] dark:text-[color:var(--zui-modal-trigger-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(98.2%_0.018_155.826)))]",
  "gradient-red":
    "border-[color:var(--zui-modal-trigger-gradient-red-border,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:border-[color:var(--zui-modal-trigger-gradient-red-border-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:from-[var(--zui-modal-trigger-gradient-red-from-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] to-[var(--zui-modal-trigger-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-modal-trigger-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-red-fg,var(--zui-brand-fg,oklch(44.4%_0.177_26.899)))] dark:text-[color:var(--zui-modal-trigger-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(97.1%_0.013_17.38)))]",
  "gradient-yellow":
    "border-[color:var(--zui-modal-trigger-gradient-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-modal-trigger-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:from-[var(--zui-modal-trigger-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)))] to-[var(--zui-modal-trigger-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:to-[var(--zui-modal-trigger-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-yellow-fg,var(--zui-brand-fg,oklch(47.6%_0.114_61.907)))] dark:text-[color:var(--zui-modal-trigger-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(98.7%_0.026_102.212)))]",
  "gradient-purple":
    "border-[color:var(--zui-modal-trigger-gradient-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-modal-trigger-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:from-[var(--zui-modal-trigger-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] to-[var(--zui-modal-trigger-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-modal-trigger-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-purple-fg,var(--zui-brand-fg,oklch(43.8%_0.218_303.724)))] dark:text-[color:var(--zui-modal-trigger-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(97.7%_0.014_308.299)))]",
  "gradient-teal":
    "border-[color:var(--zui-modal-trigger-gradient-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-modal-trigger-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:from-[var(--zui-modal-trigger-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)))] to-[var(--zui-modal-trigger-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:to-[var(--zui-modal-trigger-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(30.2%_0.056_229.695_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-teal-fg,var(--zui-brand-fg,oklch(43.7%_0.078_188.216)))] dark:text-[color:var(--zui-modal-trigger-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.014_180.72)))]",
  "gradient-indigo":
    "border-[color:var(--zui-modal-trigger-gradient-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-modal-trigger-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:from-[var(--zui-modal-trigger-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)))] to-[var(--zui-modal-trigger-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-modal-trigger-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-indigo-fg,var(--zui-brand-fg,oklch(39.8%_0.195_277.366)))] dark:text-[color:var(--zui-modal-trigger-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(96.2%_0.018_272.314)))]",
  "gradient-pink":
    "border-[color:var(--zui-modal-trigger-gradient-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-modal-trigger-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:from-[var(--zui-modal-trigger-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] to-[var(--zui-modal-trigger-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:to-[var(--zui-modal-trigger-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-pink-fg,var(--zui-brand-fg,oklch(45.9%_0.187_3.815)))] dark:text-[color:var(--zui-modal-trigger-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(97.1%_0.014_343.198)))]",
  "gradient-orange":
    "border-[color:var(--zui-modal-trigger-gradient-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-modal-trigger-gradient-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-linear-to-r from-[var(--zui-modal-trigger-gradient-orange-from,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:from-[var(--zui-modal-trigger-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] to-[var(--zui-modal-trigger-gradient-orange-to,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:to-[var(--zui-modal-trigger-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-gradient-orange-fg,var(--zui-brand-fg,oklch(47%_0.157_37.304)))] dark:text-[color:var(--zui-modal-trigger-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(98%_0.016_73.684)))]",
  blue: "border border-[color:var(--zui-modal-trigger-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-modal-trigger-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-modal-trigger-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-modal-trigger-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] hover:bg-[var(--zui-modal-trigger-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f62e) 18%, transparent))]",
  cyan: "border border-[color:var(--zui-modal-trigger-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-modal-trigger-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-modal-trigger-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-modal-trigger-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] hover:bg-[var(--zui-modal-trigger-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b218) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee2e) 18%, transparent))]",
  green:
    "border border-[color:var(--zui-modal-trigger-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-modal-trigger-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-modal-trigger-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-modal-trigger-green-fg-dark,var(--zui-color-green-dark,#22c55e))] hover:bg-[var(--zui-modal-trigger-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e2e) 18%, transparent))]",
  lime: "border border-[color:var(--zui-modal-trigger-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-modal-trigger-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-modal-trigger-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-modal-trigger-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] hover:bg-[var(--zui-modal-trigger-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e6352e) 18%, transparent))]",
  mint: "border border-[color:var(--zui-modal-trigger-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-modal-trigger-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-modal-trigger-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-modal-trigger-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] hover:bg-[var(--zui-modal-trigger-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98118) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b72e) 18%, transparent))]",
  ocean:
    "border border-[color:var(--zui-modal-trigger-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-modal-trigger-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-modal-trigger-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-modal-trigger-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] hover:bg-[var(--zui-modal-trigger-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c718) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf82e) 18%, transparent))]",
  sapphire:
    "border border-[color:var(--zui-modal-trigger-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-modal-trigger-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-modal-trigger-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-modal-trigger-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] hover:bg-[var(--zui-modal-trigger-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed818) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa2e) 18%, transparent))]",
  lavender:
    "border border-[color:var(--zui-modal-trigger-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-modal-trigger-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-modal-trigger-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-modal-trigger-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] hover:bg-[var(--zui-modal-trigger-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf618) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa2e) 18%, transparent))]",
  ruby: "border border-[color:var(--zui-modal-trigger-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-modal-trigger-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-modal-trigger-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-modal-trigger-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] hover:bg-[var(--zui-modal-trigger-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb71852e) 18%, transparent))]",
  red: "border border-[color:var(--zui-modal-trigger-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-modal-trigger-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-modal-trigger-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-modal-trigger-red-fg-dark,var(--zui-color-red-dark,#ef4444))] hover:bg-[var(--zui-modal-trigger-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262618) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44442e) 18%, transparent))]",
  slate:
    "border border-[color:var(--zui-modal-trigger-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-modal-trigger-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-modal-trigger-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-modal-trigger-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] hover:bg-[var(--zui-modal-trigger-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556918) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b2e) 18%, transparent))]",
  zinc: "border border-[color:var(--zui-modal-trigger-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-modal-trigger-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-modal-trigger-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-modal-trigger-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] hover:bg-[var(--zui-modal-trigger-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a2e) 18%, transparent))]",
  stone:
    "border border-[color:var(--zui-modal-trigger-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-modal-trigger-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-modal-trigger-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-modal-trigger-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] hover:bg-[var(--zui-modal-trigger-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c2e) 18%, transparent))]",
  royal:
    "border border-[color:var(--zui-modal-trigger-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-modal-trigger-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-modal-trigger-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-modal-trigger-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] hover:bg-[var(--zui-modal-trigger-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf82e) 18%, transparent))]",
  electric:
    "border border-[color:var(--zui-modal-trigger-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-modal-trigger-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-modal-trigger-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-modal-trigger-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] hover:bg-[var(--zui-modal-trigger-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e918) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf82e) 18%, transparent))]",
  forest:
    "border border-[color:var(--zui-modal-trigger-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-modal-trigger-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-modal-trigger-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-modal-trigger-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] hover:bg-[var(--zui-modal-trigger-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653418) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade802e) 18%, transparent))]",
  sunset:
    "border border-[color:var(--zui-modal-trigger-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-modal-trigger-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-modal-trigger-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-modal-trigger-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] hover:bg-[var(--zui-modal-trigger-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c2e) 18%, transparent))]",
  magenta:
    "border border-[color:var(--zui-modal-trigger-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-modal-trigger-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-modal-trigger-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-modal-trigger-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] hover:bg-[var(--zui-modal-trigger-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d318) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f92e) 18%, transparent))]",
  crimson:
    "border border-[color:var(--zui-modal-trigger-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-modal-trigger-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-modal-trigger-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-modal-trigger-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] hover:bg-[var(--zui-modal-trigger-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f871712e) 18%, transparent))]",
  aqua: "border border-[color:var(--zui-modal-trigger-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-modal-trigger-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-modal-trigger-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-modal-trigger-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] hover:bg-[var(--zui-modal-trigger-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf2e) 18%, transparent))]",
  plum: "border border-[color:var(--zui-modal-trigger-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-modal-trigger-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-modal-trigger-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:bg-[var(--zui-modal-trigger-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))] backdrop-blur-xl text-[color:var(--zui-modal-trigger-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-modal-trigger-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] hover:bg-[var(--zui-modal-trigger-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce18) 10%, transparent))] dark:hover:bg-[var(--zui-modal-trigger-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc2e) 18%, transparent))]",
} as const;

export const zuiModalContentBase =
  "fixed left-1/2 z-50 w-[calc(100%-2rem)] max-h-[min(90vh,720px)] translate-x-[-50%] overflow-y-auto border border-[color:var(--zui-modal-content-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-modal-content-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-modal-content-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-modal-content-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] p-6 text-[color:var(--zui-modal-content-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-modal-content-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] shadow-[var(--zui-modal-content-shadow,var(--zui-shadow,0_12px_40px_rgba(15,23,42,0.14)))] dark:shadow-[var(--zui-modal-content-shadow-dark,var(--zui-shadow-dark,0_24px_80px_rgba(15,23,42,0.55)))] focus:outline-none";

export const zuiModalContentSizes = {
  sm: "max-w-md",
  md: "max-w-lg",
  lg: "max-w-2xl",
  xl: "max-w-4xl",
  full: "max-w-[calc(100%-2rem)]",
} as const;

export const zuiModalContentPositions = {
  center: "top-1/2 translate-y-[-50%]",
  top: "top-10 translate-y-0",
  bottom: "bottom-10 translate-y-0",
} as const;

export const zuiModalContentAppearances = {
  default:
    "bg-[var(--zui-modal-content-default-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-modal-content-default-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))]",
  glass:
    "border-[color:var(--zui-modal-content-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-modal-content-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-modal-content-glass-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858_/_0.7)))] dark:bg-[var(--zui-modal-content-glass-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695_/_0.7)))] backdrop-blur-xl",
  sky: "border-[color:var(--zui-modal-content-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-modal-content-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] bg-[var(--zui-modal-content-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(97.7%_0.013_236.62)) 10%, transparent))] dark:bg-[var(--zui-modal-content-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(29.3%_0.066_243.157_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  rose: "border-[color:var(--zui-modal-content-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-modal-content-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] bg-[var(--zui-modal-content-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(96.9%_0.015_12.422)) 10%, transparent))] dark:bg-[var(--zui-modal-content-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  purple:
    "border-[color:var(--zui-modal-content-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-modal-content-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-modal-content-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(97.7%_0.014_308.299)) 10%, transparent))] dark:bg-[var(--zui-modal-content-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  pink: "border-[color:var(--zui-modal-content-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-modal-content-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-modal-content-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(97.1%_0.014_343.198)) 10%, transparent))] dark:bg-[var(--zui-modal-content-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  orange:
    "border-[color:var(--zui-modal-content-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-modal-content-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-modal-content-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(98%_0.016_73.684)) 10%, transparent))] dark:bg-[var(--zui-modal-content-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  yellow:
    "border-[color:var(--zui-modal-content-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-modal-content-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-modal-content-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(98.7%_0.026_102.212)) 10%, transparent))] dark:bg-[var(--zui-modal-content-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  teal: "border-[color:var(--zui-modal-content-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-modal-content-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-modal-content-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(98.4%_0.014_180.72)) 10%, transparent))] dark:bg-[var(--zui-modal-content-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  indigo:
    "border-[color:var(--zui-modal-content-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-modal-content-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-modal-content-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(96.2%_0.018_272.314)) 10%, transparent))] dark:bg-[var(--zui-modal-content-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  emerald:
    "border-[color:var(--zui-modal-content-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-modal-content-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] bg-[var(--zui-modal-content-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(97.9%_0.021_166.113)) 10%, transparent))] dark:bg-[var(--zui-modal-content-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(26.2%_0.051_172.552_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  gray: "border-[color:var(--zui-modal-content-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-modal-content-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] bg-[var(--zui-modal-content-gray-bg,color-mix(in oklch, var(--zui-color-gray,oklch(98.5%_0.002_247.839)) 10%, transparent))] dark:bg-[var(--zui-modal-content-gray-bg-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(13%_0.028_261.692_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  amber:
    "border-[color:var(--zui-modal-content-amber-border,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:border-[color:var(--zui-modal-content-amber-border-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] bg-[var(--zui-modal-content-amber-bg,color-mix(in oklch, var(--zui-color-amber,oklch(98.7%_0.022_95.277)) 10%, transparent))] dark:bg-[var(--zui-modal-content-amber-bg-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(27.9%_0.077_45.635_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  violet:
    "border-[color:var(--zui-modal-content-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-modal-content-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-modal-content-violet-bg,color-mix(in oklch, var(--zui-color-violet,oklch(96.9%_0.016_293.756)) 10%, transparent))] dark:bg-[var(--zui-modal-content-violet-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(28.3%_0.141_291.089_/_0.7)) 18%, transparent))] backdrop-blur-xl",
  "gradient-blue":
    "border-[color:var(--zui-modal-content-gradient-blue-border,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:border-[color:var(--zui-modal-content-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:from-[var(--zui-modal-content-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(28.2%_0.091_267.935_/_0.7)))] to-[var(--zui-modal-content-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-modal-content-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl",
  "gradient-green":
    "border-[color:var(--zui-modal-content-gradient-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:border-[color:var(--zui-modal-content-gradient-green-border-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:from-[var(--zui-modal-content-gradient-green-from-dark,var(--zui-color-green-dark,oklch(26.6%_0.065_152.934_/_0.7)))] to-[var(--zui-modal-content-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:to-[var(--zui-modal-content-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(27.4%_0.072_132.109_/_0.7)))] backdrop-blur-xl",
  "gradient-red":
    "border-[color:var(--zui-modal-content-gradient-red-border,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:border-[color:var(--zui-modal-content-gradient-red-border-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:from-[var(--zui-modal-content-gradient-red-from-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] to-[var(--zui-modal-content-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-modal-content-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl",
  "gradient-yellow":
    "border-[color:var(--zui-modal-content-gradient-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-modal-content-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:from-[var(--zui-modal-content-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)))] to-[var(--zui-modal-content-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:to-[var(--zui-modal-content-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] backdrop-blur-xl",
  "gradient-purple":
    "border-[color:var(--zui-modal-content-gradient-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-modal-content-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:from-[var(--zui-modal-content-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] to-[var(--zui-modal-content-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-modal-content-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl",
  "gradient-teal":
    "border-[color:var(--zui-modal-content-gradient-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-modal-content-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:from-[var(--zui-modal-content-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)))] to-[var(--zui-modal-content-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:to-[var(--zui-modal-content-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(30.2%_0.056_229.695_/_0.7)))] backdrop-blur-xl",
  "gradient-indigo":
    "border-[color:var(--zui-modal-content-gradient-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-modal-content-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:from-[var(--zui-modal-content-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)))] to-[var(--zui-modal-content-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-modal-content-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl",
  "gradient-pink":
    "border-[color:var(--zui-modal-content-gradient-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-modal-content-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:from-[var(--zui-modal-content-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] to-[var(--zui-modal-content-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:to-[var(--zui-modal-content-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.7)))] backdrop-blur-xl",
  "gradient-orange":
    "border-[color:var(--zui-modal-content-gradient-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-modal-content-gradient-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-linear-to-r from-[var(--zui-modal-content-gradient-orange-from,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:from-[var(--zui-modal-content-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] to-[var(--zui-modal-content-gradient-orange-to,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:to-[var(--zui-modal-content-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] backdrop-blur-xl",
  blue: "border border-[color:var(--zui-modal-content-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-modal-content-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-modal-content-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:bg-[var(--zui-modal-content-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))] text-[color:var(--zui-modal-content-blue-fg,var(--zui-color-blue,#0f172a))] dark:text-[color:var(--zui-modal-content-blue-fg-dark,var(--zui-color-blue-dark,#f8fafc))] backdrop-blur-xl",
  cyan: "border border-[color:var(--zui-modal-content-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-modal-content-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-modal-content-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:bg-[var(--zui-modal-content-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))] text-[color:var(--zui-modal-content-cyan-fg,var(--zui-color-cyan,#0f172a))] dark:text-[color:var(--zui-modal-content-cyan-fg-dark,var(--zui-color-cyan-dark,#f8fafc))] backdrop-blur-xl",
  green:
    "border border-[color:var(--zui-modal-content-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-modal-content-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-modal-content-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:bg-[var(--zui-modal-content-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))] text-[color:var(--zui-modal-content-green-fg,var(--zui-color-green,#0f172a))] dark:text-[color:var(--zui-modal-content-green-fg-dark,var(--zui-color-green-dark,#f8fafc))] backdrop-blur-xl",
  lime: "border border-[color:var(--zui-modal-content-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-modal-content-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-modal-content-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:bg-[var(--zui-modal-content-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))] text-[color:var(--zui-modal-content-lime-fg,var(--zui-color-lime,#0f172a))] dark:text-[color:var(--zui-modal-content-lime-fg-dark,var(--zui-color-lime-dark,#f8fafc))] backdrop-blur-xl",
  mint: "border border-[color:var(--zui-modal-content-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-modal-content-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-modal-content-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:bg-[var(--zui-modal-content-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))] text-[color:var(--zui-modal-content-mint-fg,var(--zui-color-mint,#0f172a))] dark:text-[color:var(--zui-modal-content-mint-fg-dark,var(--zui-color-mint-dark,#f8fafc))] backdrop-blur-xl",
  ocean:
    "border border-[color:var(--zui-modal-content-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-modal-content-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-modal-content-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:bg-[var(--zui-modal-content-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-modal-content-ocean-fg,var(--zui-color-ocean,#0f172a))] dark:text-[color:var(--zui-modal-content-ocean-fg-dark,var(--zui-color-ocean-dark,#f8fafc))] backdrop-blur-xl",
  sapphire:
    "border border-[color:var(--zui-modal-content-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-modal-content-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-modal-content-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:bg-[var(--zui-modal-content-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))] text-[color:var(--zui-modal-content-sapphire-fg,var(--zui-color-sapphire,#0f172a))] dark:text-[color:var(--zui-modal-content-sapphire-fg-dark,var(--zui-color-sapphire-dark,#f8fafc))] backdrop-blur-xl",
  lavender:
    "border border-[color:var(--zui-modal-content-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-modal-content-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-modal-content-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:bg-[var(--zui-modal-content-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))] text-[color:var(--zui-modal-content-lavender-fg,var(--zui-color-lavender,#0f172a))] dark:text-[color:var(--zui-modal-content-lavender-fg-dark,var(--zui-color-lavender-dark,#f8fafc))] backdrop-blur-xl",
  ruby: "border border-[color:var(--zui-modal-content-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-modal-content-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-modal-content-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:bg-[var(--zui-modal-content-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))] text-[color:var(--zui-modal-content-ruby-fg,var(--zui-color-ruby,#0f172a))] dark:text-[color:var(--zui-modal-content-ruby-fg-dark,var(--zui-color-ruby-dark,#f8fafc))] backdrop-blur-xl",
  red: "border border-[color:var(--zui-modal-content-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-modal-content-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-modal-content-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:bg-[var(--zui-modal-content-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))] text-[color:var(--zui-modal-content-red-fg,var(--zui-color-red,#0f172a))] dark:text-[color:var(--zui-modal-content-red-fg-dark,var(--zui-color-red-dark,#f8fafc))] backdrop-blur-xl",
  slate:
    "border border-[color:var(--zui-modal-content-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-modal-content-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-modal-content-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:bg-[var(--zui-modal-content-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))] text-[color:var(--zui-modal-content-slate-fg,var(--zui-color-slate,#0f172a))] dark:text-[color:var(--zui-modal-content-slate-fg-dark,var(--zui-color-slate-dark,#f8fafc))] backdrop-blur-xl",
  zinc: "border border-[color:var(--zui-modal-content-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-modal-content-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-modal-content-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:bg-[var(--zui-modal-content-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))] text-[color:var(--zui-modal-content-zinc-fg,var(--zui-color-zinc,#0f172a))] dark:text-[color:var(--zui-modal-content-zinc-fg-dark,var(--zui-color-zinc-dark,#f8fafc))] backdrop-blur-xl",
  stone:
    "border border-[color:var(--zui-modal-content-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-modal-content-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-modal-content-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:bg-[var(--zui-modal-content-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))] text-[color:var(--zui-modal-content-stone-fg,var(--zui-color-stone,#0f172a))] dark:text-[color:var(--zui-modal-content-stone-fg-dark,var(--zui-color-stone-dark,#f8fafc))] backdrop-blur-xl",
  royal:
    "border border-[color:var(--zui-modal-content-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-modal-content-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-modal-content-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:bg-[var(--zui-modal-content-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))] text-[color:var(--zui-modal-content-royal-fg,var(--zui-color-royal,#0f172a))] dark:text-[color:var(--zui-modal-content-royal-fg-dark,var(--zui-color-royal-dark,#f8fafc))] backdrop-blur-xl",
  electric:
    "border border-[color:var(--zui-modal-content-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-modal-content-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-modal-content-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:bg-[var(--zui-modal-content-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-modal-content-electric-fg,var(--zui-color-electric,#0f172a))] dark:text-[color:var(--zui-modal-content-electric-fg-dark,var(--zui-color-electric-dark,#f8fafc))] backdrop-blur-xl",
  forest:
    "border border-[color:var(--zui-modal-content-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-modal-content-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-modal-content-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:bg-[var(--zui-modal-content-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))] text-[color:var(--zui-modal-content-forest-fg,var(--zui-color-forest,#0f172a))] dark:text-[color:var(--zui-modal-content-forest-fg-dark,var(--zui-color-forest-dark,#f8fafc))] backdrop-blur-xl",
  sunset:
    "border border-[color:var(--zui-modal-content-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-modal-content-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-modal-content-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:bg-[var(--zui-modal-content-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))] text-[color:var(--zui-modal-content-sunset-fg,var(--zui-color-sunset,#0f172a))] dark:text-[color:var(--zui-modal-content-sunset-fg-dark,var(--zui-color-sunset-dark,#f8fafc))] backdrop-blur-xl",
  magenta:
    "border border-[color:var(--zui-modal-content-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-modal-content-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-modal-content-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:bg-[var(--zui-modal-content-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))] text-[color:var(--zui-modal-content-magenta-fg,var(--zui-color-magenta,#0f172a))] dark:text-[color:var(--zui-modal-content-magenta-fg-dark,var(--zui-color-magenta-dark,#f8fafc))] backdrop-blur-xl",
  crimson:
    "border border-[color:var(--zui-modal-content-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-modal-content-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-modal-content-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:bg-[var(--zui-modal-content-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))] text-[color:var(--zui-modal-content-crimson-fg,var(--zui-color-crimson,#0f172a))] dark:text-[color:var(--zui-modal-content-crimson-fg-dark,var(--zui-color-crimson-dark,#f8fafc))] backdrop-blur-xl",
  aqua: "border border-[color:var(--zui-modal-content-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-modal-content-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-modal-content-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:bg-[var(--zui-modal-content-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))] text-[color:var(--zui-modal-content-aqua-fg,var(--zui-color-aqua,#0f172a))] dark:text-[color:var(--zui-modal-content-aqua-fg-dark,var(--zui-color-aqua-dark,#f8fafc))] backdrop-blur-xl",
  plum: "border border-[color:var(--zui-modal-content-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-modal-content-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-modal-content-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:bg-[var(--zui-modal-content-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))] text-[color:var(--zui-modal-content-plum-fg,var(--zui-color-plum,#0f172a))] dark:text-[color:var(--zui-modal-content-plum-fg-dark,var(--zui-color-plum-dark,#f8fafc))] backdrop-blur-xl",
} as const;
