export const zuiOtpRootBase =
  "grid w-fit gap-2 text-[color:var(--zui-otp-label-fg,var(--zui-fg-muted,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-otp-label-fg-dark,var(--zui-fg-muted-dark,oklch(98.4%_0.003_247.858)))] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiOtpLabelBase =
  "text-sm font-medium leading-6 text-[color:var(--zui-otp-label-fg,var(--zui-fg-muted,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-otp-label-fg-dark,var(--zui-fg-muted-dark,oklch(98.4%_0.003_247.858)))]";

export const zuiOtpHintBase =
  "max-w-sm text-xs leading-5 text-[color:var(--zui-otp-hint-fg,var(--zui-fg-muted,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-otp-hint-fg-dark,var(--zui-fg-muted-dark,oklch(70.4%_0.04_256.788)))]";

export const zuiOtpCellsBase = "flex flex-wrap items-center gap-2";

export const zuiOtpCellBase =
  "grid place-items-center rounded-xl border bg-[var(--zui-otp-bg,var(--zui-surface-soft,#ffffff))] text-center font-semibold tabular-nums text-[color:var(--zui-otp-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] shadow-sm shadow-black/5 outline-none transition-[background-color,border-color,box-shadow,color,transform] placeholder:text-transparent focus-visible:-translate-y-0.5 focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--zui-otp-ring-offset-focus,var(--zui-ring-offset,#ffffff))] disabled:cursor-not-allowed dark:bg-[var(--zui-otp-bg-dark,var(--zui-surface-soft-dark,oklch(12.9%_0.042_264.695)))] dark:text-[color:var(--zui-otp-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] dark:shadow-black/20 dark:focus-visible:ring-offset-[var(--zui-otp-ring-offset-focus-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))]";

export const zuiOtpSeparatorBase =
  "h-px w-3 shrink-0 bg-[color:var(--zui-otp-separator,#94a3b8)] opacity-70 dark:bg-[color:var(--zui-otp-separator-dark,#64748b)]";

export const zuiOtpErrorBase =
  "text-sm leading-6 text-[color:var(--zui-otp-error-fg,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:text-[color:var(--zui-otp-error-fg-dark,var(--zui-status-error-dark,oklch(71.2%_0.194_13.428)))]";

export const zuiOtpSizes = {
  sm: "size-7 md:size-9 rounded-lg text-sm",
  md: "size-9 md:size-11 text-base",
  lg: "size-11 md:size-13 rounded-2xl text-lg",
} as const;

export const zuiOtpAppearances = {
  default:
    "border-[color:var(--zui-otp-default-border,var(--zui-border,#cbd5e1))] focus-visible:border-[color:var(--zui-otp-default-border-focus,var(--zui-border,oklch(44.6%_0.043_257.281)))] focus-visible:ring-[var(--zui-otp-default-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281_/_0.25)))] dark:border-[color:var(--zui-otp-default-border-dark,var(--zui-border-dark,#475569))] dark:focus-visible:border-[color:var(--zui-otp-default-border-focus-dark,var(--zui-border-dark,oklch(86.9%_0.022_252.894)))] dark:focus-visible:ring-[var(--zui-otp-default-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894_/_0.25)))]",
  outline:
    "border-[color:var(--zui-otp-outline-border,var(--zui-border,#64748b))] bg-transparent focus-visible:border-[color:var(--zui-otp-outline-border-focus,var(--zui-border,oklch(54.6%_0.245_262.881)))] focus-visible:ring-[var(--zui-otp-outline-ring-focus,var(--zui-focus-ring,oklch(54.6%_0.245_262.881_/_0.28)))] dark:border-[color:var(--zui-otp-outline-border-dark,var(--zui-border-dark,#94a3b8))] dark:bg-transparent dark:focus-visible:border-[color:var(--zui-otp-outline-border-focus-dark,var(--zui-border-dark,oklch(70.7%_0.165_254.624)))] dark:focus-visible:ring-[var(--zui-otp-outline-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.165_254.624_/_0.28)))]",
  glass:
    "border-[color:var(--zui-otp-glass-border,var(--zui-border,#ffffff66))] bg-[var(--zui-otp-glass-bg,var(--zui-surface-soft,#ffffffcc))] backdrop-blur-md focus-visible:border-[color:var(--zui-otp-glass-border-focus,var(--zui-border,oklch(70.7%_0.165_254.624)))] focus-visible:ring-[var(--zui-otp-glass-ring-focus,var(--zui-focus-ring,oklch(70.7%_0.165_254.624_/_0.32)))] dark:border-[color:var(--zui-otp-glass-border-dark,var(--zui-border-dark,#ffffff26))] dark:bg-[var(--zui-otp-glass-bg-dark,var(--zui-surface-soft-dark,#0f172acc))] dark:focus-visible:border-[color:var(--zui-otp-glass-border-focus-dark,var(--zui-border-dark,oklch(78.9%_0.154_211.53)))] dark:focus-visible:ring-[var(--zui-otp-glass-ring-focus-dark,var(--zui-focus-ring-dark,oklch(78.9%_0.154_211.53_/_0.32)))]",
  success:
    "border-[color:var(--zui-otp-success-border,var(--zui-status-success,oklch(69.6%_0.17_162.48_/_0.6)))] focus-visible:border-[color:var(--zui-otp-success-border-focus,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] focus-visible:ring-[var(--zui-otp-success-ring-focus,var(--zui-focus-ring,oklch(59.6%_0.145_163.225_/_0.28)))] dark:border-[color:var(--zui-otp-success-border-dark,var(--zui-status-success-dark,oklch(69.6%_0.17_162.48_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-success-border-focus-dark,var(--zui-status-success-dark,oklch(77.7%_0.152_181.912)))] dark:focus-visible:ring-[var(--zui-otp-success-ring-focus-dark,var(--zui-focus-ring-dark,oklch(77.7%_0.152_181.912_/_0.28)))]",
  error:
    "border-[color:var(--zui-otp-error-border,var(--zui-status-error,oklch(58.6%_0.253_17.585_/_0.7)))] focus-visible:border-[color:var(--zui-otp-error-border-focus,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] focus-visible:ring-[var(--zui-otp-error-ring-focus,var(--zui-focus-ring,oklch(58.6%_0.253_17.585_/_0.28)))] dark:border-[color:var(--zui-otp-error-border-dark,var(--zui-status-error-dark,oklch(71.2%_0.194_13.428_/_0.65)))] dark:focus-visible:border-[color:var(--zui-otp-error-border-focus-dark,var(--zui-status-error-dark,oklch(71.2%_0.194_13.428)))] dark:focus-visible:ring-[var(--zui-otp-error-ring-focus-dark,var(--zui-focus-ring-dark,oklch(71.2%_0.194_13.428_/_0.28)))]",
  warning:
    "border-[color:var(--zui-otp-warning-border,var(--zui-status-warning,oklch(79.5%_0.184_86.047_/_0.7)))] focus-visible:border-[color:var(--zui-otp-warning-border-focus,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] focus-visible:ring-[var(--zui-otp-warning-ring-focus,var(--zui-focus-ring,oklch(68.1%_0.162_75.834_/_0.28)))] dark:border-[color:var(--zui-otp-warning-border-dark,var(--zui-status-warning-dark,oklch(79.5%_0.184_86.047_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-warning-border-focus-dark,var(--zui-status-warning-dark,oklch(85.2%_0.199_91.936)))] dark:focus-visible:ring-[var(--zui-otp-warning-ring-focus-dark,var(--zui-focus-ring-dark,oklch(85.2%_0.199_91.936_/_0.28)))]",
  info: "border-[color:var(--zui-otp-info-border,var(--zui-status-info,oklch(62.3%_0.214_259.815_/_0.7)))] focus-visible:border-[color:var(--zui-otp-info-border-focus,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] focus-visible:ring-[var(--zui-otp-info-ring-focus,var(--zui-focus-ring,oklch(54.6%_0.245_262.881_/_0.28)))] dark:border-[color:var(--zui-otp-info-border-dark,var(--zui-status-info-dark,oklch(62.3%_0.214_259.815_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-info-border-focus-dark,var(--zui-status-info-dark,oklch(70.7%_0.165_254.624)))] dark:focus-visible:ring-[var(--zui-otp-info-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.165_254.624_/_0.28)))]",
  violet:
    "border-[color:var(--zui-otp-violet-border,var(--zui-color-violet,oklch(60.6%_0.25_292.717_/_0.7)))] focus-visible:border-[color:var(--zui-otp-violet-border-focus,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] focus-visible:ring-[var(--zui-otp-violet-ring-focus,var(--zui-focus-ring,oklch(54.1%_0.281_293.009_/_0.28)))] dark:border-[color:var(--zui-otp-violet-border-dark,var(--zui-color-violet-dark,oklch(60.6%_0.25_292.717_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-violet-border-focus-dark,var(--zui-color-violet-dark,oklch(70.2%_0.183_293.541)))] dark:focus-visible:ring-[var(--zui-otp-violet-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.2%_0.183_293.541_/_0.28)))]",
  amber:
    "border-[color:var(--zui-otp-amber-border,var(--zui-color-amber,oklch(76.9%_0.188_70.08_/_0.7)))] focus-visible:border-[color:var(--zui-otp-amber-border-focus,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] focus-visible:ring-[var(--zui-otp-amber-ring-focus,var(--zui-focus-ring,oklch(66.6%_0.179_58.318_/_0.28)))] dark:border-[color:var(--zui-otp-amber-border-dark,var(--zui-color-amber-dark,oklch(76.9%_0.188_70.08_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-amber-border-focus-dark,var(--zui-color-amber-dark,oklch(82.8%_0.189_84.429)))] dark:focus-visible:ring-[var(--zui-otp-amber-ring-focus-dark,var(--zui-focus-ring-dark,oklch(82.8%_0.189_84.429_/_0.28)))]",
  pink: "border-[color:var(--zui-otp-pink-border,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.7)))] focus-visible:border-[color:var(--zui-otp-pink-border-focus,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] focus-visible:ring-[var(--zui-otp-pink-ring-focus,var(--zui-focus-ring,oklch(59.2%_0.249_0.584_/_0.28)))] dark:border-[color:var(--zui-otp-pink-border-dark,var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-pink-border-focus-dark,var(--zui-color-pink-dark,oklch(71.8%_0.202_349.761)))] dark:focus-visible:ring-[var(--zui-otp-pink-ring-focus-dark,var(--zui-focus-ring-dark,oklch(71.8%_0.202_349.761_/_0.28)))]",
  indigo:
    "border-[color:var(--zui-otp-indigo-border,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.7)))] focus-visible:border-[color:var(--zui-otp-indigo-border-focus,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] focus-visible:ring-[var(--zui-otp-indigo-ring-focus,var(--zui-focus-ring,oklch(51.1%_0.262_276.966_/_0.28)))] dark:border-[color:var(--zui-otp-indigo-border-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-indigo-border-focus-dark,var(--zui-color-indigo-dark,oklch(67.3%_0.182_276.935)))] dark:focus-visible:ring-[var(--zui-otp-indigo-ring-focus-dark,var(--zui-focus-ring-dark,oklch(67.3%_0.182_276.935_/_0.28)))]",
  orange:
    "border-[color:var(--zui-otp-orange-border,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.7)))] focus-visible:border-[color:var(--zui-otp-orange-border-focus,var(--zui-color-orange,oklch(64.6%_0.222_41.116)))] focus-visible:ring-[var(--zui-otp-orange-ring-focus,var(--zui-focus-ring,oklch(64.6%_0.222_41.116_/_0.28)))] dark:border-[color:var(--zui-otp-orange-border-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604_/_0.5)))] dark:focus-visible:border-[color:var(--zui-otp-orange-border-focus-dark,var(--zui-color-orange-dark,oklch(75%_0.183_55.934)))] dark:focus-visible:ring-[var(--zui-otp-orange-ring-focus-dark,var(--zui-focus-ring-dark,oklch(75%_0.183_55.934_/_0.28)))]",
  blue: "border border-[color:var(--zui-otp-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-otp-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-otp-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 10%, transparent))] dark:bg-[var(--zui-otp-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 18%, transparent))] text-[color:var(--zui-otp-blue-fg,var(--zui-color-blue,#0f172a))] dark:text-[color:var(--zui-otp-blue-fg-dark,var(--zui-color-blue-dark,#f8fafc))]",
  cyan: "border border-[color:var(--zui-otp-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-otp-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-otp-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 10%, transparent))] dark:bg-[var(--zui-otp-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 18%, transparent))] text-[color:var(--zui-otp-cyan-fg,var(--zui-color-cyan,#0f172a))] dark:text-[color:var(--zui-otp-cyan-fg-dark,var(--zui-color-cyan-dark,#f8fafc))]",
  green:
    "border border-[color:var(--zui-otp-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-otp-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-otp-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 10%, transparent))] dark:bg-[var(--zui-otp-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 18%, transparent))] text-[color:var(--zui-otp-green-fg,var(--zui-color-green,#0f172a))] dark:text-[color:var(--zui-otp-green-fg-dark,var(--zui-color-green-dark,#f8fafc))]",
  lime: "border border-[color:var(--zui-otp-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-otp-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-otp-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 10%, transparent))] dark:bg-[var(--zui-otp-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 18%, transparent))] text-[color:var(--zui-otp-lime-fg,var(--zui-color-lime,#0f172a))] dark:text-[color:var(--zui-otp-lime-fg-dark,var(--zui-color-lime-dark,#f8fafc))]",
  mint: "border border-[color:var(--zui-otp-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-otp-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-otp-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 10%, transparent))] dark:bg-[var(--zui-otp-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 18%, transparent))] text-[color:var(--zui-otp-mint-fg,var(--zui-color-mint,#0f172a))] dark:text-[color:var(--zui-otp-mint-fg-dark,var(--zui-color-mint-dark,#f8fafc))]",
  ocean:
    "border border-[color:var(--zui-otp-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-otp-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-otp-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 10%, transparent))] dark:bg-[var(--zui-otp-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-otp-ocean-fg,var(--zui-color-ocean,#0f172a))] dark:text-[color:var(--zui-otp-ocean-fg-dark,var(--zui-color-ocean-dark,#f8fafc))]",
  sapphire:
    "border border-[color:var(--zui-otp-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-otp-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-otp-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 10%, transparent))] dark:bg-[var(--zui-otp-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 18%, transparent))] text-[color:var(--zui-otp-sapphire-fg,var(--zui-color-sapphire,#0f172a))] dark:text-[color:var(--zui-otp-sapphire-fg-dark,var(--zui-color-sapphire-dark,#f8fafc))]",
  lavender:
    "border border-[color:var(--zui-otp-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-otp-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-otp-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 10%, transparent))] dark:bg-[var(--zui-otp-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 18%, transparent))] text-[color:var(--zui-otp-lavender-fg,var(--zui-color-lavender,#0f172a))] dark:text-[color:var(--zui-otp-lavender-fg-dark,var(--zui-color-lavender-dark,#f8fafc))]",
  ruby: "border border-[color:var(--zui-otp-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-otp-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-otp-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 10%, transparent))] dark:bg-[var(--zui-otp-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 18%, transparent))] text-[color:var(--zui-otp-ruby-fg,var(--zui-color-ruby,#0f172a))] dark:text-[color:var(--zui-otp-ruby-fg-dark,var(--zui-color-ruby-dark,#f8fafc))]",
  red: "border border-[color:var(--zui-otp-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-otp-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-otp-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 10%, transparent))] dark:bg-[var(--zui-otp-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 18%, transparent))] text-[color:var(--zui-otp-red-fg,var(--zui-color-red,#0f172a))] dark:text-[color:var(--zui-otp-red-fg-dark,var(--zui-color-red-dark,#f8fafc))]",
  slate:
    "border border-[color:var(--zui-otp-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-otp-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-otp-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 10%, transparent))] dark:bg-[var(--zui-otp-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 18%, transparent))] text-[color:var(--zui-otp-slate-fg,var(--zui-color-slate,#0f172a))] dark:text-[color:var(--zui-otp-slate-fg-dark,var(--zui-color-slate-dark,#f8fafc))]",
  zinc: "border border-[color:var(--zui-otp-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-otp-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-otp-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 10%, transparent))] dark:bg-[var(--zui-otp-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 18%, transparent))] text-[color:var(--zui-otp-zinc-fg,var(--zui-color-zinc,#0f172a))] dark:text-[color:var(--zui-otp-zinc-fg-dark,var(--zui-color-zinc-dark,#f8fafc))]",
  stone:
    "border border-[color:var(--zui-otp-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-otp-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-otp-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 10%, transparent))] dark:bg-[var(--zui-otp-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 18%, transparent))] text-[color:var(--zui-otp-stone-fg,var(--zui-color-stone,#0f172a))] dark:text-[color:var(--zui-otp-stone-fg-dark,var(--zui-color-stone-dark,#f8fafc))]",
  royal:
    "border border-[color:var(--zui-otp-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-otp-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-otp-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 10%, transparent))] dark:bg-[var(--zui-otp-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 18%, transparent))] text-[color:var(--zui-otp-royal-fg,var(--zui-color-royal,#0f172a))] dark:text-[color:var(--zui-otp-royal-fg-dark,var(--zui-color-royal-dark,#f8fafc))]",
  electric:
    "border border-[color:var(--zui-otp-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-otp-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-otp-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 10%, transparent))] dark:bg-[var(--zui-otp-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 18%, transparent))] text-[color:var(--zui-otp-electric-fg,var(--zui-color-electric,#0f172a))] dark:text-[color:var(--zui-otp-electric-fg-dark,var(--zui-color-electric-dark,#f8fafc))]",
  forest:
    "border border-[color:var(--zui-otp-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-otp-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-otp-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 10%, transparent))] dark:bg-[var(--zui-otp-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 18%, transparent))] text-[color:var(--zui-otp-forest-fg,var(--zui-color-forest,#0f172a))] dark:text-[color:var(--zui-otp-forest-fg-dark,var(--zui-color-forest-dark,#f8fafc))]",
  sunset:
    "border border-[color:var(--zui-otp-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-otp-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-otp-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 10%, transparent))] dark:bg-[var(--zui-otp-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 18%, transparent))] text-[color:var(--zui-otp-sunset-fg,var(--zui-color-sunset,#0f172a))] dark:text-[color:var(--zui-otp-sunset-fg-dark,var(--zui-color-sunset-dark,#f8fafc))]",
  magenta:
    "border border-[color:var(--zui-otp-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-otp-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-otp-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 10%, transparent))] dark:bg-[var(--zui-otp-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 18%, transparent))] text-[color:var(--zui-otp-magenta-fg,var(--zui-color-magenta,#0f172a))] dark:text-[color:var(--zui-otp-magenta-fg-dark,var(--zui-color-magenta-dark,#f8fafc))]",
  crimson:
    "border border-[color:var(--zui-otp-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-otp-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-otp-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 10%, transparent))] dark:bg-[var(--zui-otp-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 18%, transparent))] text-[color:var(--zui-otp-crimson-fg,var(--zui-color-crimson,#0f172a))] dark:text-[color:var(--zui-otp-crimson-fg-dark,var(--zui-color-crimson-dark,#f8fafc))]",
  aqua: "border border-[color:var(--zui-otp-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-otp-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-otp-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 10%, transparent))] dark:bg-[var(--zui-otp-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 18%, transparent))] text-[color:var(--zui-otp-aqua-fg,var(--zui-color-aqua,#0f172a))] dark:text-[color:var(--zui-otp-aqua-fg-dark,var(--zui-color-aqua-dark,#f8fafc))]",
  plum: "border border-[color:var(--zui-otp-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-otp-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-otp-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 10%, transparent))] dark:bg-[var(--zui-otp-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 18%, transparent))] text-[color:var(--zui-otp-plum-fg,var(--zui-color-plum,#0f172a))] dark:text-[color:var(--zui-otp-plum-fg-dark,var(--zui-color-plum-dark,#f8fafc))]",
} as const;
