export const zuiPaginationListBase =
  "inline-flex flex-wrap items-center rounded-xl border p-1 ring-offset-[var(--zui-pagination-list-ring-offset,var(--zui-ring-offset,oklch(98.4%_0.003_247.858)))] dark:ring-offset-[var(--zui-pagination-list-ring-offset-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))]";

export const zuiPaginationListAppearances = {
  default:
    "border-[color:var(--zui-pagination-list-default-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-pagination-list-default-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-pagination-list-default-bg,var(--zui-surface-muted,#00000008))] dark:bg-[var(--zui-pagination-list-default-bg-dark,var(--zui-surface-muted-dark,#ffffff08))]",
  secondary:
    "border-[color:var(--zui-pagination-list-secondary-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-pagination-list-secondary-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-pagination-list-secondary-bg,var(--zui-surface-muted,oklch(96.8%_0.007_247.896_/_0.4)))] dark:bg-[var(--zui-pagination-list-secondary-bg-dark,var(--zui-surface-muted-dark,oklch(20.8%_0.042_265.755_/_0.4)))]",
  destructive:
    "border-[color:var(--zui-pagination-list-destructive-border,var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.25)))] dark:border-[color:var(--zui-pagination-list-destructive-border-dark,var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.25)))] bg-[var(--zui-pagination-list-destructive-bg,var(--zui-status-error,oklch(96.9%_0.015_12.422)))] dark:bg-[var(--zui-pagination-list-destructive-bg-dark,var(--zui-status-error-dark,oklch(27.1%_0.105_12.094_/_0.2)))]",
  outline:
    "border-[color:var(--zui-pagination-list-outline-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-pagination-list-outline-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-pagination-list-outline-bg,var(--zui-surface-muted,transparent))] dark:bg-[var(--zui-pagination-list-outline-bg-dark,var(--zui-surface-muted-dark,transparent))]",
  ghost:
    "border-[color:var(--zui-pagination-list-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-pagination-list-ghost-border-dark,var(--zui-border-dark,transparent))] bg-[var(--zui-pagination-list-ghost-bg,var(--zui-surface-soft,transparent))] dark:bg-[var(--zui-pagination-list-ghost-bg-dark,var(--zui-surface-soft-dark,transparent))]",
  link: "border-[color:var(--zui-pagination-list-link-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-pagination-list-link-border-dark,var(--zui-border-dark,transparent))] bg-[var(--zui-pagination-list-link-bg,var(--zui-surface-muted,transparent))] dark:bg-[var(--zui-pagination-list-link-bg-dark,var(--zui-surface-muted-dark,transparent))]",
  glass:
    "border-[color:var(--zui-pagination-list-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-pagination-list-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-pagination-list-glass-bg,var(--zui-surface-soft,#0000000d))] dark:bg-[var(--zui-pagination-list-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff0d))] backdrop-blur-md",
  emerald:
    "border-[color:var(--zui-pagination-list-emerald-border,var(--zui-color-emerald,oklch(69.6%_0.17_162.48_/_0.25)))] dark:border-[color:var(--zui-pagination-list-emerald-border-dark,var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48_/_0.25)))] bg-[var(--zui-pagination-list-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(97.9%_0.021_166.113)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(26.2%_0.051_172.552_/_0.2)) 18%, transparent))]",
  indigo:
    "border-[color:var(--zui-pagination-list-indigo-border,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.25)))] dark:border-[color:var(--zui-pagination-list-indigo-border-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117_/_0.25)))] bg-[var(--zui-pagination-list-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(96.2%_0.018_272.314)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.2)) 18%, transparent))]",
  purple:
    "border-[color:var(--zui-pagination-list-purple-border,var(--zui-color-purple,oklch(62.7%_0.265_303.9_/_0.25)))] dark:border-[color:var(--zui-pagination-list-purple-border-dark,var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9_/_0.25)))] bg-[var(--zui-pagination-list-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(97.7%_0.014_308.299)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.2)) 18%, transparent))]",
  pink: "border-[color:var(--zui-pagination-list-pink-border,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.25)))] dark:border-[color:var(--zui-pagination-list-pink-border-dark,var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308_/_0.25)))] bg-[var(--zui-pagination-list-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(97.1%_0.014_343.198)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.2)) 18%, transparent))]",
  rose: "border-[color:var(--zui-pagination-list-rose-border,var(--zui-color-rose,oklch(64.5%_0.246_16.439_/_0.25)))] dark:border-[color:var(--zui-pagination-list-rose-border-dark,var(--zui-color-rose-dark,oklch(64.5%_0.246_16.439_/_0.25)))] bg-[var(--zui-pagination-list-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(96.9%_0.015_12.422)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.2)) 18%, transparent))]",
  sky: "border-[color:var(--zui-pagination-list-sky-border,var(--zui-color-sky,oklch(68.5%_0.169_237.323_/_0.25)))] dark:border-[color:var(--zui-pagination-list-sky-border-dark,var(--zui-color-sky-dark,oklch(68.5%_0.169_237.323_/_0.25)))] bg-[var(--zui-pagination-list-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(97.7%_0.013_236.62)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(29.3%_0.066_243.157_/_0.2)) 18%, transparent))]",
  teal: "border-[color:var(--zui-pagination-list-teal-border,var(--zui-color-teal,oklch(70.4%_0.14_182.503_/_0.25)))] dark:border-[color:var(--zui-pagination-list-teal-border-dark,var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503_/_0.25)))] bg-[var(--zui-pagination-list-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(98.4%_0.014_180.72)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.2)) 18%, transparent))]",
  yellow:
    "border-[color:var(--zui-pagination-list-yellow-border,var(--zui-color-yellow,oklch(79.5%_0.184_86.047_/_0.25)))] dark:border-[color:var(--zui-pagination-list-yellow-border-dark,var(--zui-color-yellow-dark,oklch(79.5%_0.184_86.047_/_0.25)))] bg-[var(--zui-pagination-list-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(98.7%_0.026_102.212)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.2)) 18%, transparent))]",
  orange:
    "border-[color:var(--zui-pagination-list-orange-border,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.25)))] dark:border-[color:var(--zui-pagination-list-orange-border-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604_/_0.25)))] bg-[var(--zui-pagination-list-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(98%_0.016_73.684)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.2)) 18%, transparent))]",
  gray: "border-[color:var(--zui-pagination-list-gray-border,var(--zui-color-gray,oklch(55.1%_0.027_264.364_/_0.25)))] dark:border-[color:var(--zui-pagination-list-gray-border-dark,var(--zui-color-gray-dark,oklch(55.1%_0.027_264.364_/_0.25)))] bg-[var(--zui-pagination-list-gray-bg,color-mix(in oklch, var(--zui-color-gray,oklch(98.5%_0.002_247.839)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-gray-bg-dark,color-mix(in oklch, var(--zui-color-gray-dark,oklch(13%_0.028_261.692_/_0.2)) 18%, transparent))]",
  amber:
    "border-[color:var(--zui-pagination-list-amber-border,var(--zui-color-amber,oklch(76.9%_0.188_70.08_/_0.25)))] dark:border-[color:var(--zui-pagination-list-amber-border-dark,var(--zui-color-amber-dark,oklch(76.9%_0.188_70.08_/_0.25)))] bg-[var(--zui-pagination-list-amber-bg,color-mix(in oklch, var(--zui-color-amber,oklch(98.7%_0.022_95.277)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-amber-bg-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(27.9%_0.077_45.635_/_0.2)) 18%, transparent))]",
  violet:
    "border-[color:var(--zui-pagination-list-violet-border,var(--zui-color-violet,oklch(60.6%_0.25_292.717_/_0.25)))] dark:border-[color:var(--zui-pagination-list-violet-border-dark,var(--zui-color-violet-dark,oklch(60.6%_0.25_292.717_/_0.25)))] bg-[var(--zui-pagination-list-violet-bg,color-mix(in oklch, var(--zui-color-violet,oklch(96.9%_0.016_293.756)) 10%, transparent))] dark:bg-[var(--zui-pagination-list-violet-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(28.3%_0.141_291.089_/_0.2)) 18%, transparent))]",
  "gradient-blue":
    "border-[color:var(--zui-pagination-list-gradient-blue-border,var(--zui-color-blue,oklch(62.3%_0.214_259.815_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(62.3%_0.214_259.815_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:from-[var(--zui-pagination-list-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(28.2%_0.091_267.935_/_0.3)))] to-[var(--zui-pagination-list-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-pagination-list-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.3)))]",
  "gradient-green":
    "border-[color:var(--zui-pagination-list-gradient-green-border,var(--zui-color-green,oklch(76.8%_0.233_130.85_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-green-border-dark,var(--zui-color-green-dark,oklch(76.8%_0.233_130.85_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:from-[var(--zui-pagination-list-gradient-green-from-dark,var(--zui-color-green-dark,oklch(26.6%_0.065_152.934_/_0.3)))] to-[var(--zui-pagination-list-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:to-[var(--zui-pagination-list-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(27.4%_0.072_132.109_/_0.3)))]",
  "gradient-red":
    "border-[color:var(--zui-pagination-list-gradient-red-border,var(--zui-color-red,oklch(65.6%_0.241_354.308_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-red-border-dark,var(--zui-color-red-dark,oklch(65.6%_0.241_354.308_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:from-[var(--zui-pagination-list-gradient-red-from-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.3)))] to-[var(--zui-pagination-list-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-pagination-list-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.3)))]",
  "gradient-yellow":
    "border-[color:var(--zui-pagination-list-gradient-yellow-border,var(--zui-color-yellow,oklch(70.5%_0.213_47.604_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(70.5%_0.213_47.604_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:from-[var(--zui-pagination-list-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.3)))] to-[var(--zui-pagination-list-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:to-[var(--zui-pagination-list-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.3)))]",
  "gradient-purple":
    "border-[color:var(--zui-pagination-list-gradient-purple-border,var(--zui-color-purple,oklch(65.6%_0.241_354.308_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(65.6%_0.241_354.308_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:from-[var(--zui-pagination-list-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.3)))] to-[var(--zui-pagination-list-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-pagination-list-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.3)))]",
  "gradient-teal":
    "border-[color:var(--zui-pagination-list-gradient-teal-border,var(--zui-color-teal,oklch(71.5%_0.143_215.221_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(71.5%_0.143_215.221_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:from-[var(--zui-pagination-list-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.3)))] to-[var(--zui-pagination-list-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:to-[var(--zui-pagination-list-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(30.2%_0.056_229.695_/_0.3)))]",
  "gradient-indigo":
    "border-[color:var(--zui-pagination-list-gradient-indigo-border,var(--zui-color-indigo,oklch(62.7%_0.265_303.9_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(62.7%_0.265_303.9_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:from-[var(--zui-pagination-list-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.3)))] to-[var(--zui-pagination-list-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-pagination-list-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.3)))]",
  "gradient-pink":
    "border-[color:var(--zui-pagination-list-gradient-pink-border,var(--zui-color-pink,oklch(64.5%_0.246_16.439_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(64.5%_0.246_16.439_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:from-[var(--zui-pagination-list-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.3)))] to-[var(--zui-pagination-list-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:to-[var(--zui-pagination-list-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.3)))]",
  "gradient-orange":
    "border-[color:var(--zui-pagination-list-gradient-orange-border,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.3)))] dark:border-[color:var(--zui-pagination-list-gradient-orange-border-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604_/_0.3)))] bg-linear-to-r from-[var(--zui-pagination-list-gradient-orange-from,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:from-[var(--zui-pagination-list-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.3)))] to-[var(--zui-pagination-list-gradient-orange-to,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:to-[var(--zui-pagination-list-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.3)))]",
  blue: "border border-[color:var(--zui-pagination-list-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-pagination-list-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-pagination-list-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 14%, transparent))] text-[color:var(--zui-pagination-list-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-pagination-list-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] hover:bg-[var(--zui-pagination-list-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f62e) 18%, transparent))]",
  cyan: "border border-[color:var(--zui-pagination-list-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-pagination-list-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-pagination-list-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 8%, transparent))] dark:bg-[var(--zui-pagination-list-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 14%, transparent))] text-[color:var(--zui-pagination-list-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-pagination-list-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] hover:bg-[var(--zui-pagination-list-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b218) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee2e) 18%, transparent))]",
  green:
    "border border-[color:var(--zui-pagination-list-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-pagination-list-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-pagination-list-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 14%, transparent))] text-[color:var(--zui-pagination-list-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-pagination-list-green-fg-dark,var(--zui-color-green-dark,#22c55e))] hover:bg-[var(--zui-pagination-list-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e2e) 18%, transparent))]",
  lime: "border border-[color:var(--zui-pagination-list-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-pagination-list-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-pagination-list-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 14%, transparent))] text-[color:var(--zui-pagination-list-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-pagination-list-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] hover:bg-[var(--zui-pagination-list-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e6352e) 18%, transparent))]",
  mint: "border border-[color:var(--zui-pagination-list-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-pagination-list-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-pagination-list-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 8%, transparent))] dark:bg-[var(--zui-pagination-list-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 14%, transparent))] text-[color:var(--zui-pagination-list-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-pagination-list-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] hover:bg-[var(--zui-pagination-list-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98118) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b72e) 18%, transparent))]",
  ocean:
    "border border-[color:var(--zui-pagination-list-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-pagination-list-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-pagination-list-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 8%, transparent))] dark:bg-[var(--zui-pagination-list-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 14%, transparent))] text-[color:var(--zui-pagination-list-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-pagination-list-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] hover:bg-[var(--zui-pagination-list-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c718) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf82e) 18%, transparent))]",
  sapphire:
    "border border-[color:var(--zui-pagination-list-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-pagination-list-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-pagination-list-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 8%, transparent))] dark:bg-[var(--zui-pagination-list-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 14%, transparent))] text-[color:var(--zui-pagination-list-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-pagination-list-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] hover:bg-[var(--zui-pagination-list-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed818) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa2e) 18%, transparent))]",
  lavender:
    "border border-[color:var(--zui-pagination-list-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-pagination-list-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-pagination-list-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 8%, transparent))] dark:bg-[var(--zui-pagination-list-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 14%, transparent))] text-[color:var(--zui-pagination-list-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-pagination-list-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] hover:bg-[var(--zui-pagination-list-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf618) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa2e) 18%, transparent))]",
  ruby: "border border-[color:var(--zui-pagination-list-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-pagination-list-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-pagination-list-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 14%, transparent))] text-[color:var(--zui-pagination-list-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-pagination-list-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] hover:bg-[var(--zui-pagination-list-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb71852e) 18%, transparent))]",
  red: "border border-[color:var(--zui-pagination-list-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-pagination-list-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-pagination-list-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 8%, transparent))] dark:bg-[var(--zui-pagination-list-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 14%, transparent))] text-[color:var(--zui-pagination-list-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-pagination-list-red-fg-dark,var(--zui-color-red-dark,#ef4444))] hover:bg-[var(--zui-pagination-list-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262618) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44442e) 18%, transparent))]",
  slate:
    "border border-[color:var(--zui-pagination-list-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-pagination-list-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-pagination-list-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 8%, transparent))] dark:bg-[var(--zui-pagination-list-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 14%, transparent))] text-[color:var(--zui-pagination-list-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-pagination-list-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] hover:bg-[var(--zui-pagination-list-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556918) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b2e) 18%, transparent))]",
  zinc: "border border-[color:var(--zui-pagination-list-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-pagination-list-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-pagination-list-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 14%, transparent))] text-[color:var(--zui-pagination-list-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-pagination-list-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] hover:bg-[var(--zui-pagination-list-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a2e) 18%, transparent))]",
  stone:
    "border border-[color:var(--zui-pagination-list-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-pagination-list-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-pagination-list-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 14%, transparent))] text-[color:var(--zui-pagination-list-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-pagination-list-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] hover:bg-[var(--zui-pagination-list-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c2e) 18%, transparent))]",
  royal:
    "border border-[color:var(--zui-pagination-list-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-pagination-list-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-pagination-list-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 14%, transparent))] text-[color:var(--zui-pagination-list-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-pagination-list-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] hover:bg-[var(--zui-pagination-list-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf82e) 18%, transparent))]",
  electric:
    "border border-[color:var(--zui-pagination-list-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-pagination-list-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-pagination-list-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 8%, transparent))] dark:bg-[var(--zui-pagination-list-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 14%, transparent))] text-[color:var(--zui-pagination-list-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-pagination-list-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] hover:bg-[var(--zui-pagination-list-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e918) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf82e) 18%, transparent))]",
  forest:
    "border border-[color:var(--zui-pagination-list-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-pagination-list-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-pagination-list-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 8%, transparent))] dark:bg-[var(--zui-pagination-list-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 14%, transparent))] text-[color:var(--zui-pagination-list-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-pagination-list-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] hover:bg-[var(--zui-pagination-list-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653418) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade802e) 18%, transparent))]",
  sunset:
    "border border-[color:var(--zui-pagination-list-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-pagination-list-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-pagination-list-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 14%, transparent))] text-[color:var(--zui-pagination-list-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-pagination-list-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] hover:bg-[var(--zui-pagination-list-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c2e) 18%, transparent))]",
  magenta:
    "border border-[color:var(--zui-pagination-list-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-pagination-list-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-pagination-list-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 8%, transparent))] dark:bg-[var(--zui-pagination-list-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 14%, transparent))] text-[color:var(--zui-pagination-list-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-pagination-list-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] hover:bg-[var(--zui-pagination-list-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d318) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f92e) 18%, transparent))]",
  crimson:
    "border border-[color:var(--zui-pagination-list-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-pagination-list-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-pagination-list-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 14%, transparent))] text-[color:var(--zui-pagination-list-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-pagination-list-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] hover:bg-[var(--zui-pagination-list-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f871712e) 18%, transparent))]",
  aqua: "border border-[color:var(--zui-pagination-list-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-pagination-list-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-pagination-list-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 14%, transparent))] text-[color:var(--zui-pagination-list-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-pagination-list-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] hover:bg-[var(--zui-pagination-list-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf2e) 18%, transparent))]",
  plum: "border border-[color:var(--zui-pagination-list-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-pagination-list-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-pagination-list-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 8%, transparent))] dark:bg-[var(--zui-pagination-list-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 14%, transparent))] text-[color:var(--zui-pagination-list-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-pagination-list-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] hover:bg-[var(--zui-pagination-list-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce18) 9%, transparent))] dark:hover:bg-[var(--zui-pagination-list-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc2e) 18%, transparent))]",
} as const;

export const zuiPaginationListSizes = {
  sm: "gap-0.5",
  md: "gap-1",
  lg: "gap-1",
  xl: "gap-1.5",
  "2xl": "gap-1.5",
  "3xl": "gap-2",
  "4xl": "gap-2",
  "5xl": "gap-2",
  "6xl": "gap-2",
  "7xl": "gap-2.5",
  "8xl": "gap-2.5",
  "9xl": "gap-2.5",
  "10xl": "gap-3",
  icon: "gap-1",
} as const;

export const zuiPaginationEllipsisBase =
  "inline-flex min-w-[2ch] select-none items-center justify-center px-1 font-medium text-[color:var(--zui-pagination-ellipsis-fg,var(--zui-fg,oklch(55.4%_0.046_257.417)))] dark:text-[color:var(--zui-pagination-ellipsis-fg-dark,var(--zui-fg-dark,oklch(70.4%_0.04_256.788)))]";

export const zuiPaginationEllipsisSizes = {
  sm: "text-xs",
  md: "text-sm",
  lg: "text-base",
  xl: "text-base",
  "2xl": "text-lg",
  "3xl": "text-lg",
  "4xl": "text-xl",
  "5xl": "text-xl",
  "6xl": "text-xl",
  "7xl": "text-2xl",
  "8xl": "text-2xl",
  "9xl": "text-2xl",
  "10xl": "text-2xl",
  icon: "text-sm",
} as const;
