export const zuiPopoverContentBase =
  "absolute z-50 rounded-[var(--zui-popover-radius,var(--zui-radius,0.5rem))] border shadow-[var(--zui-popover-shadow,var(--zui-shadow,0_10px_30px_rgba(15,23,42,0.16)))] dark:shadow-[var(--zui-popover-shadow-dark,var(--zui-shadow-dark,0_18px_48px_rgba(15,23,42,0.35)))] transition-all duration-200 outline-none";

export const zuiPopoverContentVariants = {
  default:
    "border-[color:var(--zui-popover-default-border,var(--zui-border,oklch(20.8%_0.042_265.755_/_0.1)))] dark:border-[color:var(--zui-popover-default-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-popover-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-popover-default-bg-dark,var(--zui-surface-muted-dark,oklch(20.8%_0.042_265.755)))] text-[color:var(--zui-popover-default-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-popover-default-fg-dark,var(--zui-fg-dark,oklch(96.8%_0.007_247.896)))]",
  outline:
    "border-[color:var(--zui-popover-outline-border,var(--zui-border,oklch(37.3%_0.034_259.733)))] dark:border-[color:var(--zui-popover-outline-border-dark,var(--zui-border-dark,oklch(87.2%_0.01_258.338)))] bg-[var(--zui-popover-outline-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-popover-outline-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-popover-outline-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-popover-outline-fg-dark,var(--zui-fg-dark,#ffffff))]",
  ghost:
    "border-transparent bg-[var(--zui-popover-ghost-bg,var(--zui-surface-soft,oklch(96.7%_0.003_264.542)))] dark:bg-[var(--zui-popover-ghost-bg-dark,var(--zui-surface-soft-dark,oklch(27.8%_0.033_256.848)))] text-[color:var(--zui-popover-ghost-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-popover-ghost-fg-dark,var(--zui-fg-dark,#ffffffe6))]",
  glass:
    "border-[color:var(--zui-popover-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-popover-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-popover-glass-bg,var(--zui-surface-soft,#ffffffb3))] dark:bg-[var(--zui-popover-glass-bg-dark,var(--zui-surface-soft-dark,#020617b3))] text-[color:var(--zui-popover-glass-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-popover-glass-fg-dark,var(--zui-fg-dark,#ffffff))] backdrop-blur-md",
  emerald:
    "border-[color:var(--zui-popover-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913_/_0.35)))] dark:border-[color:var(--zui-popover-emerald-border-dark,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913_/_0.35)))] bg-[var(--zui-popover-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(90.5%_0.093_164.15)) 10%, transparent))] text-[color:var(--zui-popover-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:bg-[var(--zui-popover-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(26.2%_0.051_172.552)) 18%, transparent))] dark:text-[color:var(--zui-popover-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(90.5%_0.093_164.15)))]",
  indigo:
    "border-[color:var(--zui-popover-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366_/_0.35)))] dark:border-[color:var(--zui-popover-indigo-border-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366_/_0.35)))] bg-[var(--zui-popover-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(87%_0.065_274.039)) 10%, transparent))] text-[color:var(--zui-popover-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:bg-[var(--zui-popover-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288)) 18%, transparent))] dark:text-[color:var(--zui-popover-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)))]",
  purple:
    "border-[color:var(--zui-popover-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724_/_0.35)))] dark:border-[color:var(--zui-popover-purple-border-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724_/_0.35)))] bg-[var(--zui-popover-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(90.2%_0.063_306.703)) 10%, transparent))] text-[color:var(--zui-popover-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:bg-[var(--zui-popover-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717)) 18%, transparent))] dark:text-[color:var(--zui-popover-purple-fg-dark,var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)))]",
  pink: "border-[color:var(--zui-popover-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815_/_0.35)))] dark:border-[color:var(--zui-popover-pink-border-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815_/_0.35)))] bg-[var(--zui-popover-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(89.9%_0.061_343.231)) 10%, transparent))] text-[color:var(--zui-popover-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:bg-[var(--zui-popover-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907)) 18%, transparent))] dark:text-[color:var(--zui-popover-pink-fg-dark,var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)))]",
  rose: "border-[color:var(--zui-popover-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697_/_0.35)))] dark:border-[color:var(--zui-popover-rose-border-dark,var(--zui-color-rose-dark,oklch(45.5%_0.188_13.697_/_0.35)))] bg-[var(--zui-popover-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(89.2%_0.058_10.001)) 10%, transparent))] text-[color:var(--zui-popover-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:bg-[var(--zui-popover-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094)) 18%, transparent))] dark:text-[color:var(--zui-popover-rose-fg-dark,var(--zui-color-rose-dark,oklch(89.2%_0.058_10.001)))]",
  sky: "border-[color:var(--zui-popover-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79_/_0.35)))] dark:border-[color:var(--zui-popover-sky-border-dark,var(--zui-color-sky-dark,oklch(44.3%_0.11_240.79_/_0.35)))] bg-[var(--zui-popover-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(90.1%_0.058_230.902)) 10%, transparent))] text-[color:var(--zui-popover-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:bg-[var(--zui-popover-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(29.3%_0.066_243.157)) 18%, transparent))] dark:text-[color:var(--zui-popover-sky-fg-dark,var(--zui-color-sky-dark,oklch(90.1%_0.058_230.902)))]",
  teal: "border-[color:var(--zui-popover-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216_/_0.35)))] dark:border-[color:var(--zui-popover-teal-border-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216_/_0.35)))] bg-[var(--zui-popover-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(91%_0.096_180.426)) 10%, transparent))] text-[color:var(--zui-popover-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:bg-[var(--zui-popover-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524)) 18%, transparent))] dark:text-[color:var(--zui-popover-teal-fg-dark,var(--zui-color-teal-dark,oklch(91%_0.096_180.426)))]",
  yellow:
    "border-[color:var(--zui-popover-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907_/_0.35)))] dark:border-[color:var(--zui-popover-yellow-border-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907_/_0.35)))] bg-[var(--zui-popover-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(94.5%_0.129_101.54)) 10%, transparent))] text-[color:var(--zui-popover-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:bg-[var(--zui-popover-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813)) 18%, transparent))] dark:text-[color:var(--zui-popover-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)))]",
  orange:
    "border-[color:var(--zui-popover-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304_/_0.35)))] dark:border-[color:var(--zui-popover-orange-border-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304_/_0.35)))] bg-[var(--zui-popover-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(90.1%_0.076_70.697)) 10%, transparent))] text-[color:var(--zui-popover-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:bg-[var(--zui-popover-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259)) 18%, transparent))] dark:text-[color:var(--zui-popover-orange-fg-dark,var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)))]",
  green:
    "border-[color:var(--zui-popover-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328_/_0.35)))] dark:border-[color:var(--zui-popover-green-border-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328_/_0.35)))] bg-[var(--zui-popover-green-bg,color-mix(in oklch, var(--zui-color-green,oklch(92.5%_0.084_155.995)) 10%, transparent))] text-[color:var(--zui-popover-green-fg,var(--zui-color-green,oklch(39.3%_0.095_152.535)))] dark:bg-[var(--zui-popover-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,oklch(26.6%_0.065_152.934)) 18%, transparent))] dark:text-[color:var(--zui-popover-green-fg-dark,var(--zui-color-green-dark,oklch(92.5%_0.084_155.995)))]",
  "gradient-blue":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-popover-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(42.4%_0.199_265.638)))] to-[var(--zui-popover-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-popover-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-popover-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-green":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-popover-gradient-green-from-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328)))] to-[var(--zui-popover-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-popover-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(45.3%_0.124_130.933)))] text-[color:var(--zui-popover-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-red":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-popover-gradient-red-from-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] to-[var(--zui-popover-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-popover-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-popover-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-yellow":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-popover-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] to-[var(--zui-popover-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-popover-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] text-[color:var(--zui-popover-gradient-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-purple":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-popover-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] to-[var(--zui-popover-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-popover-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-popover-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-teal":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-popover-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))] to-[var(--zui-popover-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-popover-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(45%_0.085_224.283)))] text-[color:var(--zui-popover-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-indigo":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-popover-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))] to-[var(--zui-popover-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-popover-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-popover-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-pink":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-popover-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] to-[var(--zui-popover-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-popover-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(45.5%_0.188_13.697)))] text-[color:var(--zui-popover-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-orange":
    "border-transparent bg-linear-to-r from-[var(--zui-popover-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-popover-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] to-[var(--zui-popover-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-popover-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] text-[color:var(--zui-popover-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-popover-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  blue: "border border-[color:var(--zui-popover-content-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-popover-content-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-popover-content-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 8%, transparent))] dark:bg-[var(--zui-popover-content-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 14%, transparent))] text-[color:var(--zui-popover-content-blue-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-blue-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  cyan: "border border-[color:var(--zui-popover-content-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-popover-content-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-popover-content-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 8%, transparent))] dark:bg-[var(--zui-popover-content-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 14%, transparent))] text-[color:var(--zui-popover-content-cyan-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-cyan-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  lime: "border border-[color:var(--zui-popover-content-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-popover-content-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-popover-content-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 8%, transparent))] dark:bg-[var(--zui-popover-content-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 14%, transparent))] text-[color:var(--zui-popover-content-lime-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-lime-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  mint: "border border-[color:var(--zui-popover-content-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-popover-content-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-popover-content-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 8%, transparent))] dark:bg-[var(--zui-popover-content-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 14%, transparent))] text-[color:var(--zui-popover-content-mint-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-mint-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  ocean:
    "border border-[color:var(--zui-popover-content-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-popover-content-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-popover-content-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 8%, transparent))] dark:bg-[var(--zui-popover-content-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 14%, transparent))] text-[color:var(--zui-popover-content-ocean-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-ocean-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  sapphire:
    "border border-[color:var(--zui-popover-content-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-popover-content-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-popover-content-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 8%, transparent))] dark:bg-[var(--zui-popover-content-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 14%, transparent))] text-[color:var(--zui-popover-content-sapphire-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-sapphire-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  lavender:
    "border border-[color:var(--zui-popover-content-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-popover-content-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-popover-content-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 8%, transparent))] dark:bg-[var(--zui-popover-content-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 14%, transparent))] text-[color:var(--zui-popover-content-lavender-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-lavender-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  ruby: "border border-[color:var(--zui-popover-content-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-popover-content-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-popover-content-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 8%, transparent))] dark:bg-[var(--zui-popover-content-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 14%, transparent))] text-[color:var(--zui-popover-content-ruby-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-ruby-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  red: "border border-[color:var(--zui-popover-content-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-popover-content-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-popover-content-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 8%, transparent))] dark:bg-[var(--zui-popover-content-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 14%, transparent))] text-[color:var(--zui-popover-content-red-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-red-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  slate:
    "border border-[color:var(--zui-popover-content-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-popover-content-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-popover-content-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 8%, transparent))] dark:bg-[var(--zui-popover-content-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 14%, transparent))] text-[color:var(--zui-popover-content-slate-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-slate-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  zinc: "border border-[color:var(--zui-popover-content-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-popover-content-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-popover-content-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 8%, transparent))] dark:bg-[var(--zui-popover-content-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 14%, transparent))] text-[color:var(--zui-popover-content-zinc-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-zinc-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  stone:
    "border border-[color:var(--zui-popover-content-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-popover-content-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-popover-content-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 8%, transparent))] dark:bg-[var(--zui-popover-content-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 14%, transparent))] text-[color:var(--zui-popover-content-stone-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-stone-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  royal:
    "border border-[color:var(--zui-popover-content-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-popover-content-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-popover-content-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 8%, transparent))] dark:bg-[var(--zui-popover-content-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 14%, transparent))] text-[color:var(--zui-popover-content-royal-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-royal-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  electric:
    "border border-[color:var(--zui-popover-content-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-popover-content-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-popover-content-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 8%, transparent))] dark:bg-[var(--zui-popover-content-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 14%, transparent))] text-[color:var(--zui-popover-content-electric-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-electric-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  forest:
    "border border-[color:var(--zui-popover-content-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-popover-content-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-popover-content-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 8%, transparent))] dark:bg-[var(--zui-popover-content-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 14%, transparent))] text-[color:var(--zui-popover-content-forest-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-forest-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  sunset:
    "border border-[color:var(--zui-popover-content-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-popover-content-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-popover-content-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 8%, transparent))] dark:bg-[var(--zui-popover-content-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 14%, transparent))] text-[color:var(--zui-popover-content-sunset-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-sunset-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  magenta:
    "border border-[color:var(--zui-popover-content-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-popover-content-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-popover-content-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 8%, transparent))] dark:bg-[var(--zui-popover-content-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 14%, transparent))] text-[color:var(--zui-popover-content-magenta-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-magenta-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  crimson:
    "border border-[color:var(--zui-popover-content-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-popover-content-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-popover-content-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 8%, transparent))] dark:bg-[var(--zui-popover-content-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 14%, transparent))] text-[color:var(--zui-popover-content-crimson-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-crimson-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  aqua: "border border-[color:var(--zui-popover-content-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-popover-content-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-popover-content-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 8%, transparent))] dark:bg-[var(--zui-popover-content-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 14%, transparent))] text-[color:var(--zui-popover-content-aqua-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-aqua-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  plum: "border border-[color:var(--zui-popover-content-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-popover-content-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-popover-content-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 8%, transparent))] dark:bg-[var(--zui-popover-content-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 14%, transparent))] text-[color:var(--zui-popover-content-plum-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-popover-content-plum-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
} as const;

export const zuiPopoverContentSizes = {
  sm: "p-3 text-sm",
  md: "p-4 text-sm",
  lg: "p-5 text-base",
} as const;

export const zuiPopoverContentWidths = {
  xs: "min-w-50 md:min-w-xs",
  sm: "min-w-50 md:min-w-sm",
  md: "min-w-50 md:min-w-md",
  lg: "min-w-50 md:min-w-lg",
  xl: "min-w-50 md:min-w-xl",
  "2xl": "min-w-50 md:min-w-2xl",
} as const;
