export const zuiRadioGroupRootBase = "grid gap-2";

export const zuiRadioGroupItemBase =
  "group inline-flex w-fit items-start gap-2.5 text-sm font-medium text-[color:var(--zui-radio-label-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-radio-label-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiRadioGroupControlBase =
  "grid shrink-0 place-items-center rounded-full border-2 border-[color:var(--zui-radio-border,var(--zui-border,#0000004d))] bg-[var(--zui-radio-bg,var(--zui-surface-muted,transparent))] dark:bg-[var(--zui-radio-bg-dark,var(--zui-surface-muted-dark,transparent))] transition-[background-color,border-color,box-shadow] peer-focus-visible:outline-none peer-focus-visible:ring-2 peer-focus-visible:ring-[var(--zui-radio-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281_/_0.7)))] peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-[var(--zui-radio-ring-offset-focus,var(--zui-ring-offset,oklch(98.4%_0.003_247.858)))] dark:border-[color:var(--zui-radio-border-dark,var(--zui-border-dark,#ffffff4d))] dark:peer-focus-visible:ring-[var(--zui-radio-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894_/_0.7)))] dark:peer-focus-visible:ring-offset-[var(--zui-radio-ring-offset-focus-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))] group-data-[disabled=true]:cursor-not-allowed";

export const zuiRadioGroupIndicatorBase =
  "pointer-events-none block rounded-full opacity-0 transition-opacity duration-150 group-data-[state=checked]:opacity-100";

export const zuiRadioGroupSizes = {
  sm: {
    item: "text-xs",
    control: "mt-0.5 size-4",
    indicator: "size-1.5",
  },
  md: {
    item: "text-sm",
    control: "mt-0.5 size-5",
    indicator: "size-2",
  },
  lg: {
    item: "text-base",
    control: "mt-0.5 size-6",
    indicator: "size-2.5",
  },
} as const;

export const zuiRadioGroupAppearances = {
  default:
    "group-data-[state=checked]:border-[color:var(--zui-radio-default-border-checked,var(--zui-border,oklch(44.6%_0.043_257.281)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-default-border-checked-dark,var(--zui-border-dark,oklch(44.6%_0.043_257.281)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-default-indicator-bg,var(--zui-surface-muted,oklch(44.6%_0.043_257.281)))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-default-indicator-bg-dark,var(--zui-surface-muted-dark,oklch(44.6%_0.043_257.281)))]",
  success:
    "group-data-[state=checked]:border-[color:var(--zui-radio-success-border-checked,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-success-border-checked-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-success-indicator-bg,var(--zui-status-success,oklch(59.6%_0.145_163.225)))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-success-indicator-bg-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225)))]",
  warning:
    "group-data-[state=checked]:border-[color:var(--zui-radio-warning-border-checked,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-warning-border-checked-dark,var(--zui-status-warning-dark,oklch(68.1%_0.162_75.834)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-warning-indicator-bg,var(--zui-status-warning,oklch(68.1%_0.162_75.834)))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-warning-indicator-bg-dark,var(--zui-status-warning-dark,oklch(68.1%_0.162_75.834)))]",
  error:
    "group-data-[state=checked]:border-[color:var(--zui-radio-error-border-checked,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-error-border-checked-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-error-indicator-bg,var(--zui-status-error,oklch(58.6%_0.253_17.585)))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-error-indicator-bg-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585)))]",
  info: "group-data-[state=checked]:border-[color:var(--zui-radio-info-border-checked,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-info-border-checked-dark,var(--zui-status-info-dark,oklch(54.6%_0.245_262.881)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-info-indicator-bg,var(--zui-status-info,oklch(54.6%_0.245_262.881)))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-info-indicator-bg-dark,var(--zui-status-info-dark,oklch(54.6%_0.245_262.881)))]",
  violet:
    "group-data-[state=checked]:border-[color:var(--zui-radio-violet-border-checked,var(--zui-color-violet,oklch(54.1%_0.281_293.009)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-violet-border-checked-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-violet-indicator-bg,color-mix(in oklch, var(--zui-color-violet,oklch(54.1%_0.281_293.009)) 10%, transparent))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-violet-indicator-bg-dark,color-mix(in oklch, var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)) 18%, transparent))]",
  amber:
    "group-data-[state=checked]:border-[color:var(--zui-radio-amber-border-checked,var(--zui-color-amber,oklch(66.6%_0.179_58.318)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-amber-border-checked-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-amber-indicator-bg,color-mix(in oklch, var(--zui-color-amber,oklch(66.6%_0.179_58.318)) 10%, transparent))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-amber-indicator-bg-dark,color-mix(in oklch, var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)) 18%, transparent))]",
  pink: "group-data-[state=checked]:border-[color:var(--zui-radio-pink-border-checked,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-pink-border-checked-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-pink-indicator-bg,color-mix(in oklch, var(--zui-color-pink,oklch(59.2%_0.249_0.584)) 10%, transparent))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-pink-indicator-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)) 18%, transparent))]",
  indigo:
    "group-data-[state=checked]:border-[color:var(--zui-radio-indigo-border-checked,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-indigo-border-checked-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-indigo-indicator-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(51.1%_0.262_276.966)) 10%, transparent))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-indigo-indicator-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)) 18%, transparent))]",
  blue: "border-[color:var(--zui-radio-group-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-radio-group-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-radio-group-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-radio-group-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] data-[state=checked]:border-[color:var(--zui-radio-group-blue-border-checked,var(--zui-color-blue,#2563eb))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-blue-border-checked-dark,var(--zui-color-blue-dark,#3b82f6))] data-[state=checked]:bg-[var(--zui-radio-group-blue-bg-checked,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-blue-bg-checked-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 14%, transparent))]",
  cyan: "border-[color:var(--zui-radio-group-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-radio-group-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-radio-group-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-radio-group-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] data-[state=checked]:border-[color:var(--zui-radio-group-cyan-border-checked,var(--zui-color-cyan,#0891b2))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-cyan-border-checked-dark,var(--zui-color-cyan-dark,#22d3ee))] data-[state=checked]:bg-[var(--zui-radio-group-cyan-bg-checked,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-cyan-bg-checked-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 14%, transparent))]",
  green:
    "border-[color:var(--zui-radio-group-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-radio-group-green-border-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-radio-group-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-radio-group-green-fg-dark,var(--zui-color-green-dark,#22c55e))] data-[state=checked]:border-[color:var(--zui-radio-group-green-border-checked,var(--zui-color-green,#16a34a))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-green-border-checked-dark,var(--zui-color-green-dark,#22c55e))] data-[state=checked]:bg-[var(--zui-radio-group-green-bg-checked,color-mix(in oklch, var(--zui-color-green,#16a34a14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-green-bg-checked-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 14%, transparent))]",
  lime: "border-[color:var(--zui-radio-group-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-radio-group-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-radio-group-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-radio-group-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] data-[state=checked]:border-[color:var(--zui-radio-group-lime-border-checked,var(--zui-color-lime,#65a30d))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-lime-border-checked-dark,var(--zui-color-lime-dark,#a3e635))] data-[state=checked]:bg-[var(--zui-radio-group-lime-bg-checked,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-lime-bg-checked-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 14%, transparent))]",
  mint: "border-[color:var(--zui-radio-group-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-radio-group-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-radio-group-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-radio-group-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] data-[state=checked]:border-[color:var(--zui-radio-group-mint-border-checked,var(--zui-color-mint,#10b981))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-mint-border-checked-dark,var(--zui-color-mint-dark,#6ee7b7))] data-[state=checked]:bg-[var(--zui-radio-group-mint-bg-checked,color-mix(in oklch, var(--zui-color-mint,#10b98114) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-mint-bg-checked-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 14%, transparent))]",
  ocean:
    "border-[color:var(--zui-radio-group-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-radio-group-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-radio-group-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-radio-group-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] data-[state=checked]:border-[color:var(--zui-radio-group-ocean-border-checked,var(--zui-color-ocean,#0284c7))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-ocean-border-checked-dark,var(--zui-color-ocean-dark,#38bdf8))] data-[state=checked]:bg-[var(--zui-radio-group-ocean-bg-checked,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-ocean-bg-checked-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 14%, transparent))]",
  sapphire:
    "border-[color:var(--zui-radio-group-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-radio-group-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-radio-group-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-radio-group-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] data-[state=checked]:border-[color:var(--zui-radio-group-sapphire-border-checked,var(--zui-color-sapphire,#1d4ed8))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-sapphire-border-checked-dark,var(--zui-color-sapphire-dark,#60a5fa))] data-[state=checked]:bg-[var(--zui-radio-group-sapphire-bg-checked,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-sapphire-bg-checked-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 14%, transparent))]",
  lavender:
    "border-[color:var(--zui-radio-group-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-radio-group-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-radio-group-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-radio-group-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] data-[state=checked]:border-[color:var(--zui-radio-group-lavender-border-checked,var(--zui-color-lavender,#8b5cf6))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-lavender-border-checked-dark,var(--zui-color-lavender-dark,#a78bfa))] data-[state=checked]:bg-[var(--zui-radio-group-lavender-bg-checked,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-lavender-bg-checked-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 14%, transparent))]",
  ruby: "border-[color:var(--zui-radio-group-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-radio-group-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-radio-group-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-radio-group-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] data-[state=checked]:border-[color:var(--zui-radio-group-ruby-border-checked,var(--zui-color-ruby,#be123c))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-ruby-border-checked-dark,var(--zui-color-ruby-dark,#fb7185))] data-[state=checked]:bg-[var(--zui-radio-group-ruby-bg-checked,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-ruby-bg-checked-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 14%, transparent))]",
  red: "border-[color:var(--zui-radio-group-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-radio-group-red-border-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-radio-group-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-radio-group-red-fg-dark,var(--zui-color-red-dark,#ef4444))] data-[state=checked]:border-[color:var(--zui-radio-group-red-border-checked,var(--zui-color-red,#dc2626))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-red-border-checked-dark,var(--zui-color-red-dark,#ef4444))] data-[state=checked]:bg-[var(--zui-radio-group-red-bg-checked,color-mix(in oklch, var(--zui-color-red,#dc262614) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-red-bg-checked-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 14%, transparent))]",
  slate:
    "border-[color:var(--zui-radio-group-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-radio-group-slate-border-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-radio-group-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-radio-group-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] data-[state=checked]:border-[color:var(--zui-radio-group-slate-border-checked,var(--zui-color-slate,#475569))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-slate-border-checked-dark,var(--zui-color-slate-dark,#64748b))] data-[state=checked]:bg-[var(--zui-radio-group-slate-bg-checked,color-mix(in oklch, var(--zui-color-slate,#47556914) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-slate-bg-checked-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 14%, transparent))]",
  zinc: "border-[color:var(--zui-radio-group-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-radio-group-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-radio-group-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-radio-group-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] data-[state=checked]:border-[color:var(--zui-radio-group-zinc-border-checked,var(--zui-color-zinc,#52525b))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-zinc-border-checked-dark,var(--zui-color-zinc-dark,#71717a))] data-[state=checked]:bg-[var(--zui-radio-group-zinc-bg-checked,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-zinc-bg-checked-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 14%, transparent))]",
  stone:
    "border-[color:var(--zui-radio-group-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-radio-group-stone-border-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-radio-group-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-radio-group-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] data-[state=checked]:border-[color:var(--zui-radio-group-stone-border-checked,var(--zui-color-stone,#57534e))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-stone-border-checked-dark,var(--zui-color-stone-dark,#78716c))] data-[state=checked]:bg-[var(--zui-radio-group-stone-bg-checked,color-mix(in oklch, var(--zui-color-stone,#57534e14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-stone-bg-checked-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 14%, transparent))]",
  royal:
    "border-[color:var(--zui-radio-group-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-radio-group-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-radio-group-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-radio-group-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] data-[state=checked]:border-[color:var(--zui-radio-group-royal-border-checked,var(--zui-color-royal,#4338ca))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-royal-border-checked-dark,var(--zui-color-royal-dark,#818cf8))] data-[state=checked]:bg-[var(--zui-radio-group-royal-bg-checked,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-royal-bg-checked-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 14%, transparent))]",
  electric:
    "border-[color:var(--zui-radio-group-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-radio-group-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-radio-group-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-radio-group-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] data-[state=checked]:border-[color:var(--zui-radio-group-electric-border-checked,var(--zui-color-electric,#0ea5e9))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-electric-border-checked-dark,var(--zui-color-electric-dark,#38bdf8))] data-[state=checked]:bg-[var(--zui-radio-group-electric-bg-checked,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-electric-bg-checked-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 14%, transparent))]",
  forest:
    "border-[color:var(--zui-radio-group-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-radio-group-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-radio-group-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-radio-group-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] data-[state=checked]:border-[color:var(--zui-radio-group-forest-border-checked,var(--zui-color-forest,#166534))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-forest-border-checked-dark,var(--zui-color-forest-dark,#4ade80))] data-[state=checked]:bg-[var(--zui-radio-group-forest-bg-checked,color-mix(in oklch, var(--zui-color-forest,#16653414) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-forest-bg-checked-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 14%, transparent))]",
  sunset:
    "border-[color:var(--zui-radio-group-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-radio-group-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-radio-group-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-radio-group-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] data-[state=checked]:border-[color:var(--zui-radio-group-sunset-border-checked,var(--zui-color-sunset,#ea580c))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-sunset-border-checked-dark,var(--zui-color-sunset-dark,#fb923c))] data-[state=checked]:bg-[var(--zui-radio-group-sunset-bg-checked,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-sunset-bg-checked-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 14%, transparent))]",
  magenta:
    "border-[color:var(--zui-radio-group-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-radio-group-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-radio-group-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-radio-group-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] data-[state=checked]:border-[color:var(--zui-radio-group-magenta-border-checked,var(--zui-color-magenta,#c026d3))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-magenta-border-checked-dark,var(--zui-color-magenta-dark,#e879f9))] data-[state=checked]:bg-[var(--zui-radio-group-magenta-bg-checked,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-magenta-bg-checked-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 14%, transparent))]",
  crimson:
    "border-[color:var(--zui-radio-group-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-radio-group-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-radio-group-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-radio-group-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] data-[state=checked]:border-[color:var(--zui-radio-group-crimson-border-checked,var(--zui-color-crimson,#b91c1c))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-crimson-border-checked-dark,var(--zui-color-crimson-dark,#f87171))] data-[state=checked]:bg-[var(--zui-radio-group-crimson-bg-checked,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-crimson-bg-checked-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 14%, transparent))]",
  aqua: "border-[color:var(--zui-radio-group-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-radio-group-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-radio-group-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-radio-group-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] data-[state=checked]:border-[color:var(--zui-radio-group-aqua-border-checked,var(--zui-color-aqua,#0f766e))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-aqua-border-checked-dark,var(--zui-color-aqua-dark,#2dd4bf))] data-[state=checked]:bg-[var(--zui-radio-group-aqua-bg-checked,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-aqua-bg-checked-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 14%, transparent))]",
  plum: "border-[color:var(--zui-radio-group-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-radio-group-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-radio-group-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-radio-group-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] data-[state=checked]:border-[color:var(--zui-radio-group-plum-border-checked,var(--zui-color-plum,#7e22ce))] dark:data-[state=checked]:border-[color:var(--zui-radio-group-plum-border-checked-dark,var(--zui-color-plum-dark,#c084fc))] data-[state=checked]:bg-[var(--zui-radio-group-plum-bg-checked,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 8%, transparent))] dark:data-[state=checked]:bg-[var(--zui-radio-group-plum-bg-checked-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 14%, transparent))]",
} as const;

export const zuiRadioGroupOrientations = {
  vertical: "grid gap-2",
  horizontal: "flex flex-wrap gap-x-5 gap-y-2",
} as const;
