export const zuiRadioGroupRootBase = "grid gap-2";

export const zuiRadioGroupItemBase =
  "group inline-flex w-fit items-start gap-2.5 text-sm font-medium text-[color:var(--zui-radio-label-fg,oklch(20.8%_0.042_265.755))] dark:text-[color:var(--zui-radio-label-fg-dark,oklch(98.4%_0.003_247.858))] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiRadioGroupControlBase =
  "grid shrink-0 place-items-center rounded-full border-2 border-[color:var(--zui-radio-border,#0000004d)] bg-[var(--zui-radio-bg,transparent)] dark:bg-[var(--zui-radio-bg-dark,transparent)] transition-[background-color,border-color,box-shadow] peer-focus-visible:outline-none peer-focus-visible:ring-2 peer-focus-visible:ring-[var(--zui-radio-ring-focus,oklch(44.6%_0.043_257.281_/_0.7))] peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-[var(--zui-radio-ring-offset-focus,oklch(98.4%_0.003_247.858))] dark:border-[color:var(--zui-radio-border-dark,#ffffff4d)] dark:peer-focus-visible:ring-[var(--zui-radio-ring-focus-dark,oklch(86.9%_0.022_252.894_/_0.7))] dark:peer-focus-visible:ring-offset-[var(--zui-radio-ring-offset-focus-dark,oklch(12.9%_0.042_264.695))] group-data-[disabled=true]:cursor-not-allowed";

export const zuiRadioGroupIndicatorBase =
  "pointer-events-none block rounded-full opacity-0 transition-opacity duration-150 group-data-[state=checked]:opacity-100";

export const zuiRadioGroupSizes = {
  sm: {
    item: "text-xs",
    control: "mt-0.5 size-4",
    indicator: "size-1.5",
  },
  md: {
    item: "text-sm",
    control: "mt-0.5 size-5",
    indicator: "size-2",
  },
  lg: {
    item: "text-base",
    control: "mt-0.5 size-6",
    indicator: "size-2.5",
  },
} as const;

export const zuiRadioGroupAppearances = {
  default:
    "group-data-[state=checked]:border-[color:var(--zui-radio-default-border-checked,oklch(44.6%_0.043_257.281))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-default-border-checked-dark,oklch(44.6%_0.043_257.281))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-default-indicator-bg,oklch(44.6%_0.043_257.281))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-default-indicator-bg-dark,oklch(44.6%_0.043_257.281))]",
  success:
    "group-data-[state=checked]:border-[color:var(--zui-radio-success-border-checked,oklch(59.6%_0.145_163.225))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-success-border-checked-dark,oklch(59.6%_0.145_163.225))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-success-indicator-bg,oklch(59.6%_0.145_163.225))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-success-indicator-bg-dark,oklch(59.6%_0.145_163.225))]",
  warning:
    "group-data-[state=checked]:border-[color:var(--zui-radio-warning-border-checked,oklch(68.1%_0.162_75.834))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-warning-border-checked-dark,oklch(68.1%_0.162_75.834))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-warning-indicator-bg,oklch(68.1%_0.162_75.834))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-warning-indicator-bg-dark,oklch(68.1%_0.162_75.834))]",
  error:
    "group-data-[state=checked]:border-[color:var(--zui-radio-error-border-checked,oklch(58.6%_0.253_17.585))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-error-border-checked-dark,oklch(58.6%_0.253_17.585))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-error-indicator-bg,oklch(58.6%_0.253_17.585))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-error-indicator-bg-dark,oklch(58.6%_0.253_17.585))]",
  info: "group-data-[state=checked]:border-[color:var(--zui-radio-info-border-checked,oklch(54.6%_0.245_262.881))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-info-border-checked-dark,oklch(54.6%_0.245_262.881))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-info-indicator-bg,oklch(54.6%_0.245_262.881))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-info-indicator-bg-dark,oklch(54.6%_0.245_262.881))]",
  violet:
    "group-data-[state=checked]:border-[color:var(--zui-radio-violet-border-checked,oklch(54.1%_0.281_293.009))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-violet-border-checked-dark,oklch(54.1%_0.281_293.009))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-violet-indicator-bg,oklch(54.1%_0.281_293.009))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-violet-indicator-bg-dark,oklch(54.1%_0.281_293.009))]",
  amber:
    "group-data-[state=checked]:border-[color:var(--zui-radio-amber-border-checked,oklch(66.6%_0.179_58.318))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-amber-border-checked-dark,oklch(66.6%_0.179_58.318))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-amber-indicator-bg,oklch(66.6%_0.179_58.318))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-amber-indicator-bg-dark,oklch(66.6%_0.179_58.318))]",
  pink: "group-data-[state=checked]:border-[color:var(--zui-radio-pink-border-checked,oklch(59.2%_0.249_0.584))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-pink-border-checked-dark,oklch(59.2%_0.249_0.584))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-pink-indicator-bg,oklch(59.2%_0.249_0.584))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-pink-indicator-bg-dark,oklch(59.2%_0.249_0.584))]",
  indigo:
    "group-data-[state=checked]:border-[color:var(--zui-radio-indigo-border-checked,oklch(51.1%_0.262_276.966))] dark:group-data-[state=checked]:border-[color:var(--zui-radio-indigo-border-checked-dark,oklch(51.1%_0.262_276.966))] [&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-indigo-indicator-bg,oklch(51.1%_0.262_276.966))] dark:[&_[data-slot=radio-group-indicator]]:bg-[var(--zui-radio-indigo-indicator-bg-dark,oklch(51.1%_0.262_276.966))]",
  blue: "border-[color:var(--zui-radio-group-blue-border,#2563eb)] dark:border-[color:var(--zui-radio-group-blue-border-dark,#3b82f6)] text-[color:var(--zui-radio-group-blue-fg,#2563eb)] dark:text-[color:var(--zui-radio-group-blue-fg-dark,#3b82f6)] data-[state=checked]:border-[color:var(--zui-radio-group-blue-border-checked,#2563eb)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-blue-border-checked-dark,#3b82f6)] data-[state=checked]:bg-[var(--zui-radio-group-blue-bg-checked,#2563eb14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-blue-bg-checked-dark,#3b82f624)]",
  cyan: "border-[color:var(--zui-radio-group-cyan-border,#0891b2)] dark:border-[color:var(--zui-radio-group-cyan-border-dark,#22d3ee)] text-[color:var(--zui-radio-group-cyan-fg,#0891b2)] dark:text-[color:var(--zui-radio-group-cyan-fg-dark,#22d3ee)] data-[state=checked]:border-[color:var(--zui-radio-group-cyan-border-checked,#0891b2)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-cyan-border-checked-dark,#22d3ee)] data-[state=checked]:bg-[var(--zui-radio-group-cyan-bg-checked,#0891b214)] dark:data-[state=checked]:bg-[var(--zui-radio-group-cyan-bg-checked-dark,#22d3ee24)]",
  green:
    "border-[color:var(--zui-radio-group-green-border,#16a34a)] dark:border-[color:var(--zui-radio-group-green-border-dark,#22c55e)] text-[color:var(--zui-radio-group-green-fg,#16a34a)] dark:text-[color:var(--zui-radio-group-green-fg-dark,#22c55e)] data-[state=checked]:border-[color:var(--zui-radio-group-green-border-checked,#16a34a)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-green-border-checked-dark,#22c55e)] data-[state=checked]:bg-[var(--zui-radio-group-green-bg-checked,#16a34a14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-green-bg-checked-dark,#22c55e24)]",
  lime: "border-[color:var(--zui-radio-group-lime-border,#65a30d)] dark:border-[color:var(--zui-radio-group-lime-border-dark,#a3e635)] text-[color:var(--zui-radio-group-lime-fg,#65a30d)] dark:text-[color:var(--zui-radio-group-lime-fg-dark,#a3e635)] data-[state=checked]:border-[color:var(--zui-radio-group-lime-border-checked,#65a30d)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-lime-border-checked-dark,#a3e635)] data-[state=checked]:bg-[var(--zui-radio-group-lime-bg-checked,#65a30d14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-lime-bg-checked-dark,#a3e63524)]",
  mint: "border-[color:var(--zui-radio-group-mint-border,#10b981)] dark:border-[color:var(--zui-radio-group-mint-border-dark,#6ee7b7)] text-[color:var(--zui-radio-group-mint-fg,#10b981)] dark:text-[color:var(--zui-radio-group-mint-fg-dark,#6ee7b7)] data-[state=checked]:border-[color:var(--zui-radio-group-mint-border-checked,#10b981)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-mint-border-checked-dark,#6ee7b7)] data-[state=checked]:bg-[var(--zui-radio-group-mint-bg-checked,#10b98114)] dark:data-[state=checked]:bg-[var(--zui-radio-group-mint-bg-checked-dark,#6ee7b724)]",
  ocean:
    "border-[color:var(--zui-radio-group-ocean-border,#0284c7)] dark:border-[color:var(--zui-radio-group-ocean-border-dark,#38bdf8)] text-[color:var(--zui-radio-group-ocean-fg,#0284c7)] dark:text-[color:var(--zui-radio-group-ocean-fg-dark,#38bdf8)] data-[state=checked]:border-[color:var(--zui-radio-group-ocean-border-checked,#0284c7)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-ocean-border-checked-dark,#38bdf8)] data-[state=checked]:bg-[var(--zui-radio-group-ocean-bg-checked,#0284c714)] dark:data-[state=checked]:bg-[var(--zui-radio-group-ocean-bg-checked-dark,#38bdf824)]",
  sapphire:
    "border-[color:var(--zui-radio-group-sapphire-border,#1d4ed8)] dark:border-[color:var(--zui-radio-group-sapphire-border-dark,#60a5fa)] text-[color:var(--zui-radio-group-sapphire-fg,#1d4ed8)] dark:text-[color:var(--zui-radio-group-sapphire-fg-dark,#60a5fa)] data-[state=checked]:border-[color:var(--zui-radio-group-sapphire-border-checked,#1d4ed8)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-sapphire-border-checked-dark,#60a5fa)] data-[state=checked]:bg-[var(--zui-radio-group-sapphire-bg-checked,#1d4ed814)] dark:data-[state=checked]:bg-[var(--zui-radio-group-sapphire-bg-checked-dark,#60a5fa24)]",
  lavender:
    "border-[color:var(--zui-radio-group-lavender-border,#8b5cf6)] dark:border-[color:var(--zui-radio-group-lavender-border-dark,#a78bfa)] text-[color:var(--zui-radio-group-lavender-fg,#8b5cf6)] dark:text-[color:var(--zui-radio-group-lavender-fg-dark,#a78bfa)] data-[state=checked]:border-[color:var(--zui-radio-group-lavender-border-checked,#8b5cf6)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-lavender-border-checked-dark,#a78bfa)] data-[state=checked]:bg-[var(--zui-radio-group-lavender-bg-checked,#8b5cf614)] dark:data-[state=checked]:bg-[var(--zui-radio-group-lavender-bg-checked-dark,#a78bfa24)]",
  ruby: "border-[color:var(--zui-radio-group-ruby-border,#be123c)] dark:border-[color:var(--zui-radio-group-ruby-border-dark,#fb7185)] text-[color:var(--zui-radio-group-ruby-fg,#be123c)] dark:text-[color:var(--zui-radio-group-ruby-fg-dark,#fb7185)] data-[state=checked]:border-[color:var(--zui-radio-group-ruby-border-checked,#be123c)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-ruby-border-checked-dark,#fb7185)] data-[state=checked]:bg-[var(--zui-radio-group-ruby-bg-checked,#be123c14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-ruby-bg-checked-dark,#fb718524)]",
  red: "border-[color:var(--zui-radio-group-red-border,#dc2626)] dark:border-[color:var(--zui-radio-group-red-border-dark,#ef4444)] text-[color:var(--zui-radio-group-red-fg,#dc2626)] dark:text-[color:var(--zui-radio-group-red-fg-dark,#ef4444)] data-[state=checked]:border-[color:var(--zui-radio-group-red-border-checked,#dc2626)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-red-border-checked-dark,#ef4444)] data-[state=checked]:bg-[var(--zui-radio-group-red-bg-checked,#dc262614)] dark:data-[state=checked]:bg-[var(--zui-radio-group-red-bg-checked-dark,#ef444424)]",
  slate:
    "border-[color:var(--zui-radio-group-slate-border,#475569)] dark:border-[color:var(--zui-radio-group-slate-border-dark,#64748b)] text-[color:var(--zui-radio-group-slate-fg,#475569)] dark:text-[color:var(--zui-radio-group-slate-fg-dark,#64748b)] data-[state=checked]:border-[color:var(--zui-radio-group-slate-border-checked,#475569)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-slate-border-checked-dark,#64748b)] data-[state=checked]:bg-[var(--zui-radio-group-slate-bg-checked,#47556914)] dark:data-[state=checked]:bg-[var(--zui-radio-group-slate-bg-checked-dark,#64748b24)]",
  zinc: "border-[color:var(--zui-radio-group-zinc-border,#52525b)] dark:border-[color:var(--zui-radio-group-zinc-border-dark,#71717a)] text-[color:var(--zui-radio-group-zinc-fg,#52525b)] dark:text-[color:var(--zui-radio-group-zinc-fg-dark,#71717a)] data-[state=checked]:border-[color:var(--zui-radio-group-zinc-border-checked,#52525b)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-zinc-border-checked-dark,#71717a)] data-[state=checked]:bg-[var(--zui-radio-group-zinc-bg-checked,#52525b14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-zinc-bg-checked-dark,#71717a24)]",
  stone:
    "border-[color:var(--zui-radio-group-stone-border,#57534e)] dark:border-[color:var(--zui-radio-group-stone-border-dark,#78716c)] text-[color:var(--zui-radio-group-stone-fg,#57534e)] dark:text-[color:var(--zui-radio-group-stone-fg-dark,#78716c)] data-[state=checked]:border-[color:var(--zui-radio-group-stone-border-checked,#57534e)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-stone-border-checked-dark,#78716c)] data-[state=checked]:bg-[var(--zui-radio-group-stone-bg-checked,#57534e14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-stone-bg-checked-dark,#78716c24)]",
  royal:
    "border-[color:var(--zui-radio-group-royal-border,#4338ca)] dark:border-[color:var(--zui-radio-group-royal-border-dark,#818cf8)] text-[color:var(--zui-radio-group-royal-fg,#4338ca)] dark:text-[color:var(--zui-radio-group-royal-fg-dark,#818cf8)] data-[state=checked]:border-[color:var(--zui-radio-group-royal-border-checked,#4338ca)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-royal-border-checked-dark,#818cf8)] data-[state=checked]:bg-[var(--zui-radio-group-royal-bg-checked,#4338ca14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-royal-bg-checked-dark,#818cf824)]",
  electric:
    "border-[color:var(--zui-radio-group-electric-border,#0ea5e9)] dark:border-[color:var(--zui-radio-group-electric-border-dark,#38bdf8)] text-[color:var(--zui-radio-group-electric-fg,#0ea5e9)] dark:text-[color:var(--zui-radio-group-electric-fg-dark,#38bdf8)] data-[state=checked]:border-[color:var(--zui-radio-group-electric-border-checked,#0ea5e9)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-electric-border-checked-dark,#38bdf8)] data-[state=checked]:bg-[var(--zui-radio-group-electric-bg-checked,#0ea5e914)] dark:data-[state=checked]:bg-[var(--zui-radio-group-electric-bg-checked-dark,#38bdf824)]",
  forest:
    "border-[color:var(--zui-radio-group-forest-border,#166534)] dark:border-[color:var(--zui-radio-group-forest-border-dark,#4ade80)] text-[color:var(--zui-radio-group-forest-fg,#166534)] dark:text-[color:var(--zui-radio-group-forest-fg-dark,#4ade80)] data-[state=checked]:border-[color:var(--zui-radio-group-forest-border-checked,#166534)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-forest-border-checked-dark,#4ade80)] data-[state=checked]:bg-[var(--zui-radio-group-forest-bg-checked,#16653414)] dark:data-[state=checked]:bg-[var(--zui-radio-group-forest-bg-checked-dark,#4ade8024)]",
  sunset:
    "border-[color:var(--zui-radio-group-sunset-border,#ea580c)] dark:border-[color:var(--zui-radio-group-sunset-border-dark,#fb923c)] text-[color:var(--zui-radio-group-sunset-fg,#ea580c)] dark:text-[color:var(--zui-radio-group-sunset-fg-dark,#fb923c)] data-[state=checked]:border-[color:var(--zui-radio-group-sunset-border-checked,#ea580c)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-sunset-border-checked-dark,#fb923c)] data-[state=checked]:bg-[var(--zui-radio-group-sunset-bg-checked,#ea580c14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-sunset-bg-checked-dark,#fb923c24)]",
  magenta:
    "border-[color:var(--zui-radio-group-magenta-border,#c026d3)] dark:border-[color:var(--zui-radio-group-magenta-border-dark,#e879f9)] text-[color:var(--zui-radio-group-magenta-fg,#c026d3)] dark:text-[color:var(--zui-radio-group-magenta-fg-dark,#e879f9)] data-[state=checked]:border-[color:var(--zui-radio-group-magenta-border-checked,#c026d3)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-magenta-border-checked-dark,#e879f9)] data-[state=checked]:bg-[var(--zui-radio-group-magenta-bg-checked,#c026d314)] dark:data-[state=checked]:bg-[var(--zui-radio-group-magenta-bg-checked-dark,#e879f924)]",
  crimson:
    "border-[color:var(--zui-radio-group-crimson-border,#b91c1c)] dark:border-[color:var(--zui-radio-group-crimson-border-dark,#f87171)] text-[color:var(--zui-radio-group-crimson-fg,#b91c1c)] dark:text-[color:var(--zui-radio-group-crimson-fg-dark,#f87171)] data-[state=checked]:border-[color:var(--zui-radio-group-crimson-border-checked,#b91c1c)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-crimson-border-checked-dark,#f87171)] data-[state=checked]:bg-[var(--zui-radio-group-crimson-bg-checked,#b91c1c14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-crimson-bg-checked-dark,#f8717124)]",
  aqua: "border-[color:var(--zui-radio-group-aqua-border,#0f766e)] dark:border-[color:var(--zui-radio-group-aqua-border-dark,#2dd4bf)] text-[color:var(--zui-radio-group-aqua-fg,#0f766e)] dark:text-[color:var(--zui-radio-group-aqua-fg-dark,#2dd4bf)] data-[state=checked]:border-[color:var(--zui-radio-group-aqua-border-checked,#0f766e)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-aqua-border-checked-dark,#2dd4bf)] data-[state=checked]:bg-[var(--zui-radio-group-aqua-bg-checked,#0f766e14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-aqua-bg-checked-dark,#2dd4bf24)]",
  plum: "border-[color:var(--zui-radio-group-plum-border,#7e22ce)] dark:border-[color:var(--zui-radio-group-plum-border-dark,#c084fc)] text-[color:var(--zui-radio-group-plum-fg,#7e22ce)] dark:text-[color:var(--zui-radio-group-plum-fg-dark,#c084fc)] data-[state=checked]:border-[color:var(--zui-radio-group-plum-border-checked,#7e22ce)] dark:data-[state=checked]:border-[color:var(--zui-radio-group-plum-border-checked-dark,#c084fc)] data-[state=checked]:bg-[var(--zui-radio-group-plum-bg-checked,#7e22ce14)] dark:data-[state=checked]:bg-[var(--zui-radio-group-plum-bg-checked-dark,#c084fc24)]",
} as const;

export const zuiRadioGroupOrientations = {
  vertical: "grid gap-2",
  horizontal: "flex flex-wrap gap-x-5 gap-y-2",
} as const;
