export const zuiScrollAreaBase =
  "relative min-w-0 rounded-xl outline-none transition-[background-color,border-color,box-shadow,scrollbar-color] duration-200 [scrollbar-color:var(--zui-scroll-area-thumb,var(--zui-border,#94a3b8))_var(--zui-scroll-area-track,var(--zui-surface-muted,transparent))] [scrollbar-width:thin] focus-visible:ring-2 focus-visible:ring-[var(--zui-scroll-area-ring-focus,var(--zui-focus-ring,oklch(54.6%_0.245_262.881_/_0.28)))] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--zui-scroll-area-ring-offset-focus,var(--zui-ring-offset,#ffffff))] dark:focus-visible:ring-[var(--zui-scroll-area-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.165_254.624_/_0.28)))] dark:focus-visible:ring-offset-[var(--zui-scroll-area-ring-offset-focus-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))] [&::-webkit-scrollbar]:h-[var(--zui-scroll-area-size,0.625rem)] [&::-webkit-scrollbar]:w-[var(--zui-scroll-area-size,0.625rem)] [&::-webkit-scrollbar-corner]:bg-transparent [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:border-2 [&::-webkit-scrollbar-thumb]:border-solid [&::-webkit-scrollbar-thumb]:border-[var(--zui-scroll-area-thumb-border,var(--zui-border,transparent))] [&::-webkit-scrollbar-thumb]:bg-[var(--zui-scroll-area-thumb,var(--zui-border,#94a3b8))] [&::-webkit-scrollbar-track]:rounded-full [&::-webkit-scrollbar-track]:bg-[var(--zui-scroll-area-track,var(--zui-surface-muted,transparent))]";

export const zuiScrollAreaAppearances = {
  default:
    "[--zui-scroll-area-thumb:#94a3b8] [--zui-scroll-area-thumb-border:#f8fafc] [--zui-scroll-area-track:#e2e8f0] dark:[--zui-scroll-area-thumb:#64748b] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#1e293b]",
  muted:
    "[--zui-scroll-area-thumb:#cbd5e1] [--zui-scroll-area-thumb-border:#f8fafc] [--zui-scroll-area-track:#f1f5f9] dark:[--zui-scroll-area-thumb:#475569] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#0f172a]",
  outline:
    "border border-[color:var(--zui-scroll-area-outline-border,var(--zui-border,#cbd5e1))] [--zui-scroll-area-thumb:#64748b] [--zui-scroll-area-thumb-border:#ffffff] [--zui-scroll-area-track:#e2e8f0] dark:border-[color:var(--zui-scroll-area-outline-border-dark,var(--zui-border-dark,#334155))] dark:[--zui-scroll-area-thumb:#94a3b8] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#1e293b]",
  glass:
    "border border-[color:var(--zui-scroll-area-glass-border,var(--zui-border,#ffffff80))] bg-[var(--zui-scroll-area-glass-bg,var(--zui-surface-soft,#ffffff99))] backdrop-blur-md [--zui-scroll-area-thumb:oklch(70.7%_0.165_254.624_/_0.9)] [--zui-scroll-area-thumb-border:#ffffff66] [--zui-scroll-area-track:#ffffff33] dark:border-[color:var(--zui-scroll-area-glass-border-dark,var(--zui-border-dark,#ffffff1f))] dark:bg-[var(--zui-scroll-area-glass-bg-dark,var(--zui-surface-soft-dark,#0f172acc))] dark:[--zui-scroll-area-thumb:oklch(78.9%_0.154_211.53_/_0.8)] dark:[--zui-scroll-area-thumb-border:#02061766] dark:[--zui-scroll-area-track:#ffffff12]",
  sky: "border border-[color:var(--zui-scroll-area-sky-border,var(--zui-color-sky,oklch(62.3%_0.214_259.815_/_0.35)))] [--zui-scroll-area-thumb:oklch(54.6%_0.245_262.881)] [--zui-scroll-area-thumb-border:#eff6ff] [--zui-scroll-area-track:#dbeafe] dark:border-[color:var(--zui-scroll-area-sky-border-dark,var(--zui-color-sky-dark,oklch(70.7%_0.165_254.624_/_0.35)))] dark:[--zui-scroll-area-thumb:oklch(70.7%_0.165_254.624)] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#172554]",
  emerald:
    "border border-[color:var(--zui-scroll-area-emerald-border,var(--zui-color-emerald,oklch(59.6%_0.145_163.225_/_0.35)))] [--zui-scroll-area-thumb:oklch(59.6%_0.145_163.225)] [--zui-scroll-area-thumb-border:#ecfdf5] [--zui-scroll-area-track:#d1fae5] dark:border-[color:var(--zui-scroll-area-emerald-border-dark,var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48_/_0.35)))] dark:[--zui-scroll-area-thumb:oklch(69.6%_0.17_162.48)] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#064e3b]",
  rose: "border border-[color:var(--zui-scroll-area-rose-border,var(--zui-color-rose,oklch(58.6%_0.253_17.585_/_0.3)))] [--zui-scroll-area-thumb:oklch(58.6%_0.253_17.585)] [--zui-scroll-area-thumb-border:#fff1f2] [--zui-scroll-area-track:#ffe4e6] dark:border-[color:var(--zui-scroll-area-rose-border-dark,var(--zui-color-rose-dark,oklch(71.2%_0.194_13.428_/_0.35)))] dark:[--zui-scroll-area-thumb:oklch(71.2%_0.194_13.428)] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#4c0519]",
  amber:
    "border border-[color:var(--zui-scroll-area-amber-border,var(--zui-color-amber,oklch(76.9%_0.188_70.08_/_0.35)))] [--zui-scroll-area-thumb:oklch(66.6%_0.179_58.318)] [--zui-scroll-area-thumb-border:#fffbeb] [--zui-scroll-area-track:#fef3c7] dark:border-[color:var(--zui-scroll-area-amber-border-dark,var(--zui-color-amber-dark,oklch(82.8%_0.189_84.429_/_0.35)))] dark:[--zui-scroll-area-thumb:oklch(82.8%_0.189_84.429)] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#451a03]",
  violet:
    "border border-[color:var(--zui-scroll-area-violet-border,var(--zui-color-violet,oklch(60.6%_0.25_292.717_/_0.35)))] [--zui-scroll-area-thumb:oklch(54.1%_0.281_293.009)] [--zui-scroll-area-thumb-border:#f5f3ff] [--zui-scroll-area-track:#ede9fe] dark:border-[color:var(--zui-scroll-area-violet-border-dark,var(--zui-color-violet-dark,oklch(70.2%_0.183_293.541_/_0.35)))] dark:[--zui-scroll-area-thumb:oklch(70.2%_0.183_293.541)] dark:[--zui-scroll-area-thumb-border:#020617] dark:[--zui-scroll-area-track:#2e1065]",
  blue: "border border-[color:var(--zui-scroll-area-blue-border,var(--zui-color-blue,#2563eb66))] dark:border-[color:var(--zui-scroll-area-blue-border-dark,var(--zui-color-blue-dark,#3b82f666))] [--zui-scroll-area-thumb:var(--zui-scroll-area-blue-thumb,var(--zui-color-blue,#2563eb))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-blue-thumb-dark,var(--zui-color-blue-dark,#3b82f6))] [--zui-scroll-area-track:var(--zui-scroll-area-blue-track,var(--zui-color-blue,#2563eb14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-blue-track-dark,var(--zui-color-blue-dark,#3b82f624))]",
  cyan: "border border-[color:var(--zui-scroll-area-cyan-border,var(--zui-color-cyan,#0891b266))] dark:border-[color:var(--zui-scroll-area-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-cyan-thumb,var(--zui-color-cyan,#0891b2))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-cyan-thumb-dark,var(--zui-color-cyan-dark,#22d3ee))] [--zui-scroll-area-track:var(--zui-scroll-area-cyan-track,var(--zui-color-cyan,#0891b214))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-cyan-track-dark,var(--zui-color-cyan-dark,#22d3ee24))]",
  green:
    "border border-[color:var(--zui-scroll-area-green-border,var(--zui-color-green,#16a34a66))] dark:border-[color:var(--zui-scroll-area-green-border-dark,var(--zui-color-green-dark,#22c55e66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-green-thumb,var(--zui-color-green,#16a34a))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-green-thumb-dark,var(--zui-color-green-dark,#22c55e))] [--zui-scroll-area-track:var(--zui-scroll-area-green-track,var(--zui-color-green,#16a34a14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-green-track-dark,var(--zui-color-green-dark,#22c55e24))]",
  lime: "border border-[color:var(--zui-scroll-area-lime-border,var(--zui-color-lime,#65a30d66))] dark:border-[color:var(--zui-scroll-area-lime-border-dark,var(--zui-color-lime-dark,#a3e63566))] [--zui-scroll-area-thumb:var(--zui-scroll-area-lime-thumb,var(--zui-color-lime,#65a30d))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-lime-thumb-dark,var(--zui-color-lime-dark,#a3e635))] [--zui-scroll-area-track:var(--zui-scroll-area-lime-track,var(--zui-color-lime,#65a30d14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-lime-track-dark,var(--zui-color-lime-dark,#a3e63524))]",
  mint: "border border-[color:var(--zui-scroll-area-mint-border,var(--zui-color-mint,#10b98166))] dark:border-[color:var(--zui-scroll-area-mint-border-dark,var(--zui-color-mint-dark,#6ee7b766))] [--zui-scroll-area-thumb:var(--zui-scroll-area-mint-thumb,var(--zui-color-mint,#10b981))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-mint-thumb-dark,var(--zui-color-mint-dark,#6ee7b7))] [--zui-scroll-area-track:var(--zui-scroll-area-mint-track,var(--zui-color-mint,#10b98114))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-mint-track-dark,var(--zui-color-mint-dark,#6ee7b724))]",
  ocean:
    "border border-[color:var(--zui-scroll-area-ocean-border,var(--zui-color-ocean,#0284c766))] dark:border-[color:var(--zui-scroll-area-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf866))] [--zui-scroll-area-thumb:var(--zui-scroll-area-ocean-thumb,var(--zui-color-ocean,#0284c7))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-ocean-thumb-dark,var(--zui-color-ocean-dark,#38bdf8))] [--zui-scroll-area-track:var(--zui-scroll-area-ocean-track,var(--zui-color-ocean,#0284c714))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-ocean-track-dark,var(--zui-color-ocean-dark,#38bdf824))]",
  sapphire:
    "border border-[color:var(--zui-scroll-area-sapphire-border,var(--zui-color-sapphire,#1d4ed866))] dark:border-[color:var(--zui-scroll-area-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-sapphire-thumb,var(--zui-color-sapphire,#1d4ed8))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-sapphire-thumb-dark,var(--zui-color-sapphire-dark,#60a5fa))] [--zui-scroll-area-track:var(--zui-scroll-area-sapphire-track,var(--zui-color-sapphire,#1d4ed814))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-sapphire-track-dark,var(--zui-color-sapphire-dark,#60a5fa24))]",
  lavender:
    "border border-[color:var(--zui-scroll-area-lavender-border,var(--zui-color-lavender,#8b5cf666))] dark:border-[color:var(--zui-scroll-area-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-lavender-thumb,var(--zui-color-lavender,#8b5cf6))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-lavender-thumb-dark,var(--zui-color-lavender-dark,#a78bfa))] [--zui-scroll-area-track:var(--zui-scroll-area-lavender-track,var(--zui-color-lavender,#8b5cf614))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-lavender-track-dark,var(--zui-color-lavender-dark,#a78bfa24))]",
  ruby: "border border-[color:var(--zui-scroll-area-ruby-border,var(--zui-color-ruby,#be123c66))] dark:border-[color:var(--zui-scroll-area-ruby-border-dark,var(--zui-color-ruby-dark,#fb718566))] [--zui-scroll-area-thumb:var(--zui-scroll-area-ruby-thumb,var(--zui-color-ruby,#be123c))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-ruby-thumb-dark,var(--zui-color-ruby-dark,#fb7185))] [--zui-scroll-area-track:var(--zui-scroll-area-ruby-track,var(--zui-color-ruby,#be123c14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-ruby-track-dark,var(--zui-color-ruby-dark,#fb718524))]",
  red: "border border-[color:var(--zui-scroll-area-red-border,var(--zui-color-red,#dc262666))] dark:border-[color:var(--zui-scroll-area-red-border-dark,var(--zui-color-red-dark,#ef444466))] [--zui-scroll-area-thumb:var(--zui-scroll-area-red-thumb,var(--zui-color-red,#dc2626))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-red-thumb-dark,var(--zui-color-red-dark,#ef4444))] [--zui-scroll-area-track:var(--zui-scroll-area-red-track,var(--zui-color-red,#dc262614))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-red-track-dark,var(--zui-color-red-dark,#ef444424))]",
  slate:
    "border border-[color:var(--zui-scroll-area-slate-border,var(--zui-color-slate,#47556966))] dark:border-[color:var(--zui-scroll-area-slate-border-dark,var(--zui-color-slate-dark,#64748b66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-slate-thumb,var(--zui-color-slate,#475569))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-slate-thumb-dark,var(--zui-color-slate-dark,#64748b))] [--zui-scroll-area-track:var(--zui-scroll-area-slate-track,var(--zui-color-slate,#47556914))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-slate-track-dark,var(--zui-color-slate-dark,#64748b24))]",
  zinc: "border border-[color:var(--zui-scroll-area-zinc-border,var(--zui-color-zinc,#52525b66))] dark:border-[color:var(--zui-scroll-area-zinc-border-dark,var(--zui-color-zinc-dark,#71717a66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-zinc-thumb,var(--zui-color-zinc,#52525b))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-zinc-thumb-dark,var(--zui-color-zinc-dark,#71717a))] [--zui-scroll-area-track:var(--zui-scroll-area-zinc-track,var(--zui-color-zinc,#52525b14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-zinc-track-dark,var(--zui-color-zinc-dark,#71717a24))]",
  stone:
    "border border-[color:var(--zui-scroll-area-stone-border,var(--zui-color-stone,#57534e66))] dark:border-[color:var(--zui-scroll-area-stone-border-dark,var(--zui-color-stone-dark,#78716c66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-stone-thumb,var(--zui-color-stone,#57534e))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-stone-thumb-dark,var(--zui-color-stone-dark,#78716c))] [--zui-scroll-area-track:var(--zui-scroll-area-stone-track,var(--zui-color-stone,#57534e14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-stone-track-dark,var(--zui-color-stone-dark,#78716c24))]",
  royal:
    "border border-[color:var(--zui-scroll-area-royal-border,var(--zui-color-royal,#4338ca66))] dark:border-[color:var(--zui-scroll-area-royal-border-dark,var(--zui-color-royal-dark,#818cf866))] [--zui-scroll-area-thumb:var(--zui-scroll-area-royal-thumb,var(--zui-color-royal,#4338ca))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-royal-thumb-dark,var(--zui-color-royal-dark,#818cf8))] [--zui-scroll-area-track:var(--zui-scroll-area-royal-track,var(--zui-color-royal,#4338ca14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-royal-track-dark,var(--zui-color-royal-dark,#818cf824))]",
  electric:
    "border border-[color:var(--zui-scroll-area-electric-border,var(--zui-color-electric,#0ea5e966))] dark:border-[color:var(--zui-scroll-area-electric-border-dark,var(--zui-color-electric-dark,#38bdf866))] [--zui-scroll-area-thumb:var(--zui-scroll-area-electric-thumb,var(--zui-color-electric,#0ea5e9))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-electric-thumb-dark,var(--zui-color-electric-dark,#38bdf8))] [--zui-scroll-area-track:var(--zui-scroll-area-electric-track,var(--zui-color-electric,#0ea5e914))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-electric-track-dark,var(--zui-color-electric-dark,#38bdf824))]",
  forest:
    "border border-[color:var(--zui-scroll-area-forest-border,var(--zui-color-forest,#16653466))] dark:border-[color:var(--zui-scroll-area-forest-border-dark,var(--zui-color-forest-dark,#4ade8066))] [--zui-scroll-area-thumb:var(--zui-scroll-area-forest-thumb,var(--zui-color-forest,#166534))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-forest-thumb-dark,var(--zui-color-forest-dark,#4ade80))] [--zui-scroll-area-track:var(--zui-scroll-area-forest-track,var(--zui-color-forest,#16653414))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-forest-track-dark,var(--zui-color-forest-dark,#4ade8024))]",
  sunset:
    "border border-[color:var(--zui-scroll-area-sunset-border,var(--zui-color-sunset,#ea580c66))] dark:border-[color:var(--zui-scroll-area-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-sunset-thumb,var(--zui-color-sunset,#ea580c))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-sunset-thumb-dark,var(--zui-color-sunset-dark,#fb923c))] [--zui-scroll-area-track:var(--zui-scroll-area-sunset-track,var(--zui-color-sunset,#ea580c14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-sunset-track-dark,var(--zui-color-sunset-dark,#fb923c24))]",
  magenta:
    "border border-[color:var(--zui-scroll-area-magenta-border,var(--zui-color-magenta,#c026d366))] dark:border-[color:var(--zui-scroll-area-magenta-border-dark,var(--zui-color-magenta-dark,#e879f966))] [--zui-scroll-area-thumb:var(--zui-scroll-area-magenta-thumb,var(--zui-color-magenta,#c026d3))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-magenta-thumb-dark,var(--zui-color-magenta-dark,#e879f9))] [--zui-scroll-area-track:var(--zui-scroll-area-magenta-track,var(--zui-color-magenta,#c026d314))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-magenta-track-dark,var(--zui-color-magenta-dark,#e879f924))]",
  crimson:
    "border border-[color:var(--zui-scroll-area-crimson-border,var(--zui-color-crimson,#b91c1c66))] dark:border-[color:var(--zui-scroll-area-crimson-border-dark,var(--zui-color-crimson-dark,#f8717166))] [--zui-scroll-area-thumb:var(--zui-scroll-area-crimson-thumb,var(--zui-color-crimson,#b91c1c))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-crimson-thumb-dark,var(--zui-color-crimson-dark,#f87171))] [--zui-scroll-area-track:var(--zui-scroll-area-crimson-track,var(--zui-color-crimson,#b91c1c14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-crimson-track-dark,var(--zui-color-crimson-dark,#f8717124))]",
  aqua: "border border-[color:var(--zui-scroll-area-aqua-border,var(--zui-color-aqua,#0f766e66))] dark:border-[color:var(--zui-scroll-area-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-aqua-thumb,var(--zui-color-aqua,#0f766e))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-aqua-thumb-dark,var(--zui-color-aqua-dark,#2dd4bf))] [--zui-scroll-area-track:var(--zui-scroll-area-aqua-track,var(--zui-color-aqua,#0f766e14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-aqua-track-dark,var(--zui-color-aqua-dark,#2dd4bf24))]",
  plum: "border border-[color:var(--zui-scroll-area-plum-border,var(--zui-color-plum,#7e22ce66))] dark:border-[color:var(--zui-scroll-area-plum-border-dark,var(--zui-color-plum-dark,#c084fc66))] [--zui-scroll-area-thumb:var(--zui-scroll-area-plum-thumb,var(--zui-color-plum,#7e22ce))] dark:[--zui-scroll-area-thumb:var(--zui-scroll-area-plum-thumb-dark,var(--zui-color-plum-dark,#c084fc))] [--zui-scroll-area-track:var(--zui-scroll-area-plum-track,var(--zui-color-plum,#7e22ce14))] dark:[--zui-scroll-area-track:var(--zui-scroll-area-plum-track-dark,var(--zui-color-plum-dark,#c084fc24))]",
} as const;

export const zuiScrollAreaSizes = {
  sm: "[--zui-scroll-area-size:0.375rem]",
  md: "[--zui-scroll-area-size:0.625rem]",
  lg: "[--zui-scroll-area-size:0.875rem]",
} as const;

export const zuiScrollAreaOrientations = {
  vertical: "overflow-x-hidden overflow-y-auto",
  horizontal: "overflow-x-auto overflow-y-hidden",
  both: "overflow-auto",
} as const;

export const zuiScrollAreaVisibility = {
  auto: "",
  hover:
    "[scrollbar-color:transparent_transparent] hover:[scrollbar-color:var(--zui-scroll-area-thumb,var(--zui-border,#94a3b8))_var(--zui-scroll-area-track,var(--zui-surface-muted,transparent))] [&::-webkit-scrollbar-thumb]:bg-transparent hover:[&::-webkit-scrollbar-thumb]:bg-[var(--zui-scroll-area-thumb,var(--zui-border,#94a3b8))] [&::-webkit-scrollbar-track]:bg-transparent hover:[&::-webkit-scrollbar-track]:bg-[var(--zui-scroll-area-track,var(--zui-surface-muted,transparent))]",
  always: "",
  hidden:
    "[scrollbar-width:none] [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar]:h-0 [&::-webkit-scrollbar]:w-0",
} as const;

export const zuiScrollAreaShadows = {
  false: "",
  true: "[box-shadow:inset_0_2px_12px_rgb(15_23_42_/_0.08)] dark:[box-shadow:inset_0_2px_12px_rgb(0_0_0_/_0.3)]",
} as const;
