export const zuiSelectTriggerBase =
  "flex items-center cursor-pointer justify-between rounded-md border transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-select-trigger-ring-focus,oklch(44.6%_0.03_256.802))] dark:focus-visible:ring-[var(--zui-select-trigger-ring-focus-dark,oklch(70.7%_0.022_261.325))] focus-visible:ring-offset-2";

export const zuiSelectTriggerVariants = {
  default:
    "border-[color:var(--zui-select-trigger-default-border,oklch(87.2%_0.01_258.338))] dark:border-[color:var(--zui-select-trigger-default-border-dark,oklch(87.2%_0.01_258.338))] bg-[var(--zui-select-trigger-default-bg,#ffffff)] dark:bg-[var(--zui-select-trigger-default-bg-dark,#000000)] text-[color:var(--zui-select-trigger-default-fg,oklch(13%_0.028_261.692))] dark:text-[color:var(--zui-select-trigger-default-fg-dark,#ffffff)]",
  outline:
    "border-2 border-[color:var(--zui-select-trigger-outline-border,oklch(55.1%_0.027_264.364))] dark:border-[color:var(--zui-select-trigger-outline-border-dark,oklch(55.1%_0.027_264.364))] text-[color:var(--zui-select-trigger-outline-fg,oklch(13%_0.028_261.692))] dark:text-[color:var(--zui-select-trigger-outline-fg-dark,oklch(96.7%_0.003_264.542))]",
  ghost:
    "border-[color:var(--zui-select-trigger-ghost-border,transparent)] dark:border-[color:var(--zui-select-trigger-ghost-border-dark,transparent)] text-[color:var(--zui-select-trigger-ghost-fg,oklch(13%_0.028_261.692))] dark:text-[color:var(--zui-select-trigger-ghost-fg-dark,oklch(96.7%_0.003_264.542))]",
  sky: "border-[color:var(--zui-select-trigger-sky-border,oklch(44.3%_0.11_240.79))] dark:border-[color:var(--zui-select-trigger-sky-border-dark,oklch(58.8%_0.158_241.966))] text-[color:var(--zui-select-trigger-sky-fg,oklch(29.3%_0.066_243.157))] dark:text-[color:var(--zui-select-trigger-sky-fg-dark,oklch(58.8%_0.158_241.966))]",
  rose: "border-[color:var(--zui-select-trigger-rose-border,oklch(45.5%_0.188_13.697))] dark:border-[color:var(--zui-select-trigger-rose-border-dark,oklch(58.6%_0.253_17.585))] text-[color:var(--zui-select-trigger-rose-fg,oklch(27.1%_0.105_12.094))] dark:text-[color:var(--zui-select-trigger-rose-fg-dark,oklch(58.6%_0.253_17.585))]",
  purple:
    "border-[color:var(--zui-select-trigger-purple-border,oklch(43.8%_0.218_303.724))] dark:border-[color:var(--zui-select-trigger-purple-border-dark,oklch(55.8%_0.288_302.321))] text-[color:var(--zui-select-trigger-purple-fg,oklch(29.1%_0.149_302.717))] dark:text-[color:var(--zui-select-trigger-purple-fg-dark,oklch(55.8%_0.288_302.321))]",
  pink: "border-[color:var(--zui-select-trigger-pink-border,oklch(45.9%_0.187_3.815))] dark:border-[color:var(--zui-select-trigger-pink-border-dark,oklch(59.2%_0.249_0.584))] text-[color:var(--zui-select-trigger-pink-fg,oklch(28.4%_0.109_3.907))] dark:text-[color:var(--zui-select-trigger-pink-fg-dark,oklch(59.2%_0.249_0.584))]",
  orange:
    "border-[color:var(--zui-select-trigger-orange-border,oklch(47%_0.157_37.304))] dark:border-[color:var(--zui-select-trigger-orange-border-dark,oklch(64.6%_0.222_41.116))] text-[color:var(--zui-select-trigger-orange-fg,oklch(26.6%_0.079_36.259))] dark:text-[color:var(--zui-select-trigger-orange-fg-dark,oklch(64.6%_0.222_41.116))]",
  yellow:
    "border-[color:var(--zui-select-trigger-yellow-border,oklch(47.6%_0.114_61.907))] dark:border-[color:var(--zui-select-trigger-yellow-border-dark,oklch(68.1%_0.162_75.834))] text-[color:var(--zui-select-trigger-yellow-fg,oklch(28.6%_0.066_53.813))] dark:text-[color:var(--zui-select-trigger-yellow-fg-dark,oklch(68.1%_0.162_75.834))]",
  teal: "border-[color:var(--zui-select-trigger-teal-border,oklch(43.7%_0.078_188.216))] dark:border-[color:var(--zui-select-trigger-teal-border-dark,oklch(60%_0.118_184.704))] text-[color:var(--zui-select-trigger-teal-fg,oklch(27.7%_0.046_192.524))] dark:text-[color:var(--zui-select-trigger-teal-fg-dark,oklch(60%_0.118_184.704))]",
  indigo:
    "border-[color:var(--zui-select-trigger-indigo-border,oklch(58.5%_0.233_277.117))] dark:border-[color:var(--zui-select-trigger-indigo-border-dark,oklch(58.5%_0.233_277.117))] text-[color:var(--zui-select-trigger-indigo-fg,oklch(25.7%_0.09_281.288))] dark:text-[color:var(--zui-select-trigger-indigo-fg-dark,oklch(58.5%_0.233_277.117))]",
  emerald:
    "border-[color:var(--zui-select-trigger-emerald-border,oklch(43.2%_0.095_166.913))] dark:border-[color:var(--zui-select-trigger-emerald-border-dark,oklch(59.6%_0.145_163.225))] text-[color:var(--zui-select-trigger-emerald-fg,oklch(26.2%_0.051_172.552))] dark:text-[color:var(--zui-select-trigger-emerald-fg-dark,oklch(59.6%_0.145_163.225))]",
  glass:
    "border-[color:var(--zui-select-trigger-glass-border,#00000026)] dark:border-[color:var(--zui-select-trigger-glass-border-dark,#ffffff26)] bg-[var(--zui-select-trigger-glass-bg,#0000001a)] dark:bg-[var(--zui-select-trigger-glass-bg-dark,#ffffff1a)] text-[color:var(--zui-select-trigger-glass-fg,oklch(13%_0.028_261.692))] dark:text-[color:var(--zui-select-trigger-glass-fg-dark,#ffffff)] backdrop-blur-md",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-blue-from,oklch(37.9%_0.146_265.522))] dark:from-[var(--zui-select-trigger-gradient-blue-from-dark,oklch(54.6%_0.245_262.881))] to-[var(--zui-select-trigger-gradient-blue-to,oklch(38.1%_0.176_304.987))] dark:to-[var(--zui-select-trigger-gradient-blue-to-dark,oklch(55.8%_0.288_302.321))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-blue-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-blue-fg-dark,#ffffff)]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-green-from,oklch(39.3%_0.095_152.535))] dark:from-[var(--zui-select-trigger-gradient-green-from-dark,oklch(62.7%_0.194_149.214))] to-[var(--zui-select-trigger-gradient-green-to,oklch(40.5%_0.101_131.063))] dark:to-[var(--zui-select-trigger-gradient-green-to-dark,oklch(64.8%_0.2_131.684))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-green-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-green-fg-dark,#ffffff)]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-red-from,oklch(39.6%_0.141_25.723))] dark:from-[var(--zui-select-trigger-gradient-red-from-dark,oklch(57.7%_0.245_27.325))] to-[var(--zui-select-trigger-gradient-red-to,oklch(40.8%_0.153_2.432))] dark:to-[var(--zui-select-trigger-gradient-red-to-dark,oklch(59.2%_0.249_0.584))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-red-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-red-fg-dark,#ffffff)]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-yellow-from,oklch(42.1%_0.095_57.708))] dark:from-[var(--zui-select-trigger-gradient-yellow-from-dark,oklch(68.1%_0.162_75.834))] to-[var(--zui-select-trigger-gradient-yellow-to,oklch(40.8%_0.123_38.172))] dark:to-[var(--zui-select-trigger-gradient-yellow-to-dark,oklch(64.6%_0.222_41.116))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-yellow-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-yellow-fg-dark,#ffffff)]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-purple-from,oklch(38.1%_0.176_304.987))] dark:from-[var(--zui-select-trigger-gradient-purple-from-dark,oklch(55.8%_0.288_302.321))] to-[var(--zui-select-trigger-gradient-purple-to,oklch(40.8%_0.153_2.432))] dark:to-[var(--zui-select-trigger-gradient-purple-to-dark,oklch(59.2%_0.249_0.584))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-purple-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-purple-fg-dark,#ffffff)]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-teal-from,oklch(38.6%_0.063_188.416))] dark:from-[var(--zui-select-trigger-gradient-teal-from-dark,oklch(60%_0.118_184.704))] to-[var(--zui-select-trigger-gradient-teal-to,oklch(39.8%_0.07_227.392))] dark:to-[var(--zui-select-trigger-gradient-teal-to-dark,oklch(60.9%_0.126_221.723))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-teal-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-teal-fg-dark,#ffffff)]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-indigo-from,oklch(35.9%_0.144_278.697))] dark:from-[var(--zui-select-trigger-gradient-indigo-from-dark,oklch(51.1%_0.262_276.966))] to-[var(--zui-select-trigger-gradient-indigo-to,oklch(38.1%_0.176_304.987))] dark:to-[var(--zui-select-trigger-gradient-indigo-to-dark,oklch(55.8%_0.288_302.321))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-indigo-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-indigo-fg-dark,#ffffff)]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-pink-from,oklch(40.8%_0.153_2.432))] dark:from-[var(--zui-select-trigger-gradient-pink-from-dark,oklch(59.2%_0.249_0.584))] to-[var(--zui-select-trigger-gradient-pink-to,oklch(41%_0.159_10.272))] dark:to-[var(--zui-select-trigger-gradient-pink-to-dark,oklch(58.6%_0.253_17.585))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-pink-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-pink-fg-dark,#ffffff)]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-orange-from,oklch(40.8%_0.123_38.172))] dark:from-[var(--zui-select-trigger-gradient-orange-from-dark,oklch(64.6%_0.222_41.116))] to-[var(--zui-select-trigger-gradient-orange-to,oklch(39.6%_0.141_25.723))] dark:to-[var(--zui-select-trigger-gradient-orange-to-dark,oklch(57.7%_0.245_27.325))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-orange-fg,#ffffff)] dark:text-[color:var(--zui-select-trigger-gradient-orange-fg-dark,#ffffff)]",
  blue: "border border-[color:var(--zui-select-trigger-blue-border,#2563eb)] dark:border-[color:var(--zui-select-trigger-blue-border-dark,#3b82f6)] text-[color:var(--zui-select-trigger-blue-fg,#2563eb)] dark:text-[color:var(--zui-select-trigger-blue-fg-dark,#3b82f6)] hover:bg-[var(--zui-select-trigger-blue-bg-hover,#2563eb14)] dark:hover:bg-[var(--zui-select-trigger-blue-bg-hover-dark,#3b82f624)]",
  cyan: "border border-[color:var(--zui-select-trigger-cyan-border,#0891b2)] dark:border-[color:var(--zui-select-trigger-cyan-border-dark,#22d3ee)] text-[color:var(--zui-select-trigger-cyan-fg,#0891b2)] dark:text-[color:var(--zui-select-trigger-cyan-fg-dark,#22d3ee)] hover:bg-[var(--zui-select-trigger-cyan-bg-hover,#0891b214)] dark:hover:bg-[var(--zui-select-trigger-cyan-bg-hover-dark,#22d3ee24)]",
  green:
    "border border-[color:var(--zui-select-trigger-green-border,#16a34a)] dark:border-[color:var(--zui-select-trigger-green-border-dark,#22c55e)] text-[color:var(--zui-select-trigger-green-fg,#16a34a)] dark:text-[color:var(--zui-select-trigger-green-fg-dark,#22c55e)] hover:bg-[var(--zui-select-trigger-green-bg-hover,#16a34a14)] dark:hover:bg-[var(--zui-select-trigger-green-bg-hover-dark,#22c55e24)]",
  lime: "border border-[color:var(--zui-select-trigger-lime-border,#65a30d)] dark:border-[color:var(--zui-select-trigger-lime-border-dark,#a3e635)] text-[color:var(--zui-select-trigger-lime-fg,#65a30d)] dark:text-[color:var(--zui-select-trigger-lime-fg-dark,#a3e635)] hover:bg-[var(--zui-select-trigger-lime-bg-hover,#65a30d14)] dark:hover:bg-[var(--zui-select-trigger-lime-bg-hover-dark,#a3e63524)]",
  mint: "border border-[color:var(--zui-select-trigger-mint-border,#10b981)] dark:border-[color:var(--zui-select-trigger-mint-border-dark,#6ee7b7)] text-[color:var(--zui-select-trigger-mint-fg,#10b981)] dark:text-[color:var(--zui-select-trigger-mint-fg-dark,#6ee7b7)] hover:bg-[var(--zui-select-trigger-mint-bg-hover,#10b98114)] dark:hover:bg-[var(--zui-select-trigger-mint-bg-hover-dark,#6ee7b724)]",
  ocean:
    "border border-[color:var(--zui-select-trigger-ocean-border,#0284c7)] dark:border-[color:var(--zui-select-trigger-ocean-border-dark,#38bdf8)] text-[color:var(--zui-select-trigger-ocean-fg,#0284c7)] dark:text-[color:var(--zui-select-trigger-ocean-fg-dark,#38bdf8)] hover:bg-[var(--zui-select-trigger-ocean-bg-hover,#0284c714)] dark:hover:bg-[var(--zui-select-trigger-ocean-bg-hover-dark,#38bdf824)]",
  sapphire:
    "border border-[color:var(--zui-select-trigger-sapphire-border,#1d4ed8)] dark:border-[color:var(--zui-select-trigger-sapphire-border-dark,#60a5fa)] text-[color:var(--zui-select-trigger-sapphire-fg,#1d4ed8)] dark:text-[color:var(--zui-select-trigger-sapphire-fg-dark,#60a5fa)] hover:bg-[var(--zui-select-trigger-sapphire-bg-hover,#1d4ed814)] dark:hover:bg-[var(--zui-select-trigger-sapphire-bg-hover-dark,#60a5fa24)]",
  lavender:
    "border border-[color:var(--zui-select-trigger-lavender-border,#8b5cf6)] dark:border-[color:var(--zui-select-trigger-lavender-border-dark,#a78bfa)] text-[color:var(--zui-select-trigger-lavender-fg,#8b5cf6)] dark:text-[color:var(--zui-select-trigger-lavender-fg-dark,#a78bfa)] hover:bg-[var(--zui-select-trigger-lavender-bg-hover,#8b5cf614)] dark:hover:bg-[var(--zui-select-trigger-lavender-bg-hover-dark,#a78bfa24)]",
  ruby: "border border-[color:var(--zui-select-trigger-ruby-border,#be123c)] dark:border-[color:var(--zui-select-trigger-ruby-border-dark,#fb7185)] text-[color:var(--zui-select-trigger-ruby-fg,#be123c)] dark:text-[color:var(--zui-select-trigger-ruby-fg-dark,#fb7185)] hover:bg-[var(--zui-select-trigger-ruby-bg-hover,#be123c14)] dark:hover:bg-[var(--zui-select-trigger-ruby-bg-hover-dark,#fb718524)]",
  red: "border border-[color:var(--zui-select-trigger-red-border,#dc2626)] dark:border-[color:var(--zui-select-trigger-red-border-dark,#ef4444)] text-[color:var(--zui-select-trigger-red-fg,#dc2626)] dark:text-[color:var(--zui-select-trigger-red-fg-dark,#ef4444)] hover:bg-[var(--zui-select-trigger-red-bg-hover,#dc262614)] dark:hover:bg-[var(--zui-select-trigger-red-bg-hover-dark,#ef444424)]",
  slate:
    "border border-[color:var(--zui-select-trigger-slate-border,#475569)] dark:border-[color:var(--zui-select-trigger-slate-border-dark,#64748b)] text-[color:var(--zui-select-trigger-slate-fg,#475569)] dark:text-[color:var(--zui-select-trigger-slate-fg-dark,#64748b)] hover:bg-[var(--zui-select-trigger-slate-bg-hover,#47556914)] dark:hover:bg-[var(--zui-select-trigger-slate-bg-hover-dark,#64748b24)]",
  zinc: "border border-[color:var(--zui-select-trigger-zinc-border,#52525b)] dark:border-[color:var(--zui-select-trigger-zinc-border-dark,#71717a)] text-[color:var(--zui-select-trigger-zinc-fg,#52525b)] dark:text-[color:var(--zui-select-trigger-zinc-fg-dark,#71717a)] hover:bg-[var(--zui-select-trigger-zinc-bg-hover,#52525b14)] dark:hover:bg-[var(--zui-select-trigger-zinc-bg-hover-dark,#71717a24)]",
  stone:
    "border border-[color:var(--zui-select-trigger-stone-border,#57534e)] dark:border-[color:var(--zui-select-trigger-stone-border-dark,#78716c)] text-[color:var(--zui-select-trigger-stone-fg,#57534e)] dark:text-[color:var(--zui-select-trigger-stone-fg-dark,#78716c)] hover:bg-[var(--zui-select-trigger-stone-bg-hover,#57534e14)] dark:hover:bg-[var(--zui-select-trigger-stone-bg-hover-dark,#78716c24)]",
  royal:
    "border border-[color:var(--zui-select-trigger-royal-border,#4338ca)] dark:border-[color:var(--zui-select-trigger-royal-border-dark,#818cf8)] text-[color:var(--zui-select-trigger-royal-fg,#4338ca)] dark:text-[color:var(--zui-select-trigger-royal-fg-dark,#818cf8)] hover:bg-[var(--zui-select-trigger-royal-bg-hover,#4338ca14)] dark:hover:bg-[var(--zui-select-trigger-royal-bg-hover-dark,#818cf824)]",
  electric:
    "border border-[color:var(--zui-select-trigger-electric-border,#0ea5e9)] dark:border-[color:var(--zui-select-trigger-electric-border-dark,#38bdf8)] text-[color:var(--zui-select-trigger-electric-fg,#0ea5e9)] dark:text-[color:var(--zui-select-trigger-electric-fg-dark,#38bdf8)] hover:bg-[var(--zui-select-trigger-electric-bg-hover,#0ea5e914)] dark:hover:bg-[var(--zui-select-trigger-electric-bg-hover-dark,#38bdf824)]",
  forest:
    "border border-[color:var(--zui-select-trigger-forest-border,#166534)] dark:border-[color:var(--zui-select-trigger-forest-border-dark,#4ade80)] text-[color:var(--zui-select-trigger-forest-fg,#166534)] dark:text-[color:var(--zui-select-trigger-forest-fg-dark,#4ade80)] hover:bg-[var(--zui-select-trigger-forest-bg-hover,#16653414)] dark:hover:bg-[var(--zui-select-trigger-forest-bg-hover-dark,#4ade8024)]",
  sunset:
    "border border-[color:var(--zui-select-trigger-sunset-border,#ea580c)] dark:border-[color:var(--zui-select-trigger-sunset-border-dark,#fb923c)] text-[color:var(--zui-select-trigger-sunset-fg,#ea580c)] dark:text-[color:var(--zui-select-trigger-sunset-fg-dark,#fb923c)] hover:bg-[var(--zui-select-trigger-sunset-bg-hover,#ea580c14)] dark:hover:bg-[var(--zui-select-trigger-sunset-bg-hover-dark,#fb923c24)]",
  magenta:
    "border border-[color:var(--zui-select-trigger-magenta-border,#c026d3)] dark:border-[color:var(--zui-select-trigger-magenta-border-dark,#e879f9)] text-[color:var(--zui-select-trigger-magenta-fg,#c026d3)] dark:text-[color:var(--zui-select-trigger-magenta-fg-dark,#e879f9)] hover:bg-[var(--zui-select-trigger-magenta-bg-hover,#c026d314)] dark:hover:bg-[var(--zui-select-trigger-magenta-bg-hover-dark,#e879f924)]",
  crimson:
    "border border-[color:var(--zui-select-trigger-crimson-border,#b91c1c)] dark:border-[color:var(--zui-select-trigger-crimson-border-dark,#f87171)] text-[color:var(--zui-select-trigger-crimson-fg,#b91c1c)] dark:text-[color:var(--zui-select-trigger-crimson-fg-dark,#f87171)] hover:bg-[var(--zui-select-trigger-crimson-bg-hover,#b91c1c14)] dark:hover:bg-[var(--zui-select-trigger-crimson-bg-hover-dark,#f8717124)]",
  aqua: "border border-[color:var(--zui-select-trigger-aqua-border,#0f766e)] dark:border-[color:var(--zui-select-trigger-aqua-border-dark,#2dd4bf)] text-[color:var(--zui-select-trigger-aqua-fg,#0f766e)] dark:text-[color:var(--zui-select-trigger-aqua-fg-dark,#2dd4bf)] hover:bg-[var(--zui-select-trigger-aqua-bg-hover,#0f766e14)] dark:hover:bg-[var(--zui-select-trigger-aqua-bg-hover-dark,#2dd4bf24)]",
  plum: "border border-[color:var(--zui-select-trigger-plum-border,#7e22ce)] dark:border-[color:var(--zui-select-trigger-plum-border-dark,#c084fc)] text-[color:var(--zui-select-trigger-plum-fg,#7e22ce)] dark:text-[color:var(--zui-select-trigger-plum-fg-dark,#c084fc)] hover:bg-[var(--zui-select-trigger-plum-bg-hover,#7e22ce14)] dark:hover:bg-[var(--zui-select-trigger-plum-bg-hover-dark,#c084fc24)]",
} as const;

export const zuiSelectSizes = {
  sm: "px-2 py-1 text-sm",
  md: "px-3 py-2",
  lg: "px-4 py-3 text-lg",
} as const;

export const zuiSelectItemBase =
  "cursor-pointer px-3 py-2 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-select-item-ring-focus,oklch(44.6%_0.03_256.802))] dark:focus-visible:ring-[var(--zui-select-item-ring-focus-dark,oklch(70.7%_0.022_261.325))] focus-visible:ring-inset";

export const zuiSelectItemAppearances = {
  default:
    "bg-[var(--zui-select-item-default-bg,#ffffff)] dark:bg-[var(--zui-select-item-default-bg-dark,#000000)] text-[color:var(--zui-select-item-default-fg,oklch(21%_0.034_264.665))] dark:text-[color:var(--zui-select-item-default-fg-dark,oklch(92.8%_0.006_264.531))] data-[selected=true]:bg-[var(--zui-select-item-default-bg,oklch(92.8%_0.006_264.531))] dark:data-[selected=true]:bg-[var(--zui-select-item-default-bg-dark,oklch(92.8%_0.006_264.531))] data-[selected=true]:text-[color:var(--zui-select-item-default-fg,oklch(37.3%_0.034_259.733))] dark:data-[selected=true]:text-[color:var(--zui-select-item-default-fg-dark,oklch(21%_0.034_264.665))]",
  glass:
    "bg-[var(--zui-select-item-glass-bg,#0000001a)] dark:bg-[var(--zui-select-item-glass-bg-dark,#ffffff1a)] text-[color:var(--zui-select-item-glass-fg,oklch(37.3%_0.034_259.733))] dark:text-[color:var(--zui-select-item-glass-fg-dark,oklch(21%_0.034_264.665))] data-[selected=true]:bg-[var(--zui-select-item-glass-bg,#0000001a)] dark:data-[selected=true]:bg-[var(--zui-select-item-glass-bg-dark,#ffffff1a)] data-[selected=true]:text-[color:var(--zui-select-item-glass-fg,oklch(37.3%_0.034_259.733))] dark:data-[selected=true]:text-[color:var(--zui-select-item-glass-fg-dark,oklch(21%_0.034_264.665))]",
  outline:
    "border-2 border-[color:var(--zui-select-item-outline-border,oklch(55.1%_0.027_264.364))] dark:border-[color:var(--zui-select-item-outline-border-dark,oklch(55.1%_0.027_264.364))] text-[color:var(--zui-select-item-outline-fg,oklch(21%_0.034_264.665))] dark:text-[color:var(--zui-select-item-outline-fg-dark,oklch(96.7%_0.003_264.542))] data-[selected=true]:border-2 data-[selected=true]:border-[color:var(--zui-select-item-outline-border,oklch(55.1%_0.027_264.364))] dark:data-[selected=true]:border-[color:var(--zui-select-item-outline-border-dark,oklch(55.1%_0.027_264.364))] data-[selected=true]:bg-[var(--zui-select-item-outline-bg,oklch(92.8%_0.006_264.531))] dark:data-[selected=true]:bg-[var(--zui-select-item-outline-bg-dark,oklch(92.8%_0.006_264.531))] data-[selected=true]:text-[color:var(--zui-select-item-outline-fg,oklch(21%_0.034_264.665))] dark:data-[selected=true]:text-[color:var(--zui-select-item-outline-fg-dark,oklch(21%_0.034_264.665))]",
  ghost:
    "border-[color:var(--zui-select-item-ghost-border,transparent)] dark:border-[color:var(--zui-select-item-ghost-border-dark,transparent)] text-[color:var(--zui-select-item-ghost-fg,oklch(21%_0.034_264.665))] dark:text-[color:var(--zui-select-item-ghost-fg-dark,oklch(96.7%_0.003_264.542))] data-[selected=true]:border-[color:var(--zui-select-item-ghost-border,transparent)] dark:data-[selected=true]:border-[color:var(--zui-select-item-ghost-border-dark,transparent)] data-[selected=true]:bg-[var(--zui-select-item-ghost-bg,transparent)] dark:data-[selected=true]:bg-[var(--zui-select-item-ghost-bg-dark,transparent)] data-[selected=true]:text-[color:var(--zui-select-item-ghost-fg,oklch(21%_0.034_264.665))] dark:data-[selected=true]:text-[color:var(--zui-select-item-ghost-fg-dark,oklch(96.7%_0.003_264.542))]",
  sky: "border-[color:var(--zui-select-item-sky-border,oklch(39.1%_0.09_240.876))] dark:border-[color:var(--zui-select-item-sky-border-dark,oklch(58.8%_0.158_241.966))] text-[color:var(--zui-select-item-sky-fg,oklch(39.1%_0.09_240.876))] dark:text-[color:var(--zui-select-item-sky-fg-dark,oklch(90.1%_0.058_230.902))] data-[selected=true]:border-[color:var(--zui-select-item-sky-border,oklch(39.1%_0.09_240.876))] dark:data-[selected=true]:border-[color:var(--zui-select-item-sky-border-dark,oklch(58.8%_0.158_241.966))] data-[selected=true]:bg-[var(--zui-select-item-sky-bg,oklch(90.1%_0.058_230.902))] dark:data-[selected=true]:bg-[var(--zui-select-item-sky-bg-dark,oklch(90.1%_0.058_230.902))] data-[selected=true]:text-[color:var(--zui-select-item-sky-fg,oklch(39.1%_0.09_240.876))] dark:data-[selected=true]:text-[color:var(--zui-select-item-sky-fg-dark,oklch(39.1%_0.09_240.876))]",
  rose: "border-[color:var(--zui-select-item-rose-border,oklch(41%_0.159_10.272))] dark:border-[color:var(--zui-select-item-rose-border-dark,oklch(58.6%_0.253_17.585))] text-[color:var(--zui-select-item-rose-fg,oklch(41%_0.159_10.272))] dark:text-[color:var(--zui-select-item-rose-fg-dark,oklch(89.2%_0.058_10.001))] data-[selected=true]:border-[color:var(--zui-select-item-rose-border,oklch(41%_0.159_10.272))] dark:data-[selected=true]:border-[color:var(--zui-select-item-rose-border-dark,oklch(58.6%_0.253_17.585))] data-[selected=true]:bg-[var(--zui-select-item-rose-bg,oklch(89.2%_0.058_10.001))] dark:data-[selected=true]:bg-[var(--zui-select-item-rose-bg-dark,oklch(89.2%_0.058_10.001))] data-[selected=true]:text-[color:var(--zui-select-item-rose-fg,oklch(41%_0.159_10.272))] dark:data-[selected=true]:text-[color:var(--zui-select-item-rose-fg-dark,oklch(41%_0.159_10.272))]",
  purple:
    "border-[color:var(--zui-select-item-purple-border,oklch(38.1%_0.176_304.987))] dark:border-[color:var(--zui-select-item-purple-border-dark,oklch(55.8%_0.288_302.321))] text-[color:var(--zui-select-item-purple-fg,oklch(38.1%_0.176_304.987))] dark:text-[color:var(--zui-select-item-purple-fg-dark,oklch(90.2%_0.063_306.703))] data-[selected=true]:border-[color:var(--zui-select-item-purple-border,oklch(38.1%_0.176_304.987))] dark:data-[selected=true]:border-[color:var(--zui-select-item-purple-border-dark,oklch(55.8%_0.288_302.321))] data-[selected=true]:bg-[var(--zui-select-item-purple-bg,oklch(90.2%_0.063_306.703))] dark:data-[selected=true]:bg-[var(--zui-select-item-purple-bg-dark,oklch(90.2%_0.063_306.703))] data-[selected=true]:text-[color:var(--zui-select-item-purple-fg,oklch(38.1%_0.176_304.987))] dark:data-[selected=true]:text-[color:var(--zui-select-item-purple-fg-dark,oklch(38.1%_0.176_304.987))]",
  pink: "border-[color:var(--zui-select-item-pink-border,oklch(40.8%_0.153_2.432))] dark:border-[color:var(--zui-select-item-pink-border-dark,oklch(59.2%_0.249_0.584))] text-[color:var(--zui-select-item-pink-fg,oklch(40.8%_0.153_2.432))] dark:text-[color:var(--zui-select-item-pink-fg-dark,oklch(89.9%_0.061_343.231))] data-[selected=true]:border-[color:var(--zui-select-item-pink-border,oklch(40.8%_0.153_2.432))] dark:data-[selected=true]:border-[color:var(--zui-select-item-pink-border-dark,oklch(59.2%_0.249_0.584))] data-[selected=true]:bg-[var(--zui-select-item-pink-bg,oklch(89.9%_0.061_343.231))] dark:data-[selected=true]:bg-[var(--zui-select-item-pink-bg-dark,oklch(89.9%_0.061_343.231))] data-[selected=true]:text-[color:var(--zui-select-item-pink-fg,oklch(40.8%_0.153_2.432))] dark:data-[selected=true]:text-[color:var(--zui-select-item-pink-fg-dark,oklch(40.8%_0.153_2.432))]",
  orange:
    "border-[color:var(--zui-select-item-orange-border,oklch(40.8%_0.123_38.172))] dark:border-[color:var(--zui-select-item-orange-border-dark,oklch(64.6%_0.222_41.116))] text-[color:var(--zui-select-item-orange-fg,oklch(40.8%_0.123_38.172))] dark:text-[color:var(--zui-select-item-orange-fg-dark,oklch(90.1%_0.076_70.697))] data-[selected=true]:border-[color:var(--zui-select-item-orange-border,oklch(40.8%_0.123_38.172))] dark:data-[selected=true]:border-[color:var(--zui-select-item-orange-border-dark,oklch(64.6%_0.222_41.116))] data-[selected=true]:bg-[var(--zui-select-item-orange-bg,oklch(90.1%_0.076_70.697))] dark:data-[selected=true]:bg-[var(--zui-select-item-orange-bg-dark,oklch(90.1%_0.076_70.697))] data-[selected=true]:text-[color:var(--zui-select-item-orange-fg,oklch(40.8%_0.123_38.172))] dark:data-[selected=true]:text-[color:var(--zui-select-item-orange-fg-dark,oklch(40.8%_0.123_38.172))]",
  yellow:
    "border-[color:var(--zui-select-item-yellow-border,oklch(42.1%_0.095_57.708))] dark:border-[color:var(--zui-select-item-yellow-border-dark,oklch(68.1%_0.162_75.834))] text-[color:var(--zui-select-item-yellow-fg,oklch(42.1%_0.095_57.708))] dark:text-[color:var(--zui-select-item-yellow-fg-dark,oklch(94.5%_0.129_101.54))] data-[selected=true]:border-[color:var(--zui-select-item-yellow-border,oklch(42.1%_0.095_57.708))] dark:data-[selected=true]:border-[color:var(--zui-select-item-yellow-border-dark,oklch(68.1%_0.162_75.834))] data-[selected=true]:bg-[var(--zui-select-item-yellow-bg,oklch(94.5%_0.129_101.54))] dark:data-[selected=true]:bg-[var(--zui-select-item-yellow-bg-dark,oklch(94.5%_0.129_101.54))] data-[selected=true]:text-[color:var(--zui-select-item-yellow-fg,oklch(42.1%_0.095_57.708))] dark:data-[selected=true]:text-[color:var(--zui-select-item-yellow-fg-dark,oklch(42.1%_0.095_57.708))]",
  teal: "border-[color:var(--zui-select-item-teal-border,oklch(38.6%_0.063_188.416))] dark:border-[color:var(--zui-select-item-teal-border-dark,oklch(60%_0.118_184.704))] text-[color:var(--zui-select-item-teal-fg,oklch(38.6%_0.063_188.416))] dark:text-[color:var(--zui-select-item-teal-fg-dark,oklch(91%_0.096_180.426))] data-[selected=true]:border-[color:var(--zui-select-item-teal-border,oklch(38.6%_0.063_188.416))] dark:data-[selected=true]:border-[color:var(--zui-select-item-teal-border-dark,oklch(60%_0.118_184.704))] data-[selected=true]:bg-[var(--zui-select-item-teal-bg,oklch(91%_0.096_180.426))] dark:data-[selected=true]:bg-[var(--zui-select-item-teal-bg-dark,oklch(91%_0.096_180.426))] data-[selected=true]:text-[color:var(--zui-select-item-teal-fg,oklch(38.6%_0.063_188.416))] dark:data-[selected=true]:text-[color:var(--zui-select-item-teal-fg-dark,oklch(38.6%_0.063_188.416))]",
  indigo:
    "border-[color:var(--zui-select-item-indigo-border,oklch(35.9%_0.144_278.697))] dark:border-[color:var(--zui-select-item-indigo-border-dark,oklch(51.1%_0.262_276.966))] text-[color:var(--zui-select-item-indigo-fg,oklch(35.9%_0.144_278.697))] dark:text-[color:var(--zui-select-item-indigo-fg-dark,oklch(87%_0.065_274.039))] data-[selected=true]:border-[color:var(--zui-select-item-indigo-border,oklch(35.9%_0.144_278.697))] dark:data-[selected=true]:border-[color:var(--zui-select-item-indigo-border-dark,oklch(51.1%_0.262_276.966))] data-[selected=true]:bg-[var(--zui-select-item-indigo-bg,oklch(87%_0.065_274.039))] dark:data-[selected=true]:bg-[var(--zui-select-item-indigo-bg-dark,oklch(87%_0.065_274.039))] data-[selected=true]:text-[color:var(--zui-select-item-indigo-fg,oklch(35.9%_0.144_278.697))] dark:data-[selected=true]:text-[color:var(--zui-select-item-indigo-fg-dark,oklch(35.9%_0.144_278.697))]",
  emerald:
    "border-[color:var(--zui-select-item-emerald-border,oklch(37.8%_0.077_168.94))] dark:border-[color:var(--zui-select-item-emerald-border-dark,oklch(59.6%_0.145_163.225))] text-[color:var(--zui-select-item-emerald-fg,oklch(37.8%_0.077_168.94))] dark:text-[color:var(--zui-select-item-emerald-fg-dark,oklch(90.5%_0.093_164.15))] data-[selected=true]:border-[color:var(--zui-select-item-emerald-border,oklch(37.8%_0.077_168.94))] dark:data-[selected=true]:border-[color:var(--zui-select-item-emerald-border-dark,oklch(59.6%_0.145_163.225))] data-[selected=true]:bg-[var(--zui-select-item-emerald-bg,oklch(90.5%_0.093_164.15))] dark:data-[selected=true]:bg-[var(--zui-select-item-emerald-bg-dark,oklch(90.5%_0.093_164.15))] data-[selected=true]:text-[color:var(--zui-select-item-emerald-fg,oklch(37.8%_0.077_168.94))] dark:data-[selected=true]:text-[color:var(--zui-select-item-emerald-fg-dark,oklch(37.8%_0.077_168.94))]",
  "gradient-blue":
    "bg-[var(--zui-select-item-gradient-blue-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-blue-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-blue-fg,oklch(97%_0.014_254.604))] dark:text-[color:var(--zui-select-item-gradient-blue-fg-dark,oklch(97%_0.014_254.604))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-blue-from,oklch(97%_0.014_254.604))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-blue-from-dark,oklch(97%_0.014_254.604))] data-[selected=true]:to-[var(--zui-select-item-gradient-blue-to,oklch(97.7%_0.014_308.299))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-blue-to-dark,oklch(97.7%_0.014_308.299))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-blue-fg,oklch(37.9%_0.146_265.522))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-blue-fg-dark,oklch(37.9%_0.146_265.522))]",
  "gradient-green":
    "bg-[var(--zui-select-item-gradient-green-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-green-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-green-fg,oklch(98.2%_0.018_155.826))] dark:text-[color:var(--zui-select-item-gradient-green-fg-dark,oklch(98.2%_0.018_155.826))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-green-from,oklch(98.2%_0.018_155.826))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-green-from-dark,oklch(98.2%_0.018_155.826))] data-[selected=true]:to-[var(--zui-select-item-gradient-green-to,oklch(98.6%_0.031_120.757))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-green-to-dark,oklch(98.6%_0.031_120.757))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-green-fg,oklch(39.3%_0.095_152.535))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-green-fg-dark,oklch(39.3%_0.095_152.535))]",
  "gradient-red":
    "bg-[var(--zui-select-item-gradient-red-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-red-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-red-fg,oklch(97.1%_0.013_17.38))] dark:text-[color:var(--zui-select-item-gradient-red-fg-dark,oklch(97.1%_0.013_17.38))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-red-from,oklch(97.1%_0.013_17.38))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-red-from-dark,oklch(97.1%_0.013_17.38))] data-[selected=true]:to-[var(--zui-select-item-gradient-red-to,oklch(97.1%_0.014_343.198))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-red-to-dark,oklch(97.1%_0.014_343.198))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-red-fg,oklch(39.6%_0.141_25.723))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-red-fg-dark,oklch(39.6%_0.141_25.723))]",
  "gradient-yellow":
    "bg-[var(--zui-select-item-gradient-yellow-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-yellow-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-yellow-fg,oklch(98.7%_0.026_102.212))] dark:text-[color:var(--zui-select-item-gradient-yellow-fg-dark,oklch(98.7%_0.026_102.212))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-yellow-from,oklch(98.7%_0.026_102.212))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-yellow-from-dark,oklch(98.7%_0.026_102.212))] data-[selected=true]:to-[var(--zui-select-item-gradient-yellow-to,oklch(98%_0.016_73.684))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-yellow-to-dark,oklch(98%_0.016_73.684))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-yellow-fg,oklch(42.1%_0.095_57.708))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-yellow-fg-dark,oklch(42.1%_0.095_57.708))]",
  "gradient-purple":
    "bg-[var(--zui-select-item-gradient-purple-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-purple-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-purple-fg,oklch(97.7%_0.014_308.299))] dark:text-[color:var(--zui-select-item-gradient-purple-fg-dark,oklch(97.7%_0.014_308.299))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-purple-from,oklch(97.7%_0.014_308.299))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-purple-from-dark,oklch(97.7%_0.014_308.299))] data-[selected=true]:to-[var(--zui-select-item-gradient-purple-to,oklch(97.1%_0.014_343.198))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-purple-to-dark,oklch(97.1%_0.014_343.198))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-purple-fg,oklch(38.1%_0.176_304.987))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-purple-fg-dark,oklch(38.1%_0.176_304.987))]",
  "gradient-teal":
    "bg-[var(--zui-select-item-gradient-teal-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-teal-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-teal-fg,oklch(98.4%_0.014_180.72))] dark:text-[color:var(--zui-select-item-gradient-teal-fg-dark,oklch(98.4%_0.014_180.72))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-teal-from,oklch(98.4%_0.014_180.72))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-teal-from-dark,oklch(98.4%_0.014_180.72))] data-[selected=true]:to-[var(--zui-select-item-gradient-teal-to,oklch(98.4%_0.019_200.873))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-teal-to-dark,oklch(98.4%_0.019_200.873))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-teal-fg,oklch(38.6%_0.063_188.416))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-teal-fg-dark,oklch(38.6%_0.063_188.416))]",
  "gradient-indigo":
    "bg-[var(--zui-select-item-gradient-indigo-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-indigo-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-indigo-fg,oklch(96.2%_0.018_272.314))] dark:text-[color:var(--zui-select-item-gradient-indigo-fg-dark,oklch(96.2%_0.018_272.314))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-indigo-from,oklch(96.2%_0.018_272.314))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-indigo-from-dark,oklch(96.2%_0.018_272.314))] data-[selected=true]:to-[var(--zui-select-item-gradient-indigo-to,oklch(97.7%_0.014_308.299))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-indigo-to-dark,oklch(97.7%_0.014_308.299))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-indigo-fg,oklch(35.9%_0.144_278.697))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-indigo-fg-dark,oklch(35.9%_0.144_278.697))]",
  "gradient-pink":
    "bg-[var(--zui-select-item-gradient-pink-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-pink-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-pink-fg,oklch(97.1%_0.014_343.198))] dark:text-[color:var(--zui-select-item-gradient-pink-fg-dark,oklch(97.1%_0.014_343.198))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-pink-from,oklch(97.1%_0.014_343.198))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-pink-from-dark,oklch(97.1%_0.014_343.198))] data-[selected=true]:to-[var(--zui-select-item-gradient-pink-to,oklch(96.9%_0.015_12.422))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-pink-to-dark,oklch(96.9%_0.015_12.422))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-pink-fg,oklch(40.8%_0.153_2.432))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-pink-fg-dark,oklch(40.8%_0.153_2.432))]",
  "gradient-orange":
    "bg-[var(--zui-select-item-gradient-orange-bg,transparent)] dark:bg-[var(--zui-select-item-gradient-orange-bg-dark,transparent)] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-orange-fg,oklch(98%_0.016_73.684))] dark:text-[color:var(--zui-select-item-gradient-orange-fg-dark,oklch(98%_0.016_73.684))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-orange-from,oklch(98%_0.016_73.684))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-orange-from-dark,oklch(98%_0.016_73.684))] data-[selected=true]:to-[var(--zui-select-item-gradient-orange-to,oklch(97.1%_0.013_17.38))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-orange-to-dark,oklch(97.1%_0.013_17.38))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-orange-fg,oklch(40.8%_0.123_38.172))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-orange-fg-dark,oklch(40.8%_0.123_38.172))]",
  blue: "hover:bg-[var(--zui-select-item-blue-bg-hover,#2563eb18)] dark:hover:bg-[var(--zui-select-item-blue-bg-hover-dark,#3b82f62e)] hover:text-[color:var(--zui-select-item-blue-fg-hover,#2563eb)] dark:hover:text-[color:var(--zui-select-item-blue-fg-hover-dark,#3b82f6)] bg-[var(--zui-select-item-blue-bg,#2563eb10)] dark:bg-[var(--zui-select-item-blue-bg-dark,#3b82f61f)] text-[color:var(--zui-select-item-blue-fg,#2563eb)] dark:text-[color:var(--zui-select-item-blue-fg-dark,#3b82f6)]",
  cyan: "hover:bg-[var(--zui-select-item-cyan-bg-hover,#0891b218)] dark:hover:bg-[var(--zui-select-item-cyan-bg-hover-dark,#22d3ee2e)] hover:text-[color:var(--zui-select-item-cyan-fg-hover,#0891b2)] dark:hover:text-[color:var(--zui-select-item-cyan-fg-hover-dark,#22d3ee)] bg-[var(--zui-select-item-cyan-bg,#0891b210)] dark:bg-[var(--zui-select-item-cyan-bg-dark,#22d3ee1f)] text-[color:var(--zui-select-item-cyan-fg,#0891b2)] dark:text-[color:var(--zui-select-item-cyan-fg-dark,#22d3ee)]",
  green:
    "hover:bg-[var(--zui-select-item-green-bg-hover,#16a34a18)] dark:hover:bg-[var(--zui-select-item-green-bg-hover-dark,#22c55e2e)] hover:text-[color:var(--zui-select-item-green-fg-hover,#16a34a)] dark:hover:text-[color:var(--zui-select-item-green-fg-hover-dark,#22c55e)] bg-[var(--zui-select-item-green-bg,#16a34a10)] dark:bg-[var(--zui-select-item-green-bg-dark,#22c55e1f)] text-[color:var(--zui-select-item-green-fg,#16a34a)] dark:text-[color:var(--zui-select-item-green-fg-dark,#22c55e)]",
  lime: "hover:bg-[var(--zui-select-item-lime-bg-hover,#65a30d18)] dark:hover:bg-[var(--zui-select-item-lime-bg-hover-dark,#a3e6352e)] hover:text-[color:var(--zui-select-item-lime-fg-hover,#65a30d)] dark:hover:text-[color:var(--zui-select-item-lime-fg-hover-dark,#a3e635)] bg-[var(--zui-select-item-lime-bg,#65a30d10)] dark:bg-[var(--zui-select-item-lime-bg-dark,#a3e6351f)] text-[color:var(--zui-select-item-lime-fg,#65a30d)] dark:text-[color:var(--zui-select-item-lime-fg-dark,#a3e635)]",
  mint: "hover:bg-[var(--zui-select-item-mint-bg-hover,#10b98118)] dark:hover:bg-[var(--zui-select-item-mint-bg-hover-dark,#6ee7b72e)] hover:text-[color:var(--zui-select-item-mint-fg-hover,#10b981)] dark:hover:text-[color:var(--zui-select-item-mint-fg-hover-dark,#6ee7b7)] bg-[var(--zui-select-item-mint-bg,#10b98110)] dark:bg-[var(--zui-select-item-mint-bg-dark,#6ee7b71f)] text-[color:var(--zui-select-item-mint-fg,#10b981)] dark:text-[color:var(--zui-select-item-mint-fg-dark,#6ee7b7)]",
  ocean:
    "hover:bg-[var(--zui-select-item-ocean-bg-hover,#0284c718)] dark:hover:bg-[var(--zui-select-item-ocean-bg-hover-dark,#38bdf82e)] hover:text-[color:var(--zui-select-item-ocean-fg-hover,#0284c7)] dark:hover:text-[color:var(--zui-select-item-ocean-fg-hover-dark,#38bdf8)] bg-[var(--zui-select-item-ocean-bg,#0284c710)] dark:bg-[var(--zui-select-item-ocean-bg-dark,#38bdf81f)] text-[color:var(--zui-select-item-ocean-fg,#0284c7)] dark:text-[color:var(--zui-select-item-ocean-fg-dark,#38bdf8)]",
  sapphire:
    "hover:bg-[var(--zui-select-item-sapphire-bg-hover,#1d4ed818)] dark:hover:bg-[var(--zui-select-item-sapphire-bg-hover-dark,#60a5fa2e)] hover:text-[color:var(--zui-select-item-sapphire-fg-hover,#1d4ed8)] dark:hover:text-[color:var(--zui-select-item-sapphire-fg-hover-dark,#60a5fa)] bg-[var(--zui-select-item-sapphire-bg,#1d4ed810)] dark:bg-[var(--zui-select-item-sapphire-bg-dark,#60a5fa1f)] text-[color:var(--zui-select-item-sapphire-fg,#1d4ed8)] dark:text-[color:var(--zui-select-item-sapphire-fg-dark,#60a5fa)]",
  lavender:
    "hover:bg-[var(--zui-select-item-lavender-bg-hover,#8b5cf618)] dark:hover:bg-[var(--zui-select-item-lavender-bg-hover-dark,#a78bfa2e)] hover:text-[color:var(--zui-select-item-lavender-fg-hover,#8b5cf6)] dark:hover:text-[color:var(--zui-select-item-lavender-fg-hover-dark,#a78bfa)] bg-[var(--zui-select-item-lavender-bg,#8b5cf610)] dark:bg-[var(--zui-select-item-lavender-bg-dark,#a78bfa1f)] text-[color:var(--zui-select-item-lavender-fg,#8b5cf6)] dark:text-[color:var(--zui-select-item-lavender-fg-dark,#a78bfa)]",
  ruby: "hover:bg-[var(--zui-select-item-ruby-bg-hover,#be123c18)] dark:hover:bg-[var(--zui-select-item-ruby-bg-hover-dark,#fb71852e)] hover:text-[color:var(--zui-select-item-ruby-fg-hover,#be123c)] dark:hover:text-[color:var(--zui-select-item-ruby-fg-hover-dark,#fb7185)] bg-[var(--zui-select-item-ruby-bg,#be123c10)] dark:bg-[var(--zui-select-item-ruby-bg-dark,#fb71851f)] text-[color:var(--zui-select-item-ruby-fg,#be123c)] dark:text-[color:var(--zui-select-item-ruby-fg-dark,#fb7185)]",
  red: "hover:bg-[var(--zui-select-item-red-bg-hover,#dc262618)] dark:hover:bg-[var(--zui-select-item-red-bg-hover-dark,#ef44442e)] hover:text-[color:var(--zui-select-item-red-fg-hover,#dc2626)] dark:hover:text-[color:var(--zui-select-item-red-fg-hover-dark,#ef4444)] bg-[var(--zui-select-item-red-bg,#dc262610)] dark:bg-[var(--zui-select-item-red-bg-dark,#ef44441f)] text-[color:var(--zui-select-item-red-fg,#dc2626)] dark:text-[color:var(--zui-select-item-red-fg-dark,#ef4444)]",
  slate:
    "hover:bg-[var(--zui-select-item-slate-bg-hover,#47556918)] dark:hover:bg-[var(--zui-select-item-slate-bg-hover-dark,#64748b2e)] hover:text-[color:var(--zui-select-item-slate-fg-hover,#475569)] dark:hover:text-[color:var(--zui-select-item-slate-fg-hover-dark,#64748b)] bg-[var(--zui-select-item-slate-bg,#47556910)] dark:bg-[var(--zui-select-item-slate-bg-dark,#64748b1f)] text-[color:var(--zui-select-item-slate-fg,#475569)] dark:text-[color:var(--zui-select-item-slate-fg-dark,#64748b)]",
  zinc: "hover:bg-[var(--zui-select-item-zinc-bg-hover,#52525b18)] dark:hover:bg-[var(--zui-select-item-zinc-bg-hover-dark,#71717a2e)] hover:text-[color:var(--zui-select-item-zinc-fg-hover,#52525b)] dark:hover:text-[color:var(--zui-select-item-zinc-fg-hover-dark,#71717a)] bg-[var(--zui-select-item-zinc-bg,#52525b10)] dark:bg-[var(--zui-select-item-zinc-bg-dark,#71717a1f)] text-[color:var(--zui-select-item-zinc-fg,#52525b)] dark:text-[color:var(--zui-select-item-zinc-fg-dark,#71717a)]",
  stone:
    "hover:bg-[var(--zui-select-item-stone-bg-hover,#57534e18)] dark:hover:bg-[var(--zui-select-item-stone-bg-hover-dark,#78716c2e)] hover:text-[color:var(--zui-select-item-stone-fg-hover,#57534e)] dark:hover:text-[color:var(--zui-select-item-stone-fg-hover-dark,#78716c)] bg-[var(--zui-select-item-stone-bg,#57534e10)] dark:bg-[var(--zui-select-item-stone-bg-dark,#78716c1f)] text-[color:var(--zui-select-item-stone-fg,#57534e)] dark:text-[color:var(--zui-select-item-stone-fg-dark,#78716c)]",
  royal:
    "hover:bg-[var(--zui-select-item-royal-bg-hover,#4338ca18)] dark:hover:bg-[var(--zui-select-item-royal-bg-hover-dark,#818cf82e)] hover:text-[color:var(--zui-select-item-royal-fg-hover,#4338ca)] dark:hover:text-[color:var(--zui-select-item-royal-fg-hover-dark,#818cf8)] bg-[var(--zui-select-item-royal-bg,#4338ca10)] dark:bg-[var(--zui-select-item-royal-bg-dark,#818cf81f)] text-[color:var(--zui-select-item-royal-fg,#4338ca)] dark:text-[color:var(--zui-select-item-royal-fg-dark,#818cf8)]",
  electric:
    "hover:bg-[var(--zui-select-item-electric-bg-hover,#0ea5e918)] dark:hover:bg-[var(--zui-select-item-electric-bg-hover-dark,#38bdf82e)] hover:text-[color:var(--zui-select-item-electric-fg-hover,#0ea5e9)] dark:hover:text-[color:var(--zui-select-item-electric-fg-hover-dark,#38bdf8)] bg-[var(--zui-select-item-electric-bg,#0ea5e910)] dark:bg-[var(--zui-select-item-electric-bg-dark,#38bdf81f)] text-[color:var(--zui-select-item-electric-fg,#0ea5e9)] dark:text-[color:var(--zui-select-item-electric-fg-dark,#38bdf8)]",
  forest:
    "hover:bg-[var(--zui-select-item-forest-bg-hover,#16653418)] dark:hover:bg-[var(--zui-select-item-forest-bg-hover-dark,#4ade802e)] hover:text-[color:var(--zui-select-item-forest-fg-hover,#166534)] dark:hover:text-[color:var(--zui-select-item-forest-fg-hover-dark,#4ade80)] bg-[var(--zui-select-item-forest-bg,#16653410)] dark:bg-[var(--zui-select-item-forest-bg-dark,#4ade801f)] text-[color:var(--zui-select-item-forest-fg,#166534)] dark:text-[color:var(--zui-select-item-forest-fg-dark,#4ade80)]",
  sunset:
    "hover:bg-[var(--zui-select-item-sunset-bg-hover,#ea580c18)] dark:hover:bg-[var(--zui-select-item-sunset-bg-hover-dark,#fb923c2e)] hover:text-[color:var(--zui-select-item-sunset-fg-hover,#ea580c)] dark:hover:text-[color:var(--zui-select-item-sunset-fg-hover-dark,#fb923c)] bg-[var(--zui-select-item-sunset-bg,#ea580c10)] dark:bg-[var(--zui-select-item-sunset-bg-dark,#fb923c1f)] text-[color:var(--zui-select-item-sunset-fg,#ea580c)] dark:text-[color:var(--zui-select-item-sunset-fg-dark,#fb923c)]",
  magenta:
    "hover:bg-[var(--zui-select-item-magenta-bg-hover,#c026d318)] dark:hover:bg-[var(--zui-select-item-magenta-bg-hover-dark,#e879f92e)] hover:text-[color:var(--zui-select-item-magenta-fg-hover,#c026d3)] dark:hover:text-[color:var(--zui-select-item-magenta-fg-hover-dark,#e879f9)] bg-[var(--zui-select-item-magenta-bg,#c026d310)] dark:bg-[var(--zui-select-item-magenta-bg-dark,#e879f91f)] text-[color:var(--zui-select-item-magenta-fg,#c026d3)] dark:text-[color:var(--zui-select-item-magenta-fg-dark,#e879f9)]",
  crimson:
    "hover:bg-[var(--zui-select-item-crimson-bg-hover,#b91c1c18)] dark:hover:bg-[var(--zui-select-item-crimson-bg-hover-dark,#f871712e)] hover:text-[color:var(--zui-select-item-crimson-fg-hover,#b91c1c)] dark:hover:text-[color:var(--zui-select-item-crimson-fg-hover-dark,#f87171)] bg-[var(--zui-select-item-crimson-bg,#b91c1c10)] dark:bg-[var(--zui-select-item-crimson-bg-dark,#f871711f)] text-[color:var(--zui-select-item-crimson-fg,#b91c1c)] dark:text-[color:var(--zui-select-item-crimson-fg-dark,#f87171)]",
  aqua: "hover:bg-[var(--zui-select-item-aqua-bg-hover,#0f766e18)] dark:hover:bg-[var(--zui-select-item-aqua-bg-hover-dark,#2dd4bf2e)] hover:text-[color:var(--zui-select-item-aqua-fg-hover,#0f766e)] dark:hover:text-[color:var(--zui-select-item-aqua-fg-hover-dark,#2dd4bf)] bg-[var(--zui-select-item-aqua-bg,#0f766e10)] dark:bg-[var(--zui-select-item-aqua-bg-dark,#2dd4bf1f)] text-[color:var(--zui-select-item-aqua-fg,#0f766e)] dark:text-[color:var(--zui-select-item-aqua-fg-dark,#2dd4bf)]",
  plum: "hover:bg-[var(--zui-select-item-plum-bg-hover,#7e22ce18)] dark:hover:bg-[var(--zui-select-item-plum-bg-hover-dark,#c084fc2e)] hover:text-[color:var(--zui-select-item-plum-fg-hover,#7e22ce)] dark:hover:text-[color:var(--zui-select-item-plum-fg-hover-dark,#c084fc)] bg-[var(--zui-select-item-plum-bg,#7e22ce10)] dark:bg-[var(--zui-select-item-plum-bg-dark,#c084fc1f)] text-[color:var(--zui-select-item-plum-fg,#7e22ce)] dark:text-[color:var(--zui-select-item-plum-fg-dark,#c084fc)]",
} as const;

export const zuiSelectDisabled = {
  true: "opacity-50 cursor-not-allowed",
} as const;

export const zuiSelectContentBase =
  "absolute z-10 mt-2 w-full rounded-md border bg-[var(--zui-select-content-bg,#ffffff)] dark:bg-[var(--zui-select-content-bg-dark,#000000)] shadow-md";

export const zuiSelectContentAppearances = {
  default:
    "bg-[var(--zui-select-content-default-bg,#ffffff)] dark:bg-[var(--zui-select-content-default-bg-dark,#000000)] shadow-md",
  glass:
    "bg-[var(--zui-select-content-glass-bg,#0000001a)] dark:bg-[var(--zui-select-content-glass-bg-dark,#ffffff1a)] backdrop-blur-md",
  outline:
    "border-2 border-[color:var(--zui-select-content-outline-border,oklch(55.1%_0.027_264.364))] dark:border-[color:var(--zui-select-content-outline-border-dark,oklch(55.1%_0.027_264.364))]",
  ghost:
    "border-[color:var(--zui-select-content-ghost-border,transparent)] dark:border-[color:var(--zui-select-content-ghost-border-dark,transparent)]",
  sky: "border-[color:var(--zui-select-content-sky-border,oklch(39.1%_0.09_240.876))] dark:border-[color:var(--zui-select-content-sky-border-dark,oklch(58.8%_0.158_241.966))]",
  rose: "border-[color:var(--zui-select-content-rose-border,oklch(41%_0.159_10.272))] dark:border-[color:var(--zui-select-content-rose-border-dark,oklch(58.6%_0.253_17.585))]",
  purple:
    "border-[color:var(--zui-select-content-purple-border,oklch(38.1%_0.176_304.987))] dark:border-[color:var(--zui-select-content-purple-border-dark,oklch(55.8%_0.288_302.321))]",
  pink: "border-[color:var(--zui-select-content-pink-border,oklch(40.8%_0.153_2.432))] dark:border-[color:var(--zui-select-content-pink-border-dark,oklch(59.2%_0.249_0.584))]",
  orange:
    "border-[color:var(--zui-select-content-orange-border,oklch(40.8%_0.123_38.172))] dark:border-[color:var(--zui-select-content-orange-border-dark,oklch(64.6%_0.222_41.116))]",
  yellow:
    "border-[color:var(--zui-select-content-yellow-border,oklch(42.1%_0.095_57.708))] dark:border-[color:var(--zui-select-content-yellow-border-dark,oklch(68.1%_0.162_75.834))]",
  teal: "border-[color:var(--zui-select-content-teal-border,oklch(38.6%_0.063_188.416))] dark:border-[color:var(--zui-select-content-teal-border-dark,oklch(60%_0.118_184.704))]",
  indigo:
    "border-[color:var(--zui-select-content-indigo-border,oklch(35.9%_0.144_278.697))] dark:border-[color:var(--zui-select-content-indigo-border-dark,oklch(51.1%_0.262_276.966))]",
  emerald:
    "border-[color:var(--zui-select-content-emerald-border,oklch(37.8%_0.077_168.94))] dark:border-[color:var(--zui-select-content-emerald-border-dark,oklch(59.6%_0.145_163.225))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-blue-from,oklch(37.9%_0.146_265.522))] dark:from-[var(--zui-select-content-gradient-blue-from-dark,oklch(54.6%_0.245_262.881))] to-[var(--zui-select-content-gradient-blue-to,oklch(38.1%_0.176_304.987))] dark:to-[var(--zui-select-content-gradient-blue-to-dark,oklch(55.8%_0.288_302.321))] backdrop-blur-xl",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-green-from,oklch(39.3%_0.095_152.535))] dark:from-[var(--zui-select-content-gradient-green-from-dark,oklch(62.7%_0.194_149.214))] to-[var(--zui-select-content-gradient-green-to,oklch(40.5%_0.101_131.063))] dark:to-[var(--zui-select-content-gradient-green-to-dark,oklch(64.8%_0.2_131.684))] backdrop-blur-xl",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-red-from,oklch(39.6%_0.141_25.723))] dark:from-[var(--zui-select-content-gradient-red-from-dark,oklch(57.7%_0.245_27.325))] to-[var(--zui-select-content-gradient-red-to,oklch(40.8%_0.153_2.432))] dark:to-[var(--zui-select-content-gradient-red-to-dark,oklch(59.2%_0.249_0.584))] backdrop-blur-xl",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-yellow-from,oklch(42.1%_0.095_57.708))] dark:from-[var(--zui-select-content-gradient-yellow-from-dark,oklch(68.1%_0.162_75.834))] to-[var(--zui-select-content-gradient-yellow-to,oklch(40.8%_0.123_38.172))] dark:to-[var(--zui-select-content-gradient-yellow-to-dark,oklch(64.6%_0.222_41.116))] backdrop-blur-xl",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-purple-from,oklch(38.1%_0.176_304.987))] dark:from-[var(--zui-select-content-gradient-purple-from-dark,oklch(55.8%_0.288_302.321))] to-[var(--zui-select-content-gradient-purple-to,oklch(40.8%_0.153_2.432))] dark:to-[var(--zui-select-content-gradient-purple-to-dark,oklch(59.2%_0.249_0.584))] backdrop-blur-xl",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-teal-from,oklch(38.6%_0.063_188.416))] dark:from-[var(--zui-select-content-gradient-teal-from-dark,oklch(60%_0.118_184.704))] to-[var(--zui-select-content-gradient-teal-to,oklch(39.8%_0.07_227.392))] dark:to-[var(--zui-select-content-gradient-teal-to-dark,oklch(60.9%_0.126_221.723))] backdrop-blur-xl",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-indigo-from,oklch(35.9%_0.144_278.697))] dark:from-[var(--zui-select-content-gradient-indigo-from-dark,oklch(51.1%_0.262_276.966))] to-[var(--zui-select-content-gradient-indigo-to,oklch(38.1%_0.176_304.987))] dark:to-[var(--zui-select-content-gradient-indigo-to-dark,oklch(55.8%_0.288_302.321))] backdrop-blur-xl",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-pink-from,oklch(40.8%_0.153_2.432))] dark:from-[var(--zui-select-content-gradient-pink-from-dark,oklch(59.2%_0.249_0.584))] to-[var(--zui-select-content-gradient-pink-to,oklch(41%_0.159_10.272))] dark:to-[var(--zui-select-content-gradient-pink-to-dark,oklch(58.6%_0.253_17.585))] backdrop-blur-xl",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-orange-from,oklch(40.8%_0.123_38.172))] dark:from-[var(--zui-select-content-gradient-orange-from-dark,oklch(64.6%_0.222_41.116))] to-[var(--zui-select-content-gradient-orange-to,oklch(39.6%_0.141_25.723))] dark:to-[var(--zui-select-content-gradient-orange-to-dark,oklch(57.7%_0.245_27.325))] backdrop-blur-xl",
  blue: "border border-[color:var(--zui-select-content-blue-border,#2563eb)] dark:border-[color:var(--zui-select-content-blue-border-dark,#3b82f6)] bg-[var(--zui-select-content-blue-bg,#2563eb14)] dark:bg-[var(--zui-select-content-blue-bg-dark,#3b82f624)] text-[color:var(--zui-select-content-blue-fg,#0f172a)] dark:text-[color:var(--zui-select-content-blue-fg-dark,#f8fafc)] backdrop-blur-xl",
  cyan: "border border-[color:var(--zui-select-content-cyan-border,#0891b2)] dark:border-[color:var(--zui-select-content-cyan-border-dark,#22d3ee)] bg-[var(--zui-select-content-cyan-bg,#0891b214)] dark:bg-[var(--zui-select-content-cyan-bg-dark,#22d3ee24)] text-[color:var(--zui-select-content-cyan-fg,#0f172a)] dark:text-[color:var(--zui-select-content-cyan-fg-dark,#f8fafc)] backdrop-blur-xl",
  green:
    "border border-[color:var(--zui-select-content-green-border,#16a34a)] dark:border-[color:var(--zui-select-content-green-border-dark,#22c55e)] bg-[var(--zui-select-content-green-bg,#16a34a14)] dark:bg-[var(--zui-select-content-green-bg-dark,#22c55e24)] text-[color:var(--zui-select-content-green-fg,#0f172a)] dark:text-[color:var(--zui-select-content-green-fg-dark,#f8fafc)] backdrop-blur-xl",
  lime: "border border-[color:var(--zui-select-content-lime-border,#65a30d)] dark:border-[color:var(--zui-select-content-lime-border-dark,#a3e635)] bg-[var(--zui-select-content-lime-bg,#65a30d14)] dark:bg-[var(--zui-select-content-lime-bg-dark,#a3e63524)] text-[color:var(--zui-select-content-lime-fg,#0f172a)] dark:text-[color:var(--zui-select-content-lime-fg-dark,#f8fafc)] backdrop-blur-xl",
  mint: "border border-[color:var(--zui-select-content-mint-border,#10b981)] dark:border-[color:var(--zui-select-content-mint-border-dark,#6ee7b7)] bg-[var(--zui-select-content-mint-bg,#10b98114)] dark:bg-[var(--zui-select-content-mint-bg-dark,#6ee7b724)] text-[color:var(--zui-select-content-mint-fg,#0f172a)] dark:text-[color:var(--zui-select-content-mint-fg-dark,#f8fafc)] backdrop-blur-xl",
  ocean:
    "border border-[color:var(--zui-select-content-ocean-border,#0284c7)] dark:border-[color:var(--zui-select-content-ocean-border-dark,#38bdf8)] bg-[var(--zui-select-content-ocean-bg,#0284c714)] dark:bg-[var(--zui-select-content-ocean-bg-dark,#38bdf824)] text-[color:var(--zui-select-content-ocean-fg,#0f172a)] dark:text-[color:var(--zui-select-content-ocean-fg-dark,#f8fafc)] backdrop-blur-xl",
  sapphire:
    "border border-[color:var(--zui-select-content-sapphire-border,#1d4ed8)] dark:border-[color:var(--zui-select-content-sapphire-border-dark,#60a5fa)] bg-[var(--zui-select-content-sapphire-bg,#1d4ed814)] dark:bg-[var(--zui-select-content-sapphire-bg-dark,#60a5fa24)] text-[color:var(--zui-select-content-sapphire-fg,#0f172a)] dark:text-[color:var(--zui-select-content-sapphire-fg-dark,#f8fafc)] backdrop-blur-xl",
  lavender:
    "border border-[color:var(--zui-select-content-lavender-border,#8b5cf6)] dark:border-[color:var(--zui-select-content-lavender-border-dark,#a78bfa)] bg-[var(--zui-select-content-lavender-bg,#8b5cf614)] dark:bg-[var(--zui-select-content-lavender-bg-dark,#a78bfa24)] text-[color:var(--zui-select-content-lavender-fg,#0f172a)] dark:text-[color:var(--zui-select-content-lavender-fg-dark,#f8fafc)] backdrop-blur-xl",
  ruby: "border border-[color:var(--zui-select-content-ruby-border,#be123c)] dark:border-[color:var(--zui-select-content-ruby-border-dark,#fb7185)] bg-[var(--zui-select-content-ruby-bg,#be123c14)] dark:bg-[var(--zui-select-content-ruby-bg-dark,#fb718524)] text-[color:var(--zui-select-content-ruby-fg,#0f172a)] dark:text-[color:var(--zui-select-content-ruby-fg-dark,#f8fafc)] backdrop-blur-xl",
  red: "border border-[color:var(--zui-select-content-red-border,#dc2626)] dark:border-[color:var(--zui-select-content-red-border-dark,#ef4444)] bg-[var(--zui-select-content-red-bg,#dc262614)] dark:bg-[var(--zui-select-content-red-bg-dark,#ef444424)] text-[color:var(--zui-select-content-red-fg,#0f172a)] dark:text-[color:var(--zui-select-content-red-fg-dark,#f8fafc)] backdrop-blur-xl",
  slate:
    "border border-[color:var(--zui-select-content-slate-border,#475569)] dark:border-[color:var(--zui-select-content-slate-border-dark,#64748b)] bg-[var(--zui-select-content-slate-bg,#47556914)] dark:bg-[var(--zui-select-content-slate-bg-dark,#64748b24)] text-[color:var(--zui-select-content-slate-fg,#0f172a)] dark:text-[color:var(--zui-select-content-slate-fg-dark,#f8fafc)] backdrop-blur-xl",
  zinc: "border border-[color:var(--zui-select-content-zinc-border,#52525b)] dark:border-[color:var(--zui-select-content-zinc-border-dark,#71717a)] bg-[var(--zui-select-content-zinc-bg,#52525b14)] dark:bg-[var(--zui-select-content-zinc-bg-dark,#71717a24)] text-[color:var(--zui-select-content-zinc-fg,#0f172a)] dark:text-[color:var(--zui-select-content-zinc-fg-dark,#f8fafc)] backdrop-blur-xl",
  stone:
    "border border-[color:var(--zui-select-content-stone-border,#57534e)] dark:border-[color:var(--zui-select-content-stone-border-dark,#78716c)] bg-[var(--zui-select-content-stone-bg,#57534e14)] dark:bg-[var(--zui-select-content-stone-bg-dark,#78716c24)] text-[color:var(--zui-select-content-stone-fg,#0f172a)] dark:text-[color:var(--zui-select-content-stone-fg-dark,#f8fafc)] backdrop-blur-xl",
  royal:
    "border border-[color:var(--zui-select-content-royal-border,#4338ca)] dark:border-[color:var(--zui-select-content-royal-border-dark,#818cf8)] bg-[var(--zui-select-content-royal-bg,#4338ca14)] dark:bg-[var(--zui-select-content-royal-bg-dark,#818cf824)] text-[color:var(--zui-select-content-royal-fg,#0f172a)] dark:text-[color:var(--zui-select-content-royal-fg-dark,#f8fafc)] backdrop-blur-xl",
  electric:
    "border border-[color:var(--zui-select-content-electric-border,#0ea5e9)] dark:border-[color:var(--zui-select-content-electric-border-dark,#38bdf8)] bg-[var(--zui-select-content-electric-bg,#0ea5e914)] dark:bg-[var(--zui-select-content-electric-bg-dark,#38bdf824)] text-[color:var(--zui-select-content-electric-fg,#0f172a)] dark:text-[color:var(--zui-select-content-electric-fg-dark,#f8fafc)] backdrop-blur-xl",
  forest:
    "border border-[color:var(--zui-select-content-forest-border,#166534)] dark:border-[color:var(--zui-select-content-forest-border-dark,#4ade80)] bg-[var(--zui-select-content-forest-bg,#16653414)] dark:bg-[var(--zui-select-content-forest-bg-dark,#4ade8024)] text-[color:var(--zui-select-content-forest-fg,#0f172a)] dark:text-[color:var(--zui-select-content-forest-fg-dark,#f8fafc)] backdrop-blur-xl",
  sunset:
    "border border-[color:var(--zui-select-content-sunset-border,#ea580c)] dark:border-[color:var(--zui-select-content-sunset-border-dark,#fb923c)] bg-[var(--zui-select-content-sunset-bg,#ea580c14)] dark:bg-[var(--zui-select-content-sunset-bg-dark,#fb923c24)] text-[color:var(--zui-select-content-sunset-fg,#0f172a)] dark:text-[color:var(--zui-select-content-sunset-fg-dark,#f8fafc)] backdrop-blur-xl",
  magenta:
    "border border-[color:var(--zui-select-content-magenta-border,#c026d3)] dark:border-[color:var(--zui-select-content-magenta-border-dark,#e879f9)] bg-[var(--zui-select-content-magenta-bg,#c026d314)] dark:bg-[var(--zui-select-content-magenta-bg-dark,#e879f924)] text-[color:var(--zui-select-content-magenta-fg,#0f172a)] dark:text-[color:var(--zui-select-content-magenta-fg-dark,#f8fafc)] backdrop-blur-xl",
  crimson:
    "border border-[color:var(--zui-select-content-crimson-border,#b91c1c)] dark:border-[color:var(--zui-select-content-crimson-border-dark,#f87171)] bg-[var(--zui-select-content-crimson-bg,#b91c1c14)] dark:bg-[var(--zui-select-content-crimson-bg-dark,#f8717124)] text-[color:var(--zui-select-content-crimson-fg,#0f172a)] dark:text-[color:var(--zui-select-content-crimson-fg-dark,#f8fafc)] backdrop-blur-xl",
  aqua: "border border-[color:var(--zui-select-content-aqua-border,#0f766e)] dark:border-[color:var(--zui-select-content-aqua-border-dark,#2dd4bf)] bg-[var(--zui-select-content-aqua-bg,#0f766e14)] dark:bg-[var(--zui-select-content-aqua-bg-dark,#2dd4bf24)] text-[color:var(--zui-select-content-aqua-fg,#0f172a)] dark:text-[color:var(--zui-select-content-aqua-fg-dark,#f8fafc)] backdrop-blur-xl",
  plum: "border border-[color:var(--zui-select-content-plum-border,#7e22ce)] dark:border-[color:var(--zui-select-content-plum-border-dark,#c084fc)] bg-[var(--zui-select-content-plum-bg,#7e22ce14)] dark:bg-[var(--zui-select-content-plum-bg-dark,#c084fc24)] text-[color:var(--zui-select-content-plum-fg,#0f172a)] dark:text-[color:var(--zui-select-content-plum-fg-dark,#f8fafc)] backdrop-blur-xl",
} as const;

export const zuiSelectSpacing = {
  none: "space-y-0",
  default: "space-y-1",
  sm: "space-y-2",
  md: "space-y-3",
  lg: "space-y-4",
  xl: "space-y-5",
} as const;
