export const zuiSelectTriggerBase =
  "flex items-center cursor-pointer justify-between rounded-md border transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-select-trigger-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[var(--zui-select-trigger-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))] focus-visible:ring-offset-2";

export const zuiSelectTriggerVariants = {
  default:
    "border-[color:var(--zui-select-trigger-default-border,var(--zui-border,oklch(87.2%_0.01_258.338)))] dark:border-[color:var(--zui-select-trigger-default-border-dark,var(--zui-border-dark,oklch(87.2%_0.01_258.338)))] bg-[var(--zui-select-trigger-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-select-trigger-default-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-select-trigger-default-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-select-trigger-default-fg-dark,var(--zui-fg-dark,#ffffff))]",
  outline:
    "border-2 border-[color:var(--zui-select-trigger-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-select-trigger-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] text-[color:var(--zui-select-trigger-outline-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-select-trigger-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  ghost:
    "border-[color:var(--zui-select-trigger-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-select-trigger-ghost-border-dark,var(--zui-border-dark,transparent))] text-[color:var(--zui-select-trigger-ghost-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-select-trigger-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  sky: "border-[color:var(--zui-select-trigger-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-select-trigger-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] text-[color:var(--zui-select-trigger-sky-fg,var(--zui-color-sky,oklch(29.3%_0.066_243.157)))] dark:text-[color:var(--zui-select-trigger-sky-fg-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))]",
  rose: "border-[color:var(--zui-select-trigger-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-select-trigger-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] text-[color:var(--zui-select-trigger-rose-fg,var(--zui-color-rose,oklch(27.1%_0.105_12.094)))] dark:text-[color:var(--zui-select-trigger-rose-fg-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))]",
  purple:
    "border-[color:var(--zui-select-trigger-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-select-trigger-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-select-trigger-purple-fg,var(--zui-color-purple,oklch(29.1%_0.149_302.717)))] dark:text-[color:var(--zui-select-trigger-purple-fg-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  pink: "border-[color:var(--zui-select-trigger-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-select-trigger-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-select-trigger-pink-fg,var(--zui-color-pink,oklch(28.4%_0.109_3.907)))] dark:text-[color:var(--zui-select-trigger-pink-fg-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  orange:
    "border-[color:var(--zui-select-trigger-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-select-trigger-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] text-[color:var(--zui-select-trigger-orange-fg,var(--zui-color-orange,oklch(26.6%_0.079_36.259)))] dark:text-[color:var(--zui-select-trigger-orange-fg-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))]",
  yellow:
    "border-[color:var(--zui-select-trigger-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-select-trigger-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] text-[color:var(--zui-select-trigger-yellow-fg,var(--zui-color-yellow,oklch(28.6%_0.066_53.813)))] dark:text-[color:var(--zui-select-trigger-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))]",
  teal: "border-[color:var(--zui-select-trigger-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-select-trigger-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] text-[color:var(--zui-select-trigger-teal-fg,var(--zui-color-teal,oklch(27.7%_0.046_192.524)))] dark:text-[color:var(--zui-select-trigger-teal-fg-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))]",
  indigo:
    "border-[color:var(--zui-select-trigger-indigo-border,var(--zui-color-indigo,oklch(58.5%_0.233_277.117)))] dark:border-[color:var(--zui-select-trigger-indigo-border-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)))] text-[color:var(--zui-select-trigger-indigo-fg,var(--zui-color-indigo,oklch(25.7%_0.09_281.288)))] dark:text-[color:var(--zui-select-trigger-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)))]",
  emerald:
    "border-[color:var(--zui-select-trigger-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-select-trigger-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] text-[color:var(--zui-select-trigger-emerald-fg,var(--zui-color-emerald,oklch(26.2%_0.051_172.552)))] dark:text-[color:var(--zui-select-trigger-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))]",
  glass:
    "border-[color:var(--zui-select-trigger-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-select-trigger-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-select-trigger-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-select-trigger-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-select-trigger-glass-fg,var(--zui-fg,oklch(13%_0.028_261.692)))] dark:text-[color:var(--zui-select-trigger-glass-fg-dark,var(--zui-fg-dark,#ffffff))] backdrop-blur-md",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-blue-from,var(--zui-color-blue,oklch(37.9%_0.146_265.522)))] dark:from-[var(--zui-select-trigger-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-select-trigger-gradient-blue-to,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:to-[var(--zui-select-trigger-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-green-from,var(--zui-color-green,oklch(39.3%_0.095_152.535)))] dark:from-[var(--zui-select-trigger-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-select-trigger-gradient-green-to,var(--zui-color-lime,oklch(40.5%_0.101_131.063)))] dark:to-[var(--zui-select-trigger-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-red-from,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:from-[var(--zui-select-trigger-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-select-trigger-gradient-red-to,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:to-[var(--zui-select-trigger-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-yellow-from,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:from-[var(--zui-select-trigger-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-select-trigger-gradient-yellow-to,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:to-[var(--zui-select-trigger-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-purple-from,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:from-[var(--zui-select-trigger-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-select-trigger-gradient-purple-to,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:to-[var(--zui-select-trigger-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-teal-from,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:from-[var(--zui-select-trigger-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-select-trigger-gradient-teal-to,var(--zui-color-cyan,oklch(39.8%_0.07_227.392)))] dark:to-[var(--zui-select-trigger-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-indigo-from,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:from-[var(--zui-select-trigger-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-select-trigger-gradient-indigo-to,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:to-[var(--zui-select-trigger-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-pink-from,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:from-[var(--zui-select-trigger-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-select-trigger-gradient-pink-to,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:to-[var(--zui-select-trigger-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-select-trigger-gradient-orange-from,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:from-[var(--zui-select-trigger-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-select-trigger-gradient-orange-to,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:to-[var(--zui-select-trigger-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] backdrop-blur-xl text-[color:var(--zui-select-trigger-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-select-trigger-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  blue: "border border-[color:var(--zui-select-trigger-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-select-trigger-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] text-[color:var(--zui-select-trigger-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-select-trigger-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] hover:bg-[var(--zui-select-trigger-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 14%, transparent))]",
  cyan: "border border-[color:var(--zui-select-trigger-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-select-trigger-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] text-[color:var(--zui-select-trigger-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-select-trigger-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] hover:bg-[var(--zui-select-trigger-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 14%, transparent))]",
  green:
    "border border-[color:var(--zui-select-trigger-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-select-trigger-green-border-dark,var(--zui-color-green-dark,#22c55e))] text-[color:var(--zui-select-trigger-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-select-trigger-green-fg-dark,var(--zui-color-green-dark,#22c55e))] hover:bg-[var(--zui-select-trigger-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 14%, transparent))]",
  lime: "border border-[color:var(--zui-select-trigger-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-select-trigger-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] text-[color:var(--zui-select-trigger-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-select-trigger-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] hover:bg-[var(--zui-select-trigger-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 14%, transparent))]",
  mint: "border border-[color:var(--zui-select-trigger-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-select-trigger-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] text-[color:var(--zui-select-trigger-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-select-trigger-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] hover:bg-[var(--zui-select-trigger-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98114) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 14%, transparent))]",
  ocean:
    "border border-[color:var(--zui-select-trigger-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-select-trigger-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] text-[color:var(--zui-select-trigger-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-select-trigger-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] hover:bg-[var(--zui-select-trigger-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 14%, transparent))]",
  sapphire:
    "border border-[color:var(--zui-select-trigger-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-select-trigger-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] text-[color:var(--zui-select-trigger-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-select-trigger-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] hover:bg-[var(--zui-select-trigger-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 14%, transparent))]",
  lavender:
    "border border-[color:var(--zui-select-trigger-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-select-trigger-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] text-[color:var(--zui-select-trigger-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-select-trigger-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] hover:bg-[var(--zui-select-trigger-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 14%, transparent))]",
  ruby: "border border-[color:var(--zui-select-trigger-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-select-trigger-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] text-[color:var(--zui-select-trigger-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-select-trigger-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] hover:bg-[var(--zui-select-trigger-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 14%, transparent))]",
  red: "border border-[color:var(--zui-select-trigger-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-select-trigger-red-border-dark,var(--zui-color-red-dark,#ef4444))] text-[color:var(--zui-select-trigger-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-select-trigger-red-fg-dark,var(--zui-color-red-dark,#ef4444))] hover:bg-[var(--zui-select-trigger-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262614) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 14%, transparent))]",
  slate:
    "border border-[color:var(--zui-select-trigger-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-select-trigger-slate-border-dark,var(--zui-color-slate-dark,#64748b))] text-[color:var(--zui-select-trigger-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-select-trigger-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] hover:bg-[var(--zui-select-trigger-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556914) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 14%, transparent))]",
  zinc: "border border-[color:var(--zui-select-trigger-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-select-trigger-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] text-[color:var(--zui-select-trigger-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-select-trigger-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] hover:bg-[var(--zui-select-trigger-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 14%, transparent))]",
  stone:
    "border border-[color:var(--zui-select-trigger-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-select-trigger-stone-border-dark,var(--zui-color-stone-dark,#78716c))] text-[color:var(--zui-select-trigger-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-select-trigger-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] hover:bg-[var(--zui-select-trigger-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 14%, transparent))]",
  royal:
    "border border-[color:var(--zui-select-trigger-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-select-trigger-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] text-[color:var(--zui-select-trigger-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-select-trigger-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] hover:bg-[var(--zui-select-trigger-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 14%, transparent))]",
  electric:
    "border border-[color:var(--zui-select-trigger-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-select-trigger-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] text-[color:var(--zui-select-trigger-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-select-trigger-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] hover:bg-[var(--zui-select-trigger-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 14%, transparent))]",
  forest:
    "border border-[color:var(--zui-select-trigger-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-select-trigger-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] text-[color:var(--zui-select-trigger-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-select-trigger-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] hover:bg-[var(--zui-select-trigger-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653414) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 14%, transparent))]",
  sunset:
    "border border-[color:var(--zui-select-trigger-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-select-trigger-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] text-[color:var(--zui-select-trigger-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-select-trigger-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] hover:bg-[var(--zui-select-trigger-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 14%, transparent))]",
  magenta:
    "border border-[color:var(--zui-select-trigger-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-select-trigger-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] text-[color:var(--zui-select-trigger-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-select-trigger-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] hover:bg-[var(--zui-select-trigger-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 14%, transparent))]",
  crimson:
    "border border-[color:var(--zui-select-trigger-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-select-trigger-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] text-[color:var(--zui-select-trigger-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-select-trigger-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] hover:bg-[var(--zui-select-trigger-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 14%, transparent))]",
  aqua: "border border-[color:var(--zui-select-trigger-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-select-trigger-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] text-[color:var(--zui-select-trigger-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-select-trigger-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] hover:bg-[var(--zui-select-trigger-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 14%, transparent))]",
  plum: "border border-[color:var(--zui-select-trigger-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-select-trigger-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] text-[color:var(--zui-select-trigger-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-select-trigger-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] hover:bg-[var(--zui-select-trigger-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 8%, transparent))] dark:hover:bg-[var(--zui-select-trigger-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 14%, transparent))]",
} as const;

export const zuiSelectSizes = {
  sm: "px-2 py-1 text-sm",
  md: "px-3 py-2",
  lg: "px-4 py-3 text-lg",
} as const;

export const zuiSelectItemBase =
  "cursor-pointer px-3 py-2 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-select-item-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.03_256.802)))] dark:focus-visible:ring-[var(--zui-select-item-ring-focus-dark,var(--zui-focus-ring-dark,oklch(70.7%_0.022_261.325)))] focus-visible:ring-inset";

export const zuiSelectItemAppearances = {
  default:
    "bg-[var(--zui-select-item-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-select-item-default-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-select-item-default-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-select-item-default-fg-dark,var(--zui-fg-dark,oklch(92.8%_0.006_264.531)))] data-[selected=true]:bg-[var(--zui-select-item-default-bg,var(--zui-surface-muted,oklch(92.8%_0.006_264.531)))] dark:data-[selected=true]:bg-[var(--zui-select-item-default-bg-dark,var(--zui-surface-muted-dark,oklch(92.8%_0.006_264.531)))] data-[selected=true]:text-[color:var(--zui-select-item-default-fg,var(--zui-fg,oklch(37.3%_0.034_259.733)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-default-fg-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))]",
  glass:
    "bg-[var(--zui-select-item-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-select-item-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-select-item-glass-fg,var(--zui-fg,oklch(37.3%_0.034_259.733)))] dark:text-[color:var(--zui-select-item-glass-fg-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))] data-[selected=true]:bg-[var(--zui-select-item-glass-bg,var(--zui-surface-soft,#0000001a))] dark:data-[selected=true]:bg-[var(--zui-select-item-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] data-[selected=true]:text-[color:var(--zui-select-item-glass-fg,var(--zui-fg,oklch(37.3%_0.034_259.733)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-glass-fg-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))]",
  outline:
    "border-2 border-[color:var(--zui-select-item-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-select-item-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] text-[color:var(--zui-select-item-outline-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-select-item-outline-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))] data-[selected=true]:border-2 data-[selected=true]:border-[color:var(--zui-select-item-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))] data-[selected=true]:bg-[var(--zui-select-item-outline-bg,var(--zui-surface-muted,oklch(92.8%_0.006_264.531)))] dark:data-[selected=true]:bg-[var(--zui-select-item-outline-bg-dark,var(--zui-surface-muted-dark,oklch(92.8%_0.006_264.531)))] data-[selected=true]:text-[color:var(--zui-select-item-outline-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-outline-fg-dark,var(--zui-fg-dark,oklch(21%_0.034_264.665)))]",
  ghost:
    "border-[color:var(--zui-select-item-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-select-item-ghost-border-dark,var(--zui-border-dark,transparent))] text-[color:var(--zui-select-item-ghost-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-select-item-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))] data-[selected=true]:border-[color:var(--zui-select-item-ghost-border,var(--zui-border,transparent))] dark:data-[selected=true]:border-[color:var(--zui-select-item-ghost-border-dark,var(--zui-border-dark,transparent))] data-[selected=true]:bg-[var(--zui-select-item-ghost-bg,var(--zui-surface-soft,transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-ghost-bg-dark,var(--zui-surface-soft-dark,transparent))] data-[selected=true]:text-[color:var(--zui-select-item-ghost-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-ghost-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))]",
  sky: "border-[color:var(--zui-select-item-sky-border,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:border-[color:var(--zui-select-item-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] text-[color:var(--zui-select-item-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:text-[color:var(--zui-select-item-sky-fg-dark,var(--zui-color-sky-dark,oklch(90.1%_0.058_230.902)))] data-[selected=true]:border-[color:var(--zui-select-item-sky-border,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] data-[selected=true]:bg-[var(--zui-select-item-sky-bg,color-mix(in oklch, var(--zui-color-sky,oklch(90.1%_0.058_230.902)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-sky-bg-dark,color-mix(in oklch, var(--zui-color-sky-dark,oklch(90.1%_0.058_230.902)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-sky-fg-dark,var(--zui-color-sky-dark,oklch(39.1%_0.09_240.876)))]",
  rose: "border-[color:var(--zui-select-item-rose-border,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:border-[color:var(--zui-select-item-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] text-[color:var(--zui-select-item-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-select-item-rose-fg-dark,var(--zui-color-rose-dark,oklch(89.2%_0.058_10.001)))] data-[selected=true]:border-[color:var(--zui-select-item-rose-border,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] data-[selected=true]:bg-[var(--zui-select-item-rose-bg,color-mix(in oklch, var(--zui-color-rose,oklch(89.2%_0.058_10.001)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-rose-bg-dark,color-mix(in oklch, var(--zui-color-rose-dark,oklch(89.2%_0.058_10.001)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-rose-fg-dark,var(--zui-color-rose-dark,oklch(41%_0.159_10.272)))]",
  purple:
    "border-[color:var(--zui-select-item-purple-border,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:border-[color:var(--zui-select-item-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] text-[color:var(--zui-select-item-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-select-item-purple-fg-dark,var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)))] data-[selected=true]:border-[color:var(--zui-select-item-purple-border,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:bg-[var(--zui-select-item-purple-bg,color-mix(in oklch, var(--zui-color-purple,oklch(90.2%_0.063_306.703)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-purple-bg-dark,color-mix(in oklch, var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-purple-fg-dark,var(--zui-color-purple-dark,oklch(38.1%_0.176_304.987)))]",
  pink: "border-[color:var(--zui-select-item-pink-border,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:border-[color:var(--zui-select-item-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] text-[color:var(--zui-select-item-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-select-item-pink-fg-dark,var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)))] data-[selected=true]:border-[color:var(--zui-select-item-pink-border,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:bg-[var(--zui-select-item-pink-bg,color-mix(in oklch, var(--zui-color-pink,oklch(89.9%_0.061_343.231)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-pink-bg-dark,color-mix(in oklch, var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-pink-fg-dark,var(--zui-color-pink-dark,oklch(40.8%_0.153_2.432)))]",
  orange:
    "border-[color:var(--zui-select-item-orange-border,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:border-[color:var(--zui-select-item-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] text-[color:var(--zui-select-item-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-select-item-orange-fg-dark,var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)))] data-[selected=true]:border-[color:var(--zui-select-item-orange-border,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] data-[selected=true]:bg-[var(--zui-select-item-orange-bg,color-mix(in oklch, var(--zui-color-orange,oklch(90.1%_0.076_70.697)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-orange-bg-dark,color-mix(in oklch, var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-orange-fg-dark,var(--zui-color-orange-dark,oklch(40.8%_0.123_38.172)))]",
  yellow:
    "border-[color:var(--zui-select-item-yellow-border,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:border-[color:var(--zui-select-item-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] text-[color:var(--zui-select-item-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-select-item-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)))] data-[selected=true]:border-[color:var(--zui-select-item-yellow-border,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] data-[selected=true]:bg-[var(--zui-select-item-yellow-bg,color-mix(in oklch, var(--zui-color-yellow,oklch(94.5%_0.129_101.54)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-yellow-bg-dark,color-mix(in oklch, var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(42.1%_0.095_57.708)))]",
  teal: "border-[color:var(--zui-select-item-teal-border,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:border-[color:var(--zui-select-item-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] text-[color:var(--zui-select-item-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-select-item-teal-fg-dark,var(--zui-color-teal-dark,oklch(91%_0.096_180.426)))] data-[selected=true]:border-[color:var(--zui-select-item-teal-border,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] data-[selected=true]:bg-[var(--zui-select-item-teal-bg,color-mix(in oklch, var(--zui-color-teal,oklch(91%_0.096_180.426)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-teal-bg-dark,color-mix(in oklch, var(--zui-color-teal-dark,oklch(91%_0.096_180.426)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-teal-fg-dark,var(--zui-color-teal-dark,oklch(38.6%_0.063_188.416)))]",
  indigo:
    "border-[color:var(--zui-select-item-indigo-border,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:border-[color:var(--zui-select-item-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] text-[color:var(--zui-select-item-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-select-item-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)))] data-[selected=true]:border-[color:var(--zui-select-item-indigo-border,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] data-[selected=true]:bg-[var(--zui-select-item-indigo-bg,color-mix(in oklch, var(--zui-color-indigo,oklch(87%_0.065_274.039)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-indigo-bg-dark,color-mix(in oklch, var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(35.9%_0.144_278.697)))]",
  emerald:
    "border-[color:var(--zui-select-item-emerald-border,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:border-[color:var(--zui-select-item-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] text-[color:var(--zui-select-item-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-select-item-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(90.5%_0.093_164.15)))] data-[selected=true]:border-[color:var(--zui-select-item-emerald-border,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:data-[selected=true]:border-[color:var(--zui-select-item-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] data-[selected=true]:bg-[var(--zui-select-item-emerald-bg,color-mix(in oklch, var(--zui-color-emerald,oklch(90.5%_0.093_164.15)) 10%, transparent))] dark:data-[selected=true]:bg-[var(--zui-select-item-emerald-bg-dark,color-mix(in oklch, var(--zui-color-emerald-dark,oklch(90.5%_0.093_164.15)) 18%, transparent))] data-[selected=true]:text-[color:var(--zui-select-item-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(37.8%_0.077_168.94)))]",
  "gradient-blue":
    "bg-[var(--zui-select-item-gradient-blue-bg,var(--zui-color-blue,transparent))] dark:bg-[var(--zui-select-item-gradient-blue-bg-dark,var(--zui-color-blue-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-blue-fg,var(--zui-brand-fg,oklch(97%_0.014_254.604)))] dark:text-[color:var(--zui-select-item-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(97%_0.014_254.604)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(97%_0.014_254.604)))] data-[selected=true]:to-[var(--zui-select-item-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(97.7%_0.014_308.299)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-blue-fg,var(--zui-brand-fg,oklch(37.9%_0.146_265.522)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(37.9%_0.146_265.522)))]",
  "gradient-green":
    "bg-[var(--zui-select-item-gradient-green-bg,var(--zui-color-green,transparent))] dark:bg-[var(--zui-select-item-gradient-green-bg-dark,var(--zui-color-green-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-green-fg,var(--zui-brand-fg,oklch(98.2%_0.018_155.826)))] dark:text-[color:var(--zui-select-item-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(98.2%_0.018_155.826)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-green-from-dark,var(--zui-color-green-dark,oklch(98.2%_0.018_155.826)))] data-[selected=true]:to-[var(--zui-select-item-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(98.6%_0.031_120.757)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-green-fg,var(--zui-brand-fg,oklch(39.3%_0.095_152.535)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(39.3%_0.095_152.535)))]",
  "gradient-red":
    "bg-[var(--zui-select-item-gradient-red-bg,var(--zui-color-red,transparent))] dark:bg-[var(--zui-select-item-gradient-red-bg-dark,var(--zui-color-red-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-red-fg,var(--zui-brand-fg,oklch(97.1%_0.013_17.38)))] dark:text-[color:var(--zui-select-item-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(97.1%_0.013_17.38)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-red-from-dark,var(--zui-color-red-dark,oklch(97.1%_0.013_17.38)))] data-[selected=true]:to-[var(--zui-select-item-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(97.1%_0.014_343.198)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-red-fg,var(--zui-brand-fg,oklch(39.6%_0.141_25.723)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(39.6%_0.141_25.723)))]",
  "gradient-yellow":
    "bg-[var(--zui-select-item-gradient-yellow-bg,var(--zui-color-yellow,transparent))] dark:bg-[var(--zui-select-item-gradient-yellow-bg-dark,var(--zui-color-yellow-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-yellow-fg,var(--zui-brand-fg,oklch(98.7%_0.026_102.212)))] dark:text-[color:var(--zui-select-item-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(98.7%_0.026_102.212)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(98.7%_0.026_102.212)))] data-[selected=true]:to-[var(--zui-select-item-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(98%_0.016_73.684)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-yellow-fg,var(--zui-brand-fg,oklch(42.1%_0.095_57.708)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(42.1%_0.095_57.708)))]",
  "gradient-purple":
    "bg-[var(--zui-select-item-gradient-purple-bg,var(--zui-color-purple,transparent))] dark:bg-[var(--zui-select-item-gradient-purple-bg-dark,var(--zui-color-purple-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-purple-fg,var(--zui-brand-fg,oklch(97.7%_0.014_308.299)))] dark:text-[color:var(--zui-select-item-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(97.7%_0.014_308.299)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(97.7%_0.014_308.299)))] data-[selected=true]:to-[var(--zui-select-item-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(97.1%_0.014_343.198)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-purple-fg,var(--zui-brand-fg,oklch(38.1%_0.176_304.987)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(38.1%_0.176_304.987)))]",
  "gradient-teal":
    "bg-[var(--zui-select-item-gradient-teal-bg,var(--zui-color-teal,transparent))] dark:bg-[var(--zui-select-item-gradient-teal-bg-dark,var(--zui-color-teal-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-teal-fg,var(--zui-brand-fg,oklch(98.4%_0.014_180.72)))] dark:text-[color:var(--zui-select-item-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.014_180.72)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(98.4%_0.014_180.72)))] data-[selected=true]:to-[var(--zui-select-item-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(98.4%_0.019_200.873)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-teal-fg,var(--zui-brand-fg,oklch(38.6%_0.063_188.416)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(38.6%_0.063_188.416)))]",
  "gradient-indigo":
    "bg-[var(--zui-select-item-gradient-indigo-bg,var(--zui-color-indigo,transparent))] dark:bg-[var(--zui-select-item-gradient-indigo-bg-dark,var(--zui-color-indigo-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-indigo-fg,var(--zui-brand-fg,oklch(96.2%_0.018_272.314)))] dark:text-[color:var(--zui-select-item-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(96.2%_0.018_272.314)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(96.2%_0.018_272.314)))] data-[selected=true]:to-[var(--zui-select-item-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(97.7%_0.014_308.299)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-indigo-fg,var(--zui-brand-fg,oklch(35.9%_0.144_278.697)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(35.9%_0.144_278.697)))]",
  "gradient-pink":
    "bg-[var(--zui-select-item-gradient-pink-bg,var(--zui-color-pink,transparent))] dark:bg-[var(--zui-select-item-gradient-pink-bg-dark,var(--zui-color-pink-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-pink-fg,var(--zui-brand-fg,oklch(97.1%_0.014_343.198)))] dark:text-[color:var(--zui-select-item-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(97.1%_0.014_343.198)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(97.1%_0.014_343.198)))] data-[selected=true]:to-[var(--zui-select-item-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(96.9%_0.015_12.422)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-pink-fg,var(--zui-brand-fg,oklch(40.8%_0.153_2.432)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(40.8%_0.153_2.432)))]",
  "gradient-orange":
    "bg-[var(--zui-select-item-gradient-orange-bg,var(--zui-color-orange,transparent))] dark:bg-[var(--zui-select-item-gradient-orange-bg-dark,var(--zui-color-orange-dark,transparent))] backdrop-blur-xl text-[color:var(--zui-select-item-gradient-orange-fg,var(--zui-brand-fg,oklch(98%_0.016_73.684)))] dark:text-[color:var(--zui-select-item-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(98%_0.016_73.684)))] data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-select-item-gradient-orange-from,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:data-[selected=true]:from-[var(--zui-select-item-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(98%_0.016_73.684)))] data-[selected=true]:to-[var(--zui-select-item-gradient-orange-to,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:data-[selected=true]:to-[var(--zui-select-item-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(97.1%_0.013_17.38)))] data-[selected=true]:text-[color:var(--zui-select-item-gradient-orange-fg,var(--zui-brand-fg,oklch(40.8%_0.123_38.172)))] dark:data-[selected=true]:text-[color:var(--zui-select-item-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(40.8%_0.123_38.172)))]",
  blue: "hover:bg-[var(--zui-select-item-blue-bg-hover,color-mix(in oklch, var(--zui-color-blue,#2563eb18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-blue-bg-hover-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f62e) 18%, transparent))] hover:text-[color:var(--zui-select-item-blue-fg-hover,var(--zui-color-blue,#2563eb))] dark:hover:text-[color:var(--zui-select-item-blue-fg-hover-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-select-item-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb10) 6%, transparent))] dark:bg-[var(--zui-select-item-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f61f) 12%, transparent))] text-[color:var(--zui-select-item-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-select-item-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "hover:bg-[var(--zui-select-item-cyan-bg-hover,color-mix(in oklch, var(--zui-color-cyan,#0891b218) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-cyan-bg-hover-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-cyan-fg-hover,var(--zui-color-cyan,#0891b2))] dark:hover:text-[color:var(--zui-select-item-cyan-fg-hover-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-select-item-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b210) 6%, transparent))] dark:bg-[var(--zui-select-item-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee1f) 12%, transparent))] text-[color:var(--zui-select-item-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-select-item-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "hover:bg-[var(--zui-select-item-green-bg-hover,color-mix(in oklch, var(--zui-color-green,#16a34a18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-green-bg-hover-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-green-fg-hover,var(--zui-color-green,#16a34a))] dark:hover:text-[color:var(--zui-select-item-green-fg-hover-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-select-item-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a10) 6%, transparent))] dark:bg-[var(--zui-select-item-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e1f) 12%, transparent))] text-[color:var(--zui-select-item-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-select-item-green-fg-dark,var(--zui-color-green-dark,#22c55e))]",
  lime: "hover:bg-[var(--zui-select-item-lime-bg-hover,color-mix(in oklch, var(--zui-color-lime,#65a30d18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-lime-bg-hover-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e6352e) 18%, transparent))] hover:text-[color:var(--zui-select-item-lime-fg-hover,var(--zui-color-lime,#65a30d))] dark:hover:text-[color:var(--zui-select-item-lime-fg-hover-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-select-item-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d10) 6%, transparent))] dark:bg-[var(--zui-select-item-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e6351f) 12%, transparent))] text-[color:var(--zui-select-item-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-select-item-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))]",
  mint: "hover:bg-[var(--zui-select-item-mint-bg-hover,color-mix(in oklch, var(--zui-color-mint,#10b98118) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-mint-bg-hover-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b72e) 18%, transparent))] hover:text-[color:var(--zui-select-item-mint-fg-hover,var(--zui-color-mint,#10b981))] dark:hover:text-[color:var(--zui-select-item-mint-fg-hover-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-select-item-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98110) 6%, transparent))] dark:bg-[var(--zui-select-item-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b71f) 12%, transparent))] text-[color:var(--zui-select-item-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-select-item-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "hover:bg-[var(--zui-select-item-ocean-bg-hover,color-mix(in oklch, var(--zui-color-ocean,#0284c718) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-ocean-bg-hover-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf82e) 18%, transparent))] hover:text-[color:var(--zui-select-item-ocean-fg-hover,var(--zui-color-ocean,#0284c7))] dark:hover:text-[color:var(--zui-select-item-ocean-fg-hover-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-select-item-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c710) 6%, transparent))] dark:bg-[var(--zui-select-item-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf81f) 12%, transparent))] text-[color:var(--zui-select-item-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-select-item-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "hover:bg-[var(--zui-select-item-sapphire-bg-hover,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed818) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-sapphire-bg-hover-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-sapphire-fg-hover,var(--zui-color-sapphire,#1d4ed8))] dark:hover:text-[color:var(--zui-select-item-sapphire-fg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-select-item-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed810) 6%, transparent))] dark:bg-[var(--zui-select-item-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa1f) 12%, transparent))] text-[color:var(--zui-select-item-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-select-item-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "hover:bg-[var(--zui-select-item-lavender-bg-hover,color-mix(in oklch, var(--zui-color-lavender,#8b5cf618) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-lavender-bg-hover-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-lavender-fg-hover,var(--zui-color-lavender,#8b5cf6))] dark:hover:text-[color:var(--zui-select-item-lavender-fg-hover-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-select-item-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf610) 6%, transparent))] dark:bg-[var(--zui-select-item-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa1f) 12%, transparent))] text-[color:var(--zui-select-item-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-select-item-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "hover:bg-[var(--zui-select-item-ruby-bg-hover,color-mix(in oklch, var(--zui-color-ruby,#be123c18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-ruby-bg-hover-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb71852e) 18%, transparent))] hover:text-[color:var(--zui-select-item-ruby-fg-hover,var(--zui-color-ruby,#be123c))] dark:hover:text-[color:var(--zui-select-item-ruby-fg-hover-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-select-item-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c10) 6%, transparent))] dark:bg-[var(--zui-select-item-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb71851f) 12%, transparent))] text-[color:var(--zui-select-item-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-select-item-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "hover:bg-[var(--zui-select-item-red-bg-hover,color-mix(in oklch, var(--zui-color-red,#dc262618) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-red-bg-hover-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44442e) 18%, transparent))] hover:text-[color:var(--zui-select-item-red-fg-hover,var(--zui-color-red,#dc2626))] dark:hover:text-[color:var(--zui-select-item-red-fg-hover-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-select-item-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262610) 6%, transparent))] dark:bg-[var(--zui-select-item-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef44441f) 12%, transparent))] text-[color:var(--zui-select-item-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-select-item-red-fg-dark,var(--zui-color-red-dark,#ef4444))]",
  slate:
    "hover:bg-[var(--zui-select-item-slate-bg-hover,color-mix(in oklch, var(--zui-color-slate,#47556918) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-slate-bg-hover-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-slate-fg-hover,var(--zui-color-slate,#475569))] dark:hover:text-[color:var(--zui-select-item-slate-fg-hover-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-select-item-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556910) 6%, transparent))] dark:bg-[var(--zui-select-item-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b1f) 12%, transparent))] text-[color:var(--zui-select-item-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-select-item-slate-fg-dark,var(--zui-color-slate-dark,#64748b))]",
  zinc: "hover:bg-[var(--zui-select-item-zinc-bg-hover,color-mix(in oklch, var(--zui-color-zinc,#52525b18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-zinc-bg-hover-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-zinc-fg-hover,var(--zui-color-zinc,#52525b))] dark:hover:text-[color:var(--zui-select-item-zinc-fg-hover-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-select-item-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b10) 6%, transparent))] dark:bg-[var(--zui-select-item-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a1f) 12%, transparent))] text-[color:var(--zui-select-item-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-select-item-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))]",
  stone:
    "hover:bg-[var(--zui-select-item-stone-bg-hover,color-mix(in oklch, var(--zui-color-stone,#57534e18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-stone-bg-hover-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-stone-fg-hover,var(--zui-color-stone,#57534e))] dark:hover:text-[color:var(--zui-select-item-stone-fg-hover-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-select-item-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e10) 6%, transparent))] dark:bg-[var(--zui-select-item-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c1f) 12%, transparent))] text-[color:var(--zui-select-item-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-select-item-stone-fg-dark,var(--zui-color-stone-dark,#78716c))]",
  royal:
    "hover:bg-[var(--zui-select-item-royal-bg-hover,color-mix(in oklch, var(--zui-color-royal,#4338ca18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-royal-bg-hover-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf82e) 18%, transparent))] hover:text-[color:var(--zui-select-item-royal-fg-hover,var(--zui-color-royal,#4338ca))] dark:hover:text-[color:var(--zui-select-item-royal-fg-hover-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-select-item-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca10) 6%, transparent))] dark:bg-[var(--zui-select-item-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf81f) 12%, transparent))] text-[color:var(--zui-select-item-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-select-item-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "hover:bg-[var(--zui-select-item-electric-bg-hover,color-mix(in oklch, var(--zui-color-electric,#0ea5e918) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-electric-bg-hover-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf82e) 18%, transparent))] hover:text-[color:var(--zui-select-item-electric-fg-hover,var(--zui-color-electric,#0ea5e9))] dark:hover:text-[color:var(--zui-select-item-electric-fg-hover-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-select-item-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e910) 6%, transparent))] dark:bg-[var(--zui-select-item-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf81f) 12%, transparent))] text-[color:var(--zui-select-item-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-select-item-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "hover:bg-[var(--zui-select-item-forest-bg-hover,color-mix(in oklch, var(--zui-color-forest,#16653418) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-forest-bg-hover-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade802e) 18%, transparent))] hover:text-[color:var(--zui-select-item-forest-fg-hover,var(--zui-color-forest,#166534))] dark:hover:text-[color:var(--zui-select-item-forest-fg-hover-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-select-item-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653410) 6%, transparent))] dark:bg-[var(--zui-select-item-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade801f) 12%, transparent))] text-[color:var(--zui-select-item-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-select-item-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "hover:bg-[var(--zui-select-item-sunset-bg-hover,color-mix(in oklch, var(--zui-color-sunset,#ea580c18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-sunset-bg-hover-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-sunset-fg-hover,var(--zui-color-sunset,#ea580c))] dark:hover:text-[color:var(--zui-select-item-sunset-fg-hover-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-select-item-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c10) 6%, transparent))] dark:bg-[var(--zui-select-item-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c1f) 12%, transparent))] text-[color:var(--zui-select-item-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-select-item-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "hover:bg-[var(--zui-select-item-magenta-bg-hover,color-mix(in oklch, var(--zui-color-magenta,#c026d318) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-magenta-bg-hover-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f92e) 18%, transparent))] hover:text-[color:var(--zui-select-item-magenta-fg-hover,var(--zui-color-magenta,#c026d3))] dark:hover:text-[color:var(--zui-select-item-magenta-fg-hover-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-select-item-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d310) 6%, transparent))] dark:bg-[var(--zui-select-item-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f91f) 12%, transparent))] text-[color:var(--zui-select-item-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-select-item-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "hover:bg-[var(--zui-select-item-crimson-bg-hover,color-mix(in oklch, var(--zui-color-crimson,#b91c1c18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-crimson-bg-hover-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f871712e) 18%, transparent))] hover:text-[color:var(--zui-select-item-crimson-fg-hover,var(--zui-color-crimson,#b91c1c))] dark:hover:text-[color:var(--zui-select-item-crimson-fg-hover-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-select-item-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c10) 6%, transparent))] dark:bg-[var(--zui-select-item-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f871711f) 12%, transparent))] text-[color:var(--zui-select-item-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-select-item-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "hover:bg-[var(--zui-select-item-aqua-bg-hover,color-mix(in oklch, var(--zui-color-aqua,#0f766e18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-aqua-bg-hover-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-aqua-fg-hover,var(--zui-color-aqua,#0f766e))] dark:hover:text-[color:var(--zui-select-item-aqua-fg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-select-item-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e10) 6%, transparent))] dark:bg-[var(--zui-select-item-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf1f) 12%, transparent))] text-[color:var(--zui-select-item-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-select-item-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "hover:bg-[var(--zui-select-item-plum-bg-hover,color-mix(in oklch, var(--zui-color-plum,#7e22ce18) 9%, transparent))] dark:hover:bg-[var(--zui-select-item-plum-bg-hover-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc2e) 18%, transparent))] hover:text-[color:var(--zui-select-item-plum-fg-hover,var(--zui-color-plum,#7e22ce))] dark:hover:text-[color:var(--zui-select-item-plum-fg-hover-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-select-item-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce10) 6%, transparent))] dark:bg-[var(--zui-select-item-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc1f) 12%, transparent))] text-[color:var(--zui-select-item-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-select-item-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))]",
} as const;

export const zuiSelectDisabled = {
  true: "opacity-50 cursor-not-allowed",
} as const;

export const zuiSelectContentBase =
  "absolute z-10 mt-2 w-full rounded-[var(--zui-select-content-radius,var(--zui-radius,0.375rem))] border bg-[var(--zui-select-content-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-select-content-bg-dark,var(--zui-surface-muted-dark,#000000))] shadow-[var(--zui-select-content-shadow,var(--zui-shadow,0_4px_12px_rgba(15,23,42,0.12)))] dark:shadow-[var(--zui-select-content-shadow-dark,var(--zui-shadow-dark,0_12px_32px_rgba(15,23,42,0.35)))]";

export const zuiSelectContentAppearances = {
  default:
    "bg-[var(--zui-select-content-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-select-content-default-bg-dark,var(--zui-surface-muted-dark,#000000))]",
  glass:
    "bg-[var(--zui-select-content-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-select-content-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] backdrop-blur-md",
  outline:
    "border-2 border-[color:var(--zui-select-content-outline-border,var(--zui-border,oklch(55.1%_0.027_264.364)))] dark:border-[color:var(--zui-select-content-outline-border-dark,var(--zui-border-dark,oklch(55.1%_0.027_264.364)))]",
  ghost:
    "border-[color:var(--zui-select-content-ghost-border,var(--zui-border,transparent))] dark:border-[color:var(--zui-select-content-ghost-border-dark,var(--zui-border-dark,transparent))]",
  sky: "border-[color:var(--zui-select-content-sky-border,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:border-[color:var(--zui-select-content-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))]",
  rose: "border-[color:var(--zui-select-content-rose-border,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:border-[color:var(--zui-select-content-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))]",
  purple:
    "border-[color:var(--zui-select-content-purple-border,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:border-[color:var(--zui-select-content-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  pink: "border-[color:var(--zui-select-content-pink-border,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:border-[color:var(--zui-select-content-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  orange:
    "border-[color:var(--zui-select-content-orange-border,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:border-[color:var(--zui-select-content-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))]",
  yellow:
    "border-[color:var(--zui-select-content-yellow-border,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:border-[color:var(--zui-select-content-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))]",
  teal: "border-[color:var(--zui-select-content-teal-border,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:border-[color:var(--zui-select-content-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))]",
  indigo:
    "border-[color:var(--zui-select-content-indigo-border,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:border-[color:var(--zui-select-content-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))]",
  emerald:
    "border-[color:var(--zui-select-content-emerald-border,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:border-[color:var(--zui-select-content-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-blue-from,var(--zui-color-blue,oklch(37.9%_0.146_265.522)))] dark:from-[var(--zui-select-content-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-select-content-gradient-blue-to,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:to-[var(--zui-select-content-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-green-from,var(--zui-color-green,oklch(39.3%_0.095_152.535)))] dark:from-[var(--zui-select-content-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-select-content-gradient-green-to,var(--zui-color-lime,oklch(40.5%_0.101_131.063)))] dark:to-[var(--zui-select-content-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] backdrop-blur-xl",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-red-from,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:from-[var(--zui-select-content-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-select-content-gradient-red-to,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:to-[var(--zui-select-content-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-yellow-from,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:from-[var(--zui-select-content-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-select-content-gradient-yellow-to,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:to-[var(--zui-select-content-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] backdrop-blur-xl",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-purple-from,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:from-[var(--zui-select-content-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-select-content-gradient-purple-to,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:to-[var(--zui-select-content-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] backdrop-blur-xl",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-teal-from,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:from-[var(--zui-select-content-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-select-content-gradient-teal-to,var(--zui-color-cyan,oklch(39.8%_0.07_227.392)))] dark:to-[var(--zui-select-content-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] backdrop-blur-xl",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-indigo-from,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:from-[var(--zui-select-content-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-select-content-gradient-indigo-to,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:to-[var(--zui-select-content-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] backdrop-blur-xl",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-pink-from,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:from-[var(--zui-select-content-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-select-content-gradient-pink-to,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:to-[var(--zui-select-content-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] backdrop-blur-xl",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-select-content-gradient-orange-from,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:from-[var(--zui-select-content-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-select-content-gradient-orange-to,var(--zui-color-red,oklch(39.6%_0.141_25.723)))] dark:to-[var(--zui-select-content-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] backdrop-blur-xl",
  blue: "border border-[color:var(--zui-select-content-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-select-content-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-select-content-blue-bg,color-mix(in oklch, var(--zui-color-blue,#2563eb14) 8%, transparent))] dark:bg-[var(--zui-select-content-blue-bg-dark,color-mix(in oklch, var(--zui-color-blue-dark,#3b82f624) 14%, transparent))] text-[color:var(--zui-select-content-blue-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-blue-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  cyan: "border border-[color:var(--zui-select-content-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-select-content-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-select-content-cyan-bg,color-mix(in oklch, var(--zui-color-cyan,#0891b214) 8%, transparent))] dark:bg-[var(--zui-select-content-cyan-bg-dark,color-mix(in oklch, var(--zui-color-cyan-dark,#22d3ee24) 14%, transparent))] text-[color:var(--zui-select-content-cyan-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-cyan-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  green:
    "border border-[color:var(--zui-select-content-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-select-content-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-select-content-green-bg,color-mix(in oklch, var(--zui-color-green,#16a34a14) 8%, transparent))] dark:bg-[var(--zui-select-content-green-bg-dark,color-mix(in oklch, var(--zui-color-green-dark,#22c55e24) 14%, transparent))] text-[color:var(--zui-select-content-green-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-green-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  lime: "border border-[color:var(--zui-select-content-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-select-content-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-select-content-lime-bg,color-mix(in oklch, var(--zui-color-lime,#65a30d14) 8%, transparent))] dark:bg-[var(--zui-select-content-lime-bg-dark,color-mix(in oklch, var(--zui-color-lime-dark,#a3e63524) 14%, transparent))] text-[color:var(--zui-select-content-lime-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-lime-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  mint: "border border-[color:var(--zui-select-content-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-select-content-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-select-content-mint-bg,color-mix(in oklch, var(--zui-color-mint,#10b98114) 8%, transparent))] dark:bg-[var(--zui-select-content-mint-bg-dark,color-mix(in oklch, var(--zui-color-mint-dark,#6ee7b724) 14%, transparent))] text-[color:var(--zui-select-content-mint-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-mint-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  ocean:
    "border border-[color:var(--zui-select-content-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-select-content-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-select-content-ocean-bg,color-mix(in oklch, var(--zui-color-ocean,#0284c714) 8%, transparent))] dark:bg-[var(--zui-select-content-ocean-bg-dark,color-mix(in oklch, var(--zui-color-ocean-dark,#38bdf824) 14%, transparent))] text-[color:var(--zui-select-content-ocean-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-ocean-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  sapphire:
    "border border-[color:var(--zui-select-content-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-select-content-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-select-content-sapphire-bg,color-mix(in oklch, var(--zui-color-sapphire,#1d4ed814) 8%, transparent))] dark:bg-[var(--zui-select-content-sapphire-bg-dark,color-mix(in oklch, var(--zui-color-sapphire-dark,#60a5fa24) 14%, transparent))] text-[color:var(--zui-select-content-sapphire-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-sapphire-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  lavender:
    "border border-[color:var(--zui-select-content-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-select-content-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-select-content-lavender-bg,color-mix(in oklch, var(--zui-color-lavender,#8b5cf614) 8%, transparent))] dark:bg-[var(--zui-select-content-lavender-bg-dark,color-mix(in oklch, var(--zui-color-lavender-dark,#a78bfa24) 14%, transparent))] text-[color:var(--zui-select-content-lavender-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-lavender-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  ruby: "border border-[color:var(--zui-select-content-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-select-content-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-select-content-ruby-bg,color-mix(in oklch, var(--zui-color-ruby,#be123c14) 8%, transparent))] dark:bg-[var(--zui-select-content-ruby-bg-dark,color-mix(in oklch, var(--zui-color-ruby-dark,#fb718524) 14%, transparent))] text-[color:var(--zui-select-content-ruby-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-ruby-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  red: "border border-[color:var(--zui-select-content-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-select-content-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-select-content-red-bg,color-mix(in oklch, var(--zui-color-red,#dc262614) 8%, transparent))] dark:bg-[var(--zui-select-content-red-bg-dark,color-mix(in oklch, var(--zui-color-red-dark,#ef444424) 14%, transparent))] text-[color:var(--zui-select-content-red-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-red-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  slate:
    "border border-[color:var(--zui-select-content-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-select-content-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-select-content-slate-bg,color-mix(in oklch, var(--zui-color-slate,#47556914) 8%, transparent))] dark:bg-[var(--zui-select-content-slate-bg-dark,color-mix(in oklch, var(--zui-color-slate-dark,#64748b24) 14%, transparent))] text-[color:var(--zui-select-content-slate-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-slate-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  zinc: "border border-[color:var(--zui-select-content-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-select-content-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-select-content-zinc-bg,color-mix(in oklch, var(--zui-color-zinc,#52525b14) 8%, transparent))] dark:bg-[var(--zui-select-content-zinc-bg-dark,color-mix(in oklch, var(--zui-color-zinc-dark,#71717a24) 14%, transparent))] text-[color:var(--zui-select-content-zinc-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-zinc-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  stone:
    "border border-[color:var(--zui-select-content-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-select-content-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-select-content-stone-bg,color-mix(in oklch, var(--zui-color-stone,#57534e14) 8%, transparent))] dark:bg-[var(--zui-select-content-stone-bg-dark,color-mix(in oklch, var(--zui-color-stone-dark,#78716c24) 14%, transparent))] text-[color:var(--zui-select-content-stone-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-stone-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  royal:
    "border border-[color:var(--zui-select-content-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-select-content-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-select-content-royal-bg,color-mix(in oklch, var(--zui-color-royal,#4338ca14) 8%, transparent))] dark:bg-[var(--zui-select-content-royal-bg-dark,color-mix(in oklch, var(--zui-color-royal-dark,#818cf824) 14%, transparent))] text-[color:var(--zui-select-content-royal-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-royal-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  electric:
    "border border-[color:var(--zui-select-content-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-select-content-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-select-content-electric-bg,color-mix(in oklch, var(--zui-color-electric,#0ea5e914) 8%, transparent))] dark:bg-[var(--zui-select-content-electric-bg-dark,color-mix(in oklch, var(--zui-color-electric-dark,#38bdf824) 14%, transparent))] text-[color:var(--zui-select-content-electric-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-electric-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  forest:
    "border border-[color:var(--zui-select-content-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-select-content-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-select-content-forest-bg,color-mix(in oklch, var(--zui-color-forest,#16653414) 8%, transparent))] dark:bg-[var(--zui-select-content-forest-bg-dark,color-mix(in oklch, var(--zui-color-forest-dark,#4ade8024) 14%, transparent))] text-[color:var(--zui-select-content-forest-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-forest-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  sunset:
    "border border-[color:var(--zui-select-content-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-select-content-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-select-content-sunset-bg,color-mix(in oklch, var(--zui-color-sunset,#ea580c14) 8%, transparent))] dark:bg-[var(--zui-select-content-sunset-bg-dark,color-mix(in oklch, var(--zui-color-sunset-dark,#fb923c24) 14%, transparent))] text-[color:var(--zui-select-content-sunset-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-sunset-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  magenta:
    "border border-[color:var(--zui-select-content-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-select-content-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-select-content-magenta-bg,color-mix(in oklch, var(--zui-color-magenta,#c026d314) 8%, transparent))] dark:bg-[var(--zui-select-content-magenta-bg-dark,color-mix(in oklch, var(--zui-color-magenta-dark,#e879f924) 14%, transparent))] text-[color:var(--zui-select-content-magenta-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-magenta-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  crimson:
    "border border-[color:var(--zui-select-content-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-select-content-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-select-content-crimson-bg,color-mix(in oklch, var(--zui-color-crimson,#b91c1c14) 8%, transparent))] dark:bg-[var(--zui-select-content-crimson-bg-dark,color-mix(in oklch, var(--zui-color-crimson-dark,#f8717124) 14%, transparent))] text-[color:var(--zui-select-content-crimson-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-crimson-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  aqua: "border border-[color:var(--zui-select-content-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-select-content-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-select-content-aqua-bg,color-mix(in oklch, var(--zui-color-aqua,#0f766e14) 8%, transparent))] dark:bg-[var(--zui-select-content-aqua-bg-dark,color-mix(in oklch, var(--zui-color-aqua-dark,#2dd4bf24) 14%, transparent))] text-[color:var(--zui-select-content-aqua-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-aqua-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
  plum: "border border-[color:var(--zui-select-content-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-select-content-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-select-content-plum-bg,color-mix(in oklch, var(--zui-color-plum,#7e22ce14) 8%, transparent))] dark:bg-[var(--zui-select-content-plum-bg-dark,color-mix(in oklch, var(--zui-color-plum-dark,#c084fc24) 14%, transparent))] text-[color:var(--zui-select-content-plum-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-select-content-plum-fg-dark,var(--zui-fg-dark,#f8fafc))] backdrop-blur-xl",
} as const;

export const zuiSelectSpacing = {
  none: "space-y-0",
  default: "space-y-1",
  sm: "space-y-2",
  md: "space-y-3",
  lg: "space-y-4",
  xl: "space-y-5",
} as const;
