export const zuiSlideToCompleteRootBase =
  "inline-flex w-full max-w-[var(--zui-slide-to-complete-max-width,24rem)] flex-col gap-2 align-middle";

export const zuiSlideToCompleteTrackBase =
  "relative isolate flex w-full select-none items-center overflow-hidden rounded-full border p-1 shadow-sm transition-colors [height:var(--zui-slide-to-complete-track-height,3.5rem)] [touch-action:none] motion-reduce:transition-none";

export const zuiSlideToCompleteProgressBase =
  "pointer-events-none absolute inset-y-1 left-1 right-1 z-0 origin-left rtl:origin-right rounded-full transition-transform duration-300 ease-out motion-reduce:transition-none";

export const zuiSlideToCompleteLabelBase =
  "pointer-events-none relative z-10 mx-auto select-none truncate px-[calc(var(--zui-slide-to-complete-thumb-size,2.75rem)+0.5rem)] text-center font-medium transition-opacity duration-200 group-data-[completed=true]/slide-to-complete:opacity-0 motion-reduce:transition-none";

export const zuiSlideToCompleteThumbBase =
  "absolute left-1 rtl:left-auto rtl:right-1 z-20 inline-flex shrink-0 items-center justify-center rounded-full border shadow-sm outline-none transition-[background-color,border-color,color,box-shadow,transform] duration-300 ease-out [height:var(--zui-slide-to-complete-thumb-size,2.75rem)] [touch-action:none] [width:var(--zui-slide-to-complete-thumb-size,2.75rem)] focus-visible:ring-2 focus-visible:ring-[var(--zui-slide-to-complete-focus-ring,var(--zui-color-blue,#2563eb))] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--zui-slide-to-complete-track-bg,var(--zui-color-zinc-100,#f3f4f6))] disabled:cursor-not-allowed disabled:opacity-60 data-[dragging=true]:cursor-grabbing data-[dragging=true]:transition-none motion-reduce:transition-none";

export const zuiSlideToCompleteIconBase =
  "inline-flex items-center justify-center text-base transition-transform duration-200 group-data-[completed=true]/slide-to-complete:scale-110 motion-reduce:transition-none";

export const zuiSlideToCompleteSizes = {
  sm: "[--zui-slide-to-complete-track-height:2.75rem] [--zui-slide-to-complete-thumb-size:2.125rem] [--zui-slide-to-complete-max-width:20rem] text-xs",
  md: "[--zui-slide-to-complete-track-height:3.5rem] [--zui-slide-to-complete-thumb-size:2.75rem] [--zui-slide-to-complete-max-width:24rem] text-sm",
  lg: "[--zui-slide-to-complete-track-height:4.25rem] [--zui-slide-to-complete-thumb-size:3.375rem] [--zui-slide-to-complete-max-width:28rem] text-base",
} as const;

export const zuiSlideToCompleteTrackAppearances = {
  default:
    "border-[color:var(--zui-slide-to-complete-default-track-border,var(--zui-border,#e4e4e7))] bg-[var(--zui-slide-to-complete-default-track-bg,var(--zui-color-zinc-100,#f4f4f5))] text-[color:var(--zui-slide-to-complete-default-label-fg,var(--zui-fg-muted,#52525b))] dark:border-[color:var(--zui-slide-to-complete-default-track-border-dark,var(--zui-border-dark,#3f3f46))] dark:bg-[var(--zui-slide-to-complete-default-track-bg-dark,var(--zui-color-zinc-900,#18181b))] dark:text-[color:var(--zui-slide-to-complete-default-label-fg-dark,var(--zui-fg-muted-dark,#d4d4d8))]",
  primary:
    "border-[color:var(--zui-slide-to-complete-primary-track-border,var(--zui-color-blue-200,#bfdbfe))] bg-[var(--zui-slide-to-complete-primary-track-bg,var(--zui-color-blue-50,#eff6ff))] text-[color:var(--zui-slide-to-complete-primary-label-fg,var(--zui-color-blue-950,#172554))] dark:border-[color:var(--zui-slide-to-complete-primary-track-border-dark,var(--zui-color-blue-900,#1e3a8a))] dark:bg-[var(--zui-slide-to-complete-primary-track-bg-dark,var(--zui-color-blue-950,#172554))] dark:text-[color:var(--zui-slide-to-complete-primary-label-fg-dark,var(--zui-color-blue-100,#dbeafe))]",
  secondary:
    "border-[color:var(--zui-slide-to-complete-secondary-track-border,var(--zui-color-slate-200,#e2e8f0))] bg-[var(--zui-slide-to-complete-secondary-track-bg,var(--zui-color-slate-100,#f1f5f9))] text-[color:var(--zui-slide-to-complete-secondary-label-fg,var(--zui-color-slate-700,#334155))] dark:border-[color:var(--zui-slide-to-complete-secondary-track-border-dark,var(--zui-color-slate-700,#334155))] dark:bg-[var(--zui-slide-to-complete-secondary-track-bg-dark,var(--zui-color-slate-900,#0f172a))] dark:text-[color:var(--zui-slide-to-complete-secondary-label-fg-dark,var(--zui-color-slate-200,#e2e8f0))]",
  success:
    "border-[color:var(--zui-slide-to-complete-success-track-border,var(--zui-color-emerald-200,#a7f3d0))] bg-[var(--zui-slide-to-complete-success-track-bg,var(--zui-color-emerald-50,#ecfdf5))] text-[color:var(--zui-slide-to-complete-success-label-fg,var(--zui-color-emerald-950,#022c22))] dark:border-[color:var(--zui-slide-to-complete-success-track-border-dark,var(--zui-color-emerald-900,#064e3b))] dark:bg-[var(--zui-slide-to-complete-success-track-bg-dark,var(--zui-color-emerald-950,#022c22))] dark:text-[color:var(--zui-slide-to-complete-success-label-fg-dark,var(--zui-color-emerald-100,#d1fae5))]",
  destructive:
    "border-[color:var(--zui-slide-to-complete-destructive-track-border,var(--zui-color-red-200,#fecaca))] bg-[var(--zui-slide-to-complete-destructive-track-bg,var(--zui-color-red-50,#fef2f2))] text-[color:var(--zui-slide-to-complete-destructive-label-fg,var(--zui-color-red-950,#450a0a))] dark:border-[color:var(--zui-slide-to-complete-destructive-track-border-dark,var(--zui-color-red-900,#7f1d1d))] dark:bg-[var(--zui-slide-to-complete-destructive-track-bg-dark,var(--zui-color-red-950,#450a0a))] dark:text-[color:var(--zui-slide-to-complete-destructive-label-fg-dark,var(--zui-color-red-100,#fee2e2))]",
  warning:
    "border-[color:var(--zui-slide-to-complete-warning-track-border,var(--zui-color-amber-200,#fde68a))] bg-[var(--zui-slide-to-complete-warning-track-bg,var(--zui-color-amber-50,#fffbeb))] text-[color:var(--zui-slide-to-complete-warning-label-fg,var(--zui-color-amber-950,#451a03))] dark:border-[color:var(--zui-slide-to-complete-warning-track-border-dark,var(--zui-color-amber-900,#78350f))] dark:bg-[var(--zui-slide-to-complete-warning-track-bg-dark,var(--zui-color-amber-950,#451a03))] dark:text-[color:var(--zui-slide-to-complete-warning-label-fg-dark,var(--zui-color-amber-100,#fef3c7))]",
  info: "border-[color:var(--zui-slide-to-complete-info-track-border,var(--zui-color-cyan-200,#a5f3fc))] bg-[var(--zui-slide-to-complete-info-track-bg,var(--zui-color-cyan-50,#ecfeff))] text-[color:var(--zui-slide-to-complete-info-label-fg,var(--zui-color-cyan-950,#083344))] dark:border-[color:var(--zui-slide-to-complete-info-track-border-dark,var(--zui-color-cyan-900,#164e63))] dark:bg-[var(--zui-slide-to-complete-info-track-bg-dark,var(--zui-color-cyan-950,#083344))] dark:text-[color:var(--zui-slide-to-complete-info-label-fg-dark,var(--zui-color-cyan-100,#cffafe))]",
  blue: "border-[color:var(--zui-slide-to-complete-blue-track-border,var(--zui-color-blue-200,#bfdbfe))] bg-[var(--zui-slide-to-complete-blue-track-bg,var(--zui-color-blue-50,#eff6ff))] text-[color:var(--zui-slide-to-complete-blue-label-fg,var(--zui-color-blue-950,#172554))] dark:border-[color:var(--zui-slide-to-complete-blue-track-border-dark,var(--zui-color-blue-900,#1e3a8a))] dark:bg-[var(--zui-slide-to-complete-blue-track-bg-dark,var(--zui-color-blue-950,#172554))] dark:text-[color:var(--zui-slide-to-complete-blue-label-fg-dark,var(--zui-color-blue-100,#dbeafe))]",
  violet:
    "border-[color:var(--zui-slide-to-complete-violet-track-border,var(--zui-color-violet-200,#ddd6fe))] bg-[var(--zui-slide-to-complete-violet-track-bg,var(--zui-color-violet-50,#f5f3ff))] text-[color:var(--zui-slide-to-complete-violet-label-fg,var(--zui-color-violet-950,#2e1065))] dark:border-[color:var(--zui-slide-to-complete-violet-track-border-dark,var(--zui-color-violet-900,#4c1d95))] dark:bg-[var(--zui-slide-to-complete-violet-track-bg-dark,var(--zui-color-violet-950,#2e1065))] dark:text-[color:var(--zui-slide-to-complete-violet-label-fg-dark,var(--zui-color-violet-100,#ede9fe))]",
  emerald:
    "border-[color:var(--zui-slide-to-complete-emerald-track-border,var(--zui-color-emerald-200,#a7f3d0))] bg-[var(--zui-slide-to-complete-emerald-track-bg,var(--zui-color-emerald-50,#ecfdf5))] text-[color:var(--zui-slide-to-complete-emerald-label-fg,var(--zui-color-emerald-950,#022c22))] dark:border-[color:var(--zui-slide-to-complete-emerald-track-border-dark,var(--zui-color-emerald-900,#064e3b))] dark:bg-[var(--zui-slide-to-complete-emerald-track-bg-dark,var(--zui-color-emerald-950,#022c22))] dark:text-[color:var(--zui-slide-to-complete-emerald-label-fg-dark,var(--zui-color-emerald-100,#d1fae5))]",
  amber:
    "border-[color:var(--zui-slide-to-complete-amber-track-border,var(--zui-color-amber-200,#fde68a))] bg-[var(--zui-slide-to-complete-amber-track-bg,var(--zui-color-amber-50,#fffbeb))] text-[color:var(--zui-slide-to-complete-amber-label-fg,var(--zui-color-amber-950,#451a03))] dark:border-[color:var(--zui-slide-to-complete-amber-track-border-dark,var(--zui-color-amber-900,#78350f))] dark:bg-[var(--zui-slide-to-complete-amber-track-bg-dark,var(--zui-color-amber-950,#451a03))] dark:text-[color:var(--zui-slide-to-complete-amber-label-fg-dark,var(--zui-color-amber-100,#fef3c7))]",
  rose: "border-[color:var(--zui-slide-to-complete-rose-track-border,var(--zui-color-rose-200,#fecdd3))] bg-[var(--zui-slide-to-complete-rose-track-bg,var(--zui-color-rose-50,#fff1f2))] text-[color:var(--zui-slide-to-complete-rose-label-fg,var(--zui-color-rose-950,#4c0519))] dark:border-[color:var(--zui-slide-to-complete-rose-track-border-dark,var(--zui-color-rose-900,#881337))] dark:bg-[var(--zui-slide-to-complete-rose-track-bg-dark,var(--zui-color-rose-950,#4c0519))] dark:text-[color:var(--zui-slide-to-complete-rose-label-fg-dark,var(--zui-color-rose-100,#ffe4e6))]",
  slate:
    "border-[color:var(--zui-slide-to-complete-slate-track-border,var(--zui-color-slate-300,#cbd5e1))] bg-[var(--zui-slide-to-complete-slate-track-bg,var(--zui-color-slate-100,#f1f5f9))] text-[color:var(--zui-slide-to-complete-slate-label-fg,var(--zui-color-slate-700,#334155))] dark:border-[color:var(--zui-slide-to-complete-slate-track-border-dark,var(--zui-color-slate-700,#334155))] dark:bg-[var(--zui-slide-to-complete-slate-track-bg-dark,var(--zui-color-slate-900,#0f172a))] dark:text-[color:var(--zui-slide-to-complete-slate-label-fg-dark,var(--zui-color-slate-200,#e2e8f0))]",
  zinc: "border-[color:var(--zui-slide-to-complete-zinc-track-border,var(--zui-color-zinc-300,#d4d4d8))] bg-[var(--zui-slide-to-complete-zinc-track-bg,var(--zui-color-zinc-100,#f4f4f5))] text-[color:var(--zui-slide-to-complete-zinc-label-fg,var(--zui-color-zinc-700,#3f3f46))] dark:border-[color:var(--zui-slide-to-complete-zinc-track-border-dark,var(--zui-color-zinc-700,#3f3f46))] dark:bg-[var(--zui-slide-to-complete-zinc-track-bg-dark,var(--zui-color-zinc-900,#18181b))] dark:text-[color:var(--zui-slide-to-complete-zinc-label-fg-dark,var(--zui-color-zinc-200,#e4e4e7))]",
  "gradient-blue":
    "border-[color:var(--zui-slide-to-complete-gradient-blue-track-border,var(--zui-color-blue-200,#bfdbfe))] bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-blue-track-from,#eff6ff),var(--zui-slide-to-complete-gradient-blue-track-to,#e0f2fe))] text-[color:var(--zui-slide-to-complete-gradient-blue-label-fg,var(--zui-color-blue-950,#172554))] dark:border-[color:var(--zui-slide-to-complete-gradient-blue-track-border-dark,var(--zui-color-blue-800,#1e40af))] dark:bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-blue-track-from-dark,#172554),var(--zui-slide-to-complete-gradient-blue-track-to-dark,#164e63))] dark:text-[color:var(--zui-slide-to-complete-gradient-blue-label-fg-dark,var(--zui-color-blue-100,#dbeafe))]",
  "gradient-emerald":
    "border-[color:var(--zui-slide-to-complete-gradient-emerald-track-border,var(--zui-color-emerald-200,#a7f3d0))] bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-emerald-track-from,#ecfdf5),var(--zui-slide-to-complete-gradient-emerald-track-to,#f0fdfa))] text-[color:var(--zui-slide-to-complete-gradient-emerald-label-fg,var(--zui-color-emerald-950,#022c22))] dark:border-[color:var(--zui-slide-to-complete-gradient-emerald-track-border-dark,var(--zui-color-emerald-800,#065f46))] dark:bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-emerald-track-from-dark,#022c22),var(--zui-slide-to-complete-gradient-emerald-track-to-dark,#134e4a))] dark:text-[color:var(--zui-slide-to-complete-gradient-emerald-label-fg-dark,var(--zui-color-emerald-100,#d1fae5))]",
  "gradient-rose":
    "border-[color:var(--zui-slide-to-complete-gradient-rose-track-border,var(--zui-color-rose-200,#fecdd3))] bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-rose-track-from,#fff1f2),var(--zui-slide-to-complete-gradient-rose-track-to,#fdf2f8))] text-[color:var(--zui-slide-to-complete-gradient-rose-label-fg,var(--zui-color-rose-950,#4c0519))] dark:border-[color:var(--zui-slide-to-complete-gradient-rose-track-border-dark,var(--zui-color-rose-800,#9f1239))] dark:bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-rose-track-from-dark,#4c0519),var(--zui-slide-to-complete-gradient-rose-track-to-dark,#831843))] dark:text-[color:var(--zui-slide-to-complete-gradient-rose-label-fg-dark,var(--zui-color-rose-100,#ffe4e6))]",
  glass:
    "border-[color:var(--zui-slide-to-complete-glass-track-border,rgba(148,163,184,0.35))] bg-[var(--zui-slide-to-complete-glass-track-bg,rgba(255,255,255,0.62))] text-[color:var(--zui-slide-to-complete-glass-label-fg,var(--zui-color-slate-800,#1e293b))] backdrop-blur-xl dark:border-[color:var(--zui-slide-to-complete-glass-track-border-dark,rgba(255,255,255,0.14))] dark:bg-[var(--zui-slide-to-complete-glass-track-bg-dark,rgba(15,23,42,0.52))] dark:text-[color:var(--zui-slide-to-complete-glass-label-fg-dark,var(--zui-color-slate-100,#f1f5f9))]",
} as const;

export const zuiSlideToCompleteProgressAppearances = {
  default:
    "bg-[var(--zui-slide-to-complete-default-progress-bg,var(--zui-color-zinc-300,#d4d4d8))] dark:bg-[var(--zui-slide-to-complete-default-progress-bg-dark,var(--zui-color-zinc-700,#3f3f46))]",
  primary:
    "bg-[var(--zui-slide-to-complete-primary-progress-bg,var(--zui-color-blue-500,#3b82f6))] dark:bg-[var(--zui-slide-to-complete-primary-progress-bg-dark,var(--zui-color-blue-400,#60a5fa))]",
  secondary:
    "bg-[var(--zui-slide-to-complete-secondary-progress-bg,var(--zui-color-slate-400,#94a3b8))] dark:bg-[var(--zui-slide-to-complete-secondary-progress-bg-dark,var(--zui-color-slate-600,#475569))]",
  success:
    "bg-[var(--zui-slide-to-complete-success-progress-bg,var(--zui-color-emerald-500,#10b981))] dark:bg-[var(--zui-slide-to-complete-success-progress-bg-dark,var(--zui-color-emerald-400,#34d399))]",
  destructive:
    "bg-[var(--zui-slide-to-complete-destructive-progress-bg,var(--zui-color-red-500,#ef4444))] dark:bg-[var(--zui-slide-to-complete-destructive-progress-bg-dark,var(--zui-color-red-400,#f87171))]",
  warning:
    "bg-[var(--zui-slide-to-complete-warning-progress-bg,var(--zui-color-amber-500,#f59e0b))] dark:bg-[var(--zui-slide-to-complete-warning-progress-bg-dark,var(--zui-color-amber-400,#fbbf24))]",
  info: "bg-[var(--zui-slide-to-complete-info-progress-bg,var(--zui-color-cyan-500,#06b6d4))] dark:bg-[var(--zui-slide-to-complete-info-progress-bg-dark,var(--zui-color-cyan-400,#22d3ee))]",
  blue: "bg-[var(--zui-slide-to-complete-blue-progress-bg,var(--zui-color-blue-500,#3b82f6))] dark:bg-[var(--zui-slide-to-complete-blue-progress-bg-dark,var(--zui-color-blue-400,#60a5fa))]",
  violet:
    "bg-[var(--zui-slide-to-complete-violet-progress-bg,var(--zui-color-violet-500,#8b5cf6))] dark:bg-[var(--zui-slide-to-complete-violet-progress-bg-dark,var(--zui-color-violet-400,#a78bfa))]",
  emerald:
    "bg-[var(--zui-slide-to-complete-emerald-progress-bg,var(--zui-color-emerald-500,#10b981))] dark:bg-[var(--zui-slide-to-complete-emerald-progress-bg-dark,var(--zui-color-emerald-400,#34d399))]",
  amber:
    "bg-[var(--zui-slide-to-complete-amber-progress-bg,var(--zui-color-amber-500,#f59e0b))] dark:bg-[var(--zui-slide-to-complete-amber-progress-bg-dark,var(--zui-color-amber-400,#fbbf24))]",
  rose: "bg-[var(--zui-slide-to-complete-rose-progress-bg,var(--zui-color-rose-500,#f43f5e))] dark:bg-[var(--zui-slide-to-complete-rose-progress-bg-dark,var(--zui-color-rose-400,#fb7185))]",
  slate:
    "bg-[var(--zui-slide-to-complete-slate-progress-bg,var(--zui-color-slate-500,#64748b))] dark:bg-[var(--zui-slide-to-complete-slate-progress-bg-dark,var(--zui-color-slate-500,#64748b))]",
  zinc: "bg-[var(--zui-slide-to-complete-zinc-progress-bg,var(--zui-color-zinc-500,#71717a))] dark:bg-[var(--zui-slide-to-complete-zinc-progress-bg-dark,var(--zui-color-zinc-500,#71717a))]",
  "gradient-blue":
    "bg-[linear-gradient(90deg,var(--zui-slide-to-complete-gradient-blue-progress-from,#2563eb),var(--zui-slide-to-complete-gradient-blue-progress-to,#06b6d4))] dark:bg-[linear-gradient(90deg,var(--zui-slide-to-complete-gradient-blue-progress-from-dark,#3b82f6),var(--zui-slide-to-complete-gradient-blue-progress-to-dark,#22d3ee))]",
  "gradient-emerald":
    "bg-[linear-gradient(90deg,var(--zui-slide-to-complete-gradient-emerald-progress-from,#059669),var(--zui-slide-to-complete-gradient-emerald-progress-to,#14b8a6))] dark:bg-[linear-gradient(90deg,var(--zui-slide-to-complete-gradient-emerald-progress-from-dark,#10b981),var(--zui-slide-to-complete-gradient-emerald-progress-to-dark,#2dd4bf))]",
  "gradient-rose":
    "bg-[linear-gradient(90deg,var(--zui-slide-to-complete-gradient-rose-progress-from,#e11d48),var(--zui-slide-to-complete-gradient-rose-progress-to,#d946ef))] dark:bg-[linear-gradient(90deg,var(--zui-slide-to-complete-gradient-rose-progress-from-dark,#fb7185),var(--zui-slide-to-complete-gradient-rose-progress-to-dark,#e879f9))]",
  glass:
    "bg-[var(--zui-slide-to-complete-glass-progress-bg,rgba(59,130,246,0.32))] dark:bg-[var(--zui-slide-to-complete-glass-progress-bg-dark,rgba(96,165,250,0.28))]",
} as const;

export const zuiSlideToCompleteThumbAppearances = {
  default:
    "border-[color:var(--zui-slide-to-complete-default-thumb-border,var(--zui-color-zinc-300,#d4d4d8))] bg-[var(--zui-slide-to-complete-default-thumb-bg,var(--zui-bg,#ffffff))] text-[color:var(--zui-slide-to-complete-default-thumb-fg,var(--zui-color-zinc-700,#3f3f46))] dark:border-[color:var(--zui-slide-to-complete-default-thumb-border-dark,var(--zui-color-zinc-600,#52525b))] dark:bg-[var(--zui-slide-to-complete-default-thumb-bg-dark,var(--zui-color-zinc-800,#27272a))] dark:text-[color:var(--zui-slide-to-complete-default-thumb-fg-dark,var(--zui-color-zinc-100,#f4f4f5))]",
  primary:
    "border-[color:var(--zui-slide-to-complete-primary-thumb-border,var(--zui-color-blue-600,#2563eb))] bg-[var(--zui-slide-to-complete-primary-thumb-bg,var(--zui-color-blue-600,#2563eb))] text-[color:var(--zui-slide-to-complete-primary-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-primary-thumb-border-dark,var(--zui-color-blue-400,#60a5fa))] dark:bg-[var(--zui-slide-to-complete-primary-thumb-bg-dark,var(--zui-color-blue-500,#3b82f6))] dark:text-[color:var(--zui-slide-to-complete-primary-thumb-fg-dark,#ffffff)]",
  secondary:
    "border-[color:var(--zui-slide-to-complete-secondary-thumb-border,var(--zui-color-slate-500,#64748b))] bg-[var(--zui-slide-to-complete-secondary-thumb-bg,var(--zui-color-slate-700,#334155))] text-[color:var(--zui-slide-to-complete-secondary-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-secondary-thumb-border-dark,var(--zui-color-slate-500,#64748b))] dark:bg-[var(--zui-slide-to-complete-secondary-thumb-bg-dark,var(--zui-color-slate-200,#e2e8f0))] dark:text-[color:var(--zui-slide-to-complete-secondary-thumb-fg-dark,var(--zui-color-slate-950,#020617))]",
  success:
    "border-[color:var(--zui-slide-to-complete-success-thumb-border,var(--zui-color-emerald-600,#059669))] bg-[var(--zui-slide-to-complete-success-thumb-bg,var(--zui-color-emerald-600,#059669))] text-[color:var(--zui-slide-to-complete-success-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-success-thumb-border-dark,var(--zui-color-emerald-400,#34d399))] dark:bg-[var(--zui-slide-to-complete-success-thumb-bg-dark,var(--zui-color-emerald-500,#10b981))] dark:text-[color:var(--zui-slide-to-complete-success-thumb-fg-dark,#ffffff)]",
  destructive:
    "border-[color:var(--zui-slide-to-complete-destructive-thumb-border,var(--zui-color-red-600,#dc2626))] bg-[var(--zui-slide-to-complete-destructive-thumb-bg,var(--zui-color-red-600,#dc2626))] text-[color:var(--zui-slide-to-complete-destructive-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-destructive-thumb-border-dark,var(--zui-color-red-400,#f87171))] dark:bg-[var(--zui-slide-to-complete-destructive-thumb-bg-dark,var(--zui-color-red-500,#ef4444))] dark:text-[color:var(--zui-slide-to-complete-destructive-thumb-fg-dark,#ffffff)]",
  warning:
    "border-[color:var(--zui-slide-to-complete-warning-thumb-border,var(--zui-color-amber-500,#f59e0b))] bg-[var(--zui-slide-to-complete-warning-thumb-bg,var(--zui-color-amber-500,#f59e0b))] text-[color:var(--zui-slide-to-complete-warning-thumb-fg,var(--zui-color-amber-950,#451a03))] dark:border-[color:var(--zui-slide-to-complete-warning-thumb-border-dark,var(--zui-color-amber-300,#fcd34d))] dark:bg-[var(--zui-slide-to-complete-warning-thumb-bg-dark,var(--zui-color-amber-400,#fbbf24))] dark:text-[color:var(--zui-slide-to-complete-warning-thumb-fg-dark,var(--zui-color-amber-950,#451a03))]",
  info: "border-[color:var(--zui-slide-to-complete-info-thumb-border,var(--zui-color-cyan-600,#0891b2))] bg-[var(--zui-slide-to-complete-info-thumb-bg,var(--zui-color-cyan-600,#0891b2))] text-[color:var(--zui-slide-to-complete-info-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-info-thumb-border-dark,var(--zui-color-cyan-300,#67e8f9))] dark:bg-[var(--zui-slide-to-complete-info-thumb-bg-dark,var(--zui-color-cyan-500,#06b6d4))] dark:text-[color:var(--zui-slide-to-complete-info-thumb-fg-dark,#ffffff)]",
  blue: "border-[color:var(--zui-slide-to-complete-blue-thumb-border,var(--zui-color-blue-600,#2563eb))] bg-[var(--zui-slide-to-complete-blue-thumb-bg,var(--zui-color-blue-600,#2563eb))] text-[color:var(--zui-slide-to-complete-blue-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-blue-thumb-border-dark,var(--zui-color-blue-400,#60a5fa))] dark:bg-[var(--zui-slide-to-complete-blue-thumb-bg-dark,var(--zui-color-blue-500,#3b82f6))] dark:text-[color:var(--zui-slide-to-complete-blue-thumb-fg-dark,#ffffff)]",
  violet:
    "border-[color:var(--zui-slide-to-complete-violet-thumb-border,var(--zui-color-violet-600,#7c3aed))] bg-[var(--zui-slide-to-complete-violet-thumb-bg,var(--zui-color-violet-600,#7c3aed))] text-[color:var(--zui-slide-to-complete-violet-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-violet-thumb-border-dark,var(--zui-color-violet-400,#a78bfa))] dark:bg-[var(--zui-slide-to-complete-violet-thumb-bg-dark,var(--zui-color-violet-500,#8b5cf6))] dark:text-[color:var(--zui-slide-to-complete-violet-thumb-fg-dark,#ffffff)]",
  emerald:
    "border-[color:var(--zui-slide-to-complete-emerald-thumb-border,var(--zui-color-emerald-600,#059669))] bg-[var(--zui-slide-to-complete-emerald-thumb-bg,var(--zui-color-emerald-600,#059669))] text-[color:var(--zui-slide-to-complete-emerald-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-emerald-thumb-border-dark,var(--zui-color-emerald-400,#34d399))] dark:bg-[var(--zui-slide-to-complete-emerald-thumb-bg-dark,var(--zui-color-emerald-500,#10b981))] dark:text-[color:var(--zui-slide-to-complete-emerald-thumb-fg-dark,#ffffff)]",
  amber:
    "border-[color:var(--zui-slide-to-complete-amber-thumb-border,var(--zui-color-amber-500,#f59e0b))] bg-[var(--zui-slide-to-complete-amber-thumb-bg,var(--zui-color-amber-500,#f59e0b))] text-[color:var(--zui-slide-to-complete-amber-thumb-fg,var(--zui-color-amber-950,#451a03))] dark:border-[color:var(--zui-slide-to-complete-amber-thumb-border-dark,var(--zui-color-amber-300,#fcd34d))] dark:bg-[var(--zui-slide-to-complete-amber-thumb-bg-dark,var(--zui-color-amber-400,#fbbf24))] dark:text-[color:var(--zui-slide-to-complete-amber-thumb-fg-dark,var(--zui-color-amber-950,#451a03))]",
  rose: "border-[color:var(--zui-slide-to-complete-rose-thumb-border,var(--zui-color-rose-600,#e11d48))] bg-[var(--zui-slide-to-complete-rose-thumb-bg,var(--zui-color-rose-600,#e11d48))] text-[color:var(--zui-slide-to-complete-rose-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-rose-thumb-border-dark,var(--zui-color-rose-400,#fb7185))] dark:bg-[var(--zui-slide-to-complete-rose-thumb-bg-dark,var(--zui-color-rose-500,#f43f5e))] dark:text-[color:var(--zui-slide-to-complete-rose-thumb-fg-dark,#ffffff)]",
  slate:
    "border-[color:var(--zui-slide-to-complete-slate-thumb-border,var(--zui-color-slate-600,#475569))] bg-[var(--zui-slide-to-complete-slate-thumb-bg,var(--zui-color-slate-800,#1e293b))] text-[color:var(--zui-slide-to-complete-slate-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-slate-thumb-border-dark,var(--zui-color-slate-400,#94a3b8))] dark:bg-[var(--zui-slide-to-complete-slate-thumb-bg-dark,var(--zui-color-slate-100,#f1f5f9))] dark:text-[color:var(--zui-slide-to-complete-slate-thumb-fg-dark,var(--zui-color-slate-950,#020617))]",
  zinc: "border-[color:var(--zui-slide-to-complete-zinc-thumb-border,var(--zui-color-zinc-600,#52525b))] bg-[var(--zui-slide-to-complete-zinc-thumb-bg,var(--zui-color-zinc-800,#27272a))] text-[color:var(--zui-slide-to-complete-zinc-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-zinc-thumb-border-dark,var(--zui-color-zinc-400,#a1a1aa))] dark:bg-[var(--zui-slide-to-complete-zinc-thumb-bg-dark,var(--zui-color-zinc-100,#f4f4f5))] dark:text-[color:var(--zui-slide-to-complete-zinc-thumb-fg-dark,var(--zui-color-zinc-950,#09090b))]",
  "gradient-blue":
    "border-[color:var(--zui-slide-to-complete-gradient-blue-thumb-border,var(--zui-color-blue-500,#3b82f6))] bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-blue-thumb-from,#2563eb),var(--zui-slide-to-complete-gradient-blue-thumb-to,#06b6d4))] text-[color:var(--zui-slide-to-complete-gradient-blue-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-gradient-blue-thumb-border-dark,var(--zui-color-blue-300,#93c5fd))] dark:bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-blue-thumb-from-dark,#3b82f6),var(--zui-slide-to-complete-gradient-blue-thumb-to-dark,#22d3ee))] dark:text-[color:var(--zui-slide-to-complete-gradient-blue-thumb-fg-dark,#ffffff)]",
  "gradient-emerald":
    "border-[color:var(--zui-slide-to-complete-gradient-emerald-thumb-border,var(--zui-color-emerald-500,#10b981))] bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-emerald-thumb-from,#059669),var(--zui-slide-to-complete-gradient-emerald-thumb-to,#14b8a6))] text-[color:var(--zui-slide-to-complete-gradient-emerald-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-gradient-emerald-thumb-border-dark,var(--zui-color-emerald-300,#6ee7b7))] dark:bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-emerald-thumb-from-dark,#10b981),var(--zui-slide-to-complete-gradient-emerald-thumb-to-dark,#2dd4bf))] dark:text-[color:var(--zui-slide-to-complete-gradient-emerald-thumb-fg-dark,#ffffff)]",
  "gradient-rose":
    "border-[color:var(--zui-slide-to-complete-gradient-rose-thumb-border,var(--zui-color-rose-500,#f43f5e))] bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-rose-thumb-from,#e11d48),var(--zui-slide-to-complete-gradient-rose-thumb-to,#d946ef))] text-[color:var(--zui-slide-to-complete-gradient-rose-thumb-fg,#ffffff)] dark:border-[color:var(--zui-slide-to-complete-gradient-rose-thumb-border-dark,var(--zui-color-rose-300,#fda4af))] dark:bg-[linear-gradient(135deg,var(--zui-slide-to-complete-gradient-rose-thumb-from-dark,#fb7185),var(--zui-slide-to-complete-gradient-rose-thumb-to-dark,#e879f9))] dark:text-[color:var(--zui-slide-to-complete-gradient-rose-thumb-fg-dark,#ffffff)]",
  glass:
    "border-[color:var(--zui-slide-to-complete-glass-thumb-border,rgba(255,255,255,0.7))] bg-[var(--zui-slide-to-complete-glass-thumb-bg,rgba(255,255,255,0.86))] text-[color:var(--zui-slide-to-complete-glass-thumb-fg,var(--zui-color-slate-800,#1e293b))] backdrop-blur-xl dark:border-[color:var(--zui-slide-to-complete-glass-thumb-border-dark,rgba(255,255,255,0.2))] dark:bg-[var(--zui-slide-to-complete-glass-thumb-bg-dark,rgba(15,23,42,0.78))] dark:text-[color:var(--zui-slide-to-complete-glass-thumb-fg-dark,var(--zui-color-slate-100,#f1f5f9))]",
} as const;

export const zuiSlideToCompleteAppearances = zuiSlideToCompleteTrackAppearances;
