export const zuiTabsListBase = "flex flex-wrap items-center gap-1";

export const zuiTabsListVariants = {
  default:
    "bg-[var(--zui-tabs-list-default-bg,transparent)] dark:bg-[var(--zui-tabs-list-default-bg-dark,transparent)]",
  underline:
    "border-b-2 border-[color:var(--zui-tabs-list-underline-border,transparent)] dark:border-[color:var(--zui-tabs-list-underline-border-dark,transparent)]",
  pills: "rounded-md",
} as const;

export const zuiTabsListSizes = {
  sm: "text-sm p-1",
  md: "text-base p-1.5",
  lg: "text-lg p-2",
} as const;

export const zuiTabsOrientations = {
  horizontal: "flex-row",
  vertical: "flex-col",
} as const;

export const zuiTabsTriggerBase =
  "px-3 py-1.5 rounded-md transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-tabs-trigger-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281)))] dark:focus-visible:ring-[var(--zui-tabs-trigger-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894)))]";

export const zuiTabsTriggerAppearances = {
  default:
    "bg-[var(--zui-tabs-trigger-default-bg,transparent)] dark:bg-[var(--zui-tabs-trigger-default-bg-dark,transparent)] text-[color:var(--zui-tabs-trigger-default-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-tabs-trigger-default-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))]",
  sky: "bg-[var(--zui-tabs-trigger-sky-bg,var(--zui-color-sky,oklch(82.8%_0.111_230.318)))] text-[color:var(--zui-tabs-trigger-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:bg-[var(--zui-tabs-trigger-sky-bg-dark,var(--zui-color-sky-dark,oklch(39.1%_0.09_240.876)))] dark:text-[color:var(--zui-tabs-trigger-sky-fg-dark,var(--zui-color-sky-dark,oklch(90.1%_0.058_230.902)))] data-[state=active]:bg-[var(--zui-tabs-trigger-sky-bg-active,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-sky-bg-active-dark,var(--zui-color-sky-dark,oklch(50%_0.134_242.749)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-sky-fg-active,var(--zui-color-sky,oklch(97.7%_0.013_236.62)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-sky-fg-active-dark,var(--zui-color-sky-dark,oklch(95.1%_0.026_236.824)))]",
  rose: "bg-[var(--zui-tabs-trigger-rose-bg,var(--zui-color-rose,oklch(81%_0.117_11.638)))] text-[color:var(--zui-tabs-trigger-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:bg-[var(--zui-tabs-trigger-rose-bg-dark,var(--zui-color-rose-dark,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-tabs-trigger-rose-fg-dark,var(--zui-color-rose-dark,oklch(89.2%_0.058_10.001)))] data-[state=active]:bg-[var(--zui-tabs-trigger-rose-bg-active,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-rose-bg-active-dark,var(--zui-color-rose-dark,oklch(51.4%_0.222_16.935)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-rose-fg-active,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-rose-fg-active-dark,var(--zui-color-rose-dark,oklch(94.1%_0.03_12.58)))]",
  purple:
    "bg-[var(--zui-tabs-trigger-purple-bg,var(--zui-color-purple,oklch(82.7%_0.119_306.383)))] text-[color:var(--zui-tabs-trigger-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:bg-[var(--zui-tabs-trigger-purple-bg-dark,var(--zui-color-purple-dark,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-tabs-trigger-purple-fg-dark,var(--zui-color-purple-dark,oklch(90.2%_0.063_306.703)))] data-[state=active]:bg-[var(--zui-tabs-trigger-purple-bg-active,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-purple-bg-active-dark,var(--zui-color-purple-dark,oklch(49.6%_0.265_301.924)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-purple-fg-active,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-purple-fg-active-dark,var(--zui-color-purple-dark,oklch(94.6%_0.033_307.174)))]",
  pink: "bg-[var(--zui-tabs-trigger-pink-bg,var(--zui-color-pink,oklch(82.3%_0.12_346.018)))] text-[color:var(--zui-tabs-trigger-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:bg-[var(--zui-tabs-trigger-pink-bg-dark,var(--zui-color-pink-dark,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-tabs-trigger-pink-fg-dark,var(--zui-color-pink-dark,oklch(89.9%_0.061_343.231)))] data-[state=active]:bg-[var(--zui-tabs-trigger-pink-bg-active,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-pink-bg-active-dark,var(--zui-color-pink-dark,oklch(52.5%_0.223_3.958)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-pink-fg-active,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-pink-fg-active-dark,var(--zui-color-pink-dark,oklch(94.8%_0.028_342.258)))]",
  orange:
    "bg-[var(--zui-tabs-trigger-orange-bg,var(--zui-color-orange,oklch(83.7%_0.128_66.29)))] text-[color:var(--zui-tabs-trigger-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:bg-[var(--zui-tabs-trigger-orange-bg-dark,var(--zui-color-orange-dark,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-tabs-trigger-orange-fg-dark,var(--zui-color-orange-dark,oklch(90.1%_0.076_70.697)))] data-[state=active]:bg-[var(--zui-tabs-trigger-orange-bg-active,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-orange-bg-active-dark,var(--zui-color-orange-dark,oklch(55.3%_0.195_38.402)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-orange-fg-active,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-orange-fg-active-dark,var(--zui-color-orange-dark,oklch(95.4%_0.038_75.164)))]",
  yellow:
    "bg-[var(--zui-tabs-trigger-yellow-bg,var(--zui-color-yellow,oklch(90.5%_0.182_98.111)))] text-[color:var(--zui-tabs-trigger-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:bg-[var(--zui-tabs-trigger-yellow-bg-dark,var(--zui-color-yellow-dark,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-tabs-trigger-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(94.5%_0.129_101.54)))] data-[state=active]:bg-[var(--zui-tabs-trigger-yellow-bg-active,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-yellow-bg-active-dark,var(--zui-color-yellow-dark,oklch(55.4%_0.135_66.442)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-yellow-fg-active,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-yellow-fg-active-dark,var(--zui-color-yellow-dark,oklch(97.3%_0.071_103.193)))]",
  teal: "bg-[var(--zui-tabs-trigger-teal-bg,var(--zui-color-teal,oklch(85.5%_0.138_181.071)))] text-[color:var(--zui-tabs-trigger-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:bg-[var(--zui-tabs-trigger-teal-bg-dark,var(--zui-color-teal-dark,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-tabs-trigger-teal-fg-dark,var(--zui-color-teal-dark,oklch(91%_0.096_180.426)))] data-[state=active]:bg-[var(--zui-tabs-trigger-teal-bg-active,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-teal-bg-active-dark,var(--zui-color-teal-dark,oklch(51.1%_0.096_186.391)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-teal-fg-active,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-teal-fg-active-dark,var(--zui-color-teal-dark,oklch(95.3%_0.051_180.801)))]",
  indigo:
    "bg-[var(--zui-tabs-trigger-indigo-bg,var(--zui-color-indigo,oklch(78.5%_0.115_274.713)))] text-[color:var(--zui-tabs-trigger-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:bg-[var(--zui-tabs-trigger-indigo-bg-dark,var(--zui-color-indigo-dark,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-tabs-trigger-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(87%_0.065_274.039)))] data-[state=active]:bg-[var(--zui-tabs-trigger-indigo-bg-active,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-indigo-bg-active-dark,var(--zui-color-indigo-dark,oklch(45.7%_0.24_277.023)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-indigo-fg-active,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-indigo-fg-active-dark,var(--zui-color-indigo-dark,oklch(93%_0.034_272.788)))]",
  emerald:
    "bg-[var(--zui-tabs-trigger-emerald-bg,var(--zui-color-emerald,oklch(84.5%_0.143_164.978)))] text-[color:var(--zui-tabs-trigger-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:bg-[var(--zui-tabs-trigger-emerald-bg-dark,var(--zui-color-emerald-dark,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-tabs-trigger-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(90.5%_0.093_164.15)))] data-[state=active]:bg-[var(--zui-tabs-trigger-emerald-bg-active,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-emerald-bg-active-dark,var(--zui-color-emerald-dark,oklch(50.8%_0.118_165.612)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-emerald-fg-active,var(--zui-color-emerald,oklch(97.9%_0.021_166.113)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-emerald-fg-active-dark,var(--zui-color-emerald-dark,oklch(95%_0.052_163.051)))]",
  gray: "bg-[var(--zui-tabs-trigger-gray-bg,var(--zui-color-gray,oklch(87.2%_0.01_258.338)))] text-[color:var(--zui-tabs-trigger-gray-fg,var(--zui-color-gray,oklch(21%_0.034_264.665)))] dark:bg-[var(--zui-tabs-trigger-gray-bg-dark,var(--zui-color-gray-dark,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-tabs-trigger-gray-fg-dark,var(--zui-color-gray-dark,oklch(92.8%_0.006_264.531)))] data-[state=active]:bg-[var(--zui-tabs-trigger-gray-bg-active,var(--zui-color-gray,oklch(21%_0.034_264.665)))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-gray-bg-active-dark,var(--zui-color-gray-dark,oklch(37.3%_0.034_259.733)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gray-fg-active,var(--zui-color-gray,oklch(98.5%_0.002_247.839)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gray-fg-active-dark,var(--zui-color-gray-dark,oklch(96.7%_0.003_264.542)))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-tabs-trigger-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(42.4%_0.199_265.638)))] to-[var(--zui-tabs-trigger-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-tabs-trigger-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-tabs-trigger-gradient-blue-fg,var(--zui-brand-fg,oklch(93.2%_0.032_255.585)))] dark:text-[color:var(--zui-tabs-trigger-gradient-blue-fg-dark,var(--zui-brand-fg-dark,oklch(97%_0.014_254.604)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-blue-from-active,var(--zui-color-blue,oklch(54.6%_0.245_262.881)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-blue-from-active-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-blue-to-active,var(--zui-color-purple,oklch(55.8%_0.288_302.321)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-blue-to-active-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-blue-fg-active,var(--zui-brand-fg,oklch(93.2%_0.032_255.585)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-blue-fg-active-dark,var(--zui-brand-fg-dark,oklch(93.2%_0.032_255.585)))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-tabs-trigger-gradient-green-from-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328)))] to-[var(--zui-tabs-trigger-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-tabs-trigger-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(45.3%_0.124_130.933)))] text-[color:var(--zui-tabs-trigger-gradient-green-fg,var(--zui-brand-fg,oklch(96.2%_0.044_156.743)))] dark:text-[color:var(--zui-tabs-trigger-gradient-green-fg-dark,var(--zui-brand-fg-dark,oklch(98.2%_0.018_155.826)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-green-from-active,var(--zui-color-green,oklch(62.7%_0.194_149.214)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-green-from-active-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-green-to-active,var(--zui-color-lime,oklch(64.8%_0.2_131.684)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-green-to-active-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-green-fg-active,var(--zui-brand-fg,oklch(96.2%_0.044_156.743)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-green-fg-active-dark,var(--zui-brand-fg-dark,oklch(96.2%_0.044_156.743)))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-tabs-trigger-gradient-red-from-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] to-[var(--zui-tabs-trigger-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-tabs-trigger-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-tabs-trigger-gradient-red-fg,var(--zui-brand-fg,oklch(93.6%_0.032_17.717)))] dark:text-[color:var(--zui-tabs-trigger-gradient-red-fg-dark,var(--zui-brand-fg-dark,oklch(97.1%_0.013_17.38)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-red-from-active,var(--zui-color-red,oklch(57.7%_0.245_27.325)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-red-from-active-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-red-to-active,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-red-to-active-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-red-fg-active,var(--zui-brand-fg,oklch(93.6%_0.032_17.717)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-red-fg-active-dark,var(--zui-brand-fg-dark,oklch(93.6%_0.032_17.717)))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-tabs-trigger-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] to-[var(--zui-tabs-trigger-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-tabs-trigger-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] text-[color:var(--zui-tabs-trigger-gradient-yellow-fg,var(--zui-brand-fg,oklch(97.3%_0.071_103.193)))] dark:text-[color:var(--zui-tabs-trigger-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,oklch(98.7%_0.026_102.212)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-yellow-from-active,var(--zui-color-yellow,oklch(68.1%_0.162_75.834)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-yellow-from-active-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-yellow-to-active,var(--zui-color-orange,oklch(64.6%_0.222_41.116)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-yellow-to-active-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-yellow-fg-active,var(--zui-brand-fg,oklch(97.3%_0.071_103.193)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-yellow-fg-active-dark,var(--zui-brand-fg-dark,oklch(97.3%_0.071_103.193)))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-tabs-trigger-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] to-[var(--zui-tabs-trigger-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-tabs-trigger-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-tabs-trigger-gradient-purple-fg,var(--zui-brand-fg,oklch(94.6%_0.033_307.174)))] dark:text-[color:var(--zui-tabs-trigger-gradient-purple-fg-dark,var(--zui-brand-fg-dark,oklch(97.7%_0.014_308.299)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-purple-from-active,var(--zui-color-purple,oklch(55.8%_0.288_302.321)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-purple-from-active-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-purple-to-active,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-purple-to-active-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-purple-fg-active,var(--zui-brand-fg,oklch(94.6%_0.033_307.174)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-purple-fg-active-dark,var(--zui-brand-fg-dark,oklch(94.6%_0.033_307.174)))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-tabs-trigger-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))] to-[var(--zui-tabs-trigger-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-tabs-trigger-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(45%_0.085_224.283)))] text-[color:var(--zui-tabs-trigger-gradient-teal-fg,var(--zui-brand-fg,oklch(95.3%_0.051_180.801)))] dark:text-[color:var(--zui-tabs-trigger-gradient-teal-fg-dark,var(--zui-brand-fg-dark,oklch(98.4%_0.014_180.72)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-teal-from-active,var(--zui-color-teal,oklch(60%_0.118_184.704)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-teal-from-active-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-teal-to-active,var(--zui-color-cyan,oklch(60.9%_0.126_221.723)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-teal-to-active-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-teal-fg-active,var(--zui-brand-fg,oklch(95.3%_0.051_180.801)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-teal-fg-active-dark,var(--zui-brand-fg-dark,oklch(95.3%_0.051_180.801)))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-tabs-trigger-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))] to-[var(--zui-tabs-trigger-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-tabs-trigger-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-tabs-trigger-gradient-indigo-fg,var(--zui-brand-fg,oklch(93%_0.034_272.788)))] dark:text-[color:var(--zui-tabs-trigger-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,oklch(96.2%_0.018_272.314)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-indigo-from-active,var(--zui-color-indigo,oklch(51.1%_0.262_276.966)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-indigo-from-active-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-indigo-to-active,var(--zui-color-purple,oklch(55.8%_0.288_302.321)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-indigo-to-active-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-indigo-fg-active,var(--zui-brand-fg,oklch(93%_0.034_272.788)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-indigo-fg-active-dark,var(--zui-brand-fg-dark,oklch(93%_0.034_272.788)))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-tabs-trigger-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] to-[var(--zui-tabs-trigger-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-tabs-trigger-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(45.5%_0.188_13.697)))] text-[color:var(--zui-tabs-trigger-gradient-pink-fg,var(--zui-brand-fg,oklch(94.8%_0.028_342.258)))] dark:text-[color:var(--zui-tabs-trigger-gradient-pink-fg-dark,var(--zui-brand-fg-dark,oklch(97.1%_0.014_343.198)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-pink-from-active,var(--zui-color-pink,oklch(59.2%_0.249_0.584)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-pink-from-active-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-pink-to-active,var(--zui-color-rose,oklch(58.6%_0.253_17.585)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-pink-to-active-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-pink-fg-active,var(--zui-brand-fg,oklch(94.8%_0.028_342.258)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-pink-fg-active-dark,var(--zui-brand-fg-dark,oklch(94.8%_0.028_342.258)))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-tabs-trigger-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-tabs-trigger-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] to-[var(--zui-tabs-trigger-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-tabs-trigger-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] text-[color:var(--zui-tabs-trigger-gradient-orange-fg,var(--zui-brand-fg,oklch(95.4%_0.038_75.164)))] dark:text-[color:var(--zui-tabs-trigger-gradient-orange-fg-dark,var(--zui-brand-fg-dark,oklch(98%_0.016_73.684)))] data-[state=active]:from-[var(--zui-tabs-trigger-gradient-orange-from-active,var(--zui-color-orange,oklch(64.6%_0.222_41.116)))] dark:data-[state=active]:from-[var(--zui-tabs-trigger-gradient-orange-from-active-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] data-[state=active]:to-[var(--zui-tabs-trigger-gradient-orange-to-active,var(--zui-color-red,oklch(57.7%_0.245_27.325)))] dark:data-[state=active]:to-[var(--zui-tabs-trigger-gradient-orange-to-active-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-orange-fg-active,var(--zui-brand-fg,oklch(95.4%_0.038_75.164)))] dark:data-[state=active]:text-[color:var(--zui-tabs-trigger-gradient-orange-fg-active-dark,var(--zui-brand-fg-dark,oklch(95.4%_0.038_75.164)))]",
  blue: "hover:bg-[var(--zui-tabs-trigger-blue-bg-hover,var(--zui-color-blue,#2563eb18))] dark:hover:bg-[var(--zui-tabs-trigger-blue-bg-hover-dark,var(--zui-color-blue-dark,#3b82f62e))] hover:text-[color:var(--zui-tabs-trigger-blue-fg-hover,var(--zui-color-blue,#2563eb))] dark:hover:text-[color:var(--zui-tabs-trigger-blue-fg-hover-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-tabs-trigger-blue-bg,var(--zui-color-blue,#2563eb10))] dark:bg-[var(--zui-tabs-trigger-blue-bg-dark,var(--zui-color-blue-dark,#3b82f61f))] text-[color:var(--zui-tabs-trigger-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-tabs-trigger-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "hover:bg-[var(--zui-tabs-trigger-cyan-bg-hover,var(--zui-color-cyan,#0891b218))] dark:hover:bg-[var(--zui-tabs-trigger-cyan-bg-hover-dark,var(--zui-color-cyan-dark,#22d3ee2e))] hover:text-[color:var(--zui-tabs-trigger-cyan-fg-hover,var(--zui-color-cyan,#0891b2))] dark:hover:text-[color:var(--zui-tabs-trigger-cyan-fg-hover-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-tabs-trigger-cyan-bg,var(--zui-color-cyan,#0891b210))] dark:bg-[var(--zui-tabs-trigger-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee1f))] text-[color:var(--zui-tabs-trigger-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-tabs-trigger-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "hover:bg-[var(--zui-tabs-trigger-green-bg-hover,var(--zui-color-green,#16a34a18))] dark:hover:bg-[var(--zui-tabs-trigger-green-bg-hover-dark,var(--zui-color-green-dark,#22c55e2e))] hover:text-[color:var(--zui-tabs-trigger-green-fg-hover,var(--zui-color-green,#16a34a))] dark:hover:text-[color:var(--zui-tabs-trigger-green-fg-hover-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-tabs-trigger-green-bg,var(--zui-color-green,#16a34a10))] dark:bg-[var(--zui-tabs-trigger-green-bg-dark,var(--zui-color-green-dark,#22c55e1f))] text-[color:var(--zui-tabs-trigger-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-tabs-trigger-green-fg-dark,var(--zui-color-green-dark,#22c55e))]",
  lime: "hover:bg-[var(--zui-tabs-trigger-lime-bg-hover,var(--zui-color-lime,#65a30d18))] dark:hover:bg-[var(--zui-tabs-trigger-lime-bg-hover-dark,var(--zui-color-lime-dark,#a3e6352e))] hover:text-[color:var(--zui-tabs-trigger-lime-fg-hover,var(--zui-color-lime,#65a30d))] dark:hover:text-[color:var(--zui-tabs-trigger-lime-fg-hover-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-tabs-trigger-lime-bg,var(--zui-color-lime,#65a30d10))] dark:bg-[var(--zui-tabs-trigger-lime-bg-dark,var(--zui-color-lime-dark,#a3e6351f))] text-[color:var(--zui-tabs-trigger-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-tabs-trigger-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))]",
  mint: "hover:bg-[var(--zui-tabs-trigger-mint-bg-hover,var(--zui-color-mint,#10b98118))] dark:hover:bg-[var(--zui-tabs-trigger-mint-bg-hover-dark,var(--zui-color-mint-dark,#6ee7b72e))] hover:text-[color:var(--zui-tabs-trigger-mint-fg-hover,var(--zui-color-mint,#10b981))] dark:hover:text-[color:var(--zui-tabs-trigger-mint-fg-hover-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-tabs-trigger-mint-bg,var(--zui-color-mint,#10b98110))] dark:bg-[var(--zui-tabs-trigger-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b71f))] text-[color:var(--zui-tabs-trigger-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-tabs-trigger-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "hover:bg-[var(--zui-tabs-trigger-ocean-bg-hover,var(--zui-color-ocean,#0284c718))] dark:hover:bg-[var(--zui-tabs-trigger-ocean-bg-hover-dark,var(--zui-color-ocean-dark,#38bdf82e))] hover:text-[color:var(--zui-tabs-trigger-ocean-fg-hover,var(--zui-color-ocean,#0284c7))] dark:hover:text-[color:var(--zui-tabs-trigger-ocean-fg-hover-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-tabs-trigger-ocean-bg,var(--zui-color-ocean,#0284c710))] dark:bg-[var(--zui-tabs-trigger-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf81f))] text-[color:var(--zui-tabs-trigger-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-tabs-trigger-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "hover:bg-[var(--zui-tabs-trigger-sapphire-bg-hover,var(--zui-color-sapphire,#1d4ed818))] dark:hover:bg-[var(--zui-tabs-trigger-sapphire-bg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa2e))] hover:text-[color:var(--zui-tabs-trigger-sapphire-fg-hover,var(--zui-color-sapphire,#1d4ed8))] dark:hover:text-[color:var(--zui-tabs-trigger-sapphire-fg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-tabs-trigger-sapphire-bg,var(--zui-color-sapphire,#1d4ed810))] dark:bg-[var(--zui-tabs-trigger-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa1f))] text-[color:var(--zui-tabs-trigger-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-tabs-trigger-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "hover:bg-[var(--zui-tabs-trigger-lavender-bg-hover,var(--zui-color-lavender,#8b5cf618))] dark:hover:bg-[var(--zui-tabs-trigger-lavender-bg-hover-dark,var(--zui-color-lavender-dark,#a78bfa2e))] hover:text-[color:var(--zui-tabs-trigger-lavender-fg-hover,var(--zui-color-lavender,#8b5cf6))] dark:hover:text-[color:var(--zui-tabs-trigger-lavender-fg-hover-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-tabs-trigger-lavender-bg,var(--zui-color-lavender,#8b5cf610))] dark:bg-[var(--zui-tabs-trigger-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa1f))] text-[color:var(--zui-tabs-trigger-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-tabs-trigger-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "hover:bg-[var(--zui-tabs-trigger-ruby-bg-hover,var(--zui-color-ruby,#be123c18))] dark:hover:bg-[var(--zui-tabs-trigger-ruby-bg-hover-dark,var(--zui-color-ruby-dark,#fb71852e))] hover:text-[color:var(--zui-tabs-trigger-ruby-fg-hover,var(--zui-color-ruby,#be123c))] dark:hover:text-[color:var(--zui-tabs-trigger-ruby-fg-hover-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-tabs-trigger-ruby-bg,var(--zui-color-ruby,#be123c10))] dark:bg-[var(--zui-tabs-trigger-ruby-bg-dark,var(--zui-color-ruby-dark,#fb71851f))] text-[color:var(--zui-tabs-trigger-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-tabs-trigger-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "hover:bg-[var(--zui-tabs-trigger-red-bg-hover,var(--zui-color-red,#dc262618))] dark:hover:bg-[var(--zui-tabs-trigger-red-bg-hover-dark,var(--zui-color-red-dark,#ef44442e))] hover:text-[color:var(--zui-tabs-trigger-red-fg-hover,var(--zui-color-red,#dc2626))] dark:hover:text-[color:var(--zui-tabs-trigger-red-fg-hover-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-tabs-trigger-red-bg,var(--zui-color-red,#dc262610))] dark:bg-[var(--zui-tabs-trigger-red-bg-dark,var(--zui-color-red-dark,#ef44441f))] text-[color:var(--zui-tabs-trigger-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-tabs-trigger-red-fg-dark,var(--zui-color-red-dark,#ef4444))]",
  slate:
    "hover:bg-[var(--zui-tabs-trigger-slate-bg-hover,var(--zui-color-slate,#47556918))] dark:hover:bg-[var(--zui-tabs-trigger-slate-bg-hover-dark,var(--zui-color-slate-dark,#64748b2e))] hover:text-[color:var(--zui-tabs-trigger-slate-fg-hover,var(--zui-color-slate,#475569))] dark:hover:text-[color:var(--zui-tabs-trigger-slate-fg-hover-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-tabs-trigger-slate-bg,var(--zui-color-slate,#47556910))] dark:bg-[var(--zui-tabs-trigger-slate-bg-dark,var(--zui-color-slate-dark,#64748b1f))] text-[color:var(--zui-tabs-trigger-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-tabs-trigger-slate-fg-dark,var(--zui-color-slate-dark,#64748b))]",
  zinc: "hover:bg-[var(--zui-tabs-trigger-zinc-bg-hover,var(--zui-color-zinc,#52525b18))] dark:hover:bg-[var(--zui-tabs-trigger-zinc-bg-hover-dark,var(--zui-color-zinc-dark,#71717a2e))] hover:text-[color:var(--zui-tabs-trigger-zinc-fg-hover,var(--zui-color-zinc,#52525b))] dark:hover:text-[color:var(--zui-tabs-trigger-zinc-fg-hover-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-tabs-trigger-zinc-bg,var(--zui-color-zinc,#52525b10))] dark:bg-[var(--zui-tabs-trigger-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a1f))] text-[color:var(--zui-tabs-trigger-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-tabs-trigger-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))]",
  stone:
    "hover:bg-[var(--zui-tabs-trigger-stone-bg-hover,var(--zui-color-stone,#57534e18))] dark:hover:bg-[var(--zui-tabs-trigger-stone-bg-hover-dark,var(--zui-color-stone-dark,#78716c2e))] hover:text-[color:var(--zui-tabs-trigger-stone-fg-hover,var(--zui-color-stone,#57534e))] dark:hover:text-[color:var(--zui-tabs-trigger-stone-fg-hover-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-tabs-trigger-stone-bg,var(--zui-color-stone,#57534e10))] dark:bg-[var(--zui-tabs-trigger-stone-bg-dark,var(--zui-color-stone-dark,#78716c1f))] text-[color:var(--zui-tabs-trigger-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-tabs-trigger-stone-fg-dark,var(--zui-color-stone-dark,#78716c))]",
  royal:
    "hover:bg-[var(--zui-tabs-trigger-royal-bg-hover,var(--zui-color-royal,#4338ca18))] dark:hover:bg-[var(--zui-tabs-trigger-royal-bg-hover-dark,var(--zui-color-royal-dark,#818cf82e))] hover:text-[color:var(--zui-tabs-trigger-royal-fg-hover,var(--zui-color-royal,#4338ca))] dark:hover:text-[color:var(--zui-tabs-trigger-royal-fg-hover-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-tabs-trigger-royal-bg,var(--zui-color-royal,#4338ca10))] dark:bg-[var(--zui-tabs-trigger-royal-bg-dark,var(--zui-color-royal-dark,#818cf81f))] text-[color:var(--zui-tabs-trigger-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-tabs-trigger-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "hover:bg-[var(--zui-tabs-trigger-electric-bg-hover,var(--zui-color-electric,#0ea5e918))] dark:hover:bg-[var(--zui-tabs-trigger-electric-bg-hover-dark,var(--zui-color-electric-dark,#38bdf82e))] hover:text-[color:var(--zui-tabs-trigger-electric-fg-hover,var(--zui-color-electric,#0ea5e9))] dark:hover:text-[color:var(--zui-tabs-trigger-electric-fg-hover-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-tabs-trigger-electric-bg,var(--zui-color-electric,#0ea5e910))] dark:bg-[var(--zui-tabs-trigger-electric-bg-dark,var(--zui-color-electric-dark,#38bdf81f))] text-[color:var(--zui-tabs-trigger-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-tabs-trigger-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "hover:bg-[var(--zui-tabs-trigger-forest-bg-hover,var(--zui-color-forest,#16653418))] dark:hover:bg-[var(--zui-tabs-trigger-forest-bg-hover-dark,var(--zui-color-forest-dark,#4ade802e))] hover:text-[color:var(--zui-tabs-trigger-forest-fg-hover,var(--zui-color-forest,#166534))] dark:hover:text-[color:var(--zui-tabs-trigger-forest-fg-hover-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-tabs-trigger-forest-bg,var(--zui-color-forest,#16653410))] dark:bg-[var(--zui-tabs-trigger-forest-bg-dark,var(--zui-color-forest-dark,#4ade801f))] text-[color:var(--zui-tabs-trigger-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-tabs-trigger-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "hover:bg-[var(--zui-tabs-trigger-sunset-bg-hover,var(--zui-color-sunset,#ea580c18))] dark:hover:bg-[var(--zui-tabs-trigger-sunset-bg-hover-dark,var(--zui-color-sunset-dark,#fb923c2e))] hover:text-[color:var(--zui-tabs-trigger-sunset-fg-hover,var(--zui-color-sunset,#ea580c))] dark:hover:text-[color:var(--zui-tabs-trigger-sunset-fg-hover-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-tabs-trigger-sunset-bg,var(--zui-color-sunset,#ea580c10))] dark:bg-[var(--zui-tabs-trigger-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c1f))] text-[color:var(--zui-tabs-trigger-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-tabs-trigger-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "hover:bg-[var(--zui-tabs-trigger-magenta-bg-hover,var(--zui-color-magenta,#c026d318))] dark:hover:bg-[var(--zui-tabs-trigger-magenta-bg-hover-dark,var(--zui-color-magenta-dark,#e879f92e))] hover:text-[color:var(--zui-tabs-trigger-magenta-fg-hover,var(--zui-color-magenta,#c026d3))] dark:hover:text-[color:var(--zui-tabs-trigger-magenta-fg-hover-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-tabs-trigger-magenta-bg,var(--zui-color-magenta,#c026d310))] dark:bg-[var(--zui-tabs-trigger-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f91f))] text-[color:var(--zui-tabs-trigger-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-tabs-trigger-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "hover:bg-[var(--zui-tabs-trigger-crimson-bg-hover,var(--zui-color-crimson,#b91c1c18))] dark:hover:bg-[var(--zui-tabs-trigger-crimson-bg-hover-dark,var(--zui-color-crimson-dark,#f871712e))] hover:text-[color:var(--zui-tabs-trigger-crimson-fg-hover,var(--zui-color-crimson,#b91c1c))] dark:hover:text-[color:var(--zui-tabs-trigger-crimson-fg-hover-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-tabs-trigger-crimson-bg,var(--zui-color-crimson,#b91c1c10))] dark:bg-[var(--zui-tabs-trigger-crimson-bg-dark,var(--zui-color-crimson-dark,#f871711f))] text-[color:var(--zui-tabs-trigger-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-tabs-trigger-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "hover:bg-[var(--zui-tabs-trigger-aqua-bg-hover,var(--zui-color-aqua,#0f766e18))] dark:hover:bg-[var(--zui-tabs-trigger-aqua-bg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf2e))] hover:text-[color:var(--zui-tabs-trigger-aqua-fg-hover,var(--zui-color-aqua,#0f766e))] dark:hover:text-[color:var(--zui-tabs-trigger-aqua-fg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-tabs-trigger-aqua-bg,var(--zui-color-aqua,#0f766e10))] dark:bg-[var(--zui-tabs-trigger-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf1f))] text-[color:var(--zui-tabs-trigger-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-tabs-trigger-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "hover:bg-[var(--zui-tabs-trigger-plum-bg-hover,var(--zui-color-plum,#7e22ce18))] dark:hover:bg-[var(--zui-tabs-trigger-plum-bg-hover-dark,var(--zui-color-plum-dark,#c084fc2e))] hover:text-[color:var(--zui-tabs-trigger-plum-fg-hover,var(--zui-color-plum,#7e22ce))] dark:hover:text-[color:var(--zui-tabs-trigger-plum-fg-hover-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-tabs-trigger-plum-bg,var(--zui-color-plum,#7e22ce10))] dark:bg-[var(--zui-tabs-trigger-plum-bg-dark,var(--zui-color-plum-dark,#c084fc1f))] text-[color:var(--zui-tabs-trigger-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-tabs-trigger-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))]",
} as const;

export const zuiTabsTriggerVariants = {
  default:
    "data-[state=active]:bg-[var(--zui-tabs-trigger-default-bg-active,var(--zui-surface-muted,#ffffff))] dark:data-[state=active]:bg-[var(--zui-tabs-trigger-default-bg-active-dark,var(--zui-surface-muted-dark,#020617))]",
  underline:
    "border-b-2 border-[color:var(--zui-tabs-trigger-underline-border,transparent)] dark:border-[color:var(--zui-tabs-trigger-underline-border-dark,transparent)] data-[state=active]:border-current rounded-none",
  pills: "",
} as const;

export const zuiTabsTriggerSizes = {
  sm: "px-2 py-1",
  md: "px-3 py-1.5",
  lg: "px-4 py-2",
} as const;
