export const zuiTimelineBase = "flex w-full flex-col";

export const zuiTimelineItemBase = "relative flex gap-4";

export const zuiTimelineIndicatorBase =
  "relative z-[1] grid shrink-0 place-items-center rounded-full border font-semibold transition-colors";

export const zuiTimelineIndicatorAppearances = {
  default:
    "border-[color:var(--zui-timeline-indicator-default-border,var(--zui-border,oklch(55.1%_0.027_264.364_/_0.6)))] bg-[var(--zui-timeline-indicator-default-bg,var(--zui-surface-muted,oklch(55.1%_0.027_264.364_/_0.2)))] text-[color:var(--zui-timeline-indicator-default-fg,var(--zui-fg,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-timeline-indicator-default-fg-dark,var(--zui-fg-dark,oklch(96.7%_0.003_264.542)))] ring-2 ring-[var(--zui-timeline-indicator-default-ring,var(--zui-focus-ring,oklch(70.7%_0.022_261.325_/_0.3)))]",
  sky: "border-[color:var(--zui-timeline-indicator-sky-border,var(--zui-color-sky,oklch(68.5%_0.169_237.323_/_0.6)))] bg-[var(--zui-timeline-indicator-sky-bg,var(--zui-color-sky,oklch(68.5%_0.169_237.323_/_0.2)))] text-[color:var(--zui-timeline-indicator-sky-fg,var(--zui-color-sky,oklch(39.1%_0.09_240.876)))] dark:text-[color:var(--zui-timeline-indicator-sky-fg-dark,var(--zui-color-sky-dark,oklch(95.1%_0.026_236.824)))] ring-2 ring-[var(--zui-timeline-indicator-sky-ring,var(--zui-color-sky,oklch(74.6%_0.16_232.661_/_0.3)))]",
  rose: "border-[color:var(--zui-timeline-indicator-rose-border,var(--zui-color-rose,oklch(64.5%_0.246_16.439_/_0.6)))] bg-[var(--zui-timeline-indicator-rose-bg,var(--zui-color-rose,oklch(64.5%_0.246_16.439_/_0.2)))] text-[color:var(--zui-timeline-indicator-rose-fg,var(--zui-color-rose,oklch(41%_0.159_10.272)))] dark:text-[color:var(--zui-timeline-indicator-rose-fg-dark,var(--zui-color-rose-dark,oklch(94.1%_0.03_12.58)))] ring-2 ring-[var(--zui-timeline-indicator-rose-ring,var(--zui-color-rose,oklch(71.2%_0.194_13.428_/_0.3)))]",
  purple:
    "border-[color:var(--zui-timeline-indicator-purple-border,var(--zui-color-purple,oklch(62.7%_0.265_303.9_/_0.6)))] bg-[var(--zui-timeline-indicator-purple-bg,var(--zui-color-purple,oklch(62.7%_0.265_303.9_/_0.2)))] text-[color:var(--zui-timeline-indicator-purple-fg,var(--zui-color-purple,oklch(38.1%_0.176_304.987)))] dark:text-[color:var(--zui-timeline-indicator-purple-fg-dark,var(--zui-color-purple-dark,oklch(94.6%_0.033_307.174)))] ring-2 ring-[var(--zui-timeline-indicator-purple-ring,var(--zui-color-purple,oklch(71.4%_0.203_305.504_/_0.3)))]",
  pink: "border-[color:var(--zui-timeline-indicator-pink-border,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.6)))] bg-[var(--zui-timeline-indicator-pink-bg,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.2)))] text-[color:var(--zui-timeline-indicator-pink-fg,var(--zui-color-pink,oklch(40.8%_0.153_2.432)))] dark:text-[color:var(--zui-timeline-indicator-pink-fg-dark,var(--zui-color-pink-dark,oklch(94.8%_0.028_342.258)))] ring-2 ring-[var(--zui-timeline-indicator-pink-ring,var(--zui-color-pink,oklch(71.8%_0.202_349.761_/_0.3)))]",
  orange:
    "border-[color:var(--zui-timeline-indicator-orange-border,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.6)))] bg-[var(--zui-timeline-indicator-orange-bg,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.2)))] text-[color:var(--zui-timeline-indicator-orange-fg,var(--zui-color-orange,oklch(40.8%_0.123_38.172)))] dark:text-[color:var(--zui-timeline-indicator-orange-fg-dark,var(--zui-color-orange-dark,oklch(95.4%_0.038_75.164)))] ring-2 ring-[var(--zui-timeline-indicator-orange-ring,var(--zui-color-orange,oklch(75%_0.183_55.934_/_0.3)))]",
  yellow:
    "border-[color:var(--zui-timeline-indicator-yellow-border,var(--zui-color-yellow,oklch(79.5%_0.184_86.047_/_0.6)))] bg-[var(--zui-timeline-indicator-yellow-bg,var(--zui-color-yellow,oklch(79.5%_0.184_86.047_/_0.2)))] text-[color:var(--zui-timeline-indicator-yellow-fg,var(--zui-color-yellow,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-timeline-indicator-yellow-fg-dark,var(--zui-color-yellow-dark,oklch(97.3%_0.071_103.193)))] ring-2 ring-[var(--zui-timeline-indicator-yellow-ring,var(--zui-color-yellow,oklch(85.2%_0.199_91.936_/_0.3)))]",
  teal: "border-[color:var(--zui-timeline-indicator-teal-border,var(--zui-color-teal,oklch(70.4%_0.14_182.503_/_0.6)))] bg-[var(--zui-timeline-indicator-teal-bg,var(--zui-color-teal,oklch(70.4%_0.14_182.503_/_0.2)))] text-[color:var(--zui-timeline-indicator-teal-fg,var(--zui-color-teal,oklch(38.6%_0.063_188.416)))] dark:text-[color:var(--zui-timeline-indicator-teal-fg-dark,var(--zui-color-teal-dark,oklch(95.3%_0.051_180.801)))] ring-2 ring-[var(--zui-timeline-indicator-teal-ring,var(--zui-color-teal,oklch(77.7%_0.152_181.912_/_0.3)))]",
  indigo:
    "border-[color:var(--zui-timeline-indicator-indigo-border,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.6)))] bg-[var(--zui-timeline-indicator-indigo-bg,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.2)))] text-[color:var(--zui-timeline-indicator-indigo-fg,var(--zui-color-indigo,oklch(35.9%_0.144_278.697)))] dark:text-[color:var(--zui-timeline-indicator-indigo-fg-dark,var(--zui-color-indigo-dark,oklch(93%_0.034_272.788)))] ring-2 ring-[var(--zui-timeline-indicator-indigo-ring,var(--zui-color-indigo,oklch(67.3%_0.182_276.935_/_0.3)))]",
  emerald:
    "border-[color:var(--zui-timeline-indicator-emerald-border,var(--zui-color-emerald,oklch(69.6%_0.17_162.48_/_0.6)))] bg-[var(--zui-timeline-indicator-emerald-bg,var(--zui-color-emerald,oklch(69.6%_0.17_162.48_/_0.2)))] text-[color:var(--zui-timeline-indicator-emerald-fg,var(--zui-color-emerald,oklch(37.8%_0.077_168.94)))] dark:text-[color:var(--zui-timeline-indicator-emerald-fg-dark,var(--zui-color-emerald-dark,oklch(95%_0.052_163.051)))] ring-2 ring-[var(--zui-timeline-indicator-emerald-ring,var(--zui-color-emerald,oklch(76.5%_0.177_163.223_/_0.3)))]",
  gray: "border-[color:var(--zui-timeline-indicator-gray-border,var(--zui-color-gray,oklch(55.1%_0.027_264.364_/_0.6)))] bg-[var(--zui-timeline-indicator-gray-bg,var(--zui-color-gray,oklch(55.1%_0.027_264.364_/_0.2)))] text-[color:var(--zui-timeline-indicator-gray-fg,var(--zui-color-gray,oklch(21%_0.034_264.665)))] dark:text-[color:var(--zui-timeline-indicator-gray-fg-dark,var(--zui-color-gray-dark,oklch(96.7%_0.003_264.542)))] ring-2 ring-[var(--zui-timeline-indicator-gray-ring,var(--zui-color-gray,oklch(70.7%_0.022_261.325_/_0.3)))]",
  violet:
    "border-[color:var(--zui-timeline-indicator-violet-border,var(--zui-color-violet,oklch(60.6%_0.25_292.717_/_0.6)))] bg-[var(--zui-timeline-indicator-violet-bg,var(--zui-color-violet,oklch(60.6%_0.25_292.717_/_0.2)))] text-[color:var(--zui-timeline-indicator-violet-fg,var(--zui-color-violet,oklch(38%_0.189_293.745)))] dark:text-[color:var(--zui-timeline-indicator-violet-fg-dark,var(--zui-color-violet-dark,oklch(94.3%_0.029_294.588)))] ring-2 ring-[var(--zui-timeline-indicator-violet-ring,var(--zui-color-violet,oklch(70.2%_0.183_293.541_/_0.3)))]",
  "gradient-blue":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-blue-from,var(--zui-color-blue,oklch(62.3%_0.214_259.815)))] dark:from-[var(--zui-timeline-indicator-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(42.4%_0.199_265.638)))] to-[var(--zui-timeline-indicator-gradient-blue-to,var(--zui-color-purple,oklch(54.6%_0.245_262.881)))] dark:to-[var(--zui-timeline-indicator-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(37.9%_0.146_265.522)))] text-[color:var(--zui-timeline-indicator-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-blue-ring,var(--zui-color-blue,oklch(70.7%_0.165_254.624_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-blue-ring-dark,var(--zui-color-blue-dark,oklch(42.4%_0.199_265.638_/_0.3)))]",
  "gradient-green":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-green-from,var(--zui-color-green,oklch(72.3%_0.219_149.579)))] dark:from-[var(--zui-timeline-indicator-gradient-green-from-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328)))] to-[var(--zui-timeline-indicator-gradient-green-to,var(--zui-color-lime,oklch(62.7%_0.194_149.214)))] dark:to-[var(--zui-timeline-indicator-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(39.3%_0.095_152.535)))] text-[color:var(--zui-timeline-indicator-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-green-ring,var(--zui-color-green,oklch(79.2%_0.209_151.711_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-green-ring-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328_/_0.3)))]",
  "gradient-red":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-red-from,var(--zui-color-red,oklch(63.7%_0.237_25.331)))] dark:from-[var(--zui-timeline-indicator-gradient-red-from-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] to-[var(--zui-timeline-indicator-gradient-red-to,var(--zui-color-pink,oklch(57.7%_0.245_27.325)))] dark:to-[var(--zui-timeline-indicator-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(39.6%_0.141_25.723)))] text-[color:var(--zui-timeline-indicator-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-red-ring,var(--zui-color-red,oklch(70.4%_0.191_22.216_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-red-ring-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899_/_0.3)))]",
  "gradient-yellow":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-yellow-from,var(--zui-color-yellow,oklch(85.2%_0.199_91.936)))] dark:from-[var(--zui-timeline-indicator-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] to-[var(--zui-timeline-indicator-gradient-yellow-to,var(--zui-color-orange,oklch(79.5%_0.184_86.047)))] dark:to-[var(--zui-timeline-indicator-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(42.1%_0.095_57.708)))] text-[color:var(--zui-timeline-indicator-gradient-yellow-fg,var(--zui-brand-fg,oklch(42.1%_0.095_57.708)))] dark:text-[color:var(--zui-timeline-indicator-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-yellow-ring,var(--zui-color-yellow,oklch(85.2%_0.199_91.936_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-yellow-ring-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907_/_0.3)))]",
  "gradient-purple":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-purple-from,var(--zui-color-purple,oklch(71.4%_0.203_305.504)))] dark:from-[var(--zui-timeline-indicator-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] to-[var(--zui-timeline-indicator-gradient-purple-to,var(--zui-color-pink,oklch(62.7%_0.265_303.9)))] dark:to-[var(--zui-timeline-indicator-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(38.1%_0.176_304.987)))] text-[color:var(--zui-timeline-indicator-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-purple-ring,var(--zui-color-purple,oklch(71.4%_0.203_305.504_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-purple-ring-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724_/_0.3)))]",
  "gradient-teal":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-teal-from,var(--zui-color-teal,oklch(77.7%_0.152_181.912)))] dark:from-[var(--zui-timeline-indicator-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))] to-[var(--zui-timeline-indicator-gradient-teal-to,var(--zui-color-cyan,oklch(70.4%_0.14_182.503)))] dark:to-[var(--zui-timeline-indicator-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(38.6%_0.063_188.416)))] text-[color:var(--zui-timeline-indicator-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-teal-ring,var(--zui-color-teal,oklch(77.7%_0.152_181.912_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-teal-ring-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216_/_0.3)))]",
  "gradient-indigo":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-indigo-from,var(--zui-color-indigo,oklch(67.3%_0.182_276.935)))] dark:from-[var(--zui-timeline-indicator-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))] to-[var(--zui-timeline-indicator-gradient-indigo-to,var(--zui-color-purple,oklch(58.5%_0.233_277.117)))] dark:to-[var(--zui-timeline-indicator-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(35.9%_0.144_278.697)))] text-[color:var(--zui-timeline-indicator-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-indigo-ring,var(--zui-color-indigo,oklch(67.3%_0.182_276.935_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-indigo-ring-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366_/_0.3)))]",
  "gradient-pink":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-pink-from,var(--zui-color-pink,oklch(71.8%_0.202_349.761)))] dark:from-[var(--zui-timeline-indicator-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] to-[var(--zui-timeline-indicator-gradient-pink-to,var(--zui-color-rose,oklch(65.6%_0.241_354.308)))] dark:to-[var(--zui-timeline-indicator-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(40.8%_0.153_2.432)))] text-[color:var(--zui-timeline-indicator-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-pink-ring,var(--zui-color-pink,oklch(71.8%_0.202_349.761_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-pink-ring-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815_/_0.3)))]",
  "gradient-orange":
    "border-transparent bg-linear-to-br from-[var(--zui-timeline-indicator-gradient-orange-from,var(--zui-color-orange,oklch(75%_0.183_55.934)))] dark:from-[var(--zui-timeline-indicator-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] to-[var(--zui-timeline-indicator-gradient-orange-to,var(--zui-color-red,oklch(70.5%_0.213_47.604)))] dark:to-[var(--zui-timeline-indicator-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(40.8%_0.123_38.172)))] text-[color:var(--zui-timeline-indicator-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-timeline-indicator-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))] ring-2 ring-[var(--zui-timeline-indicator-gradient-orange-ring,var(--zui-color-orange,oklch(75%_0.183_55.934_/_0.3)))] dark:ring-[var(--zui-timeline-indicator-gradient-orange-ring-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304_/_0.3)))]",
  blue: "border-[color:var(--zui-timeline-indicator-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-timeline-indicator-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-timeline-indicator-blue-bg,var(--zui-color-blue,#2563eb14))] dark:bg-[var(--zui-timeline-indicator-blue-bg-dark,var(--zui-color-blue-dark,#3b82f624))] text-[color:var(--zui-timeline-indicator-blue-fg,var(--zui-color-blue,#2563eb))] dark:text-[color:var(--zui-timeline-indicator-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))] ring-2 ring-[var(--zui-timeline-indicator-blue-ring,var(--zui-color-blue,#2563eb33))] dark:ring-[var(--zui-timeline-indicator-blue-ring-dark,var(--zui-color-blue-dark,#3b82f640))]",
  cyan: "border-[color:var(--zui-timeline-indicator-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-timeline-indicator-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-timeline-indicator-cyan-bg,var(--zui-color-cyan,#0891b214))] dark:bg-[var(--zui-timeline-indicator-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee24))] text-[color:var(--zui-timeline-indicator-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:text-[color:var(--zui-timeline-indicator-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))] ring-2 ring-[var(--zui-timeline-indicator-cyan-ring,var(--zui-color-cyan,#0891b233))] dark:ring-[var(--zui-timeline-indicator-cyan-ring-dark,var(--zui-color-cyan-dark,#22d3ee40))]",
  green:
    "border-[color:var(--zui-timeline-indicator-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-timeline-indicator-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-timeline-indicator-green-bg,var(--zui-color-green,#16a34a14))] dark:bg-[var(--zui-timeline-indicator-green-bg-dark,var(--zui-color-green-dark,#22c55e24))] text-[color:var(--zui-timeline-indicator-green-fg,var(--zui-color-green,#16a34a))] dark:text-[color:var(--zui-timeline-indicator-green-fg-dark,var(--zui-color-green-dark,#22c55e))] ring-2 ring-[var(--zui-timeline-indicator-green-ring,var(--zui-color-green,#16a34a33))] dark:ring-[var(--zui-timeline-indicator-green-ring-dark,var(--zui-color-green-dark,#22c55e40))]",
  lime: "border-[color:var(--zui-timeline-indicator-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-timeline-indicator-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-timeline-indicator-lime-bg,var(--zui-color-lime,#65a30d14))] dark:bg-[var(--zui-timeline-indicator-lime-bg-dark,var(--zui-color-lime-dark,#a3e63524))] text-[color:var(--zui-timeline-indicator-lime-fg,var(--zui-color-lime,#65a30d))] dark:text-[color:var(--zui-timeline-indicator-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))] ring-2 ring-[var(--zui-timeline-indicator-lime-ring,var(--zui-color-lime,#65a30d33))] dark:ring-[var(--zui-timeline-indicator-lime-ring-dark,var(--zui-color-lime-dark,#a3e63540))]",
  mint: "border-[color:var(--zui-timeline-indicator-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-timeline-indicator-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-timeline-indicator-mint-bg,var(--zui-color-mint,#10b98114))] dark:bg-[var(--zui-timeline-indicator-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b724))] text-[color:var(--zui-timeline-indicator-mint-fg,var(--zui-color-mint,#10b981))] dark:text-[color:var(--zui-timeline-indicator-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))] ring-2 ring-[var(--zui-timeline-indicator-mint-ring,var(--zui-color-mint,#10b98133))] dark:ring-[var(--zui-timeline-indicator-mint-ring-dark,var(--zui-color-mint-dark,#6ee7b740))]",
  ocean:
    "border-[color:var(--zui-timeline-indicator-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-timeline-indicator-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-timeline-indicator-ocean-bg,var(--zui-color-ocean,#0284c714))] dark:bg-[var(--zui-timeline-indicator-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf824))] text-[color:var(--zui-timeline-indicator-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:text-[color:var(--zui-timeline-indicator-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))] ring-2 ring-[var(--zui-timeline-indicator-ocean-ring,var(--zui-color-ocean,#0284c733))] dark:ring-[var(--zui-timeline-indicator-ocean-ring-dark,var(--zui-color-ocean-dark,#38bdf840))]",
  sapphire:
    "border-[color:var(--zui-timeline-indicator-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-timeline-indicator-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-timeline-indicator-sapphire-bg,var(--zui-color-sapphire,#1d4ed814))] dark:bg-[var(--zui-timeline-indicator-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa24))] text-[color:var(--zui-timeline-indicator-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:text-[color:var(--zui-timeline-indicator-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))] ring-2 ring-[var(--zui-timeline-indicator-sapphire-ring,var(--zui-color-sapphire,#1d4ed833))] dark:ring-[var(--zui-timeline-indicator-sapphire-ring-dark,var(--zui-color-sapphire-dark,#60a5fa40))]",
  lavender:
    "border-[color:var(--zui-timeline-indicator-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-timeline-indicator-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-timeline-indicator-lavender-bg,var(--zui-color-lavender,#8b5cf614))] dark:bg-[var(--zui-timeline-indicator-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa24))] text-[color:var(--zui-timeline-indicator-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:text-[color:var(--zui-timeline-indicator-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))] ring-2 ring-[var(--zui-timeline-indicator-lavender-ring,var(--zui-color-lavender,#8b5cf633))] dark:ring-[var(--zui-timeline-indicator-lavender-ring-dark,var(--zui-color-lavender-dark,#a78bfa40))]",
  ruby: "border-[color:var(--zui-timeline-indicator-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-timeline-indicator-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-timeline-indicator-ruby-bg,var(--zui-color-ruby,#be123c14))] dark:bg-[var(--zui-timeline-indicator-ruby-bg-dark,var(--zui-color-ruby-dark,#fb718524))] text-[color:var(--zui-timeline-indicator-ruby-fg,var(--zui-color-ruby,#be123c))] dark:text-[color:var(--zui-timeline-indicator-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))] ring-2 ring-[var(--zui-timeline-indicator-ruby-ring,var(--zui-color-ruby,#be123c33))] dark:ring-[var(--zui-timeline-indicator-ruby-ring-dark,var(--zui-color-ruby-dark,#fb718540))]",
  red: "border-[color:var(--zui-timeline-indicator-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-timeline-indicator-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-timeline-indicator-red-bg,var(--zui-color-red,#dc262614))] dark:bg-[var(--zui-timeline-indicator-red-bg-dark,var(--zui-color-red-dark,#ef444424))] text-[color:var(--zui-timeline-indicator-red-fg,var(--zui-color-red,#dc2626))] dark:text-[color:var(--zui-timeline-indicator-red-fg-dark,var(--zui-color-red-dark,#ef4444))] ring-2 ring-[var(--zui-timeline-indicator-red-ring,var(--zui-color-red,#dc262633))] dark:ring-[var(--zui-timeline-indicator-red-ring-dark,var(--zui-color-red-dark,#ef444440))]",
  slate:
    "border-[color:var(--zui-timeline-indicator-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-timeline-indicator-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-timeline-indicator-slate-bg,var(--zui-color-slate,#47556914))] dark:bg-[var(--zui-timeline-indicator-slate-bg-dark,var(--zui-color-slate-dark,#64748b24))] text-[color:var(--zui-timeline-indicator-slate-fg,var(--zui-color-slate,#475569))] dark:text-[color:var(--zui-timeline-indicator-slate-fg-dark,var(--zui-color-slate-dark,#64748b))] ring-2 ring-[var(--zui-timeline-indicator-slate-ring,var(--zui-color-slate,#47556933))] dark:ring-[var(--zui-timeline-indicator-slate-ring-dark,var(--zui-color-slate-dark,#64748b40))]",
  zinc: "border-[color:var(--zui-timeline-indicator-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-timeline-indicator-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-timeline-indicator-zinc-bg,var(--zui-color-zinc,#52525b14))] dark:bg-[var(--zui-timeline-indicator-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a24))] text-[color:var(--zui-timeline-indicator-zinc-fg,var(--zui-color-zinc,#52525b))] dark:text-[color:var(--zui-timeline-indicator-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))] ring-2 ring-[var(--zui-timeline-indicator-zinc-ring,var(--zui-color-zinc,#52525b33))] dark:ring-[var(--zui-timeline-indicator-zinc-ring-dark,var(--zui-color-zinc-dark,#71717a40))]",
  stone:
    "border-[color:var(--zui-timeline-indicator-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-timeline-indicator-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-timeline-indicator-stone-bg,var(--zui-color-stone,#57534e14))] dark:bg-[var(--zui-timeline-indicator-stone-bg-dark,var(--zui-color-stone-dark,#78716c24))] text-[color:var(--zui-timeline-indicator-stone-fg,var(--zui-color-stone,#57534e))] dark:text-[color:var(--zui-timeline-indicator-stone-fg-dark,var(--zui-color-stone-dark,#78716c))] ring-2 ring-[var(--zui-timeline-indicator-stone-ring,var(--zui-color-stone,#57534e33))] dark:ring-[var(--zui-timeline-indicator-stone-ring-dark,var(--zui-color-stone-dark,#78716c40))]",
  royal:
    "border-[color:var(--zui-timeline-indicator-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-timeline-indicator-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-timeline-indicator-royal-bg,var(--zui-color-royal,#4338ca14))] dark:bg-[var(--zui-timeline-indicator-royal-bg-dark,var(--zui-color-royal-dark,#818cf824))] text-[color:var(--zui-timeline-indicator-royal-fg,var(--zui-color-royal,#4338ca))] dark:text-[color:var(--zui-timeline-indicator-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))] ring-2 ring-[var(--zui-timeline-indicator-royal-ring,var(--zui-color-royal,#4338ca33))] dark:ring-[var(--zui-timeline-indicator-royal-ring-dark,var(--zui-color-royal-dark,#818cf840))]",
  electric:
    "border-[color:var(--zui-timeline-indicator-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-timeline-indicator-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-timeline-indicator-electric-bg,var(--zui-color-electric,#0ea5e914))] dark:bg-[var(--zui-timeline-indicator-electric-bg-dark,var(--zui-color-electric-dark,#38bdf824))] text-[color:var(--zui-timeline-indicator-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:text-[color:var(--zui-timeline-indicator-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))] ring-2 ring-[var(--zui-timeline-indicator-electric-ring,var(--zui-color-electric,#0ea5e933))] dark:ring-[var(--zui-timeline-indicator-electric-ring-dark,var(--zui-color-electric-dark,#38bdf840))]",
  forest:
    "border-[color:var(--zui-timeline-indicator-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-timeline-indicator-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-timeline-indicator-forest-bg,var(--zui-color-forest,#16653414))] dark:bg-[var(--zui-timeline-indicator-forest-bg-dark,var(--zui-color-forest-dark,#4ade8024))] text-[color:var(--zui-timeline-indicator-forest-fg,var(--zui-color-forest,#166534))] dark:text-[color:var(--zui-timeline-indicator-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))] ring-2 ring-[var(--zui-timeline-indicator-forest-ring,var(--zui-color-forest,#16653433))] dark:ring-[var(--zui-timeline-indicator-forest-ring-dark,var(--zui-color-forest-dark,#4ade8040))]",
  sunset:
    "border-[color:var(--zui-timeline-indicator-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-timeline-indicator-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-timeline-indicator-sunset-bg,var(--zui-color-sunset,#ea580c14))] dark:bg-[var(--zui-timeline-indicator-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c24))] text-[color:var(--zui-timeline-indicator-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:text-[color:var(--zui-timeline-indicator-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))] ring-2 ring-[var(--zui-timeline-indicator-sunset-ring,var(--zui-color-sunset,#ea580c33))] dark:ring-[var(--zui-timeline-indicator-sunset-ring-dark,var(--zui-color-sunset-dark,#fb923c40))]",
  magenta:
    "border-[color:var(--zui-timeline-indicator-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-timeline-indicator-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-timeline-indicator-magenta-bg,var(--zui-color-magenta,#c026d314))] dark:bg-[var(--zui-timeline-indicator-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f924))] text-[color:var(--zui-timeline-indicator-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:text-[color:var(--zui-timeline-indicator-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))] ring-2 ring-[var(--zui-timeline-indicator-magenta-ring,var(--zui-color-magenta,#c026d333))] dark:ring-[var(--zui-timeline-indicator-magenta-ring-dark,var(--zui-color-magenta-dark,#e879f940))]",
  crimson:
    "border-[color:var(--zui-timeline-indicator-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-timeline-indicator-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-timeline-indicator-crimson-bg,var(--zui-color-crimson,#b91c1c14))] dark:bg-[var(--zui-timeline-indicator-crimson-bg-dark,var(--zui-color-crimson-dark,#f8717124))] text-[color:var(--zui-timeline-indicator-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:text-[color:var(--zui-timeline-indicator-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))] ring-2 ring-[var(--zui-timeline-indicator-crimson-ring,var(--zui-color-crimson,#b91c1c33))] dark:ring-[var(--zui-timeline-indicator-crimson-ring-dark,var(--zui-color-crimson-dark,#f8717140))]",
  aqua: "border-[color:var(--zui-timeline-indicator-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-timeline-indicator-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-timeline-indicator-aqua-bg,var(--zui-color-aqua,#0f766e14))] dark:bg-[var(--zui-timeline-indicator-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf24))] text-[color:var(--zui-timeline-indicator-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:text-[color:var(--zui-timeline-indicator-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))] ring-2 ring-[var(--zui-timeline-indicator-aqua-ring,var(--zui-color-aqua,#0f766e33))] dark:ring-[var(--zui-timeline-indicator-aqua-ring-dark,var(--zui-color-aqua-dark,#2dd4bf40))]",
  plum: "border-[color:var(--zui-timeline-indicator-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-timeline-indicator-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-timeline-indicator-plum-bg,var(--zui-color-plum,#7e22ce14))] dark:bg-[var(--zui-timeline-indicator-plum-bg-dark,var(--zui-color-plum-dark,#c084fc24))] text-[color:var(--zui-timeline-indicator-plum-fg,var(--zui-color-plum,#7e22ce))] dark:text-[color:var(--zui-timeline-indicator-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))] ring-2 ring-[var(--zui-timeline-indicator-plum-ring,var(--zui-color-plum,#7e22ce33))] dark:ring-[var(--zui-timeline-indicator-plum-ring-dark,var(--zui-color-plum-dark,#c084fc40))]",
} as const;

export const zuiTimelineIndicatorSizes = {
  sm: "size-5 text-[0.625rem]",
  md: "size-6 text-xs",
  lg: "size-7 text-sm",
} as const;

export const zuiTimelineConnectorBase =
  "pointer-events-none absolute bottom-0 w-px -translate-x-1/2 rounded-full bg-[var(--zui-timeline-connector,var(--zui-border,#0000001f))] dark:bg-[var(--zui-timeline-connector-dark,var(--zui-border-dark,#ffffff1f))]";

export const zuiTimelineConnectorSizes = {
  sm: "left-2.5 top-6",
  md: "left-3 top-7",
  lg: "left-3.5 top-8",
} as const;

export const zuiTimelineContentBase = "min-w-0 flex-1";

export const zuiTimelineContentSizes = {
  sm: "pb-5",
  md: "pb-6",
  lg: "pb-8",
} as const;

export const zuiTimelineTitleBase =
  "font-semibold text-[color:var(--zui-timeline-title-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-timeline-title-fg-dark,var(--zui-brand-fg-dark,#ffffff))]";

export const zuiTimelineTitleSizes = {
  sm: "text-sm",
  md: "text-sm",
  lg: "text-base",
} as const;

export const zuiTimelineDescriptionBase =
  "text-[color:var(--zui-timeline-description-fg,var(--zui-fg-muted,oklch(44.6%_0.03_256.802)))] dark:text-[color:var(--zui-timeline-description-fg-dark,var(--zui-fg-muted-dark,oklch(70.4%_0.04_256.788)))]";

export const zuiTimelineDescriptionSizes = {
  sm: "text-xs",
  md: "text-xs",
  lg: "text-sm",
} as const;
