export const zuiToastViewportBase =
  "fixed z-[60] flex max-h-screen flex-col gap-2 p-4";

export const zuiToastViewportPositions = {
  "top-left": "left-0 top-0 items-start",
  "top-center": "left-1/2 top-0 -translate-x-1/2 items-center",
  "top-right": "right-0 top-0 items-end",
  "bottom-left": "bottom-0 left-0 items-start",
  "bottom-center": "bottom-0 left-1/2 -translate-x-1/2 items-center",
  "bottom-right": "bottom-0 right-0 items-end",
} as const;

export const zuiToastRootBase =
  "pointer-events-auto w-[min(100vw-2rem,380px)] rounded-xl border bg-[var(--zui-toast-root-bg,var(--zui-surface-muted,oklch(98.4%_0.003_247.858)))] dark:bg-[var(--zui-toast-root-bg-dark,var(--zui-surface-muted-dark,oklch(98.4%_0.003_247.858)))] p-4 text-[color:var(--zui-toast-root-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-toast-root-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))] shadow-[var(--zui-toast-root-shadow,var(--zui-shadow,0_8px_24px_rgba(15,23,42,0.12)))] dark:shadow-[var(--zui-toast-root-shadow-dark,var(--zui-shadow-dark,0_18px_48px_rgba(15,23,42,0.45)))]";

export const zuiToastRootAppearances = {
  default:
    "bg-[var(--zui-toast-root-default-bg,var(--zui-surface-muted,oklch(12.9%_0.042_264.695)))] dark:bg-[var(--zui-toast-root-default-bg-dark,var(--zui-surface-muted-dark,oklch(12.9%_0.042_264.695)))] text-[color:var(--zui-toast-root-default-fg,var(--zui-fg,oklch(98.4%_0.003_247.858)))] dark:text-[color:var(--zui-toast-root-default-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.003_247.858)))]",
  success:
    "border-[color:var(--zui-toast-root-success-border,var(--zui-status-success,oklch(69.6%_0.17_162.48_/_0.4)))] dark:border-[color:var(--zui-toast-root-success-border-dark,var(--zui-status-success-dark,oklch(69.6%_0.17_162.48_/_0.4)))] bg-[var(--zui-toast-root-success-bg,var(--zui-status-success,oklch(26.2%_0.051_172.552)))] dark:bg-[var(--zui-toast-root-success-bg-dark,var(--zui-status-success-dark,oklch(26.2%_0.051_172.552)))] text-[color:var(--zui-toast-root-success-fg,var(--zui-fg,oklch(97.9%_0.021_166.113)))] dark:text-[color:var(--zui-toast-root-success-fg-dark,var(--zui-fg-dark,oklch(97.9%_0.021_166.113)))]",
  warning:
    "border-[color:var(--zui-toast-root-warning-border,var(--zui-status-warning,oklch(76.9%_0.188_70.08_/_0.4)))] dark:border-[color:var(--zui-toast-root-warning-border-dark,var(--zui-status-warning-dark,oklch(76.9%_0.188_70.08_/_0.4)))] bg-[var(--zui-toast-root-warning-bg,var(--zui-status-warning,oklch(27.9%_0.077_45.635)))] dark:bg-[var(--zui-toast-root-warning-bg-dark,var(--zui-status-warning-dark,oklch(27.9%_0.077_45.635)))] text-[color:var(--zui-toast-root-warning-fg,var(--zui-fg,oklch(98.7%_0.022_95.277)))] dark:text-[color:var(--zui-toast-root-warning-fg-dark,var(--zui-fg-dark,oklch(98.7%_0.022_95.277)))]",
  error:
    "border-[color:var(--zui-toast-root-error-border,var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.5)))] dark:border-[color:var(--zui-toast-root-error-border-dark,var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.5)))] bg-[var(--zui-toast-root-error-bg,var(--zui-status-error,oklch(27.1%_0.105_12.094)))] dark:bg-[var(--zui-toast-root-error-bg-dark,var(--zui-status-error-dark,oklch(27.1%_0.105_12.094)))] text-[color:var(--zui-toast-root-error-fg,var(--zui-fg,oklch(96.9%_0.015_12.422)))] dark:text-[color:var(--zui-toast-root-error-fg-dark,var(--zui-fg-dark,oklch(96.9%_0.015_12.422)))]",
  info: "border-[color:var(--zui-toast-root-info-border,var(--zui-status-info,oklch(68.5%_0.169_237.323_/_0.4)))] dark:border-[color:var(--zui-toast-root-info-border-dark,var(--zui-status-info-dark,oklch(68.5%_0.169_237.323_/_0.4)))] bg-[var(--zui-toast-root-info-bg,var(--zui-status-info,oklch(29.3%_0.066_243.157)))] dark:bg-[var(--zui-toast-root-info-bg-dark,var(--zui-status-info-dark,oklch(29.3%_0.066_243.157)))] text-[color:var(--zui-toast-root-info-fg,var(--zui-brand-fg,oklch(97.7%_0.013_236.62)))] dark:text-[color:var(--zui-toast-root-info-fg-dark,var(--zui-brand-fg-dark,oklch(97.7%_0.013_236.62)))]",
  ghost:
    "border-[color:var(--zui-toast-root-ghost-border,transparent)] dark:border-[color:var(--zui-toast-root-ghost-border-dark,transparent)] bg-[var(--zui-toast-root-ghost-bg,transparent)] dark:bg-[var(--zui-toast-root-ghost-bg-dark,transparent)] text-[color:var(--zui-toast-root-ghost-fg,var(--zui-fg-muted,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-toast-root-ghost-fg-dark,var(--zui-fg-muted-dark,oklch(20.8%_0.042_265.755)))]",
  purple:
    "border-[color:var(--zui-toast-root-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-toast-root-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-[var(--zui-toast-root-purple-bg,var(--zui-color-purple,oklch(29.1%_0.149_302.717)))] dark:bg-[var(--zui-toast-root-purple-bg-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717)))] backdrop-blur-xl text-[color:var(--zui-toast-root-purple-fg,var(--zui-fg,oklch(97.7%_0.014_308.299)))] dark:text-[color:var(--zui-toast-root-purple-fg-dark,var(--zui-fg-dark,oklch(97.7%_0.014_308.299)))]",
  pink: "border-[color:var(--zui-toast-root-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-toast-root-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-[var(--zui-toast-root-pink-bg,var(--zui-color-pink,oklch(28.4%_0.109_3.907)))] dark:bg-[var(--zui-toast-root-pink-bg-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907)))] backdrop-blur-xl text-[color:var(--zui-toast-root-pink-fg,var(--zui-fg,oklch(97.1%_0.014_343.198)))] dark:text-[color:var(--zui-toast-root-pink-fg-dark,var(--zui-fg-dark,oklch(97.1%_0.014_343.198)))]",
  orange:
    "border-[color:var(--zui-toast-root-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-toast-root-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-[var(--zui-toast-root-orange-bg,var(--zui-color-orange,oklch(26.6%_0.079_36.259)))] dark:bg-[var(--zui-toast-root-orange-bg-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259)))] backdrop-blur-xl text-[color:var(--zui-toast-root-orange-fg,var(--zui-fg,oklch(98%_0.016_73.684)))] dark:text-[color:var(--zui-toast-root-orange-fg-dark,var(--zui-fg-dark,oklch(98%_0.016_73.684)))]",
  yellow:
    "border-[color:var(--zui-toast-root-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-toast-root-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-[var(--zui-toast-root-yellow-bg,var(--zui-color-yellow,oklch(28.6%_0.066_53.813)))] dark:bg-[var(--zui-toast-root-yellow-bg-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813)))] backdrop-blur-xl text-[color:var(--zui-toast-root-yellow-fg,var(--zui-fg,oklch(98.7%_0.026_102.212)))] dark:text-[color:var(--zui-toast-root-yellow-fg-dark,var(--zui-fg-dark,oklch(98.7%_0.026_102.212)))]",
  teal: "border-[color:var(--zui-toast-root-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-toast-root-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-[var(--zui-toast-root-teal-bg,var(--zui-color-teal,oklch(27.7%_0.046_192.524)))] dark:bg-[var(--zui-toast-root-teal-bg-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524)))] backdrop-blur-xl text-[color:var(--zui-toast-root-teal-fg,var(--zui-fg,oklch(98.4%_0.014_180.72)))] dark:text-[color:var(--zui-toast-root-teal-fg-dark,var(--zui-fg-dark,oklch(98.4%_0.014_180.72)))]",
  indigo:
    "border-[color:var(--zui-toast-root-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-toast-root-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-[var(--zui-toast-root-indigo-bg,var(--zui-color-indigo,oklch(25.7%_0.09_281.288)))] dark:bg-[var(--zui-toast-root-indigo-bg-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288)))] backdrop-blur-xl text-[color:var(--zui-toast-root-indigo-fg,var(--zui-fg,oklch(96.2%_0.018_272.314)))] dark:text-[color:var(--zui-toast-root-indigo-fg-dark,var(--zui-fg-dark,oklch(96.2%_0.018_272.314)))]",
  emerald:
    "border-[color:var(--zui-toast-root-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-toast-root-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] bg-[var(--zui-toast-root-emerald-bg,var(--zui-color-emerald,oklch(26.2%_0.051_172.552)))] dark:bg-[var(--zui-toast-root-emerald-bg-dark,var(--zui-color-emerald-dark,oklch(26.2%_0.051_172.552)))] backdrop-blur-xl text-[color:var(--zui-toast-root-emerald-fg,var(--zui-fg,oklch(97.9%_0.021_166.113)))] dark:text-[color:var(--zui-toast-root-emerald-fg-dark,var(--zui-fg-dark,oklch(97.9%_0.021_166.113)))]",
  gray: "border-[color:var(--zui-toast-root-gray-border,var(--zui-color-gray,oklch(27.8%_0.033_256.848)))] dark:border-[color:var(--zui-toast-root-gray-border-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802)))] bg-[var(--zui-toast-root-gray-bg,var(--zui-color-gray,oklch(13%_0.028_261.692)))] dark:bg-[var(--zui-toast-root-gray-bg-dark,var(--zui-color-gray-dark,oklch(13%_0.028_261.692)))] backdrop-blur-xl text-[color:var(--zui-toast-root-gray-fg,var(--zui-fg,oklch(98.5%_0.002_247.839)))] dark:text-[color:var(--zui-toast-root-gray-fg-dark,var(--zui-fg-dark,oklch(98.5%_0.002_247.839)))]",
  amber:
    "border-[color:var(--zui-toast-root-amber-border,var(--zui-color-amber,oklch(47.3%_0.137_46.201)))] dark:border-[color:var(--zui-toast-root-amber-border-dark,var(--zui-color-amber-dark,oklch(66.6%_0.179_58.318)))] bg-[var(--zui-toast-root-amber-bg,var(--zui-color-amber,oklch(27.9%_0.077_45.635)))] dark:bg-[var(--zui-toast-root-amber-bg-dark,var(--zui-color-amber-dark,oklch(27.9%_0.077_45.635)))] backdrop-blur-xl text-[color:var(--zui-toast-root-amber-fg,var(--zui-fg,oklch(98.7%_0.022_95.277)))] dark:text-[color:var(--zui-toast-root-amber-fg-dark,var(--zui-fg-dark,oklch(98.7%_0.022_95.277)))]",
  violet:
    "border-[color:var(--zui-toast-root-violet-border,var(--zui-color-violet,oklch(43.2%_0.232_292.759)))] dark:border-[color:var(--zui-toast-root-violet-border-dark,var(--zui-color-violet-dark,oklch(54.1%_0.281_293.009)))] bg-[var(--zui-toast-root-violet-bg,var(--zui-color-violet,oklch(28.3%_0.141_291.089)))] dark:bg-[var(--zui-toast-root-violet-bg-dark,var(--zui-color-violet-dark,oklch(28.3%_0.141_291.089)))] backdrop-blur-xl text-[color:var(--zui-toast-root-violet-fg,var(--zui-fg,oklch(96.9%_0.016_293.756)))] dark:text-[color:var(--zui-toast-root-violet-fg-dark,var(--zui-fg-dark,oklch(96.9%_0.016_293.756)))]",
  "gradient-blue":
    "border-[color:var(--zui-toast-root-gradient-blue-border,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:border-[color:var(--zui-toast-root-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-blue-from,var(--zui-color-blue,oklch(97%_0.014_254.604)))] dark:from-[var(--zui-toast-root-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(28.2%_0.091_267.935_/_0.7)))] to-[var(--zui-toast-root-gradient-blue-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-toast-root-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl",
  "gradient-green":
    "border-[color:var(--zui-toast-root-gradient-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:border-[color:var(--zui-toast-root-gradient-green-border-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-green-from,var(--zui-color-green,oklch(98.2%_0.018_155.826)))] dark:from-[var(--zui-toast-root-gradient-green-from-dark,var(--zui-color-green-dark,oklch(26.6%_0.065_152.934_/_0.7)))] to-[var(--zui-toast-root-gradient-green-to,var(--zui-color-lime,oklch(98.6%_0.031_120.757)))] dark:to-[var(--zui-toast-root-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(27.4%_0.072_132.109_/_0.7)))] backdrop-blur-xl",
  "gradient-red":
    "border-[color:var(--zui-toast-root-gradient-red-border,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:border-[color:var(--zui-toast-root-gradient-red-border-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-red-from,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:from-[var(--zui-toast-root-gradient-red-from-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] to-[var(--zui-toast-root-gradient-red-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-toast-root-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl",
  "gradient-yellow":
    "border-[color:var(--zui-toast-root-gradient-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-toast-root-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-yellow-from,var(--zui-color-yellow,oklch(98.7%_0.026_102.212)))] dark:from-[var(--zui-toast-root-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(28.6%_0.066_53.813_/_0.7)))] to-[var(--zui-toast-root-gradient-yellow-to,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:to-[var(--zui-toast-root-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] backdrop-blur-xl",
  "gradient-purple":
    "border-[color:var(--zui-toast-root-gradient-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-toast-root-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-purple-from,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:from-[var(--zui-toast-root-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] to-[var(--zui-toast-root-gradient-purple-to,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:to-[var(--zui-toast-root-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] backdrop-blur-xl",
  "gradient-teal":
    "border-[color:var(--zui-toast-root-gradient-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-toast-root-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-teal-from,var(--zui-color-teal,oklch(98.4%_0.014_180.72)))] dark:from-[var(--zui-toast-root-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(27.7%_0.046_192.524_/_0.7)))] to-[var(--zui-toast-root-gradient-teal-to,var(--zui-color-cyan,oklch(98.4%_0.019_200.873)))] dark:to-[var(--zui-toast-root-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(30.2%_0.056_229.695_/_0.7)))] backdrop-blur-xl",
  "gradient-indigo":
    "border-[color:var(--zui-toast-root-gradient-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-toast-root-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-indigo-from,var(--zui-color-indigo,oklch(96.2%_0.018_272.314)))] dark:from-[var(--zui-toast-root-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(25.7%_0.09_281.288_/_0.7)))] to-[var(--zui-toast-root-gradient-indigo-to,var(--zui-color-purple,oklch(97.7%_0.014_308.299)))] dark:to-[var(--zui-toast-root-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(29.1%_0.149_302.717_/_0.7)))] backdrop-blur-xl",
  "gradient-pink":
    "border-[color:var(--zui-toast-root-gradient-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-toast-root-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-pink-from,var(--zui-color-pink,oklch(97.1%_0.014_343.198)))] dark:from-[var(--zui-toast-root-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(28.4%_0.109_3.907_/_0.7)))] to-[var(--zui-toast-root-gradient-pink-to,var(--zui-color-rose,oklch(96.9%_0.015_12.422)))] dark:to-[var(--zui-toast-root-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(27.1%_0.105_12.094_/_0.7)))] backdrop-blur-xl",
  "gradient-orange":
    "border-[color:var(--zui-toast-root-gradient-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-toast-root-gradient-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] bg-linear-to-r from-[var(--zui-toast-root-gradient-orange-from,var(--zui-color-orange,oklch(98%_0.016_73.684)))] dark:from-[var(--zui-toast-root-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(26.6%_0.079_36.259_/_0.7)))] to-[var(--zui-toast-root-gradient-orange-to,var(--zui-color-red,oklch(97.1%_0.013_17.38)))] dark:to-[var(--zui-toast-root-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(25.8%_0.092_26.042_/_0.7)))] backdrop-blur-xl",
  blue: "border border-[color:var(--zui-toast-root-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-toast-root-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-toast-root-blue-bg,var(--zui-color-blue,#2563eb14))] dark:bg-[var(--zui-toast-root-blue-bg-dark,var(--zui-color-blue-dark,#3b82f624))] text-[color:var(--zui-toast-root-blue-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-blue-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  cyan: "border border-[color:var(--zui-toast-root-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-toast-root-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-toast-root-cyan-bg,var(--zui-color-cyan,#0891b214))] dark:bg-[var(--zui-toast-root-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee24))] text-[color:var(--zui-toast-root-cyan-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-cyan-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  green:
    "border border-[color:var(--zui-toast-root-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-toast-root-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-toast-root-green-bg,var(--zui-color-green,#16a34a14))] dark:bg-[var(--zui-toast-root-green-bg-dark,var(--zui-color-green-dark,#22c55e24))] text-[color:var(--zui-toast-root-green-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-green-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  lime: "border border-[color:var(--zui-toast-root-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-toast-root-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-toast-root-lime-bg,var(--zui-color-lime,#65a30d14))] dark:bg-[var(--zui-toast-root-lime-bg-dark,var(--zui-color-lime-dark,#a3e63524))] text-[color:var(--zui-toast-root-lime-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-lime-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  mint: "border border-[color:var(--zui-toast-root-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-toast-root-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-toast-root-mint-bg,var(--zui-color-mint,#10b98114))] dark:bg-[var(--zui-toast-root-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b724))] text-[color:var(--zui-toast-root-mint-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-mint-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  ocean:
    "border border-[color:var(--zui-toast-root-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-toast-root-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-toast-root-ocean-bg,var(--zui-color-ocean,#0284c714))] dark:bg-[var(--zui-toast-root-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf824))] text-[color:var(--zui-toast-root-ocean-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-ocean-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  sapphire:
    "border border-[color:var(--zui-toast-root-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-toast-root-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-toast-root-sapphire-bg,var(--zui-color-sapphire,#1d4ed814))] dark:bg-[var(--zui-toast-root-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa24))] text-[color:var(--zui-toast-root-sapphire-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-sapphire-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  lavender:
    "border border-[color:var(--zui-toast-root-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-toast-root-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-toast-root-lavender-bg,var(--zui-color-lavender,#8b5cf614))] dark:bg-[var(--zui-toast-root-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa24))] text-[color:var(--zui-toast-root-lavender-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-lavender-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  ruby: "border border-[color:var(--zui-toast-root-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-toast-root-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-toast-root-ruby-bg,var(--zui-color-ruby,#be123c14))] dark:bg-[var(--zui-toast-root-ruby-bg-dark,var(--zui-color-ruby-dark,#fb718524))] text-[color:var(--zui-toast-root-ruby-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-ruby-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  red: "border border-[color:var(--zui-toast-root-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-toast-root-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-toast-root-red-bg,var(--zui-color-red,#dc262614))] dark:bg-[var(--zui-toast-root-red-bg-dark,var(--zui-color-red-dark,#ef444424))] text-[color:var(--zui-toast-root-red-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-red-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  slate:
    "border border-[color:var(--zui-toast-root-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-toast-root-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-toast-root-slate-bg,var(--zui-color-slate,#47556914))] dark:bg-[var(--zui-toast-root-slate-bg-dark,var(--zui-color-slate-dark,#64748b24))] text-[color:var(--zui-toast-root-slate-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-slate-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  zinc: "border border-[color:var(--zui-toast-root-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-toast-root-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-toast-root-zinc-bg,var(--zui-color-zinc,#52525b14))] dark:bg-[var(--zui-toast-root-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a24))] text-[color:var(--zui-toast-root-zinc-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-zinc-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  stone:
    "border border-[color:var(--zui-toast-root-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-toast-root-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-toast-root-stone-bg,var(--zui-color-stone,#57534e14))] dark:bg-[var(--zui-toast-root-stone-bg-dark,var(--zui-color-stone-dark,#78716c24))] text-[color:var(--zui-toast-root-stone-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-stone-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  royal:
    "border border-[color:var(--zui-toast-root-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-toast-root-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-toast-root-royal-bg,var(--zui-color-royal,#4338ca14))] dark:bg-[var(--zui-toast-root-royal-bg-dark,var(--zui-color-royal-dark,#818cf824))] text-[color:var(--zui-toast-root-royal-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-royal-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  electric:
    "border border-[color:var(--zui-toast-root-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-toast-root-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-toast-root-electric-bg,var(--zui-color-electric,#0ea5e914))] dark:bg-[var(--zui-toast-root-electric-bg-dark,var(--zui-color-electric-dark,#38bdf824))] text-[color:var(--zui-toast-root-electric-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-electric-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  forest:
    "border border-[color:var(--zui-toast-root-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-toast-root-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-toast-root-forest-bg,var(--zui-color-forest,#16653414))] dark:bg-[var(--zui-toast-root-forest-bg-dark,var(--zui-color-forest-dark,#4ade8024))] text-[color:var(--zui-toast-root-forest-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-forest-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  sunset:
    "border border-[color:var(--zui-toast-root-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-toast-root-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-toast-root-sunset-bg,var(--zui-color-sunset,#ea580c14))] dark:bg-[var(--zui-toast-root-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c24))] text-[color:var(--zui-toast-root-sunset-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-sunset-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  magenta:
    "border border-[color:var(--zui-toast-root-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-toast-root-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-toast-root-magenta-bg,var(--zui-color-magenta,#c026d314))] dark:bg-[var(--zui-toast-root-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f924))] text-[color:var(--zui-toast-root-magenta-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-magenta-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  crimson:
    "border border-[color:var(--zui-toast-root-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-toast-root-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-toast-root-crimson-bg,var(--zui-color-crimson,#b91c1c14))] dark:bg-[var(--zui-toast-root-crimson-bg-dark,var(--zui-color-crimson-dark,#f8717124))] text-[color:var(--zui-toast-root-crimson-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-crimson-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  aqua: "border border-[color:var(--zui-toast-root-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-toast-root-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-toast-root-aqua-bg,var(--zui-color-aqua,#0f766e14))] dark:bg-[var(--zui-toast-root-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf24))] text-[color:var(--zui-toast-root-aqua-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-aqua-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  plum: "border border-[color:var(--zui-toast-root-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-toast-root-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-toast-root-plum-bg,var(--zui-color-plum,#7e22ce14))] dark:bg-[var(--zui-toast-root-plum-bg-dark,var(--zui-color-plum-dark,#c084fc24))] text-[color:var(--zui-toast-root-plum-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-toast-root-plum-fg-dark,var(--zui-fg-dark,#f8fafc))]",
} as const;

export const zuiToastRootSizes = {
  sm: "p-3 text-xs",
  md: "p-4 text-sm",
  lg: "p-5 text-base",
} as const;
