export const zuiToggleTrackBase =
  "relative inline-flex shrink-0 cursor-pointer rounded-full border border-[color:var(--zui-toggle-track-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-toggle-track-border-dark,var(--zui-border-dark,#ffffff1a))] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-toggle-track-ring-focus,var(--zui-focus-ring,oklch(44.6%_0.043_257.281)))] dark:focus-visible:ring-[var(--zui-toggle-track-ring-focus-dark,var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894)))] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--zui-toggle-track-ring-offset-focus,var(--zui-ring-offset,oklch(98.4%_0.003_247.858)))] dark:focus-visible:ring-offset-[var(--zui-toggle-track-ring-offset-focus-dark,var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695)))] data-[state=checked]:border-[color:var(--zui-toggle-track-border-checked,var(--zui-border,oklch(71.5%_0.143_215.221_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-border-checked-dark,var(--zui-border-dark,oklch(71.5%_0.143_215.221_/_0.4)))] disabled:cursor-not-allowed disabled:opacity-50";

export const zuiToggleTrackSizes = {
  sm: "h-5 w-9",
  md: "h-6 w-11",
  lg: "h-7 w-[3.25rem]",
} as const;

export const zuiToggleTrackAppearances = {
  default:
    "data-[state=checked]:bg-[var(--zui-toggle-track-default-bg-checked,var(--zui-brand,oklch(78.9%_0.154_211.53_/_0.7)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-default-bg-checked-dark,var(--zui-brand-dark,oklch(60.9%_0.126_221.723_/_0.9)))]",
  success:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-success-border-checked,var(--zui-status-success,oklch(69.6%_0.17_162.48_/_0.7)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-success-border-checked-dark,var(--zui-status-success-dark,oklch(69.6%_0.17_162.48_/_0.7)))] data-[state=checked]:bg-[var(--zui-toggle-track-success-bg-checked,var(--zui-status-success,oklch(76.5%_0.177_163.223_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-success-bg-checked-dark,var(--zui-status-success-dark,oklch(59.6%_0.145_163.225_/_0.8)))]",
  destructive:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-destructive-border-checked,var(--zui-status-error,oklch(64.5%_0.246_16.439_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-destructive-border-checked-dark,var(--zui-status-error-dark,oklch(64.5%_0.246_16.439_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-destructive-bg-checked,var(--zui-status-error,oklch(71.2%_0.194_13.428_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-destructive-bg-checked-dark,var(--zui-status-error-dark,oklch(58.6%_0.253_17.585_/_0.8)))]",
  neutral:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-neutral-border-checked,var(--zui-border,oklch(55.4%_0.046_257.417_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-neutral-border-checked-dark,var(--zui-border-dark,oklch(70.4%_0.04_256.788_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-neutral-bg-checked,var(--zui-surface-muted,oklch(70.4%_0.04_256.788_/_0.9)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-neutral-bg-checked-dark,var(--zui-surface-muted-dark,oklch(44.6%_0.043_257.281_/_0.9)))]",
  indigo:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-indigo-border-checked,var(--zui-color-indigo,oklch(58.5%_0.233_277.117_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-indigo-border-checked-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-indigo-bg-checked,var(--zui-color-indigo,oklch(67.3%_0.182_276.935_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-indigo-bg-checked-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966_/_0.8)))]",
  purple:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-purple-border-checked,var(--zui-color-purple,oklch(62.7%_0.265_303.9_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-purple-border-checked-dark,var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-purple-bg-checked,var(--zui-color-purple,oklch(71.4%_0.203_305.504_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-purple-bg-checked-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321_/_0.8)))]",
  pink: "data-[state=checked]:border-[color:var(--zui-toggle-track-pink-border-checked,var(--zui-color-pink,oklch(65.6%_0.241_354.308_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-pink-border-checked-dark,var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-pink-bg-checked,var(--zui-color-pink,oklch(71.8%_0.202_349.761_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-pink-bg-checked-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584_/_0.8)))]",
  orange:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-orange-border-checked,var(--zui-color-orange,oklch(70.5%_0.213_47.604_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-orange-border-checked-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-orange-bg-checked,var(--zui-color-orange,oklch(75%_0.183_55.934_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-orange-bg-checked-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116_/_0.8)))]",
  yellow:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-yellow-border-checked,var(--zui-color-yellow,oklch(79.5%_0.184_86.047_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-yellow-border-checked-dark,var(--zui-color-yellow-dark,oklch(79.5%_0.184_86.047_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-yellow-bg-checked,var(--zui-color-yellow,oklch(85.2%_0.199_91.936_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-yellow-bg-checked-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834_/_0.8)))]",
  green:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-green-border-checked,var(--zui-color-green,oklch(72.3%_0.219_149.579_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-green-border-checked-dark,var(--zui-color-green-dark,oklch(72.3%_0.219_149.579_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-green-bg-checked,var(--zui-color-green,oklch(79.2%_0.209_151.711_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-green-bg-checked-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214_/_0.8)))]",
  teal: "data-[state=checked]:border-[color:var(--zui-toggle-track-teal-border-checked,var(--zui-color-teal,oklch(70.4%_0.14_182.503_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-teal-border-checked-dark,var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-teal-bg-checked,var(--zui-color-teal,oklch(77.7%_0.152_181.912_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-teal-bg-checked-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704_/_0.8)))]",
  cyan: "data-[state=checked]:border-[color:var(--zui-toggle-track-cyan-border-checked,var(--zui-color-cyan,oklch(71.5%_0.143_215.221_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-cyan-border-checked-dark,var(--zui-color-cyan-dark,oklch(71.5%_0.143_215.221_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-cyan-bg-checked,var(--zui-color-cyan,oklch(78.9%_0.154_211.53_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-cyan-bg-checked-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723_/_0.8)))]",
  lime: "data-[state=checked]:border-[color:var(--zui-toggle-track-lime-border-checked,var(--zui-color-lime,oklch(76.8%_0.233_130.85_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-lime-border-checked-dark,var(--zui-color-lime-dark,oklch(76.8%_0.233_130.85_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-lime-bg-checked,var(--zui-color-lime,oklch(84.1%_0.238_128.85_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-lime-bg-checked-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684_/_0.8)))]",
  emerald:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-emerald-border-checked,var(--zui-color-emerald,oklch(69.6%_0.17_162.48_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-emerald-border-checked-dark,var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-emerald-bg-checked,var(--zui-color-emerald,oklch(76.5%_0.177_163.223_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-emerald-bg-checked-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225_/_0.8)))]",
  rose: "data-[state=checked]:border-[color:var(--zui-toggle-track-rose-border-checked,var(--zui-color-rose,oklch(64.5%_0.246_16.439_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-rose-border-checked-dark,var(--zui-color-rose-dark,oklch(64.5%_0.246_16.439_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-rose-bg-checked,var(--zui-color-rose,oklch(71.2%_0.194_13.428_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-rose-bg-checked-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585_/_0.8)))]",
  slate:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-slate-border-checked,var(--zui-color-slate,oklch(55.4%_0.046_257.417_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-slate-border-checked-dark,var(--zui-color-slate-dark,oklch(70.4%_0.04_256.788_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-slate-bg-checked,var(--zui-color-slate,oklch(70.4%_0.04_256.788_/_0.9)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-slate-bg-checked-dark,var(--zui-color-slate-dark,oklch(44.6%_0.043_257.281_/_0.9)))]",
  zinc: "data-[state=checked]:border-[color:var(--zui-toggle-track-zinc-border-checked,var(--zui-color-zinc,oklch(70.5%_0.015_286.067_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-zinc-border-checked-dark,var(--zui-color-zinc-dark,oklch(70.5%_0.015_286.067_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-zinc-bg-checked,var(--zui-color-zinc,oklch(44.2%_0.017_285.786_/_0.9)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-zinc-bg-checked-dark,var(--zui-color-zinc-dark,oklch(44.2%_0.017_285.786_/_0.9)))]",
  gray: "data-[state=checked]:border-[color:var(--zui-toggle-track-gray-border-checked,var(--zui-color-gray,oklch(70.7%_0.022_261.325_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-gray-border-checked-dark,var(--zui-color-gray-dark,oklch(70.7%_0.022_261.325_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-gray-bg-checked,var(--zui-color-gray,oklch(70.7%_0.022_261.325_/_0.8)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-gray-bg-checked-dark,var(--zui-color-gray-dark,oklch(44.6%_0.03_256.802_/_0.9)))]",
  stone:
    "bg-[var(--zui-toggle-track-stone-bg,var(--zui-color-stone,oklch(86.9%_0.005_56.366)))] dark:bg-[var(--zui-toggle-track-stone-bg-dark,var(--zui-color-stone-dark,oklch(86.9%_0.005_56.366)))] data-[state=checked]:border-[color:var(--zui-toggle-track-stone-border-checked,var(--zui-color-stone,oklch(70.9%_0.01_56.259_/_0.4)))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-stone-border-checked-dark,var(--zui-color-stone-dark,oklch(70.9%_0.01_56.259_/_0.4)))] data-[state=checked]:bg-[var(--zui-toggle-track-stone-bg-checked,var(--zui-color-stone,oklch(44.4%_0.011_73.639_/_0.9)))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-stone-bg-checked-dark,var(--zui-color-stone-dark,oklch(44.4%_0.011_73.639_/_0.9)))]",
  "gradient-blue":
    "bg-[var(--zui-toggle-track-gradient-blue-bg,var(--zui-color-blue,oklch(80.9%_0.105_251.813)))] dark:bg-[var(--zui-toggle-track-gradient-blue-bg-dark,var(--zui-color-blue-dark,oklch(80.9%_0.105_251.813)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-toggle-track-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] to-[var(--zui-toggle-track-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-toggle-track-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  "gradient-green":
    "bg-[var(--zui-toggle-track-gradient-green-bg,var(--zui-color-green,oklch(87.1%_0.15_154.449)))] dark:bg-[var(--zui-toggle-track-gradient-green-bg-dark,var(--zui-color-green-dark,oklch(87.1%_0.15_154.449)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-toggle-track-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] to-[var(--zui-toggle-track-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-toggle-track-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))]",
  "gradient-red":
    "bg-[var(--zui-toggle-track-gradient-red-bg,var(--zui-color-red,oklch(80.8%_0.114_19.571)))] dark:bg-[var(--zui-toggle-track-gradient-red-bg-dark,var(--zui-color-red-dark,oklch(80.8%_0.114_19.571)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-toggle-track-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] to-[var(--zui-toggle-track-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-toggle-track-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  "gradient-yellow":
    "bg-[var(--zui-toggle-track-gradient-yellow-bg,var(--zui-color-yellow,oklch(90.5%_0.182_98.111)))] dark:bg-[var(--zui-toggle-track-gradient-yellow-bg-dark,var(--zui-color-yellow-dark,oklch(90.5%_0.182_98.111)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-toggle-track-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] to-[var(--zui-toggle-track-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-toggle-track-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))]",
  "gradient-purple":
    "bg-[var(--zui-toggle-track-gradient-purple-bg,var(--zui-color-purple,oklch(82.7%_0.119_306.383)))] dark:bg-[var(--zui-toggle-track-gradient-purple-bg-dark,var(--zui-color-purple-dark,oklch(82.7%_0.119_306.383)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-toggle-track-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] to-[var(--zui-toggle-track-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-toggle-track-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))]",
  "gradient-teal":
    "bg-[var(--zui-toggle-track-gradient-teal-bg,var(--zui-color-teal,oklch(85.5%_0.138_181.071)))] dark:bg-[var(--zui-toggle-track-gradient-teal-bg-dark,var(--zui-color-teal-dark,oklch(85.5%_0.138_181.071)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-toggle-track-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] to-[var(--zui-toggle-track-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-toggle-track-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))]",
  "gradient-indigo":
    "bg-[var(--zui-toggle-track-gradient-indigo-bg,var(--zui-color-indigo,oklch(78.5%_0.115_274.713)))] dark:bg-[var(--zui-toggle-track-gradient-indigo-bg-dark,var(--zui-color-indigo-dark,oklch(78.5%_0.115_274.713)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-toggle-track-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] to-[var(--zui-toggle-track-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-toggle-track-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))]",
  "gradient-pink":
    "bg-[var(--zui-toggle-track-gradient-pink-bg,var(--zui-color-pink,oklch(82.3%_0.12_346.018)))] dark:bg-[var(--zui-toggle-track-gradient-pink-bg-dark,var(--zui-color-pink-dark,oklch(82.3%_0.12_346.018)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-toggle-track-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] to-[var(--zui-toggle-track-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-toggle-track-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))]",
  "gradient-orange":
    "bg-[var(--zui-toggle-track-gradient-orange-bg,var(--zui-color-orange,oklch(83.7%_0.128_66.29)))] dark:bg-[var(--zui-toggle-track-gradient-orange-bg-dark,var(--zui-color-orange-dark,oklch(83.7%_0.128_66.29)))] data-[state=checked]:bg-linear-to-r from-[var(--zui-toggle-track-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-toggle-track-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] to-[var(--zui-toggle-track-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-toggle-track-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))]",
  blue: "data-[state=checked]:border-[color:var(--zui-toggle-track-blue-border-checked,var(--zui-color-blue,#2563eb66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-blue-border-checked-dark,var(--zui-color-blue-dark,#3b82f666))] data-[state=checked]:bg-[var(--zui-toggle-track-blue-bg-checked,var(--zui-color-blue,#2563ebcc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-blue-bg-checked-dark,var(--zui-color-blue-dark,#3b82f6cc))]",
  mint: "data-[state=checked]:border-[color:var(--zui-toggle-track-mint-border-checked,var(--zui-color-mint,#10b98166))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-mint-border-checked-dark,var(--zui-color-mint-dark,#6ee7b766))] data-[state=checked]:bg-[var(--zui-toggle-track-mint-bg-checked,var(--zui-color-mint,#10b981cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-mint-bg-checked-dark,var(--zui-color-mint-dark,#6ee7b7cc))]",
  ocean:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-ocean-border-checked,var(--zui-color-ocean,#0284c766))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-ocean-border-checked-dark,var(--zui-color-ocean-dark,#38bdf866))] data-[state=checked]:bg-[var(--zui-toggle-track-ocean-bg-checked,var(--zui-color-ocean,#0284c7cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-ocean-bg-checked-dark,var(--zui-color-ocean-dark,#38bdf8cc))]",
  sapphire:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-sapphire-border-checked,var(--zui-color-sapphire,#1d4ed866))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-sapphire-border-checked-dark,var(--zui-color-sapphire-dark,#60a5fa66))] data-[state=checked]:bg-[var(--zui-toggle-track-sapphire-bg-checked,var(--zui-color-sapphire,#1d4ed8cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-sapphire-bg-checked-dark,var(--zui-color-sapphire-dark,#60a5facc))]",
  lavender:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-lavender-border-checked,var(--zui-color-lavender,#8b5cf666))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-lavender-border-checked-dark,var(--zui-color-lavender-dark,#a78bfa66))] data-[state=checked]:bg-[var(--zui-toggle-track-lavender-bg-checked,var(--zui-color-lavender,#8b5cf6cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-lavender-bg-checked-dark,var(--zui-color-lavender-dark,#a78bfacc))]",
  ruby: "data-[state=checked]:border-[color:var(--zui-toggle-track-ruby-border-checked,var(--zui-color-ruby,#be123c66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-ruby-border-checked-dark,var(--zui-color-ruby-dark,#fb718566))] data-[state=checked]:bg-[var(--zui-toggle-track-ruby-bg-checked,var(--zui-color-ruby,#be123ccc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-ruby-bg-checked-dark,var(--zui-color-ruby-dark,#fb7185cc))]",
  red: "data-[state=checked]:border-[color:var(--zui-toggle-track-red-border-checked,var(--zui-color-red,#dc262666))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-red-border-checked-dark,var(--zui-color-red-dark,#ef444466))] data-[state=checked]:bg-[var(--zui-toggle-track-red-bg-checked,var(--zui-color-red,#dc2626cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-red-bg-checked-dark,var(--zui-color-red-dark,#ef4444cc))]",
  royal:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-royal-border-checked,var(--zui-color-royal,#4338ca66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-royal-border-checked-dark,var(--zui-color-royal-dark,#818cf866))] data-[state=checked]:bg-[var(--zui-toggle-track-royal-bg-checked,var(--zui-color-royal,#4338cacc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-royal-bg-checked-dark,var(--zui-color-royal-dark,#818cf8cc))]",
  electric:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-electric-border-checked,var(--zui-color-electric,#0ea5e966))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-electric-border-checked-dark,var(--zui-color-electric-dark,#38bdf866))] data-[state=checked]:bg-[var(--zui-toggle-track-electric-bg-checked,var(--zui-color-electric,#0ea5e9cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-electric-bg-checked-dark,var(--zui-color-electric-dark,#38bdf8cc))]",
  forest:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-forest-border-checked,var(--zui-color-forest,#16653466))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-forest-border-checked-dark,var(--zui-color-forest-dark,#4ade8066))] data-[state=checked]:bg-[var(--zui-toggle-track-forest-bg-checked,var(--zui-color-forest,#166534cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-forest-bg-checked-dark,var(--zui-color-forest-dark,#4ade80cc))]",
  sunset:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-sunset-border-checked,var(--zui-color-sunset,#ea580c66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-sunset-border-checked-dark,var(--zui-color-sunset-dark,#fb923c66))] data-[state=checked]:bg-[var(--zui-toggle-track-sunset-bg-checked,var(--zui-color-sunset,#ea580ccc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-sunset-bg-checked-dark,var(--zui-color-sunset-dark,#fb923ccc))]",
  magenta:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-magenta-border-checked,var(--zui-color-magenta,#c026d366))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-magenta-border-checked-dark,var(--zui-color-magenta-dark,#e879f966))] data-[state=checked]:bg-[var(--zui-toggle-track-magenta-bg-checked,var(--zui-color-magenta,#c026d3cc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-magenta-bg-checked-dark,var(--zui-color-magenta-dark,#e879f9cc))]",
  crimson:
    "data-[state=checked]:border-[color:var(--zui-toggle-track-crimson-border-checked,var(--zui-color-crimson,#b91c1c66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-crimson-border-checked-dark,var(--zui-color-crimson-dark,#f8717166))] data-[state=checked]:bg-[var(--zui-toggle-track-crimson-bg-checked,var(--zui-color-crimson,#b91c1ccc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-crimson-bg-checked-dark,var(--zui-color-crimson-dark,#f87171cc))]",
  aqua: "data-[state=checked]:border-[color:var(--zui-toggle-track-aqua-border-checked,var(--zui-color-aqua,#0f766e66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-aqua-border-checked-dark,var(--zui-color-aqua-dark,#2dd4bf66))] data-[state=checked]:bg-[var(--zui-toggle-track-aqua-bg-checked,var(--zui-color-aqua,#0f766ecc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-aqua-bg-checked-dark,var(--zui-color-aqua-dark,#2dd4bfcc))]",
  plum: "data-[state=checked]:border-[color:var(--zui-toggle-track-plum-border-checked,var(--zui-color-plum,#7e22ce66))] dark:data-[state=checked]:border-[color:var(--zui-toggle-track-plum-border-checked-dark,var(--zui-color-plum-dark,#c084fc66))] data-[state=checked]:bg-[var(--zui-toggle-track-plum-bg-checked,var(--zui-color-plum,#7e22cecc))] dark:data-[state=checked]:bg-[var(--zui-toggle-track-plum-bg-checked-dark,var(--zui-color-plum-dark,#c084fccc))]",
} as const;

export const zuiToggleThumbBase =
  "pointer-events-none block rounded-full border border-[color:var(--zui-toggle-thumb-border,var(--zui-border,oklch(20.8%_0.042_265.755_/_0.3)))] dark:border-[color:var(--zui-toggle-thumb-border-dark,var(--zui-border-dark,#ffffff1a))] shadow-[var(--zui-toggle-thumb-shadow,var(--zui-shadow,0_1px_2px_rgba(15,23,42,0.12)))] dark:shadow-[var(--zui-toggle-thumb-shadow-dark,var(--zui-shadow-dark,0_1px_2px_rgba(15,23,42,0.35)))] ring-0";

export const zuiToggleThumbSizes = {
  sm: "size-4",
  md: "size-5",
  lg: "size-6",
} as const;

export const zuiToggleThumbColors = {
  default:
    "bg-[var(--zui-toggle-thumb-colors-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-toggle-thumb-colors-default-bg-dark,var(--zui-surface-muted-dark,#ffffff))]",
  success:
    "bg-[var(--zui-toggle-thumb-colors-success-bg,var(--zui-status-success,oklch(69.6%_0.17_162.48)))] dark:bg-[var(--zui-toggle-thumb-colors-success-bg-dark,var(--zui-status-success-dark,oklch(69.6%_0.17_162.48)))]",
  destructive:
    "bg-[var(--zui-toggle-thumb-colors-destructive-bg,var(--zui-status-error,oklch(64.5%_0.246_16.439)))] dark:bg-[var(--zui-toggle-thumb-colors-destructive-bg-dark,var(--zui-status-error-dark,oklch(64.5%_0.246_16.439)))]",
  neutral:
    "bg-[var(--zui-toggle-thumb-colors-neutral-bg,var(--zui-surface-muted,oklch(55.4%_0.046_257.417)))] dark:bg-[var(--zui-toggle-thumb-colors-neutral-bg-dark,var(--zui-surface-muted-dark,oklch(55.4%_0.046_257.417)))]",
  indigo:
    "bg-[var(--zui-toggle-thumb-colors-indigo-bg,var(--zui-color-indigo,oklch(58.5%_0.233_277.117)))] dark:bg-[var(--zui-toggle-thumb-colors-indigo-bg-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)))]",
  purple:
    "bg-[var(--zui-toggle-thumb-colors-purple-bg,var(--zui-color-purple,oklch(62.7%_0.265_303.9)))] dark:bg-[var(--zui-toggle-thumb-colors-purple-bg-dark,var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9)))]",
  pink: "bg-[var(--zui-toggle-thumb-colors-pink-bg,var(--zui-color-pink,oklch(65.6%_0.241_354.308)))] dark:bg-[var(--zui-toggle-thumb-colors-pink-bg-dark,var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308)))]",
  orange:
    "bg-[var(--zui-toggle-thumb-colors-orange-bg,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:bg-[var(--zui-toggle-thumb-colors-orange-bg-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604)))]",
  yellow:
    "bg-[var(--zui-toggle-thumb-colors-yellow-bg,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:bg-[var(--zui-toggle-thumb-colors-yellow-bg-dark,var(--zui-color-yellow-dark,oklch(79.5%_0.184_86.047)))]",
  green:
    "bg-[var(--zui-toggle-thumb-colors-green-bg,var(--zui-color-green,oklch(72.3%_0.219_149.579)))] dark:bg-[var(--zui-toggle-thumb-colors-green-bg-dark,var(--zui-color-green-dark,oklch(72.3%_0.219_149.579)))]",
  teal: "bg-[var(--zui-toggle-thumb-colors-teal-bg,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:bg-[var(--zui-toggle-thumb-colors-teal-bg-dark,var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503)))]",
  cyan: "bg-[var(--zui-toggle-thumb-colors-cyan-bg,var(--zui-color-cyan,oklch(71.5%_0.143_215.221)))] dark:bg-[var(--zui-toggle-thumb-colors-cyan-bg-dark,var(--zui-color-cyan-dark,oklch(71.5%_0.143_215.221)))]",
  lime: "bg-[var(--zui-toggle-thumb-colors-lime-bg,var(--zui-color-lime,oklch(76.8%_0.233_130.85)))] dark:bg-[var(--zui-toggle-thumb-colors-lime-bg-dark,var(--zui-color-lime-dark,oklch(76.8%_0.233_130.85)))]",
  emerald:
    "bg-[var(--zui-toggle-thumb-colors-emerald-bg,var(--zui-color-emerald,oklch(69.6%_0.17_162.48)))] dark:bg-[var(--zui-toggle-thumb-colors-emerald-bg-dark,var(--zui-color-emerald-dark,oklch(69.6%_0.17_162.48)))]",
  rose: "bg-[var(--zui-toggle-thumb-colors-rose-bg,var(--zui-color-rose,oklch(64.5%_0.246_16.439)))] dark:bg-[var(--zui-toggle-thumb-colors-rose-bg-dark,var(--zui-color-rose-dark,oklch(64.5%_0.246_16.439)))]",
  slate:
    "bg-[var(--zui-toggle-thumb-colors-slate-bg,var(--zui-color-slate,oklch(55.4%_0.046_257.417)))] dark:bg-[var(--zui-toggle-thumb-colors-slate-bg-dark,var(--zui-color-slate-dark,oklch(55.4%_0.046_257.417)))]",
  zinc: "bg-[var(--zui-toggle-thumb-colors-zinc-bg,var(--zui-color-zinc,oklch(55.2%_0.016_285.938)))] dark:bg-[var(--zui-toggle-thumb-colors-zinc-bg-dark,var(--zui-color-zinc-dark,oklch(55.2%_0.016_285.938)))]",
  gray: "bg-[var(--zui-toggle-thumb-colors-gray-bg,var(--zui-color-gray,oklch(55.1%_0.027_264.364)))] dark:bg-[var(--zui-toggle-thumb-colors-gray-bg-dark,var(--zui-color-gray-dark,oklch(55.1%_0.027_264.364)))]",
  stone:
    "bg-[var(--zui-toggle-thumb-colors-stone-bg,var(--zui-color-stone,oklch(55.3%_0.013_58.071)))] dark:bg-[var(--zui-toggle-thumb-colors-stone-bg-dark,var(--zui-color-stone-dark,oklch(55.3%_0.013_58.071)))]",
  "gradient-blue":
    "bg-[var(--zui-toggle-thumb-colors-gradient-blue-bg,var(--zui-color-blue,oklch(62.3%_0.214_259.815)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-blue-bg-dark,var(--zui-color-blue-dark,oklch(62.3%_0.214_259.815)))]",
  "gradient-green":
    "bg-[var(--zui-toggle-thumb-colors-gradient-green-bg,var(--zui-color-green,oklch(72.3%_0.219_149.579)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-green-bg-dark,var(--zui-color-green-dark,oklch(72.3%_0.219_149.579)))]",
  "gradient-red":
    "bg-[var(--zui-toggle-thumb-colors-gradient-red-bg,var(--zui-color-red,oklch(63.7%_0.237_25.331)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-red-bg-dark,var(--zui-color-red-dark,oklch(63.7%_0.237_25.331)))]",
  "gradient-yellow":
    "bg-[var(--zui-toggle-thumb-colors-gradient-yellow-bg,var(--zui-color-yellow,oklch(79.5%_0.184_86.047)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-yellow-bg-dark,var(--zui-color-yellow-dark,oklch(79.5%_0.184_86.047)))]",
  "gradient-purple":
    "bg-[var(--zui-toggle-thumb-colors-gradient-purple-bg,var(--zui-color-purple,oklch(62.7%_0.265_303.9)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-purple-bg-dark,var(--zui-color-purple-dark,oklch(62.7%_0.265_303.9)))]",
  "gradient-teal":
    "bg-[var(--zui-toggle-thumb-colors-gradient-teal-bg,var(--zui-color-teal,oklch(70.4%_0.14_182.503)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-teal-bg-dark,var(--zui-color-teal-dark,oklch(70.4%_0.14_182.503)))]",
  "gradient-indigo":
    "bg-[var(--zui-toggle-thumb-colors-gradient-indigo-bg,var(--zui-color-indigo,oklch(58.5%_0.233_277.117)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-indigo-bg-dark,var(--zui-color-indigo-dark,oklch(58.5%_0.233_277.117)))]",
  "gradient-pink":
    "bg-[var(--zui-toggle-thumb-colors-gradient-pink-bg,var(--zui-color-pink,oklch(65.6%_0.241_354.308)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-pink-bg-dark,var(--zui-color-pink-dark,oklch(65.6%_0.241_354.308)))]",
  "gradient-orange":
    "bg-[var(--zui-toggle-thumb-colors-gradient-orange-bg,var(--zui-color-orange,oklch(70.5%_0.213_47.604)))] dark:bg-[var(--zui-toggle-thumb-colors-gradient-orange-bg-dark,var(--zui-color-orange-dark,oklch(70.5%_0.213_47.604)))]",
  blue: "bg-[var(--zui-toggle-thumb-colors-blue-bg,var(--zui-color-blue,#2563eb))] dark:bg-[var(--zui-toggle-thumb-colors-blue-bg-dark,var(--zui-color-blue-dark,#3b82f6))]",
  mint: "bg-[var(--zui-toggle-thumb-colors-mint-bg,var(--zui-color-mint,#10b981))] dark:bg-[var(--zui-toggle-thumb-colors-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "bg-[var(--zui-toggle-thumb-colors-ocean-bg,var(--zui-color-ocean,#0284c7))] dark:bg-[var(--zui-toggle-thumb-colors-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "bg-[var(--zui-toggle-thumb-colors-sapphire-bg,var(--zui-color-sapphire,#1d4ed8))] dark:bg-[var(--zui-toggle-thumb-colors-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "bg-[var(--zui-toggle-thumb-colors-lavender-bg,var(--zui-color-lavender,#8b5cf6))] dark:bg-[var(--zui-toggle-thumb-colors-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "bg-[var(--zui-toggle-thumb-colors-ruby-bg,var(--zui-color-ruby,#be123c))] dark:bg-[var(--zui-toggle-thumb-colors-ruby-bg-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "bg-[var(--zui-toggle-thumb-colors-red-bg,var(--zui-color-red,#dc2626))] dark:bg-[var(--zui-toggle-thumb-colors-red-bg-dark,var(--zui-color-red-dark,#ef4444))]",
  royal:
    "bg-[var(--zui-toggle-thumb-colors-royal-bg,var(--zui-color-royal,#4338ca))] dark:bg-[var(--zui-toggle-thumb-colors-royal-bg-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "bg-[var(--zui-toggle-thumb-colors-electric-bg,var(--zui-color-electric,#0ea5e9))] dark:bg-[var(--zui-toggle-thumb-colors-electric-bg-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "bg-[var(--zui-toggle-thumb-colors-forest-bg,var(--zui-color-forest,#166534))] dark:bg-[var(--zui-toggle-thumb-colors-forest-bg-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "bg-[var(--zui-toggle-thumb-colors-sunset-bg,var(--zui-color-sunset,#ea580c))] dark:bg-[var(--zui-toggle-thumb-colors-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "bg-[var(--zui-toggle-thumb-colors-magenta-bg,var(--zui-color-magenta,#c026d3))] dark:bg-[var(--zui-toggle-thumb-colors-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "bg-[var(--zui-toggle-thumb-colors-crimson-bg,var(--zui-color-crimson,#b91c1c))] dark:bg-[var(--zui-toggle-thumb-colors-crimson-bg-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "bg-[var(--zui-toggle-thumb-colors-aqua-bg,var(--zui-color-aqua,#0f766e))] dark:bg-[var(--zui-toggle-thumb-colors-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "bg-[var(--zui-toggle-thumb-colors-plum-bg,var(--zui-color-plum,#7e22ce))] dark:bg-[var(--zui-toggle-thumb-colors-plum-bg-dark,var(--zui-color-plum-dark,#c084fc))]",
} as const;
