export const zuiCssVariablePattern =
  "--zui-<component>-<slot?>-<variant?>-<property>-<state?>-dark?" as const;

export const zuiGlobalThemeTokens = {
  radius: "--zui-radius",
  ringOffset: "--zui-ring-offset",
  ringOffsetDark: "--zui-ring-offset-dark",
  focusRing: "--zui-focus-ring",
  focusRingDark: "--zui-focus-ring-dark",
  shadow: "--zui-shadow",
  shadowDark: "--zui-shadow-dark",
  surfaceMuted: "--zui-surface-muted",
  surfaceMutedDark: "--zui-surface-muted-dark",
  surfaceSoft: "--zui-surface-soft",
  surfaceSoftDark: "--zui-surface-soft-dark",
  surfaceHover: "--zui-surface-hover",
  surfaceHoverDark: "--zui-surface-hover-dark",
  border: "--zui-border",
  borderDark: "--zui-border-dark",
  fg: "--zui-fg",
  fgDark: "--zui-fg-dark",
  fgMuted: "--zui-fg-muted",
  fgMutedDark: "--zui-fg-muted-dark",
  brand: "--zui-brand",
  brandDark: "--zui-brand-dark",
  brandHover: "--zui-brand-hover",
  brandHoverDark: "--zui-brand-hover-dark",
  brandFg: "--zui-brand-fg",
  brandFgDark: "--zui-brand-fg-dark",
  statusSuccess: "--zui-status-success",
  statusSuccessDark: "--zui-status-success-dark",
  statusWarning: "--zui-status-warning",
  statusWarningDark: "--zui-status-warning-dark",
  statusError: "--zui-status-error",
  statusErrorDark: "--zui-status-error-dark",
  statusInfo: "--zui-status-info",
  statusInfoDark: "--zui-status-info-dark",
  colorBlue: "--zui-color-blue",
  colorBlueDark: "--zui-color-blue-dark",
  colorCyan: "--zui-color-cyan",
  colorCyanDark: "--zui-color-cyan-dark",
  colorGreen: "--zui-color-green",
  colorGreenDark: "--zui-color-green-dark",
  colorLime: "--zui-color-lime",
  colorLimeDark: "--zui-color-lime-dark",
  colorMint: "--zui-color-mint",
  colorMintDark: "--zui-color-mint-dark",
  colorOcean: "--zui-color-ocean",
  colorOceanDark: "--zui-color-ocean-dark",
  colorSapphire: "--zui-color-sapphire",
  colorSapphireDark: "--zui-color-sapphire-dark",
  colorLavender: "--zui-color-lavender",
  colorLavenderDark: "--zui-color-lavender-dark",
  colorRuby: "--zui-color-ruby",
  colorRubyDark: "--zui-color-ruby-dark",
  colorRed: "--zui-color-red",
  colorRedDark: "--zui-color-red-dark",
  colorSlate: "--zui-color-slate",
  colorSlateDark: "--zui-color-slate-dark",
  colorZinc: "--zui-color-zinc",
  colorZincDark: "--zui-color-zinc-dark",
  colorStone: "--zui-color-stone",
  colorStoneDark: "--zui-color-stone-dark",
  colorRoyal: "--zui-color-royal",
  colorRoyalDark: "--zui-color-royal-dark",
  colorElectric: "--zui-color-electric",
  colorElectricDark: "--zui-color-electric-dark",
  colorForest: "--zui-color-forest",
  colorForestDark: "--zui-color-forest-dark",
  colorSunset: "--zui-color-sunset",
  colorSunsetDark: "--zui-color-sunset-dark",
  colorMagenta: "--zui-color-magenta",
  colorMagentaDark: "--zui-color-magenta-dark",
  colorCrimson: "--zui-color-crimson",
  colorCrimsonDark: "--zui-color-crimson-dark",
  colorAqua: "--zui-color-aqua",
  colorAquaDark: "--zui-color-aqua-dark",
  colorPlum: "--zui-color-plum",
  colorPlumDark: "--zui-color-plum-dark",
  colorEmerald: "--zui-color-emerald",
  colorEmeraldDark: "--zui-color-emerald-dark",
  colorIndigo: "--zui-color-indigo",
  colorIndigoDark: "--zui-color-indigo-dark",
  colorPurple: "--zui-color-purple",
  colorPurpleDark: "--zui-color-purple-dark",
  colorPink: "--zui-color-pink",
  colorPinkDark: "--zui-color-pink-dark",
  colorRose: "--zui-color-rose",
  colorRoseDark: "--zui-color-rose-dark",
  colorSky: "--zui-color-sky",
  colorSkyDark: "--zui-color-sky-dark",
  colorTeal: "--zui-color-teal",
  colorTealDark: "--zui-color-teal-dark",
  colorYellow: "--zui-color-yellow",
  colorYellowDark: "--zui-color-yellow-dark",
  colorOrange: "--zui-color-orange",
  colorOrangeDark: "--zui-color-orange-dark",
  colorGray: "--zui-color-gray",
  colorGrayDark: "--zui-color-gray-dark",
  colorAmber: "--zui-color-amber",
  colorAmberDark: "--zui-color-amber-dark",
  colorViolet: "--zui-color-violet",
  colorVioletDark: "--zui-color-violet-dark",
} as const;

export const zuiInteractiveBase = ["transition-colors", "select-none"] as const;

export const zuiDisabledState = {
  default: "disabled:pointer-events-none disabled:opacity-50",
} as const;

export const zuiFocusRing = {
  default:
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--zui-focus-ring,oklch(44.6%_0.043_257.281))] dark:focus-visible:ring-[var(--zui-focus-ring-dark,oklch(86.9%_0.022_252.894))] focus-visible:ring-offset-2",
} as const;

export const zuiRingOffset = {
  default:
    "ring-offset-[var(--zui-ring-offset,oklch(98.4%_0.003_247.858))] dark:ring-offset-[var(--zui-ring-offset-dark,oklch(12.9%_0.042_264.695))]",
} as const;

export const zuiRadius = {
  xl: "rounded-[var(--zui-radius-xl,0.75rem)]",
} as const;
