// Literal utilities keep all public theme tokens in consumer Tailwind scan scope.
export const zuiToolbarBase =
  "flex min-w-0 max-w-full items-center border-solid rounded-[var(--zui-toolbar-radius,0.75rem)] dark:rounded-[var(--zui-toolbar-radius-dark,0.75rem)] border-[length:var(--zui-toolbar-border-width,1px)] dark:border-[length:var(--zui-toolbar-border-width-dark,1px)] p-[var(--zui-toolbar-padding,0.375rem)] dark:p-[var(--zui-toolbar-padding-dark,0.375rem)] gap-[var(--zui-toolbar-gap,0.25rem)] dark:gap-[var(--zui-toolbar-gap-dark,0.25rem)]";
export const zuiToolbarOrientations = {
  horizontal: "flex-row",
  vertical: "flex-col items-stretch",
} as const;
export const zuiToolbarWrap = {
  false: "flex-nowrap",
  true: "flex-wrap",
} as const;
export const zuiToolbarItemBase =
  "inline-flex shrink-0 items-center justify-center whitespace-nowrap font-medium text-inherit outline-none focus-visible:outline-solid transition-colors motion-reduce:transition-none rounded-[var(--zui-toolbar-item-radius,0.5rem)] dark:rounded-[var(--zui-toolbar-item-radius-dark,0.5rem)] gap-[var(--zui-toolbar-item-gap,0.375rem)] dark:gap-[var(--zui-toolbar-item-gap-dark,0.375rem)] bg-[var(--zui-toolbar-item-bg,transparent)] dark:bg-[var(--zui-toolbar-item-bg-dark,transparent)] hover:bg-[var(--zui-toolbar-item-hover-bg,#64748b1a)] dark:hover:bg-[var(--zui-toolbar-item-hover-bg-dark,#64748b1a)] data-[state=on]:bg-[var(--zui-toolbar-item-pressed-bg,#64748b33)] dark:data-[state=on]:bg-[var(--zui-toolbar-item-pressed-bg-dark,#64748b33)] disabled:opacity-[var(--zui-toolbar-disabled-opacity,0.5)] dark:disabled:opacity-[var(--zui-toolbar-disabled-opacity-dark,0.5)] aria-disabled:opacity-[var(--zui-toolbar-disabled-opacity,0.5)] dark:aria-disabled:opacity-[var(--zui-toolbar-disabled-opacity-dark,0.5)] disabled:cursor-not-allowed aria-disabled:cursor-not-allowed focus-visible:outline-[length:var(--zui-toolbar-focus-width,2px)] dark:focus-visible:outline-[length:var(--zui-toolbar-focus-width-dark,2px)] focus-visible:outline-offset-[var(--zui-toolbar-focus-offset,2px)] dark:focus-visible:outline-offset-[var(--zui-toolbar-focus-offset-dark,2px)] focus-visible:outline-[color:var(--zui-toolbar-focus-ring,currentColor)] dark:focus-visible:outline-[color:var(--zui-toolbar-focus-ring-dark,currentColor)]";
export const zuiToolbarItemSizes = {
  sm: "min-h-[var(--zui-toolbar-item-height-sm,2rem)] dark:min-h-[var(--zui-toolbar-item-height-sm-dark,2rem)] px-[var(--zui-toolbar-item-padding-sm,0.5rem)] dark:px-[var(--zui-toolbar-item-padding-sm-dark,0.5rem)] text-[length:var(--zui-toolbar-font-size-sm,0.75rem)] dark:text-[length:var(--zui-toolbar-font-size-sm-dark,0.75rem)]",
  md: "min-h-[var(--zui-toolbar-item-height-md,2.25rem)] dark:min-h-[var(--zui-toolbar-item-height-md-dark,2.25rem)] px-[var(--zui-toolbar-item-padding-md,0.75rem)] dark:px-[var(--zui-toolbar-item-padding-md-dark,0.75rem)] text-[length:var(--zui-toolbar-font-size-md,0.875rem)] dark:text-[length:var(--zui-toolbar-font-size-md-dark,0.875rem)]",
  lg: "min-h-[var(--zui-toolbar-item-height-lg,2.75rem)] dark:min-h-[var(--zui-toolbar-item-height-lg-dark,2.75rem)] px-[var(--zui-toolbar-item-padding-lg,1rem)] dark:px-[var(--zui-toolbar-item-padding-lg-dark,1rem)] text-[length:var(--zui-toolbar-font-size-lg,1rem)] dark:text-[length:var(--zui-toolbar-font-size-lg-dark,1rem)]",
} as const;
export const zuiToolbarGroupBase =
  "flex shrink-0 items-center gap-[var(--zui-toolbar-group-gap,0.25rem)] dark:gap-[var(--zui-toolbar-group-gap-dark,0.25rem)]";
export const zuiToolbarGroupOrientations = {
  horizontal: "flex-row",
  vertical: "flex-col items-stretch",
} as const;
export const zuiToolbarSeparatorBase =
  "shrink-0 self-stretch bg-[var(--zui-toolbar-separator-fg,#64748b66)] dark:bg-[var(--zui-toolbar-separator-fg-dark,#64748b66)] data-[orientation=vertical]:w-[var(--zui-toolbar-separator-width,1px)] dark:data-[orientation=vertical]:w-[var(--zui-toolbar-separator-width-dark,1px)] data-[orientation=vertical]:my-[var(--zui-toolbar-separator-inset,0.25rem)] dark:data-[orientation=vertical]:my-[var(--zui-toolbar-separator-inset-dark,0.25rem)] data-[orientation=horizontal]:h-[var(--zui-toolbar-separator-width,1px)] dark:data-[orientation=horizontal]:h-[var(--zui-toolbar-separator-width-dark,1px)] data-[orientation=horizontal]:mx-[var(--zui-toolbar-separator-inset,0.25rem)] dark:data-[orientation=horizontal]:mx-[var(--zui-toolbar-separator-inset-dark,0.25rem)]";
export const zuiToolbarAppearances = {
  default:
    "bg-[var(--zui-toolbar-default-bg,#ffffff)] dark:bg-[var(--zui-toolbar-default-bg-dark,#0f172a)] text-[color:var(--zui-toolbar-default-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-default-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-default-border,#e2e8f0)] dark:border-[color:var(--zui-toolbar-default-border-dark,#334155)]",
  subtle:
    "bg-[var(--zui-toolbar-subtle-bg,#f8fafc)] dark:bg-[var(--zui-toolbar-subtle-bg-dark,#1e293b)] text-[color:var(--zui-toolbar-subtle-fg,#334155)] dark:text-[color:var(--zui-toolbar-subtle-fg-dark,#e2e8f0)] border-[color:var(--zui-toolbar-subtle-border,#e2e8f0)] dark:border-[color:var(--zui-toolbar-subtle-border-dark,#334155)]",
  contrast:
    "bg-[var(--zui-toolbar-contrast-bg,#0f172a)] dark:bg-[var(--zui-toolbar-contrast-bg-dark,#f8fafc)] text-[color:var(--zui-toolbar-contrast-fg,#f8fafc)] dark:text-[color:var(--zui-toolbar-contrast-fg-dark,#0f172a)] border-[color:var(--zui-toolbar-contrast-border,#334155)] dark:border-[color:var(--zui-toolbar-contrast-border-dark,#cbd5e1)]",
  glass:
    "bg-[var(--zui-toolbar-glass-bg,#ffffffb3)] dark:bg-[var(--zui-toolbar-glass-bg-dark,#0f172ab3)] text-[color:var(--zui-toolbar-glass-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-glass-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-glass-border,#cbd5e1)] dark:border-[color:var(--zui-toolbar-glass-border-dark,#475569)] backdrop-blur-[var(--zui-toolbar-glass-blur,12px)] dark:backdrop-blur-[var(--zui-toolbar-glass-blur-dark,12px)]",
  blue: "bg-[var(--zui-toolbar-blue-bg,#eff6ff)] dark:bg-[var(--zui-toolbar-blue-bg-dark,#172554)] text-[color:var(--zui-toolbar-blue-fg,#1e40af)] dark:text-[color:var(--zui-toolbar-blue-fg-dark,#dbeafe)] border-[color:var(--zui-toolbar-blue-border,#bfdbfe)] dark:border-[color:var(--zui-toolbar-blue-border-dark,#1e40af)]",
  cyan: "bg-[var(--zui-toolbar-cyan-bg,#ecfeff)] dark:bg-[var(--zui-toolbar-cyan-bg-dark,#083344)] text-[color:var(--zui-toolbar-cyan-fg,#155e75)] dark:text-[color:var(--zui-toolbar-cyan-fg-dark,#cffafe)] border-[color:var(--zui-toolbar-cyan-border,#a5f3fc)] dark:border-[color:var(--zui-toolbar-cyan-border-dark,#155e75)]",
  green:
    "bg-[var(--zui-toolbar-green-bg,#f0fdf4)] dark:bg-[var(--zui-toolbar-green-bg-dark,#052e16)] text-[color:var(--zui-toolbar-green-fg,#166534)] dark:text-[color:var(--zui-toolbar-green-fg-dark,#dcfce7)] border-[color:var(--zui-toolbar-green-border,#bbf7d0)] dark:border-[color:var(--zui-toolbar-green-border-dark,#166534)]",
  lime: "bg-[var(--zui-toolbar-lime-bg,#f7fee7)] dark:bg-[var(--zui-toolbar-lime-bg-dark,#1a2e05)] text-[color:var(--zui-toolbar-lime-fg,#3f6212)] dark:text-[color:var(--zui-toolbar-lime-fg-dark,#ecfccb)] border-[color:var(--zui-toolbar-lime-border,#d9f99d)] dark:border-[color:var(--zui-toolbar-lime-border-dark,#3f6212)]",
  emerald:
    "bg-[var(--zui-toolbar-emerald-bg,#ecfdf5)] dark:bg-[var(--zui-toolbar-emerald-bg-dark,#022c22)] text-[color:var(--zui-toolbar-emerald-fg,#065f46)] dark:text-[color:var(--zui-toolbar-emerald-fg-dark,#d1fae5)] border-[color:var(--zui-toolbar-emerald-border,#a7f3d0)] dark:border-[color:var(--zui-toolbar-emerald-border-dark,#065f46)]",
  indigo:
    "bg-[var(--zui-toolbar-indigo-bg,#eef2ff)] dark:bg-[var(--zui-toolbar-indigo-bg-dark,#1e1b4b)] text-[color:var(--zui-toolbar-indigo-fg,#3730a3)] dark:text-[color:var(--zui-toolbar-indigo-fg-dark,#e0e7ff)] border-[color:var(--zui-toolbar-indigo-border,#c7d2fe)] dark:border-[color:var(--zui-toolbar-indigo-border-dark,#3730a3)]",
  purple:
    "bg-[var(--zui-toolbar-purple-bg,#faf5ff)] dark:bg-[var(--zui-toolbar-purple-bg-dark,#3b0764)] text-[color:var(--zui-toolbar-purple-fg,#6b21a8)] dark:text-[color:var(--zui-toolbar-purple-fg-dark,#f3e8ff)] border-[color:var(--zui-toolbar-purple-border,#e9d5ff)] dark:border-[color:var(--zui-toolbar-purple-border-dark,#6b21a8)]",
  pink: "bg-[var(--zui-toolbar-pink-bg,#fdf2f8)] dark:bg-[var(--zui-toolbar-pink-bg-dark,#500724)] text-[color:var(--zui-toolbar-pink-fg,#9d174d)] dark:text-[color:var(--zui-toolbar-pink-fg-dark,#fce7f3)] border-[color:var(--zui-toolbar-pink-border,#fbcfe8)] dark:border-[color:var(--zui-toolbar-pink-border-dark,#9d174d)]",
  rose: "bg-[var(--zui-toolbar-rose-bg,#fff1f2)] dark:bg-[var(--zui-toolbar-rose-bg-dark,#4c0519)] text-[color:var(--zui-toolbar-rose-fg,#9f1239)] dark:text-[color:var(--zui-toolbar-rose-fg-dark,#ffe4e6)] border-[color:var(--zui-toolbar-rose-border,#fecdd3)] dark:border-[color:var(--zui-toolbar-rose-border-dark,#9f1239)]",
  sky: "bg-[var(--zui-toolbar-sky-bg,#f0f9ff)] dark:bg-[var(--zui-toolbar-sky-bg-dark,#082f49)] text-[color:var(--zui-toolbar-sky-fg,#075985)] dark:text-[color:var(--zui-toolbar-sky-fg-dark,#e0f2fe)] border-[color:var(--zui-toolbar-sky-border,#bae6fd)] dark:border-[color:var(--zui-toolbar-sky-border-dark,#075985)]",
  teal: "bg-[var(--zui-toolbar-teal-bg,#f0fdfa)] dark:bg-[var(--zui-toolbar-teal-bg-dark,#042f2e)] text-[color:var(--zui-toolbar-teal-fg,#115e59)] dark:text-[color:var(--zui-toolbar-teal-fg-dark,#ccfbf1)] border-[color:var(--zui-toolbar-teal-border,#99f6e4)] dark:border-[color:var(--zui-toolbar-teal-border-dark,#115e59)]",
  yellow:
    "bg-[var(--zui-toolbar-yellow-bg,#fefce8)] dark:bg-[var(--zui-toolbar-yellow-bg-dark,#422006)] text-[color:var(--zui-toolbar-yellow-fg,#854d0e)] dark:text-[color:var(--zui-toolbar-yellow-fg-dark,#fef9c3)] border-[color:var(--zui-toolbar-yellow-border,#fef08a)] dark:border-[color:var(--zui-toolbar-yellow-border-dark,#854d0e)]",
  orange:
    "bg-[var(--zui-toolbar-orange-bg,#fff7ed)] dark:bg-[var(--zui-toolbar-orange-bg-dark,#431407)] text-[color:var(--zui-toolbar-orange-fg,#9a3412)] dark:text-[color:var(--zui-toolbar-orange-fg-dark,#ffedd5)] border-[color:var(--zui-toolbar-orange-border,#fed7aa)] dark:border-[color:var(--zui-toolbar-orange-border-dark,#9a3412)]",
  red: "bg-[var(--zui-toolbar-red-bg,#fef2f2)] dark:bg-[var(--zui-toolbar-red-bg-dark,#450a0a)] text-[color:var(--zui-toolbar-red-fg,#991b1b)] dark:text-[color:var(--zui-toolbar-red-fg-dark,#fee2e2)] border-[color:var(--zui-toolbar-red-border,#fecaca)] dark:border-[color:var(--zui-toolbar-red-border-dark,#991b1b)]",
  slate:
    "bg-[var(--zui-toolbar-slate-bg,#f8fafc)] dark:bg-[var(--zui-toolbar-slate-bg-dark,#0f172a)] text-[color:var(--zui-toolbar-slate-fg,#334155)] dark:text-[color:var(--zui-toolbar-slate-fg-dark,#f1f5f9)] border-[color:var(--zui-toolbar-slate-border,#cbd5e1)] dark:border-[color:var(--zui-toolbar-slate-border-dark,#334155)]",
  gray: "bg-[var(--zui-toolbar-gray-bg,#f9fafb)] dark:bg-[var(--zui-toolbar-gray-bg-dark,#111827)] text-[color:var(--zui-toolbar-gray-fg,#374151)] dark:text-[color:var(--zui-toolbar-gray-fg-dark,#f3f4f6)] border-[color:var(--zui-toolbar-gray-border,#d1d5db)] dark:border-[color:var(--zui-toolbar-gray-border-dark,#374151)]",
  zinc: "bg-[var(--zui-toolbar-zinc-bg,#fafafa)] dark:bg-[var(--zui-toolbar-zinc-bg-dark,#18181b)] text-[color:var(--zui-toolbar-zinc-fg,#3f3f46)] dark:text-[color:var(--zui-toolbar-zinc-fg-dark,#f4f4f5)] border-[color:var(--zui-toolbar-zinc-border,#d4d4d8)] dark:border-[color:var(--zui-toolbar-zinc-border-dark,#3f3f46)]",
  "gradient-blue":
    "bg-linear-to-br from-[var(--zui-toolbar-gradient-blue-from,#eff6ff)] dark:from-[var(--zui-toolbar-gradient-blue-from-dark,#172554)] to-[var(--zui-toolbar-gradient-blue-to,#faf5ff)] dark:to-[var(--zui-toolbar-gradient-blue-to-dark,#3b0764)] text-[color:var(--zui-toolbar-gradient-blue-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-gradient-blue-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-gradient-blue-border,#bfdbfe)] dark:border-[color:var(--zui-toolbar-gradient-blue-border-dark,#1e40af)]",
  "gradient-green":
    "bg-linear-to-br from-[var(--zui-toolbar-gradient-green-from,#f0fdf4)] dark:from-[var(--zui-toolbar-gradient-green-from-dark,#052e16)] to-[var(--zui-toolbar-gradient-green-to,#f7fee7)] dark:to-[var(--zui-toolbar-gradient-green-to-dark,#1a2e05)] text-[color:var(--zui-toolbar-gradient-green-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-gradient-green-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-gradient-green-border,#bbf7d0)] dark:border-[color:var(--zui-toolbar-gradient-green-border-dark,#166534)]",
  "gradient-purple":
    "bg-linear-to-br from-[var(--zui-toolbar-gradient-purple-from,#faf5ff)] dark:from-[var(--zui-toolbar-gradient-purple-from-dark,#3b0764)] to-[var(--zui-toolbar-gradient-purple-to,#fdf2f8)] dark:to-[var(--zui-toolbar-gradient-purple-to-dark,#500724)] text-[color:var(--zui-toolbar-gradient-purple-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-gradient-purple-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-gradient-purple-border,#e9d5ff)] dark:border-[color:var(--zui-toolbar-gradient-purple-border-dark,#6b21a8)]",
  "gradient-orange":
    "bg-linear-to-br from-[var(--zui-toolbar-gradient-orange-from,#fff7ed)] dark:from-[var(--zui-toolbar-gradient-orange-from-dark,#431407)] to-[var(--zui-toolbar-gradient-orange-to,#fefce8)] dark:to-[var(--zui-toolbar-gradient-orange-to-dark,#422006)] text-[color:var(--zui-toolbar-gradient-orange-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-gradient-orange-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-gradient-orange-border,#fed7aa)] dark:border-[color:var(--zui-toolbar-gradient-orange-border-dark,#9a3412)]",
  "gradient-pink":
    "bg-linear-to-br from-[var(--zui-toolbar-gradient-pink-from,#fdf2f8)] dark:from-[var(--zui-toolbar-gradient-pink-from-dark,#500724)] to-[var(--zui-toolbar-gradient-pink-to,#fff1f2)] dark:to-[var(--zui-toolbar-gradient-pink-to-dark,#4c0519)] text-[color:var(--zui-toolbar-gradient-pink-fg,#0f172a)] dark:text-[color:var(--zui-toolbar-gradient-pink-fg-dark,#f8fafc)] border-[color:var(--zui-toolbar-gradient-pink-border,#fbcfe8)] dark:border-[color:var(--zui-toolbar-gradient-pink-border-dark,#9d174d)]",
} as const;
