export const zuiTooltipBase =
  "absolute z-50 rounded-md shadow-[var(--zui-tooltip-shadow,var(--zui-shadow,0_4px_6px_-1px_rgb(0_0_0_/_0.1),0_2px_4px_-2px_rgb(0_0_0_/_0.1)))] dark:shadow-[var(--zui-tooltip-shadow-dark,var(--zui-shadow-dark,0_4px_6px_-1px_rgb(0_0_0_/_0.35),0_2px_4px_-2px_rgb(0_0_0_/_0.28)))] transition-all duration-200 pointer-events-none";

export const zuiTooltipVariants = {
  default:
    "bg-[var(--zui-tooltip-default-bg,var(--zui-surface-muted,#ffffff))] dark:bg-[var(--zui-tooltip-default-bg-dark,var(--zui-surface-muted-dark,#000000))] text-[color:var(--zui-tooltip-default-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-tooltip-default-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  outline:
    "border bg-[var(--zui-tooltip-outline-bg,var(--zui-surface-muted,#000000))] dark:bg-[var(--zui-tooltip-outline-bg-dark,var(--zui-surface-muted-dark,#ffffff))] text-[color:var(--zui-tooltip-outline-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-outline-fg-dark,var(--zui-brand-fg-dark,#000000))]",
  ghost:
    "bg-[var(--zui-tooltip-ghost-bg,var(--zui-surface-soft,oklch(27.8%_0.033_256.848)))] dark:bg-[var(--zui-tooltip-ghost-bg-dark,var(--zui-surface-soft-dark,oklch(27.8%_0.033_256.848)))] text-[color:var(--zui-tooltip-ghost-fg,var(--zui-brand-fg,#ffffffe6))] dark:text-[color:var(--zui-tooltip-ghost-fg-dark,var(--zui-brand-fg-dark,#ffffffe6))]",
  glass:
    "border border-[color:var(--zui-tooltip-glass-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-tooltip-glass-border-dark,var(--zui-border-dark,#ffffff26))] bg-[var(--zui-tooltip-glass-bg,var(--zui-surface-soft,#0000001a))] dark:bg-[var(--zui-tooltip-glass-bg-dark,var(--zui-surface-soft-dark,#ffffff1a))] text-[color:var(--zui-tooltip-glass-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-tooltip-glass-fg-dark,var(--zui-brand-fg-dark,#ffffff))] backdrop-blur-md",
  emerald:
    "bg-[var(--zui-tooltip-emerald-bg,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:bg-[var(--zui-tooltip-emerald-bg-dark,var(--zui-color-emerald-dark,oklch(43.2%_0.095_166.913)))] text-[color:var(--zui-tooltip-emerald-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-emerald-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  indigo:
    "bg-[var(--zui-tooltip-indigo-bg,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:bg-[var(--zui-tooltip-indigo-bg-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))] text-[color:var(--zui-tooltip-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  purple:
    "bg-[var(--zui-tooltip-purple-bg,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:bg-[var(--zui-tooltip-purple-bg-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-tooltip-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  pink: "bg-[var(--zui-tooltip-pink-bg,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:bg-[var(--zui-tooltip-pink-bg-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-tooltip-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  rose: "bg-[var(--zui-tooltip-rose-bg,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:bg-[var(--zui-tooltip-rose-bg-dark,var(--zui-color-rose-dark,oklch(45.5%_0.188_13.697)))] text-[color:var(--zui-tooltip-rose-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-rose-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  sky: "bg-[var(--zui-tooltip-sky-bg,var(--zui-color-sky,oklch(50%_0.134_242.749)))] dark:bg-[var(--zui-tooltip-sky-bg-dark,var(--zui-color-sky-dark,oklch(50%_0.134_242.749)))] text-[color:var(--zui-tooltip-sky-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-sky-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  teal: "bg-[var(--zui-tooltip-teal-bg,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:bg-[var(--zui-tooltip-teal-bg-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))] text-[color:var(--zui-tooltip-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  yellow:
    "bg-[var(--zui-tooltip-yellow-bg,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:bg-[var(--zui-tooltip-yellow-bg-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] text-[color:var(--zui-tooltip-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  orange:
    "bg-[var(--zui-tooltip-orange-bg,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:bg-[var(--zui-tooltip-orange-bg-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] text-[color:var(--zui-tooltip-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  green:
    "bg-[var(--zui-tooltip-green-bg,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:bg-[var(--zui-tooltip-green-bg-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328)))] text-[color:var(--zui-tooltip-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-blue":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-blue-from,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:from-[var(--zui-tooltip-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(42.4%_0.199_265.638)))] to-[var(--zui-tooltip-gradient-blue-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-tooltip-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-tooltip-gradient-blue-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-blue-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-green":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-green-from,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:from-[var(--zui-tooltip-gradient-green-from-dark,var(--zui-color-green-dark,oklch(44.8%_0.119_151.328)))] to-[var(--zui-tooltip-gradient-green-to,var(--zui-color-lime,oklch(45.3%_0.124_130.933)))] dark:to-[var(--zui-tooltip-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(45.3%_0.124_130.933)))] text-[color:var(--zui-tooltip-gradient-green-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-green-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-red":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-red-from,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:from-[var(--zui-tooltip-gradient-red-from-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] to-[var(--zui-tooltip-gradient-red-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-tooltip-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-tooltip-gradient-red-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-red-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-yellow":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-yellow-from,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:from-[var(--zui-tooltip-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(47.6%_0.114_61.907)))] to-[var(--zui-tooltip-gradient-yellow-to,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:to-[var(--zui-tooltip-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] text-[color:var(--zui-tooltip-gradient-yellow-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-yellow-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-purple":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-purple-from,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:from-[var(--zui-tooltip-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] to-[var(--zui-tooltip-gradient-purple-to,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:to-[var(--zui-tooltip-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] text-[color:var(--zui-tooltip-gradient-purple-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-purple-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-teal":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-teal-from,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:from-[var(--zui-tooltip-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(43.7%_0.078_188.216)))] to-[var(--zui-tooltip-gradient-teal-to,var(--zui-color-cyan,oklch(45%_0.085_224.283)))] dark:to-[var(--zui-tooltip-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(45%_0.085_224.283)))] text-[color:var(--zui-tooltip-gradient-teal-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-teal-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-indigo":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-indigo-from,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:from-[var(--zui-tooltip-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(39.8%_0.195_277.366)))] to-[var(--zui-tooltip-gradient-indigo-to,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:to-[var(--zui-tooltip-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(43.8%_0.218_303.724)))] text-[color:var(--zui-tooltip-gradient-indigo-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-indigo-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-pink":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-pink-from,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:from-[var(--zui-tooltip-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(45.9%_0.187_3.815)))] to-[var(--zui-tooltip-gradient-pink-to,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:to-[var(--zui-tooltip-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(45.5%_0.188_13.697)))] text-[color:var(--zui-tooltip-gradient-pink-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-pink-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  "gradient-orange":
    "bg-linear-to-r from-[var(--zui-tooltip-gradient-orange-from,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:from-[var(--zui-tooltip-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(47%_0.157_37.304)))] to-[var(--zui-tooltip-gradient-orange-to,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:to-[var(--zui-tooltip-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(44.4%_0.177_26.899)))] text-[color:var(--zui-tooltip-gradient-orange-fg,var(--zui-brand-fg,#ffffff))] dark:text-[color:var(--zui-tooltip-gradient-orange-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  blue: "border border-[color:var(--zui-tooltip-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-tooltip-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-tooltip-blue-bg,var(--zui-color-blue,#2563eb14))] dark:bg-[var(--zui-tooltip-blue-bg-dark,var(--zui-color-blue-dark,#3b82f624))] text-[color:var(--zui-tooltip-blue-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-blue-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  cyan: "border border-[color:var(--zui-tooltip-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-tooltip-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-tooltip-cyan-bg,var(--zui-color-cyan,#0891b214))] dark:bg-[var(--zui-tooltip-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee24))] text-[color:var(--zui-tooltip-cyan-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-cyan-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  lime: "border border-[color:var(--zui-tooltip-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-tooltip-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-tooltip-lime-bg,var(--zui-color-lime,#65a30d14))] dark:bg-[var(--zui-tooltip-lime-bg-dark,var(--zui-color-lime-dark,#a3e63524))] text-[color:var(--zui-tooltip-lime-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-lime-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  mint: "border border-[color:var(--zui-tooltip-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-tooltip-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-tooltip-mint-bg,var(--zui-color-mint,#10b98114))] dark:bg-[var(--zui-tooltip-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b724))] text-[color:var(--zui-tooltip-mint-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-mint-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  ocean:
    "border border-[color:var(--zui-tooltip-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-tooltip-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-tooltip-ocean-bg,var(--zui-color-ocean,#0284c714))] dark:bg-[var(--zui-tooltip-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf824))] text-[color:var(--zui-tooltip-ocean-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-ocean-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  sapphire:
    "border border-[color:var(--zui-tooltip-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-tooltip-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-tooltip-sapphire-bg,var(--zui-color-sapphire,#1d4ed814))] dark:bg-[var(--zui-tooltip-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa24))] text-[color:var(--zui-tooltip-sapphire-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-sapphire-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  lavender:
    "border border-[color:var(--zui-tooltip-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-tooltip-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-tooltip-lavender-bg,var(--zui-color-lavender,#8b5cf614))] dark:bg-[var(--zui-tooltip-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa24))] text-[color:var(--zui-tooltip-lavender-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-lavender-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  ruby: "border border-[color:var(--zui-tooltip-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-tooltip-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-tooltip-ruby-bg,var(--zui-color-ruby,#be123c14))] dark:bg-[var(--zui-tooltip-ruby-bg-dark,var(--zui-color-ruby-dark,#fb718524))] text-[color:var(--zui-tooltip-ruby-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-ruby-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  red: "border border-[color:var(--zui-tooltip-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-tooltip-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-tooltip-red-bg,var(--zui-color-red,#dc262614))] dark:bg-[var(--zui-tooltip-red-bg-dark,var(--zui-color-red-dark,#ef444424))] text-[color:var(--zui-tooltip-red-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-red-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  slate:
    "border border-[color:var(--zui-tooltip-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-tooltip-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-tooltip-slate-bg,var(--zui-color-slate,#47556914))] dark:bg-[var(--zui-tooltip-slate-bg-dark,var(--zui-color-slate-dark,#64748b24))] text-[color:var(--zui-tooltip-slate-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-slate-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  zinc: "border border-[color:var(--zui-tooltip-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-tooltip-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-tooltip-zinc-bg,var(--zui-color-zinc,#52525b14))] dark:bg-[var(--zui-tooltip-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a24))] text-[color:var(--zui-tooltip-zinc-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-zinc-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  stone:
    "border border-[color:var(--zui-tooltip-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-tooltip-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-tooltip-stone-bg,var(--zui-color-stone,#57534e14))] dark:bg-[var(--zui-tooltip-stone-bg-dark,var(--zui-color-stone-dark,#78716c24))] text-[color:var(--zui-tooltip-stone-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-stone-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  royal:
    "border border-[color:var(--zui-tooltip-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-tooltip-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-tooltip-royal-bg,var(--zui-color-royal,#4338ca14))] dark:bg-[var(--zui-tooltip-royal-bg-dark,var(--zui-color-royal-dark,#818cf824))] text-[color:var(--zui-tooltip-royal-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-royal-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  electric:
    "border border-[color:var(--zui-tooltip-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-tooltip-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-tooltip-electric-bg,var(--zui-color-electric,#0ea5e914))] dark:bg-[var(--zui-tooltip-electric-bg-dark,var(--zui-color-electric-dark,#38bdf824))] text-[color:var(--zui-tooltip-electric-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-electric-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  forest:
    "border border-[color:var(--zui-tooltip-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-tooltip-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-tooltip-forest-bg,var(--zui-color-forest,#16653414))] dark:bg-[var(--zui-tooltip-forest-bg-dark,var(--zui-color-forest-dark,#4ade8024))] text-[color:var(--zui-tooltip-forest-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-forest-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  sunset:
    "border border-[color:var(--zui-tooltip-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-tooltip-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-tooltip-sunset-bg,var(--zui-color-sunset,#ea580c14))] dark:bg-[var(--zui-tooltip-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c24))] text-[color:var(--zui-tooltip-sunset-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-sunset-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  magenta:
    "border border-[color:var(--zui-tooltip-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-tooltip-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-tooltip-magenta-bg,var(--zui-color-magenta,#c026d314))] dark:bg-[var(--zui-tooltip-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f924))] text-[color:var(--zui-tooltip-magenta-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-magenta-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  crimson:
    "border border-[color:var(--zui-tooltip-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-tooltip-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-tooltip-crimson-bg,var(--zui-color-crimson,#b91c1c14))] dark:bg-[var(--zui-tooltip-crimson-bg-dark,var(--zui-color-crimson-dark,#f8717124))] text-[color:var(--zui-tooltip-crimson-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-crimson-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  aqua: "border border-[color:var(--zui-tooltip-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-tooltip-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-tooltip-aqua-bg,var(--zui-color-aqua,#0f766e14))] dark:bg-[var(--zui-tooltip-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf24))] text-[color:var(--zui-tooltip-aqua-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-aqua-fg-dark,var(--zui-fg-dark,#f8fafc))]",
  plum: "border border-[color:var(--zui-tooltip-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-tooltip-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-tooltip-plum-bg,var(--zui-color-plum,#7e22ce14))] dark:bg-[var(--zui-tooltip-plum-bg-dark,var(--zui-color-plum-dark,#c084fc24))] text-[color:var(--zui-tooltip-plum-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tooltip-plum-fg-dark,var(--zui-fg-dark,#f8fafc))]",
} as const;

export const zuiTooltipSizes = {
  sm: "text-xs px-2 py-1",
  md: "text-sm px-3 py-1.5",
  lg: "text-base px-4 py-2",
} as const;

export const zuiTooltipWidths = {
  fit: "min-w-75 md:min-w-fit",
  xs: "min-w-75 md:min-w-xs",
  sm: "min-w-75 md:min-w-sm",
  md: "min-w-75 md:min-w-md",
  lg: "min-w-75 md:min-w-lg",
  xl: "min-w-75 md:min-w-xl",
  "2xl": "min-w-75 md:min-w-2xl",
} as const;
