export const zuiTreeViewBase =
  "w-full text-[color:var(--zui-tree-view-fg,oklch(20.8%_0.042_265.755))] dark:text-[color:var(--zui-tree-view-fg-dark,oklch(92.9%_0.013_255.508))]";

export const zuiTreeViewAppearances = {
  default:
    "rounded-xl border border-[color:var(--zui-tree-view-default-border,#0000001a)] dark:border-[color:var(--zui-tree-view-default-border-dark,#ffffff1a)] p-2",
  outline:
    "rounded-xl border border-[color:var(--zui-tree-view-outline-border,#00000026)] dark:border-[color:var(--zui-tree-view-outline-border-dark,#ffffff26)] p-2",
  ghost: "p-1",
  card: "rounded-xl border border-[color:var(--zui-tree-view-card-border,#0000001a)] dark:border-[color:var(--zui-tree-view-card-border-dark,#ffffff1a)] bg-[var(--zui-tree-view-card-bg,#0000000d)] dark:bg-[var(--zui-tree-view-card-bg-dark,#00000099)] p-3",
  separated:
    "rounded-xl border border-[color:var(--zui-tree-view-separated-border,#0000001a)] dark:border-[color:var(--zui-tree-view-separated-border-dark,#ffffff1a)] bg-[var(--zui-tree-view-separated-bg,oklch(98.4%_0.003_247.858_/_0.4))] dark:bg-[var(--zui-tree-view-separated-bg-dark,oklch(12.9%_0.042_264.695_/_0.4))] p-3",
  sky: "rounded-xl border border-[color:var(--zui-tree-view-sky-border,oklch(44.3%_0.11_240.79))] dark:border-[color:var(--zui-tree-view-sky-border-dark,oklch(58.8%_0.158_241.966))] p-2",
  rose: "rounded-xl border border-[color:var(--zui-tree-view-rose-border,oklch(45.5%_0.188_13.697))] dark:border-[color:var(--zui-tree-view-rose-border-dark,oklch(58.6%_0.253_17.585))] p-2",
  purple:
    "rounded-xl border border-[color:var(--zui-tree-view-purple-border,oklch(43.8%_0.218_303.724))] dark:border-[color:var(--zui-tree-view-purple-border-dark,oklch(55.8%_0.288_302.321))] p-2",
  pink: "rounded-xl border border-[color:var(--zui-tree-view-pink-border,oklch(45.9%_0.187_3.815))] dark:border-[color:var(--zui-tree-view-pink-border-dark,oklch(59.2%_0.249_0.584))] p-2",
  orange:
    "rounded-xl border border-[color:var(--zui-tree-view-orange-border,oklch(47%_0.157_37.304))] dark:border-[color:var(--zui-tree-view-orange-border-dark,oklch(64.6%_0.222_41.116))] p-2",
  yellow:
    "rounded-xl border border-[color:var(--zui-tree-view-yellow-border,oklch(47.6%_0.114_61.907))] dark:border-[color:var(--zui-tree-view-yellow-border-dark,oklch(68.1%_0.162_75.834))] p-2",
  teal: "rounded-xl border border-[color:var(--zui-tree-view-teal-border,oklch(43.7%_0.078_188.216))] dark:border-[color:var(--zui-tree-view-teal-border-dark,oklch(60%_0.118_184.704))] p-2",
  indigo:
    "rounded-xl border border-[color:var(--zui-tree-view-indigo-border,oklch(39.8%_0.195_277.366))] dark:border-[color:var(--zui-tree-view-indigo-border-dark,oklch(51.1%_0.262_276.966))] p-2",
  emerald:
    "rounded-xl border border-[color:var(--zui-tree-view-emerald-border,oklch(43.2%_0.095_166.913))] dark:border-[color:var(--zui-tree-view-emerald-border-dark,oklch(59.6%_0.145_163.225))] p-2",
  "gradient-blue":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-blue-border,oklch(42.4%_0.199_265.638))] dark:border-[color:var(--zui-tree-view-gradient-blue-border-dark,oklch(54.6%_0.245_262.881))] p-2",
  "gradient-green":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-green-border,oklch(44.8%_0.119_151.328))] dark:border-[color:var(--zui-tree-view-gradient-green-border-dark,oklch(62.7%_0.194_149.214))] p-2",
  "gradient-red":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-red-border,oklch(44.4%_0.177_26.899))] dark:border-[color:var(--zui-tree-view-gradient-red-border-dark,oklch(57.7%_0.245_27.325))] p-2",
  "gradient-yellow":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-yellow-border,oklch(47.6%_0.114_61.907))] dark:border-[color:var(--zui-tree-view-gradient-yellow-border-dark,oklch(68.1%_0.162_75.834))] p-2",
  "gradient-purple":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-purple-border,oklch(43.8%_0.218_303.724))] dark:border-[color:var(--zui-tree-view-gradient-purple-border-dark,oklch(55.8%_0.288_302.321))] p-2",
  "gradient-teal":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-teal-border,oklch(43.7%_0.078_188.216))] dark:border-[color:var(--zui-tree-view-gradient-teal-border-dark,oklch(60%_0.118_184.704))] p-2",
  "gradient-indigo":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-indigo-border,oklch(39.8%_0.195_277.366))] dark:border-[color:var(--zui-tree-view-gradient-indigo-border-dark,oklch(51.1%_0.262_276.966))] p-2",
  "gradient-pink":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-pink-border,oklch(45.9%_0.187_3.815))] dark:border-[color:var(--zui-tree-view-gradient-pink-border-dark,oklch(59.2%_0.249_0.584))] p-2",
  "gradient-orange":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-orange-border,oklch(47%_0.157_37.304))] dark:border-[color:var(--zui-tree-view-gradient-orange-border-dark,oklch(64.6%_0.222_41.116))] p-2",
  blue: "rounded-xl border border-[color:var(--zui-tree-view-blue-border,#2563eb)] dark:border-[color:var(--zui-tree-view-blue-border-dark,#3b82f6)] bg-[var(--zui-tree-view-blue-bg,transparent)] dark:bg-[var(--zui-tree-view-blue-bg-dark,transparent)] text-[color:var(--zui-tree-view-blue-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-blue-fg-dark,#f8fafc)] p-2",
  cyan: "rounded-xl border border-[color:var(--zui-tree-view-cyan-border,#0891b2)] dark:border-[color:var(--zui-tree-view-cyan-border-dark,#22d3ee)] bg-[var(--zui-tree-view-cyan-bg,transparent)] dark:bg-[var(--zui-tree-view-cyan-bg-dark,transparent)] text-[color:var(--zui-tree-view-cyan-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-cyan-fg-dark,#f8fafc)] p-2",
  green:
    "rounded-xl border border-[color:var(--zui-tree-view-green-border,#16a34a)] dark:border-[color:var(--zui-tree-view-green-border-dark,#22c55e)] bg-[var(--zui-tree-view-green-bg,transparent)] dark:bg-[var(--zui-tree-view-green-bg-dark,transparent)] text-[color:var(--zui-tree-view-green-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-green-fg-dark,#f8fafc)] p-2",
  lime: "rounded-xl border border-[color:var(--zui-tree-view-lime-border,#65a30d)] dark:border-[color:var(--zui-tree-view-lime-border-dark,#a3e635)] bg-[var(--zui-tree-view-lime-bg,transparent)] dark:bg-[var(--zui-tree-view-lime-bg-dark,transparent)] text-[color:var(--zui-tree-view-lime-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-lime-fg-dark,#f8fafc)] p-2",
  mint: "rounded-xl border border-[color:var(--zui-tree-view-mint-border,#10b981)] dark:border-[color:var(--zui-tree-view-mint-border-dark,#6ee7b7)] bg-[var(--zui-tree-view-mint-bg,transparent)] dark:bg-[var(--zui-tree-view-mint-bg-dark,transparent)] text-[color:var(--zui-tree-view-mint-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-mint-fg-dark,#f8fafc)] p-2",
  ocean:
    "rounded-xl border border-[color:var(--zui-tree-view-ocean-border,#0284c7)] dark:border-[color:var(--zui-tree-view-ocean-border-dark,#38bdf8)] bg-[var(--zui-tree-view-ocean-bg,transparent)] dark:bg-[var(--zui-tree-view-ocean-bg-dark,transparent)] text-[color:var(--zui-tree-view-ocean-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-ocean-fg-dark,#f8fafc)] p-2",
  sapphire:
    "rounded-xl border border-[color:var(--zui-tree-view-sapphire-border,#1d4ed8)] dark:border-[color:var(--zui-tree-view-sapphire-border-dark,#60a5fa)] bg-[var(--zui-tree-view-sapphire-bg,transparent)] dark:bg-[var(--zui-tree-view-sapphire-bg-dark,transparent)] text-[color:var(--zui-tree-view-sapphire-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-sapphire-fg-dark,#f8fafc)] p-2",
  lavender:
    "rounded-xl border border-[color:var(--zui-tree-view-lavender-border,#8b5cf6)] dark:border-[color:var(--zui-tree-view-lavender-border-dark,#a78bfa)] bg-[var(--zui-tree-view-lavender-bg,transparent)] dark:bg-[var(--zui-tree-view-lavender-bg-dark,transparent)] text-[color:var(--zui-tree-view-lavender-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-lavender-fg-dark,#f8fafc)] p-2",
  ruby: "rounded-xl border border-[color:var(--zui-tree-view-ruby-border,#be123c)] dark:border-[color:var(--zui-tree-view-ruby-border-dark,#fb7185)] bg-[var(--zui-tree-view-ruby-bg,transparent)] dark:bg-[var(--zui-tree-view-ruby-bg-dark,transparent)] text-[color:var(--zui-tree-view-ruby-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-ruby-fg-dark,#f8fafc)] p-2",
  red: "rounded-xl border border-[color:var(--zui-tree-view-red-border,#dc2626)] dark:border-[color:var(--zui-tree-view-red-border-dark,#ef4444)] bg-[var(--zui-tree-view-red-bg,transparent)] dark:bg-[var(--zui-tree-view-red-bg-dark,transparent)] text-[color:var(--zui-tree-view-red-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-red-fg-dark,#f8fafc)] p-2",
  slate:
    "rounded-xl border border-[color:var(--zui-tree-view-slate-border,#475569)] dark:border-[color:var(--zui-tree-view-slate-border-dark,#64748b)] bg-[var(--zui-tree-view-slate-bg,transparent)] dark:bg-[var(--zui-tree-view-slate-bg-dark,transparent)] text-[color:var(--zui-tree-view-slate-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-slate-fg-dark,#f8fafc)] p-2",
  zinc: "rounded-xl border border-[color:var(--zui-tree-view-zinc-border,#52525b)] dark:border-[color:var(--zui-tree-view-zinc-border-dark,#71717a)] bg-[var(--zui-tree-view-zinc-bg,transparent)] dark:bg-[var(--zui-tree-view-zinc-bg-dark,transparent)] text-[color:var(--zui-tree-view-zinc-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-zinc-fg-dark,#f8fafc)] p-2",
  stone:
    "rounded-xl border border-[color:var(--zui-tree-view-stone-border,#57534e)] dark:border-[color:var(--zui-tree-view-stone-border-dark,#78716c)] bg-[var(--zui-tree-view-stone-bg,transparent)] dark:bg-[var(--zui-tree-view-stone-bg-dark,transparent)] text-[color:var(--zui-tree-view-stone-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-stone-fg-dark,#f8fafc)] p-2",
  royal:
    "rounded-xl border border-[color:var(--zui-tree-view-royal-border,#4338ca)] dark:border-[color:var(--zui-tree-view-royal-border-dark,#818cf8)] bg-[var(--zui-tree-view-royal-bg,transparent)] dark:bg-[var(--zui-tree-view-royal-bg-dark,transparent)] text-[color:var(--zui-tree-view-royal-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-royal-fg-dark,#f8fafc)] p-2",
  electric:
    "rounded-xl border border-[color:var(--zui-tree-view-electric-border,#0ea5e9)] dark:border-[color:var(--zui-tree-view-electric-border-dark,#38bdf8)] bg-[var(--zui-tree-view-electric-bg,transparent)] dark:bg-[var(--zui-tree-view-electric-bg-dark,transparent)] text-[color:var(--zui-tree-view-electric-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-electric-fg-dark,#f8fafc)] p-2",
  forest:
    "rounded-xl border border-[color:var(--zui-tree-view-forest-border,#166534)] dark:border-[color:var(--zui-tree-view-forest-border-dark,#4ade80)] bg-[var(--zui-tree-view-forest-bg,transparent)] dark:bg-[var(--zui-tree-view-forest-bg-dark,transparent)] text-[color:var(--zui-tree-view-forest-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-forest-fg-dark,#f8fafc)] p-2",
  sunset:
    "rounded-xl border border-[color:var(--zui-tree-view-sunset-border,#ea580c)] dark:border-[color:var(--zui-tree-view-sunset-border-dark,#fb923c)] bg-[var(--zui-tree-view-sunset-bg,transparent)] dark:bg-[var(--zui-tree-view-sunset-bg-dark,transparent)] text-[color:var(--zui-tree-view-sunset-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-sunset-fg-dark,#f8fafc)] p-2",
  magenta:
    "rounded-xl border border-[color:var(--zui-tree-view-magenta-border,#c026d3)] dark:border-[color:var(--zui-tree-view-magenta-border-dark,#e879f9)] bg-[var(--zui-tree-view-magenta-bg,transparent)] dark:bg-[var(--zui-tree-view-magenta-bg-dark,transparent)] text-[color:var(--zui-tree-view-magenta-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-magenta-fg-dark,#f8fafc)] p-2",
  crimson:
    "rounded-xl border border-[color:var(--zui-tree-view-crimson-border,#b91c1c)] dark:border-[color:var(--zui-tree-view-crimson-border-dark,#f87171)] bg-[var(--zui-tree-view-crimson-bg,transparent)] dark:bg-[var(--zui-tree-view-crimson-bg-dark,transparent)] text-[color:var(--zui-tree-view-crimson-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-crimson-fg-dark,#f8fafc)] p-2",
  aqua: "rounded-xl border border-[color:var(--zui-tree-view-aqua-border,#0f766e)] dark:border-[color:var(--zui-tree-view-aqua-border-dark,#2dd4bf)] bg-[var(--zui-tree-view-aqua-bg,transparent)] dark:bg-[var(--zui-tree-view-aqua-bg-dark,transparent)] text-[color:var(--zui-tree-view-aqua-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-aqua-fg-dark,#f8fafc)] p-2",
  plum: "rounded-xl border border-[color:var(--zui-tree-view-plum-border,#7e22ce)] dark:border-[color:var(--zui-tree-view-plum-border-dark,#c084fc)] bg-[var(--zui-tree-view-plum-bg,transparent)] dark:bg-[var(--zui-tree-view-plum-bg-dark,transparent)] text-[color:var(--zui-tree-view-plum-fg,#0f172a)] dark:text-[color:var(--zui-tree-view-plum-fg-dark,#f8fafc)] p-2",
} as const;

export const zuiTreeViewSizes = {
  sm: "text-xs",
  md: "text-sm",
  lg: "text-base",
} as const;

export const zuiTreeViewItemBase =
  "relative flex w-full items-center gap-2 rounded-lg pr-2 text-left font-medium outline-none transition select-none cursor-pointer hover:bg-[var(--zui-tree-view-item-hover,#0000000d)] dark:hover:bg-[var(--zui-tree-view-item-hover-dark,#ffffff0d)] focus-visible:ring-2 focus-visible:ring-[var(--zui-tree-view-ring-focus,#0000004d)] dark:focus-visible:ring-[var(--zui-tree-view-ring-focus-dark,#ffffff4d)] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiTreeViewItemSizes = {
  sm: "py-1 text-xs",
  md: "py-1.5 text-sm",
  lg: "py-2 text-base",
} as const;

export const zuiTreeViewItemAppearances = {
  default:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,#0000000f)] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,#ffffff14)] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,oklch(20.8%_0.042_265.755))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,#ffffff)]",
  outline:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,#0000000f)] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,#ffffff14)] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,oklch(20.8%_0.042_265.755))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,#ffffff)]",
  ghost:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,#0000000f)] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,#ffffff14)] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,oklch(20.8%_0.042_265.755))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,#ffffff)]",
  card: "data-[selected=true]:bg-[var(--zui-tree-view-selected,#00000014)] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,#ffffff1f)] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,oklch(20.8%_0.042_265.755))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,#ffffff)]",
  separated:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,#00000014)] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,#ffffff1f)] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,oklch(20.8%_0.042_265.755))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,#ffffff)]",
  sky: "data-[selected=true]:bg-[var(--zui-tree-view-sky-selected,oklch(95.1%_0.026_236.824))] dark:data-[selected=true]:bg-[var(--zui-tree-view-sky-selected-dark,oklch(58.8%_0.158_241.966_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-sky-selected-fg,oklch(44.3%_0.11_240.79))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-sky-selected-fg-dark,oklch(82.8%_0.111_230.318))]",
  rose: "data-[selected=true]:bg-[var(--zui-tree-view-rose-selected,oklch(94.1%_0.03_12.58))] dark:data-[selected=true]:bg-[var(--zui-tree-view-rose-selected-dark,oklch(58.6%_0.253_17.585_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-rose-selected-fg,oklch(45.5%_0.188_13.697))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-rose-selected-fg-dark,oklch(81%_0.117_11.638))]",
  purple:
    "data-[selected=true]:bg-[var(--zui-tree-view-purple-selected,oklch(94.6%_0.033_307.174))] dark:data-[selected=true]:bg-[var(--zui-tree-view-purple-selected-dark,oklch(55.8%_0.288_302.321_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-purple-selected-fg,oklch(43.8%_0.218_303.724))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-purple-selected-fg-dark,oklch(82.7%_0.119_306.383))]",
  pink: "data-[selected=true]:bg-[var(--zui-tree-view-pink-selected,oklch(94.8%_0.028_342.258))] dark:data-[selected=true]:bg-[var(--zui-tree-view-pink-selected-dark,oklch(59.2%_0.249_0.584_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-pink-selected-fg,oklch(45.9%_0.187_3.815))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-pink-selected-fg-dark,oklch(82.3%_0.12_346.018))]",
  orange:
    "data-[selected=true]:bg-[var(--zui-tree-view-orange-selected,oklch(95.4%_0.038_75.164))] dark:data-[selected=true]:bg-[var(--zui-tree-view-orange-selected-dark,oklch(64.6%_0.222_41.116_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-orange-selected-fg,oklch(47%_0.157_37.304))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-orange-selected-fg-dark,oklch(83.7%_0.128_66.29))]",
  yellow:
    "data-[selected=true]:bg-[var(--zui-tree-view-yellow-selected,oklch(97.3%_0.071_103.193))] dark:data-[selected=true]:bg-[var(--zui-tree-view-yellow-selected-dark,oklch(68.1%_0.162_75.834_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-yellow-selected-fg,oklch(47.6%_0.114_61.907))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-yellow-selected-fg-dark,oklch(90.5%_0.182_98.111))]",
  teal: "data-[selected=true]:bg-[var(--zui-tree-view-teal-selected,oklch(95.3%_0.051_180.801))] dark:data-[selected=true]:bg-[var(--zui-tree-view-teal-selected-dark,oklch(60%_0.118_184.704_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-teal-selected-fg,oklch(43.7%_0.078_188.216))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-teal-selected-fg-dark,oklch(85.5%_0.138_181.071))]",
  indigo:
    "data-[selected=true]:bg-[var(--zui-tree-view-indigo-selected,oklch(93%_0.034_272.788))] dark:data-[selected=true]:bg-[var(--zui-tree-view-indigo-selected-dark,oklch(51.1%_0.262_276.966_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-indigo-selected-fg,oklch(39.8%_0.195_277.366))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-indigo-selected-fg-dark,oklch(78.5%_0.115_274.713))]",
  emerald:
    "data-[selected=true]:bg-[var(--zui-tree-view-emerald-selected,oklch(95%_0.052_163.051))] dark:data-[selected=true]:bg-[var(--zui-tree-view-emerald-selected-dark,oklch(59.6%_0.145_163.225_/_0.16))] data-[selected=true]:text-[color:var(--zui-tree-view-emerald-selected-fg,oklch(43.2%_0.095_166.913))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-emerald-selected-fg-dark,oklch(84.5%_0.143_164.978))]",
  "gradient-blue":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-blue-from,oklch(80.9%_0.105_251.813))] data-[selected=true]:to-[var(--zui-tree-view-gradient-blue-to,oklch(82.7%_0.119_306.383))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-blue-from-dark,oklch(54.6%_0.245_262.881))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-blue-to-dark,oklch(55.8%_0.288_302.321))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-green":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-green-from,oklch(87.1%_0.15_154.449))] data-[selected=true]:to-[var(--zui-tree-view-gradient-green-to,oklch(89.7%_0.196_126.665))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-green-from-dark,oklch(62.7%_0.194_149.214))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-green-to-dark,oklch(64.8%_0.2_131.684))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-red":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-red-from,oklch(80.8%_0.114_19.571))] data-[selected=true]:to-[var(--zui-tree-view-gradient-red-to,oklch(82.3%_0.12_346.018))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-red-from-dark,oklch(57.7%_0.245_27.325))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-red-to-dark,oklch(59.2%_0.249_0.584))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-yellow":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-yellow-from,oklch(90.5%_0.182_98.111))] data-[selected=true]:to-[var(--zui-tree-view-gradient-yellow-to,oklch(83.7%_0.128_66.29))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-yellow-from-dark,oklch(68.1%_0.162_75.834))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-yellow-to-dark,oklch(64.6%_0.222_41.116))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-purple":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-purple-from,oklch(82.7%_0.119_306.383))] data-[selected=true]:to-[var(--zui-tree-view-gradient-purple-to,oklch(82.3%_0.12_346.018))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-purple-from-dark,oklch(55.8%_0.288_302.321))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-purple-to-dark,oklch(59.2%_0.249_0.584))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-teal":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-teal-from,oklch(85.5%_0.138_181.071))] data-[selected=true]:to-[var(--zui-tree-view-gradient-teal-to,oklch(86.5%_0.127_207.078))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-teal-from-dark,oklch(60%_0.118_184.704))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-teal-to-dark,oklch(60.9%_0.126_221.723))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-indigo":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-indigo-from,oklch(78.5%_0.115_274.713))] data-[selected=true]:to-[var(--zui-tree-view-gradient-indigo-to,oklch(82.7%_0.119_306.383))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-indigo-from-dark,oklch(51.1%_0.262_276.966))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-indigo-to-dark,oklch(55.8%_0.288_302.321))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-pink":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-pink-from,oklch(82.3%_0.12_346.018))] data-[selected=true]:to-[var(--zui-tree-view-gradient-pink-to,oklch(81%_0.117_11.638))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-pink-from-dark,oklch(59.2%_0.249_0.584))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-pink-to-dark,oklch(58.6%_0.253_17.585))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  "gradient-orange":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-orange-from,oklch(83.7%_0.128_66.29))] data-[selected=true]:to-[var(--zui-tree-view-gradient-orange-to,oklch(80.8%_0.114_19.571))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-orange-from-dark,oklch(64.6%_0.222_41.116))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-orange-to-dark,oklch(57.7%_0.245_27.325))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,#ffffff)]",
  blue: "hover:bg-[var(--zui-tree-view-item-blue-bg-hover,#2563eb18)] dark:hover:bg-[var(--zui-tree-view-item-blue-bg-hover-dark,#3b82f62e)] hover:text-[color:var(--zui-tree-view-item-blue-fg-hover,#2563eb)] dark:hover:text-[color:var(--zui-tree-view-item-blue-fg-hover-dark,#3b82f6)] data-[selected=true]:bg-[var(--zui-tree-view-item-blue-bg,#2563eb14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-blue-bg-dark,#3b82f624)] data-[selected=true]:text-[color:var(--zui-tree-view-item-blue-fg,#2563eb)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-blue-fg-dark,#3b82f6)]",
  cyan: "hover:bg-[var(--zui-tree-view-item-cyan-bg-hover,#0891b218)] dark:hover:bg-[var(--zui-tree-view-item-cyan-bg-hover-dark,#22d3ee2e)] hover:text-[color:var(--zui-tree-view-item-cyan-fg-hover,#0891b2)] dark:hover:text-[color:var(--zui-tree-view-item-cyan-fg-hover-dark,#22d3ee)] data-[selected=true]:bg-[var(--zui-tree-view-item-cyan-bg,#0891b214)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-cyan-bg-dark,#22d3ee24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-cyan-fg,#0891b2)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-cyan-fg-dark,#22d3ee)]",
  green:
    "hover:bg-[var(--zui-tree-view-item-green-bg-hover,#16a34a18)] dark:hover:bg-[var(--zui-tree-view-item-green-bg-hover-dark,#22c55e2e)] hover:text-[color:var(--zui-tree-view-item-green-fg-hover,#16a34a)] dark:hover:text-[color:var(--zui-tree-view-item-green-fg-hover-dark,#22c55e)] data-[selected=true]:bg-[var(--zui-tree-view-item-green-bg,#16a34a14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-green-bg-dark,#22c55e24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-green-fg,#16a34a)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-green-fg-dark,#22c55e)]",
  lime: "hover:bg-[var(--zui-tree-view-item-lime-bg-hover,#65a30d18)] dark:hover:bg-[var(--zui-tree-view-item-lime-bg-hover-dark,#a3e6352e)] hover:text-[color:var(--zui-tree-view-item-lime-fg-hover,#65a30d)] dark:hover:text-[color:var(--zui-tree-view-item-lime-fg-hover-dark,#a3e635)] data-[selected=true]:bg-[var(--zui-tree-view-item-lime-bg,#65a30d14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-lime-bg-dark,#a3e63524)] data-[selected=true]:text-[color:var(--zui-tree-view-item-lime-fg,#65a30d)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-lime-fg-dark,#a3e635)]",
  mint: "hover:bg-[var(--zui-tree-view-item-mint-bg-hover,#10b98118)] dark:hover:bg-[var(--zui-tree-view-item-mint-bg-hover-dark,#6ee7b72e)] hover:text-[color:var(--zui-tree-view-item-mint-fg-hover,#10b981)] dark:hover:text-[color:var(--zui-tree-view-item-mint-fg-hover-dark,#6ee7b7)] data-[selected=true]:bg-[var(--zui-tree-view-item-mint-bg,#10b98114)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-mint-bg-dark,#6ee7b724)] data-[selected=true]:text-[color:var(--zui-tree-view-item-mint-fg,#10b981)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-mint-fg-dark,#6ee7b7)]",
  ocean:
    "hover:bg-[var(--zui-tree-view-item-ocean-bg-hover,#0284c718)] dark:hover:bg-[var(--zui-tree-view-item-ocean-bg-hover-dark,#38bdf82e)] hover:text-[color:var(--zui-tree-view-item-ocean-fg-hover,#0284c7)] dark:hover:text-[color:var(--zui-tree-view-item-ocean-fg-hover-dark,#38bdf8)] data-[selected=true]:bg-[var(--zui-tree-view-item-ocean-bg,#0284c714)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-ocean-bg-dark,#38bdf824)] data-[selected=true]:text-[color:var(--zui-tree-view-item-ocean-fg,#0284c7)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-ocean-fg-dark,#38bdf8)]",
  sapphire:
    "hover:bg-[var(--zui-tree-view-item-sapphire-bg-hover,#1d4ed818)] dark:hover:bg-[var(--zui-tree-view-item-sapphire-bg-hover-dark,#60a5fa2e)] hover:text-[color:var(--zui-tree-view-item-sapphire-fg-hover,#1d4ed8)] dark:hover:text-[color:var(--zui-tree-view-item-sapphire-fg-hover-dark,#60a5fa)] data-[selected=true]:bg-[var(--zui-tree-view-item-sapphire-bg,#1d4ed814)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-sapphire-bg-dark,#60a5fa24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-sapphire-fg,#1d4ed8)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-sapphire-fg-dark,#60a5fa)]",
  lavender:
    "hover:bg-[var(--zui-tree-view-item-lavender-bg-hover,#8b5cf618)] dark:hover:bg-[var(--zui-tree-view-item-lavender-bg-hover-dark,#a78bfa2e)] hover:text-[color:var(--zui-tree-view-item-lavender-fg-hover,#8b5cf6)] dark:hover:text-[color:var(--zui-tree-view-item-lavender-fg-hover-dark,#a78bfa)] data-[selected=true]:bg-[var(--zui-tree-view-item-lavender-bg,#8b5cf614)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-lavender-bg-dark,#a78bfa24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-lavender-fg,#8b5cf6)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-lavender-fg-dark,#a78bfa)]",
  ruby: "hover:bg-[var(--zui-tree-view-item-ruby-bg-hover,#be123c18)] dark:hover:bg-[var(--zui-tree-view-item-ruby-bg-hover-dark,#fb71852e)] hover:text-[color:var(--zui-tree-view-item-ruby-fg-hover,#be123c)] dark:hover:text-[color:var(--zui-tree-view-item-ruby-fg-hover-dark,#fb7185)] data-[selected=true]:bg-[var(--zui-tree-view-item-ruby-bg,#be123c14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-ruby-bg-dark,#fb718524)] data-[selected=true]:text-[color:var(--zui-tree-view-item-ruby-fg,#be123c)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-ruby-fg-dark,#fb7185)]",
  red: "hover:bg-[var(--zui-tree-view-item-red-bg-hover,#dc262618)] dark:hover:bg-[var(--zui-tree-view-item-red-bg-hover-dark,#ef44442e)] hover:text-[color:var(--zui-tree-view-item-red-fg-hover,#dc2626)] dark:hover:text-[color:var(--zui-tree-view-item-red-fg-hover-dark,#ef4444)] data-[selected=true]:bg-[var(--zui-tree-view-item-red-bg,#dc262614)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-red-bg-dark,#ef444424)] data-[selected=true]:text-[color:var(--zui-tree-view-item-red-fg,#dc2626)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-red-fg-dark,#ef4444)]",
  slate:
    "hover:bg-[var(--zui-tree-view-item-slate-bg-hover,#47556918)] dark:hover:bg-[var(--zui-tree-view-item-slate-bg-hover-dark,#64748b2e)] hover:text-[color:var(--zui-tree-view-item-slate-fg-hover,#475569)] dark:hover:text-[color:var(--zui-tree-view-item-slate-fg-hover-dark,#64748b)] data-[selected=true]:bg-[var(--zui-tree-view-item-slate-bg,#47556914)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-slate-bg-dark,#64748b24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-slate-fg,#475569)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-slate-fg-dark,#64748b)]",
  zinc: "hover:bg-[var(--zui-tree-view-item-zinc-bg-hover,#52525b18)] dark:hover:bg-[var(--zui-tree-view-item-zinc-bg-hover-dark,#71717a2e)] hover:text-[color:var(--zui-tree-view-item-zinc-fg-hover,#52525b)] dark:hover:text-[color:var(--zui-tree-view-item-zinc-fg-hover-dark,#71717a)] data-[selected=true]:bg-[var(--zui-tree-view-item-zinc-bg,#52525b14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-zinc-bg-dark,#71717a24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-zinc-fg,#52525b)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-zinc-fg-dark,#71717a)]",
  stone:
    "hover:bg-[var(--zui-tree-view-item-stone-bg-hover,#57534e18)] dark:hover:bg-[var(--zui-tree-view-item-stone-bg-hover-dark,#78716c2e)] hover:text-[color:var(--zui-tree-view-item-stone-fg-hover,#57534e)] dark:hover:text-[color:var(--zui-tree-view-item-stone-fg-hover-dark,#78716c)] data-[selected=true]:bg-[var(--zui-tree-view-item-stone-bg,#57534e14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-stone-bg-dark,#78716c24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-stone-fg,#57534e)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-stone-fg-dark,#78716c)]",
  royal:
    "hover:bg-[var(--zui-tree-view-item-royal-bg-hover,#4338ca18)] dark:hover:bg-[var(--zui-tree-view-item-royal-bg-hover-dark,#818cf82e)] hover:text-[color:var(--zui-tree-view-item-royal-fg-hover,#4338ca)] dark:hover:text-[color:var(--zui-tree-view-item-royal-fg-hover-dark,#818cf8)] data-[selected=true]:bg-[var(--zui-tree-view-item-royal-bg,#4338ca14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-royal-bg-dark,#818cf824)] data-[selected=true]:text-[color:var(--zui-tree-view-item-royal-fg,#4338ca)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-royal-fg-dark,#818cf8)]",
  electric:
    "hover:bg-[var(--zui-tree-view-item-electric-bg-hover,#0ea5e918)] dark:hover:bg-[var(--zui-tree-view-item-electric-bg-hover-dark,#38bdf82e)] hover:text-[color:var(--zui-tree-view-item-electric-fg-hover,#0ea5e9)] dark:hover:text-[color:var(--zui-tree-view-item-electric-fg-hover-dark,#38bdf8)] data-[selected=true]:bg-[var(--zui-tree-view-item-electric-bg,#0ea5e914)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-electric-bg-dark,#38bdf824)] data-[selected=true]:text-[color:var(--zui-tree-view-item-electric-fg,#0ea5e9)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-electric-fg-dark,#38bdf8)]",
  forest:
    "hover:bg-[var(--zui-tree-view-item-forest-bg-hover,#16653418)] dark:hover:bg-[var(--zui-tree-view-item-forest-bg-hover-dark,#4ade802e)] hover:text-[color:var(--zui-tree-view-item-forest-fg-hover,#166534)] dark:hover:text-[color:var(--zui-tree-view-item-forest-fg-hover-dark,#4ade80)] data-[selected=true]:bg-[var(--zui-tree-view-item-forest-bg,#16653414)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-forest-bg-dark,#4ade8024)] data-[selected=true]:text-[color:var(--zui-tree-view-item-forest-fg,#166534)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-forest-fg-dark,#4ade80)]",
  sunset:
    "hover:bg-[var(--zui-tree-view-item-sunset-bg-hover,#ea580c18)] dark:hover:bg-[var(--zui-tree-view-item-sunset-bg-hover-dark,#fb923c2e)] hover:text-[color:var(--zui-tree-view-item-sunset-fg-hover,#ea580c)] dark:hover:text-[color:var(--zui-tree-view-item-sunset-fg-hover-dark,#fb923c)] data-[selected=true]:bg-[var(--zui-tree-view-item-sunset-bg,#ea580c14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-sunset-bg-dark,#fb923c24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-sunset-fg,#ea580c)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-sunset-fg-dark,#fb923c)]",
  magenta:
    "hover:bg-[var(--zui-tree-view-item-magenta-bg-hover,#c026d318)] dark:hover:bg-[var(--zui-tree-view-item-magenta-bg-hover-dark,#e879f92e)] hover:text-[color:var(--zui-tree-view-item-magenta-fg-hover,#c026d3)] dark:hover:text-[color:var(--zui-tree-view-item-magenta-fg-hover-dark,#e879f9)] data-[selected=true]:bg-[var(--zui-tree-view-item-magenta-bg,#c026d314)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-magenta-bg-dark,#e879f924)] data-[selected=true]:text-[color:var(--zui-tree-view-item-magenta-fg,#c026d3)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-magenta-fg-dark,#e879f9)]",
  crimson:
    "hover:bg-[var(--zui-tree-view-item-crimson-bg-hover,#b91c1c18)] dark:hover:bg-[var(--zui-tree-view-item-crimson-bg-hover-dark,#f871712e)] hover:text-[color:var(--zui-tree-view-item-crimson-fg-hover,#b91c1c)] dark:hover:text-[color:var(--zui-tree-view-item-crimson-fg-hover-dark,#f87171)] data-[selected=true]:bg-[var(--zui-tree-view-item-crimson-bg,#b91c1c14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-crimson-bg-dark,#f8717124)] data-[selected=true]:text-[color:var(--zui-tree-view-item-crimson-fg,#b91c1c)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-crimson-fg-dark,#f87171)]",
  aqua: "hover:bg-[var(--zui-tree-view-item-aqua-bg-hover,#0f766e18)] dark:hover:bg-[var(--zui-tree-view-item-aqua-bg-hover-dark,#2dd4bf2e)] hover:text-[color:var(--zui-tree-view-item-aqua-fg-hover,#0f766e)] dark:hover:text-[color:var(--zui-tree-view-item-aqua-fg-hover-dark,#2dd4bf)] data-[selected=true]:bg-[var(--zui-tree-view-item-aqua-bg,#0f766e14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-aqua-bg-dark,#2dd4bf24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-aqua-fg,#0f766e)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-aqua-fg-dark,#2dd4bf)]",
  plum: "hover:bg-[var(--zui-tree-view-item-plum-bg-hover,#7e22ce18)] dark:hover:bg-[var(--zui-tree-view-item-plum-bg-hover-dark,#c084fc2e)] hover:text-[color:var(--zui-tree-view-item-plum-fg-hover,#7e22ce)] dark:hover:text-[color:var(--zui-tree-view-item-plum-fg-hover-dark,#c084fc)] data-[selected=true]:bg-[var(--zui-tree-view-item-plum-bg,#7e22ce14)] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-plum-bg-dark,#c084fc24)] data-[selected=true]:text-[color:var(--zui-tree-view-item-plum-fg,#7e22ce)] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-plum-fg-dark,#c084fc)]",
} as const;

export const zuiTreeViewChevron =
  "inline-flex h-5 w-5 shrink-0 items-center justify-center rounded text-[color:var(--zui-tree-view-chevron,oklch(55.5%_0.041_257.417))] dark:text-[color:var(--zui-tree-view-chevron-dark,oklch(70.4%_0.04_256.788))] transition-transform duration-200 data-[expanded=true]:rotate-90";

export const zuiTreeViewIcon =
  "inline-flex shrink-0 items-center justify-center text-[color:var(--zui-tree-view-icon,oklch(55.5%_0.041_257.417))] dark:text-[color:var(--zui-tree-view-icon-dark,oklch(70.4%_0.04_256.788))]";

export const zuiTreeViewGuide =
  "border-l border-[color:var(--zui-tree-view-guide,#0000001a)] dark:border-[color:var(--zui-tree-view-guide-dark,#ffffff1a)]";
