export const zuiTreeViewBase =
  "w-full text-[color:var(--zui-tree-view-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:text-[color:var(--zui-tree-view-fg-dark,var(--zui-fg-dark,oklch(92.9%_0.013_255.508)))]";

export const zuiTreeViewAppearances = {
  default:
    "rounded-xl border border-[color:var(--zui-tree-view-default-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-tree-view-default-border-dark,var(--zui-border-dark,#ffffff1a))] p-2",
  outline:
    "rounded-xl border border-[color:var(--zui-tree-view-outline-border,var(--zui-border,#00000026))] dark:border-[color:var(--zui-tree-view-outline-border-dark,var(--zui-border-dark,#ffffff26))] p-2",
  ghost: "p-1",
  card: "rounded-xl border border-[color:var(--zui-tree-view-card-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-tree-view-card-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-tree-view-card-bg,var(--zui-surface-soft,#0000000d))] dark:bg-[var(--zui-tree-view-card-bg-dark,var(--zui-surface-soft-dark,#00000099))] p-3",
  separated:
    "rounded-xl border border-[color:var(--zui-tree-view-separated-border,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-tree-view-separated-border-dark,var(--zui-border-dark,#ffffff1a))] bg-[var(--zui-tree-view-separated-bg,var(--zui-surface-soft,oklch(98.4%_0.003_247.858_/_0.4)))] dark:bg-[var(--zui-tree-view-separated-bg-dark,var(--zui-surface-soft-dark,oklch(12.9%_0.042_264.695_/_0.4)))] p-3",
  sky: "rounded-xl border border-[color:var(--zui-tree-view-sky-border,var(--zui-color-sky,oklch(44.3%_0.11_240.79)))] dark:border-[color:var(--zui-tree-view-sky-border-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966)))] p-2",
  rose: "rounded-xl border border-[color:var(--zui-tree-view-rose-border,var(--zui-color-rose,oklch(45.5%_0.188_13.697)))] dark:border-[color:var(--zui-tree-view-rose-border-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] p-2",
  purple:
    "rounded-xl border border-[color:var(--zui-tree-view-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-tree-view-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] p-2",
  pink: "rounded-xl border border-[color:var(--zui-tree-view-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-tree-view-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] p-2",
  orange:
    "rounded-xl border border-[color:var(--zui-tree-view-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-tree-view-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] p-2",
  yellow:
    "rounded-xl border border-[color:var(--zui-tree-view-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-tree-view-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] p-2",
  teal: "rounded-xl border border-[color:var(--zui-tree-view-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-tree-view-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] p-2",
  indigo:
    "rounded-xl border border-[color:var(--zui-tree-view-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-tree-view-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] p-2",
  emerald:
    "rounded-xl border border-[color:var(--zui-tree-view-emerald-border,var(--zui-color-emerald,oklch(43.2%_0.095_166.913)))] dark:border-[color:var(--zui-tree-view-emerald-border-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225)))] p-2",
  "gradient-blue":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-blue-border,var(--zui-color-blue,oklch(42.4%_0.199_265.638)))] dark:border-[color:var(--zui-tree-view-gradient-blue-border-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] p-2",
  "gradient-green":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-green-border,var(--zui-color-green,oklch(44.8%_0.119_151.328)))] dark:border-[color:var(--zui-tree-view-gradient-green-border-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] p-2",
  "gradient-red":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-red-border,var(--zui-color-red,oklch(44.4%_0.177_26.899)))] dark:border-[color:var(--zui-tree-view-gradient-red-border-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] p-2",
  "gradient-yellow":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-yellow-border,var(--zui-color-yellow,oklch(47.6%_0.114_61.907)))] dark:border-[color:var(--zui-tree-view-gradient-yellow-border-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] p-2",
  "gradient-purple":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-purple-border,var(--zui-color-purple,oklch(43.8%_0.218_303.724)))] dark:border-[color:var(--zui-tree-view-gradient-purple-border-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] p-2",
  "gradient-teal":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-teal-border,var(--zui-color-teal,oklch(43.7%_0.078_188.216)))] dark:border-[color:var(--zui-tree-view-gradient-teal-border-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] p-2",
  "gradient-indigo":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-indigo-border,var(--zui-color-indigo,oklch(39.8%_0.195_277.366)))] dark:border-[color:var(--zui-tree-view-gradient-indigo-border-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] p-2",
  "gradient-pink":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-pink-border,var(--zui-color-pink,oklch(45.9%_0.187_3.815)))] dark:border-[color:var(--zui-tree-view-gradient-pink-border-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] p-2",
  "gradient-orange":
    "rounded-xl border border-[color:var(--zui-tree-view-gradient-orange-border,var(--zui-color-orange,oklch(47%_0.157_37.304)))] dark:border-[color:var(--zui-tree-view-gradient-orange-border-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] p-2",
  blue: "rounded-xl border border-[color:var(--zui-tree-view-blue-border,var(--zui-color-blue,#2563eb))] dark:border-[color:var(--zui-tree-view-blue-border-dark,var(--zui-color-blue-dark,#3b82f6))] bg-[var(--zui-tree-view-blue-bg,transparent)] dark:bg-[var(--zui-tree-view-blue-bg-dark,transparent)] text-[color:var(--zui-tree-view-blue-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-blue-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  cyan: "rounded-xl border border-[color:var(--zui-tree-view-cyan-border,var(--zui-color-cyan,#0891b2))] dark:border-[color:var(--zui-tree-view-cyan-border-dark,var(--zui-color-cyan-dark,#22d3ee))] bg-[var(--zui-tree-view-cyan-bg,transparent)] dark:bg-[var(--zui-tree-view-cyan-bg-dark,transparent)] text-[color:var(--zui-tree-view-cyan-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-cyan-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  green:
    "rounded-xl border border-[color:var(--zui-tree-view-green-border,var(--zui-color-green,#16a34a))] dark:border-[color:var(--zui-tree-view-green-border-dark,var(--zui-color-green-dark,#22c55e))] bg-[var(--zui-tree-view-green-bg,transparent)] dark:bg-[var(--zui-tree-view-green-bg-dark,transparent)] text-[color:var(--zui-tree-view-green-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-green-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  lime: "rounded-xl border border-[color:var(--zui-tree-view-lime-border,var(--zui-color-lime,#65a30d))] dark:border-[color:var(--zui-tree-view-lime-border-dark,var(--zui-color-lime-dark,#a3e635))] bg-[var(--zui-tree-view-lime-bg,transparent)] dark:bg-[var(--zui-tree-view-lime-bg-dark,transparent)] text-[color:var(--zui-tree-view-lime-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-lime-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  mint: "rounded-xl border border-[color:var(--zui-tree-view-mint-border,var(--zui-color-mint,#10b981))] dark:border-[color:var(--zui-tree-view-mint-border-dark,var(--zui-color-mint-dark,#6ee7b7))] bg-[var(--zui-tree-view-mint-bg,transparent)] dark:bg-[var(--zui-tree-view-mint-bg-dark,transparent)] text-[color:var(--zui-tree-view-mint-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-mint-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  ocean:
    "rounded-xl border border-[color:var(--zui-tree-view-ocean-border,var(--zui-color-ocean,#0284c7))] dark:border-[color:var(--zui-tree-view-ocean-border-dark,var(--zui-color-ocean-dark,#38bdf8))] bg-[var(--zui-tree-view-ocean-bg,transparent)] dark:bg-[var(--zui-tree-view-ocean-bg-dark,transparent)] text-[color:var(--zui-tree-view-ocean-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-ocean-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  sapphire:
    "rounded-xl border border-[color:var(--zui-tree-view-sapphire-border,var(--zui-color-sapphire,#1d4ed8))] dark:border-[color:var(--zui-tree-view-sapphire-border-dark,var(--zui-color-sapphire-dark,#60a5fa))] bg-[var(--zui-tree-view-sapphire-bg,transparent)] dark:bg-[var(--zui-tree-view-sapphire-bg-dark,transparent)] text-[color:var(--zui-tree-view-sapphire-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-sapphire-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  lavender:
    "rounded-xl border border-[color:var(--zui-tree-view-lavender-border,var(--zui-color-lavender,#8b5cf6))] dark:border-[color:var(--zui-tree-view-lavender-border-dark,var(--zui-color-lavender-dark,#a78bfa))] bg-[var(--zui-tree-view-lavender-bg,transparent)] dark:bg-[var(--zui-tree-view-lavender-bg-dark,transparent)] text-[color:var(--zui-tree-view-lavender-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-lavender-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  ruby: "rounded-xl border border-[color:var(--zui-tree-view-ruby-border,var(--zui-color-ruby,#be123c))] dark:border-[color:var(--zui-tree-view-ruby-border-dark,var(--zui-color-ruby-dark,#fb7185))] bg-[var(--zui-tree-view-ruby-bg,transparent)] dark:bg-[var(--zui-tree-view-ruby-bg-dark,transparent)] text-[color:var(--zui-tree-view-ruby-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-ruby-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  red: "rounded-xl border border-[color:var(--zui-tree-view-red-border,var(--zui-color-red,#dc2626))] dark:border-[color:var(--zui-tree-view-red-border-dark,var(--zui-color-red-dark,#ef4444))] bg-[var(--zui-tree-view-red-bg,transparent)] dark:bg-[var(--zui-tree-view-red-bg-dark,transparent)] text-[color:var(--zui-tree-view-red-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-red-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  slate:
    "rounded-xl border border-[color:var(--zui-tree-view-slate-border,var(--zui-color-slate,#475569))] dark:border-[color:var(--zui-tree-view-slate-border-dark,var(--zui-color-slate-dark,#64748b))] bg-[var(--zui-tree-view-slate-bg,transparent)] dark:bg-[var(--zui-tree-view-slate-bg-dark,transparent)] text-[color:var(--zui-tree-view-slate-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-slate-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  zinc: "rounded-xl border border-[color:var(--zui-tree-view-zinc-border,var(--zui-color-zinc,#52525b))] dark:border-[color:var(--zui-tree-view-zinc-border-dark,var(--zui-color-zinc-dark,#71717a))] bg-[var(--zui-tree-view-zinc-bg,transparent)] dark:bg-[var(--zui-tree-view-zinc-bg-dark,transparent)] text-[color:var(--zui-tree-view-zinc-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-zinc-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  stone:
    "rounded-xl border border-[color:var(--zui-tree-view-stone-border,var(--zui-color-stone,#57534e))] dark:border-[color:var(--zui-tree-view-stone-border-dark,var(--zui-color-stone-dark,#78716c))] bg-[var(--zui-tree-view-stone-bg,transparent)] dark:bg-[var(--zui-tree-view-stone-bg-dark,transparent)] text-[color:var(--zui-tree-view-stone-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-stone-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  royal:
    "rounded-xl border border-[color:var(--zui-tree-view-royal-border,var(--zui-color-royal,#4338ca))] dark:border-[color:var(--zui-tree-view-royal-border-dark,var(--zui-color-royal-dark,#818cf8))] bg-[var(--zui-tree-view-royal-bg,transparent)] dark:bg-[var(--zui-tree-view-royal-bg-dark,transparent)] text-[color:var(--zui-tree-view-royal-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-royal-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  electric:
    "rounded-xl border border-[color:var(--zui-tree-view-electric-border,var(--zui-color-electric,#0ea5e9))] dark:border-[color:var(--zui-tree-view-electric-border-dark,var(--zui-color-electric-dark,#38bdf8))] bg-[var(--zui-tree-view-electric-bg,transparent)] dark:bg-[var(--zui-tree-view-electric-bg-dark,transparent)] text-[color:var(--zui-tree-view-electric-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-electric-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  forest:
    "rounded-xl border border-[color:var(--zui-tree-view-forest-border,var(--zui-color-forest,#166534))] dark:border-[color:var(--zui-tree-view-forest-border-dark,var(--zui-color-forest-dark,#4ade80))] bg-[var(--zui-tree-view-forest-bg,transparent)] dark:bg-[var(--zui-tree-view-forest-bg-dark,transparent)] text-[color:var(--zui-tree-view-forest-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-forest-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  sunset:
    "rounded-xl border border-[color:var(--zui-tree-view-sunset-border,var(--zui-color-sunset,#ea580c))] dark:border-[color:var(--zui-tree-view-sunset-border-dark,var(--zui-color-sunset-dark,#fb923c))] bg-[var(--zui-tree-view-sunset-bg,transparent)] dark:bg-[var(--zui-tree-view-sunset-bg-dark,transparent)] text-[color:var(--zui-tree-view-sunset-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-sunset-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  magenta:
    "rounded-xl border border-[color:var(--zui-tree-view-magenta-border,var(--zui-color-magenta,#c026d3))] dark:border-[color:var(--zui-tree-view-magenta-border-dark,var(--zui-color-magenta-dark,#e879f9))] bg-[var(--zui-tree-view-magenta-bg,transparent)] dark:bg-[var(--zui-tree-view-magenta-bg-dark,transparent)] text-[color:var(--zui-tree-view-magenta-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-magenta-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  crimson:
    "rounded-xl border border-[color:var(--zui-tree-view-crimson-border,var(--zui-color-crimson,#b91c1c))] dark:border-[color:var(--zui-tree-view-crimson-border-dark,var(--zui-color-crimson-dark,#f87171))] bg-[var(--zui-tree-view-crimson-bg,transparent)] dark:bg-[var(--zui-tree-view-crimson-bg-dark,transparent)] text-[color:var(--zui-tree-view-crimson-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-crimson-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  aqua: "rounded-xl border border-[color:var(--zui-tree-view-aqua-border,var(--zui-color-aqua,#0f766e))] dark:border-[color:var(--zui-tree-view-aqua-border-dark,var(--zui-color-aqua-dark,#2dd4bf))] bg-[var(--zui-tree-view-aqua-bg,transparent)] dark:bg-[var(--zui-tree-view-aqua-bg-dark,transparent)] text-[color:var(--zui-tree-view-aqua-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-aqua-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
  plum: "rounded-xl border border-[color:var(--zui-tree-view-plum-border,var(--zui-color-plum,#7e22ce))] dark:border-[color:var(--zui-tree-view-plum-border-dark,var(--zui-color-plum-dark,#c084fc))] bg-[var(--zui-tree-view-plum-bg,transparent)] dark:bg-[var(--zui-tree-view-plum-bg-dark,transparent)] text-[color:var(--zui-tree-view-plum-fg,var(--zui-fg,#0f172a))] dark:text-[color:var(--zui-tree-view-plum-fg-dark,var(--zui-fg-dark,#f8fafc))] p-2",
} as const;

export const zuiTreeViewSizes = {
  sm: "text-xs",
  md: "text-sm",
  lg: "text-base",
} as const;

export const zuiTreeViewItemBase =
  "relative flex w-full items-center gap-2 rounded-lg pr-2 text-left font-medium outline-none transition select-none cursor-pointer hover:bg-[var(--zui-tree-view-item-hover,var(--zui-surface-hover,#0000000d))] dark:hover:bg-[var(--zui-tree-view-item-hover-dark,var(--zui-surface-hover-dark,#ffffff0d))] focus-visible:ring-2 focus-visible:ring-[var(--zui-tree-view-ring-focus,var(--zui-focus-ring,#0000004d))] dark:focus-visible:ring-[var(--zui-tree-view-ring-focus-dark,var(--zui-focus-ring-dark,#ffffff4d))] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50";

export const zuiTreeViewItemSizes = {
  sm: "py-1 text-xs",
  md: "py-1.5 text-sm",
  lg: "py-2 text-base",
} as const;

export const zuiTreeViewItemAppearances = {
  default:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,var(--zui-surface-soft,#0000000f))] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,var(--zui-surface-soft-dark,#ffffff14))] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  outline:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,var(--zui-surface-soft,#0000000f))] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,var(--zui-surface-soft-dark,#ffffff14))] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  ghost:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,var(--zui-surface-soft,#0000000f))] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,var(--zui-surface-soft-dark,#ffffff14))] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  card: "data-[selected=true]:bg-[var(--zui-tree-view-selected,var(--zui-surface-soft,#00000014))] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,var(--zui-surface-soft-dark,#ffffff1f))] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  separated:
    "data-[selected=true]:bg-[var(--zui-tree-view-selected,var(--zui-surface-soft,#00000014))] dark:data-[selected=true]:bg-[var(--zui-tree-view-selected-dark,var(--zui-surface-soft-dark,#ffffff1f))] data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg,var(--zui-fg,oklch(20.8%_0.042_265.755)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-selected-fg-dark,var(--zui-brand-fg-dark,#ffffff))]",
  sky: "data-[selected=true]:bg-[var(--zui-tree-view-sky-selected,var(--zui-color-sky,oklch(95.1%_0.026_236.824)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-sky-selected-dark,var(--zui-color-sky-dark,oklch(58.8%_0.158_241.966_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-sky-selected-fg,var(--zui-fg,oklch(44.3%_0.11_240.79)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-sky-selected-fg-dark,var(--zui-fg-dark,oklch(82.8%_0.111_230.318)))]",
  rose: "data-[selected=true]:bg-[var(--zui-tree-view-rose-selected,var(--zui-color-rose,oklch(94.1%_0.03_12.58)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-rose-selected-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-rose-selected-fg,var(--zui-fg,oklch(45.5%_0.188_13.697)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-rose-selected-fg-dark,var(--zui-fg-dark,oklch(81%_0.117_11.638)))]",
  purple:
    "data-[selected=true]:bg-[var(--zui-tree-view-purple-selected,var(--zui-color-purple,oklch(94.6%_0.033_307.174)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-purple-selected-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-purple-selected-fg,var(--zui-fg,oklch(43.8%_0.218_303.724)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-purple-selected-fg-dark,var(--zui-fg-dark,oklch(82.7%_0.119_306.383)))]",
  pink: "data-[selected=true]:bg-[var(--zui-tree-view-pink-selected,var(--zui-color-pink,oklch(94.8%_0.028_342.258)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-pink-selected-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-pink-selected-fg,var(--zui-fg,oklch(45.9%_0.187_3.815)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-pink-selected-fg-dark,var(--zui-fg-dark,oklch(82.3%_0.12_346.018)))]",
  orange:
    "data-[selected=true]:bg-[var(--zui-tree-view-orange-selected,var(--zui-color-orange,oklch(95.4%_0.038_75.164)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-orange-selected-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-orange-selected-fg,var(--zui-fg,oklch(47%_0.157_37.304)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-orange-selected-fg-dark,var(--zui-fg-dark,oklch(83.7%_0.128_66.29)))]",
  yellow:
    "data-[selected=true]:bg-[var(--zui-tree-view-yellow-selected,var(--zui-color-yellow,oklch(97.3%_0.071_103.193)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-yellow-selected-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-yellow-selected-fg,var(--zui-fg,oklch(47.6%_0.114_61.907)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-yellow-selected-fg-dark,var(--zui-fg-dark,oklch(90.5%_0.182_98.111)))]",
  teal: "data-[selected=true]:bg-[var(--zui-tree-view-teal-selected,var(--zui-color-teal,oklch(95.3%_0.051_180.801)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-teal-selected-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-teal-selected-fg,var(--zui-fg,oklch(43.7%_0.078_188.216)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-teal-selected-fg-dark,var(--zui-fg-dark,oklch(85.5%_0.138_181.071)))]",
  indigo:
    "data-[selected=true]:bg-[var(--zui-tree-view-indigo-selected,var(--zui-color-indigo,oklch(93%_0.034_272.788)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-indigo-selected-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-indigo-selected-fg,var(--zui-fg,oklch(39.8%_0.195_277.366)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-indigo-selected-fg-dark,var(--zui-fg-dark,oklch(78.5%_0.115_274.713)))]",
  emerald:
    "data-[selected=true]:bg-[var(--zui-tree-view-emerald-selected,var(--zui-color-emerald,oklch(95%_0.052_163.051)))] dark:data-[selected=true]:bg-[var(--zui-tree-view-emerald-selected-dark,var(--zui-color-emerald-dark,oklch(59.6%_0.145_163.225_/_0.16)))] data-[selected=true]:text-[color:var(--zui-tree-view-emerald-selected-fg,var(--zui-fg,oklch(43.2%_0.095_166.913)))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-emerald-selected-fg-dark,var(--zui-fg-dark,oklch(84.5%_0.143_164.978)))]",
  "gradient-blue":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-blue-from,var(--zui-color-blue,oklch(80.9%_0.105_251.813)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-blue-to,var(--zui-color-purple,oklch(82.7%_0.119_306.383)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-blue-from-dark,var(--zui-color-blue-dark,oklch(54.6%_0.245_262.881)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-blue-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-green":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-green-from,var(--zui-color-green,oklch(87.1%_0.15_154.449)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-green-to,var(--zui-color-lime,oklch(89.7%_0.196_126.665)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-green-from-dark,var(--zui-color-green-dark,oklch(62.7%_0.194_149.214)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-green-to-dark,var(--zui-color-lime-dark,oklch(64.8%_0.2_131.684)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-red":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-red-from,var(--zui-color-red,oklch(80.8%_0.114_19.571)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-red-to,var(--zui-color-pink,oklch(82.3%_0.12_346.018)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-red-from-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-red-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-yellow":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-yellow-from,var(--zui-color-yellow,oklch(90.5%_0.182_98.111)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-yellow-to,var(--zui-color-orange,oklch(83.7%_0.128_66.29)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-yellow-from-dark,var(--zui-color-yellow-dark,oklch(68.1%_0.162_75.834)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-yellow-to-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-purple":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-purple-from,var(--zui-color-purple,oklch(82.7%_0.119_306.383)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-purple-to,var(--zui-color-pink,oklch(82.3%_0.12_346.018)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-purple-from-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-purple-to-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-teal":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-teal-from,var(--zui-color-teal,oklch(85.5%_0.138_181.071)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-teal-to,var(--zui-color-cyan,oklch(86.5%_0.127_207.078)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-teal-from-dark,var(--zui-color-teal-dark,oklch(60%_0.118_184.704)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-teal-to-dark,var(--zui-color-cyan-dark,oklch(60.9%_0.126_221.723)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-indigo":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-indigo-from,var(--zui-color-indigo,oklch(78.5%_0.115_274.713)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-indigo-to,var(--zui-color-purple,oklch(82.7%_0.119_306.383)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-indigo-from-dark,var(--zui-color-indigo-dark,oklch(51.1%_0.262_276.966)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-indigo-to-dark,var(--zui-color-purple-dark,oklch(55.8%_0.288_302.321)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-pink":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-pink-from,var(--zui-color-pink,oklch(82.3%_0.12_346.018)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-pink-to,var(--zui-color-rose,oklch(81%_0.117_11.638)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-pink-from-dark,var(--zui-color-pink-dark,oklch(59.2%_0.249_0.584)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-pink-to-dark,var(--zui-color-rose-dark,oklch(58.6%_0.253_17.585)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  "gradient-orange":
    "data-[selected=true]:bg-linear-to-r data-[selected=true]:from-[var(--zui-tree-view-gradient-orange-from,var(--zui-color-orange,oklch(83.7%_0.128_66.29)))] data-[selected=true]:to-[var(--zui-tree-view-gradient-orange-to,var(--zui-color-red,oklch(80.8%_0.114_19.571)))] dark:data-[selected=true]:from-[var(--zui-tree-view-gradient-orange-from-dark,var(--zui-color-orange-dark,oklch(64.6%_0.222_41.116)))] dark:data-[selected=true]:to-[var(--zui-tree-view-gradient-orange-to-dark,var(--zui-color-red-dark,oklch(57.7%_0.245_27.325)))] data-[selected=true]:text-[color:var(--zui-tree-view-gradient-fg,var(--zui-brand-fg,#ffffff))]",
  blue: "hover:bg-[var(--zui-tree-view-item-blue-bg-hover,var(--zui-color-blue,#2563eb18))] dark:hover:bg-[var(--zui-tree-view-item-blue-bg-hover-dark,var(--zui-color-blue-dark,#3b82f62e))] hover:text-[color:var(--zui-tree-view-item-blue-fg-hover,var(--zui-color-blue,#2563eb))] dark:hover:text-[color:var(--zui-tree-view-item-blue-fg-hover-dark,var(--zui-color-blue-dark,#3b82f6))] data-[selected=true]:bg-[var(--zui-tree-view-item-blue-bg,var(--zui-color-blue,#2563eb14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-blue-bg-dark,var(--zui-color-blue-dark,#3b82f624))] data-[selected=true]:text-[color:var(--zui-tree-view-item-blue-fg,var(--zui-color-blue,#2563eb))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-blue-fg-dark,var(--zui-color-blue-dark,#3b82f6))]",
  cyan: "hover:bg-[var(--zui-tree-view-item-cyan-bg-hover,var(--zui-color-cyan,#0891b218))] dark:hover:bg-[var(--zui-tree-view-item-cyan-bg-hover-dark,var(--zui-color-cyan-dark,#22d3ee2e))] hover:text-[color:var(--zui-tree-view-item-cyan-fg-hover,var(--zui-color-cyan,#0891b2))] dark:hover:text-[color:var(--zui-tree-view-item-cyan-fg-hover-dark,var(--zui-color-cyan-dark,#22d3ee))] data-[selected=true]:bg-[var(--zui-tree-view-item-cyan-bg,var(--zui-color-cyan,#0891b214))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-cyan-bg-dark,var(--zui-color-cyan-dark,#22d3ee24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-cyan-fg,var(--zui-color-cyan,#0891b2))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-cyan-fg-dark,var(--zui-color-cyan-dark,#22d3ee))]",
  green:
    "hover:bg-[var(--zui-tree-view-item-green-bg-hover,var(--zui-color-green,#16a34a18))] dark:hover:bg-[var(--zui-tree-view-item-green-bg-hover-dark,var(--zui-color-green-dark,#22c55e2e))] hover:text-[color:var(--zui-tree-view-item-green-fg-hover,var(--zui-color-green,#16a34a))] dark:hover:text-[color:var(--zui-tree-view-item-green-fg-hover-dark,var(--zui-color-green-dark,#22c55e))] data-[selected=true]:bg-[var(--zui-tree-view-item-green-bg,var(--zui-color-green,#16a34a14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-green-bg-dark,var(--zui-color-green-dark,#22c55e24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-green-fg,var(--zui-color-green,#16a34a))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-green-fg-dark,var(--zui-color-green-dark,#22c55e))]",
  lime: "hover:bg-[var(--zui-tree-view-item-lime-bg-hover,var(--zui-color-lime,#65a30d18))] dark:hover:bg-[var(--zui-tree-view-item-lime-bg-hover-dark,var(--zui-color-lime-dark,#a3e6352e))] hover:text-[color:var(--zui-tree-view-item-lime-fg-hover,var(--zui-color-lime,#65a30d))] dark:hover:text-[color:var(--zui-tree-view-item-lime-fg-hover-dark,var(--zui-color-lime-dark,#a3e635))] data-[selected=true]:bg-[var(--zui-tree-view-item-lime-bg,var(--zui-color-lime,#65a30d14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-lime-bg-dark,var(--zui-color-lime-dark,#a3e63524))] data-[selected=true]:text-[color:var(--zui-tree-view-item-lime-fg,var(--zui-color-lime,#65a30d))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-lime-fg-dark,var(--zui-color-lime-dark,#a3e635))]",
  mint: "hover:bg-[var(--zui-tree-view-item-mint-bg-hover,var(--zui-color-mint,#10b98118))] dark:hover:bg-[var(--zui-tree-view-item-mint-bg-hover-dark,var(--zui-color-mint-dark,#6ee7b72e))] hover:text-[color:var(--zui-tree-view-item-mint-fg-hover,var(--zui-color-mint,#10b981))] dark:hover:text-[color:var(--zui-tree-view-item-mint-fg-hover-dark,var(--zui-color-mint-dark,#6ee7b7))] data-[selected=true]:bg-[var(--zui-tree-view-item-mint-bg,var(--zui-color-mint,#10b98114))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-mint-bg-dark,var(--zui-color-mint-dark,#6ee7b724))] data-[selected=true]:text-[color:var(--zui-tree-view-item-mint-fg,var(--zui-color-mint,#10b981))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-mint-fg-dark,var(--zui-color-mint-dark,#6ee7b7))]",
  ocean:
    "hover:bg-[var(--zui-tree-view-item-ocean-bg-hover,var(--zui-color-ocean,#0284c718))] dark:hover:bg-[var(--zui-tree-view-item-ocean-bg-hover-dark,var(--zui-color-ocean-dark,#38bdf82e))] hover:text-[color:var(--zui-tree-view-item-ocean-fg-hover,var(--zui-color-ocean,#0284c7))] dark:hover:text-[color:var(--zui-tree-view-item-ocean-fg-hover-dark,var(--zui-color-ocean-dark,#38bdf8))] data-[selected=true]:bg-[var(--zui-tree-view-item-ocean-bg,var(--zui-color-ocean,#0284c714))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-ocean-bg-dark,var(--zui-color-ocean-dark,#38bdf824))] data-[selected=true]:text-[color:var(--zui-tree-view-item-ocean-fg,var(--zui-color-ocean,#0284c7))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-ocean-fg-dark,var(--zui-color-ocean-dark,#38bdf8))]",
  sapphire:
    "hover:bg-[var(--zui-tree-view-item-sapphire-bg-hover,var(--zui-color-sapphire,#1d4ed818))] dark:hover:bg-[var(--zui-tree-view-item-sapphire-bg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa2e))] hover:text-[color:var(--zui-tree-view-item-sapphire-fg-hover,var(--zui-color-sapphire,#1d4ed8))] dark:hover:text-[color:var(--zui-tree-view-item-sapphire-fg-hover-dark,var(--zui-color-sapphire-dark,#60a5fa))] data-[selected=true]:bg-[var(--zui-tree-view-item-sapphire-bg,var(--zui-color-sapphire,#1d4ed814))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-sapphire-bg-dark,var(--zui-color-sapphire-dark,#60a5fa24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-sapphire-fg,var(--zui-color-sapphire,#1d4ed8))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-sapphire-fg-dark,var(--zui-color-sapphire-dark,#60a5fa))]",
  lavender:
    "hover:bg-[var(--zui-tree-view-item-lavender-bg-hover,var(--zui-color-lavender,#8b5cf618))] dark:hover:bg-[var(--zui-tree-view-item-lavender-bg-hover-dark,var(--zui-color-lavender-dark,#a78bfa2e))] hover:text-[color:var(--zui-tree-view-item-lavender-fg-hover,var(--zui-color-lavender,#8b5cf6))] dark:hover:text-[color:var(--zui-tree-view-item-lavender-fg-hover-dark,var(--zui-color-lavender-dark,#a78bfa))] data-[selected=true]:bg-[var(--zui-tree-view-item-lavender-bg,var(--zui-color-lavender,#8b5cf614))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-lavender-bg-dark,var(--zui-color-lavender-dark,#a78bfa24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-lavender-fg,var(--zui-color-lavender,#8b5cf6))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-lavender-fg-dark,var(--zui-color-lavender-dark,#a78bfa))]",
  ruby: "hover:bg-[var(--zui-tree-view-item-ruby-bg-hover,var(--zui-color-ruby,#be123c18))] dark:hover:bg-[var(--zui-tree-view-item-ruby-bg-hover-dark,var(--zui-color-ruby-dark,#fb71852e))] hover:text-[color:var(--zui-tree-view-item-ruby-fg-hover,var(--zui-color-ruby,#be123c))] dark:hover:text-[color:var(--zui-tree-view-item-ruby-fg-hover-dark,var(--zui-color-ruby-dark,#fb7185))] data-[selected=true]:bg-[var(--zui-tree-view-item-ruby-bg,var(--zui-color-ruby,#be123c14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-ruby-bg-dark,var(--zui-color-ruby-dark,#fb718524))] data-[selected=true]:text-[color:var(--zui-tree-view-item-ruby-fg,var(--zui-color-ruby,#be123c))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-ruby-fg-dark,var(--zui-color-ruby-dark,#fb7185))]",
  red: "hover:bg-[var(--zui-tree-view-item-red-bg-hover,var(--zui-color-red,#dc262618))] dark:hover:bg-[var(--zui-tree-view-item-red-bg-hover-dark,var(--zui-color-red-dark,#ef44442e))] hover:text-[color:var(--zui-tree-view-item-red-fg-hover,var(--zui-color-red,#dc2626))] dark:hover:text-[color:var(--zui-tree-view-item-red-fg-hover-dark,var(--zui-color-red-dark,#ef4444))] data-[selected=true]:bg-[var(--zui-tree-view-item-red-bg,var(--zui-color-red,#dc262614))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-red-bg-dark,var(--zui-color-red-dark,#ef444424))] data-[selected=true]:text-[color:var(--zui-tree-view-item-red-fg,var(--zui-color-red,#dc2626))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-red-fg-dark,var(--zui-color-red-dark,#ef4444))]",
  slate:
    "hover:bg-[var(--zui-tree-view-item-slate-bg-hover,var(--zui-color-slate,#47556918))] dark:hover:bg-[var(--zui-tree-view-item-slate-bg-hover-dark,var(--zui-color-slate-dark,#64748b2e))] hover:text-[color:var(--zui-tree-view-item-slate-fg-hover,var(--zui-color-slate,#475569))] dark:hover:text-[color:var(--zui-tree-view-item-slate-fg-hover-dark,var(--zui-color-slate-dark,#64748b))] data-[selected=true]:bg-[var(--zui-tree-view-item-slate-bg,var(--zui-color-slate,#47556914))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-slate-bg-dark,var(--zui-color-slate-dark,#64748b24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-slate-fg,var(--zui-color-slate,#475569))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-slate-fg-dark,var(--zui-color-slate-dark,#64748b))]",
  zinc: "hover:bg-[var(--zui-tree-view-item-zinc-bg-hover,var(--zui-color-zinc,#52525b18))] dark:hover:bg-[var(--zui-tree-view-item-zinc-bg-hover-dark,var(--zui-color-zinc-dark,#71717a2e))] hover:text-[color:var(--zui-tree-view-item-zinc-fg-hover,var(--zui-color-zinc,#52525b))] dark:hover:text-[color:var(--zui-tree-view-item-zinc-fg-hover-dark,var(--zui-color-zinc-dark,#71717a))] data-[selected=true]:bg-[var(--zui-tree-view-item-zinc-bg,var(--zui-color-zinc,#52525b14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-zinc-bg-dark,var(--zui-color-zinc-dark,#71717a24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-zinc-fg,var(--zui-color-zinc,#52525b))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-zinc-fg-dark,var(--zui-color-zinc-dark,#71717a))]",
  stone:
    "hover:bg-[var(--zui-tree-view-item-stone-bg-hover,var(--zui-color-stone,#57534e18))] dark:hover:bg-[var(--zui-tree-view-item-stone-bg-hover-dark,var(--zui-color-stone-dark,#78716c2e))] hover:text-[color:var(--zui-tree-view-item-stone-fg-hover,var(--zui-color-stone,#57534e))] dark:hover:text-[color:var(--zui-tree-view-item-stone-fg-hover-dark,var(--zui-color-stone-dark,#78716c))] data-[selected=true]:bg-[var(--zui-tree-view-item-stone-bg,var(--zui-color-stone,#57534e14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-stone-bg-dark,var(--zui-color-stone-dark,#78716c24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-stone-fg,var(--zui-color-stone,#57534e))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-stone-fg-dark,var(--zui-color-stone-dark,#78716c))]",
  royal:
    "hover:bg-[var(--zui-tree-view-item-royal-bg-hover,var(--zui-color-royal,#4338ca18))] dark:hover:bg-[var(--zui-tree-view-item-royal-bg-hover-dark,var(--zui-color-royal-dark,#818cf82e))] hover:text-[color:var(--zui-tree-view-item-royal-fg-hover,var(--zui-color-royal,#4338ca))] dark:hover:text-[color:var(--zui-tree-view-item-royal-fg-hover-dark,var(--zui-color-royal-dark,#818cf8))] data-[selected=true]:bg-[var(--zui-tree-view-item-royal-bg,var(--zui-color-royal,#4338ca14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-royal-bg-dark,var(--zui-color-royal-dark,#818cf824))] data-[selected=true]:text-[color:var(--zui-tree-view-item-royal-fg,var(--zui-color-royal,#4338ca))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-royal-fg-dark,var(--zui-color-royal-dark,#818cf8))]",
  electric:
    "hover:bg-[var(--zui-tree-view-item-electric-bg-hover,var(--zui-color-electric,#0ea5e918))] dark:hover:bg-[var(--zui-tree-view-item-electric-bg-hover-dark,var(--zui-color-electric-dark,#38bdf82e))] hover:text-[color:var(--zui-tree-view-item-electric-fg-hover,var(--zui-color-electric,#0ea5e9))] dark:hover:text-[color:var(--zui-tree-view-item-electric-fg-hover-dark,var(--zui-color-electric-dark,#38bdf8))] data-[selected=true]:bg-[var(--zui-tree-view-item-electric-bg,var(--zui-color-electric,#0ea5e914))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-electric-bg-dark,var(--zui-color-electric-dark,#38bdf824))] data-[selected=true]:text-[color:var(--zui-tree-view-item-electric-fg,var(--zui-color-electric,#0ea5e9))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-electric-fg-dark,var(--zui-color-electric-dark,#38bdf8))]",
  forest:
    "hover:bg-[var(--zui-tree-view-item-forest-bg-hover,var(--zui-color-forest,#16653418))] dark:hover:bg-[var(--zui-tree-view-item-forest-bg-hover-dark,var(--zui-color-forest-dark,#4ade802e))] hover:text-[color:var(--zui-tree-view-item-forest-fg-hover,var(--zui-color-forest,#166534))] dark:hover:text-[color:var(--zui-tree-view-item-forest-fg-hover-dark,var(--zui-color-forest-dark,#4ade80))] data-[selected=true]:bg-[var(--zui-tree-view-item-forest-bg,var(--zui-color-forest,#16653414))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-forest-bg-dark,var(--zui-color-forest-dark,#4ade8024))] data-[selected=true]:text-[color:var(--zui-tree-view-item-forest-fg,var(--zui-color-forest,#166534))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-forest-fg-dark,var(--zui-color-forest-dark,#4ade80))]",
  sunset:
    "hover:bg-[var(--zui-tree-view-item-sunset-bg-hover,var(--zui-color-sunset,#ea580c18))] dark:hover:bg-[var(--zui-tree-view-item-sunset-bg-hover-dark,var(--zui-color-sunset-dark,#fb923c2e))] hover:text-[color:var(--zui-tree-view-item-sunset-fg-hover,var(--zui-color-sunset,#ea580c))] dark:hover:text-[color:var(--zui-tree-view-item-sunset-fg-hover-dark,var(--zui-color-sunset-dark,#fb923c))] data-[selected=true]:bg-[var(--zui-tree-view-item-sunset-bg,var(--zui-color-sunset,#ea580c14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-sunset-bg-dark,var(--zui-color-sunset-dark,#fb923c24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-sunset-fg,var(--zui-color-sunset,#ea580c))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-sunset-fg-dark,var(--zui-color-sunset-dark,#fb923c))]",
  magenta:
    "hover:bg-[var(--zui-tree-view-item-magenta-bg-hover,var(--zui-color-magenta,#c026d318))] dark:hover:bg-[var(--zui-tree-view-item-magenta-bg-hover-dark,var(--zui-color-magenta-dark,#e879f92e))] hover:text-[color:var(--zui-tree-view-item-magenta-fg-hover,var(--zui-color-magenta,#c026d3))] dark:hover:text-[color:var(--zui-tree-view-item-magenta-fg-hover-dark,var(--zui-color-magenta-dark,#e879f9))] data-[selected=true]:bg-[var(--zui-tree-view-item-magenta-bg,var(--zui-color-magenta,#c026d314))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-magenta-bg-dark,var(--zui-color-magenta-dark,#e879f924))] data-[selected=true]:text-[color:var(--zui-tree-view-item-magenta-fg,var(--zui-color-magenta,#c026d3))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-magenta-fg-dark,var(--zui-color-magenta-dark,#e879f9))]",
  crimson:
    "hover:bg-[var(--zui-tree-view-item-crimson-bg-hover,var(--zui-color-crimson,#b91c1c18))] dark:hover:bg-[var(--zui-tree-view-item-crimson-bg-hover-dark,var(--zui-color-crimson-dark,#f871712e))] hover:text-[color:var(--zui-tree-view-item-crimson-fg-hover,var(--zui-color-crimson,#b91c1c))] dark:hover:text-[color:var(--zui-tree-view-item-crimson-fg-hover-dark,var(--zui-color-crimson-dark,#f87171))] data-[selected=true]:bg-[var(--zui-tree-view-item-crimson-bg,var(--zui-color-crimson,#b91c1c14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-crimson-bg-dark,var(--zui-color-crimson-dark,#f8717124))] data-[selected=true]:text-[color:var(--zui-tree-view-item-crimson-fg,var(--zui-color-crimson,#b91c1c))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-crimson-fg-dark,var(--zui-color-crimson-dark,#f87171))]",
  aqua: "hover:bg-[var(--zui-tree-view-item-aqua-bg-hover,var(--zui-color-aqua,#0f766e18))] dark:hover:bg-[var(--zui-tree-view-item-aqua-bg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf2e))] hover:text-[color:var(--zui-tree-view-item-aqua-fg-hover,var(--zui-color-aqua,#0f766e))] dark:hover:text-[color:var(--zui-tree-view-item-aqua-fg-hover-dark,var(--zui-color-aqua-dark,#2dd4bf))] data-[selected=true]:bg-[var(--zui-tree-view-item-aqua-bg,var(--zui-color-aqua,#0f766e14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-aqua-bg-dark,var(--zui-color-aqua-dark,#2dd4bf24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-aqua-fg,var(--zui-color-aqua,#0f766e))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-aqua-fg-dark,var(--zui-color-aqua-dark,#2dd4bf))]",
  plum: "hover:bg-[var(--zui-tree-view-item-plum-bg-hover,var(--zui-color-plum,#7e22ce18))] dark:hover:bg-[var(--zui-tree-view-item-plum-bg-hover-dark,var(--zui-color-plum-dark,#c084fc2e))] hover:text-[color:var(--zui-tree-view-item-plum-fg-hover,var(--zui-color-plum,#7e22ce))] dark:hover:text-[color:var(--zui-tree-view-item-plum-fg-hover-dark,var(--zui-color-plum-dark,#c084fc))] data-[selected=true]:bg-[var(--zui-tree-view-item-plum-bg,var(--zui-color-plum,#7e22ce14))] dark:data-[selected=true]:bg-[var(--zui-tree-view-item-plum-bg-dark,var(--zui-color-plum-dark,#c084fc24))] data-[selected=true]:text-[color:var(--zui-tree-view-item-plum-fg,var(--zui-color-plum,#7e22ce))] dark:data-[selected=true]:text-[color:var(--zui-tree-view-item-plum-fg-dark,var(--zui-color-plum-dark,#c084fc))]",
} as const;

export const zuiTreeViewChevron =
  "inline-flex h-5 w-5 shrink-0 items-center justify-center rounded text-[color:var(--zui-tree-view-chevron,var(--zui-fg-muted,oklch(55.5%_0.041_257.417)))] dark:text-[color:var(--zui-tree-view-chevron-dark,var(--zui-fg-muted-dark,oklch(70.4%_0.04_256.788)))] transition-transform duration-200 data-[expanded=true]:rotate-90";

export const zuiTreeViewIcon =
  "inline-flex shrink-0 items-center justify-center text-[color:var(--zui-tree-view-icon,var(--zui-fg-muted,oklch(55.5%_0.041_257.417)))] dark:text-[color:var(--zui-tree-view-icon-dark,var(--zui-fg-muted-dark,oklch(70.4%_0.04_256.788)))]";

export const zuiTreeViewGuide =
  "border-l border-[color:var(--zui-tree-view-guide,var(--zui-border,#0000001a))] dark:border-[color:var(--zui-tree-view-guide-dark,var(--zui-border-dark,#ffffff1a))]";
