import type { PaginationProps } from "@zentauri-ui/zentauri-components/ui/pagination";

export { PREVIEW_SECTION_CLASS as PAGINATION_CODE_EXAMPLES_SECTION_CLASS } from "@/components/common/Section";

export const PAGINATION_APPEARANCES = [
  "default",
  "secondary",
  "destructive",
  "outline",
  "ghost",
  "link",
  "glass",
  "emerald",
  "indigo",
  "purple",
  "pink",
  "rose",
  "sky",
  "teal",
  "yellow",
  "orange",
  "gray",
  "amber",
  "violet",
  "gradient-blue",
  "gradient-green",
  "gradient-red",
  "gradient-yellow",
  "gradient-purple",
  "gradient-teal",
  "gradient-indigo",
  "gradient-pink",
  "gradient-orange",
  "blue",
  "cyan",
  "green",
  "lime",
  "mint",
  "ocean",
  "sapphire",
  "lavender",
  "ruby",
  "red",
  "slate",
  "zinc",
  "stone",
  "royal",
  "electric",
  "forest",
  "sunset",
  "magenta",
  "crimson",
  "aqua",
  "plum",
] as const satisfies readonly NonNullable<PaginationProps["appearance"]>[];

export const PAGINATION_SIZES = [
  "sm",
  "md",
  "lg",
  "xl",
  "icon",
] as const satisfies readonly NonNullable<PaginationProps["size"]>[];
