import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { defineConfig } from "tsup";

const uiComponentNames = [
  "accordion",
  "alert",
  "animated-number",
  "api-endpoint-card",
  "api-response-viewer",
  "audio-player",
  "avatar",
  "badge",
  "breadcrumb",
  "buttons",
  "card",
  "checkbox",
  "code-block",
  "code-diff",
  "combobox",
  "command",
  "console-viewer",
  "context-menu",
  "copy-button",
  "data-table",
  "divider",
  "drawer",
  "dropdown",
  "dynamic-stepper",
  "empty-state",
  "file-upload",
  "hash-generator",
  "http-request-viewer",
  "http-status-badge",
  "inputs",
  "json-viewer",
  "kbd",
  "log-viewer",
  "marquee",
  "modal",
  "network-status",
  "otp-input",
  "package-install-command",
  "pagination",
  "password-strength-meter",
  "popover",
  "progress",
  "qr-code",
  "qr-scanner",
  "rating",
  "radio-group",
  "relative-time",
  "request-timeline-viewer",
  "scroll-area",
  "search",
  "secret-reveal",
  "select",
  "skeleton",
  "slider",
  "speech-recognition",
  "speech-synthesizer",
  "split-button",
  "table",
  "tabs",
  "terminal-emulator",
  "timezone-select",
  "timeline",
  "toast",
  "toggle",
  "tooltip",
  "tree-view",
  "typing-indicator",
  "typography",
  "world-clock",
] as const;

const chartEntryNames = [
  "area",
  "bar",
  "bubble",
  "funnel",
  "line",
  "pie",
  "radar",
  "scatter",
  "stacked-bar",
] as const;

const animationEntryNames = [
  "fade-in",
  "fade-out",
  "fade-up",
  "fade-down",
  "fade-left",
  "fade-right",
  "scale-in",
  "scale-out",
  "pop-in",
  "blur-in",
  "blur-out",
  "slide-up",
  "slide-down",
  "slide-left",
  "slide-right",
  "reveal-up",
  "reveal-down",
  "reveal-left",
  "reveal-right",
  "reveal-blur",
  "text-reveal",
  "text-shimmer",
  "rotate-in",
  "pulse",
  "ping",
  "shake",
  "bounce",
  "wiggle",
  "float",
  "spin",
  "flip",
  "flip-in",
  "tilt",
  "magnetic",
  "hover-lift",
  "hover-scale",
  "press",
  "reorder",
  "skeleton-shimmer",
  "progress",
  "parallax",
] as const;

const uiAnimatedComponentNames = [
  "accordion",
  "alert",
  "api-endpoint-card",
  "api-response-viewer",
  "avatar",
  "badge",
  "buttons",
  "card",
  "checkbox",
  "code-block",
  "command",
  "console-viewer",
  "copy-button",
  "divider",
  "drawer",
  "empty-state",
  "http-request-viewer",
  "inputs",
  "json-viewer",
  "kbd",
  "log-viewer",
  "modal",
  "network-status",
  "package-install-command",
  "password-strength-meter",
  "popover",
  "progress",
  "qr-code",
  "radio-group",
  "relative-time",
  "request-timeline-viewer",
  "secret-reveal",
  "skeleton",
  "speech-recognition",
  "speech-synthesizer",
  "spinner",
  "table",
  "tabs",
  "terminal-emulator",
  "timeline",
  "toast",
  "toggle",
  "tooltip",
  "tree-view",
  "typing-indicator",
  "world-clock",
] as const;

const hooksEntryNames = [
  "useBodyScrollLock",
  "useClickOutside",
  "useClipboard",
  "useControllableState",
  "useCookie",
  "useCountdown",
  "useDateTimeFormat",
  "useDebouncedValue",
  "useDisclosure",
  "useDocumentTitle",
  "useDurationFormat",
  "useDynamicStepper",
  "useEventListener",
  "useFocusManagement",
  "useGeolocation",
  "useHotkeys",
  "useHash",
  "useHover",
  "useIdleTimeout",
  "useInterval",
  "useInView",
  "useIntersectionObserver",
  "useIsomorphicLayoutEffect",
  "useIsMounted",
  "useKeyPress",
  "useLocalStorage",
  "useLongPress",
  "useMediaQuery",
  "useNetworkStatus",
  "usePageVisibility",
  "usePagination",
  "usePrefersColorScheme",
  "usePrefersReducedMotion",
  "usePrevious",
  "useRelativeTime",
  "useResizeObserver",
  "useScrollPosition",
  "useSessionStorage",
  "useTableFilter",
  "useTableSort",
  "useThrottledCallback",
  "useTimeout",
  "useTimezone",
  "useToggle",
  "useVirtualList",
  "useWindowSize",
] as const;

const uiEntries = Object.fromEntries(
  uiComponentNames.map((name) => [`ui/${name}`, `src/ui/${name}/index.ts`]),
);

const chartEntries = Object.fromEntries(
  chartEntryNames.map((name) => [
    `charts/${name}`,
    `src/charts/${name}/index.ts`,
  ]),
);

const animationEntries = Object.fromEntries(
  animationEntryNames.map((name) => [
    `animations/${name}`,
    `src/animations/${name}/index.ts`,
  ]),
);

const uiAnimatedEntries = Object.fromEntries(
  uiAnimatedComponentNames.map((name) => [
    `ui/${name}/animated`,
    `src/ui/${name}/animated/index.ts`,
  ]),
);

const hooksEntries = {
  "hooks/utils": "src/lib/utils.ts",
  ...Object.fromEntries(
    hooksEntryNames.map((name) => [
      `hooks/${name}`,
      `src/hooks/${name}/index.ts`,
    ]),
  ),
};

export default defineConfig({
  entry: {
    "design-system/tokens": "src/design-system/tokens.ts",
    "design-system/facade": "src/lib/facade.ts",
    ...uiEntries,
    ...chartEntries,
    ...animationEntries,
    ...uiAnimatedEntries,
    ...hooksEntries,
  },
  format: ["esm", "cjs"],
  dts: false,
  clean: true,
  // Externalize peer deps and subpaths (e.g. react-icons/hi2) so they are never inlined.
  external: [
    "react",
    "react-dom",
    "clsx",
    "class-variance-authority",
    "tailwind-merge",
    "react-icons",
    "recharts",
    "framer-motion",
    /^react-icons\//,
    /^recharts/,
    /^framer-motion/,
  ],
  sourcemap: true,
  splitting: true,
  // Rollup treeshake can reorder output so tsup's `banner` no longer leads with
  // `"use client"`. Entry `index.ts` files include the directive for source clarity;
  // `scripts/prepend-use-client.mjs` runs after the build to enforce it on each UI entry.
  treeshake: true,
  async onSuccess() {
    execFileSync(
      "node",
      [join(process.cwd(), "scripts/prepend-use-client.mjs")],
      {
        stdio: "inherit",
      },
    );
  },
});
