import type { PreviewSeoDocument } from "@/lib/preview-seo";
import accordion from "@/content/seo/preview/components/accordion.json";
import alert from "@/content/seo/preview/components/alert.json";
import apiEndpointCard from "@/content/seo/preview/components/api-endpoint-card.json";
import audioPlayer from "@/content/seo/preview/components/audio-player.json";
import animations from "@/content/seo/preview/animations.json";
import animatedNumber from "@/content/seo/preview/components/animated-number.json";
import avatar from "@/content/seo/preview/components/avatar.json";
import badge from "@/content/seo/preview/components/badge.json";
import bentoGrid from "@/content/seo/preview/components/bento-grid.json";
import breadcrumb from "@/content/seo/preview/components/breadcrumb.json";
import buttons from "@/content/seo/preview/components/buttons.json";
import calendar from "@/content/seo/preview/components/calendar.json";
import card from "@/content/seo/preview/components/card.json";
import checkbox from "@/content/seo/preview/components/checkbox.json";
import codeBlock from "@/content/seo/preview/components/code-block.json";
import codeDiff from "@/content/seo/preview/components/code-diff.json";
import combobox from "@/content/seo/preview/components/combobox.json";
import command from "@/content/seo/preview/components/command.json";
import contextMenu from "@/content/seo/preview/components/context-menu.json";
import copyButton from "@/content/seo/preview/components/copy-button.json";
import dataTable from "@/content/seo/preview/components/data-table.json";
import datePicker from "@/content/seo/preview/components/date-picker.json";
import charts from "@/content/seo/preview/charts.json";
import divider from "@/content/seo/preview/components/divider.json";
import drawer from "@/content/seo/preview/components/drawer.json";
import dropdown from "@/content/seo/preview/components/dropdown.json";
import dynamicStepper from "@/content/seo/preview/components/dynamic-stepper.json";
import emptyState from "@/content/seo/preview/components/empty-state.json";
import hooks from "@/content/seo/preview/hooks/hooks.json";
import fileUpload from "@/content/seo/preview/components/file-upload.json";
import hashGenerator from "@/content/seo/preview/components/hash-generator.json";
import index from "@/content/seo/preview/components/index.json";
import inputs from "@/content/seo/preview/components/inputs.json";
import installation from "@/content/seo/preview/components/installation.json";
import jsonViewer from "@/content/seo/preview/components/json-viewer.json";
import consoleViewer from "@/content/seo/preview/components/console-viewer.json";
import terminalEmulator from "@/content/seo/preview/components/terminal-emulator.json";
import apiResponseViewer from "@/content/seo/preview/components/api-response-viewer.json";
import httpRequestViewer from "@/content/seo/preview/components/http-request-viewer.json";
import httpStatusBadge from "@/content/seo/preview/components/http-status-badge.json";
import requestTimelineViewer from "@/content/seo/preview/components/request-timeline-viewer.json";
import logViewer from "@/content/seo/preview/components/log-viewer.json";
import kbd from "@/content/seo/preview/components/kbd.json";
import marquee from "@/content/seo/preview/components/marquee.json";
import modal from "@/content/seo/preview/components/modal.json";
import networkStatus from "@/content/seo/preview/components/network-status.json";
import packageInstallCommand from "@/content/seo/preview/components/package-install-command.json";
import otpInput from "@/content/seo/preview/components/otp-input.json";
import pagination from "@/content/seo/preview/components/pagination.json";
import passwordStrengthMeter from "@/content/seo/preview/components/password-strength-meter.json";
import popover from "@/content/seo/preview/components/popover.json";
import progress from "@/content/seo/preview/components/progress.json";
import qrCode from "@/content/seo/preview/components/qr-code.json";
import qrScanner from "@/content/seo/preview/components/qr-scanner.json";
import rating from "@/content/seo/preview/components/rating.json";
import radioGroup from "@/content/seo/preview/components/radio-group.json";
import relativeTime from "@/content/seo/preview/components/relative-time.json";
import scrollArea from "@/content/seo/preview/components/scroll-area.json";
import secretReveal from "@/content/seo/preview/components/secret-reveal.json";
import select from "@/content/seo/preview/components/select.json";
import search from "@/content/seo/preview/components/search.json";
import skeleton from "@/content/seo/preview/components/skeleton.json";
import speechRecognition from "@/content/seo/preview/components/speech-recognition.json";
import speechSynthesizer from "@/content/seo/preview/components/speech-synthesizer.json";
import splitButton from "@/content/seo/preview/components/split-button.json";
import slider from "@/content/seo/preview/components/slider.json";
import spinner from "@/content/seo/preview/components/spinner.json";
import table from "@/content/seo/preview/components/table.json";
import tabs from "@/content/seo/preview/components/tabs.json";
import timezoneSelect from "@/content/seo/preview/components/timezone-select.json";
import timeline from "@/content/seo/preview/components/timeline.json";
import toast from "@/content/seo/preview/components/toast.json";
import toggle from "@/content/seo/preview/components/toggle.json";
import tokens from "@/content/seo/preview/components/tokens.json";
import tooltip from "@/content/seo/preview/components/tooltip.json";
import treeView from "@/content/seo/preview/components/tree-view.json";
import typingIndicator from "@/content/seo/preview/components/typing-indicator.json";
import typography from "@/content/seo/preview/components/typography.json";
import wizard from "@/content/seo/preview/components/wizard.json";
import worldClock from "@/content/seo/preview/components/world-clock.json";
import permission from "@/content/seo/preview/components/permission.json";

const previewSeoRegistry = {
  index: index as PreviewSeoDocument,
  installation: installation as PreviewSeoDocument,
  accordion: accordion as PreviewSeoDocument,
  alert: alert as PreviewSeoDocument,
  animations: animations as PreviewSeoDocument,
  "animated-number": animatedNumber as PreviewSeoDocument,
  "audio-player": audioPlayer as PreviewSeoDocument,
  avatar: avatar as PreviewSeoDocument,
  badge: badge as PreviewSeoDocument,
  "bento-grid": bentoGrid as PreviewSeoDocument,
  breadcrumb: breadcrumb as PreviewSeoDocument,
  buttons: buttons as PreviewSeoDocument,
  calendar: calendar as PreviewSeoDocument,
  card: card as PreviewSeoDocument,
  checkbox: checkbox as PreviewSeoDocument,
  "code-block": codeBlock as PreviewSeoDocument,
  "code-diff": codeDiff as PreviewSeoDocument,
  combobox: combobox as PreviewSeoDocument,
  command: command as PreviewSeoDocument,
  "context-menu": contextMenu as PreviewSeoDocument,
  "copy-button": copyButton as PreviewSeoDocument,
  "data-table": dataTable as PreviewSeoDocument,
  "date-picker": datePicker as PreviewSeoDocument,
  charts: charts as PreviewSeoDocument,
  divider: divider as PreviewSeoDocument,
  drawer: drawer as PreviewSeoDocument,
  dropdown: dropdown as PreviewSeoDocument,
  "dynamic-stepper": dynamicStepper as PreviewSeoDocument,
  "empty-state": emptyState as PreviewSeoDocument,
  hooks: hooks as PreviewSeoDocument,
  "file-upload": fileUpload as PreviewSeoDocument,
  "hash-generator": hashGenerator as PreviewSeoDocument,
  inputs: inputs as PreviewSeoDocument,
  "json-viewer": jsonViewer as PreviewSeoDocument,
  "console-viewer": consoleViewer as PreviewSeoDocument,
  "terminal-emulator": terminalEmulator as PreviewSeoDocument,
  "timezone-select": timezoneSelect as PreviewSeoDocument,
  "api-endpoint-card": apiEndpointCard as PreviewSeoDocument,
  "api-response-viewer": apiResponseViewer as PreviewSeoDocument,
  "http-request-viewer": httpRequestViewer as PreviewSeoDocument,
  "http-status-badge": httpStatusBadge as PreviewSeoDocument,
  "request-timeline-viewer": requestTimelineViewer as PreviewSeoDocument,
  "log-viewer": logViewer as PreviewSeoDocument,
  kbd: kbd as PreviewSeoDocument,
  marquee: marquee as PreviewSeoDocument,
  modal: modal as PreviewSeoDocument,
  "network-status": networkStatus as PreviewSeoDocument,
  "otp-input": otpInput as PreviewSeoDocument,
  "package-install-command": packageInstallCommand as PreviewSeoDocument,
  pagination: pagination as PreviewSeoDocument,
  "password-strength-meter": passwordStrengthMeter as PreviewSeoDocument,
  popover: popover as PreviewSeoDocument,
  progress: progress as PreviewSeoDocument,
  "qr-code": qrCode as PreviewSeoDocument,
  "qr-scanner": qrScanner as PreviewSeoDocument,
  rating: rating as PreviewSeoDocument,
  "radio-group": radioGroup as PreviewSeoDocument,
  "relative-time": relativeTime as PreviewSeoDocument,
  "scroll-area": scrollArea as PreviewSeoDocument,
  "secret-reveal": secretReveal as PreviewSeoDocument,
  select: select as PreviewSeoDocument,
  search: search as PreviewSeoDocument,
  skeleton: skeleton as PreviewSeoDocument,
  "speech-recognition": speechRecognition as PreviewSeoDocument,
  "speech-synthesizer": speechSynthesizer as PreviewSeoDocument,
  "split-button": splitButton as PreviewSeoDocument,
  slider: slider as PreviewSeoDocument,
  spinner: spinner as PreviewSeoDocument,
  table: table as PreviewSeoDocument,
  tabs: tabs as PreviewSeoDocument,
  timeline: timeline as PreviewSeoDocument,
  toast: toast as PreviewSeoDocument,
  toggle: toggle as PreviewSeoDocument,
  tokens: tokens as PreviewSeoDocument,
  tooltip: tooltip as PreviewSeoDocument,
  "tree-view": treeView as PreviewSeoDocument,
  "typing-indicator": typingIndicator as PreviewSeoDocument,
  typography: typography as PreviewSeoDocument,
  wizard: wizard as PreviewSeoDocument,
  "world-clock": worldClock as PreviewSeoDocument,
  permission: permission as PreviewSeoDocument,
} as const;

export type PreviewSeoSlug = keyof typeof previewSeoRegistry;

export function getPreviewSeo(slug: PreviewSeoSlug): PreviewSeoDocument {
  return previewSeoRegistry[slug];
}
