import type { ToastInput } from "@zentauri-ui/zentauri-components/ui/toast";

export { PREVIEW_SECTION_CLASS as TOAST_CODE_EXAMPLES_SECTION_CLASS } from "@/components/common/Section";

export const TOAST_APPEARANCES = [
  "default",
  "success",
  "warning",
  "error",
  "info",
  "ghost",
  "purple",
  "pink",
  "orange",
  "yellow",
  "teal",
  "indigo",
  "emerald",
  "gray",
  "amber",
  "violet",
  "gradient-blue",
  "gradient-green",
  "gradient-red",
  "gradient-yellow",
  "gradient-purple",
  "gradient-teal",
  "gradient-indigo",
  "gradient-pink",
  "gradient-orange",
  "blue",
  "cyan",
  "green",
  "lime",
  "mint",
  "ocean",
  "sapphire",
  "lavender",
  "ruby",
  "red",
  "slate",
  "zinc",
  "stone",
  "royal",
  "electric",
  "forest",
  "sunset",
  "magenta",
  "crimson",
  "aqua",
  "plum",
] as const satisfies readonly NonNullable<ToastInput["appearance"]>[];

export const TOAST_SIZES = [
  "sm",
  "md",
  "lg",
] as const satisfies readonly NonNullable<ToastInput["size"]>[];
