import type { SplitButtonAppearance, SplitButtonSize } from "./types";

export const SPLIT_BUTTON_APPEARANCES = [
  "default",
  "secondary",
  "destructive",
  "outline",
  "ghost",
  "link",
  "glass",
  "blue",
  "cyan",
  "green",
  "lime",
  "mint",
  "ocean",
  "sapphire",
  "lavender",
  "ruby",
  "red",
  "slate",
  "zinc",
  "stone",
  "royal",
  "electric",
  "forest",
  "sunset",
  "magenta",
  "crimson",
  "aqua",
  "plum",
  "emerald",
  "indigo",
  "purple",
  "pink",
  "rose",
  "sky",
  "teal",
  "yellow",
  "orange",
  "gray",
  "amber",
  "violet",
  "gradient-blue",
  "gradient-green",
  "gradient-red",
  "gradient-yellow",
  "gradient-purple",
  "gradient-teal",
  "gradient-indigo",
  "gradient-pink",
  "gradient-orange",
] as const satisfies readonly SplitButtonAppearance[];

export const SPLIT_BUTTON_SIZES = [
  "sm",
  "md",
  "lg",
  "xl",
] as const satisfies readonly SplitButtonSize[];

export const SPLIT_BUTTON_TRIGGER_ON = ["click", "hover"] as const;
