import type { HookPreviewSlug } from "@/lib/hook-preview-registry";

const PANEL_IMPORT =
  'import { HookDemoPanel } from "@/components/preview/hooks/hook-demo-panel";';

const bodyScrollLockFullSource = [
  '"use client";',
  "",
  'import { useBodyScrollLock } from "@zentauri-ui/zentauri-components/lib/useBodyScrollLock";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  'import { useState } from "react";',
  "",
  "export default function HookDemo() {",
  "  const [locked, setLocked] = useState(false);",
  "  useBodyScrollLock(locked);",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Toggle scroll lock on the document body. When locked, the page behind this",
  "        panel should not scroll.",
  "      </p>",
  '      <Button type="button" onClick={() => setLocked((v) => !v)}>',
  '        {locked ? "Unlock body scroll" : "Lock body scroll"}',
  "      </Button>",
  '      <div className="mt-6 h-64 overflow-auto rounded-lg border border-white/10 bg-slate-900/50 p-4 text-sm text-slate-400">',
  '        <p className="mb-2 font-medium text-slate-300">Tall inner scroll region</p>',
  "        {Array.from({ length: 24 }, (_, i) => (",
  '          <p key={i}>Line {i + 1} — scroll inside this box is independent of body lock.</p>',
  "        ))}",
  "      </div>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const clickOutsideFullSource = [
  '"use client";',
  "",
  'import { useClickOutside } from "@zentauri-ui/zentauri-components/lib/useClickOutside";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  'import { useRef, useState } from "react";',
  "",
  "export default function HookDemo() {",
  "  const [open, setOpen] = useState(true);",
  "  const ref = useRef<HTMLDivElement>(null);",
  "  useClickOutside({ ref, setOpen });",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        The panel starts open. Click outside the bordered region to close it.",
  "      </p>",
  "      {open ? (",
  "        <div",
  "          ref={ref}",
  '          className="rounded-xl border border-cyan-500/40 bg-cyan-950/30 p-6 text-center text-cyan-100"',
  "        >",
  "          Inside — click outside to dismiss",
  "        </div>",
  "      ) : (",
  '        <Button type="button" onClick={() => setOpen(true)}>',
  "          Reset panel",
  "        </Button>",
  "      )}",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const clipboardFullSource = [
  '"use client";',
  "",
  'import { useClipboard } from "@zentauri-ui/zentauri-components/lib/useClipboard";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const { copy, copied, error, reset } = useClipboard();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <div className="flex flex-wrap items-center gap-3">',
  '        <Button type="button" onClick={() => void copy("zentauri-ui-clipboard-demo")}>',
  "          Copy sample text",
  "        </Button>",
  '        <Button type="button" appearance="outline" onClick={reset}>',
  "          Reset",
  "        </Button>",
  "      </div>",
  '      <p className="mt-4 text-sm text-slate-400">',
  "        Status: ",
  "        {copied ? (",
  '          <span className="text-emerald-400">Copied</span>',
  "        ) : error ? (",
  '          <span className="text-rose-400">{error.message}</span>',
  "        ) : (",
  "          <span>Idle</span>",
  "        )}",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const controllableStateFullSource = [
  '"use client";',
  "",
  'import { useControllableState } from "@zentauri-ui/zentauri-components/lib/useControllableState";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  'import { useState } from "react";',
  "",
  "export default function HookDemo() {",
  '  const [mode, setMode] = useState<"uncontrolled" | "controlled">("uncontrolled");',
  "  const [controlled, setControlled] = useState(0);",
  "  const [value, setValue] = useControllableState({",
  "    value: mode === \"controlled\" ? controlled : undefined,",
  "    defaultValue: 0,",
  "    onChange: mode === \"controlled\" ? setControlled : undefined,",
  "  });",
  "",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <div className="mb-4 flex flex-wrap gap-2">',
  "        <Button",
  '          type="button"',
  '          size="sm"',
  '          appearance={mode === "uncontrolled" ? "default" : "outline"}',
  '          onClick={() => setMode("uncontrolled")}',
  "        >",
  "          Uncontrolled",
  "        </Button>",
  "        <Button",
  '          type="button"',
  '          size="sm"',
  '          appearance={mode === "controlled" ? "default" : "outline"}',
  "          onClick={() => {",
  '            setMode("controlled");',
  "            setControlled(value);",
  "          }}",
  "        >",
  "          Controlled",
  "        </Button>",
  "      </div>",
  '      <p className="mb-2 text-2xl font-semibold tabular-nums text-white">{value}</p>',
  '      <Button type="button" onClick={() => setValue((v) => v + 1)}>',
  "        Increment",
  "      </Button>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const debouncedValueFullSource = [
  '"use client";',
  "",
  'import { useDebouncedValue } from "@zentauri-ui/zentauri-components/lib/useDebouncedValue";',
  PANEL_IMPORT,
  'import { useState } from "react";',
  'import { Input } from "@zentauri-ui/zentauri-components/ui/inputs";',
  "",
  "export default function HookDemo() {",
  '  const [raw, setRaw] = useState("");',
  "  const debounced = useDebouncedValue(raw, 400);",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <label className="mb-2 block text-sm text-slate-400" htmlFor="debounce-input">',
  "        Type quickly — debounced value updates 400ms after you pause.",
  "      </label>",
  "      <Input",
  '        id="debounce-input"',
  '        appearance="info"',
  "        value={raw}",
  "        onChange={(e) => setRaw(e.target.value)}",
  '        placeholder="Search…"',
  "      />",
  '      <dl className="grid gap-2 text-sm sm:grid-cols-2">',
  '        <dt className="text-slate-500">Live</dt>',
  '        <dd className="font-mono text-cyan-200">{raw || "—"}</dd>',
  '        <dt className="text-slate-500">Debounced</dt>',
  '        <dd className="font-mono text-emerald-200">{debounced || "—"}</dd>',
  "      </dl>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const disclosureFullSource = [
  '"use client";',
  "",
  'import { useDisclosure } from "@zentauri-ui/zentauri-components/lib/useDisclosure";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const { isOpen, open, close, toggle } = useDisclosure({ defaultOpen: false });",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <div className="flex flex-wrap gap-2">',
  '        <Button type="button" onClick={open}>',
  "          Open",
  "        </Button>",
  '        <Button type="button" appearance="outline" onClick={close}>',
  "          Close",
  "        </Button>",
  '        <Button type="button" appearance="outline" onClick={toggle}>',
  "          Toggle",
  "        </Button>",
  "      </div>",
  '      <p className="mt-4 text-sm text-slate-400">',
  '        Panel is <span className="text-white">{isOpen ? "open" : "closed"}</span>.',
  "      </p>",
  "      {isOpen ? (",
  '        <div className="mt-4 rounded-lg border border-white/10 bg-slate-900/60 p-4 text-sm">',
  "          Disclosure content — use close or toggle to hide.",
  "        </div>",
  "      ) : null}",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const documentTitleFullSource = [
  '"use client";',
  "",
  'import { useDocumentTitle } from "@zentauri-ui/zentauri-components/lib/useDocumentTitle";',
  PANEL_IMPORT,
  'import { useState } from "react";',
  'import { Input } from "@zentauri-ui/zentauri-components/ui/inputs";',
  "",
  "export default function HookDemo() {",
  '  const [title, setTitle] = useState("Hooks preview");',
  "  useDocumentTitle({ title, restoreOnUnmount: true });",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Updates the browser tab title live. Leaving this page restores the previous",
  "        title when restoreOnUnmount is true.",
  "      </p>",
  "      <Input",
  '        appearance="info"',
  "        value={title}",
  "        onChange={(e) => setTitle(e.target.value)}",
  "      />",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const focusManagementFullSource = [
  '"use client";',
  "",
  'import { useFocusManagement } from "@zentauri-ui/zentauri-components/lib/useFocusManagement";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  'import { useRef, useState } from "react";',
  "",
  "export default function HookDemo() {",
  "  const [open, setOpen] = useState(false);",
  "  const contentRef = useRef<HTMLDivElement>(null);",
  "  useFocusManagement({ open, setOpen, contentRef });",
  "",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Opens a focus-managed region with Escape to close. Tab should stay inside",
  "        while open.",
  "      </p>",
  '      <Button type="button" onClick={() => setOpen(true)}>',
  "        Open dialog",
  "      </Button>",
  "      {open ? (",
  '        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" role="presentation">',
  "          <div",
  "            ref={contentRef}",
  '            role="dialog"',
  '            aria-modal="true"',
  '            aria-label="Focus trap demo"',
  "            tabIndex={-1}",
  '            className="max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl outline-none"',
  "          >",
  '            <p className="mb-4 text-sm text-slate-300">',
  "              Try Tab through these controls, then Escape.",
  "            </p>",
  '            <div className="flex flex-col gap-3">',
  '              <Button type="button">First action</Button>',
  '              <Button type="button" appearance="outline">',
  "                Second action",
  "              </Button>",
  '              <Button type="button" appearance="outline" onClick={() => setOpen(false)}>',
  "                Close",
  "              </Button>",
  "            </div>",
  "          </div>",
  "        </div>",
  "      ) : null}",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const hoverFullSource = [
  '"use client";',
  "",
  'import { useHover } from "@zentauri-ui/zentauri-components/lib/useHover";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const [ref, hovered] = useHover<HTMLDivElement>();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  "      <div",
  "        ref={ref}",
  "        className={`inline-flex cursor-default rounded-xl border px-8 py-6 text-lg transition-colors ${",
  "          hovered",
  '            ? "border-cyan-400/60 bg-cyan-950/40 text-cyan-100"',
  '            : "border-white/15 bg-slate-900/50 text-slate-300"',
  "        }`}",
  "      >",
  '        {hovered ? "Hovered" : "Hover this surface"}',
  "      </div>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const inViewFullSource = [
  '"use client";',
  "",
  'import { useInView } from "@zentauri-ui/zentauri-components/lib/useInView";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const [ref, inView] = useInView<HTMLDivElement>({ threshold: 0.35 });",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Scroll the sentinel into view — the hook reports intersection as a boolean.",
  "      </p>",
  '      <p className="mb-6 text-sm font-medium text-white">',
  "        In view: ",
  '        <span className={inView ? "text-emerald-400" : "text-slate-500"}>',
  '          {inView ? "yes" : "no"}',
  "        </span>",
  "      </p>",
  '      <div className="h-48 overflow-y-auto rounded-lg border border-white/10 bg-slate-900/40 p-4">',
  '        <div className="h-40 text-sm text-slate-500">Scroll down ↓</div>',
  "        <div",
  "          ref={ref}",
  '          className="my-4 flex h-24 items-center justify-center rounded-lg bg-cyan-950/50 text-cyan-100"',
  "        >",
  "          Sentinel",
  "        </div>",
  '        <div className="h-40 text-sm text-slate-500">End</div>',
  "      </div>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const intersectionObserverFullSource = [
  '"use client";',
  "",
  'import { useIntersectionObserver } from "@zentauri-ui/zentauri-components/lib/useIntersectionObserver";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const [ref, entry] = useIntersectionObserver<HTMLDivElement>({",
  "    threshold: [0, 0.5, 1],",
  "  });",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Raw observer entry — scroll the box to see intersectionRatio change.",
  "      </p>",
  '      <pre className="mb-4 max-h-28 overflow-auto rounded-lg border border-white/10 bg-slate-950/80 p-3 text-xs text-slate-300">',
  "        {entry",
  "          ? JSON.stringify(",
  "              {",
  "                isIntersecting: entry.isIntersecting,",
  "                intersectionRatio: entry.intersectionRatio,",
  "              },",
  "              null,",
  "              2,",
  "            )",
  '          : "null"}',
  "      </pre>",
  '      <div className="h-44 overflow-y-auto rounded-lg border border-white/10 bg-slate-900/40 p-4">',
  '        <div className="h-32 text-slate-500">↓</div>',
  "        <div",
  "          ref={ref}",
  '          className="flex h-20 items-center justify-center rounded-lg bg-indigo-950/50 text-indigo-100"',
  "        >",
  "          Observed",
  "        </div>",
  '        <div className="h-32 text-slate-500">↓</div>',
  "      </div>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const isomorphicLayoutEffectFullSource = [
  '"use client";',
  "",
  'import { useIsomorphicLayoutEffect } from "@zentauri-ui/zentauri-components/lib/useIsomorphicLayoutEffect";',
  PANEL_IMPORT,
  'import { useEffect, useRef, useState } from "react";',
  "",
  "export default function HookDemo() {",
  "  const ref = useRef<HTMLDivElement>(null);",
  "  const [layout, setLayout] = useState(0);",
  "  const [effect, setEffect] = useState(0);",
  "",
  "  useIsomorphicLayoutEffect(() => {",
  "    setLayout(ref.current?.offsetHeight ?? 0);",
  "  });",
  "",
  "  useEffect(() => {",
  "    const frame = requestAnimationFrame(() => {",
  "      setEffect(ref.current?.offsetHeight ?? 0);",
  "    });",
  "    return () => cancelAnimationFrame(frame);",
  "  }, []);",
  "",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        After first paint, layout measurement from useIsomorphicLayoutEffect typically",
  "        matches the element; both values are shown for this static box.",
  "      </p>",
  "      <div",
  "        ref={ref}",
  '        className="mb-4 inline-block min-h-[80px] rounded-lg border border-white/10 bg-slate-900/60 px-6 py-4"',
  "      >",
  "        Target box",
  "      </div>",
  '      <dl className="grid gap-1 text-sm sm:grid-cols-2">',
  '        <dt className="text-slate-500">Layout effect height</dt>',
  '        <dd className="font-mono text-cyan-200">{layout}px</dd>',
  '        <dt className="text-slate-500">useEffect height (initial)</dt>',
  '        <dd className="font-mono text-slate-300">{effect}px</dd>',
  "      </dl>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const isMountedFullSource = [
  '"use client";',
  "",
  'import { useIsMounted } from "@zentauri-ui/zentauri-components/lib/useIsMounted";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  'import { useState } from "react";',
  "",
  "export default function HookDemo() {",
  "  const isMounted = useIsMounted();",
  '  const [label, setLabel] = useState("");',
  "",
  "  const run = () => {",
  "    setTimeout(() => {",
  '      setLabel(isMounted() ? "mounted" : "unmounted (after timeout)");',
  "    }, 50);",
  "  };",
  "",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Schedules a timeout then reads the mounted ref — navigate away quickly after",
  "        clicking to see unmounted if you shorten delay in your own tests.",
  "      </p>",
  '      <Button type="button" onClick={run}>',
  "        Check mounted in 50ms",
  "      </Button>",
  "      {label ? (",
  '        <p className="mt-4 text-sm text-white">',
  '          Result: <span className="text-cyan-300">{label}</span>',
  "        </p>",
  "      ) : null}",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const localStorageFullSource = [
  '"use client";',
  "",
  'import { useLocalStorage } from "@zentauri-ui/zentauri-components/lib/useLocalStorage";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  'import { Input } from "@zentauri-ui/zentauri-components/ui/inputs";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  '  const storageKey = "zentauri-ui.hooks.preview.local";',
  "  const [value, setValue, remove] = useLocalStorage(storageKey, \"\");",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-2 text-xs text-slate-500">Key: {storageKey}</p>',
  "      <Input",
  '        appearance="info"',
  "        value={value}",
  "        onChange={(e) => setValue(e.target.value)}",
  '        placeholder="Persisted in localStorage"',
  "      />",
  '      <Button type="button" appearance="outline" onClick={remove}>',
  "        Clear key",
  "      </Button>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const mediaQueryFullSource = [
  '"use client";',
  "",
  'import { useMediaQuery } from "@zentauri-ui/zentauri-components/lib/useMediaQuery";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  '  const narrow = useMediaQuery("(max-width: 640px)");',
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="text-sm text-slate-400">',
  '        <span className="font-medium text-white">(max-width: 640px)</span> matches: ',
  '        <span className={narrow ? "text-emerald-400" : "text-slate-300"}>',
  '          {narrow ? "true" : "false"}',
  "        </span>",
  "        . Resize the window to update.",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const networkStatusFullSource = [
  '"use client";',
  "",
  'import { useNetworkStatus } from "@zentauri-ui/zentauri-components/lib/useNetworkStatus";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const online = useNetworkStatus();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="text-sm text-slate-400">',
  "        Navigator reports: ",
  '        <span className={online ? "text-emerald-400" : "text-rose-400"}>',
  '          {online ? "online" : "offline"}',
  "        </span>",
  "        . Toggle your connection to test.",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const pageVisibilityFullSource = [
  '"use client";',
  "",
  'import { usePageVisibility } from "@zentauri-ui/zentauri-components/lib/usePageVisibility";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const state = usePageVisibility();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="text-sm text-slate-400">',
  '        Current <code className="text-cyan-200">document.visibilityState</code>: ',
  '        <span className="font-mono text-white">{state}</span>. Switch tabs to see it',
  "        change.",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const paginationFullSource = [
  '"use client";',
  "",
  'import { buildPaginationItems, usePagination } from "@zentauri-ui/zentauri-components/lib/usePagination";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const pageCount = 12;",
  "  const { currentPage, items, setPage, goPrev, goNext, canGoPrev, canGoNext } =",
  "    usePagination({",
  "      pageCount,",
  "      defaultPage: 1,",
  "      siblingCount: 1,",
  "      boundaryCount: 1,",
  "    });",
  "  const built = buildPaginationItems({",
  "    pageCount,",
  "    currentPage,",
  "    siblingCount: 1,",
  "    boundaryCount: 1,",
  "  });",
  "",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        usePagination state plus buildPaginationItems for the same window (should",
  '        match <span className="font-mono text-cyan-200">items</span>).',
  "      </p>",
  '      <div className="mb-4 flex flex-wrap items-center gap-2">',
  '        <Button type="button" disabled={!canGoPrev} onClick={goPrev}>',
  "          Prev",
  "        </Button>",
  '        <Button type="button" disabled={!canGoNext} onClick={goNext}>',
  "          Next",
  "        </Button>",
  '        <span className="ml-2 text-sm text-slate-400">',
  "        Page {currentPage} / {pageCount}",
  "        </span>",
  "      </div>",
  '      <div className="mb-4 flex flex-wrap gap-2">',
  "        {items.map((item) =>",
  '          item.type === "ellipsis" ? (',
  '            <span key={item.key} className="px-2 text-slate-500">',
  "              …",
  "            </span>",
  "          ) : (",
  "            <Button",
  "              key={item.value}",
  '              type="button"',
  '              size="sm"',
  '              appearance={item.value === currentPage ? "default" : "outline"}',
  "              onClick={() => setPage(item.value)}",
  "            >",
  "              {item.value}",
  "            </Button>",
  "          ),",
  "        )}",
  "      </div>",
  '      <p className="mb-1 text-xs uppercase tracking-wider text-slate-500">',
  "        buildPaginationItems snapshot",
  "      </p>",
  '      <pre className="max-h-32 overflow-auto rounded-lg border border-white/10 bg-slate-950/80 p-3 text-xs text-slate-300">',
  "        {JSON.stringify(built, null, 2)}",
  "      </pre>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const prefersColorSchemeFullSource = [
  '"use client";',
  "",
  'import { usePrefersColorScheme } from "@zentauri-ui/zentauri-components/lib/usePrefersColorScheme";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  '  const scheme = usePrefersColorScheme("light");',
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="text-sm text-slate-400">',
  "        System color scheme preference: ",
  '        <span className="font-medium text-white">{scheme}</span>. Change OS theme to',
  "        update.",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const prefersReducedMotionFullSource = [
  '"use client";',
  "",
  'import { usePrefersReducedMotion } from "@zentauri-ui/zentauri-components/lib/usePrefersReducedMotion";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const reduce = usePrefersReducedMotion();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="text-sm text-slate-400">',
  '        <code className="text-cyan-200">prefers-reduced-motion: reduce</code> matches: ',
  '        <span className="text-white">{reduce ? "true" : "false"}</span>',
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const resizeObserverFullSource = [
  '"use client";',
  "",
  'import { useResizeObserver } from "@zentauri-ui/zentauri-components/lib/useResizeObserver";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const [setRef, size] = useResizeObserver<HTMLTextAreaElement>();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Drag the textarea corner — content box size updates from ResizeObserver.",
  "      </p>",
  "      <textarea",
  "        ref={setRef}",
  "        rows={3}",
  '        className="min-h-16 w-full max-w-md resize rounded-lg border border-white/15 bg-slate-900/80 p-3 text-sm text-white outline-none focus:border-cyan-500/50"',
  '        defaultValue="Resize me…"',
  "      />",
  '      <p className="mt-4 font-mono text-sm text-cyan-200">',
  "        {size ? `${Math.round(size.width)} × ${Math.round(size.height)} px` : \"—\"}",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const sessionStorageFullSource = [
  '"use client";',
  "",
  'import { useSessionStorage } from "@zentauri-ui/zentauri-components/lib/useSessionStorage";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  'import { Input } from "@zentauri-ui/zentauri-components/ui/inputs";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  '  const storageKey = "zentauri-ui.hooks.preview.session";',
  "  const [value, setValue, remove] = useSessionStorage(storageKey, \"\");",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-2 text-xs text-slate-500">Key: {storageKey}</p>',
  "      <Input",
  '        appearance="info"',
  "        value={value}",
  "        onChange={(e) => setValue(e.target.value)}",
  '        placeholder="Persists for this tab session"',
  "      />",
  '      <Button type="button" appearance="outline" onClick={remove}>',
  "        Clear key",
  "      </Button>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const throttledCallbackFullSource = [
  '"use client";',
  "",
  'import { useThrottledCallback } from "@zentauri-ui/zentauri-components/lib/useThrottledCallback";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  'import { useState } from "react";',
  "",
  "export default function HookDemo() {",
  "  const [count, setCount] = useState(0);",
  "  const onBurst = useThrottledCallback(() => {",
  "    setCount((c) => c + 1);",
  "  }, 500);",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  "        Clicks are throttled to at most one handled call per 500ms.",
  "      </p>",
  '      <Button type="button" onClick={onBurst}>',
  "        Click rapidly",
  "      </Button>",
  '      <p className="mt-4 text-sm text-slate-400">',
  "        Handler invocations: ",
  '        <span className="text-2xl font-semibold text-white">{count}</span>',
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const toggleFullSource = [
  '"use client";',
  "",
  'import { useToggle } from "@zentauri-ui/zentauri-components/lib/useToggle";',
  'import { Button } from "@zentauri-ui/zentauri-components/ui/buttons";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const [on, toggle, set] = useToggle(false);",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="mb-4 text-sm text-slate-400">',
  '        State: <span className="text-white">{on ? "on" : "off"}</span>',
  "      </p>",
  '      <div className="flex flex-wrap gap-2">',
  '        <Button type="button" onClick={toggle}>',
  "          Toggle",
  "        </Button>",
  '        <Button type="button" appearance="outline" onClick={() => set(true)}>',
  "          Set on",
  "        </Button>",
  '        <Button type="button" appearance="outline" onClick={() => set(false)}>',
  "          Set off",
  "        </Button>",
  "      </div>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

const windowSizeFullSource = [
  '"use client";',
  "",
  'import { useWindowSize } from "@zentauri-ui/zentauri-components/lib/useWindowSize";',
  PANEL_IMPORT,
  "",
  "export default function HookDemo() {",
  "  const { width, height } = useWindowSize();",
  "  return (",
  '    <HookDemoPanel title="Interactive demo">',
  '      <p className="text-sm text-slate-400">',
  "        Window inner size: ",
  '        <span className="font-mono text-cyan-200">',
  "        {width} × {height}",
  "        </span>",
  "        px — resize the browser to update.",
  "      </p>",
  "    </HookDemoPanel>",
  "  );",
  "}",
].join("\n");

export const HOOK_DEMO_FULL_SOURCES: Record<HookPreviewSlug, string> = {
  "use-body-scroll-lock": bodyScrollLockFullSource,
  "use-click-outside": clickOutsideFullSource,
  "use-clipboard": clipboardFullSource,
  "use-controllable-state": controllableStateFullSource,
  "use-debounced-value": debouncedValueFullSource,
  "use-disclosure": disclosureFullSource,
  "use-document-title": documentTitleFullSource,
  "use-focus-management": focusManagementFullSource,
  "use-hover": hoverFullSource,
  "use-in-view": inViewFullSource,
  "use-intersection-observer": intersectionObserverFullSource,
  "use-isomorphic-layout-effect": isomorphicLayoutEffectFullSource,
  "use-is-mounted": isMountedFullSource,
  "use-local-storage": localStorageFullSource,
  "use-media-query": mediaQueryFullSource,
  "use-network-status": networkStatusFullSource,
  "use-page-visibility": pageVisibilityFullSource,
  "use-pagination": paginationFullSource,
  "use-prefers-color-scheme": prefersColorSchemeFullSource,
  "use-prefers-reduced-motion": prefersReducedMotionFullSource,
  "use-resize-observer": resizeObserverFullSource,
  "use-session-storage": sessionStorageFullSource,
  "use-throttled-callback": throttledCallbackFullSource,
  "use-toggle": toggleFullSource,
  "use-window-size": windowSizeFullSource,
};

export function getHookDemoFullSource(slug: HookPreviewSlug): string {
  return HOOK_DEMO_FULL_SOURCES[slug];
}
